### ISSUE TITLE
Errors when loading  GEMINI files produced by the pipeline

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#143]
It looks like one of the runs produced non-functional GEMINI files:

```
gemini interactions Sample_174-varscan.db 
Traceback (most recent call last):
  File "/usr/bin/gemini", line 5, in <module>
    pkg_resources.run_script('gemini==0.6.3a', 'gemini')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 492, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1350, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/gemini-0.6.3a-py2.7.egg/EGG-INFO/scripts/gemini", line 5, in <module>
    gemini.gemini_main.main()
  File "/usr/lib/python2.7/site-packages/gemini-0.6.3a-py2.7.egg/gemini/gemini_main.py", line 748, in main
    args.func(parser, args)
  File "/usr/lib/python2.7/site-packages/gemini-0.6.3a-py2.7.egg/gemini/tool_interactions.py", line 285, in genequery
    sample_variants(c, args)
  File "/usr/lib/python2.7/site-packages/gemini-0.6.3a-py2.7.egg/gemini/tool_interactions.py", line 231, in sample_variants
    idx_to_sample = util.map_indicies_to_samples(c)
  File "/usr/lib/python2.7/site-packages/gemini-0.6.3a-py2.7.egg/gemini/gemini_utils.py", line 24, in map_indicies_to_samples
    c.execute("select sample_id, name from samples")
sqlite3.OperationalError: no such table: samples
```

In fact, there is no `samples` table in the SQLite database (checked with the command line sqlite3). 
I'm running another analysis to be sure.

**Comment by RatnamRaju** [comment]
[root@localhost home]# gemini -v
Traceback (most recent call last):
  File "/usr/bin/gemini", line 4, in <module>
    import pkg_resources
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2659, in <module>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: numexpr>=2.4.3
