### ISSUE TITLE
Cannot find sambamba

### ISSUE THREAD

**Issue by pengxiao78** [bcbio/bcbio-nextgen#1886]
Hi,
I was running bcbio exome-seq pipeline and found the following error. Could you help me debug?
Thanks!

[2017-04-04T22:44Z] c2607.***.edu: Aligning lane 34_2017-04-04_24th_s-merged with bwa aligner
[2017-04-04T22:49Z] c2915.***.edu: ipython: delayed_bam_merge
[2017-04-04T22:49Z] c2921.***.edu: Unexpected error
Traceback (most recent call last):
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 235, in delayed_bam_merge
    return ipython.zip_args(apply(sample.delayed_bam_merge, *args))
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 295, in delayed_bam_merge
    out_file=cur_out_file)
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/merge.py", line 63, in merge_bam_files
    sambamba = config_utils.get_program("sambamba", config)
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/config_utils.py", line 188, in get_program
    return _get_program_cmd(name, pconfig, config, default)
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/config_utils.py", line 214, in wrap
    raise CmdNotFound(" ".join(map(repr, (fn.func_name, name, pconfig, default))))
CmdNotFound: '_get_program_cmd' 'sambamba' {} None

**Comment by chapmanb** [comment]
Sorry about the issues. Normally this occurs when you don't have the bin directory of tools installed by bcbio in your PATH, which you can do with `export PATH`:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#automated

Hopefully doing that will get things running. Happy to debug more if you've already done this and can provide additional details. Thanks much.

**Comment by pengxiao78** [comment]
I have done that long time ago. However, this error just came out today. I did not meet any problem like this previously. However, I did upgrade bcbio recently before ran this. Do you think that it has any problem with the upgrade. Thanks!

**Comment by chapmanb** [comment]
It's a bit hard for me to remotely debug further with the details you've provided. bcbio upgrades didn't intentionally remove sambamba but the run indicates it's missing from your PATH, so it's possible either you no longer have the right directory in your PATH or sambamba got removed somehow. Here's my suggestion for checking:

- If you type `sambamba` on the command line, is it found?
- Is the path to `sambamba` installed with bcbio set correctly if you do `echo $PATH`?
- If `sambamba` is missing, does `bcbio_conda install -c bioconda sambamba` or `bcbio_nextgen.py upgrade --tools` reinstall it?

Hope this helps.

**Comment by pengxiao78** [comment]
Yes, sambamba was found  and when I typed "which sambamba", it gave me the correct path
/path/to/bcbio/anaconda/bin/sambamba . echo $PATH also gave the correct path. Should I do bcbio_conda install -c bioconda sambamba or bcbio_nextgen.py upgrade --tools reinstall it? Thanks.

**Comment by pengxiao78** [comment]
sambamba is missing and I used bcbio_conda install -c bioconda sambamba to reinstall it. The running is back to normal now. Thanks!

**Comment by roryk** [comment]
Thanks, we fixed a bunch of these problems where we weren't looking up the full path, so I doubt this is a problem anymore.
