### ISSUE TITLE
ValueError: Could not find reference genome file GRCh37 samtools

### ISSUE THREAD

**Issue by jich-MCTP** [bcbio/bcbio-nextgen#1903]
Hi, 
After I install reference file using command line:
bcbio_nextgen.py upgrade --data --genomes GRCh37 --aligners bwa --aligners bowtie2, 
I try to run the example of Cancer tumor normal.
run bcbio_nextgen.py ../config/cancer-dream-syn3.yaml -n 8, I get the error:
ValueError: Could not find reference genome file GRCh37 samtools

The whole message is:
bcbio_nextgen.py ../config/cancer-dream-syn3.yaml -n 8
[2017-04-17T13:35Z] System YAML configuration: /bcbio/data/test/cancer-dream-syn3/work/bcbio_system-merged.yaml
[2017-04-17T13:35Z] Resource requests: bwa, sambamba, samtools; memory: 3.00, 3.00, 3.00; cores: 16, 16, 16
[2017-04-17T13:35Z] Configuring 1 jobs to run, using 8 cores each with 24.1g of memory reserved for each job
[2017-04-17T13:35Z] Timing: organize samples
[2017-04-17T13:35Z] multiprocessing: organize_samples
[2017-04-17T13:35Z] Using input YAML configuration: /bcbio/data/test/cancer-dream-syn3/config/cancer-dream-syn3.yaml
[2017-04-17T13:35Z] Checking sample YAML configuration: /bcbio/data/test/cancer-dream-syn3/config/cancer-dream-syn3.yaml
[2017-04-17T13:35Z] Downloading GRCh37 samtools from AWS
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 119, in variant2pipeline
    [x[0]["description"] for x in samples]]])
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 350, in organize_samples
    return run_info.organize(*args)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 69, in organize
    item = add_reference_resources(item, remote_retriever)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 161, in add_reference_resources
    data["reference"] = genome.get_refs(data["genome_build"], aligner, data["dirs"]["galaxy"], data)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 219, in get_refs
    galaxy_config, data)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 171, in _get_ref_from_galaxy_loc
    cur_ref = download_prepped_genome(genome_build, data, name, need_remap)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 292, in download_prepped_genome
    raise ValueError("Could not find reference genome file %s %s" % (genome_build, name))
ValueError: Could not find reference genome file GRCh37 samtools

I check the folder :/usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37. all reference files are at there.

**Comment by jich-MCTP** [comment]
in the folder: /usr/local/share/bcbio-nextgen/galaxy/tool-data
run cat *.loc and get:
GRCh37  GRCh37  Human (GRCh37)  /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/bowtie2/GRCh37
hg38    hg38    Human (hg38) full       /usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg38/bowtie2/hg38
GRCh37  GRCh37  Human (GRCh37)  /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa
hg38    hg38    Human (hg38) full       /usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg38/bwa/hg38.fa
GRCh37  GRCh37  Human (GRCh37)  /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/seq/GRCh37.fa
hg38    hg38    Human (hg38) full       /usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg38/seq/hg38.fa
GRCh37  GRCh37  Human (GRCh37)  /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/seq/GRCh37.fa
hg38    hg38    Human (hg38) full       /usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg38/seq/hg38.fa
index   GRCh37  /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/seq/GRCh37.fa
index   hg38    /usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg38/seq/hg38.fa

I check all files in the loc file. All reference files are there.

**Comment by chapmanb** [comment]
Jin;
Sorry about the issues and thank you for the detailed report. I suspect something confusing is happening here with your use of Docker. It looks like you might be mixing use of bcbio_vm.py and bcbio_nextgen.py, as I see the run uses `bcbio_system-merged.yaml`. It's likely that points to a different set of genomes as bcbio_vm.py stores the genome data outside of the Docker container. Is it possible your update has some data inside and other outside the container?

Do you need to use Docker here or could you install bcbio isolated on your system? We're actively working to make Docker usage cleaner via the Common Workflow Language (http://bcbio-nextgen.readthedocs.io/en/latest/contents/cwl.html) and will probably be replacing the custom bcbio_vm.py and single large Docker container approach in the future. 

The Docker parts are just in a lot of transition and more complex, so an isolated install might get you a cleaner path to running bcbio successfully. Hope this helps.

**Comment by roryk** [comment]
Stale, and should be working now so closing. Thanks!
