### ISSUE TITLE
CNVKit: Reference is missing 155434 bins 

### ISSUE THREAD

**Issue by NeillGibson** [bcbio/bcbio-nextgen#1933]
Hi,

I am trying to use CNVKit to call copy number variants in a population of 100 WGS samples. Reference genome size is ca 200MB, depth per sample varies 9X and 85X, average is 34X. Some samples have 100 bp PE reads, other 125bp PE reads. 

I am using bcbio 1.0.3a and this is my YAML:

```
# Template for whole genome Illumina variant calling with FreeBayes
# This is a GATK-free pipeline without post-alignment BAM pre-processing
# (recalibration and realignment)
---
details:
  - analysis: variant2
    genome_build: my_genome
    description:
    # to do multi-sample variant calling, assign samples the same metadata / batch
    metadata:
      batch: Project_123_CNVKit
    algorithm:
      aligner: false
      mark_duplicates: false
      recalibrate: false
      realign: false
      svcaller: cnvkit
      ploidy:
          default: 2
      nomap_split_targets: 3000
      effects: false
      tools_off:
      - gemini
      # for targetted projects, set the region
      # variant_regions: /path/to/your.bed
```

I get the following CNVKit log and the error at the end. 

I am kind of new to calling copy number variattions and using CNVKit. Does the above yaml make sense and is is possible to use CNVKit within bcbio to analyze a batch of 100 WGS samples?

Should I adjust some parameters like bin size to make this work?

How can I avoid the `Reference is missing 155434 bins`  error? I am running the analysis starting from BAM files and checked that the bam file and reference are compatible (i.e. bam header SQ lenght and fa.fai lenght entries match. ). 

Thank you. 

```
[2017-05-16T01:37Z] CNVkit background
[2017-05-16T01:37Z] Detected file format: bed
[2017-05-16T01:37Z] Calculating GC and RepeatMasker content in /data/prod/Tools/bcbio/latest/genomes/my_genome/my_genome/seq/my_genome.fa ..
.
[2017-05-16T01:37Z] Extracting sequences from chromosome Chr_01
[2017-05-16T01:37Z] Extracting sequences from chromosome Chr_02
[2017-05-16T01:37Z] Extracting sequences from chromosome Chr_03
[2017-05-16T01:37Z] Extracting sequences from chromosome Chr_04
[2017-05-16T01:37Z] Extracting sequences from chromosome Chr_05
[2017-05-16T01:37Z] Extracting sequences from chromosome Chr_06
[2017-05-16T01:37Z] Extracting sequences from chromosome Chr_07
[2017-05-16T01:37Z] Wrote /data/run/Projects/Organism/Project-945/CNVKit/Project_756_bam_table/work/bcbiotx/tmp7on8JT/ProviderX_701_03_background.cnn with 187646 regions
[2017-05-16T01:37Z] Resource requests: cnvkit; memory: 3.00; cores: 10
[2017-05-16T01:37Z] Configuring 1 jobs to run, using 10 cores each with 30.1g of memory reserved for each job
[2017-05-16T01:37Z] CNVkit fix
[2017-05-16T01:38Z] Processing target: ProviderX_601_01-ready-Project_756
[2017-05-16T01:38Z] Keeping 187646 of 187646 bins
[2017-05-16T01:38Z] Correcting for GC bias...
[2017-05-16T01:38Z] Correcting for density bias...
[2017-05-16T01:38Z] Processing antitarget: ProviderX_601_01-ready-Project_756
[2017-05-16T01:38Z] Wrote /data/run/Projects/Organism/Project-945/CNVKit/Project_756_bam_table/work/bcbiotx/tmp_3j6sG/ProviderX_601_01-ready-Project_756.cnr with 187646 regions
[2017-05-16T01:38Z] CNVkit segment
[2017-05-16T01:38Z] Dropped 6 outlier bins:
[2017-05-16T01:38Z]   chromosome     start       end gene     log2        depth    weight
[2017-05-16T01:38Z] 0     Chr_04     43875     44872    -  3.82126   594.507000  0.665554
[2017-05-16T01:38Z] 1     Chr_04   3768574   3769577    -  4.71662  1107.270000  0.669559
[2017-05-16T01:38Z] 2     Chr_04  14962860  14963851    -  4.98888  1267.650000  0.661549
[2017-05-16T01:38Z] 3     Chr_04  19813663  19813919    - -5.78114     0.671875  0.170895
[2017-05-16T01:38Z] 4     Chr_04  21851750  21852747    -  6.08524  2786.990000  0.665554
[2017-05-16T01:38Z] 5     Chr_04  22659059  22660058    -  4.98365  1337.320000  0.666889
[2017-05-16T01:38Z] Dropped 9 outlier bins:
[2017-05-16T01:38Z]   chromosome     start       end gene     log2        depth    weight
[2017-05-16T01:38Z] 0     Chr_02   2284274   2285278    -  5.18663  1418.500000  0.670227
[2017-05-16T01:38Z] 1     Chr_02   5373320   5374325    -  4.32901   777.542000  0.670895
[2017-05-16T01:38Z] 2     Chr_02   5729794   5730039    - -5.83922     0.738776  0.163551
[2017-05-16T01:38Z] 3     Chr_02   6635560   6636565    -  4.50737   947.006000  0.670895
[2017-05-16T01:38Z] 4     Chr_02   7422936   7422977    - -5.27897     1.000000  0.027370
[2017-05-16T01:38Z] 5     Chr_02  16275183  16276178    -  4.73816  1096.160000  0.664219
[2017-05-16T01:38Z] 6     Chr_02  17861712  17862713    -  5.42750  1728.420000  0.668224
[2017-05-16T01:38Z] 7     Chr_02  19148604  19149603    -  5.93644  2544.380000  0.666889
[2017-05-16T01:38Z] 8     Chr_02  21269849  21270056    - -6.54394     0.405797  0.138184
[2017-05-16T01:38Z] Dropped 4 outlier bins:
[2017-05-16T01:38Z]   chromosome     start       end gene     log2     depth    weight
[2017-05-16T01:38Z] 0     Chr_05   6710716   6711711    -  5.26742  1612.370  0.664219
[2017-05-16T01:38Z] 1     Chr_05   6904285   6905286    -  4.31289   835.528  0.668224
[2017-05-16T01:38Z] 2     Chr_05  18637921  18638916    -  5.65862  2121.810  0.664219
[2017-05-16T01:38Z] 3     Chr_05  24385842  24386835    -  4.61168  1028.460  0.662884
[2017-05-16T01:38Z] Dropped 10 outlier bins:
[2017-05-16T01:38Z]   chromosome     start       end gene     log2        depth    weight
[2017-05-16T01:38Z] 0     Chr_03   1288798   1289799    -  5.89180  2385.410000  0.668224
[2017-05-16T01:38Z] 1     Chr_03   1492974   1493971    -  4.47154   913.139000  0.665554
[2017-05-16T01:38Z] 2     Chr_03   4227015   4228014    -  5.08963  1369.540000  0.666889
[2017-05-16T01:38Z] 3     Chr_03  12813615  12814624    -  4.43577   864.906000  0.673565
[2017-05-16T01:38Z] 4     Chr_03  17191216  17191442    - -6.32083     0.530973  0.150868
[2017-05-16T01:38Z] 5     Chr_03  18034323  18035337    -  3.27861   401.201000  0.676903
[2017-05-16T01:38Z] 6     Chr_03  24316966  24317958    -  5.94889  2615.860000  0.662216
[2017-05-16T01:38Z] 7     Chr_03  28343571  28344573    -  4.12480   643.906000  0.668892
[2017-05-16T01:38Z] 8     Chr_03  29374854  29374900    - -5.35189     1.000000  0.030708
[2017-05-16T01:38Z] 9     Chr_03  34650526  34651514    -  5.83752  2409.550000  0.659546
[2017-05-16T01:38Z] Dropped 8 outlier bins:
[2017-05-16T01:38Z]   chromosome     start       end gene     log2     depth    weight
[2017-05-16T01:38Z] 0     Chr_01   6853606   6853636    - -5.19398     1.000  0.020027
[2017-05-16T01:38Z] 1     Chr_01   9384097   9385096    -  3.58383   510.999  0.666889
[2017-05-16T01:38Z] 2     Chr_01  12859336  12859774    -  6.31799  3390.130  0.292390
[2017-05-16T01:38Z] 3     Chr_01  15806879  15807886    -  4.46807   903.364  0.672230
[2017-05-16T01:38Z] 4     Chr_01  19948931  19949931    -  5.05138  1383.190  0.667557
[2017-05-16T01:38Z] 5     Chr_01  20844956  20845956    -  4.53715   933.929  0.667557
[2017-05-16T01:38Z] 6     Chr_01  23036061  23037058    -  4.67662  1074.430  0.665554
[2017-05-16T01:38Z] 7     Chr_01  25571584  25571607    - -5.19406     1.000  0.015354
[2017-05-16T01:38Z] Dropped 7 outlier bins:
[2017-05-16T01:38Z]   chromosome     start       end gene     log2        depth    weight
[2017-05-16T01:38Z] 0     Chr_07   3175442   3175533    - -5.40440     1.000000  0.060748
[2017-05-16T01:38Z] 1     Chr_07   7624629   7625411    -  4.53094   984.240000  0.522029
[2017-05-16T01:38Z] 2     Chr_07   8946397   8946398    -  6.27048  2826.000000  0.000668
[2017-05-16T01:38Z] 3     Chr_07   9690619   9690865    - -6.25141     0.556911  0.164219
[2017-05-16T01:38Z] 4     Chr_07  14884535  14885535    -  5.32291  1689.060000  0.667557
[2017-05-16T01:38Z] 5     Chr_07  15825118  15826121    -  4.88396  1200.100000  0.669559
[2017-05-16T01:38Z] 6     Chr_07  18109673  18110672    -  4.77358  1135.280000  0.666889
[2017-05-16T01:38Z] Dropped 9 outlier bins:
[2017-05-16T01:38Z]   chromosome     start       end gene     log2     depth    weight
[2017-05-16T01:38Z] 0     Chr_06   2021674   2022670    -  4.42288   906.738  0.664887
[2017-05-16T01:38Z] 1     Chr_06   5240098   5241101    -  4.89400  1159.750  0.669559
[2017-05-16T01:38Z] 2     Chr_06   6877458   6878460    -  5.57360  2013.810  0.668892
[2017-05-16T01:38Z] 3     Chr_06   8738273   8739273    -  4.84077  1212.390  0.667557
[2017-05-16T01:38Z] 4     Chr_06  16535804  16536806    -  6.13019  2833.090  0.668892
[2017-05-16T01:38Z] 5     Chr_06  20284285  20285280    -  3.60832   507.778  0.664219
[2017-05-16T01:38Z] 6     Chr_06  22816075  22817073    -  5.48555  1664.030  0.666222
[2017-05-16T01:38Z] 7     Chr_06  23621405  23622405    -  5.39556  1752.040  0.667557
[2017-05-16T01:38Z] 8     Chr_06  23834016  23834044    - -5.19636     1.000  0.018692
[2017-05-16T01:38Z] Wrote /data/run/Projects/Organism/Project-945/CNVKit/Project_756_bam_table/work/bcbiotx/tmpRXnmhE/ProviderX_601_01-ready-Project_756.cns with 42 regions
[2017-05-16T01:38Z] Sort and merge BED file : ProviderX_701_03
[2017-05-16T01:38Z] CNVkit coverage bin estimation
[2017-05-16T01:39Z] Targets will be ignored: /data/run/Projects/Organism/Project-945/CNVKit/Project_756_bam_table/work/structural/ProviderX_701_03/cnvkit/ProviderX_701_03-coverage.callable-vrsubset-callableblocks-sortmerge.bed
[2017-05-16T01:39Z] CNVkit target
[2017-05-16T01:39Z] Detected file format: bed
[2017-05-16T01:39Z] Splitting large targets
[2017-05-16T01:39Z] Wrote /data/run/Projects/Organism/Project-945/CNVKit/Project_756_bam_table/work/bcbiotx/tmprpaXYo/ProviderX_701_03-coverage.callable-vrsubset-callableblocks-sortmerge-Project_756.target.bed with 187565 regions
[2017-05-16T01:39Z] CNVkit antitarget
[2017-05-16T01:39Z] Detected file format: bed
[2017-05-16T01:39Z] Detected file format: bed
[2017-05-16T01:40Z] Wrote /data/run/Projects/Organism/Project-945/CNVKit/Project_756_bam_table/work/bcbiotx/tmp2HgA1N/ProviderX_701_03-coverage.callable-vrsubset-callableblocks-sortmerge-Project_756.antitarget.bed with 0 regions
[2017-05-16T01:40Z] CNVkit background
[2017-05-16T01:40Z] Detected file format: bed
[2017-05-16T01:40Z] Calculating GC and RepeatMasker content in /data/prod/Tools/bcbio/latest/genomes/my_genome/my_genome/seq/my_genome.fa ...
[2017-05-16T01:40Z] Extracting sequences from chromosome Chr_01
[2017-05-16T01:40Z] Extracting sequences from chromosome Chr_02
[2017-05-16T01:40Z] Extracting sequences from chromosome Chr_03
[2017-05-16T01:40Z] Extracting sequences from chromosome Chr_04
[2017-05-16T01:40Z] Extracting sequences from chromosome Chr_05
[2017-05-16T01:40Z] Extracting sequences from chromosome Chr_06
[2017-05-16T01:40Z] Extracting sequences from chromosome Chr_07
[2017-05-16T01:40Z] Wrote /data/run/Projects/Organism/Project-945/CNVKit/Project_756_bam_table/work/bcbiotx/tmpWv8gEh/ProviderX_601_01_background.cnn with 187565 regions
[2017-05-16T01:40Z] Resource requests: cnvkit; memory: 3.00; cores: 10
[2017-05-16T01:40Z] Configuring 1 jobs to run, using 10 cores each with 30.1g of memory reserved for each job
[2017-05-16T01:40Z] CNVkit fix
[2017-05-16T01:40Z] Processing target: ProviderX_701_03-ready-Project_756
[2017-05-16T01:41Z] Traceback (most recent call last):
[2017-05-16T01:41Z]   File "/data/prod/Tools/bcbio/latest/anaconda/bin/cnvkit.py", line 13, in <module>
[2017-05-16T01:41Z]     args.func(args)
[2017-05-16T01:41Z]   File "/data/prod/Tools/bcbio/latest/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 553, in _cmd_fix
[2017-05-16T01:41Z]     args.do_gc, args.do_edge, args.do_rmask)
[2017-05-16T01:41Z]   File "/data/prod/Tools/bcbio/latest/anaconda/lib/python2.7/site-packages/cnvlib/fix.py", line 19, in do_fix
[2017-05-16T01:41Z]     do_gc, do_edge, False)
[2017-05-16T01:41Z]   File "/data/prod/Tools/bcbio/latest/anaconda/lib/python2.7/site-packages/cnvlib/fix.py", line 53, in load_adjust_coverages
[2017-05-16T01:41Z]     ref_matched = match_ref_to_sample(ref_cnarr, cnarr)
[2017-05-16T01:41Z]   File "/data/prod/Tools/bcbio/latest/anaconda/lib/python2.7/site-packages/cnvlib/fix.py", line 123, in match_ref_to_sample
[2017-05-16T01:41Z]     % (num_missing, samp_cnarr.sample_id))
[2017-05-16T01:41Z] ValueError: Reference is missing 155434 bins found in ProviderX_701_03-ready-Project_756
[2017-05-16T01:41Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/data/prod/Tools/bcbio/latest/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/data/prod/Tools/bcbio/latest/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; export TMPDIR=/data/run/Projects/Organism/Project-945/CNVKit/Project_756_bam_table/work/bcbiotx/tmplBSk1k && /data/prod/Tools/bcbio/latest/anaconda/bin/cnvkit.py fix -o /data/run/Projects/Organism/Project-945/CNVKit/Project_756_bam_table/work/bcbiotx/tmplBSk1k/ProviderX_701_03-ready-Project_756.cnr /data/run/Projects/Organism/Project-945/CNVKit/Project_756_bam_table/work/structural/ProviderX_701_03/cnvkit/raw/ProviderX_701_03-ready-Project_756.targetcoverage.cnn /data/run/Projects/Organism/Project-945/CNVKit/Project_756_bam_table/work/structural/ProviderX_701_03/cnvkit/raw/ProviderX_701_03-ready-Project_756.antitargetcoverage.cnn /data/run/Projects/Organism/Project-945/CNVKit/Project_756_bam_table/work/structural/ProviderX_701_03/cnvkit/raw/ProviderX_601_01_background.cnn
Processing target: ProviderX_701_03-ready-Project_756
Traceback (most recent call last):
  File "/data/prod/Tools/bcbio/latest/anaconda/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/data/prod/Tools/bcbio/latest/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 553, in _cmd_fix
    args.do_gc, args.do_edge, args.do_rmask)
  File "/data/prod/Tools/bcbio/latest/anaconda/lib/python2.7/site-packages/cnvlib/fix.py", line 19, in do_fix
    do_gc, do_edge, False)
  File "/data/prod/Tools/bcbio/latest/anaconda/lib/python2.7/site-packages/cnvlib/fix.py", line 53, in load_adjust_coverages
    ref_matched = match_ref_to_sample(ref_cnarr, cnarr)
  File "/data/prod/Tools/bcbio/latest/anaconda/lib/python2.7/site-packages/cnvlib/fix.py", line 123, in match_ref_to_sample
    % (num_missing, samp_cnarr.sample_id))
ValueError: Reference is missing 155434 bins found in ProviderX_701_03-ready-Project_756
' returned non-zero exit status 1

```

**Comment by chapmanb** [comment]
Neill;
From the bcbio side it looks like you specified everything correctly, but I'm not sure what does wrong with the CNVkit fix step. I'll have to page @etal  Eric does this error point you in a useful direction to help debug further? Happy to investigate if there is something bcbio does wrong to cause this.

**Comment by etal** [comment]
Sorry for the trouble. It looks like the CNVkit part of the pipeline worked for one sample, but then failed on the next. Relatedly, it would be reasonable to construct two separate references, one for 100bp-read samples and another for 125bp.

In general that `ValueError` means a reference was generated from bins other than the `.targetcoverage.cnn` and `.antitargetcoverage.cnn` that it's being compared to at that step. I'll have to look into the bcbio workflow a little more.

**Comment by roryk** [comment]
This is old and bcbio and cnvkit have been updated a ton, so it is unlikely this problem still exists, closing.
