### ISSUE TITLE
 seq2c.py assert len(svouts) == 1

### ISSUE THREAD

**Issue by apastore** [bcbio/bcbio-nextgen#1957]
Hi Brad, sorry! I have add seq2C and now I am receiving this error. 

(aslo I have noticed that cnvkit do not output the vcf files (anymore?))
thanks a lot for all your help!

[2017-05-26T23:33Z] gpu-2-12.local: Unexpected error
Traceback (most recent call last):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 386, in detect_sv
    return ipython.zip_args(apply(structural.detect_sv, *args))
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 191, in detect_sv
    for svdata in caller_fn(items):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/seq2c.py", line 65, in run
    coverage_file = _combine_coverages(items, work_dir)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/seq2c.py", line 281, in _combine_coverages
    assert len(svouts) == 1
AssertionError
2017-05-26 19:33:20.553 [IPClusterStop] Using existing profile dir: u'/cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/log/ipython'
2017-05-26 19:33:20.579 [IPClusterStop] Stopping cluster [pid=7943] with [signal=2]
2017-05-26 19:33:22.836 [IPClusterStop] Using existing profile dir: u'/cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/log/ipython'
2017-05-26 19:33:22.844 [IPClusterStop] Stopping cluster [pid=7943] with [signal=2]
16 Engines running
Sending a shutdown signal to the controller and engines.
256 Engines running
Sending a shutdown signal to the controller and engines.
16 Engines running
Sending a shutdown signal to the controller and engines.
Traceback (most recent call last):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 177, in variant2pipeline
    samples = structural.run(samples, run_parallel, "standard")
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 172, in run
    for xs in to_process.values()))
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipython.py", line 136, in run
    for data in view.map_sync(fn, items, track=False):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 353, in map_sync
    return self.map(f,*sequences,**kwargs)
  File "<decorator-gen-139>", line 2, in map
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 54, in sync_results
    ret = f(self, *args, **kwargs)
  File "<decorator-gen-138>", line 2, in map
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 39, in save_ids
    ret = f(self, *args, **kwargs)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 1119, in map
    return pf.map(*sequences)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 268, in map
    ret = self(*sequences)
  File "<decorator-gen-118>", line 2, in __call__
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 75, in sync_view_results
    return f(self, *args, **kwargs)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 251, in __call__
    return r.get()
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/asyncresult.py", line 104, in get
    raise self._exception
ipyparallel.error.CompositeError: one or more exceptions from call to method: detect_sv
[10:apply]: AssertionError:

**Comment by roryk** [comment]
Thanks, seq2c has been updated a bunch to fix these issues, so should be fixed now.
