### ISSUE TITLE
Kept encountering Error during age-metasv package installation

### ISSUE THREAD

**Issue by jhangyu** [bcbio/bcbio-nextgen#2008]
Hi, I kept receiving the 

> OSError: [Errno 22] Invalid argument: '/home/jhangyu/anaconda/bin/age_align'

while installing the age-metasv package through this install command:
> python bcbio_nextgen_install.py ~ --tooldir=~/anaconda --cores 22 

And so the installation process was interrupted
Could you help me to fix it?
Here is the full error message:

[localhost] local: /home/user/anaconda/bin/conda list --json -f age-metasv
Traceback (most recent call last):
  File "/home/user/anaconda/bin/bcbio_nextgen.py", line 215, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/home/user/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 80, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/home/user/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 433, in upgrade_thirdparty_tools
    cbl_deploy.deploy(s)
  File "/home/user/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/home/user/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/home/user/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 257, in configure_instance
    install_biolinux(options)
  File "/home/user/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 281, in install_biolinux
    _perform_install(target=target, flavor=flavor, more_custom_add=options.get("custom_add", None))
  File "/home/user/tmpbcbio-install/cloudbiolinux/fabfile.py", line 120, in _perform_install
    install_conda(flavor=flavor, automated=True)
  File "/home/user/tmpbcbio-install/cloudbiolinux/fabfile.py", line 321, in install_conda
    conda.install_packages(env, to_install=pkg_install)
  File "/home/user/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 42, in install_packages
    _link_bin(package, env, conda_info, conda_bin)
  File "/home/user/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 76, in _link_bin
    os.path.join(final_bindir, "%s%s" % (prefix, fname)))
  File "/home/user/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 88, in _do_link
    orig_file == os.path.normpath(os.path.join(os.path.dirname(final_file), os.readlink(final_file)))):
OSError: [Errno 22] Invalid argument: '/home/user/anaconda/bin/age_align'
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 251, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/home/user/anaconda/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/user/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=~/anaconda', '--cores', '22', '--data']' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Sorry about the issue, it looks like something is off with resolving your home directory with `~` on your system. I see references to both `/home/user` and `/home/jhangyu` in your error output. I'd suggest using the full path to your install and tool directory on the commandline:
```
python bcbio_nextgen_install.py /home/jhangyu --tooldir=/home/jhangyu/anaconda --cores 22
```
Hope this fixes it for you.

**Comment by jhangyu** [comment]
Thanks for the quick reply! 
I'll try it! Thanks!

**Comment by jhangyu** [comment]
Hi,
I've tried the command:

> python bcbio_nextgen_install.py /home/jhangyu --tooldir=/home/jhangyu/anaconda --cores 22

but still get the same error message:

> OSError: [Errno 22] Invalid argument: '/home/jhangyu/anaconda/bin/age_align'

here is the [full error message](https://pastebin.com/SuhQdh4P)

Thanks for helping!

**Comment by chapmanb** [comment]
Thanks for testing that out. Apologies, I don't know what is going on here. Could you try removing `/home/jhangyu/anaconda` and then re-running? I'm not sure if there is something cached from the previous run that could cause issues.

If this still causes issues, could you do a `ls -lh /home/jhangyu/anaconda/bin/age_align`? That might help me see what is going on with that file that is confusing the `os` package. Thanks much for the help debugging.

**Comment by roryk** [comment]
Installation issue that is very old and very unlikely to be a problem still, so closing.
