### ISSUE TITLE
The remote end hung up unexpectedly

### ISSUE THREAD

**Issue by saxejeffreyd** [bcbio/bcbio-nextgen#207]
I'm attempting to install bcbio-nextgen.  It goes through quite a bit, but then I see:

Requirement already satisfied (use --upgrade to upgrade): ecdsa in /opt/az/local/bcbio-nextgen/use_wget/installdir/anaconda/lib/python2.7/site-packages (from paramiko>=1.10.0->fabric>=1.7.0->-r https://raw.github.com/chapmanb/bcbio-nextgen/master/requirements.txt (line 6))
Cleaning up...
Installing data and third party dependencies
Upgrading third party tools to latest versions
Cloning into 'cloudbiolinux'...
remote: Counting objects: 8294, done.
error: RPC failed; result=18, HTTP code = 200  
fatal: The remote end hung up unexpectedly
fatal: protocol error: bad pack header
Traceback (most recent call last):
  File "/opt/az/local/bcbio-nextgen/use_wget/installdir/anaconda/bin/bcbio_nextgen.py", line 43, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/opt/az/local/bcbio-nextgen/use_wget/installdir/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 49, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/opt/az/local/bcbio-nextgen/use_wget/installdir/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 157, in upgrade_thirdparty_tools
    cbl = get_cloudbiolinux(remotes)
  File "/opt/az/local/bcbio-nextgen/use_wget/installdir/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 270, in get_cloudbiolinux
    subprocess.check_call(["git", "clone", remotes["cloudbiolinux"]])
  File "/opt/az/local/bcbio-nextgen/use_wget/installdir/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'clone', 'https://github.com/chapmanb/cloudbiolinux.git']' returned non-zero exit status 128
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 226, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 36, in main
    subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
  File "/opt/az/local/bcbio-nextgen/jakub/bcbio-nextgen/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/az/local/bcbio-nextgen/use_wget/installdir/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/opt/az/local/bcbio-nextgen/use_wget/tooldir', '--data']' returned non-zero exit status 1

This has been happening the past 2 days.  I originally thought that it was due to network problems here, but they claim to have fixed our network issues and this is still occurring.  

Jeff

**Comment by zytwh2012** [comment]
git config --global http.postBuffer 524288000 works for me
