### ISSUE TITLE
GRCh37 samtools ERROR????

### ISSUE THREAD

**Issue by RobertWBaldwin** [bcbio/bcbio-nextgen#2248]
Hi,

Some help please?

I just installed bcbio, as follows:

wget https://raw.github.com/chapmanb/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py
python bcbio_nextgen_install.py /usr/local/share/bcbio --tooldir=/usr/local \
  --genomes GRCh37 --aligners bwa --aligners bowtie2

There is a config yaml in /hpf/tools/centos6/bcbio/20180111/config that might be helpful.

[apple@data3 config]$ cat install-params.yaml 
aligners:
- bwa
- bowtie2
- rtg
- twobit
datatarget:
- variation
- rnaseq
- smallrna
genomes:
- GRCh37
isolate: false
tooldir: /hpf/tools/centos6/bcbio/20180111
toolplus: []

THE PROBLEM:

When I run this command:

bcbio_nextgen.py /hpf/largeprojects/pray/rbaldwin/project1/GIAB/bcbio_system.yaml /hpf/largeprojects/pray/rbaldwin/project1/GIAB/NA12878/config/NA12878.yaml -n 10

I get this error:

[2018-01-31T16:41Z] System YAML configuration: /hpf/largeprojects/pray/rbaldwin/project1/GIAB/bcbio_system.yaml
[2018-01-31T16:41Z] Resource requests: bwa, sambamba, samtools; memory: 5.00, 5.00, 5.00; cores: 8, 8, 8
[2018-01-31T16:41Z] Configuring 1 jobs to run, using 8 cores each with 40.1g of memory reserved for each job
[2018-01-31T16:41Z] Timing: organize samples
[2018-01-31T16:41Z] multiprocessing: organize_samples
[2018-01-31T16:41Z] Using input YAML configuration: /hpf/largeprojects/pray/rbaldwin/project1/GIAB/NA12878/config/NA12878.yaml
[2018-01-31T16:41Z] Checking sample YAML configuration: /hpf/largeprojects/pray/rbaldwin/project1/GIAB/NA12878/config/NA12878.yaml
[2018-01-31T16:41Z] Downloading GRCh37 samtools from AWS
Traceback (most recent call last):
  File "/hpf/tools/centos6/bcbio/20180111/bin/bcbio_nextgen.py", line 241, in <module>
    main(**kwargs)
  File "/hpf/tools/centos6/bcbio/20180111/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/hpf/tools/centos6/bcbio/20180111/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/hpf/tools/centos6/bcbio/20180111/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/hpf/tools/centos6/bcbio/20180111/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 120, in variant2pipeline
    [x[0]["description"] for x in samples]]])
  File "/hpf/tools/centos6/bcbio/20180111/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/hpf/tools/centos6/bcbio/20180111/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/hpf/tools/centos6/bcbio/20180111/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File "/hpf/tools/centos6/bcbio/20180111/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File "/hpf/tools/centos6/bcbio/20180111/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/hpf/tools/centos6/bcbio/20180111/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File "/hpf/tools/centos6/bcbio/20180111/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 332, in __init__
    self.results = batch()
  File "/hpf/tools/centos6/bcbio/20180111/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/hpf/tools/centos6/bcbio/20180111/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "/hpf/tools/centos6/bcbio/20180111/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 403, in organize_samples
    return run_info.organize(*args)
  File "/hpf/tools/centos6/bcbio/20180111/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 70, in organize
    item = add_reference_resources(item, remote_retriever)
  File "/hpf/tools/centos6/bcbio/20180111/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 164, in add_reference_resources
    data["reference"] = genome.get_refs(data["genome_build"], aligner, data["dirs"]["galaxy"], data)
  File "/hpf/tools/centos6/bcbio/20180111/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 226, in get_refs
    galaxy_config, data)
  File "/hpf/tools/centos6/bcbio/20180111/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 172, in _get_ref_from_galaxy_loc
    cur_ref = download_prepped_genome(genome_build, data, name, need_remap)
  File "/hpf/tools/centos6/bcbio/20180111/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 310, in download_prepped_genome
    raise ValueError("Could not find reference genome file %s %s" % (genome_build, name))
ValueError: Could not find reference genome file GRCh37 samtools

**Comment by rdocking** [comment]
Can you report the contents of this file?

`/hpf/largeprojects/pray/rbaldwin/project1/GIAB/NA12878/config/NA12878.yaml`

**Comment by RobertWBaldwin** [comment]
rbaldwin@qlogin5 config]$ cat NA12878.yaml
details:
- algorithm:
    aligner: bwa
    mark_duplicates: true
    realign: gatk
    recalibrate: gatk
    variantcaller: gatk-haplotype
  analysis: variant2
  description: NA12878_S1_L001
  files:
  - /localhd/32297704/NA12878/NA12878_S1_L001_R1_001.fastq.gz
  - /localhd/32297704/NA12878/NA12878_S1_L001_R2_001.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: batch1
    phenotype: normal
    sex: female
  upload:
    dir: /hpf/largeprojects/pray/rbaldwin/project1/GIAB/final
fc_name: NA12878
upload:
  dir: ../final

**Comment by chapmanb** [comment]
Robert;
Sorry about the issue, it looks like your command points to an alternative `bcbio_system.yaml` file: `/hpf/largeprojects/pray/rbaldwin/project1/GIAB/bcbio_system.yaml ` instead of the one that was created as part of your installation. This would result in bcbio trying to find the genome data relative to this file and is likely the cause of your issue.

My suggestion would be to use the standard file installed, which I think should be in `/hpf/tools/centos6/bcbio/20180111/galaxy/bcbio_system.yaml` if you need to adjust it. To do this, you don't need to reference anything on the command line and can just point to your sample YAML file:
```
bcbio_nextgen.py /hpf/largeprojects/pray/rbaldwin/project1/GIAB/NA12878/config/NA12878.yaml -n 10
```
Hope that fixes things for you and get the analysis running.

**Comment by RobertWBaldwin** [comment]
o.k thanks.
It says in the documentation that it is o.k to pass an alternative system config file to bcbio-nextgen.py script. But it looks like that may only be o.k provided that the alternative system.yaml is in the same folder as the default one, or are you saying that you should just not use the alternative system config at all? 

The problem is that I don't have permission to edit or create files in the /hpf/tools/centos6/ path. But I may be able to move files there, I don't know. I'll have to figure this out. In any case, I'll try it with the default first and see how it goes.

thanks for your help - Robert

**Comment by chapmanb** [comment]
Robert;
Thanks much for this feedback. The alternative file does work but is a bit tricky as it also needs to point at the data files. The preferred way to do this is to define the resource changes you need directly in your sample YAML file, which would take precedence over the default system YAML:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#sample-or-run-specific-resources

I'd be happy to make the documentation more helpful in pointing folks at this. Where specifically were you reading? I can work on tackling that to make sure it's more clear. Thank you again for this really helpful feedback and hope this gets your analysis running.

**Comment by RobertWBaldwin** [comment]
I was reading the documentation on the web page, at the very top of the Configuration section.

**Comment by chapmanb** [comment]
Robert -- thanks again for this feedback. I've modified the documentation here to put more emphasis on configuring your sample information and tweaking there, to avoid sending anyone down the wrong path going forward. Please let us know if you run into any other issues.
