### ISSUE TITLE
smallrnaseq pipeline tdrmapper/MINTmap issue

### ISSUE THREAD

**Issue by mshadbolt** [bcbio/bcbio-nextgen#2250]
Hi guys

I tried to run the srnaseq pipeline with tdrmapper enabled but in my `final` folder I get folder for mintmap that ends up empty for each file.

I also noticed that in the log file I get the error message: `There is no tRNA annotation to run MINTmap.`

Wondering if I have some kind of database file missing from my installation that could be causing this?

I am running the dev version of the pipeline

Thanks in advance for any advice

**Comment by lpantano** [comment]
Hi @mshadbolt 

Thanks so much for reporting this. I migrated to mintmap, but I forgot to add the conda package in the installation list. I just pushed it, so if you update bcbio it should install it. You can do it as well using `bcbio_conda -c bioconda install mintmap` but then maybe you need to link MINTmap.pl to the bcbio path.

This is only supported for human. I am working actually to support both, in that case, mouse genome is supported as well.

Let me know if that fixes it.

cheers

**Comment by mshadbolt** [comment]
Hi @lpantano thanks for the quick fix!
I'm not sure whether it works as yet as I am still running into the issue of the pipeline proceeding with trimming even though I have specified `trim_reads: false` in my yaml file, and the pipeline is crashing when it tries to trim reads with the error:
```
bcbio_nextgen.py $LOCAL_RESOURCES ../config/srnaseq_test.yaml --numcores 1
[2018-02-02T19:46Z] System YAML configuration: /bcbio_system.yaml
[2018-02-02T19:46Z] Resource requests: atropos, picard; memory: 3.60, 3.60; cores: 32, 32
[2018-02-02T19:46Z] Configuring 1 jobs to run, using 1 cores each with 3.60g of memory reserved for each job
[2018-02-02T19:46Z] Timing: organize samples
[2018-02-02T19:46Z] multiprocessing: organize_samples
[2018-02-02T19:46Z] Using input YAML configuration: /projects/karsanscratch/mshadbolt/bcbio_srnaseq_test_mintmap/srnaseq_test/config/srnaseq_test.yaml
[2018-02-02T19:46Z] Checking sample YAML configuration: /projects/karsanscratch/mshadbolt/bcbio_srnaseq_test_mintmap/srnaseq_test/config/srnaseq_test.yaml
[2018-02-02T19:46Z] Testing minimum versions of installed programs
[2018-02-02T19:46Z] multiprocessing: prepare_sample
[2018-02-02T19:46Z] Preparing sample1
[2018-02-02T19:46Z] Preparing sample2
[2018-02-02T19:46Z] Preparing sample3
[2018-02-02T19:46Z] Timing: adapter trimming
[2018-02-02T19:46Z] multiprocessing: trim_srna_sample
Traceback (most recent call last):
  File "/projects/rdocking_prj/software/bcbio-nextgen/tools/bin/bcbio_nextgen.py", line 241, in <module>
    main(**kwargs)
  File "/projects/rdocking_prj/software/bcbio-nextgen/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 312, in smallrnaseqpipeline
    samples = rnaseq_prep_samples(config, run_info_yaml, parallel, dirs, samples)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 400, in rnaseq_prep_samples
    samples = run_parallel("trim_srna_sample", samples)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 332, in __init__
    self.results = batch()
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 102, in trim_srna_sample
    return srna.trim_srna_sample(*args)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/bcbio/srna/sample.py", line 58, in trim_srna_sample
    times = "" if len(adapters) == 1 else "--times %s" % len(adapters)
UnboundLocalError: local variable 'adapters' referenced before assignment
```

**Comment by lpantano** [comment]
oops, sorry about that. I think I fixed it. I guess I shouldn't try to fix something while in jet lag. You can give it a try with the last dev.

Cheers

**Comment by mshadbolt** [comment]
Hi again. mintmap does now run successfully but I think the pipeline is still trimming my fastqs and as a result I am ending up with hardly any reads being mapped.

As an example I feed in a fastq with 16,778,589 reads.

The pipeline says 'skipping trimming' but then when I look in the `work` folder there is a `trimmed` folder with three files with `clean.fastq.gz`, `clean.trimming.fastq` and `fastq_size_stats` which seems to me like it has done trimming.

Then I had a look at the log files to see what fastq the pipeline is using for the STAR alignment step, it is using `work/seqcluster/prepare/seqs.fastq`, this fastq has only 119,909 reads. I guess this is because the reads are clustered but I don't think there should be that much of a reduction in reads should there? I think the pipeline is still trimming and is causing a lot of my reads to be thrown away, though it is not clear to me what input fastq the seqcluster is using as it doesn't show up in the commands.log file

Any help or advice would be much appreciated. Let me know if you need me to provide further info from log files etc.

**Comment by lpantano** [comment]
Hi,

Sorry for the issues. Can you send me the log files? Not sure why all this is happening, but I am trying to reproduce. Can you send as well the YAML file?

Thanks in advance

**Comment by lpantano** [comment]
I forgot to comment to your other questions. Actually, it is ok to have those files, those are after collapsing your reads. Can you check whether the `*clen.fastq.gz` is a symlink to your input files?

Those number of reads in `seqs.fastq` seems right. Yes, normally you reduce a lot, because there is a high duplication level. Normally, you sequence the full small RNA, so you directly have the reads repeated as many times as the sequence is in your sample.

Are you checking the files inside `mirbase` folder? can you share the top 10 lines of `mirbase/sample/*mirna` or if you could look at the `freq` column to see how the numbers are. You should have some big numbers if it is a standard small RNA.

I can look at the error of mintmap when you share the log files.

thanks!

**Comment by mshadbolt** [comment]
Hi again, ok if those numbers are expected perhaps something is going wrong with way the reads I am using were originally trimmed resulting in a low mapping rate. I am re-running now with the data trimmed differently to see if that could be the issue. 

yes the `.clean.fastq.gz` is a symlink to my input file

I have very low counts in my mirna file which is why I thought something was going wrong somewhere

First 10 lines of `.mirna` file
```
seq	name	freq	mir	start	end	mism	add	t5	t3	s5	s3	DB	precursor	ambiguity
AACATTCAACGCTGTCGGTGAGAGC	seq_1000_x13	13	hsa-miR-181a-5p	39	60	0	AGC	0	t	AAGGAACA	GAGTTTGG	miRNA	hsa-mir-181a-2	1
AAGCTGCCAGTTTAAGAACTGTA	seq_100145_x3	3	hsa-miR-22-3p	53	74	13TG	A	0	0	GCTAAAGC	CTGTTGCC	miRNA	hsa-mir-22	1
TGTAACCATCCTTGACTGGAAGC	seq_100242_x2	2	hsa-miR-30e-5p	17	39	6CA	0	0	C	CTACTGTA	GAAGCTGT	miRNA	hsa-mir-30e	1
TCGGATCCGTCTGAGCTTG	seq_100301_x9	9	hsa-miR-127-3p	57	75	0	0	0	gct	ATCATCGG	GGCTGGTC	miRNA	hsa-mir-127	1
GTATTGTTTCCTACTTTATGGATC	seq_100348_x24	24	hsa-miR-142-3p	53	75	4TG	C	t	T	AGGGTGTA	TGGATGAG	miRNA	hsa-mir-142	1
TGGCTCAGTTCAGCAGGAAC	seq_10062_x10	10	hsa-miR-24-3p	50	69	0	0	0	ag	ACACTGGC	ACAGGG	miRNA	hsa-mir-24-2	1
AACCCGTAGATCGGAACTTGTGA	seq_100760_x9	9	hsa-miR-100-5p	13	34	13GC	A	0	0	CACAAACC	TGTGGTAT	miRNA	hsa-mir-100	1
CATTGCACTTGTCTCGGTCTGAATCT	seq_100842_x65	65	hsa-miR-25-3p	52	74	23AC	TCT	0	C	TGGGCATT	CTGACAGT	miRNA	hsa-mir-25	1
CATAAAGTAGAAAGCACTACTA	seq_100902_x5	5	hsa-miR-142-5p	16	37	0	0	0	A	CACCCATA	TACTAACA	miRNA	hsa-mir-142	1
```

Sorry for assuming there was something wrong with the pipeline rather than my own files. I'll let you know how my tests go.

**Comment by lpantano** [comment]
Hi,

I appreciate all the feedback, is better to ask to make sure nothing is wrong.

Did you sort the file and check for the highest expression sequence?

I am using this R package to load data from this pipeline: https://github.com/lpantano/bcbioSmallRna

It is quite alpha, but maybe you can use the example report that comes with the package. I am working in this code right now, so hopefully there are no many errors. Let me know.

Cheers

**Comment by mshadbolt** [comment]
Hi again, it was a problem with the original trimming done with the files, I have fixed this now and the pipeline all works well. Thanks so much for your responsiveness. I will definitely check out the R package.

One last question, if I want to run seqcluster with an alternative gtf file, how would I go about doing that? When you run seqcluster it says that if you use a bam file then the `-g` file is ignored, but you can't actually run seqcluster without specifying a bam file right?

**Comment by lpantano** [comment]
Hi, 

Glad there is some news.

Right now there is no way to pass a custom GTF, but I can work on adding this in the next days. I will look into that message, because as you guessed it doesn’t make sense.

Cheers

**Comment by lpantano** [comment]
Hi,

I added the option to pass a custom GTF with `transcriptome_gtf `.

Thanks for helping with bcbio.
