### ISSUE TITLE
failed to install bcbio???

### ISSUE THREAD

**Issue by vwchen001** [bcbio/bcbio-nextgen#2322]
....
Successfully built bcbio-nextgen
Installing collected packages: bcbio-nextgen
Successfully installed bcbio-nextgen-1.0.8
Installing data and third party dependencies
Traceback (most recent call last):
  File ".../bcbio/anaconda/bin/bcbio_nextgen.py", line 36, in <module>
    from bcbio import install, utils, workflow
  File ".../bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 25, in <module>
    from bcbio import broad, utils
  File ".../bcbio/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 17, in <module>
    from bcbio.broad import picardrun
  File ".../bcbio/anaconda/lib/python2.7/site-packages/bcbio/broad/picardrun.py", line 9, in <module>
    from bcbio.distributed.transaction import file_transaction, tx_tmpdir
  File ".../bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/transaction.py", line 16, in <module>
    from bcbio.log import logger
  File ".../bcbio/anaconda/lib/python2.7/site-packages/bcbio/log/__init__.py", line 9, in <module>
    import logbook
ImportError: No module named logbook
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 255, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 41, in main
    subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
  File ".../python/2.7.9-2/anaconda/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['.../bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=.../', '--genomes', 'hg19', '--aligners', 'star']' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Thanks for the report and apologies about the issue. I'm not positive how it got in a state without the logbook dependency, but you should be able to fix with:
```
bcbio_conda update -c conda-forge -c bioconda logbook
```
and then re-run. Please let us know if you run into any other problems.

**Comment by vwchen001** [comment]
Where should I run/add this command? It cannot be found. Thanks for your reply.

**Comment by chapmanb** [comment]
bcbio_conda should be created as a symlink to the conda installation within bcbio within the `bin` directory of whatever you specified as `--tooldir`. If things didn't cleanly install/update, you can use the conda inside of bcbio directly:
```
bcbio/anaconda/bin/conda install -c conda-forge -c bioconda logbook
```
Hope this helps.

**Comment by vwchen001** [comment]
anaconda/bin/conda install -c conda-forge -c bioconda logbook
Solving environment: done

## Package Plan ##

  environment location: /scratch/cas/wchen/programs/bcbio/anaconda

  added / updated specs: 
    - logbook


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-1.0.2n             |                0         3.5 MB  conda-forge
    logbook-1.0.0              |           py27_0         223 KB  bioconda
    conda-4.3.34               |           py27_0         507 KB  conda-forge
    certifi-2018.1.18          |           py27_0         143 KB  conda-forge
    ca-certificates-2018.1.18  |                0         140 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         4.5 MB

The following NEW packages will be INSTALLED:

    ca-certificates: 2018.1.18-0      conda-forge
    logbook:         1.0.0-py27_0     bioconda   

The following packages will be UPDATED:

    certifi:         2018.1.18-py27_0             --> 2018.1.18-py27_0 conda-forge
    openssl:         1.0.2l-0                     --> 1.0.2n-0         conda-forge

The following packages will be DOWNGRADED:

    conda:           4.4.11-py27_0                --> 4.3.34-py27_0    conda-forge

Proceed ([y]/n)? vi note
Invalid choice: vi note
Proceed ([y]/n)? y


Downloading and Extracting Packages
openssl 1.0.2n: #################################################################################################################################################################################################################################################################################################### | 100% 
logbook 1.0.0: ##################################################################################################################################################################################################################################################################################################### | 100% 
conda 4.3.34: ###################################################################################################################################################################################################################################################################################################### | 100% 
certifi 2018.1.18: ################################################################################################################################################################################################################################################################################################# | 100% 
ca-certificates 2018.1.18: ######################################################################################################################################################################################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Segmentation fault (core dumped)

Thank you for your help!

**Comment by vwchen001** [comment]
Segmentation fault (core dumped)

**Comment by vwchen001** [comment]
I tried again, this time it finished.

**Comment by vwchen001** [comment]
Now it complains lack of dependencies of  gffutils, pybedtools, cyvcf2. After installed these similar to logbook. There is still problem:

# All requested packages already installed.

Requirement already satisfied: fabric in ..../bcbio/anaconda/lib/python2.7/site-packages
Requirement already satisfied: paramiko<3.0,>=1.10 in ..../bcbio/anaconda/lib/python2.7/site-packages (from fabric)
Requirement already satisfied: cryptography>=1.5 in ..../bcbio/anaconda/lib/python2.7/site-packages (from paramiko<3.0,>=1.10->fabric)
Requirement already satisfied: pynacl>=1.0.1 in ..../bcbio/anaconda/lib/python2.7/site-packages (from paramiko<3.0,>=1.10->fabric)
Requirement already satisfied: pyasn1>=0.1.7 in ..../bcbio/anaconda/lib/python2.7/site-packages (from paramiko<3.0,>=1.10->fabric)
Requirement already satisfied: bcrypt>=3.1.3 in ..../bcbio/anaconda/lib/python2.7/site-packages (from paramiko<3.0,>=1.10->fabric)
Requirement already satisfied: idna>=2.1 in ..../bcbio/anaconda/lib/python2.7/site-packages (from cryptography>=1.5->paramiko<3.0,>=1.10->fabric)
Requirement already satisfied: asn1crypto>=0.21.0 in ..../bcbio/anaconda/lib/python2.7/site-packages (from cryptography>=1.5->paramiko<3.0,>=1.10->fabric)
Requirement already satisfied: packaging in ..../bcbio/anaconda/lib/python2.7/site-packages (from cryptography>=1.5->paramiko<3.0,>=1.10->fabric)
Requirement already satisfied: six>=1.4.1 in ..../bcbio/anaconda/lib/python2.7/site-packages (from cryptography>=1.5->paramiko<3.0,>=1.10->fabric)
Requirement already satisfied: setuptools>=11.3 in ..../bcbio/anaconda/lib/python2.7/site-packages (from cryptography>=1.5->paramiko<3.0,>=1.10->fabric)
Requirement already satisfied: enum34 in ..../bcbio/anaconda/lib/python2.7/site-packages (from cryptography>=1.5->paramiko<3.0,>=1.10->fabric)
Requirement already satisfied: ipaddress in ..../bcbio/anaconda/lib/python2.7/site-packages (from cryptography>=1.5->paramiko<3.0,>=1.10->fabric)
Requirement already satisfied: cffi>=1.4.1 in ..../bcbio/anaconda/lib/python2.7/site-packages (from cryptography>=1.5->paramiko<3.0,>=1.10->fabric)
Requirement already satisfied: pycparser in ..../bcbio/anaconda/lib/python2.7/site-packages (from cffi>=1.4.1->cryptography>=1.5->paramiko<3.0,>=1.10->fabric)
Requirement already satisfied: bcbio-nextgen==1.0.8 in ..../bcbio/anaconda/lib/python2.7/site-packages (from -r https://raw.github.com/chapmanb/bcbio-nextgen/master/requirements.txt (line 1))
Installing data and third party dependencies
Traceback (most recent call last):
  File "..../bcbio/anaconda/bin/bcbio_nextgen.py", line 36, in <module>
    from bcbio import install, utils, workflow
  File "..../bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 26, in <module>
    from bcbio.pipeline import genome, version
  File "..../bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 17, in <module>
    from bcbio.pipeline import alignment
  File "..../bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 12, in <module>
    from bcbio.ngsalign import (bowtie, bwa, tophat, bowtie2, minimap2,
  File "..../bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/bwa.py", line 14, in <module>
    from bcbio.variation import sentieon
  File "..../bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/sentieon.py", line 20, in <module>
    from bcbio.variation import bamprep, bedutils, joint, vcfutils
  File "..../bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/joint.py", line 24, in <module>
    from bcbio.variation import bamprep, gatkjoint, genotype, multi, vcfutils
  File "..../bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 16, in <module>
    from bcbio.variation import (gatk, gatkfilter, germline, multi,
  File "..../bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/germline.py", line 8, in <module>
    import cyvcf2
  File "..../bcbio/anaconda/lib/python2.7/site-packages/cyvcf2/__init__.py", line 1, in <module>
    from .cyvcf2 import (VCF, Variant, Writer, r_ as r_unphased, par_relatedness,
  File "__init__.pxd", line 163, in init cyvcf2.cyvcf2
ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96
Traceback (most recent call last):
  File "..../bcbio/anaconda/bin/bcbio_nextgen.py", line 36, in <module>
    from bcbio import install, utils, workflow
  File "..../bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 26, in <module>
    from bcbio.pipeline import genome, version
  File "..../bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 17, in <module>
    from bcbio.pipeline import alignment
  File "..../bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 12, in <module>
    from bcbio.ngsalign import (bowtie, bwa, tophat, bowtie2, minimap2,
  File "..../bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/bwa.py", line 14, in <module>
    from bcbio.variation import sentieon
  File "..../bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/sentieon.py", line 20, in <module>
    from bcbio.variation import bamprep, bedutils, joint, vcfutils
  File "..../bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/joint.py", line 24, in <module>
    from bcbio.variation import bamprep, gatkjoint, genotype, multi, vcfutils
  File "..../bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 16, in <module>
    from bcbio.variation import (gatk, gatkfilter, germline, multi,
  File "..../bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/germline.py", line 8, in <module>
    import cyvcf2
  File "..../bcbio/anaconda/lib/python2.7/site-packages/cyvcf2/__init__.py", line 1, in <module>
    from .cyvcf2 import (VCF, Variant, Writer, r_ as r_unphased, par_relatedness,
  File "__init__.pxd", line 163, in init cyvcf2.cyvcf2
ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 255, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 41, in main
    subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
  File "...../python/2.7.9-2/anaconda/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['..../bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=..../bcbio', '--genomes', 'hg19', '--aligners', 'star']' returned non-zero exit status 1

**Comment by vwchen001** [comment]
Tried this:

bin/bcbio_nextgen.py upgrade -u development
Traceback (most recent call last):
  File "bin/bcbio_nextgen.py", line 36, in <module>
    from bcbio import install, utils, workflow
  File ".../bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 26, in <module>
    from bcbio.pipeline import genome, version
  File ".../bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 17, in <module>
    from bcbio.pipeline import alignment
  File "..../bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 12, in <module>
    from bcbio.ngsalign import (bowtie, bwa, tophat, bowtie2, minimap2,
  File "..../bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/bwa.py", line 14, in <module>
    from bcbio.variation import sentieon
  File "..../bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/sentieon.py", line 20, in <module>
    from bcbio.variation import bamprep, bedutils, joint, vcfutils
  File "..../bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/joint.py", line 24, in <module>
    from bcbio.variation import bamprep, gatkjoint, genotype, multi, vcfutils
  File "..../bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 16, in <module>
    from bcbio.variation import (gatk, gatkfilter, germline, multi,
  File "..../bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/germline.py", line 8, in <module>
    import cyvcf2
  File "..../bcbio/anaconda/lib/python2.7/site-packages/cyvcf2/__init__.py", line 1, in <module>
    from .cyvcf2 import (VCF, Variant, Writer, r_ as r_unphased, par_relatedness,
  File "__init__.pxd", line 163, in init cyvcf2.cyvcf2
ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96

**Comment by chapmanb** [comment]
Sorry about the continued problems. The error you're encountering is that the version of numpy installed with your bcbio system is incorrect. Running:
```
/path/to/bcbio/anacondai/bin/conda install -c conda-forge 'numpy=1.12*'
```
should resolve it.

More generally, this is a lot of manual updates and installs which shouldn't be necessary on a clean install/upgrade so I feel like something more general is going wrong. Could you provide a bit more detail on your install? Is it a new install or upgrade? What processes have you run so far for the installation? This might help us understand more about the general problems contributing to all these issues. Thanks for the help debugging.

**Comment by vwchen001** [comment]
anaconda/bin/conda install -c conda-forge 'numpy=1.12*'
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - cpat -> bx-python -> numpy=1.9 -> mkl==11.3.3
  - numpy=1.12
Use "conda info <package>" to see the dependencies for each package.

How can I clean up everything and reinstall? Thanks!

**Comment by vwchen001** [comment]
Saw this:
We don't have an automated remove method but the full installation is isolated to the install directory, so just doing a rm -rf /path/to/bcbio will remove bcbio, the tools, and associated data. Hope this works for your needs.

Tried reinstallation similar to this:
wget https://raw.github.com/chapmanb/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py
python bcbio_nextgen_install.py path/bcbio --tooldir=path/bcbio
  --genomes hg19--aligners bwa --aligners star

STILL ERRORS:
Installing data and third party dependencies
Traceback (most recent call last):
  File "path/bcbio/anaconda/bin/bcbio_nextgen.py", line 36, in <module>
    from bcbio import install, utils, workflow
  File "path/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 25, in <module>
    from bcbio import broad, utils
  File "path/bcbio/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 17, in <module>
    from bcbio.broad import picardrun
  File "path/bcbio/anaconda/lib/python2.7/site-packages/bcbio/broad/picardrun.py", line 6, in <module>
    import pysam
  File "path/bcbio/anaconda/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: /lib64/libk5crypto.so.3: symbol krb5int_buf_len, version krb5support_0_MIT not defined in file libkrb5support.so.0 with link time reference
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 260, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "path/python/2.7.9-2/anaconda/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['path/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=path/bcbio', '--genomes', 'hg19', '--aligners', 'bwa', '--aligners', 'star', '--data']' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Thanks for helping debug and sorry for the continued issues. When re-installing does `path/bcbio` contain a pre-existing anaconda installation from another bcbio installation? If so, removing `path/bcbio/anaconda` would let you do a clean install using the same data files but creating a new anaconda environment with the issues in your previous one. Hope this helps.

**Comment by vwchen001** [comment]
I removed the whole bcbio folder that contained everything from previous bcbio installation, before the automated reinstallation.

**Comment by chapmanb** [comment]
Thanks for following up and confirming that we're dealing with a clean install. From the errors I'm seeing it looks like something is problematic about your system crypto libraries, specifically `/lib64/libk5crypto.so.3`. This is a long thread I found which tries to debug some of this and might be helpful:

http://kerberos.996246.n3.nabble.com/version-krb5support-0-MIT-not-defined-td22574.html

What type of system are you running this on? Is it possible to avoid including the problematic libraries in your shared library path so anaconda can use it's own internal libraries rather than picking these up?

Sorry to not know exactly what is going on but hope this helps some.
