### ISSUE TITLE
Kraken crashes: error (with proposed solution)

### ISSUE THREAD

**Issue by choosehappy** [bcbio/bcbio-nextgen#2326]
I received this error:
```
root@cbc6fb3a9444:/data/liver_test_update/888_PD18810/work/log# tail -n 20 bcbio-nextgen.log
[2018-03-09T21:23Z] Timing: peddy check
[2018-03-09T21:23Z] multiprocessing: run_peddy
[2018-03-09T21:23Z] peddy is not installed, not human or sample VCFs don't match, skipping correspondence checking for None.
[2018-03-09T21:23Z] Timing: quality control
[2018-03-09T21:23Z] multiprocessing: pipeline_summary
[2018-03-09T21:23Z] QC: 888_PD18810b fastqc
[2018-03-09T21:23Z] Produced HTML report /data/liver_test_update/888_PD18810/work/qc/888_PD18810b/fastqc/fastqc_report.html
[2018-03-09T21:23Z] QC: 888_PD18810b qualimap
[2018-03-09T21:23Z] QC: 888_PD18810b samtools
[2018-03-09T21:23Z] QC: 888_PD18810b kraken
[2018-03-09T21:23Z] Running kraken to determine contaminant: 888_PD18810b
[2018-03-09T21:23Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; zcat /data/liver_test_update/888_PD18810b_R1.fastq.gz | /usr/local/share/bcbio-nextgen/anaconda/bin/kraken --db /usr/local/share/bcbio-nextgen/genomes/kraken/minikraken --quick --preload --min-hits 2 --threads 4 --out /data/liver_test_update/888_PD18810/work/bcbiotx/tmp8w01Og/kraken_out --fastq-input /dev/stdin  2> /data/liver_test_update/888_PD18810/work/bcbiotx/tmp8w01Og/kraken_stats
gzip: stdout: Broken pipe
' returned non-zero exit status 66
root@cbc6fb3a9444:/data/liver_test_update/888_PD18810/work/log#
```

i ran the command independently and received this error:
```
root@cbc6fb3a9444:/data/liver_test_update/888_PD18810/work# zcat /data/liver_test_update/888_PD18810b_R1.fastq.gz | /usr/local/share/bcbio-nextgen/anaconda/bin/kraken --db /usr/local/share/bcbio-nextgen/genomes/kraken/minikraken --quick --preload --min-hits 2 --threads 4 --out /data/liver_test_update/888_PD18810/work/bcbiotx/tmp8w01Og/kraken_out --fastq-input /dev/stdin
Option out is ambiguous (out-fmt, output)
Loading database... complete.
classify: can't open /data/liver_test_update/888_PD18810/work/bcbiotx/tmp8w01Og/kraken_out: No such file or directory
```

It seems the "-out" parameter is ambigious? I looked at the kraken options on the command line, it seems that "--output" was the intended target instead of "--out" which specifies the format:

```
root@cbc6fb3a9444:/data/liver_test_update/888_PD18810/work# /usr/local/share/bcbio-nextgen/anaconda/bin/kraken
Need to specify input filenames!
Usage: kraken [options] <filename(s)>

Options:
  --db NAME               Name for Kraken DB
                          (default: none)
  --threads NUM           Number of threads (default: 1)
  --fasta-input           Input is FASTA format
  --fastq-input           Input is FASTQ format
  --fastq-output          Output in FASTQ format
  --gzip-compressed       Input is gzip compressed
  --bzip2-compressed      Input is bzip2 compressed
  --quick                 Quick operation (use first hit or hits)
  --min-hits NUM          In quick op., number of hits req'd for classification
                          NOTE: this is ignored if --quick is not specified
  --unclassified-out FILENAME
                          Print unclassified sequences to filename
  --classified-out FILENAME
                          Print classified sequences to filename
  --out-fmt FORMAT        Format for [un]classified sequence output. supported
                          options are: {legacy, paired, interleaved}
  --output FILENAME       Print output to filename (default: stdout); "-" will
                          suppress normal output
  --only-classified-output
                          Print no Kraken output for unclassified sequences
  --preload               Loads DB into memory before classification
  --paired                The two filenames provided are paired-end reads
  --check-names           Ensure each pair of reads have names that agree
                          with each other; ignored if --paired is not specified
  --help                  Print this message
  --version               Print version information

```

So I think bcbio should change "--out" to "--output", when doing this on the command line, things seem to work as expected. Thoughts?

**Comment by choosehappy** [comment]
maybe change "--out" to "--output" here?

https://github.com/bcbio/bcbio-nextgen/blob/c61e2dc09045f66f6eba36b0cd9763d77da422f4/bcbio/qc/kraken.py#L49

**Comment by roryk** [comment]
@choosehappy, sorry for the delay in getting to this. Thanks so much for the fix, you are right kraken was broken and your fix fixes it.
