### ISSUE TITLE
bcbio_nextgen_install.py fails to download cloudbiolinux-master 

### ISSUE THREAD

**Issue by Itagliaf** [bcbio/bcbio-nextgen#2330]
Dear developers,

I'm tring to install bcbio locally (on the machine I use I have no root privileges) but I find issues in doing that.  I downloaded and ran bcbio_nextgen_install.py as follows

```
wget https://raw.github.com/chapmanb/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py
python bcbio_nextgen_install.py local/share/bcbio --tooldir=local --isolate
```
but the local installation fails with the following error:

```
Checking required dependencies
Installing isolated base python installation
Installing bcbio-nextgen
--2018-03-12 09:29:47--  https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/master/requirements-conda.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.112.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.112.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20 [text/plain]
Saving to: ‘requirements-conda.txt’

100%[===============================================================================================================================================>] 20          --.-K/s   in 0s      

2018-03-12 09:29:47 (2.60 MB/s) - ‘requirements-conda.txt’ saved [20/20]

Solving environment: ...working... done


==> WARNING: A newer version of conda exists. <==
  current version: 4.4.10
  latest version: 4.4.11

Please update conda by running

    $ conda update -n base conda



# All requested packages already installed.

Installing data and third party dependencies
Upgrading bcbio
Upgrading third party tools to latest versions
--2018-03-12 09:31:23--  https://github.com/chapmanb/cloudbiolinux/archive/master.tar.gz
Resolving github.com (github.com)... tar (child): /gss/gss_work/tape/userinternal/itagliaf: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master [following]
--2018-03-12 09:31:23--  https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master
Resolving codeload.github.com (codeload.github.com)... 192.30.253.120, 192.30.253.121
Connecting to codeload.github.com (codeload.github.com)|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘STDOUT’

     0KTraceback (most recent call last):
  File "/my/path/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 222, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/my/path/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 82, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/my/path/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 442, in upgrade_thirdparty_tools
    cbl = get_cloudbiolinux(remotes)
  File "/my/path/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 740, in get_cloudbiolinux
    % remotes["cloudbiolinux"], shell=True)
  File "/my/path/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'wget --progress=dot:mega --no-check-certificate -O- https://github.com/chapmanb/cloudbiolinux/archive/master.tar.gz | tar xz && (mv cloudbiolinux-master cloudbiolinux || mv master cloudbiolinux)' returned non-zero exit status 2
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 257, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/my/path/local/share/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=local', '--isolate', '--data']' returned non-zero exit status 1
```
The problem seems to be the "wget call" at line 740 of install.py

How can I solve this problem?

I tried running the installation script with both python 2.7.5 and 3.5.2.
My git version is 1.8.3.1

Thank you for your attention

Ilario

**Comment by roryk** [comment]
Hi Ilario,

If you run `'wget --progress=dot:mega --no-check-certificate  https://github.com/chapmanb/cloudbiolinux/archive/master.tar.gz  ` does it give you a more informative error?

**Comment by Itagliaf** [comment]
Hi,

running
```
wget --progress=dot:mega --no-check-certificate https://github.com/chapmanb/cloudbiolinux/archive/master.tar.gz
```
from command line actually resuts in a success, the archive is correctly downloaded. Here's the output:

```--2018-03-12 16:02:28--  https://github.com/chapmanb/cloudbiolinux/archive/master.tar.gz
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master [following]
--2018-03-12 16:02:33--  https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master
Resolving codeload.github.com (codeload.github.com)... 192.30.253.120, 192.30.253.121
Connecting to codeload.github.com (codeload.github.com)|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5168087 (4.9M) [application/x-gzip]
Saving to: ‘master.tar.gz.1’

     0K ........ ........ ........ ........ ........ ........ 60% 3.66M 1s
  3072K ........ ........ ........ ......                    100% 16.9M=0.9s

2018-03-12 16:02:35 (5.27 MB/s) - ‘master.tar.gz.’ saved [5168087/5168087]
```
thank you for the quick reply

**Comment by roryk** [comment]
Gotcha-- it looks like it was having trouble writing to: `/gss/gss_work/tape/userinternal/itagliaf`, do you have access to write to that?

**Comment by Itagliaf** [comment]
No, i don't have access to that folder.

How can i work around this problem?

**Comment by roryk** [comment]
I'm not super sure why it was trying to write to there-- do you have TMPDIR or anything like that set to write there? What directory are you running out of?

**Comment by Itagliaf** [comment]
Hi again,

i set the absolute path in the command as follows:

```
python bcbio_nextgen_install.py $(pwd)/local/share/bcbio/bcbio --tooldir=$(pwd)/local --isolate
```
but the result was the same.
As regarding the folder, I think it's set by the system's administration (it's a multi user cluster). Actually my TMPDIR.

Again, thanks for the fast reply

**Comment by roryk** [comment]
Can you unset the TMPDIR and re-try installing? If you do:

``unset TMPDIR`` 

and rerun it should fix this issue.

**Comment by Itagliaf** [comment]
Hi again,

sorry for the late reply. I actually tried unsetting TMPDIR but the situation don't change.

It seems to me that the problem is the machine i'm running on and i should contact the administrators, unless you have some more ideas.

In any case, thank you for your support.

Ilario
