### ISSUE TITLE
Small Rna

### ISSUE THREAD

**Issue by ahsen1402** [bcbio/bcbio-nextgen#2335]
This is related to thread #2334 . I followed your guide only get this error:

Hi,
I tried this but the error persists unfortunately here is a log:

Traceback (most recent call last):
  File " software/bin/bcbio_nextgen.py", line 241, in <module>
    main(**kwargs)
  File " software/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 334, in smallrnaseqpipeline
    samples = qcsummary.generate_parallel(samples, run_parallel)
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 37, in generate_parallel
    qced = run_parallel("pipeline_summary", to_analyze)
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 332, in __init__
    self.results = batch()
File " software_data/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 199, in pipeline_summary
    return qcsummary.pipeline_summary(*args)
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 68, in pipeline_summary
    data["summary"] = _run_qc_tools(work_bam, work_data)
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 151, in _run_qc_tools
    out = qc_fn(bam_file, data, cur_qc_dir)
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/qc/atropos.py", line 5, in run
    if "log_trimming" in data and utils.file_exists(data["log_trimming"]):
NameError: global name 'utils' is not defined

This error is new i believe "NameError: global name 'utils' is not defined". Any more guidance?

**Comment by chapmanb** [comment]
Apologies, this is my mistake on forgetting an import for the fix. If you do another update:
```
bcbio_nextgen.py upgrade -u development
```
it will hopefully run cleanly this time. Sorry again about the mistake.

If you run into any other issues you only need to raise a single error report. We all track the bcbio issues and try to help and having the thread in a single place make it easier to follow. Feel free to reopen an issue if a previous fix is not working for you and we can always revisit there. Thanks again.
