### ISSUE TITLE
subprocess.CalledProcessError:

### ISSUE THREAD

**Issue by mxhp75** [bcbio/bcbio-nextgen#2340]
Hi

I am attempting to install bcbio_nextgen using:
```
python bcbio_nextgen_install.py /localscratch/msmith/bcbio --tooldir=/localscratch/msmith \
  --genomes GRCh37 --aligners bwa --aligners bowtie2 --aligners star --datatarget smallrna --datatarget rnaseq
```

However, I received an error message as follows:
```
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 260, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 38, in main
    bcbio = install_conda_pkgs(anaconda, args)
  File "bcbio_nextgen_install.py", line 78, in install_conda_pkgs
    "-c", "conda-forge", "-c", "bioconda", "--only-deps", "bcbio-nextgen"])
  File "/apps/software/Anaconda3/4.3.1/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/localscratch/msmith/bcbio/anaconda/bin/conda', 'install', '--yes', '-c', 'conda-forge', '-c', 'bioconda', '--only-deps', 'bcbio-nextgen']' returned non-zero exit status 2.
```

I tried `$ echo $?` to confirm the exit status and it returned `1`

I found another similar issue and tried their solution which was (amended for my file structure):
```/localscratch/msmith/bcbio/anaconda/bin/conda clean --lock```

I then tried to re-run the install with:
```
python bcbio_nextgen_install.py /localscratch/msmith/bcbio --tooldir=/localscratch/msmith   \
--genomes GRCh37 --aligners bwa --aligners bowtie2 --aligners star --datatarget smallrna --datatarget rnaseq
```
but again receive the error message:
```
Checking required dependencies
Installing isolated base python installation
Installing bcbio-nextgen
Fetching package metadata ...............
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /localscratch/msmith/bcbio/anaconda:
#
conda                     4.3.34                   py27_0    conda-forge
usage: conda [-h] [-V] command ...
conda: error: unrecognized arguments: --only-deps
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 260, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 38, in main
    bcbio = install_conda_pkgs(anaconda, args)
  File "bcbio_nextgen_install.py", line 78, in install_conda_pkgs
    "-c", "conda-forge", "-c", "bioconda", "--only-deps", "bcbio-nextgen"])
  File "/apps/software/Anaconda3/4.3.1/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/localscratch/msmith/bcbio/anaconda/bin/conda', 'install', '--yes', '-c', 'conda-forge', '-c', 'bioconda', '--only-deps', 'bcbio-nextgen']' returned non-zero exit status 2.
```

I would like to use your pipeline for my smallrna analysis - any help on what to try next is greatly appreciated.

**Comment by chapmanb** [comment]
Thanks much for the report and apologies about the issue. Could you try getting the latest install script and re-running the install command:

https://raw.githubusercontent.com/bcbio/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py

This explicitly forces having the right conda version to support `--only-deps` and will hopefully let you proceed cleanly through the rest of the install. Please let us know if you run into any other issues.
