### ISSUE TITLE
titancna with vrn_file not enough input data

### ISSUE THREAD

**Issue by apastore** [bcbio/bcbio-nextgen#2346]
Hi I am trying titancna on cohort with precalled mutation. I am using the ensemble-annotated.vcf as a vrn_file. bcbio find the vcd and generate a .tbi file but TitanCNA is complaining about not enough input data even if each vcf is plenty of variants. Do you have any idea what I am doing wrong?

Thanks a lot!

`2018-03-18T15:19Z] ls04: Skipping TitanCNA; not enough input data: MMRF_1598_1_BM_CD138pos_T1_KHS5U_K14088_msk MMRF_1598_1_PB_CD3pos_C2_KHS5U_K14069_msk
[2018-03-18T15:23Z] ls11: Skipping TitanCNA; not enough input data: MMRF_1890_1_BM_CD138pos_T1_KBS5U_L05558_msk MMRF_1890_2_PB_CD3pos_C1_KBS5U_L05562_msk
[2018-03-18T15:40Z] lt12: Skipping TitanCNA; not enough input data: MMRF_1881_1_PB_Whole_C3_KBS5U_L05808_msk MMRF_1881_1_BM_CD138pos_T1_KBS5U_L05787_msk
[2018-03-18T15:40Z] lt12: Unexpected error
Traceback (most recent call last):
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 51, in _setup_logging
    yield config
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 429, in detect_sv
    return ipython.zip_args(apply(structural.detect_sv, *args))
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 197, in detect_sv
    for svdata in caller_fn(items):
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/titancna.py", line 28, in run
    het_file = _titan_het_file(heterogeneity.get_variants(paired.tumor_data), work_dir, paired)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/titancna.py", line 127, in _titan_het_file
    work_dir, paired, OutWriter)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/bubbletree.py", line 147, in prep_vrn_file
    stats = _is_possible_loh(rec, bcf_in, params, somatic_info)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/bubbletree.py", line 309, in _is_possible_loh
    stats = _tumor_normal_stats(rec, somatic_info)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/bubbletree.py", line 292, in _tumor_normal_stats
    alt, depth, freq = sample_alt_and_depth(rec, sample)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/bubbletree.py", line 350, in sample_alt_and_depth
    all_counts = [int(x) for x in sample["AD"]]
TypeError: int() argument must be a string or a number, not 'NoneType'
[2018-03-18T15:41Z] lt18: Unexpected error
Traceback (most recent call last):
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 51, in _setup_logging
    yield config
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 429, in detect_sv
    return ipython.zip_args(apply(structural.detect_sv, *args))
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 197, in detect_sv
    for svdata in caller_fn(items):
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/titancna.py", line 28, in run
    het_file = _titan_het_file(heterogeneity.get_variants(paired.tumor_data), work_dir, paired)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/titancna.py", line 127, in _titan_het_file
    work_dir, paired, OutWriter)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/bubbletree.py", line 147, in prep_vrn_file
    stats = _is_possible_loh(rec, bcf_in, params, somatic_info)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/bubbletree.py", line 309, in _is_possible_loh
    stats = _tumor_normal_stats(rec, somatic_info)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/bubbletree.py", line 292, in _tumor_normal_stats
    alt, depth, freq = sample_alt_and_depth(rec, sample)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/bubbletree.py", line 350, in sample_alt_and_depth
    all_counts = [int(x) for x in sample["AD"]]
TypeError: int() argument must be a string or a number, not 'NoneType'
[2018-03-18T15:44Z] lt18: Unexpected error
Traceback (most recent call last):
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 51, in _setup_logging
    yield config
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 429, in detect_sv
    return ipython.zip_args(apply(structural.detect_sv, *args))
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 197, in detect_sv
    for svdata in caller_fn(items):
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/titancna.py", line 28, in run
    het_file = _titan_het_file(heterogeneity.get_variants(paired.tumor_data), work_dir, paired)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/titancna.py", line 127, in _titan_het_file
    work_dir, paired, OutWriter)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/bubbletree.py", line 147, in prep_vrn_file
    stats = _is_possible_loh(rec, bcf_in, params, somatic_info)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/bubbletree.py", line 309, in _is_possible_loh
    stats = _tumor_normal_stats(rec, somatic_info)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/bubbletree.py", line 292, in _tumor_normal_stats
    alt, depth, freq = sample_alt_and_depth(rec, sample)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/heterogeneity/bubbletree.py", line 350, in sample_alt_and_depth
    all_counts = [int(x) for x in sample["AD"]]
TypeError: int() argument must be a string or a number, not 'NoneType'`

**Comment by chapmanb** [comment]
Thanks for testing this out and sorry about the issues. We've not yet tried to run TitanCNA and heterogeneity analysis from pre-called VCF inputs, so we're likely running into issues with converting the data into the right formats. In this case it appears as if the ensemble inputs you're inputting don't have some of the expected keys like allele depth homogenized:

https://github.com/bcbio/bcbio-nextgen/blob/8a76c9e546cb79621707082fd763bd643e0e9652/bcbio/heterogeneity/bubbletree.py#L346

If you compare your input to what the code there expects it might give us some idea of what is missing. ensemble is going to be especially problematic for this because it's a combination of multiple callers, so you might want to explore using a single somatic caller.

 We'll work on generalizing this but in the short term if you need to get an analysis done might need to recall with a somatic callers in the analysis to avoid having to do too much debugging. Hope this helps.

**Comment by apastore** [comment]
Thanks a lot! I am rerunning with vardict. Let you know if i will get other issues. 

Thanks a lot!

**Comment by roryk** [comment]
Thanks, closing this as a reasonable workaround was suggested which seemed to do the trick. Please re-open if this is a recurring issue.
