### ISSUE TITLE
ensemble error

### ISSUE THREAD

**Issue by parlar** [bcbio/bcbio-nextgen#2350]
Hi, I'm running the latest dev version of bcbio-nextgen, using enseble calling.

It exits with an error:

```
 returned non-zero exit status 1
Traceback (most recent call last):
  File "/home/genetik-devel/bcbio/tools/bin/bcbio_nextgen.py", line 241, in <module>
    main(**kwargs)
  File "/home/genetik-devel/bcbio/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 166, in variant2pipeline
    samples = ensemble.combine_calls_parallel(samples, run_parallel)
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/ensemble.py", line 73, in combine_calls_parallel
    processed = run_parallel("combine_calls", ((b, xs, xs[0]) for b, xs in batch_groups.items()))
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 331, in combine_calls
    return ensemble.combine_calls(*args)
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/ensemble.py", line 44, in combine_calls
    callinfo = _run_ensemble_intersection(batch_id, vrn_files, caller_names, base_dir, edata)
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/ensemble.py", line 216, in _run_ensemble_intersection
    do.run(cmd, "Ensemble intersection calling: %s" % (batch_id))
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; export PATH=/home/genetik-devel/bcbio/share/bcbio/anaconda/bin:$PATH &&  /home/genetik-devel/bcbio/share/bcbio/anaconda/bin/bcbio-variation-recall ensemble --cores=1 --numpass 1 --names freebayes,gatk-haplotype,platypus,samtools --nofiltered /home/genetik-devel/Projects/svcalls/calling/work/bcbiotx/tmpaRCJla/batch1-ensemble.vcf.gz /home/genetik-devel/bcbio/share/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa /home/genetik-devel/Projects/svcalls/calling/work/gemini/batch1-freebayes-noeff-nomultiallelic.vcf.gz /home/genetik-devel/Projects/svcalls/calling/work/gemini/batch1-gatk-haplotype-noeff-nomultiallelic.vcf.gz /home/genetik-devel/Projects/svcalls/calling/work/gemini/batch1-platypus-noeff-nomultiallelic.vcf.gz /home/genetik-devel/Projects/svcalls/calling/work/gemini/batch1-samtools-noeff-nomultiallelic.vcf.gz
2018-03-27 12:57:37 v01s979.vll.se INFO [bcbio.run.itx] - [W::bcf_hdr_check_sanity] GL should be declared as Number=G
2018-03-27 12:57:38 v01s979.vll.se INFO [bcbio.run.itx] - [W::bcf_hdr_check_sanity] GL should be declared as Number=G
2018-03-27 12:57:38 v01s979.vll.se INFO [bcbio.run.itx] - Note: -w option not given, printing list of sites...
2018-03-27 12:57:39 v01s979.vll.se ERROR [bcbio.variation.recall.main] - 
java.lang.Exception: Problem retrieving reference variant for {:chr "chr1", :start 116268176, :refa "GGaaaa", :alta ["G"], :end 116268182, :vc-indices (3)}: []
   bcbio.variation.ensemble.intersect/get-rep-vc/fn       intersect.clj:   58
                               clojure.core/comp/fn            core.clj: 2438
                                clojure.core/map/fn            core.clj: 2624
                          clojure.lang.LazySeq.sval        LazySeq.java:   40
                           clojure.lang.LazySeq.seq        LazySeq.java:   49
                                clojure.lang.RT.seq             RT.java:  507
                                   clojure.core/seq            core.clj:  137
                                clojure.core/map/fn            core.clj: 2616
                          clojure.lang.LazySeq.sval        LazySeq.java:   40
                           clojure.lang.LazySeq.seq        LazySeq.java:   49
                             clojure.lang.Cons.next           Cons.java:   39
                               clojure.lang.RT.next             RT.java:  674
                                  clojure.core/next            core.clj:   64
bcbio.variation.variantcontext/write-vcf-w-template  variantcontext.clj:  189
                         clojure.lang.RestFn.invoke         RestFn.java:  573
bcbio.variation.ensemble.intersect/ensemble-vcfs/fn       intersect.clj:   88
   bcbio.variation.ensemble.intersect/ensemble-vcfs       intersect.clj:   86
           bcbio.variation.ensemble.intersect/-main       intersect.clj:  140
                        clojure.lang.RestFn.applyTo         RestFn.java:  137
                                 clojure.core/apply            core.clj:  630
               bcbio.variation.recall.main/-main/fn            main.clj:   34
                  bcbio.variation.recall.main/-main            main.clj:   33
                        clojure.lang.RestFn.applyTo         RestFn.java:  137
                   bcbio.variation.recall.main.main                    :     
' returned non-zero exit status 1
```

**Comment by chapmanb** [comment]
Pär;
Sorry about the issue and thanks for the detailed report. It looks from the error message like we're having a problem with the upper/lower casing on the reference reads for this deletion. Typically callers report these as upper case but at least one of the callers in your ensemble input isn't.

Could you share the calls in this problem region for each of the callers:
```
tabix /home/genetik-devel/Projects/svcalls/calling/work/gemini/batch1-freebayes-noeff-nomultiallelic.vcf.gz chr1:116268175-116268180
tabix /home/genetik-devel/Projects/svcalls/calling/work/gemini/batch1-gatk-haplotype-noeff-nomultiallelic.vcf.gz chr1:116268175-116268180
tabix /home/genetik-devel/Projects/svcalls/calling/work/gemini/batch1-platypus-noeff-nomultiallelic.vcf.gz chr1:116268175-116268180
tabix /home/genetik-devel/Projects/svcalls/calling/work/gemini/batch1-samtools-noeff-nomultiallelic.vcf.gz chr1:116268175-116268180
```
That should give us some details about how best to normalize these and which caller is triggering problems. Thanks much for the help debugging.

**Comment by parlar** [comment]
Hi,

Thanks for responding quickly. Sending the variants. I notice that the output was empty for two of the files (freebayes and platypus), if that has something to do with anything? Since they were empty they could not be uploaded.


[gatk-chr1_116268175-116268180.txt](https://github.com/bcbio/bcbio-nextgen/files/1852542/gatk-chr1_116268175-116268180.txt)

[samtools-chr1_116268175-116268180.txt](https://github.com/bcbio/bcbio-nextgen/files/1852543/samtools-chr1_116268175-116268180.txt)

**Comment by roryk** [comment]
Thanks, this is old and we haven't done much action on it, so closing it out.
