### ISSUE TITLE
manta sv calling error

### ISSUE THREAD

**Issue by parlar** [bcbio/bcbio-nextgen#2351]
Ran upon another error in the latest dev version of bcbio-nextgen

```
[2018-03-27T12:07Z] Timing: structural variation
[2018-03-27T12:07Z] multiprocessing: detect_sv
Traceback (most recent call last):
  File "/home/genetik-devel/bcbio/tools/bin/bcbio_nextgen.py", line 241, in <module>
    main(**kwargs)
  File "/home/genetik-devel/bcbio/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 174, in variant2pipeline
    samples = structural.run(samples, run_parallel, "standard")
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 177, in run
    for xs in to_process.values()))
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 311, in detect_sv
    return structural.detect_sv(*args)
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 197, in detect_sv
    for svdata in caller_fn(items):
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/manta.py", line 27, in run
    tx_workflow_file = _prep_config(items, paired, tx_work_dir)
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/manta.py", line 91, in _prep_config
    for region in _maybe_limit_chromosomes(data):
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/manta.py", line 109, in _maybe_limit_chromosomes
    std_chroms.append(contig.name)
NameError: global name 'std_chroms' is not defined
```

**Comment by chapmanb** [comment]
Sorry about the issue. This was a typo that got fixed yesterday:

https://github.com/bcbio/bcbio-nextgen/commit/776ef06a8732b976428d1d354219d7d72978dd46

If you update with `bcbio_nextgen.py upgrade -u development` it should hopefully avoid the issue and run cleanly for you. Hope this gets your analysis working.

**Comment by parlar** [comment]
I'm still having an issue with manta.

Manta still fails, and I cannot seem to understand why.  See error below:

```
/home/genetik-devel/bcbio/share/bcbio/anaconda/share/manta-1.3.2-0/libexec/GetAlignmentStats --ref /home/genetik-devel/bcbio/share/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa --output-file /home/genetik-devel/Projects/svcalls/calling/work/bcbiotx/tmppj60Nw/manta/workspace/alignmentStats.xml.tmpdir/alignmentStats.xml.003.xml --align-file /home/genetik-devel/Projects/svcalls/calling/work/align/14-3306/14-3306-sort.bam
FATAL_ERROR: 2018-Apr-06 13:19:39 /builder/src/c++/lib/manta/ReadGroupStatsUtil.cpp(260): Throw in function void ReadGroupOrientTracker::finalize(const ReadCounter&)
Dynamic exception type: boost::exception_detail::clone_impl<illumina::common::GeneralException>
std::exception::what: Can't determine consensus pair orientation of read group '' in bam file '/home/genetik-devel/Projects/svcalls/calling/work/align/14-3306/14-3306-sort.bam.
	The most frequent orientation is 'Rm' (57% of 54224 total used read pairs)
	The fraction of 'Rm' among total high-confidence read pairs needs to be more than 0.9 to determine consensus pair orientation.
	Total sampled reads: 3818416
	Total sampled paired reads: 3818416
	Total sampled paired reads passing MAPQ filter: 3755852
	Total sampled high-confidence read pairs passing all filters: 54224

```

A hint might be that the ```read group``` is empty in the error msg. However looking in the bam header, it's there:

```
@RG	ID:14-3306	PL:illumina	PU:14-3306	SM:14-3306
```

Output from alfred qc does not help me either:

```
ME	ME
Sample	14-3306
Library	14-3306
#QCFail	0
QCFailFraction	0
#DuplicateMarked	0
DuplicateFraction	0
#Unmapped	335509
UnmappedFraction	0.0808109
#Mapped	3816271
MappedFraction	0.919189
#MappedRead1	1908182
#MappedRead2	1908089
RatioMapped2vsMapped1	0.999951
#MappedForward	1908121
MappedForwardFraction	0.499996
#MappedReverse	1908150
MappedReverseFraction	0.500004
#SecondaryAlignments	1156
SecondaryAlignmentFraction	0.000302913
#SupplementaryAlignments	0
SupplementaryAlignmentFraction	0
#SplicedAlignments	0
SplicedAlignmentFraction	0
#Pairs	2076468
#MappedPairs	1908211
MappedPairsFraction	0.91897
#MappedSameChr	1907357
MappedSameChrFraction	0.918558
#MappedProperPair	1905816
MappedProperFraction	0.917816
#ReferenceBp	3136565497
#ReferenceNs	239850702
#AlignedBases	392068296
#MatchedBases	390475716
MatchRate	0.995938
#MismatchedBases	1592580
MismatchRate	0.004062
#DeletionsCigarD	20322
DeletionRate	5.18328E-05
HomopolymerContextDel	0.570613
#InsertionsCigarI	11157
InsertionRate	2.84568E-05
HomopolymerContextIns	0.409519
#SoftClippedBases	1110926
SoftClipRate	0.0028335
#HardClippedBases	0
HardClipRate	0
ErrorRate	0.00697579
MedianReadLength	124
DefaultLibraryLayout	3
MedianInsertSize	109
MedianCoverage	0
SDCoverage	1.86657
MedianMAPQ	60
```

**Comment by chapmanb** [comment]
Par;
Thanks for continuing to debug this and the detailed report. Looking through the statistics for the reads, my guess is that the small insert size is the likely issue:
```
MedianReadLength	108
MedianInsertSize	102
```
Most SV callers will have trouble with these as I believe heavily overlapping reads aren't always reported in a consistent way. This older manta thread discusses some of the issues with this type of data: https://github.com/Illumina/manta/issues/21

My suggestion would be to remove split/discordant read based callers like delly and manta on this sample and try to stick with a depth based caller like CNVkit only. Hope this helps.

**Comment by parlar** [comment]
Thanks!
