### ISSUE TITLE
delly sv calling error

### ISSUE THREAD

**Issue by parlar** [bcbio/bcbio-nextgen#2352]
Delly complains about incorrect paired-end orientation: Seems that it could be related to read group info in the bam files?

https://github.com/dellytools/delly/issues/97

It should be noted that the data used was from a panel and not exome/whole genome, if this could be causing issues.

```
Error: One library has a non-default paired-end layout! Read-group: 17-5853
The expected paired-end orientation is   ---Read1--->      <---Read2---  which is the default illumina paired-end layout.
Error: One library has a non-default paired-end layout! Read-group: 17-6138
The expected paired-end orientation is   ---Read1--->      <---Read2---  which is the default illumina paired-end layout.
Error: One library has a non-default paired-end layout! Read-group: 10-0116
The expected paired-end orientation is   ---Read1--->      <---Read2---  which is the default illumina paired-end layout.
Error: One library has a non-default paired-end layout! Read-group: 17-6145
The expected paired-end orientation is   ---Read1--->      <---Read2---  which is the default illumina paired-end layout.
Error: One library has a non-default paired-end layout! Read-group: 17-5122
The expected paired-end orientation is   ---Read1--->      <---Read2---  which is the default illumina paired-end layout.
Error: One library has a non-default paired-end layout! Read-group: 17-6078
The expected paired-end orientation is   ---Read1--->      <---Read2---  which is the default illumina paired-end layout.
Error: One library has a non-default paired-end layout! Read-group: 17-4976
The expected paired-end orientation is   ---Read1--->      <---Read2---  which is the default illumina paired-end layout.
Error: One library has a non-default paired-end layout! Read-group: 14-3306
The expected paired-end orientation is   ---Read1--->      <---Read2---  which is the default illumina paired-end layout.
Error: One library has a non-default paired-end layout! Read-group: 17-5740
The expected paired-end orientation is   ---Read1--->      <---Read2---  which is the default illumina paired-end layout.
Error: One library has a non-default paired-end layout! Read-group: 17-5352
The expected paired-end orientation is   ---Read1--->      <---Read2---  which is the default illumina paired-end layout.
Error: One library has a non-default paired-end layout! Read-group: 17-5975
The expected paired-end orientation is   ---Read1--->      <---Read2---  which is the default illumina paired-end layout.
Error: One library has a non-default paired-end layout! Read-group: 15-2773
The expected paired-end orientation is   ---Read1--->      <---Read2---  which is the default illumina paired-end layout.
Library parameters could not be estimated!
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/home/genetik-devel/bcbio/tools/bin/bcbio_nextgen.py", line 241, in <module>
    main(**kwargs)
  File "/home/genetik-devel/bcbio/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 174, in variant2pipeline
    samples = structural.run(samples, run_parallel, "standard")
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 177, in run
    for xs in to_process.values()))
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 311, in detect_sv
    return structural.detect_sv(*args)
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 197, in detect_sv
    for svdata in caller_fn(items):
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/delly.py", line 166, in run
    config, parallel)
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 812, in __call__
    self.retrieve()
  File "/home/genetik-devel/bcbio/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 749, in retrieve
    exception = exception_type(report)
TypeError: __init__() takes at least 3 arguments (2 given)
```

**Comment by chapmanb** [comment]
Pär;
Sorry for the problems and thanks for the detailed report. Practically it sounds like your data has unexpected orientations due to the preparation process. What type of input data is it and how did you prepare and align the BAMs? Does any of the advice in that delly thread you linked provide relevant tips? It sounds like some pre-procesisng is necessary for custom input types, and that's typically something that is done upstream of bcbio. Hope this helps some.

**Comment by parlar** [comment]
Thanks. The bams were created using bcbio-nextgen pipeline. Sorry, should have clarified that. 

Here is the yaml definition, except for manta, delly, ensemble calling -  that I removed since they failed.

So, the alignment performed using bwa, after trimming using the default trimmer. 

I can take a look at the bams tomorrow using Alfred, as suggested further down in the thread. To see if that provides any clues.

```
---
upload:
  dir: ../final
details:
  - files: [/home/genetik-devel/Projects/svcalls/Data/Intensities/BaseCalls/10-0116_S1_L001_R1_001.fastq.gz, /home/genetik-devel/Projects/svcalls/Data/Intensities/BaseCalls/10-0116_S1_L001_R2_001.fastq.gz]
    description: 10-0116
    metadata:
      batch: batch1
      sex: male
    analysis: variant2
    genome_build: hg19
    algorithm:
      aligner: bwa
      mark_duplicates: false
      trim_reads: true
      custom_trim: ['AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC','AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT']
      min_read_length: '40'
      trim_ends: [5,0,5,0] 
      variantcaller: ['freebayes', 'gatk-haplotype', 'platypus', 'samtools'] 
      svcaller: [lumpy, cnvkit, seq2c, battenberg]
      svprioritize: /home/genetik-devel/calling-configs/LKPN_hart_design_III_17150-1413761621.bed
      quality_format: Standard
      coverage_interval: amplicon
      recalibrate: false
      realign: false
      merge_bamprep: true
      variant_regions: /home/genetik-devel/calling-configs/LKPN_hart_design_III_17150-1413761621.bed
#      clinical_reporting: true
#      effects: false
#      ensemble:
#        numpass: 1
```

**Comment by parlar** [comment]
Probably same as https://github.com/bcbio/bcbio-nextgen/issues/2352 (?)

No clues from alfred that I can see.

```
Sample	10-0116
Library	10-0116
#QCFail	0
QCFailFraction	0
#DuplicateMarked	0
DuplicateFraction	0
#Unmapped	350531
UnmappedFraction	0.105886
#Mapped	2959915
MappedFraction	0.894114
#MappedRead1	1479952
#MappedRead2	1479963
RatioMapped2vsMapped1	1.00001
#MappedForward	1479956
MappedForwardFraction	0.499999
#MappedReverse	1479959
MappedReverseFraction	0.500001
#SecondaryAlignments	806
SecondaryAlignmentFraction	0.000272305
#SupplementaryAlignments	0
SupplementaryAlignmentFraction	0
#SplicedAlignments	0
SplicedAlignmentFraction	0
#Pairs	1655626
#MappedPairs	1479928
MappedPairsFraction	0.893878
#MappedSameChr	1479383
MappedSameChrFraction	0.893549
#MappedProperPair	1477783
MappedProperFraction	0.892583
#ReferenceBp	3136120105
#ReferenceNs	239850602
#AlignedBases	268005786
#MatchedBases	266934402
MatchRate	0.996002
#MismatchedBases	1071384
MismatchRate	0.00399762
#DeletionsCigarD	15612
DeletionRate	5.82525E-05
HomopolymerContextDel	0.494043
#InsertionsCigarI	7203
InsertionRate	2.68763E-05
HomopolymerContextIns	0.423296
#SoftClippedBases	1177011
SoftClipRate	0.00439174
#HardClippedBases	0
HardClipRate	0
ErrorRate	0.00847448
MedianReadLength	108
DefaultLibraryLayout	3
MedianInsertSize	102
MedianCoverage	0
SDCoverage	1.87432
MedianMAPQ	60
```

**Comment by chapmanb** [comment]
Discussion of this sample in: https://github.com/bcbio/bcbio-nextgen/issues/2351#issuecomment-379563784

**Comment by roryk** [comment]
Workaround suggested in the https://github.com/bcbio/bcbio-nextgen/issues/2351#issuecomment-379563784 thread, so closing here.
