### ISSUE TITLE
bcbio compatibility with GCE

### ISSUE THREAD

**Issue by PatrickJReed** [bcbio/bcbio-nextgen#2353]
I'm hoping to get bcbio set up on a google instance.  Our Lab got a grant specifically to use google compute resources, so i need to transition from amazon to google.  I'm having issues right off the bat, and am wondering what is the best way to get bcbio running on gce?  I need a straight forward set up, no cluster or shared file system compatibility.

following a basic install attempt:

python bcbio_nextgen_install.py /usr/local/share/bcbio --tooldir=/usr/local   -
-genomes GRCh37 --aligners bwa

it crashes:

Upgrading third party tools to latest versions
--2018-03-29 20:13:41--  https://github.com/chapmanb/cloudbiolinux/archive/master.tar.gz
Resolving github.com (github.com)... 192.30.255.112, 192.30.255.113
Connecting to github.com (github.com)|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master [following]
--2018-03-29 20:13:41--  https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master
Resolving codeload.github.com (codeload.github.com)... 192.30.255.121, 192.30.255.120
Connecting to codeload.github.com (codeload.github.com)|192.30.255.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘STDOUT’
     0K ........ ........ ........ ........ ........ ........ 32.8M
  3072K ........ ........ ........ ......                     25.5M=0.2s
2018-03-29 20:13:41 (29.5 MB/s) - written to stdout [5168529]
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 222, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 82, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 444, in upgrade_thirdpa
rty_tools
    cbl_deploy = __import__("cloudbio.deploy", fromlist=["deploy"])
  File "/home/patrickjenningsreed/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 18, in <module>
    from .volume import attach_volumes, make_snapshots, detach_volumes
  File "/home/patrickjenningsreed/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/volume.py", line 3, in <module>
    from boto.exception import EC2ResponseError
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/boto/__init__.py", line 1216, in <module>
    boto.plugin.load_plugins(config)
AttributeError: 'module' object has no attribute 'plugin'
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 260, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tool
dir=/usr/local', '--genomes', 'GRCh37', '--aligners', 'bwa', '--data']' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Patrick;
Thanks much for this report and apologies about the issue. I believe we're running into this boto issues on GCE:

https://stackoverflow.com/questions/40732313/gensim-installation-problems

which I tried to avoid by moving the unneeded boto import in cloudbiolinux. You should be able to easily use either a local bcbio install or Docker approach here, so hopefully this enables it for you. You'll need to remove any cached cloudbiolinux installs (`rm -rf tmpbcbio-install`) and then re-running should work. Please let us know if you run into any other issues.
