### ISSUE TITLE
Unable to import numpy

### ISSUE THREAD

**Issue by phu5ion** [bcbio/bcbio-nextgen#2369]
Hi,

After upgrading to the most recent (as of now) developmental version, I ran into an error with importing numpy:

```
Traceback (most recent call last):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/bin/bcbio_nextgen.py", line 36, in <module>
    from bcbio import install, utils, workflow
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 26, in <module>
    from bcbio.pipeline import genome, version
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 13, in <module>
    from bcbio.cwl import cwlutils
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/cwl/cwlutils.py", line 15, in <module>
    from bcbio import bam, utils
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/bam/__init__.py", line 8, in <module>
    import numpy
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/numpy/core/__init__.py", line 24, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

```
Short search online turned out that a likely reason is numpy version conflicts with python. I think bcbio uses its native anaconda installation? Any ideas on how to resolve this problem? Thanks!

**Comment by lbeltrame** [comment]
I've seen this as well, strangely not on all the nodes that run bcbio (despite it being on a network mount).

**Comment by phu5ion** [comment]
Ooooppps it looks like I broke my bcbio install. Now I can't get bcbio to upgrade again.

If my memory doesn't fail me, I think I had the issue #2333 (encountering issues with the multiarray module from numpy related to libquadmath.so.0 in my previous install that I could not resolve) that other users also reported, before getting the numpy failed to import error. I'll try to do a clean install but Bcbio team might want to look into this issue too.

**Comment by chapmanb** [comment]
Thanks for all the reports and for working on debugging. Apologies about the issue; I've been working to try and replicate this with a few different installs and haven't been able to do so. As far as I can tell some upgrade paths from older installs can get different numpy versions or you might be injecting other numpy installs into your python path from `~/.local` directory imports. Hopefully either a clean install or the manual steps for the older fixes (which should be automated now if you can get a clean upgrade to the latest release or development) will get you back in a good place. Thanks again for working on this and sorry about the issues.

**Comment by lbeltrame** [comment]
It's probably a local issue but puzzling because the stuff is on the *same filesystem* but some nodes take offense with that library and other not.

**Comment by phu5ion** [comment]
@chapmanb thanks for all your efforts on debugging this issue. Yeah I think you could be right as I haven't upgraded bcbio for a long time. As far as I can tell getting bcbio_nextgen upgrade to work cleanly got the numpy issue fixed and the pipeline working - crossed fingers hoping the pipeline doesn't choke again.
