### ISSUE TITLE
mapped-stats.txt during coverage: invalid file generated due to potential race conditions

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2371]
I've noticed that in some occasions the file is not created correctly: I'm still not sure if it's a local issue or in bcbio but I wanted to gather some input on it.

I get weirdly-done `mapped-stats.txt` files, for example this one:

```
{"flags":["not duplicate","not failed_quality_control","not mate_is_unmapped","not secondary_alignment","not unmapped"],"region":"","sample":"Sample1"}      16252134{"fl{"flags":["not duplicate","not failed_quality_control","not mate_is_unmapped","not secondary_alignment","not unmapped"],"region":"cleaned-Illumina_Nextera_Rapid_Capture_Exome.hg38-merged.bed","sample":"Sample2"}    126581960
```

As you can see, it has multiple lines written in one. In another case, I had a lone "5" written on a single line. It looks like there is some kind of race condition when creating this file. The logs report errors with "file exists" in some cases, in fact.

This causes the pipeline to fail later, regardless:

```python
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 51, in _setup_logging
    yield config
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 242, in postprocess_alignment
    return ipython.zip_args(apply(sample.postprocess_alignment, *args))
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 254, in postprocess_alignment
    data = coverage.assign_interval(data)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/coverage.py", line 55, in assign_interval
    vrs or callable_file, "variant_regions")
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/coverage.py", line 66, in _count_offtarget
    mapped_unique = readstats.number_of_mapped_reads(data, bam_file, keep_dups=False)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/readstats.py", line 71, in number_of_mapped_reads
    for cur_key, cur_val in (l.strip().split("\t") for l in in_handle):
ValueError: too many values to unpack
```

Because of course the file is malformed.

**Comment by chapmanb** [comment]
Luca;
Thanks much for this report and apologies about the issue. We'd moved the statistics file into a single location to facilitate usage in CWL, where we won't have this kind of shared filesystem concurrent write issue, but I was hoping it wouldn't be a big problem until then. Thanks for reporting that you're hitting it. I pushed a fix to the latest development version that implements some simple locking to avoid these concurrent writes which will hopefully fix the issue entirely. Hope this fixes the issue for you and please let us know if you run into any other problems.
