### ISSUE TITLE
Run Strelka2: Uncaught exception occurred

### ISSUE THREAD

**Issue by hongenxu** [bcbio/bcbio-nextgen#2377]
Hi, 

thanks for providing such a nice framework. 

When I tried to call somatic mutation using vardict, mutect2 and strelka2, at the step of 

`/home/pmc1/local/share/bcbio/anaconda/bin/python /public/home/pmc1/proj/zhiping/proj/work/bcbiotx/tmpdjZQGx/batch1-Y_15513483_58820326-work/runWorkflow.py -m local -j 1 --quiet`

I got errors, 
```
[2018-04-22T22:17Z] Run Strelka2: Illumina_pt2_B1700
[2018-04-22T22:21Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/pmc1/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/pmc1/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command '/home/pmc1/local/share/bcbio/anaconda/bin/python /public/home/pmc1/proj/zhiping/proj/work/bcbiotx/tmpdjZQGx/batch1-Y_15513483_58820326-work/runWorkflow.py -m local -j 1 --quiet
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/home/pmc1/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 241, in <module>
    main(**kwargs)
  File "/home/pmc1/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/pmc1/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/home/pmc1/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/pmc1/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 146, in variant2pipeline
    samples = genotype.parallel_variantcall_region(samples, run_parallel)
  File "/home/pmc1/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 195, in parallel_variantcall_region
    "vrn_file", ["region", "sam_ref", "config"]))
  File "/home/pmc1/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 32, in grouped_parallel_split_combine
    final_output = parallel_fn(parallel_name, split_args)
  File "/home/pmc1/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/pmc1/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/home/pmc1/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/pmc1/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/pmc1/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/pmc1/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File "/home/pmc1/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 332, in __init__
    self.results = batch()
  File "/home/pmc1/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/pmc1/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/pmc1/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 275, in variantcall_sample
    return genotype.variantcall_sample(*args)
  File "/home/pmc1/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 351, in variantcall_sample
    out_file = caller_fn(align_bams, items, ref_file, assoc_files, region, out_file)
  File "/home/pmc1/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/strelka2.py", line 26, in run
    call_file = _run_somatic(paired, ref_file, assoc_files, region, call_file, strelka_work_dir)
  File "/home/pmc1/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/strelka2.py", line 245, in _run_somatic
    _run_workflow(paired.tumor_data, workflow_file, tx_work_dir)
  File "/home/pmc1/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/strelka2.py", line 257, in _run_workflow
    do.run(cmd, "Run Strelka2: %s" % dd.get_sample_name(data))
  File "/home/pmc1/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/pmc1/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command '/home/pmc1/local/share/bcbio/anaconda/bin/python /public/home/pmc1/proj/zhiping/proj/work/bcbiotx/tmpdjZQGx/batch1-Y_15513483_58820326-work/runWorkflow.py -m local -j 1 --quiet
```

Would you please help me figure out the problem?

Best,
Hongen

**Comment by chapmanb** [comment]
Hongen;
Apologies about the issue and thanks much for the report. Unfortunately we're not getting much debug information here to help isolate the cause of the issue with strelka2. strelka2 can generate a lot of log output so we have `--quiet` set which doesn't give us The best way to debug would be to look at `log/bcbio-nextgen-commands.log` and find the `configureStrelka*` command that immediately proceeds `runWorkflow.py` for the failing region. If you run those manually outside of bcbio to generate a workflow and then run it, without `--quiet`, that should hopefully provide more context to understand the error. Thanks for the help debugging and hope this helps.

**Comment by hongenxu** [comment]
thanks very much for your help. 

I rerun the job

`/home/pmc1/local/share/bcbio/anaconda/bin/python /public/home/pmc1/proj/zhiping/proj/work/bcbiotx/tmpdjZQGx/batch1-Y_15513483_58820326-work/runWorkflow.py -m local -j 1
`

and  got errors 

`
[2018-04-28T14:22:46.879810Z] [mu02] [63902_1] [WorkflowRunner] Initiating pyFlow run
[2018-04-28T14:22:46.893737Z] [mu02] [63902_1] [WorkflowRunner] pyFlowClientWorkflowClass: StrelkaSomaticWorkflow
[2018-04-28T14:22:46.896107Z] [mu02] [63902_1] [WorkflowRunner] pyFlowVersion: 1.1.20
[2018-04-28T14:22:46.898539Z] [mu02] [63902_1] [WorkflowRunner] pythonVersion: 2.7.14.final.0
[2018-04-28T14:22:46.900820Z] [mu02] [63902_1] [WorkflowRunner] WorkingDir: '/public/home/pmc1/proj/zhiping/proj/work/log'
[2018-04-28T14:22:46.902978Z] [mu02] [63902_1] [WorkflowRunner] ProcessCmdLine: '/public/home/pmc1/proj/zhiping/proj/work/bcbiotx/tmpdjZQGx/batch1-Y_15513483_58820326-work/runWorkflow.py -m local -j 1'
[2018-04-28T14:22:46.905300Z] [mu02] [63902_1] [WorkflowRunner] [RunParameters] mode: local
[2018-04-28T14:22:46.907315Z] [mu02] [63902_1] [WorkflowRunner] [RunParameters] nCores: 1
[2018-04-28T14:22:46.909565Z] [mu02] [63902_1] [WorkflowRunner] [RunParameters] memMb: 128649
[2018-04-28T14:22:46.911648Z] [mu02] [63902_1] [WorkflowRunner] [RunParameters] dataDir: /public/home/pmc1/proj/zhiping/proj/work/bcbiotx/tmpdjZQGx/batch1-Y_15513483_58820326-work/workspace/pyflow.data
[2018-04-28T14:22:46.913864Z] [mu02] [63902_1] [WorkflowRunner] [RunParameters] isDryRun: False
[2018-04-28T14:22:46.915783Z] [mu02] [63902_1] [WorkflowRunner] [RunParameters] isContinue: False
[2018-04-28T14:22:46.917665Z] [mu02] [63902_1] [WorkflowRunner] [RunParameters] isForceContinue: True
[2018-04-28T14:22:46.919255Z] [mu02] [63902_1] [WorkflowRunner] [RunParameters] mailTo: ''
[2018-04-28T14:22:46.921741Z] [mu02] [63902_1] [TaskRunner:masterWorkflow] Starting task specification for master workflow
[2018-04-28T14:22:46.923778Z] [mu02] [63902_1] [StrelkaSomaticWorkflow] Initiating Strelka somatic workflow version: 2.9.2
[2018-04-28T14:22:46.927860Z] [mu02] [63902_1] [WorkflowRunner] Adding sub-workflow task 'CallGenome' to master workflow
[2018-04-28T14:22:46.931498Z] [mu02] [63902_1] [TaskRunner:masterWorkflow] Finished task specification for master workflow
[2018-04-28T14:22:46.934194Z] [mu02] [63902_1] [TaskManager] Launching sub-workflow task: 'CallGenome' from master workflow
[2018-04-28T14:22:46.936545Z] [mu02] [63902_1] [TaskRunner:CallGenome] Starting task specification for sub-workflow
[2018-04-28T14:22:46.939132Z] [mu02] [63902_1] [WorkflowRunner] Adding command task 'CallGenome+makeTmpDir' to sub-workflow 'CallGenome'
[2018-04-28T14:22:46.946336Z] [mu02] [63902_1] [WorkflowRunner] Adding command task 'CallGenome+callGenomeSegment_chromId_023_Y_0000' to sub-workflow 'CallGenome'
[2018-04-28T14:22:46.949418Z] [mu02] [63902_1] [WorkflowRunner] Adding command task 'CallGenome+fixVcfHeader_chromId_023_Y_0000' to sub-workflow 'CallGenome'
[2018-04-28T14:22:46.952722Z] [mu02] [63902_1] [WorkflowRunner] Adding command task 'CallGenome+compressSegmentOutput_chromId_023_Y_0000' to sub-workflow 'CallGenome'
[2018-04-28T14:22:46.955399Z] [mu02] [63902_1] [TaskManager] Launching command task: 'CallGenome+makeTmpDir' from sub-workflow 'CallGenome'
[2018-04-28T14:22:46.958614Z] [mu02] [63902_1] [WorkflowRunner] Adding command task 'CallGenome+callGenomeSegment_chromId_023_Y_0001' to sub-workflow 'CallGenome'
[2018-04-28T14:22:46.961238Z] [mu02] [63902_1] [WorkflowRunner] Adding command task 'CallGenome+compressSegmentOutput_chromId_023_Y_0001' to sub-workflow 'CallGenome'
[2018-04-28T14:22:46.963999Z] [mu02] [63902_1] [WorkflowRunner] Adding command task 'CallGenome+callGenomeSegment_chromId_023_Y_0002' to sub-workflow 'CallGenome'
[2018-04-28T14:22:46.967784Z] [mu02] [63902_1] [WorkflowRunner] Adding command task 'CallGenome+compressSegmentOutput_chromId_023_Y_0002' to sub-workflow 'CallGenome'
[2018-04-28T14:22:46.971607Z] [mu02] [63902_1] [TaskRunner:CallGenome+makeTmpDir] Task initiated on local node
[2018-04-28T14:22:46.974072Z] [mu02] [63902_1] [WorkflowRunner] Adding command task 'CallGenome+callGenomeSegment_chromId_023_Y_0003' to sub-workflow 'CallGenome'
[2018-04-28T14:22:46.978296Z] [mu02] [63902_1] [WorkflowRunner] Adding command task 'CallGenome+compressSegmentOutput_chromId_023_Y_0003' to sub-workflow 'CallGenome'
[2018-04-28T14:22:46.982998Z] [mu02] [63902_1] [WorkflowRunner] Adding command task 'CallGenome+callGenomeSegment_chromId_023_Y_0004' to sub-workflow 'CallGenome'
[2018-04-28T14:22:46.985154Z] [mu02] [63902_1] [WorkflowRunner] Adding command task 'CallGenome+compressSegmentOutput_chromId_023_Y_0004' to sub-workflow 'CallGenome'
[2018-04-28T14:22:46.988107Z] [mu02] [63902_1] [WorkflowRunner] Adding command task 'CallGenome+completedAllGenomeSegments' to sub-workflow 'CallGenome'
[2018-04-28T14:22:46.990700Z] [mu02] [63902_1] [WorkflowRunner] Adding command task 'CallGenome+SNV_concat_vcf' to sub-workflow 'CallGenome'
[2018-04-28T14:22:46.993666Z] [mu02] [63902_1] [WorkflowRunner] Adding command task 'CallGenome+SNV_index_vcf' to sub-workflow 'CallGenome'
[2018-04-28T14:22:46.995928Z] [mu02] [63902_1] [WorkflowRunner] Adding command task 'CallGenome+Indel_concat_vcf' to sub-workflow 'CallGenome'
[2018-04-28T14:22:46.998181Z] [mu02] [63902_1] [WorkflowRunner] Adding command task 'CallGenome+Indel_index_vcf' to sub-workflow 'CallGenome'
[2018-04-28T14:22:47.000936Z] [mu02] [63902_1] [WorkflowRunner] Adding command task 'CallGenome+mergeRunStats' to sub-workflow 'CallGenome'
[2018-04-28T14:22:47.003246Z] [mu02] [63902_1] [WorkflowRunner] Adding command task 'CallGenome+removeTmpDir' to sub-workflow 'CallGenome'
[2018-04-28T14:22:47.006013Z] [mu02] [63902_1] [TaskRunner:CallGenome] Finished task specification for sub-workflow
[2018-04-28T14:22:47.122779Z] [mu02] [63902_1] [TaskManager] Completed command task: 'CallGenome+makeTmpDir' launched from sub-workflow 'CallGenome'
[2018-04-28T14:22:47.126118Z] [mu02] [63902_1] [TaskManager] Launching command task: 'CallGenome+callGenomeSegment_chromId_023_Y_0004' from sub-workflow 'CallGenome'
[2018-04-28T14:22:47.137717Z] [mu02] [63902_1] [TaskRunner:CallGenome+callGenomeSegment_chromId_023_Y_0004] Task initiated on local node
[2018-04-28T14:22:47.531155Z] [mu02] [63902_1] [TaskRunner:CallGenome+callGenomeSegment_chromId_023_Y_0004] [WARNING] Task: 'CallGenome+callGenomeSegment_chromId_023_Y_0004' failed but qualifies for retry. Total task failures (including this one): 1. Task command: '/home/pmc1/local/share/bcbio/anaconda/share/strelka-2.9.2-0/libexec/strelka2 --region Y:47498854-59373566 --ref /public/home/pmc1/local/share/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --max-indel-size 49 --call-regions-bed /public/home/pmc1/proj/zhiping/proj/work/strelka2/Y/batch1-Y_15513483_58820326-raw-regions-merged.bed.gz --min-mapping-quality 20 --somatic-snv-rate 0.0001 --shared-site-error-rate 0.0000000005 --shared-site-error-strand-bias-fraction 0.0 --somatic-indel-rate 0.000001 --shared-indel-error-factor 2.2 --tier2-min-mapping-quality 0 --strelka-snv-max-filtered-basecall-frac 0.4 --strelka-snv-max-spanning-deletion-frac 0.75 --strelka-snv-min-qss-ref 15 --strelka-indel-max-window-filtered-basecall-frac 0.3 --strelka-indel-min-qsi-ref 40 --ssnv-contam-tolerance 0.15 --indel-contam-tolerance 0.15 --somatic-snv-scoring-model-file /home/pmc1/local/share/bcbio/anaconda/share/strelka-2.9.2-0/share/config/somaticSNVScoringModels.json --somatic-indel-scoring-model-file /home/pmc1/local/share/bcbio/anaconda/share/strelka-2.9.2-0/share/config/somaticIndelScoringModels.json --normal-align-file /public/home/pmc1/proj/zhiping/proj/work/align/Illumina_pt2_B17NC/Illumina_pt2_B17NC-sort.bam --tumor-align-file /public/home/pmc1/proj/zhiping/proj/work/align/Illumina_pt2_B1700/Illumina_pt2_B1700-sort.bam --somatic-snv-file /public/home/pmc1/proj/zhiping/proj/work/bcbiotx/tmpdjZQGx/batch1-Y_15513483_58820326-work/workspace/genomeSegment.tmpdir/somatic.snvs.unfiltered.chromId_023_Y_0004.vcf --somatic-indel-file /public/home/pmc1/proj/zhiping/proj/work/bcbiotx/tmpdjZQGx/batch1-Y_15513483_58820326-work/workspace/genomeSegment.tmpdir/somatic.indels.unfiltered.chromId_023_Y_0004.vcf --stats-file /public/home/pmc1/proj/zhiping/proj/work/bcbiotx/tmpdjZQGx/batch1-Y_15513483_58820326-work/workspace/genomeSegment.tmpdir/runStats.chromId_023_Y_0004.xml --strelka-skip-header'
[2018-04-28T14:24:17.628341Z] [mu02] [63902_1] [TaskRunner:CallGenome+callGenomeSegment_chromId_023_Y_0004] Retrying task: 'CallGenome+callGenomeSegment_chromId_023_Y_0004'. Total prior task failures: 1
[2018-04-28T14:24:17.637649Z] [mu02] [63902_1] [TaskRunner:CallGenome+callGenomeSegment_chromId_023_Y_0004] Task initiated on local node
[2018-04-28T14:24:17.947165Z] [mu02] [63902_1] [TaskRunner:CallGenome+callGenomeSegment_chromId_023_Y_0004] [WARNING] Task: 'CallGenome+callGenomeSegment_chromId_023_Y_0004' failed but qualifies for retry. Total task failures (including this one): 2. Task command: '/home/pmc1/local/share/bcbio/anaconda/share/strelka-2.9.2-0/libexec/strelka2 --region Y:47498854-59373566 --ref /public/home/pmc1/local/share/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --max-indel-size 49 --call-regions-bed /public/home/pmc1/proj/zhiping/proj/work/strelka2/Y/batch1-Y_15513483_58820326-raw-regions-merged.bed.gz --min-mapping-quality 20 --somatic-snv-rate 0.0001 --shared-site-error-rate 0.0000000005 --shared-site-error-strand-bias-fraction 0.0 --somatic-indel-rate 0.000001 --shared-indel-error-factor 2.2 --tier2-min-mapping-quality 0 --strelka-snv-max-filtered-basecall-frac 0.4 --strelka-snv-max-spanning-deletion-frac 0.75 --strelka-snv-min-qss-ref 15 --strelka-indel-max-window-filtered-basecall-frac 0.3 --strelka-indel-min-qsi-ref 40 --ssnv-contam-tolerance 0.15 --indel-contam-tolerance 0.15 --somatic-snv-scoring-model-file /home/pmc1/local/share/bcbio/anaconda/share/strelka-2.9.2-0/share/config/somaticSNVScoringModels.json --somatic-indel-scoring-model-file /home/pmc1/local/share/bcbio/anaconda/share/strelka-2.9.2-0/share/config/somaticIndelScoringModels.json --normal-align-file /public/home/pmc1/proj/zhiping/proj/work/align/Illumina_pt2_B17NC/Illumina_pt2_B17NC-sort.bam --tumor-align-file /public/home/pmc1/proj/zhiping/proj/work/align/Illumina_pt2_B1700/Illumina_pt2_B1700-sort.bam --somatic-snv-file /public/home/pmc1/proj/zhiping/proj/work/bcbiotx/tmpdjZQGx/batch1-Y_15513483_58820326-work/workspace/genomeSegment.tmpdir/somatic.snvs.unfiltered.chromId_023_Y_0004.vcf --somatic-indel-file /public/home/pmc1/proj/zhiping/proj/work/bcbiotx/tmpdjZQGx/batch1-Y_15513483_58820326-work/workspace/genomeSegment.tmpdir/somatic.indels.unfiltered.chromId_023_Y_0004.vcf --stats-file /public/home/pmc1/proj/zhiping/proj/work/bcbiotx/tmpdjZQGx/batch1-Y_15513483_58820326-work/workspace/genomeSegment.tmpdir/runStats.chromId_023_Y_0004.xml --strelka-skip-header'`

this task "CallGenome+callGenomeSegment_chromId_023_Y_0004" failed. 
The problem is about Y chromosome. When I prepared the sample CSV, the gender information is missing, so I did not specify sex in the CSV file. I am not sure whether it will cause problem. 

Best,
Hongen

**Comment by chapmanb** [comment]
Hongen;
Thanks for running this and for providing the additional information. We shouldn't need gender information to call on X/Y chromosomes, so I'm not entirely positive what the issue is from just this traceback. If you look in the log files in:
```
/public/home/pmc1/proj/zhiping/proj/work/bcbiotx/tmpdjZQGx/batch1-Y_15513483_58820326-work/
```
Do they provide any additional information about the error message? Specifically `workflow.error.log.txt` might have a more detailed traceback about why the `CallGenome+callGenomeSegment_chromId_023_Y_0004` subtask within strelka2 failed. Thanks much for the help debugging.

**Comment by hongenxu** [comment]
After reformating the fastq file, streka2 is successful. Thanks.

**Comment by chapmanb** [comment]
Thanks for following up and I'm glad this debugging got your analysis finished.
