### ISSUE TITLE
Peddy error in Mutect2 pipeline

### ISSUE THREAD

**Issue by phu5ion** [bcbio/bcbio-nextgen#2388]
Hi,

While running Mutect2 for the first time, I've met with this error in peddy:
```
[2018-05-02T03:03Z] Skipping peddy because no variants overlap with checks: MCYK00017
[2018-05-02T03:03Z] peddy is not installed, not human or sample VCFs don't match, skipping correspondence checking for None.
[2018-05-02T03:03Z] Running peddy on /mnt/projects/ngbhs/cirqseq/2017_bcbio/20170417_breast/20180426_mutect2/work/mutect2/MBC062-17042015-vepeffects-annotated.vcf.gz against /mnt/projects/ngbhs/cirqseq/2017_bcbio/20170417_breast/20180426_mutect2/work/mutect2/MBC062-17042015-vepeffects-annotated.ped.
[2018-05-02T03:03Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/bin/peddy -p 16 --plot --prefix /mnt/projects/ngbhs/cirqseq/2017_bcbio/20170417_breast/20180426_mutect2/work/bcbiotx/tmprrZV0q/MBC062-17042015 /mnt/projects/ngbhs/cirqseq/2017_bcbio/20170417_breast/20180426_mutect2/work/mutect2/MBC062-17042015-vepeffects-annotated.vcf.gz /mnt/projects/ngbhs/cirqseq/2017_bcbio/20170417_breast/20180426_mutect2/work/mutect2/MBC062-17042015-vepeffects-annotated.ped 2> /mnt/projects/ngbhs/cirqseq/2017_bcbio/20170417_breast/20180426_mutect2/work/bcbiotx/tmprrZV0q/run-stderr.log
' returned non-zero exit status 1
```
When I just ran the command that failed above, there is a further error on missing intervals:
```
[dlho@n007 /mnt/projects/ngbhs/cirqseq/2017_bcbio/20170417_breast/20180426_mutect2]/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/bin/peddy -p 16 --plot --prefix /mnt/projects/ngbhs/cirqseq/2017_bcbio/20170417_breast/20180426_mutect2/work/bcbiotx/tmprrZV0q/MBC062-17042015 /mnt/projects/ngbhs/cirqseq/2017_bcbio/20170417_breast/20180426_mutect2/work/mutect2/MBC062-17042015-vepeffects-annotated.vcf.gz /mnt/projects/ngbhs/cirqseq/2017_bcbio/20170417_breast/20180426_mutect2/work/mutect2/MBC062-17042015-vepeffects-annotated.ped
2018-05-02 11:14:29 n007 peddy.cli[228521] INFO Running Peddy version 0.3.1
2018-05-02 11:14:29 n007 peddy.cli[228521] WARNING 1 samples in vcf not in ped:
BC062-17042015_N

2018-05-02 11:14:29 n007 peddy.cli[228521] INFO ped_check
no intervals found for /mnt/projects/ngbhs/cirqseq/2017_bcbio/20170417_breast/20180426_mutect2/work/mutect2/MBC062-17042015-vepeffects-annotated.vcf.gz at chr21:19756040-19756040
no intervals found for /mnt/projects/ngbhs/cirqseq/2017_bcbio/20170417_breast/20180426_mutect2/work/mutect2/MBC062-17042015-vepeffects-annotated.vcf.gz at chr21:30408670-30408670
no intervals found for /mnt/projects/ngbhs/cirqseq/2017_bcbio/20170417_breast/20180426_mutect2/work/mutect2/MBC062-17042015-vepeffects-annotated.vcf.gz at chr21:33785343-33785343
no intervals found for /mnt/projects/ngbhs/cirqseq/2017_bcbio/20170417_breast/20180426_mutect2/work/mutect2/MBC062-17042015-vepeffects-annotated.vcf.gz at chr21:35138326-35138326
no intervals found for /mnt/projects/ngbhs/cirqseq/2017_bcbio/20170417_breast/20180426_mutect2/work/mutect2/MBC062-17042015-vepeffects-annotated.vcf.gz at chr21:37518362-37518362
...
```

I thought I read from somewhere that if peddy is not available it will skip the tool? Anyway upgrading to the newest developmental version doesn't solve the problem. Could someone help pls?

**Comment by roryk** [comment]
Hi @phu5ion,

Could you post the entire log from the failed command so we can debug it? Thanks!

**Comment by roryk** [comment]
No worries, thanks for following up!
