### ISSUE TITLE
damage_filter is not too well tolerated by pysam

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2399]
cc @LMannarino

Apparently the INFO field that is being added by the bias filter isn't well tolerated by pysam:

```python
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/bin/bcbio_nextgen.py", line 241, in <module>
    main(**kwargs)
  File "/opt/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 53, in run_main
    fc_dir, run_info_yaml)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 192, in variant2pipeline
    samples = qcsummary.generate_parallel(samples, run_parallel)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 37, in generate_parallel
    qced = run_parallel("pipeline_summary", to_analyze)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipython.py", line 137, in run
    for data in view.map_sync(fn, items, track=False):
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 342, in map_sync
    return self.map(f,*sequences,**kwargs)
  File "<decorator-gen-137>", line 2, in map
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 50, in sync_results
    ret = f(self, *args, **kwargs)
  File "<decorator-gen-136>", line 2, in map
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 35, in save_ids
    ret = f(self, *args, **kwargs)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 1109, in map
    return pf.map(*sequences)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 285, in map
    return self(*sequences, __ipp_mapping=True)
  File "<decorator-gen-119>", line 2, in __call__
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 76, in sync_view_results
    return f(self, *args, **kwargs)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 271, in __call__
    return r.get()
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/asyncresult.py", line 167, in get
    raise self.exception()
ipyparallel.error.CompositeError: one or more exceptions from call to method: pipeline_summary
[0:apply]: CalledProcessError: Command 'dkfzbiasfilter_summarize.py --sample=CR02-18-basal --outfile=/scratch/tmppPNcy3/CR02-18-basal-damage.yaml /bioinformatics/laura/CaseReport/CR02-18/CR02-18/work/ensemble/CR02-18-basal_vs_blood/CR02-18-basal_vs_blood-ensemble-vepeffects.vcf.gz
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/bin/dkfzbiasfilter_summarize.py", line 152, in <module>
    main(args[0], options)
  File "/opt/bcbio/anaconda/bin/dkfzbiasfilter_summarize.py", line 52, in main
    depths_pass = pass_support(rec, depths_pass)
  File "/opt/bcbio/anaconda/bin/dkfzbiasfilter_summarize.py", line 87, in pass_support
    summarized = dict(summarize_support(rec))
  File "/opt/bcbio/anaconda/bin/dkfzbiasfilter_summarize.py", line 120, in summarize_support
    for i, (base, val) in enumerate(zip(fields, rec.info[key])):
  File "pysam/libcbcf.pyx", line 2556, in pysam.libcbcf.VariantRecordInfo.__getitem__
KeyError: 'Invalid INFO field: ACGTNacgtnPLUS'
' returned non-zero exit status 1
```
It looks more like an upstream problem, but others may stumble upon this.

**Comment by chapmanb** [comment]
Luca -- thanks for the report and sorry about the problem. This looks like an issue with the `dkfzbiasfilter_summarize.py` script that I wrote. One of your input lines is missing the `ACGTNacgtnPLUS` and the code assumes they're all present as part of the filter output. Are you able to share the problem VCF file that's feeding into it? Is it annotated by the bias filter with these fields in general? I'm guessing some post-processing step split variants and lines might be missing them but will need to work to track down what is going wrong. Thanks for the help debugging.

**Comment by chapmanb** [comment]
Luca and Laura -- thanks much for sending along the example VCF and for reporting the issue. I'm not entirely sure how we got a decomposed variant without the bias information but pushed a fix that should handle this by correctly avoiding pulling stats on non-annotated records. If you update with:
```
bcbio_nextgen.py upgrade --tools
```
it should get the latest version of DKFZ bias filter that will work on your inputs. Thank you again and please let us know if you run into any other issues.
