### ISSUE TITLE
Issue #2283 peddy failure occurring again in 1.0.9 release

### ISSUE THREAD

**Issue by ameynert** [bcbio/bcbio-nextgen#2400]
https://github.com/bcbio/bcbio-nextgen/issues/2283

Suspect code at line 91, change listed is from my patch to my 1.0.7 installation:

```
<             if to_show[-1].find("IndexError") >=0 and to_show[-1].find("is out of bounds for axis") >= 0:
>             if any([l.find("IndexError") >=0 and l.find("is out of bounds for axis") >= 0
```

**Comment by ameynert** [comment]
It's a clean install of the latest stable bcbio release. Log file:

```
[2018-05-15T10:53Z] multiprocessing: run_peddy
[2018-05-15T10:53Z] Running peddy on /gpfs/igmmfs01/eddie/omics-seq/lg_exome_seq/work/NI_10030/ensemble/lg_exome_seq/lg_exome_seq-ensemble-vepeffects.vcf.gz against /gpfs/igmmfs01/eddie/omics-seq/lg_exome_seq/work/NI_10030/ensemble/lg_exome_seq/lg_exome_seq-ensemble-vepeffects.ped.
[2018-05-15T10:54Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /exports/igmm/eddie/omics-seq/software/bcbio/anaconda/bin/peddy -p 2 --plot --prefix /gpfs/igmmfs01/eddie/omics-seq/lg_exome_seq/work/NI_10030/bcbiotx/tmp2DlUwM/lg_exome_seq /gpfs/igmmfs01/eddie/omics-seq/lg_exome_seq/work/NI_10030/ensemble/lg_exome_seq/lg_exome_seq-ensemble-vepeffects.vcf.gz /gpfs/igmmfs01/eddie/omics-seq/lg_exome_seq/work/NI_10030/ensemble/lg_exome_seq/lg_exome_seq-ensemble-vepeffects.ped 2> /gpfs/igmmfs01/eddie/omics-seq/lg_exome_seq/work/NI_10030/bcbiotx/tmp2DlUwM/run-stderr.log
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/exports/igmm/eddie/omics-seq/software/bcbio/tools/bin/bcbio_nextgen.py", line 241, in <module>
    main(**kwargs)
  File "/exports/igmm/eddie/omics-seq/software/bcbio/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
[2018-05-15T10:54Z] 2018-05-15 11:53:55 node1f15.ecdf.ed.ac.uk peddy.cli[89588] INFO Running Peddy version 0.3.1
2018-05-15 11:53:55 node1f15.ecdf.ed.ac.uk peddy.cli[89588] INFO ped_check
2018-05-15 11:53:56 node1f15.ecdf.ed.ac.uk matplotlib.font_manager[89588] INFO font search path ['/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/ttf', '/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/afm', '/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/pdfcorefonts']
Traceback (most recent call last):
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/bin/peddy", line 11, in <module>
    load_entry_point('peddy==0.3.1', 'console_scripts', 'peddy')()
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/peddy/cli.py", line 204, in peddy
    in ("ped_check", "het_check", "sex_check")]):
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/peddy/cli.py", line 43, in run
    prefix=prefix, **kwargs)
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/peddy/peddy.py", line 1027, in ped_check
    from matplotlib import pyplot as plt
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/matplotlib/pyplot.py", line 31, in <module>
    import matplotlib.colorbar
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/matplotlib/colorbar.py", line 36, in <module>
    import matplotlib.contour as contour
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/matplotlib/contour.py", line 20, in <module>
    import matplotlib.font_manager as font_manager
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py", line 1469, in <module>
    _rebuild()
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py", line 1454, in _rebuild
    json_dump(fontManager, _fmcache)
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py", line 979, in json_dump
    warnings.warn('Could not save font_manager cache ', e)
TypeError: issubclass() arg 1 must be a class

    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 184, in variant2pipeline
    samples = peddy.run_peddy_parallel(samples, run_parallel)
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/peddy.py", line 32, in run_peddy_parallel
    samples = parallel_fn("run_peddy", [[x] for x in to_run])
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 332, in __init__
    self.results = batch()
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 22, in run_peddy
    return peddy.run_peddy(*args)
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/peddy.py", line 85, in run_peddy
    do.run(cmd.format(**locals()), message.format(**locals()))
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/exports/igmm/eddie/omics-seq/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /exports/igmm/eddie/omics-seq/software/bcbio/anaconda/bin/peddy -p 2 --plot --prefix /gpfs/igmmfs01/eddie/omics-seq/lg_exome_seq/work/NI_10030/bcbiotx/tmp2DlUwM/lg_exome_seq /gpfs/igmmfs01/eddie/omics-seq/lg_exome_seq/work/NI_10030/ensemble/lg_exome_seq/lg_exome_seq-ensemble-vepeffects.vcf.gz /gpfs/igmmfs01/eddie/omics-seq/lg_exome_seq/work/NI_10030/ensemble/lg_exome_seq/lg_exome_seq-ensemble-vepeffects.ped 2> /gpfs/igmmfs01/eddie/omics-seq/lg_exome_seq/work/NI_10030/bcbiotx/tmp2DlUwM/run-stderr.log
' returned non-zero exit status 1
```

**Comment by chapmanb** [comment]
Alison;
Thanks for the traceback, this is really helpful for tracking down the problem. It looks like you're hitting a different issue which is why the bcbio code is not catching it. There is something problematic about setting up the fonts for matplotlib so you hit the bug described here:

https://github.com/matplotlib/matplotlib/pull/9676

It looks to be present in matplotlib 2.2.2 and there has not yet been a new release with a fix. If you do:
```
bcbio_conda install -c conda-forge matplotlib=2.2.0
```
That should hopefully fix the issue in the short term. Please let me know if you're still stuck after this. Thanks again for the report and helping debug.
