### ISSUE TITLE
CWL: cromwell/torque error

### ISSUE THREAD

**Issue by matthdsm** [bcbio/bcbio-nextgen#2406]
Hi Brad,

I'm testing the new cromwell integration in bcbio and I've run into the following error:
```
[2018-05-29 10:27:21,91] [warn] TORQUE [13b3db38]: Key/s [docker] is/are not supported by backend. Unsupported attributes will not be part of job executions.
```
followed by

```
[2018-05-29 10:27:25,61] [info] DispatchedConfigAsyncJobExecutionActor [13b3db38alignment_to_rec:NA:1]: executing: qsub -V -l wd -N cromwell_13b3db38_alignment_to_rec -o /kyukon/data/gent/gvo000/gvo00082/vsc41443/D1614040_WGS/cromwell_work/cromwell-executions/main-genome.cwl/13b3db38-a9c7-4e85-b33e-4cb322f54ef4/call-alignment_to_rec/execution/stdout -e /kyukon/data/ge
nt/gvo000/gvo00082/vsc41443/D1614040_WGS/cromwell_work/cromwell-executions/main-genome.cwl/13b3db38-a9c7-4e85-b33e-4cb322f54ef4/call-alignment_to_rec/execution/stderr -q long         -l nodes=1:ppn=1 -l mem=2147mb -l walltime=24:00:00         -- /usr/bin/env bash /kyukon/data/gent/gvo000/gvo00082/vsc41443/D1614040_WGS/cromwell_work/cromwell-executions/main-genome.cwl/
13b3db38-a9c7-4e85-b33e-4cb322f54ef4/call-alignment_to_rec/execution/script
[2018-05-29 10:27:26,20] [error] WorkflowManagerActor Workflow 13b3db38-a9c7-4e85-b33e-4cb322f54ef4 failed (during ExecutingWorkflowState): Unable to start job. Check the stderr file for possible errors: /kyukon/data/gent/gvo000/gvo00082/vsc41443/D1614040_WGS/cromwell_work/cromwell-executions/main-genome.cwl/13b3db38-a9c7-4e85-b33e-4cb322f54ef4/call-alignment_to_rec/e
xecution/stderr.submit
java.lang.RuntimeException: Unable to start job. Check the stderr file for possible errors: /kyukon/data/gent/gvo000/gvo00082/vsc41443/D1614040_WGS/cromwell_work/cromwell-executions/main-genome.cwl/13b3db38-a9c7-4e85-b33e-4cb322f54ef4/call-alignment_to_rec/execution/stderr.submit
        at cromwell.backend.sfs.SharedFileSystemAsyncJobExecutionActor.$anonfun$execute$2(SharedFileSystemAsyncJobExecutionActor.scala:131)
        at scala.util.Either.fold(Either.scala:188)
        at cromwell.backend.sfs.SharedFileSystemAsyncJobExecutionActor.execute(SharedFileSystemAsyncJobExecutionActor.scala:126)
        at cromwell.backend.sfs.SharedFileSystemAsyncJobExecutionActor.execute$(SharedFileSystemAsyncJobExecutionActor.scala:121)
        at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.execute(ConfigAsyncJobExecutionActor.scala:208)
        at cromwell.backend.standard.StandardAsyncExecutionActor.$anonfun$executeAsync$1(StandardAsyncExecutionActor.scala:459)
        at scala.util.Try$.apply(Try.scala:209)
        at cromwell.backend.standard.StandardAsyncExecutionActor.executeAsync(StandardAsyncExecutionActor.scala:459)
        at cromwell.backend.standard.StandardAsyncExecutionActor.executeAsync$(StandardAsyncExecutionActor.scala:459)
        at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.executeAsync(ConfigAsyncJobExecutionActor.scala:208)
        at cromwell.backend.standard.StandardAsyncExecutionActor.executeOrRecover(StandardAsyncExecutionActor.scala:753)
        at cromwell.backend.standard.StandardAsyncExecutionActor.executeOrRecover$(StandardAsyncExecutionActor.scala:745)
        at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.executeOrRecover(ConfigAsyncJobExecutionActor.scala:208)
        at cromwell.backend.async.AsyncBackendJobExecutionActor.$anonfun$robustExecuteOrRecover$1(AsyncBackendJobExecutionActor.scala:65)
        at cromwell.core.retry.Retry$.withRetry(Retry.scala:37)
        at cromwell.backend.async.AsyncBackendJobExecutionActor.withRetry(AsyncBackendJobExecutionActor.scala:61)
        at cromwell.backend.async.AsyncBackendJobExecutionActor.cromwell$backend$async$AsyncBackendJobExecutionActor$$robustExecuteOrRecover(AsyncBackendJobExecutionActor.scala:65)
        at cromwell.backend.async.AsyncBackendJobExecutionActor$$anonfun$receive$1.applyOrElse(AsyncBackendJobExecutionActor.scala:88)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
        at akka.actor.Actor.aroundReceive(Actor.scala:514)
        at akka.actor.Actor.aroundReceive$(Actor.scala:512)
        at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.aroundReceive(ConfigAsyncJobExecutionActor.scala:208)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
        at akka.actor.ActorCell.invoke(ActorCell.scala:496)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

The stderr file contains `qsub: script file 'bash' cannot be loaded - No such file or directory`
Which leads me to believe there's something wrong with the qsub command.
```
qsub -V -l wd -N cromwell_13b3db38_alignment_to_rec -o /kyukon/data/gent/gvo000/gvo00082/vsc41443/D1614040_WGS/cromwell_work/cromwell-executions/main-genome.cwl/13b3db38-a9c7-4e85-b33e-4cb322f54ef4/call-alignment_to_rec/execution/stdout -e /kyukon/data/gent/gvo000/gvo00082/vsc41443/D1614040_WGS/cromwell_work/cromwell-executions/main-genome.cwl/13b3db38-a9c7-4e85-b33e-4cb322f54ef4/call-alignment_to_rec/execution/stderr -q long -l nodes=1:ppn=1 -l mem=2147mb -l walltime=24:00:00 -- /usr/bin/env bash /kyukon/data/gent/gvo000/gvo00082/vsc41443/D1614040_WGS/cromwell_work/cromwell-executions/main-genome.cwl/13b3db38-a9c7-4e85-b33e-4cb322f54ef4/call-alignment_to_rec/execution/script
```

I'm not sure what you mean with the ` -- /usr/bin/env bash` flag in the command, as this seems to be the source of the issue.

Cheers
M

**Comment by matthdsm** [comment]
fixed in #2407, tested and works like a charm.

M

**Comment by matthdsm** [comment]
Hi Brad,
FYI: in the previous PR, I hadn't readded the `-S /bin/bash`.

On another note. With the recent edits, jobs runs smoothly and cromwell performs great. However, at the end of the pipeline I still encountered some typing issues.
Perhaps you can make more of this:
```
[2018-05-30 19:02:47,49] [info] d82c00ca-7641-40d9-ae9a-b075bd84493b-SubWorkflowActor-SubWorkflow-variantcall:0:1 [d82c00ca]: Workflow wf-variantcall.cwl complete. Final Outputs:
{
  "wf-variantcall.cwl.vc_rec": "[typed object {genome_resources__aliases__human: true, genome_build: \"hg38\", config__algorithm__tools_on: [\"coverage_perbase\"], validate__summary: null, config__algorithm__cal
lable_regions: \"/kyukon/data/gent/gvo000/gvo00082/vsc41443/D1614040_WGS/cromwell_work/cromwell-executions/main-genome.cwl/0e49e364-9158-4bb1-8401-7a3f920236aa/call-variantcall/shard-0/wf-variantcall.cwl/d82c00c
a-7641-40d9-ae9a-b075bd84493b/call-compare_to_rm/inputs/252955174/D1614040-analysis_blocks.bed\", metadata__batch: null, description: \"D1614040\", config__algorithm__effects: false, validate__fp: null, referenc
e__genome_context: [\"/kyukon/data/gent/gvo000/gvo00082/vsc41443/D1614040_WGS/cromwell_work/cromwell-executions/main-genome.cwl/0e49e364-9158-4bb1-8401-7a3f920236aa/call-variantcall/shard-0/wf-variantcall.cwl/d8
2c00ca-7641-40d9-ae9a-b075bd84493b/call-compare_to_rm/inputs/-1426330849/polyx.bed.gz\", \"/kyukon/data/gent/gvo000/gvo00082/vsc41443/D1614040_WGS/cromwell_work/cromwell-executions/main-genome.cwl..."
}
[2018-05-30 19:02:48,92] [error] WorkflowManagerActor Workflow 0e49e364-9158-4bb1-8401-7a3f920236aa failed (during ExecutingWorkflowState): Error(s):
No coercion defined from wom value(s) 'null' of type 'Array[String]?' to 'Array[String]'.
No coercion defined from wom value(s) 'null' of type 'class wom.types.WomMaybePopulatedFileType$?' to 'class wom.types.WomMaybePopulatedFileType$'.
No coercion defined from wom value(s) 'null' of type 'class wom.types.WomMaybePopulatedFileType$?' to 'class wom.types.WomMaybePopulatedFileType$'.
No coercion defined from wom value(s) 'null' of type 'String?' to 'String'.
No coercion defined from wom value(s) 'null' of type 'class wom.types.WomMaybePopulatedFileType$?' to 'class wom.types.WomMaybePopulatedFileType$'.
No coercion defined from wom value(s) 'null' of type 'String?' to 'String'.
No coercion defined from wom value(s) 'null' of type 'class wom.types.WomMaybePopulatedFileType$?' to 'class wom.types.WomMaybePopulatedFileType$'.
No coercion defined from wom value(s) 'null' of type 'class wom.types.WomMaybePopulatedFileType$?' to 'class wom.types.WomMaybePopulatedFileType$'.
No coercion defined from wom value(s) 'null' of type 'String?' to 'String'.
common.exception.AggregatedMessageException: Error(s):
No coercion defined from wom value(s) 'null' of type 'Array[String]?' to 'Array[String]'.
No coercion defined from wom value(s) 'null' of type 'class wom.types.WomMaybePopulatedFileType$?' to 'class wom.types.WomMaybePopulatedFileType$'.
No coercion defined from wom value(s) 'null' of type 'class wom.types.WomMaybePopulatedFileType$?' to 'class wom.types.WomMaybePopulatedFileType$'.
No coercion defined from wom value(s) 'null' of type 'String?' to 'String'.
No coercion defined from wom value(s) 'null' of type 'class wom.types.WomMaybePopulatedFileType$?' to 'class wom.types.WomMaybePopulatedFileType$'.
No coercion defined from wom value(s) 'null' of type 'String?' to 'String'.
No coercion defined from wom value(s) 'null' of type 'class wom.types.WomMaybePopulatedFileType$?' to 'class wom.types.WomMaybePopulatedFileType$'.
No coercion defined from wom value(s) 'null' of type 'class wom.types.WomMaybePopulatedFileType$?' to 'class wom.types.WomMaybePopulatedFileType$'.
No coercion defined from wom value(s) 'null' of type 'String?' to 'String'.
        at common.validation.Validation$ValidationTry$.toTry$extension1(Validation.scala:60)
        at common.validation.Validation$ValidationTry$.toTry$extension0(Validation.scala:56)
        at wom.values.WomObject$.withType(WomObject.scala:80)
        at cwl.CwlJsonToDelayedCoercionFunction$.$anonfun$onObject$9(CwlJsonToDelayedCoercionFunction.scala:80)
        at cats.data.Validated.map(Validated.scala:194)
        at cwl.CwlJsonToDelayedCoercionFunction$.$anonfun$onObject$1(CwlJsonToDelayedCoercionFunction.scala:80)
        at cwl.CwlJsonToDelayedCoercionFunction$.$anonfun$onArray$2(CwlJsonToDelayedCoercionFunction.scala:40)
        at cats.instances.ListInstances$$anon$1.$anonfun$traverse$2(list.scala:73)
        at cats.instances.ListInstances$$anon$1.loop$2(list.scala:63)
        at cats.instances.ListInstances$$anon$1.$anonfun$foldRight$2(list.scala:65)
        at cats.Eval$.advance(Eval.scala:272)
        at cats.Eval$.loop$1(Eval.scala:354)
        at cats.Eval$.cats$Eval$$evaluate(Eval.scala:372)
        at cats.Eval$Defer.value(Eval.scala:258)
        at cats.instances.ListInstances$$anon$1.traverse(list.scala:72)
        at cats.instances.ListInstances$$anon$1.traverse(list.scala:12)
        at cats.Traverse$Ops.traverse(Traverse.scala:19)
        at cats.Traverse$Ops.traverse$(Traverse.scala:19)
        at cats.Traverse$ToTraverseOps$$anon$3.traverse(Traverse.scala:19)
        at cwl.CwlJsonToDelayedCoercionFunction$.$anonfun$onArray$1(CwlJsonToDelayedCoercionFunction.scala:40)
        at cwl.CommandLineTool.$anonfun$outputEvaluationJsonFunction$2(CommandLineTool.scala:159)
        at scala.Option.map(Option.scala:146)
        at cwl.CommandLineTool.$anonfun$outputEvaluationJsonFunction$1(CommandLineTool.scala:159)
        at cats.instances.ListInstances$$anon$1.$anonfun$traverse$2(list.scala:73)
        at cats.instances.ListInstances$$anon$1.loop$2(list.scala:63)
        at cats.instances.ListInstances$$anon$1.$anonfun$foldRight$2(list.scala:65)
        at cats.Eval$.advance(Eval.scala:272)
        at cats.Eval$.loop$1(Eval.scala:354)
        at cats.Eval$.cats$Eval$$evaluate(Eval.scala:372)
        at cats.Eval$Defer.value(Eval.scala:258)
        at cats.instances.ListInstances$$anon$1.traverse(list.scala:72)
        at cats.instances.ListInstances$$anon$1.traverse(list.scala:12)
        at cats.Traverse$Ops.traverse(Traverse.scala:19)
        at cats.Traverse$Ops.traverse$(Traverse.scala:19)
        at cats.Traverse$ToTraverseOps$$anon$3.traverse(Traverse.scala:19)
        at cwl.CommandLineTool.jsonToOutputs$1(CommandLineTool.scala:151)
        at cwl.CommandLineTool.$anonfun$outputEvaluationJsonFunction$8(CommandLineTool.scala:169)
        at scala.util.Either.flatMap(Either.scala:338)
        at cwl.CommandLineTool.parseContent$1(CommandLineTool.scala:168)
        at cwl.CommandLineTool.$anonfun$outputEvaluationJsonFunction$12(CommandLineTool.scala:181)
        at scala.Option.map(Option.scala:146)
        at cats.data.OptionT.$anonfun$map$1(OptionT.scala:29)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:289)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[2018-05-30 19:02:48,92] [info] WorkflowManagerActor WorkflowActor-0e49e364-9158-4bb1-8401-7a3f920236aa is in a terminal state: WorkflowFailedState
[2018-05-30 19:03:28,09] [info] SingleWorkflowRunnerActor workflow finished with status 'Failed'.
[2018-05-30 19:03:32,78] [info] Automatic shutdown of the async connection
[2018-05-30 19:03:32,78] [info] Gracefully shutdown sentry threads.
[2018-05-30 19:03:32,78] [info] Shutdown finished.
Failed bcbio Cromwell run
-------------------------
Failure in step: normalize_sv_coverage.0
  bcbio log file     : cromwell_work/cromwell-executions/main-genome.cwl/0e49e364-9158-4bb1-8401-7a3f920236aa/call-normalize_sv_coverage/execution/log/bcbio-nextgen-debug.log
  bcbio commands file: cromwell_work/cromwell-executions/main-genome.cwl/0e49e364-9158-4bb1-8401-7a3f920236aa/call-normalize_sv_coverage/execution/log/bcbio-nextgen-commands.log
  Cromwell directory : cromwell_work/cromwell-executions/main-genome.cwl/0e49e364-9158-4bb1-8401-7a3f920236aa/call-normalize_sv_coverage
```
The logs specified at the end are empty, so no help there.

Any ideas?

Thanks
M

**Comment by chapmanb** [comment]
Matthias;
Sorry about the run problem and thank you for the detailed report. It looks like something is problematic about the outputs of that process as you got null values instead of the expected record outputs. I'm not positive if this is happening because of a run error or we're not handling a case with your configuration. For the former, are there any errors reported in the stdout/stderr?
```
cromwell_work/cromwell-executions/main-genome.cwl/0e49e364-9158-4bb1-8401-7a3f920236aa/call-normalize_sv_coverage/execution/stdout
cromwell_work/cromwell-executions/main-genome.cwl/0e49e364-9158-4bb1-8401-7a3f920236aa/call-normalize_sv_coverage/execution/stderr
```
If those are also empty, would you be able to share the YAML you're using so I can see if I can replicate and identify the issue? Thanks much for the help debugging.

**Comment by matthdsm** [comment]
Hi Brad,

thanks for the help,
Unfortunately, both the `stderr` and `stdout` files are empty. 
I'm using the following config:
```
fc_name: D1614040_WGS
upload:
  dir: ../final
globals:
  analysis_regions: /bcbio/genomes/Hsapiens/hg38/regions/RefSeqExomeAndPanels_20171003.bed
  coverage_regions: /bcbio/genomes/Hsapiens/hg38/regions/RefSeqExomeAndPanels_20171003.bed
resources:
  tmp:
    dir: $VSC_SCRATCH_VO_USER/bcbio
details:
  - analysis: variant2
    genome_build: hg38
    description: D1614040
    algorithm:
      aligner: bwa
      save_diskspace: true
      coverage_interval: genome
      mark_duplicates: true
      recalibrate: false
      realign: false
      variantcaller: gatk-haplotype
      svcaller: [lumpy, manta]
      effects: false
      tools_on:
        - coverage_perbase
      tools_off:
        - gemini
    files:
        - ../input/D1614040_S9_L008_R2_001.fastq.gz
        - ../input/D1614040_S9_L008_R1_001.fastq.gz
```

Am I asking anything that isn't CWL ready yet?
Thanks
M

**Comment by ruchim** [comment]
Hello @matthdsm,

Cromwell is looking into this error. Can you please point me to workflow you tried to run? Thanks!

**Comment by chapmanb** [comment]
Matthias;
I think I've isolated the problem and pushed a fix. If you can update the bcbio instance you're using for running (`bcbio_nextgen.py upgrade -u development`) and re-run I hope it will now do the right thing. This looked like an error when CNVkit was not enabled since bcbio skipped some calculations for SV coverage that it doesn't need without CNV calling and was not returning an object CWL was happy with. I got an error message at these steps, rather than an empty message, so hopefully this isolates the right issue. Thanks again for the feedback and testing, please feel free to re-open if you're sill finding issues.

**Comment by matthdsm** [comment]
Hi Brad,

I noticed that our HPC cluster is starting to limit my job submission because of the high volume of jobs from cromwell. Is there a flag I can use to set the walltime and/or cpu req's for the cromwell jobs? As it is now, alle jobs ask for 24h cputime, which makes it default to the "long" job queue. This requirement is way too high for a single WGS sample. I'd like to shorten it so I can use the "short" queue to make my job run faster.

On the same note, the jobs that were submitted last week got killed for some reason, but the cromwell monitor didn't pick it up and was just left waiting.

Cheers
M

**Comment by chapmanb** [comment]
Matthias;
Glad you got the walltime parameters configured, please let us know if you hit any issues with that.

For the Cromwell issues, if you can provide a detailed example of what is going wrong it would be worth raising an issue in the Cromwell repo (and cc'ing me in) to see if they have advice/suggestions about how best to manage when jobs get unexpectedly killed by the scheduler. It's possible we're missing something with querying the scheduler for job status but I don't have a full picture of how Cromwell manages this yet. Thanks again for testing.
