### ISSUE TITLE
Mysterious peddy error: works on 1:17704860-18004860, but fails on 1:171000000-172000000 in NA12878

### ISSUE THREAD

**Issue by naumenko-sa** [bcbio/bcbio-nextgen#2413]
Hello guys!

Thanks for the great pipeline! 

I needed a small test for a tutorial, which would run in minutes, and discovered that variant2 works when called with bed: 1:17,704,860-18,004,860, but fails with 1:171,000,000-172,000,000 in NA12878 WES
because of peddy.

Why is that? I needed the particular interval to show rare variant discovery.

Thanks!
Sergey

**Comment by naumenko-sa** [comment]
1 megabase on chr22 works fine:
22:22,000,000-23,000,000

**Comment by chapmanb** [comment]
Sergey;
Sorry about the issue. What error are you seeing with peddy? It's likely that the subset doesn't have an overlapping markers with peddy so errors out. We try to catch these errors and continue, but this might be triggering a new issue that we're not correctly dealing with. If you could post the full traceback we can hopefully correctly catch and skip peddy for this case. Thanks much.

**Comment by naumenko-sa** [comment]
Hi Brad!

I'm running variant calling and annotation with the interval 1:171000000-172000000
and config

```
details:
- algorithm:
    aligner: bwa
    effects: vep
    effects_transcripts: all
    ensemble:
      numpass: 2
    mark_duplicates: true
    realign: false
    recalibrate: false
    save_diskspace: true
    tools_on:
    - qualimap
    - vep_splicesite_annotations
    - noalt_calling
    validate: giab-NA12878/truth_small_variants.vcf.gz
    validate_regions: giab-NA12878/truth_regions.bed
    variant_regions: /home/stud40/nist/input/region.bed
    variantcaller:
    - gatk-haplotype
    - samtools
    - freebayes
    - platypus
  analysis: variant2
  description: nist_NA12878
  files:
  - /home/stud40/nist/input/nist_NA12878.bam
  genome_build: GRCh37
  metadata:
    batch: nist
fc_name: gatk4
resources:
  default:
    cores: 30
    jvm_opts:
    - -Xms75m
    - -Xmx700m
    memory: 1G
upload:
  dir: ../final

```

Error:
```
[2018-06-10T22:04Z] Add PED file to gemini database : nist_NA12878
[2018-06-10T22:04Z] Timing: peddy check
[2018-06-10T22:04Z] multiprocessing: run_peddy
[2018-06-10T22:04Z] Running peddy on /home/stud40/nist/work/ensemble/nist/nist-ensemble-vepeffects.vcf.gz against /home/stud40/nist/work/ensemble/nist/nist-ensemble-vepeffects.ped.
[2018-06-10T22:05Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/stud40/module3_annotation/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/stud40/module3_annotation/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /home/stud40/module3_annotation/tools/bcbio/anaconda/bin/peddy -p 30 --plot --prefix /home/stud40/nist/work/bcbiotx/tmp56vvcs/nist /home/stud40/nist/work/ensemble/nist/nist-ensemble-vepeffects.vcf.gz /home/stud40/nist/work/ensemble/nist/nist-ensemble-vepeffects.ped 2> /home/stud40/nist/work/bcbiotx/tmp56vvcs/run-stderr.log
' returned non-zero exit status 1
[2018-06-10T22:05Z] no intervals found for /home/stud40/nist/work/ensemble/nist/nist-ensemble-vepeffects.vcf.gz at 20:60419750-60419750
no intervals found for /home/stud40/nist/work/ensemble/nist/nist-ensemble-vepeffects.vcf.gz at 20:60775932-60775932
no intervals found for /home/stud40/nist/work/ensemble/nist/nist-ensemble-vepeffects.vcf.gz at 20:60963055-60963055
no intervals found for /home/stud40/nist/work/ensemble/nist/nist-ensemble-vepeffects.vcf.gz at 20:61443716-61443716
no intervals found for /home/stud40/nist/work/ensemble/nist/nist-ensemble-vepeffects.vcf.gz at 20:61943089-61943089
no intervals found for /home/stud40/nist/work/ensemble/nist/nist-ensemble-vepeffects.vcf.gz at 20:62191937-62191937
no intervals found for /home/stud40/nist/work/ensemble/nist/nist-ensemble-vepeffects.vcf.gz at 20:62328480-62328480
no intervals found for /home/stud40/nist/work/ensemble/nist/nist-ensemble-vepeffects.vcf.gz at 21:10910340-10910340
```

Sergey

**Comment by chapmanb** [comment]
Sergey;
Thanks for the details on the error, it appears as if there is just nothing for peddy to process on so it ends up erroring out. I pushed a fix which should capture this and continue. If you update to the latest development version (`bcbio_nextgen.py upgrade -u development`) and re-try in place hopefully it'll work cleanly for you. Please let us know if you run into any other problems.
