### ISSUE TITLE
Installation of custom reference genome failing on empty temporary GTF file at `prepare_tx_gff.py` and `gffutils `

### ISSUE THREAD

**Issue by WimSpee** [bcbio/bcbio-nextgen#2423]
Hi,

I am trying to install a custom reference genome:

`bcbio_setup_genome.py -f ./physical_map/custom_reference/custom_reference.fa -n custom_reference -b custom_reference -i bwa seq star -g custom_reference.gtf`

This did create the seq, bwa, star and bowtie indexes:
```
985M	/data/prod/Tools/bcbio/1.0.8/genomes/custom_reference/custom_reference/seq/custom_reference.fa
257	/data/prod/Tools/bcbio/1.0.8/genomes/custom_reference/custom_reference/seq/custom_reference.fa.fai
1.9K	/data/prod/Tools/bcbio/1.0.8/genomes/custom_reference/custom_reference/seq/custom_reference.dict
18M	/data/prod/Tools/bcbio/1.0.8/genomes/custom_reference/custom_reference/rnaseq/ref-transcripts.gtf
243M	/data/prod/Tools/bcbio/1.0.8/genomes/custom_reference/custom_reference/bwa/custom_reference.fa.pac
340	/data/prod/Tools/bcbio/1.0.8/genomes/custom_reference/custom_reference/bwa/custom_reference.fa.ann
3.1M	/data/prod/Tools/bcbio/1.0.8/genomes/custom_reference/custom_reference/bwa/custom_reference.fa.amb
969M	/data/prod/Tools/bcbio/1.0.8/genomes/custom_reference/custom_reference/bwa/custom_reference.fa.bwt
485M	/data/prod/Tools/bcbio/1.0.8/genomes/custom_reference/custom_reference/bwa/custom_reference.fa.sa
60	/data/prod/Tools/bcbio/1.0.8/genomes/custom_reference/custom_reference/star/chrName.txt
83	/data/prod/Tools/bcbio/1.0.8/genomes/custom_reference/custom_reference/star/chrStart.txt
76	/data/prod/Tools/bcbio/1.0.8/genomes/custom_reference/custom_reference/star/chrLength.txt
136	/data/prod/Tools/bcbio/1.0.8/genomes/custom_reference/custom_reference/star/chrNameLength.txt
966	/data/prod/Tools/bcbio/1.0.8/genomes/custom_reference/custom_reference/star/genomeParameters.txt
19K	/data/prod/Tools/bcbio/1.0.8/genomes/custom_reference/custom_reference/Log.out
1.9M	/data/prod/Tools/bcbio/1.0.8/genomes/custom_reference/custom_reference/bowtie2/custom_reference.3.bt2
199M	/data/prod/Tools/bcbio/1.0.8/genomes/custom_reference/custom_reference/bowtie2/custom_reference.4.bt2
271M	/data/prod/Tools/bcbio/1.0.8/genomes/custom_reference/custom_reference/bowtie2/custom_reference.1.bt2
199M	/data/prod/Tools/bcbio/1.0.8/genomes/custom_reference/custom_reference/bowtie2/custom_reference.2.bt2
271M	/data/prod/Tools/bcbio/1.0.8/genomes/custom_reference/custom_reference/bowtie2/custom_reference.rev.1.bt2
199M	/data/prod/Tools/bcbio/1.0.8/genomes/custom_reference/custom_reference/bowtie2/custom_reference.rev.2.bt2
44	/data/prod/Tools/bcbio/1.0.8/genomes/custom_reference/custom_reference/bowtie2/custom_reference.fa
161	/data/prod/Tools/bcbio/1.0.8/genomes/custom_reference/custom_reference/tmpcbl/version.txt
0	/data/prod/Tools/bcbio/1.0.8/genomes/custom_reference/custom_reference/tmpcbl/ref-transcripts.gtf
```

The installation fails in `gffutils`, which seems to be passed an empty temporary gtf file from `prepare_tx_gff.py`:
```
  File "/data/run/Projects/DA_1191/DA_1224_20180620_samples-merged/work/re_add_reference/cloudbiolinux/utils/prepare_tx_gff.py", line 772, in _get_gtf_db
    disable_infer_transcripts, disable_infer_genes = guess_disable_infer_extent(gtf)
  File "/data/run/Projects/DA_1191/DA_1224_20180620_samples-merged/work/re_add_reference/cloudbiolinux/utils/prepare_tx_gff.py", line 744, in guess_disable_infer_extent
    db = _create_tiny_gffutils_db(gtf_file)
  File "/data/run/Projects/DA_1191/DA_1224_20180620_samples-merged/work/re_add_reference/cloudbiolinux/utils/prepare_tx_gff.py", line 715, in _create_tiny_gffutils_db
    disable_infer_transcripts=True)
  File "/data/prod/Tools/bcbio/1.0.8/anaconda/lib/python2.7/site-packages/gffutils/create.py", line 1288, in create_db
    c.create()
  File "/data/prod/Tools/bcbio/1.0.8/anaconda/lib/python2.7/site-packages/gffutils/create.py", line 504, in create
    self._populate_from_lines(self.iterator)
  File "/data/prod/Tools/bcbio/1.0.8/anaconda/lib/python2.7/site-packages/gffutils/create.py", line 625, in _populate_from_lines
    raise ValueError("No lines parsed -- was an empty file provided?")
ValueError: No lines parsed -- was an empty file provided?
Traceback (most recent call last):
  File "/tools/bioinfo/app/bcbio-1.0.8/bin/bcbio_setup_genome.py", line 304, in <module>
    subprocess.check_call(cmd.format(**locals()), shell=True)
  File "/data/prod/Tools/bcbio/1.0.8/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/data/prod/Tools/bcbio/1.0.8/anaconda/bin/python /data/run/Projects/DA_1191/DA_1224_20180620_samples-merged/work/re_add_reference/cloudbiolinux/utils/prepare_tx_gff.py --cores 1 --genome-dir /data/prod/Tools/bcbio/1.0.8/genomes --gtf /data/prod/Tools/bcbio/1.0.8/genomes/custom_reference/custom_reference/rnaseq/ref-transcripts.gtf custom_reference custom_reference' returned non-zero exit status 1
```

I am not sure why this happens. I tried to have a look at the code of `gffutils `and `prepare_tx_gff.py`:
https://github.com/daler/gffutils/blob/9e6b8790a99b52c5673644e41642a21d48beb264/gffutils/create.py
https://github.com/chapmanb/cloudbiolinux/blob/master/utils/prepare_tx_gff.py#L701

I am guessing this has to do with some gtf formatting issue, or optional field missing. But the gtf is accepted by other tools during the reference genome installation. 

Here is the beginning and end of the gtf file. Can you please have a look at why the `gffutils `and `prepare_tx_gff.py` part of the genome installation fails on this gtf. Thank you. 

```
Chr_00_A        maker   exon    217854  218112  .       +       .       transcript_id "ts22931";
Chr_00_A        maker   exon    218841  219211  .       +       .       transcript_id "ts22931";
Chr_00_A        maker   exon    221140  221708  .       +       .       transcript_id "ts22931";
Chr_00_A        maker   CDS     218097  218112  .       +       0       transcript_id "ts22931";
Chr_00_A        maker   CDS     218841  219211  .       +       2       transcript_id "ts22931";
Chr_00_A        maker   CDS     221140  221496  .       +       0       transcript_id "ts22931";
Chr_00_A        maker   exon    665643  666084  .       +       .       transcript_id "ts19388";
Chr_00_A        maker   exon    666182  666260  .       +       .       transcript_id "ts19388";
Chr_00_A        maker   exon    666368  666565  .       +       .       transcript_id "ts19388";
Chr_00_A        maker   exon    669912  670123  .       +       .       transcript_id "ts19388";
Chr_00_A        maker   exon    670477  670549  .       +       .       transcript_id "ts19388";
Chr_00_A        maker   exon    670788  670844  .       +       .       transcript_id "ts19388";
Chr_00_A        maker   exon    673265  673344  .       +       .       transcript_id "ts19388";
Chr_00_A        maker   exon    673433  673495  .       +       .       transcript_id "ts19388";
Chr_00_A        maker   exon    673576  673663  .       +       .       transcript_id "ts19388";
Chr_00_A        maker   exon    673904  674006  .       +       .       transcript_id "ts19388";
Chr_00_A        maker   exon    674128  674231  .       +       .       transcript_id "ts19388";
Chr_00_A        maker   exon    678407  678480  .       +       .       transcript_id "ts19388";
Chr_00_A        maker   exon    679582  679646  .       +       .       transcript_id "ts19388";
Chr_00_A        maker   exon    679767  679936  .       +       .       transcript_id "ts19388";
Chr_00_A        maker   exon    681856  681923  .       +       .       transcript_id "ts19388";
Chr_00_A        maker   exon    682014  682074  .       +       .       transcript_id "ts19388";
Chr_00_A        maker   exon    683823  683860  .       +       .       transcript_id "ts19388";
Chr_00_A        maker   exon    683958  684026  .       +       .       transcript_id "ts19388";
Chr_00_A        maker   exon    684132  684441  .       +       .       transcript_id "ts19388";
Chr_00_A        maker   exon    684645  684725  .       +       .       transcript_id "ts19388";
Chr_00_A        maker   exon    684929  685585  .       +       .       transcript_id "ts19388";
Chr_00_A        maker   CDS     665852  666084  .       +       0       transcript_id "ts19388";
Chr_00_A        maker   CDS     666182  666260  .       +       1       transcript_id "ts19388";
Chr_00_A        maker   CDS     666368  666565  .       +       0       transcript_id "ts19388";
Chr_00_A        maker   CDS     669912  670123  .       +       0       transcript_id "ts19388";
Chr_00_A        maker   CDS     670477  670549  .       +       1       transcript_id "ts19388";
Chr_00_A        maker   CDS     670788  670844  .       +       0       transcript_id "ts19388";
Chr_00_A        maker   CDS     673265  673344  .       +       0       transcript_id "ts19388";
Chr_00_A        maker   CDS     673433  673495  .       +       1       transcript_id "ts19388";
Chr_00_A        maker   CDS     673576  673663  .       +       1       transcript_id "ts19388";
Chr_00_A        maker   CDS     673904  674006  .       +       0       transcript_id "ts19388";
Chr_00_A        maker   CDS     674128  674231  .       +       2       transcript_id "ts19388";
Chr_00_A        maker   CDS     678407  678480  .       +       0       transcript_id "ts19388";
Chr_00_A        maker   CDS     679582  679646  .       +       1       transcript_id "ts19388";
Chr_00_A        maker   CDS     679767  679936  .       +       2       transcript_id "ts19388";
Chr_00_A        maker   CDS     681856  681923  .       +       0       transcript_id "ts19388";
Chr_00_A        maker   CDS     682014  682074  .       +       1       transcript_id "ts19388";
Chr_00_A        maker   CDS     683823  683860  .       +       0       transcript_id "ts19388";
Chr_00_A        maker   CDS     683958  684026  .       +       1       transcript_id "ts19388";
Chr_00_A        maker   CDS     684132  684441  .       +       1       transcript_id "ts19388";
Chr_00_A        maker   CDS     684645  684680  .       +       0       transcript_id "ts19388";
Chr_00_A        maker   exon    992535  993236  .       +       .       transcript_id "ts19387";
Chr_00_A        maker   exon    994328  996223  .       +       .       transcript_id "ts19387";
Chr_00_A        maker   CDS     992719  993236  .       +       0       transcript_id "ts19387";
Chr_00_A        maker   CDS     994328  996020  .       +       1       transcript_id "ts19387";
```

```
Chr_06  maker   exon    46190779        46192482        .       +       .       transcript_id "ts17480";
Chr_06  maker   CDS     46190779        46192482        .       +       0       transcript_id "ts17480";
Chr_06  maker   exon    46194716        46195277        .       -       .       transcript_id "ts17456";
Chr_06  maker   exon    46196128        46196229        .       -       .       transcript_id "ts17456";
Chr_06  maker   exon    46196324        46196419        .       -       .       transcript_id "ts17456";
Chr_06  maker   exon    46198257        46198397        .       -       .       transcript_id "ts17456";
Chr_06  maker   exon    46198479        46198523        .       -       .       transcript_id "ts17456";
Chr_06  maker   exon    46199076        46199329        .       -       .       transcript_id "ts17456";
Chr_06  maker   exon    46199423        46199462        .       -       .       transcript_id "ts17456";
Chr_06  maker   exon    46199539        46199771        .       -       .       transcript_id "ts17456";
Chr_06  maker   exon    46201219        46201374        .       -       .       transcript_id "ts17456";
Chr_06  maker   exon    46201527        46201598        .       -       .       transcript_id "ts17456";
Chr_06  maker   exon    46201683        46201747        .       -       .       transcript_id "ts17456";
Chr_06  maker   exon    46201935        46202030        .       -       .       transcript_id "ts17456";
Chr_06  maker   exon    46203371        46203471        .       -       .       transcript_id "ts17456";
Chr_06  maker   exon    46203556        46203596        .       -       .       transcript_id "ts17456";
Chr_06  maker   exon    46203688        46203811        .       -       .       transcript_id "ts17456";
Chr_06  maker   exon    46203903        46203905        .       -       .       transcript_id "ts17456";
Chr_06  maker   CDS     46195167        46195277        .       -       0       transcript_id "ts17456";
Chr_06  maker   CDS     46196128        46196229        .       -       0       transcript_id "ts17456";
Chr_06  maker   CDS     46196324        46196419        .       -       0       transcript_id "ts17456";
Chr_06  maker   CDS     46198257        46198397        .       -       0       transcript_id "ts17456";
Chr_06  maker   CDS     46198479        46198523        .       -       0       transcript_id "ts17456";
Chr_06  maker   CDS     46199076        46199329        .       -       2       transcript_id "ts17456";
Chr_06  maker   CDS     46199423        46199462        .       -       0       transcript_id "ts17456";
Chr_06  maker   CDS     46199539        46199771        .       -       2       transcript_id "ts17456";
Chr_06  maker   CDS     46201219        46201374        .       -       2       transcript_id "ts17456";
Chr_06  maker   CDS     46201527        46201598        .       -       2       transcript_id "ts17456";
Chr_06  maker   CDS     46201683        46201747        .       -       1       transcript_id "ts17456";
Chr_06  maker   CDS     46201935        46202030        .       -       1       transcript_id "ts17456";
Chr_06  maker   CDS     46203371        46203471        .       -       0       transcript_id "ts17456";
Chr_06  maker   CDS     46203556        46203596        .       -       2       transcript_id "ts17456";
Chr_06  maker   CDS     46203688        46203811        .       -       0       transcript_id "ts17456";
Chr_06  maker   CDS     46203903        46203905        .       -       0       transcript_id "ts17456";
Chr_06  maker   exon    46393081        46393142        .       +       .       transcript_id "ts17479";
Chr_06  maker   exon    46394188        46394281        .       +       .       transcript_id "ts17479";
Chr_06  maker   exon    46394830        46394894        .       +       .       transcript_id "ts17479";
Chr_06  maker   exon    46397969        46398050        .       +       .       transcript_id "ts17479";
Chr_06  maker   exon    46398325        46398439        .       +       .       transcript_id "ts17479";
Chr_06  maker   exon    46398542        46398764        .       +       .       transcript_id "ts17479";
Chr_06  maker   CDS     46393094        46393142        .       +       0       transcript_id "ts17479";
Chr_06  maker   CDS     46394188        46394281        .       +       2       transcript_id "ts17479";
Chr_06  maker   CDS     46394830        46394894        .       +       1       transcript_id "ts17479";
Chr_06  maker   CDS     46397969        46398050        .       +       2       transcript_id "ts17479";
Chr_06  maker   CDS     46398325        46398439        .       +       1       transcript_id "ts17479";
Chr_06  maker   CDS     46398542        46398652        .       +       0       transcript_id "ts17479";
```

**Comment by roryk** [comment]
Hi @WimSpee,

Sorry, we require a GTF file to have these three things:

1) a transcript_id field
2) a gene_id field
3) exon fields

This is missing gene_ids so it is failing. If there are no actual genes, just adding a gene_id that is the same as the transcript_id will work.

**Comment by WimSpee** [comment]
Hi @roryk  Thank you for the quick answer.  Indeed there were no actual genes. Copying the transcript_ids to gene_ids in the GTF file fixed the issue. 

Thank you.
