### ISSUE TITLE
bcbio 1.1.0 dev installation error: conda: error: unrecognized arguments: --only-deps

### ISSUE THREAD

**Issue by WimSpee** [bcbio/bcbio-nextgen#2424]
Hi, 

I am trying to install the latest 1.1.0 development version of bcbio. 

`python bcbio_nextgen_install.py --tooldir=/home/my_user/workspace/tmp_bcbio_1.1.0_development/tool_dir --aligners bwa --aligners star --nodata --isolate -u stable --distribution centos /home/my_user/workspace/tmp_bcbio_1.1.0_development/data_dir`

I run into this conda error:

```
conda                     4.5.4                    py27_0    https://repo.anaconda.com/pkgs/main
usage: conda [-h] [-V] command ...
conda: error: unrecognized arguments: --only-deps
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 266, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 38, in main
    bcbio = install_conda_pkgs(anaconda, args)
  File "bcbio_nextgen_install.py", line 83, in install_conda_pkgs
    "-c", "conda-forge", "-c", "bioconda", "--only-deps", "bcbio-nextgen"], env=env)
  File "/tools/general/app/anaconda-python-2.7/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/my_user/workspace/tmp_bcbio_1.1.0_development/data_dir/anaconda/bin/conda', 'install', '--yes', '-c', 'conda-forge', '-c', 'bioconda', '--only-deps', 'bcbio-nextgen']' returned non-zero exit status 2
```

Do you have any advice on how to fix this.  

For this installation attempt I set the $PYTHONPATH and $PATH variables to and older bcbio installation:
```
echo $PYTHONPATH
/data/prod/Tools/bcbio/1.0.4/anaconda/lib/python2.7/site-packages/:/tools/general/app/anaconda-python-2.7/lib

echo $PATH
/tools/bioinfo/app/bcbio-1.0.4/bin: ................................
```

If I don't set the these PATHS the installation continues much further before crashing on:

```
Traceback (most recent call last):
  File "/home/my_user/.local/lib/python2.7/site-packages/fabric/network.py", line 24, in <module>
    import paramiko as ssh
  File "/home/my_user/.local/lib/python2.7/site-packages/paramiko/__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/home/my_user/.local/lib/python2.7/site-packages/paramiko/transport.py", line 49, in <module>
    from paramiko.dsskey import DSSKey
  File "/home/my_user/.local/lib/python2.7/site-packages/paramiko/dsskey.py", line 26, in <module>
    from Crypto.PublicKey import DSA
  File "/home/my_user/.local/lib/python2.7/site-packages/Crypto/PublicKey/DSA.py", line 89, in <module>
    from Crypto import Random
  File "/home/my_user/.local/lib/python2.7/site-packages/Crypto/Random/__init__.py", line 29, in <module>
    from Crypto.Random import _UserFriendlyRNG
  File "/home/my_user/.local/lib/python2.7/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 38, in <module>
    from Crypto.Random.Fortuna import FortunaAccumulator
  File "/home/my_user/.local/lib/python2.7/site-packages/Crypto/Random/Fortuna/FortunaAccumulator.py", line 39, in <module>
    import FortunaGenerator
  File "/home/my_user/.local/lib/python2.7/site-packages/Crypto/Random/Fortuna/FortunaGenerator.py", line 36, in <module>
    from Crypto.Cipher import AES
  File "/home/my_user/.local/lib/python2.7/site-packages/Crypto/Cipher/AES.py", line 50, in <module>
    from Crypto.Cipher import _AES
ImportError: /home/my_user/.local/lib/python2.7/site-packages/Crypto/Cipher/_AES.so: undefined symbol: rpl_malloc

There was a problem importing our SSH library (see traceback above).
Please make sure all dependencies are installed and importable.
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 266, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/tools/general/app/anaconda-python-2.7/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/my_user/workspace/tmp_bcbio_1.1.0_development/data_dir/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/home/my_user/workspace/tmp_bcbio_1.1.0_development/tool_dir', '--aligners', 'bwa', '--aligners', 'star', '--isolate', '-u', 'stable', '--distribution', 'centos']' returned non-zero exit status 1
```

This error I used to solve via setting the PATH and PYTHONPATH to and older bcbio version. But this not does not work anymore since I get the first error in this ticket. 

Advice on how to fix this second error would also be useful. Thank you.

**Comment by chapmanb** [comment]
Thanks for the detailed report and apologies about the issue. For the main bcbio install issue, I'm not entirely sure what is happening but it looks like we're somehow getting conda environments crossed up. The traceback looks like you have a recent version which should support the `--only-deps` argument. You can check by looking at:
```
/home/my_user/workspace/tmp_bcbio_1.1.0_development/data_dir/anaconda/bin/conda install -h
```
From your description I'd guess that setting the PYTHONPATH and PATH cause injection of the older conda so that gets picked up instead of the one we should be using.

The second error you're seeing is due to an incompatible crypto library in your '~/.local` directory, which gets automatically inserted into your PYTHONPATH.

So both issues are due to incompatible cross talk. My suggestion to fix would be to remove the '~/.local` directory and do not set PATH and PYTHONPATH. Hopefully this will keep the new install isolated and work properly so you can get running. Please let us know if this doesn't fix the problem.

**Comment by WimSpee** [comment]
Thank you for the quick answer. Removing the locally installed  `python2.7/site-packages/Crypto` package fixed the issue.
