### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\uffa0' in position 30: ordinal not in range(128)

### ISSUE THREAD

**Issue by mattdmem** [bcbio/bcbio-nextgen#2425]
Hi,

I get the error below when running the paired somatic analysis on bcbio 1.0.9. Wondering if you can help me track down the cause of the problem?

Thanks!

Error:

```

[2018-06-27T15:59Z] multiprocessing: calculate_sv_bins
[2018-06-27T15:59Z] multiprocessing: calculate_sv_coverage
[2018-06-27T15:59Z] multiprocessing: normalize_sv_coverage
[2018-06-27T15:59Z] Timing: hla typing
[2018-06-27T15:59Z] Resource requests: gatk, mutect2, picard, strelka2, vardict; memory: 3.50, 3.00, 3.00, 3.00, 3.00; cores: 1, 16, 16, 16, 16
[2018-06-27T15:59Z] Configuring 1 jobs to run, using 1 cores each with 3.50g of memory reserved for each job
[2018-06-27T15:59Z] Timing: alignment post-processing
[2018-06-27T15:59Z] multiprocessing: piped_bamprep
[2018-06-27T15:59Z] Timing: variant calling
[2018-06-27T15:59Z] multiprocessing: variantcall_sample
Traceback (most recent call last):
  File "/usr/local/community/bcbio-nextgen/2017-08/tool/bin/bcbio_nextgen.py", line 241, in <module>
    main(**kwargs)
  File "/usr/local/community/bcbio-nextgen/2017-08/tool/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 146, in variant2pipeline
    samples = genotype.parallel_variantcall_region(samples, run_parallel)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 195, in parallel_variantcall_region
    "vrn_file", ["region", "sam_ref", "config"]))
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 32, in grouped_parallel_split_combine
    final_output = parallel_fn(parallel_name, split_args)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 275, in variantcall_sample
    return genotype.variantcall_sample(*args)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 351, in variantcall_sample
    out_file = caller_fn(align_bams, items, ref_file, assoc_files, region, out_file)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/variation/vardict.py", line 87, in run_vardict
    assoc_files, region, out_file)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/variation/vardict.py", line 239, in _run_vardict_paired
    out_file, items=items, do_merge=True)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/shared.py", line 251, in wrapper
    region_bed = f(variant_regions, region, out_file, items, do_merge, data)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/shared.py", line 294, in subset_variant_regions
    dd.get_ref_file(data), do_merge=do_merge)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/shared.py", line 136, in _subset_bed_by_region
    filter(lambda x: len(x) > 1).saveas().merge().saveas(out_file)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 806, in decorated
    result = method(self, *args, **kwargs)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 2996, in saveas
    compressed=compressed)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 1249, in _collapse
    out_.write(str(i))
UnicodeEncodeError: 'ascii' codec can't encode character u'\uffa0' in position 30: ordinal not in range(128)
```

YAML Config:

```
details:
- algorithm:
    aligner: bwa
    ensemble:
      numpass: 2
    variant_regions: /fastdata/md1mpar/polly/3016441_Covered.bed
    variantcaller:
    - vardict
    - mutect2
    - strelka2
  analysis: variant2
  description: Sample_144Blood
  files:
  - /mnt/fastdata/md1mpar/polly/Sample_144Blood_R1.fastq.gz
  - /mnt/fastdata/md1mpar/polly/Sample_144Blood_R2.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: 144
    phenotype: normal
- algorithm:
    aligner: bwa
    ensemble:
      numpass: 2
    variant_regions: /fastdata/md1mpar/polly/3016441_Covered.bed
    variantcaller:
    - vardict
    - mutect2
    - strelka2
  analysis: variant2
  description: Sample_144CD138
  files:
  - /mnt/fastdata/md1mpar/polly/Sample_144CD138_R1.fastq.gz
  - /mnt/fastdata/md1mpar/polly/Sample_144CD138_R2.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: 144
    phenotype: tumor
fc_name: batch_144
upload:
  dir: ../final
```

**Comment by chapmanb** [comment]
Matthew;
Sorry about the issues. It looks like we're running into an issue where there are non-ascii characters in your input BED file:
```
/fastdata/md1mpar/polly/3016441_Covered.bed
```
Is this intentional or is there perhaps something corrupted about the input? This can often indicate some issues with the BED file.

If you're able to clean/fix that file that should hopefully resolve the problem. If you're not able to identify and are able to share the file we can help with debugging further. Hope this helps.

**Comment by mattdmem** [comment]
Thanks Brad. That was our thinking too. I'll cleanse the bed and let you know if it works.

**Comment by mattdmem** [comment]
Do you think I need to redo the whole pipeline after fixing the bed or do you think a new cleaned bed and restarting from where it left off would work?

**Comment by chapmanb** [comment]
Matthew;
Glad that helped, hopefully it'll get things running cleanly for you. I don't think there is any need to restart from the beginning. It looks like it's having issues when first dealing with the BED so anything done previously should be BED independent. Hope the re-run gets your analysis finished.
