### ISSUE TITLE
conda error with installation

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2431]
When updating to the latest state, I got this error

```
conda install -y -n samtools0 -c conda-forge -c bioconda ericscript
Solving environment: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/bcbio/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/opt/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "/opt/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/opt/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 11, in execute
        install(args, parser, 'install')
      File "/opt/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 235, in install
        force_reinstall=context.force,
      File "/opt/bcbio/anaconda/lib/python2.7/site-packages/conda/core/solve.py", line 506, in solve_for_transaction
        force_remove, force_reinstall)
      File "/opt/bcbio/anaconda/lib/python2.7/site-packages/conda/core/solve.py", line 439, in solve_for_diff
        final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
      File "/opt/bcbio/anaconda/lib/python2.7/site-packages/conda/core/solve.py", line 148, in solve_final_state
        specs_from_history_map = History(self.prefix).get_requested_specs_map()
      File "/opt/bcbio/anaconda/lib/python2.7/site-packages/conda/history.py", line 230, in get_requested_specs_map
        for request in self.get_user_requests():
      File "/opt/bcbio/anaconda/lib/python2.7/site-packages/conda/history.py", line 215, in get_user_requests
        comment_items = self._parse_comment_line(line)
      File "/opt/bcbio/anaconda/lib/python2.7/site-packages/conda/history.py", line 191, in _parse_comment_line
        specs = History._parse_old_format_specs_string(specs_string)
      File "/opt/bcbio/anaconda/lib/python2.7/site-packages/conda/history.py", line 152, in _parse_old_format_specs_string
        if spec[0].isalpha():
    IndexError: string index out of range

`$ /opt/bcbio/anaconda/bin/conda install -y -n samtools0 -c conda-forge -c bioconda ericscript`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/opt/bcbio/anaconda
                     PATH=/home/einar/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbi
                          n:/bin:/usr/games:/usr/local/games:/usr/lib/cd-hit
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /home/einar/.condarc
 populated config files : 
          conda version : 4.5.5
    conda-build version : 3.2.2
         python version : 2.7.14.final.0
       base environment : /opt/bcbio/anaconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /opt/bcbio/anaconda/pkgs
                          /home/einar/.conda/pkgs
       envs directories : /opt/bcbio/anaconda/envs
                          /home/einar/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.5 requests/2.18.4 CPython/2.7.14 Linux/4.4.0-119-generic ubuntu/14.04 glibc/2.19
                UID:GID : 2010:2001
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

It looks like a conda bug to me, but just in case I thought I'd mention it in case other users are affected.

**Comment by ohofmann** [comment]
Yep, ran into the same issue. Removing the `samtools0` environment and restarting the upgrade worked as a quick fix.

**Comment by lbeltrame** [comment]
Thanks @ohofmann, I did the same and was able to finish the upgrade.

**Comment by chapmanb** [comment]
Luca and Oliver;
Thanks much for this report and apologies about the problem. It looks like the newest conda has some problems with older history files in `/path/to/env/conda-meta/history`. There are lines like:
```
# create specs:
```
without any information after the colon, it appears to trigger this failure. I pushed a fix to cloudbiolinux to clean up these files automatically as part of the install, so conda will no longer fail so it should work going forward without needing to remove the entire directory (which also works fine as a workaround since it removes the offending history file).

Thanks again for the report and debugging.

**Comment by manugarri** [comment]
Same issue here, is the only solution to delete the existing environments?

**Comment by chapmanb** [comment]
Manuel;
Are you running into this problem as part of a bcbio upgrade, or in some other conda usage? In bcbio, this should now be fixed as we'll resolve any issues with the `conda-meta/history` file. Outside of bcbio, you can fix by manually editing this file to remove problematic comment lines as described above. Hope this helps.

**Comment by manugarri** [comment]
other conda usage, my bad I didnt read the github repo and this was the first link to show up.

**Comment by Xrampino** [comment]
I had to truncate my `history` file, but it works now
