### ISSUE TITLE
Could not find reference genome file GRCh37 samtools

### ISSUE THREAD

**Issue by phu5ion** [bcbio/bcbio-nextgen#2433]
Hi,

I realised that other folks have also reported on this issue before #2159 #691 but it seems like my problem may need a different solution. This is my error logfile:

```
[2018-07-05T09:20Z] System YAML configuration: /mnt/projects/dlho/tancrc/bcbio_pipeline/galaxy/bcbio_system.yaml
[2018-07-05T09:20Z] Resource requests: picard; memory: 3.00; cores: 16
[2018-07-05T09:20Z] Configuring 1 jobs to run, using 1 cores each with 3.00g of memory reserved for each job
[2018-07-05T09:20Z] Timing: organize samples
[2018-07-05T09:20Z] multiprocessing: organize_samples
[2018-07-05T09:20Z] Using input YAML configuration: /mnt/projects/ngbhs/cirqseq/2017_bcbio/20180702_YF_FFPE/YF_FFPE_fusion/config/YF_FFPE_fusion.yaml
[2018-07-05T09:20Z] Checking sample YAML configuration: /mnt/projects/ngbhs/cirqseq/2017_bcbio/20180702_YF_FFPE/YF_FFPE_fusion/config/YF_FFPE_fusion.yaml
[2018-07-05T09:20Z] Downloading GrCh37 samtools from AWS
Traceback (most recent call last):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/bin/bcbio_nextgen.py", line 241, in <module>
    main(**kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 240, in rnaseqpipeline
    samples = rnaseq_prep_samples(config, run_info_yaml, parallel, dirs, samples)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 402, in rnaseq_prep_samples
    [x[0]["description"] for x in samples]]])
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 332, in __init__
    self.results = batch()
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 411, in organize_samples
    return run_info.organize(*args)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 72, in organize
    item = add_reference_resources(item, remote_retriever)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 166, in add_reference_resources
    data["reference"] = genome.get_refs(data["genome_build"], aligner, data["dirs"]["galaxy"], data)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 229, in get_refs
    galaxy_config, data)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 175, in _get_ref_from_galaxy_loc
    cur_ref = download_prepped_genome(genome_build, data, name, need_remap)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 313, in download_prepped_genome
    raise ValueError("Could not find reference genome file %s %s" % (genome_build, name))
ValueError: Could not find reference genome file GrCh37 samtools

```

- I'm not using any dockers and bcbio is definitely reading from `bcbio_system.yaml`
- The files for GrCh37 should be present:
```
ls /mnt/projects/dlho/tancrc/bcbio_pipeline/genomes/Hsapiens/GRCh37
bwa       editing              rnaseq  snpeff   ucsc        vep
config    hs_err_pid82897.log  rtg     srnaseq  validation  versions.csv
coverage  prioritization       seq     star     variation   viral
```
The *loc files for GrCh37 looks good:
```
[dlho@n126 /mnt/projects/dlho/tancrc/bcbio_pipeline/galaxy/tool-data]cat *.loc | grep "GRCh37"
GRCh37  GRCh37  Human (GRCh37)  /mnt/projects/dlho/tancrc/bcbio_pipeline/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa
GRCh37  GRCh37  Human (GRCh37)  /mnt/projects/dlho/tancrc/bcbio_pipeline/genomes/Hsapiens/GRCh37/seq/GRCh37.fa
GRCh37  GRCh37  Human (GRCh37)  /mnt/projects/dlho/tancrc/bcbio_pipeline/genomes/Hsapiens/GRCh37/seq/GRCh37.fa
index   GRCh37  /mnt/projects/dlho/tancrc/bcbio_pipeline/genomes/Hsapiens/GRCh37/seq/GRCh37.fa
```

The thing bugging me is that the error log shows it's looking for "GrCh37" while what I have in my system is "GRCh37".... Anyway any ideas on what's happening here?

**Comment by chapmanb** [comment]
Thanks for the detailed report and sorry about the issue. My guess is that you have a typo in your input sample YAML file and have specified:
```
genome_build: GrCh37
```
instead of `GRCh37`. If you correct the case on that it should hopefully correctly find the right GRCh37 genome you have installed. Hope this helps.

**Comment by phu5ion** [comment]
Hi Brad,

Oops, haha, you're right. This is pretty embarrassing. Sorry for wasting your time!
