### ISSUE TITLE
bcbio can't start on SGE queue that has dot in the queue name 

### ISSUE THREAD

**Issue by WimSpee** [bcbio/bcbio-nextgen#2441]
Hi @roryk 

The bcbio SGE cluster helper  split's the queue name on a "." via `base_queue = os.path.splitext(queue)[0]`  in `def _find_parallel_environment(queue):`
https://github.com/roryk/ipython-cluster-helper/blob/master/cluster_helper/cluster.py#L348

This results in the following error when having a queue named main.regular 
 ```
bcbio_nextgen.py ../config/VSDA_1080_samples-merged.yaml  -t ipython -n 61 -s sge -q main.regular -r vf=4G,h_rss=40G
[2018-07-11T09:32Z] machine_4: System YAML configuration: /data/prod/Tools/bcbio/1.0.8/galaxy/bcbio_system.yaml
[2018-07-11T09:32Z] machine_4: Resource requests: bwa, sambamba, samtools; memory: 4.00, 4.00, 4.00; cores: 10, 10, 10
[2018-07-11T09:32Z] machine_4: Configuring 6 jobs to run, using 10 cores each with 40.1g of memory reserved for each job
No cluster queue or queue instance matches the phrase "main.q"
No cluster queue or queue instance matches the phrase "main"
Traceback (most recent call last):
  File "/data/prod/Tools/bcbio/1.0.8/anaconda/bin/bcbio_nextgen.py", line 241, in <module>
    main(**kwargs)
  File "/data/prod/Tools/bcbio/1.0.8/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/data/prod/Tools/bcbio/1.0.8/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 51, in run_main
    fc_dir, run_info_yaml)
  File "/data/prod/Tools/bcbio/1.0.8/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/data/prod/Tools/bcbio/1.0.8/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 117, in variant2pipeline
    multiplier=alignprep.parallel_multiplier(samples)) as run_parallel:
  File "/data/prod/Tools/bcbio/1.0.8/anaconda/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/data/prod/Tools/bcbio/1.0.8/anaconda/lib/python2.7/site-packages/bcbio/distributed/prun.py", line 55, in start
    with ipython.create(parallel, dirs, config) as view:
  File "/data/prod/Tools/bcbio/1.0.8/anaconda/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/data/prod/Tools/bcbio/1.0.8/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py", line 1146, in cluster_view
    wait_for_all_engines=wait_for_all_engines)
  File "/data/prod/Tools/bcbio/1.0.8/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py", line 1033, in __init__
    cores_per_job, self.cluster_id, extra_params)
  File "/data/prod/Tools/bcbio/1.0.8/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py", line 889, in _start
    resources, specials = _scheduler_resources(scheduler, extra_params, queue)
  File "/data/prod/Tools/bcbio/1.0.8/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py", line 869, in _scheduler_resources
    specials["pename"] = _find_parallel_environment(queue)
  File "/data/prod/Tools/bcbio/1.0.8/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py", line 361, in _find_parallel_environment
    "https://blogs.oracle.com/templedf/entry/configuring_a_new_parallel_environment")
ValueError: Could not find an SGE environment configured for parallel execution. See https://blogs.oracle.com/templedf/entry/configuring_a_new_parallel_environment for SGE setup instructions.
```

Changing `base_queue = os.path.splitext(queue)[0]` to `base_queue = queue` solved the issue. 

I am not sure why the queue name is split on the "." .  Is there a good reason for this, otherwise it might be better to just take the queue name without splitting on "."  If "." is not allowed in SGE queue names or serves a special purpose we can change the queue name. 

Thank you.

**Comment by roryk** [comment]
Thanks @WimSpee, good catch. We split there because we need to look for both, you can set up the parallel execution with or without the .q. I'll add a step to check for an unsplit queue first.

**Comment by roryk** [comment]
Thanks, I pushed a fix for this to `ipython-cluster-helper`. Could you test the fix and make sure it works on your environment? If so I'll push a new release to `ipython-cluster-helper` which will work.

**Comment by WimSpee** [comment]
Hi @roryk  I added applied the modified to my local bcbio installation. I could then the start analysis using main.regular as the queue name. So it seems to work from my perspective.

**Comment by roryk** [comment]
Thank you! I'll push a new release with this fix so you won't have to hack it going forward. Thanks so much.

**Comment by roryk** [comment]
Thanks-- I updated the bioconda recipe so this should be all set for the future. Thanks so much for testing.

**Comment by mchimenti** [comment]
I realize this issue is closed, but I'm having the opposite problem.  The queue I want to run on is called simply "IIHG".  There is no ".q" after it.  When I try to run, it looks for "IIHG.q" which doesn't exist.  

Which file should I edit to change this behavior?  I'm running bcbio 1.2.2.  I'm thinking it's this: 

bcbio-1.2.2/anaconda/pkgs/ipython-cluster-helper-0.6.4-py_0/site-packages/cluster_helper/cluster.py

But I'm not sure?

**Comment by roryk** [comment]
Hi Michael,

It should be searching for both the queue with ".q" and without it, you can see the behavior here: 

https://github.com/roryk/ipython-cluster-helper/blob/20bca58255608937fdb24a791db3372047053e8e/cluster_helper/cluster.py#L345-L363

what's the error you are seeing?

**Comment by mchimenti** [comment]
Hi Rory,  thank you for the prompt reply.  I think I sorted this.

**Comment by roryk** [comment]
Thanks for following up! What was the eventual solution, just for FutureFolks who might run into this.
