### ISSUE TITLE
mirbase: command not found

### ISSUE THREAD

**Issue by komalsrathi** [bcbio/bcbio-nextgen#2443]
Hi,

I am trying to get the star index files and they got generated but after that the command is failing on line 18 of ggd-run.sh: 

Here is the error: 

```
/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh: line 18: mirbase: command not found
```

Here is the partial log (I tried the command again so it did not take as long as the first time):

```
[rathik@reslnrefo01 bcbio-nextgen]$ ./local/bin/bcbio_nextgen.py upgrade --data --aligners star
Upgrading bcbio
Upgrading bcbio-nextgen data files
Setting up virtual machine
INFO: <cloudbio.flavor.Flavor instance at 0x7f45ce5a85a8>
INFO: This is a ngs_pipeline_minimal flavor
INFO: Reading default fabricrc.txt
DBG [config.py]: Using config file /mnt/isilon/cbmi/variome/bin/bcbio-nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/../config/fabricrc.txt
INFO: Distribution __auto__
INFO: Get local environment
INFO: CentOS setup
DBG [distribution.py]: NixPkgs: Ignored
[localhost] local: echo $HOME
[localhost] local: uname -m
INFO: Now, testing connection to host...
INFO: Connection to host appears to work!
DBG [utils.py]: Expand paths
INFO: List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['star', 'bwa', 'bowtie2', 'rtg', 'twobit'], 'genomes': [{'name': 'Human (GRCh37)', 'validation': ['giab-NA12878', 'giab-NA24385', 'giab-NA24631', 'dream-syn3', 'dream-syn4', 'giab-NA12878-NA24385-somatic'], 'annotations': ['GA4GH_problem_regions', 'capture_regions', 'MIG', 'prioritize', 'dbsnp', 'hapmap', '1000g_omni_snps', 'ACMG56_genes', '1000g_snps', 'mills_indels', 'clinvar', 'cosmic', 'ancestral', 'qsignature', 'genesplicer', 'effects_transcripts', 'vcfanno', 'viral', 'transcripts', 'RADAR', 'mirbase'], 'dbkey': 'GRCh37', 'indexes': ['seq', 'twobit']}], 'install_uniref': False}'): Human (GRCh37)
Running GGD recipe: GRCh37 srnaseq 20180710
--2018-07-11 11:30:05--  http://www.regulatoryrna.org/database/piRNA/download/archive/v1.0/bed/piR_hg19_v1.0.bed.gz
Resolving www.regulatoryrna.org... 159.226.118.231
Connecting to www.regulatoryrna.org|159.226.118.231|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7355917 (7.0M) [application/x-gzip]
Saving to: ‘piR_hg19_v1.0.bed.gz.1’

piR_hg19_v1.0.bed.gz.1                  100%[=============================================================================>]   7.01M  11.0MB/s    in 0.6s    

2018-07-11 11:30:10 (11.0 MB/s) - ‘piR_hg19_v1.0.bed.gz.1’ saved [7355917/7355917]

/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh: line 18: mirbase: command not found
Traceback (most recent call last):
  File "./local/bin/bcbio_nextgen.py", line 222, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 98, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 306, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 63, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 109, in _setup_vm
    configure_instance(options, actions)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 269, in configure_instance
    setup_biodata(options)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 251, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 340, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 469, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 836, in _install_with_ggd
    ggd.install_recipe(env.cwd, recipe_file, gid)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 31, in install_recipe
    recipe["recipe"]["full"]["recipe_type"])
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 63, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bash', '/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh']' returned non-zero exit status 127
```

**Comment by komalsrathi** [comment]
Oh looks like it line 18 in ggd-run.sh needed to be commented out.

**Comment by komalsrathi** [comment]
I tried to comment it but looks like everytime I run `./local/bin/bcbio_nextgen.py upgrade --data --aligners star` this file is created again - can you tell me what's the workaround for this?

**Comment by roryk** [comment]
Hi Komal,

Could you post the text of the line that is failing?

**Comment by komalsrathi** [comment]
on Line 18 of ggd-run.sh it says `mirbase` but it should be `# mirbase`.

**Comment by roryk** [comment]
Gotcha, I see. If you delete `/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/tmpbcbio-install/` and rerun, it should fix this issue.

**Comment by komalsrathi** [comment]
Hmm ok. I removed the folder and reran:

```
[rathik@reslnrefo01 bcbio-nextgen]$ ./local/bin/bcbio_nextgen.py upgrade --data --aligners star
Upgrading bcbio
Upgrading bcbio-nextgen data files
--2018-07-11 11:51:31--  https://github.com/chapmanb/cloudbiolinux/archive/master.tar.gz
Resolving github.com... 192.30.253.113, 192.30.253.112
Connecting to github.com|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master [following]
--2018-07-11 11:51:31--  https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master
Resolving codeload.github.com... 192.30.253.121, 192.30.253.120
Connecting to codeload.github.com|192.30.253.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘STDOUT’

     0K ........ ........ ........ ........ ........ ........  429K
  3072K ........ ........ ........ ......                      546K=11s

2018-07-11 11:51:42 (468 KB/s) - written to stdout [5170680]

Setting up virtual machine
INFO: <cloudbio.flavor.Flavor instance at 0x7f4c8d9bbd40>
INFO: This is a ngs_pipeline_minimal flavor
INFO: Reading default fabricrc.txt
DBG [config.py]: Using config file /mnt/isilon/cbmi/variome/bin/bcbio-nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/../config/fabricrc.txt
INFO: Distribution __auto__
INFO: Get local environment
INFO: CentOS setup
DBG [distribution.py]: NixPkgs: Ignored
[localhost] local: echo $HOME
[localhost] local: uname -m
INFO: Now, testing connection to host...
INFO: Connection to host appears to work!
DBG [utils.py]: Expand paths
INFO: List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['star', 'bwa', 'bowtie2', 'rtg', 'twobit'], 'genomes': [{'name': 'Human (GRCh37)', 'validation': ['giab-NA12878', 'giab-NA24385', 'giab-NA24631', 'dream-syn3', 'dream-syn4', 'giab-NA12878-NA24385-somatic'], 'annotations': ['GA4GH_problem_regions', 'capture_regions', 'MIG', 'prioritize', 'dbsnp', 'hapmap', '1000g_omni_snps', 'ACMG56_genes', '1000g_snps', 'mills_indels', 'clinvar', 'cosmic', 'ancestral', 'qsignature', 'genesplicer', 'effects_transcripts', 'vcfanno', 'viral', 'transcripts', 'RADAR', 'mirbase'], 'dbkey': 'GRCh37', 'indexes': ['seq', 'twobit']}], 'install_uniref': False}'): Human (GRCh37)
Running GGD recipe: GRCh37 srnaseq 20180710
--2018-07-11 11:52:05--  http://www.regulatoryrna.org/database/piRNA/download/archive/v1.0/bed/piR_hg19_v1.0.bed.gz
Resolving www.regulatoryrna.org... 159.226.118.231
Connecting to www.regulatoryrna.org|159.226.118.231|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7355917 (7.0M) [application/x-gzip]
Saving to: ‘piR_hg19_v1.0.bed.gz.4’

piR_hg19_v1.0.bed.gz.4                  100%[=============================================================================>]   7.01M  17.6MB/s    in 0.4s    

2018-07-11 11:52:06 (17.6 MB/s) - ‘piR_hg19_v1.0.bed.gz.4’ saved [7355917/7355917]```

but it's been stuck for the past 8 mins or so.. so I will wait for another hour maybe and update.

**Comment by komalsrathi** [comment]
Ok - this was resolved. Thanks for your help!

**Comment by lpantano** [comment]
sorry about the issues, I’ll try to replicate and let you know something. Maybe we need the options for wget for that file if that is the problem.

**Comment by roryk** [comment]
Thanks Komal!

**Comment by komalsrathi** [comment]
@lpantano actually this was resolved - not sure if you saw it. Line 18 in ggd-run.sh had to be commented out - it was just documentation which wasn't commented out. And then I removed $bin/bcbio-nextgen/tmpbcbio-install/ per the suggestion. It worked out for me.

**Comment by lpantano** [comment]
Thanks, I saw it. Glad it worked. Sorry about the typo.
