### ISSUE TITLE
GATK processing requested but gatk or older jar install not found

### ISSUE THREAD

**Issue by komalsrathi** [bcbio/bcbio-nextgen#2445]
Hi,

This is my config file for running variant-calling on RNA-seq:

```
details:
- algorithm:
    aligner: star
    variantcaller: gatk-haplotype
    tools_off: gatk4
  analysis: RNA-seq
  description: 'Sample 1: CDL-634-13P'
  files:
  - CDL-634-13P_pe_1.fq.gz
  - CDL-634-13P_pe_2.fq.gz
  genome_build: GRCh37
  metadata:
    batch: CDL-634-13P
fc_name: CDL-634-13P-CDLS
upload:
  dir: final
```

Does it look okay? Because I am getting this error after the deduplicated bam file is indexed:

```
[2018-07-11T19:41Z] Index BAM file: Sample_1__CDL-634-13P-dedup.bam
Traceback (most recent call last):
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/local/bin/bcbio_nextgen.py", line 241, in <module>
    main(**kwargs)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/local/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 260, in rnaseqpipeline
    samples = rnaseq.rnaseq_variant_calling(samples, run_parallel)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 49, in rnaseq_variant_calling
    samples = run_parallel("run_rnaseq_variant_calling", samples)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 949, in __call__
    if self.dispatch_one_batch(iterator):
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 791, in dispatch_one_batch
    self._dispatch(tasks)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 748, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 183, in apply_async
    result = ImmediateResult(func)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 543, in __init__
    self.results = batch()
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 224, in __call__
    for func, args, kwargs in self.items]
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 243, in run_rnaseq_variant_calling
    return rnaseq.run_rnaseq_variant_calling(*args)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 83, in run_rnaseq_variant_calling
    data = variation.rnaseq_gatk_variant_calling(data)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/variation.py", line 20, in rnaseq_gatk_variant_calling
    data = gatk_splitreads(data)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/variation.py", line 53, in gatk_splitreads
    broad_runner.run_gatk(params)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 347, in run_gatk
    cl = self.cl_gatk(params, tmp_dir, memscale=memscale, parallel_gc=parallel_gc)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 278, in cl_gatk
    raise ValueError("GATK processing requested but gatk or older jar install not found: "
ValueError: GATK processing requested but gatk or older jar install not found: http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#gatk-and-mutect-mutect2
```

**Comment by roryk** [comment]
Hi Komal,

Sorry for the problems. To use GATK3 you'll have to install it manually, since we're not allowed to bundle it in bcbio.

https://github.com/bcbio/bcbio-nextgen/blob/master/docs/contents/installation.rst#gatk-and-mutectmutect2 has instructions regarding how to do that.

**Comment by komalsrathi** [comment]
Can I actually use gatk4 - as in remove it from tools_off and will it use the installation that comes with bcbio-nextgen?

**Comment by roryk** [comment]
Yes, but GATK4 does much more poorly for RNA-seq variant calling than GATK3. See https://github.com/bcbio/bcbio-nextgen/issues/2410 for some discussion about that.

**Comment by komalsrathi** [comment]
Ok this was really helpful - thank you for clarifying.
