### ISSUE TITLE
gatk-launch: command not found

### ISSUE THREAD

**Issue by komalsrathi** [bcbio/bcbio-nextgen#2447]
Hi,

Sorry to bother again. Running the `bcbio_nextgen.py config.yaml -n 8` command is giving me this error now:

```
[2018-07-12T18:01Z] System YAML configuration: /mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/galaxy/bcbio_system.yaml
[2018-07-12T18:01Z] Resource requests: picard; memory: 3.00; cores: 16
[2018-07-12T18:01Z] Configuring 1 jobs to run, using 1 cores each with 3.00g of memory reserved for each job
[2018-07-12T18:01Z] Timing: organize samples
[2018-07-12T18:01Z] multiprocessing: organize_samples
[2018-07-12T18:01Z] Using input YAML configuration: /mnt/isilon/cbmi/variome/rathik/mendelian_rnaseq/bcbio_out/config.yaml
[2018-07-12T18:01Z] Checking sample YAML configuration: /mnt/isilon/cbmi/variome/rathik/mendelian_rnaseq/bcbio_out/config.yaml
/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/gffutils/interface.py:161: UserWarning: It appears that this database has not had the ANALYZE sqlite3 command run on it. Doing so can dramatically speed up queries, and is done by default for databases created with gffutils >0.8.7.1 (this database was created with version 0.8.6.1) Consider calling the analyze() method of this object.
  "method of this object." % self.version)
[2018-07-12T18:01Z] Testing minimum versions of installed programs
[2018-07-12T18:01Z] multiprocessing: prepare_sample
[2018-07-12T18:01Z] Preparing Sample_1__CDL-634-13P
[2018-07-12T18:01Z] Resource requests: picard, samtools, star; memory: 3.00, 3.00, 3.00; cores: 16, 16, 16
[2018-07-12T18:01Z] Configuring 1 jobs to run, using 8 cores each with 24.1g of memory reserved for each job
[2018-07-12T18:01Z] Timing: alignment
[2018-07-12T18:01Z] multiprocessing: disambiguate_split
[2018-07-12T18:01Z] multiprocessing: process_alignment
[2018-07-12T18:01Z] Aligning lane Sample_1__CDL-634-13P with star aligner
[2018-07-12T18:01Z] Resource requests: cufflinks, samtools; memory: 3.00, 3.00; cores: 16, 16
[2018-07-12T18:01Z] Configuring 1 jobs to run, using 8 cores each with 24.1g of memory reserved for each job
[2018-07-12T18:01Z] Timing: disambiguation
[2018-07-12T18:01Z] Timing: transcript assembly
[2018-07-12T18:01Z] Timing: estimate expression (threaded)
[2018-07-12T18:01Z] multiprocessing: generate_transcript_counts
[2018-07-12T18:01Z] multiprocessing: run_salmon_index
[2018-07-12T18:01Z] Transcriptome index for /mnt/isilon/cbmi/variome/rathik/mendelian_rnaseq/bcbio_out/inputs/transcriptome/GRCh37.fa detected, skipping building.
[2018-07-12T18:01Z] multiprocessing: run_salmon_reads
[2018-07-12T18:01Z] multiprocessing: detect_fusions
[2018-07-12T18:01Z] Resource requests: dexseq, express; memory: 10.00, 8.00; cores: 1, 1
[2018-07-12T18:01Z] Configuring 1 jobs to run, using 1 cores each with 10.00g of memory reserved for each job
[2018-07-12T18:01Z] Timing: estimate expression (single threaded)
[2018-07-12T18:07Z] Resource requests: gatk, vardict; memory: 3.50, 3.00; cores: 1, 16
[2018-07-12T18:07Z] Configuring 1 jobs to run, using 8 cores each with 28.1g of memory reserved for each job
[2018-07-12T18:07Z] Timing: RNA-seq variant calling
[2018-07-12T18:07Z] multiprocessing: run_rnaseq_variant_calling
[2018-07-12T18:07Z] GATK: SplitNCigarReads
[2018-07-12T18:07Z] /usr/bin/bash: gatk-launch: command not found
[2018-07-12T18:07Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && export PATH=/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/bin:$PATH && gatk-launch --java-options '-Xms454m -Xmx3181m -XX:+UseSerialGC -Djava.io.tmpdir=/mnt/isilon/cbmi/variome/rathik/mendelian_rnaseq/bcbio_out/bcbiotx/tmp12jmC0' SplitNCigarReads -R /mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -I /mnt/isilon/cbmi/variome/rathik/mendelian_rnaseq/bcbio_out/align/Sample_1__CDL-634-13P/Sample_1__CDL-634-13P-dedup.bam --output /mnt/isilon/cbmi/variome/rathik/mendelian_rnaseq/bcbio_out/bcbiotx/tmpj3QkzE/Sample_1__CDL-634-13P-dedup.splitN.bam
/usr/bin/bash: gatk-launch: command not found
' returned non-zero exit status 127
Traceback (most recent call last):
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/local/bin/bcbio_nextgen.py", line 241, in <module>
    main(**kwargs)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/local/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 260, in rnaseqpipeline
    samples = rnaseq.rnaseq_variant_calling(samples, run_parallel)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 49, in rnaseq_variant_calling
    samples = run_parallel("run_rnaseq_variant_calling", samples)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 949, in __call__
    if self.dispatch_one_batch(iterator):
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 791, in dispatch_one_batch
    self._dispatch(tasks)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 748, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 183, in apply_async
    result = ImmediateResult(func)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 543, in __init__
    self.results = batch()
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 224, in __call__
    for func, args, kwargs in self.items]
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 243, in run_rnaseq_variant_calling
    return rnaseq.run_rnaseq_variant_calling(*args)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 83, in run_rnaseq_variant_calling
    data = variation.rnaseq_gatk_variant_calling(data)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/variation.py", line 20, in rnaseq_gatk_variant_calling
    data = gatk_splitreads(data)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/variation.py", line 53, in gatk_splitreads
    broad_runner.run_gatk(params)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 353, in run_gatk
    log_error=log_error)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && export PATH=/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/bin:$PATH && gatk-launch --java-options '-Xms454m -Xmx3181m -XX:+UseSerialGC -Djava.io.tmpdir=/mnt/isilon/cbmi/variome/rathik/mendelian_rnaseq/bcbio_out/bcbiotx/tmp12jmC0' SplitNCigarReads -R /mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -I /mnt/isilon/cbmi/variome/rathik/mendelian_rnaseq/bcbio_out/align/Sample_1__CDL-634-13P/Sample_1__CDL-634-13P-dedup.bam --output /mnt/isilon/cbmi/variome/rathik/mendelian_rnaseq/bcbio_out/bcbiotx/tmpj3QkzE/Sample_1__CDL-634-13P-dedup.splitN.bam
/usr/bin/bash: gatk-launch: command not found
' returned non-zero exit status 127
```

Config file:
```
details:
- algorithm:
    aligner: star
    variantcaller: gatk-haplotype
    # tools_off: gatk4
  analysis: RNA-seq
  description: 'Sample 1: CDL-634-13P'
  files:
  - /mnt/isilon/cbmi/variome/rathik/mendelian_rnaseq/fastq/CDL-634-13P/CDL-634-13P_pe_1.fq.gz
  - /mnt/isilon/cbmi/variome/rathik/mendelian_rnaseq/fastq/CDL-634-13P/CDL-634-13P_pe_2.fq.gz
  genome_build: GRCh37
  metadata:
    batch: CDL-634-13P
fc_name: CDL-634-13P-CDLS
upload:
  dir: /mnt/isilon/cbmi/variome/rathik/mendelian_rnaseq/bcbio_out/final
```

**Comment by roryk** [comment]
Hi Komal,

If you do a `bcbio_nextgen.py upgrade -u stable --tools` it should fix this issue.

**Comment by komalsrathi** [comment]
Thanks looks like it is working!
