### ISSUE TITLE
Peddy ZeroDivisionError

### ISSUE THREAD

**Issue by phu5ion** [bcbio/bcbio-nextgen#2458]
Hi,

Sorry to bother again. After upgrading to the latest stable version (as per #2447 because of the issue reported there) I ran into a problem with Peddy.

```
[2018-07-18T00:59Z] peddy is not installed, not human or sample VCFs don't match, skipping correspondence checking for None.
[2018-07-18T00:59Z] peddy is not installed, not human or sample VCFs don't match, skipping correspondence checking for None.
[2018-07-18T00:59Z] Running peddy on /mnt/projects/ngbhs/cirqseq/2017_bcbio/20180711_YF_onoffbeads/YF_onoffbeads/work/mutect2/HD_5pct_100ng-vepeffects-annotated.vcf.gz against /mnt/projects/ngbhs/cirqseq/2017_bcbio/20180711_YF_onoffbeads/YF_onoffbeads/work/mutect2/HD_5pct_100ng-vepeffects-annotated.ped.
[2018-07-18T00:59Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/bin/peddy -p 16 --sites hg38 --plot --prefix /mnt/projects/ngbhs/cirqseq/2017_bcbio/20180711_YF_onoffbeads/YF_onoffbeads/work/bcbiotx/tmpqDhzYL/HD_5pct_100ng /mnt/projects/ngbhs/cirqseq/2017_bcbio/20180711_YF_onoffbeads/YF_onoffbeads/work/mutect2/HD_5pct_100ng-vepeffects-annotated.vcf.gz /mnt/projects/ngbhs/cirqseq/2017_bcbio/20180711_YF_onoffbeads/YF_onoffbeads/work/mutect2/HD_5pct_100ng-vepeffects-annotated.ped 2> /mnt/projects/ngbhs/cirqseq/2017_bcbio/20180711_YF_onoffbeads/YF_onoffbeads/work/bcbiotx/tmpqDhzYL/run-stderr.log
' returned non-zero exit status 1
[2018-07-18T00:59Z] 2018-07-18 08:59:43 n070 peddy.cli[186636] INFO Running Peddy version 0.4.2
2018-07-18 08:59:43 n070 peddy.cli[186636] WARNING 1 samples in vcf not in ped:
HD_WildType_100ng_OnBeads

2018-07-18 08:59:43 n070 peddy.cli[186636] INFO ped_check
2018-07-18 08:59:51 n070 peddy.peddy[186636] INFO plotting
2018-07-18 08:59:51 n070 matplotlib.legend[186636] WARNING No handles with labels found to put in legend.
2018-07-18 08:59:52 n070 peddy.cli[186636] INFO ran in 8.6 seconds
2018-07-18 08:59:52 n070 peddy.cli[186636] INFO het_check
2018-07-18 08:59:54 n070 peddy.pca[186636] INFO loaded and subsetted thousand-genomes genotypes (shape: (2504, 4)) in 0.6 seconds
2018-07-18 08:59:55 n070 peddy.pca[186636] INFO ran randomized PCA on thousand-genomes samples at 4 sites in 1.2 seconds
/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/sklearn/decomposition/base.py:133: RuntimeWarning: divide by zero encountered in divide
  X_transformed /= np.sqrt(self.explained_variance_)
Traceback (most recent call last):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/bin/peddy", line 11, in <module>
    load_entry_point('peddy==0.4.2', 'console_scripts', 'peddy')()
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/peddy/cli.py", line 207, in peddy
    in ("ped_check", "het_check", "sex_check")]):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/peddy/cli.py", line 43, in run
    prefix=prefix, **kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/peddy/peddy.py", line 878, in het_check
    pca_df, background_pca_df = pca(pca_plot, sitesfile, gt_types, sites)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/peddy/pca.py", line 81, in pca
    pred = clf.predict(genotype_matrix)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/sklearn/utils/metaestimators.py", line 115, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/sklearn/pipeline.py", line 307, in predict
    return self.steps[-1][-1].predict(Xt)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/sklearn/svm/base.py", line 548, in predict
    y = super(BaseSVC, self).predict(X)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/sklearn/svm/base.py", line 308, in predict
    X = self._validate_for_predict(X)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/sklearn/svm/base.py", line 439, in _validate_for_predict
    X = check_array(X, accept_sparse='csr', dtype=np.float64, order="C")
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py", line 453, in check_array
    _assert_all_finite(array)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py", line 44, in _assert_all_finite
    " or a value too large for %r." % X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

Traceback (most recent call last):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/bin/bcbio_nextgen.py", line 242, in <module>
    main(**kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/bin/bcbio_nextgen.py", line 47, in main
    run_main(**kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 190, in variant2pipeline
    samples = peddy.run_peddy_parallel(samples, run_parallel)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/variation/peddy.py", line 33, in run_peddy_parallel
    samples = parallel_fn("run_peddy", [[x] for x in to_run])
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 332, in __init__
    self.results = batch()
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 23, in run_peddy
    return peddy.run_peddy(*args)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/variation/peddy.py", line 88, in run_peddy
    do.run(cmd.format(**locals()), message.format(**locals()))
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/bin/peddy -p 16 --sites hg38 --plot --prefix /mnt/projects/ngbhs/cirqseq/2017_bcbio/20180711_YF_onoffbeads/YF_onoffbeads/work/bcbiotx/tmpqDhzYL/HD_5pct_100ng /mnt/projects/ngbhs/cirqseq/2017_bcbio/20180711_YF_onoffbeads/YF_onoffbeads/work/mutect2/HD_5pct_100ng-vepeffects-annotated.vcf.gz /mnt/projects/ngbhs/cirqseq/2017_bcbio/20180711_YF_onoffbeads/YF_onoffbeads/work/mutect2/HD_5pct_100ng-vepeffects-annotated.ped 2> /mnt/projects/ngbhs/cirqseq/2017_bcbio/20180711_YF_onoffbeads/YF_onoffbeads/work/bcbiotx/tmpqDhzYL/run-stderr.log
' returned non-zero exit status 1
```
Could you help pls? Thank you!

**Comment by roryk** [comment]
Thanks! Is there any way you could pass on these two files:

```
/mnt/projects/ngbhs/cirqseq/2017_bcbio/20180711_YF_onoffbeads/YF_onoffbeads/work/mutect2/HD_5pct_100ng-vepeffects-annotated.vcf.gz 
```
```
/mnt/projects/ngbhs/cirqseq/2017_bcbio/20180711_YF_onoffbeads/YF_onoffbeads/work/mutect2/HD_5pct_100ng-vepeffects-annotated.ped.
```
so we can try to reproduce and fix the issue in peddy?

**Comment by phu5ion** [comment]
[files.zip](https://github.com/bcbio/bcbio-nextgen/files/2205896/files.zip)

Hi here you go~

**Comment by phu5ion** [comment]
Hi how's this going?

**Comment by chapmanb** [comment]
Thanks for the test files and apologies the delay in resolving this. I pushed a fix which should skip peddy for this input. The underlying issue is that the sample has no non-filtered variants so nothing useful to process on. I've added a check for this case and generally tried to make the error reporting more robust and easy to understand.

Thank you again for reporting this and the detailed report. Please let us know if you run into any other issues.
