### ISSUE TITLE
RNA-Seq pipleline fails at kraken

### ISSUE THREAD

**Issue by PatrickJReed** [bcbio/bcbio-nextgen#2475]
I'm trying to add kraken to my analysis pipelines and am getting a the following issue in my output:

[2018-08-02T21:34Z] System YAML configuration: /usr/local/share/bcbio/galaxy/bcbio_system.yaml
[2018-08-02T21:34Z] Resource requests: picard; memory: 3.00; cores: 16
[2018-08-02T21:34Z] Configuring 18 jobs to run, using 1 cores each with 3.00g of memory reserved for each job
[2018-08-02T21:34Z] Timing: organize samples
[2018-08-02T21:34Z] multiprocessing: organize_samples
[2018-08-02T21:34Z] multiprocessing: prepare_sample
[2018-08-02T21:34Z] Resource requests: hisat2, picard, samtools; memory: 3.00, 3.00, 3.00; cores: 16, 16, 16
[2018-08-02T21:34Z] Configuring 1 jobs to run, using 16 cores each with 48.1g of memory reserved for each job
[2018-08-02T21:34Z] Timing: alignment
[2018-08-02T21:34Z] multiprocessing: disambiguate_split
[2018-08-02T21:34Z] multiprocessing: process_alignment
[2018-08-02T21:34Z] Aligning lane MDD_mayo_iPS_C1_CTL_iPSC_meta31 with hisat2 aligner
[2018-08-02T21:34Z] Aligning lane MDD_mayo_Neuron_C1_CTL_Neuron_meta32 with hisat2 aligner
[2018-08-02T21:34Z] Aligning lane MDD_mayo_iPS_C2_CTL_iPSC_meta33 with hisat2 aligner
[2018-08-02T21:34Z] Aligning lane MDD_mayo_Neuron_C2_CTL_Neuron_meta34 with hisat2 aligner
[2018-08-02T21:34Z] Aligning lane MDD_mayo_iPS_C3_CTL_iPSC_meta35 with hisat2 aligner
[2018-08-02T21:34Z] Aligning lane MDD_mayo_Neuron_C3_CTL_Neuron_meta36 with hisat2 aligner
[2018-08-02T21:34Z] Aligning lane MDD_mayo_iPS_NR1_MDD_iPSC_meta154 with hisat2 aligner
[2018-08-02T21:34Z] Aligning lane MDD_mayo_Neuron_NR1_MDD_Neuron_meta155 with hisat2 aligner
[2018-08-02T21:34Z] Aligning lane MDD_mayo_iPS_NR2_MDD_iPSC_meta156 with hisat2 aligner
[2018-08-02T21:34Z] Aligning lane MDD_mayo_Neuron_NR2_MDD_Neuron_meta157 with hisat2 aligner
[2018-08-02T21:34Z] Aligning lane MDD_mayo_iPS_NR3_MDD_iPSC_meta158 with hisat2 aligner
[2018-08-02T21:34Z] Aligning lane MDD_mayo_Neuron_NR3_MDD_Neuron_meta159 with hisat2 aligner
[2018-08-02T21:34Z] Aligning lane MDD_mayo_iPS_R1_MDD_iPSC_meta160 with hisat2 aligner
[2018-08-02T21:34Z] Aligning lane MDD_mayo_Neuron_R1_MDD_Neuron_meta161 with hisat2 aligner
[2018-08-02T21:34Z] Aligning lane MDD_mayo_iPS_R2_MDD_iPSC_meta162 with hisat2 aligner
[2018-08-02T21:34Z] Aligning lane MDD_mayo_Neuron_R2_MDD_Neuron_meta163 with hisat2 aligner
[2018-08-02T21:34Z] Aligning lane MDD_mayo_iPS_R3_MDD_iPSC_meta164 with hisat2 aligner
[2018-08-02T21:34Z] Aligning lane MDD_mayo_Neuron_R3_MDD_Neuron_meta165 with hisat2 aligner
[2018-08-02T21:34Z] Resource requests: cufflinks, samtools; memory: 3.00, 3.00; cores: 16, 16
[2018-08-02T21:34Z] Configuring 1 jobs to run, using 16 cores each with 48.1g of memory reserved for each job
[2018-08-02T21:34Z] Timing: disambiguation
[2018-08-02T21:34Z] Timing: transcript assembly
[2018-08-02T21:34Z] Timing: estimate expression (threaded)
[2018-08-02T21:34Z] multiprocessing: generate_transcript_counts
[2018-08-02T21:34Z] multiprocessing: run_salmon_index
[2018-08-02T21:34Z] Transcriptome index for /home/ubuntu/efs/metapsych/metapsych-krishna-mdd/work/inputs/transcriptome/hg38.fa detected, skipping building.
[2018-08-02T21:34Z] Transcriptome index for /home/ubuntu/efs/metapsych/metapsych-krishna-mdd/work/inputs/transcriptome/hg38.fa detected, skipping building.
[2018-08-02T21:34Z] Transcriptome index for /home/ubuntu/efs/metapsych/metapsych-krishna-mdd/work/inputs/transcriptome/hg38.fa detected, skipping building.
[2018-08-02T21:34Z] Transcriptome index for /home/ubuntu/efs/metapsych/metapsych-krishna-mdd/work/inputs/transcriptome/hg38.fa detected, skipping building.
[2018-08-02T21:34Z] Transcriptome index for /home/ubuntu/efs/metapsych/metapsych-krishna-mdd/work/inputs/transcriptome/hg38.fa detected, skipping building.
[2018-08-02T21:34Z] Transcriptome index for /home/ubuntu/efs/metapsych/metapsych-krishna-mdd/work/inputs/transcriptome/hg38.fa detected, skipping building.
[2018-08-02T21:34Z] Transcriptome index for /home/ubuntu/efs/metapsych/metapsych-krishna-mdd/work/inputs/transcriptome/hg38.fa detected, skipping building.
[2018-08-02T21:34Z] Transcriptome index for /home/ubuntu/efs/metapsych/metapsych-krishna-mdd/work/inputs/transcriptome/hg38.fa detected, skipping building.
[2018-08-02T21:34Z] Transcriptome index for /home/ubuntu/efs/metapsych/metapsych-krishna-mdd/work/inputs/transcriptome/hg38.fa detected, skipping building.
[2018-08-02T21:34Z] Transcriptome index for /home/ubuntu/efs/metapsych/metapsych-krishna-mdd/work/inputs/transcriptome/hg38.fa detected, skipping building.
[2018-08-02T21:34Z] Transcriptome index for /home/ubuntu/efs/metapsych/metapsych-krishna-mdd/work/inputs/transcriptome/hg38.fa detected, skipping building.
[2018-08-02T21:34Z] Transcriptome index for /home/ubuntu/efs/metapsych/metapsych-krishna-mdd/work/inputs/transcriptome/hg38.fa detected, skipping building.
[2018-08-02T21:34Z] Transcriptome index for /home/ubuntu/efs/metapsych/metapsych-krishna-mdd/work/inputs/transcriptome/hg38.fa detected, skipping building.
[2018-08-02T21:34Z] Transcriptome index for /home/ubuntu/efs/metapsych/metapsych-krishna-mdd/work/inputs/transcriptome/hg38.fa detected, skipping building.
[2018-08-02T21:34Z] Transcriptome index for /home/ubuntu/efs/metapsych/metapsych-krishna-mdd/work/inputs/transcriptome/hg38.fa detected, skipping building.
[2018-08-02T21:34Z] Transcriptome index for /home/ubuntu/efs/metapsych/metapsych-krishna-mdd/work/inputs/transcriptome/hg38.fa detected, skipping building.
[2018-08-02T21:34Z] Transcriptome index for /home/ubuntu/efs/metapsych/metapsych-krishna-mdd/work/inputs/transcriptome/hg38.fa detected, skipping building.
[2018-08-02T21:34Z] Transcriptome index for /home/ubuntu/efs/metapsych/metapsych-krishna-mdd/work/inputs/transcriptome/hg38.fa detected, skipping building.
[2018-08-02T21:34Z] multiprocessing: run_salmon_reads
[2018-08-02T21:34Z] multiprocessing: detect_fusions
[2018-08-02T21:34Z] Resource requests: dexseq, express; memory: 10.00, 8.00; cores: 1, 1
[2018-08-02T21:34Z] Configuring 6 jobs to run, using 1 cores each with 10.00g of memory reserved for each job
[2018-08-02T21:34Z] Timing: estimate expression (single threaded)
[2018-08-02T21:38Z] Resource requests: gatk, vardict; memory: 3.50, 3.00; cores: 1, 16
[2018-08-02T21:38Z] Configuring 1 jobs to run, using 16 cores each with 56.1g of memory reserved for each job
[2018-08-02T21:38Z] Timing: RNA-seq variant calling
[2018-08-02T21:38Z] multiprocessing: run_rnaseq_variant_calling
[2018-08-02T21:38Z] Resource requests: fastqc, gatk, kraken, preseq, qualimap, samtools; memory: 3.00, 3.50, 3.00, 3.00, 4.00, 3.00; cores: 16, 1, 16, 16, 1, 16
[2018-08-02T21:38Z] Configuring 1 jobs to run, using 16 cores each with 64.1g of memory reserved for each job
[2018-08-02T21:38Z] Timing: quality control
[2018-08-02T21:38Z] multiprocessing: pipeline_summary
[2018-08-02T21:38Z] QC: MDD_mayo_iPS_C1_CTL_iPSC_meta31 kraken
[2018-08-02T21:38Z] Running kraken to determine contaminant: MDD_mayo_iPS_C1_CTL_iPSC_meta31
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 242, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 47, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 272, in rnaseqpipeline
    samples = qcsummary.generate_parallel(samples, run_parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 39, in generate_parallel
    qced = run_parallel("pipeline_summary", to_analyze)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 949, in __call__
    if self.dispatch_one_batch(iterator):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 791, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 748, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 183, in apply_async
    result = ImmediateResult(func)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 543, in __init__
    self.results = batch()
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 224, in __call__
    for func, args, kwargs in self.items]
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 208, in pipeline_summary
    return qcsummary.pipeline_summary(*args)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 70, in pipeline_summary
    data["summary"] = _run_qc_tools(work_bam, work_data)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 161, in _run_qc_tools
    out = qc_fn(bam_file, data, cur_qc_dir)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/qc/kraken.py", line 29, in run
    if not os.path.exists(db):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, list found

everything works great until it hits kraken, my yaml template is:

# Template for human RNA-seq using Illumina prepared samples
---
details:
  - analysis: RNA-seq
    metadata:
      batch:
      phenotype:
    genome_build: hg38
    algorithm:
      aligner: hisat2
      adapters: [truseq, polya]
      expression_caller: [salmon]
      tools_on: [qualimap]
      kraken: [minikraken]
upload:
  dir: ../final

Any help with this would be awesome!

**Comment by chapmanb** [comment]
Patrick;
Thanks much for the detailed report and apologies about the issue. The problem is that kraken expects a single value and the configuration provides it as a list. If you change:
```
kraken: [minikraken]
```
to
```
kraken: minikraken
```
It should fix the issue. I also pushed a fix to handle this to the latest development version, so updating to that is another option to avoid the error. Hope this helps get your analysis finished.

**Comment by roryk** [comment]
Thanks @chapmanb, I missed this one.

**Comment by PatrickJReed** [comment]
easy fix, thank you!!
