### ISSUE TITLE
multiqc 'Directory not empty' error

### ISSUE THREAD

**Issue by esebesty** [bcbio/bcbio-nextgen#2476]
Hi,

I have the following error at the multiqc step:

<pre>
Traceback (most recent call last):
  File "/lustre/data/t-tcga/esebesty/bcbio/data/anaconda/bin/multiqc", line 4, in <module>
    __import__('pkg_resources').run_script('multiqc==0.6', 'multiqc')
  File "/lustre/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
  File "/lustre/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script
  File "/lustre/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/multiqc-0.6-py2.7.egg/EGG-INFO/scripts/multiqc", line 436, in <module>
    multiqc()
  File "/lustre/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/lustre/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/lustre/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/lustre/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/lustre/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/multiqc-0.6-py2.7.egg/EGG-INFO/scripts/multiqc", line 425, in multiqc
    log.copy_tmp_log()
  File "/lustre/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/multiqc-0.6-py2.7.egg/multiqc/utils/log.py", line 57, in copy_tmp_log
    shutil.rmtree(log_tmp_dir)
  File "/lustre/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/lustre/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/mnt/infi/data/t-tcga/bcbio_analysis/bcbio_tmp/tmpthcUat'
' returned non-zero exit status 1

</pre>

so it seems that shutil.py is having some trouble to remove a temporary directory, that is not empty. However, the directory is empty and anyway os.rmdir should be able to remove non-empty directories. This seems to be related to an issue discussed [here](https://github.com/hashdist/hashdist/issues/113). I have the feeling that we have some kind of filesystem/network/file locking issue with our brand new infinidat filesystem.

Until we figure that out, can I somehow disable multiqc or add some option so it doesn't want to clean up?

Thanks,

Endre

**Comment by chapmanb** [comment]
Endre;
Thanks much for the report. Unfortunately the failing code is happening inside multiqc itself, so we don't have any easy ways to avoid the directory cleanup from within bcbio. Practically, there is going to a lot of code that assumes filesystem stability so from a general perspective not running multiqc isn't going to solve your issues when running pipelines. Are you seeing this process dying regularly, or is it only intermittent?

My practical suggestion would be to work on the filesystem issues as an actual fix. If restarts work in the short term that would be the best way to get analyses processed while working on the underlying issues. Would that work okay for your needs?

**Comment by roryk** [comment]
Closing as this seems like a filesystem problem.
