### ISSUE TITLE
joblib? error during align prep

### ISSUE THREAD

**Issue by PatrickJReed** [bcbio/bcbio-nextgen#2490]
Hey Guys, 

I'm getting the following error at the start of a WGS run.  I'm running the most recent development version as of this morning and the error persists.

[2018-08-20T17:44Z] System YAML configuration: /usr/local/share/bcbio/galaxy/bcbio_system.yaml
[2018-08-20T17:44Z] Resource requests: bwa, sambamba, samtools; memory: 3.00, 3.00, 3.00; cores: 16, 16, 16
[2018-08-20T17:44Z] Configuring 2 jobs to run, using 16 cores each with 48.1g of memory reserved for each job
[2018-08-20T17:44Z] Timing: organize samples
[2018-08-20T17:44Z] multiprocessing: organize_samples
[2018-08-20T17:44Z] Timing: alignment preparation
[2018-08-20T17:44Z] multiprocessing: prep_align_inputs
Process LokyProcess-2:
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/joblib/externals/loky/process_executor.py", line 428, in _process_worker
    result_queue.put(_ResultItem(call_item.work_id, exception=exc))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/joblib/externals/loky/backend/queues.py", line 233, in put
    obj = CustomizableLokyPickler.dumps(obj, reducers=self._reducers)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/joblib/externals/loky/backend/reduction.py", line 145, in dumps
    p.dump(obj)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/pickle.py", line 425, in save_reduce
    save(state)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/pickle.py", line 669, in _batch_setitems
    save(v)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/pickle.py", line 401, in save_reduce
    save(args)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/pickle.py", line 568, in save_tuple
    save(element)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/pickle.py", line 401, in save_reduce
    save(args)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/pickle.py", line 568, in save_tuple
    save(element)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/pickle.py", line 754, in save_global
    (obj, module, name))
PicklingError: Can't pickle <class 'joblib.my_exceptions.JoblibCalledProcessError'>: it's not found as joblib.my_exceptions.JoblibCalledProcessError
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 242, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 47, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 128, in variant2pipeline
    samples = run_parallel("prep_align_inputs", samples)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 994, in __call__
    self.retrieve()
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 897, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 515, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/externals/loky/_base.py", line 431, in result
    return self.__get_result()
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/externals/loky/_base.py", line 382, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A process in the executor was terminated abruptly while the future was running or pending.

**Comment by PatrickJReed** [comment]
FYI, Im running bcbio on an amazon EC2 ubuntu instance.  bcbio is installed on the boot drive with an EFS mounted to process the run.

**Comment by roryk** [comment]
It looks like you have another PYTHON site-libs that is getting injected into your path from .local:

```
/home/ubuntu/.local/lib/python2.7/site-packages/joblib/externals/loky/backend/queues.py
```

Is there some way you could nuke that in your instance?

**Comment by PatrickJReed** [comment]
Thanks Rory, did the trick.

**Comment by roryk** [comment]
Awesome, glad that worked! Thanks so much for following up.
