### ISSUE TITLE
Complete removal of installed tool

### ISSUE THREAD

**Issue by jimmybgammyknee** [bcbio/bcbio-nextgen#2498]
Im getting an update error for Novoalign which I see a few people are currently having (https://groups.google.com/forum/#!msg/biovalidation/ss3wTUCbUWM/mYMRmrvVEwAJ).

```
ERROR conda.core.link:_execute(502): An error occurred while installing package 'bioconda::novoalign-3.09.00-h7311fa2_1'.
LinkError: post-link script failed for package bioconda::novoalign-3.09.00-h7311fa2_1
running your command again with `-v` will provide additional information
location of failed script: /apps/bioinfo/share/bcbio/anaconda/bin/.novoalign-post-link.sh
==> script messages <==

========================= Novoalign information ===========================================
Novoalign is installed. Documentation installed in
/apps/bioinfo/share/bcbio/anaconda/share/doc/novoalign

Commercial use requires a license; contact sales@novocraft.com.
License also adds multi-threading and other features.
Once you have a license file, run novoalign-license-register to install it.

Licensing information from Novocraft website:
--------------------------------------------------------------------------------------------
```
However im not actually using the tool at all so I'm keen on removing it from the installation. I've tried removing the package through conda and deleting installation directories, however whenever I go to update novoalign just re-installs. Whats the easiest way to completely remove a tool from bcbio?

PS: Apologies if this is detailed in the docs, I just can't see it

**Comment by chapmanb** [comment]
Jimmy;
Apologies about the issues with the novoalign install and thanks for the discussion. We don't have a way to exclude tools from the install like this. In general, our goals with bcbio are to create a stable distribution that doesn't require a lot of configuration to apply and maintain, so we'd rather approach this by trying to figure out what is wrong with the install so we can fix it for everyone. I haven't been able to reproduce this so have been struggling to fix, would you be able to report the output of:
```
bcbio_conda install --yes -c conda-forge -c bioconda novoalign -v
```
Does that provide any clue as to what is failing? Thanks much for the help debugging.

**Comment by jimmybgammyknee** [comment]
Thanks Brad. Here is the output:

```
bcbio_conda install --yes -c conda-forge -c bioconda novoalign -v
Solving environment: ...working...
done

## Package Plan ##

  environment location: /data/biohub/local/share/bcbio/anaconda

  added / updated specs:
    - novoalign


The following NEW packages will be INSTALLED:

    novoalign: 3.09.00-h7311fa2_1 bioconda

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... ===> LINKING PACKAGE: bioconda::novoalign-3.09.00-h7311fa2_1 <===
  prefix=/data/biohub/local/share/bcbio/anaconda
  source=/data/biohub/local/share/bcbio/anaconda/pkgs/novoalign-3.09.00-h7311fa2_1


$ bash -x /data/biohub/local/share/bcbio/anaconda/bin/.novoalign-post-link.sh
==> cwd: /data/biohub/local/share/bcbio/anaconda/bin <==
==> exit code: 48 <==
==> stdout <==

==> stderr <==
+ LMOD_PKG=/usr/share/lmod/lmod
+ LMOD_DIR=/usr/share/lmod/lmod/libexec
+ LMOD_CMD=/usr/share/lmod/lmod/libexec/lmod
+ MODULESHOME=/usr/share/lmod/lmod
+ export LMOD_PKG
+ export LMOD_CMD
+ export LMOD_DIR
+ export MODULESHOME
+ LMOD_VERSION=6.3.4
+ export LMOD_VERSION
+ '[' : '!=' : ']'
+ unalias ml
+ true
++ echo YES
++ /usr/bin/tr '[:upper:]' '[:lower:]'
+ export_module=yes
+ '[' -n '4.2.46(1)-release' -a yes '!=' no ']'
+ export -f module
+ export -f ml
+ unset export_module
+ '[' -n '' ']'
+ '[' 4 -ge 3 ']'
+ '[' -r /usr/share/lmod/lmod/init/lmod_bash_completions ']'
+ '[' -n '' ']'
+ set -e -o pipefail
+ MSGS=/data/biohub/local/share/bcbio/anaconda/.messages.txt
+ touch /data/biohub/local/share/bcbio/anaconda/.messages.txt
+ msg
+ echo
+ msg '========================= Novoalign information ==========================================='
+ echo ========================= Novoalign information ===========================================
+ msg 'Novoalign is installed.  Documentation installed in'
+ echo Novoalign is installed. Documentation installed in
+ msg /data/biohub/local/share/bcbio/anaconda/share/doc/novoalign
+ echo /data/biohub/local/share/bcbio/anaconda/share/doc/novoalign
+ msg
+ echo
+ msg 'Commercial use requires a license; contact sales@novocraft.com.'
+ echo Commercial use requires a 'license;' contact sales@novocraft.com.
+ msg 'License also adds multi-threading and other features.'
+ echo License also adds multi-threading and other features.
+ msg 'Once you have a license file, run novoalign-license-register to install it.'
+ echo Once you have a license file, run novoalign-license-register to install it.
+ msg
+ echo
+ msg 'Licensing information from Novocraft website:'
+ echo Licensing information from Novocraft website:
+ msg --------------------------------------------------------------------------------------------
+ echo --------------------------------------------------------------------------------------------
+ curl --silent -L http://www.novocraft.com/bioconda/license.txt




========================= Novoalign information ===========================================
Novoalign is installed. Documentation installed in
/data/biohub/local/share/bcbio/anaconda/share/doc/novoalign

Commercial use requires a license; contact sales@novocraft.com.
License also adds multi-threading and other features.
Once you have a license file, run novoalign-license-register to install it.

Licensing information from Novocraft website:
--------------------------------------------------------------------------------------------

===> REVERSING PACKAGE LINK: bioconda::novoalign-3.09.00-h7311fa2_1 <===
  prefix=/data/biohub/local/share/bcbio/anaconda


failed
An error occurred while installing package 'bioconda::novoalign-3.09.00-h7311fa2_1'.
LinkError: post-link script failed for package bioconda::novoalign-3.09.00-h7311fa2_1
running your command again with `-v` will provide additional information
location of failed script: /data/biohub/local/share/bcbio/anaconda/bin/.novoalign-post-link.sh
==> script messages <==

========================= Novoalign information ===========================================
Novoalign is installed. Documentation installed in
/data/biohub/local/share/bcbio/anaconda/share/doc/novoalign

Commercial use requires a license; contact sales@novocraft.com.
License also adds multi-threading and other features.
Once you have a license file, run novoalign-license-register to install it.

Licensing information from Novocraft website:
--------------------------------------------------------------------------------------------


Attempting to roll back.


Rolling back transaction: ...working... done
Traceback (most recent call last):
  File "/data/biohub/local/share/bcbio/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 819, in __call__
    return func(*args, **kwargs)
  File "/data/biohub/local/share/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "/data/biohub/local/share/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/data/biohub/local/share/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 11, in execute
    install(args, parser, 'install')
  File "/data/biohub/local/share/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 253, in install
    handle_txn(unlink_link_transaction, prefix, args, newenv)
  File "/data/biohub/local/share/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 282, in handle_txn
    unlink_link_transaction.execute()
  File "/data/biohub/local/share/bcbio/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 228, in execute
    self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
  File "/data/biohub/local/share/bcbio/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 521, in _execute
    rollback_excs,
CondaMultiError: post-link script failed for package bioconda::novoalign-3.09.00-h7311fa2_1
running your command again with `-v` will provide additional information
location of failed script: /data/biohub/local/share/bcbio/anaconda/bin/.novoalign-post-link.sh
==> script messages <==

========================= Novoalign information ===========================================
Novoalign is installed. Documentation installed in
/data/biohub/local/share/bcbio/anaconda/share/doc/novoalign

Commercial use requires a license; contact sales@novocraft.com.
License also adds multi-threading and other features.
Once you have a license file, run novoalign-license-register to install it.

Licensing information from Novocraft website:
--------------------------------------------------------------------------------------------

```

Looks like something from the license link. I can access that file ok. Perhaps the registration of the license?

Thanks for your help!

**Comment by chapmanb** [comment]
Jimmy -- thanks much for the detailed output. I agree with your assessment, something is going wrong with the call to the novoalign website, maybe it is intermittently failing. I pushed an updated package which I hope fixes the install issue by not failing on this registration. Could you try running the bcbio update again and see if that resolves the issue? Thanks again for all the help debugging.

**Comment by jimmybgammyknee** [comment]
Running now and it looks like its updated everything fine. Thanks again for your help !
