### ISSUE TITLE
Errors with GATK calling on exomes

### ISSUE THREAD

**Issue by DrMcStrange** [bcbio/bcbio-nextgen#2504]
Hi,

I've been trying to run GATK variant calling on 250 whole-exome samples, and I keep running into errors. I get several error messages like the one below in the log files, and the job stops logging at some point, but the processes keep running for some days afterwards, although they don't seem to produce output.

I've tried increasing memory allocation (since it's an OutOfMemoryError). I've currently got `jvm_opts: ["-Xms1g", "-Xmx32g"]`, and the problem persists. Any help would be much appreciated!

```
06:55:13.193 INFO  HaplotypeCaller - Shutting down engine
[August 22, 2018 6:55:13 AM AEST] org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller done. Elapsed time: 794.88 minutes.
Runtime.totalMemory()=7265714176
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at org.broadinstitute.hellbender.tools.walkers.genotyper.GenotypeAlleleCounts.alleleCountsByIndex(GenotypeAlleleCounts.java:514)
        at org.broadinstitute.hellbender.tools.walkers.genotyper.afcalc.GeneralPloidyExactAFCalculator.computeLofK(GeneralPloidyExactAFCalculator.java:276)
        at org.broadinstitute.hellbender.tools.walkers.genotyper.afcalc.GeneralPloidyExactAFCalculator.calculateACConformationAndUpdateQueue(GeneralPloidyExactAFCalculator.java:187)
        at org.broadinstitute.hellbender.tools.walkers.genotyper.afcalc.GeneralPloidyExactAFCalculator.fastCombineMultiallelicPool(GeneralPloidyExactAFCalculator.java:148)
        at org.broadinstitute.hellbender.tools.walkers.genotyper.afcalc.GeneralPloidyExactAFCalculator.combineSinglePools(GeneralPloidyExactAFCalculator.java:112)
        at org.broadinstitute.hellbender.tools.walkers.genotyper.afcalc.GeneralPloidyExactAFCalculator.computeLog10PNonRef(GeneralPloidyExactAFCalculator.java:25)
        at org.broadinstitute.hellbender.tools.walkers.genotyper.afcalc.AFCalculator.getLog10PNonRef(AFCalculator.java:33)
        at org.broadinstitute.hellbender.tools.walkers.genotyper.GenotypingEngine.calculateGenotypes(GenotypingEngine.java:255)
        at org.broadinstitute.hellbender.tools.walkers.genotyper.GenotypingEngine.calculateGenotypes(GenotypingEngine.java:210)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerGenotypingEngine.assignGenotypeLikelihoods(HaplotypeCallerGenotypingEngine.java:150)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerEngine.callRegion(HaplotypeCallerEngine.java:565)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller.apply(HaplotypeCaller.java:218)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:295)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:271)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:893)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:134)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
' returned non-zero exit status 1
```

**Comment by chapmanb** [comment]
Bennet;
Sorry about the issues and thanks for the report. For the error you're reporting here, you're asking for 32g of memory per process which should be more than enough for this many samples, although I haven't run larger pooled variant calling with GATK4 recently since we're instead using joint calling for larger samples. A couple of questions/suggestions:

- Is joint calling with gVCF intermediates an option? That should be more memory efficient approach as sample sizes increase (https://bcbio-nextgen.readthedocs.io/en/latest/contents/pipelines.html#population-calling)
- What version of GATK are you running for this?
- How are you running this? Is it distributed on a cluster or otherwise allocated with respect to resources? One potential issue might be that you're running out of memory due to overlapping allocation between processes. It would help to know what type of machines you run on (cores and memory) to understand how a 32Gb process allocates.

Hope this helps some with debugging.

**Comment by DrMcStrange** [comment]
Hi Brad,

Thanks for the suggestion - we'll give joint calling a go. This run is actually for a PhD student in the group I support, who's getting desperate for results, so I hope this solves the issue!

We're running on a single machine with 62 cores and 512Gb of RAM, which shares storage with a few other machines as part of a cluster. A somewhat idiosyncratic setup, and we'll be moving to a more standard HPC cluster soon, but that's what we've got for now. Running GATK 4.0.3.0.
