### ISSUE TITLE
IOError with small RNA pipelne

### ISSUE THREAD

**Issue by markdunning** [bcbio/bcbio-nextgen#2505]
Hi,

I am having difficulties running the small RNA pipeline but get an IOError at a certain point that I am unable to get past.

The Error message is given below
```
[2018-09-03T12:54Z] ['gff', '--sps', 'hsa', '--hairpin', '/usr/local/community/bcbio-nextgen/2017-08/data/genomes/Hsapiens/GRCh37/srnaseq/hairpin.fa', '--gtf', '/usr/local/community/bcbio-nextgen/2017-08/data/genomes/Hsapiens/GRCh37/srnaseq/mirbase.gff3', '--format', 'seqbuster', '-o', '/shared/bioinformatics_core1/Shared/wip/streets_miRNA/project-merged/work/bcbiotx/tmpzYC2At', '/shared/bioinformatics_core1/Shared/wip/streets_miRNA/project-merged/work/mirbase/Sample_T10TUC30/Sample_T10TUC30.mirna']
Traceback (most recent call last):
  File "/usr/local/community/bcbio-nextgen/2017-08/tool/bin/bcbio_nextgen.py", line 241, in <module>
    main(**kwargs)
  File "/usr/local/community/bcbio-nextgen/2017-08/tool/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 323, in smallrnaseqpipeline
    samples = run_parallel("srna_annotation", samples)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 151, in srna_annotation
    return srna.sample_annotation(*args)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/srna/sample.py", line 123, in sample_annotation
    data['config'])
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/srna/sample.py", line 261, in _mirtop
    os.path.join(out_dir, out_fn))
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/shutil.py", line 316, in move
    copy2(src, real_dst)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/shutil.py", line 144, in copy2
    copyfile(src, dst)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/shared/bioinformatics_core1/Shared/wip/streets_miRNA/project-merged/work/bcbiotx/tmpzYC2At/Sample_T10TUC30.gff'
```

It complains about `/shared/bioinformatics_core1/Shared/wip/streets_miRNA/project-merged/work/bcbiotx/tmpzYC2At/Sample_T10TUC30.gff'` not existing - which is indeed the case. However, I should have write permission in this directory so not sure why it wasn't created.

Many thanks,

Mark

**Comment by lpantano** [comment]
Hi sorry about the issue.

Can you tell me the version of bcbio_nextgen you are using and the version
of mirtop installed in the bcbio path?

You can check the latter, by doing bcbio_conda list | grep mirtop

There shouldn't be any problem in the last release version and updated
mirtop version.

Cheers

Lo

**Comment by markdunning** [comment]
Hi,

Thanks for the quick reply. The bcbio version is **1.0.9** and mirtop is **0.36a0**

```
mirtop                    0.3.6a0                  py27_0    bioconda
```

**Comment by lpantano** [comment]
Hi,

thanks for the numbers. I think that was the version that got the bug.

In the last stable version (1.1.0) with the last mirtop version (0.3.17),
this shouldn't happen. Any change you can update and make sure you have
those versions?

Using the bcbio_nextgen.py upgrade -u stable -tools should make it work.

Let me know.

**Comment by markdunning** [comment]
Thanks. I have some issues with permissions which means I haven't been able to update the pipeline yet. I'll let you know how it goes.

**Comment by markdunning** [comment]
So I used the latest version of bcbio and it seems to run fine now. Many thanks.
