### ISSUE TITLE
issue creating gemini db

### ISSUE THREAD

**Issue by matthdsm** [bcbio/bcbio-nextgen#2509]
Hi Brad,

I updated our dev bcbio deployment to the latest dev build yesterday. I tried to run our standard workflow and encountered the following issue:

```
[2018-09-13T04:00Z] multiprocessing: prep_gemini_db
Traceback (most recent call last):
  File "/home/galaxy/bcbio-dev/anaconda/bin/bcbio_nextgen.py", line 238, in <module>
    main(**kwargs)
  File "/home/galaxy/bcbio-dev/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)  
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 188, in variant2pipeline
    samples = population.prep_db_parallel(samples, run_parallel)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/variation/population.py", line 390, in prep_db_parallel
    output = parallel_fn("prep_gemini_db", to_process)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 332, in __init__
    self.results = batch()
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 352, in prep_gemini_db
    return population.prep_gemini_db(*args)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/variation/population.py", line 29, in prep_gemini_db
    build_type = _get_build_type(fnames, samples, caller)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/variation/population.py", line 333, in _get_build_type
    if vcfanno.annoated_gemini(data):
AttributeError: 'module' object has no attribute 'annoated_gemini'
```
The workflow config looks like this:

```
#bcbio-nextgen v1.1.0a
---
#include an experiment name here
fc_name: v1.1.0a_test
upload:
  dir: ../final
globals:
  analysis_regions: /ref/variant_regions/RefSeqExomeAndPanels_20171003.bed
  coverage_regions: /ref/variant_regions/RefSeqExomeAndPanels_20171003.bed
resources:
  tmp:
    dir: /tmp/bcbio
details:
  - analysis: variant2
    genome_build: hg38
    description: NA12878K12
    algorithm:
      aligner: bwa
      save_diskspace: true
      coverage_interval: regional
      coverage: coverage_regions
      mark_duplicates: true
      recalibrate: false
      realign: false
      variantcaller: gatk-haplotype
      variant_regions: analysis_regions
      jointcaller: gatk-haplotype-joint
      effects: vep
      effects_transcripts: all
      vcfanno: [eog,dbscsnv,dbnsfp]
      validate: giab-NA12878/truth_small_variants.vcf.gz
      validate_regions: analysis_regions
      tools_on:
        - vep_splicesite_annotations
        - gemini
        - coverage_perbase
    files: [../input/NA12878K12_R1.fastq.gz,../input/NA12878K12_R2.fastq.gz]
```

Any idea what went wrong?
Cheers
M

**Comment by chapmanb** [comment]
Matthias -- apologies about the issue and thank you for the heads up. This was a typo in code and I pushed a fix. Please let me know if you run into any other problems at all.
