### ISSUE TITLE
ValueError: Did not find genome build GRCh37 in bcbio installation: /home/shlee/local/share/bcbio/galaxy/tool-data/tool-data/sam_fa_indices.loc

### ISSUE THREAD

**Issue by sooheelee** [bcbio/bcbio-nextgen#2517]
I'm new to bcbio-nextgen. I've successfully installed bcbio-nextgen onto a cloud vm. When trying to run one of the example analyses from <https://bcbio-nextgen.readthedocs.io/en/latest/contents/testing.html#example-pipelines>, I get the following traceback:
```
shlee@binky:~/local/cancer-dream-syn3/work$ bcbio_nextgen.py ../config/cancer-dream-syn3.yaml -n 8
[2018-09-17T22:12Z] System YAML configuration: /home/shlee/local/share/bcbio/galaxy/bcbio_system.yaml
[2018-09-17T22:12Z] Resource requests: bwa, sambamba, samtools; memory: 3.00, 3.00, 3.00; cores: 16, 16, 16
[2018-09-17T22:12Z] Configuring 1 jobs to run, using 8 cores each with 24.1g of memory reserved for each job
[2018-09-17T22:12Z] Timing: organize samples
[2018-09-17T22:12Z] multiprocessing: organize_samples
[2018-09-17T22:12Z] Using input YAML configuration: /home/shlee/local/cancer-dream-syn3/config/cancer-dream-syn3.yaml
[2018-09-17T22:12Z] Checking sample YAML configuration: /home/shlee/local/cancer-dream-syn3/config/cancer-dream-syn3.yaml
Traceback (most recent call last):
  File "/home/shlee/local/bin/bcbio_nextgen.py", line 242, in <module>
    main(**kwargs)
  File "/home/shlee/local/bin/bcbio_nextgen.py", line 47, in main
    run_main(**kwargs)
  File "/home/shlee/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/home/shlee/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/shlee/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 126, in variant2pipeline
    [x[0]["description"] for x in samples]]])
  File "/home/shlee/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/shlee/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/home/shlee/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 983, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/shlee/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 825, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/shlee/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 782, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/shlee/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/home/shlee/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 545, in __init__
    self.results = batch()
  File "/home/shlee/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 261, in __call__
    for func, args, kwargs in self.items]
  File "/home/shlee/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/shlee/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 416, in organize_samples
    return run_info.organize(*args)
  File "/home/shlee/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 72, in organize
    item = add_reference_resources(item, remote_retriever)
  File "/home/shlee/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 166, in add_reference_resources
    data["reference"] = genome.get_refs(data["genome_build"], aligner, data["dirs"]["galaxy"], data)
  File "/home/shlee/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 229, in get_refs
    galaxy_config, data)
  File "/home/shlee/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 176, in _get_ref_from_galaxy_loc
    (genome_build, os.path.normpath(loc_file)))
ValueError: Did not find genome build GRCh37 in bcbio installation: /home/shlee/local/share/bcbio/galaxy/tool-data/tool-data/sam_fa_indices.loc
```
```
shlee@binky:~/local/cancer-dream-syn3/work$ ls /home/shlee/local/share/bcbio/galaxy/
bcbio_system.yaml  bcbio_system.yaml.bak20180414_2004
```

Would appreciate pointers to solving this. 

Also, could I confirm that if folks are using default configurations, gatk always runs with the following options for every tool?
```
jvm_opts: ["-Xms500m", "-Xmx3500m"]
```
Thanks.

**Comment by chapmanb** [comment]
Thanks for trying out bcbio and apologies about the issues. Could you provide the command you used to install bcbio? The error mesage and content of your directory looks like you might not have installed any genomes as part of the process (https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#upgrade). For the specific error here, I think doing:
```
bcbio_nextgen.py upgrade --data --genomes GRCh37 --aligners bwa
```
will give you a GRCh37 genome build you can use for the run. Hope this helps.

**Comment by sooheelee** [comment]
Thanks for the quick reply @chapmanb. My install command was:
```
python bcbio_nextgen_install.py ~/local/share/bcbio --tooldir=~/local   --genomes GRCh37 --aligners bwa --aligners bowtie2
```
By using your suggested command thusly:
```
bcbio_nextgen.py upgrade --data --genomes GRCh37 --aligners bwa --tooldir=~/local
``` 
I am seeing messages I haven't seen before that indicate the reference components are indeed installing:
```
...
  inflating: data/GRCh37.75/sequence.HSCHR6_MHC_QBL.bin
  inflating: data/GRCh37.75/sequence.HSCHR6_MHC_SSTO.bin
  inflating: data/GRCh37.75/sequence.X.bin
  inflating: data/GRCh37.75/sequence.Y.bin
  inflating: data/GRCh37.75/snpEffectPredictor.bin
bcbio-nextgen data upgrade complete.
Upgrade completed successfully.
```
The `cancer-dream-syn3` example pipeline that erred before is now running. Thank you for the solution!

**Comment by chapmanb** [comment]
Thanks for reporting back. I'm glad this fixed it, although still unsure why the initial install did not include the data. Perhaps it didn't finish successfully on the first run and the upgrade correctly finished. Either way, glad you're now processing things and thanks for helping to debug.
