### ISSUE TITLE
Cromwell run ends up with errors ("Cannot find filesystem with http")

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2527]
As the title says, with the latest updates from both bcbio and bcbio-vm:

```
[2018-09-28 17:09:44,17] [info] WorkflowStoreHeartbeatWriteActor configured to flush with batch size 10000 and process rate 2 minutes.
Uncaught error from thread [cromwell-system-akka.dispatchers.engine-dispatcher-9]: null, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for for ActorSystem[cromwell-system]
java.lang.ExceptionInInitializerError
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.$anonfun$workflowOptionsAndPathBuilders$1(MaterializeWorkflowDescriptorActor.scala:212)
        at cats.data.Validated.map(Validated.scala:194)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$materialization$MaterializeWorkflowDescriptorActor$$workflowOptionsAndPathBuilders(MaterializeWorkflowDescriptorActor.scala:211)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$1.applyOrElse(MaterializeWorkflowDescriptorActor.scala:145)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$1.applyOrElse(MaterializeWorkflowDescriptorActor.scala:141)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
        at akka.actor.FSM.processEvent(FSM.scala:665)
        at akka.actor.FSM.processEvent$(FSM.scala:662)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.akka$actor$LoggingFSM$$super$processEvent(MaterializeWorkflowDescriptorActor.scala:126)
        at akka.actor.LoggingFSM.processEvent(FSM.scala:801)
        at akka.actor.LoggingFSM.processEvent$(FSM.scala:783)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.processEvent(MaterializeWorkflowDescriptorActor.scala:126)
        at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:659)
        at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:653)
        at akka.actor.Actor.aroundReceive(Actor.scala:514)
        at akka.actor.Actor.aroundReceive$(Actor.scala:512)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.aroundReceive(MaterializeWorkflowDescriptorActor.scala:126)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
        at akka.actor.ActorCell.invoke(ActorCell.scala:496)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: common.exception.AggregatedMessageException: Failed to instantiate engine filesystem:
Cannot find a filesystem with name http in the configuration. Available filesystems: oss, gcs
```

This CWL workflow was created before the latest commit for http support was added. Perhaps related?

**Comment by chapmanb** [comment]
Luca -- sorry about this issue. We've been working on remote input support in Cromwell to help with cloud and GA4GH integration and this attempt with http needed Cromwell 35. I've updated the conda packages for Cromwell to that version and bcbio-nextgen to support it and also be back compatible with older versions. So either a full upgrade or just bcbio:
```
bcbio_conda -n bcbioenv -c conda-forge -c bioconda bcbio-nextgen
```
should resolve the issue. Sorry about the problem and please let me know if you have any other issues at all.
