### ISSUE TITLE
2bit reference not taken by BaseRecalibratorSpark

### ISSUE THREAD

**Issue by maxabruzzi** [bcbio/bcbio-nextgen#2536]
Dear support team,

I ran into an error testing the bcbio exome variant calling pipeline. Apparently the pipeline mandates the 2bit file format in this step, but BaseRecalibrator was complaining about the 2bit file is not supported as it was looking for a fasta file. Then I created a fasta file and the corresponding dict file and and the tested the step manually, it went through. So I wonder how should I change the default 2bit reference to a fasta file in this step. Or any other more appropriate solution to this? Thanks a lot!

(I tried many times so the log files contain multiple occurrences of the same error message toward the end)
[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/2474124/bcbio-nextgen-commands.log)
[bcbio-nextgen-debug.log](https://github.com/bcbio/bcbio-nextgen/files/2474125/bcbio-nextgen-debug.log)
[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/2474126/bcbio-nextgen.log)

Max Xu

**Comment by chapmanb** [comment]
Max Xu;
Apologies about the issue. GATK 4.0.10.0 changed the usage of these Spark parallelized components to use standard fasta references rather than 2bit. This has been fixed in the latest development version, if you update with:
```
bcbio_nextgen.py upgrade -u development
```
and re-run, it should correctly assign the fasta reference rather than 2bit and fix the issue. We're planning to have a new release in the next couple of days with this fix in place as well if you prefer to work from a release version. Sorry again about the issue and hope this helps to get your analysis finished.

**Comment by maxabruzzi** [comment]
Hi, thanks a lot for your quick response! I updated it to the development version and tried re-running it. Had a different error indicating missing of validation file (capture_regions/Exome-NGv3). It is probably just a simple glitch or from my own mistake, but I have not got to know enough about the syntax and how it works to figure it out. Can you please take another look? The error message is here:

[2018-10-12T23:32Z] Checking sample YAML configuration: /home/xix137/bcbioRuns/NA12878-exome-eval/config/NA12878-exome-methodcmp.yaml
Traceback (most recent call last):
  File "/home/xix137/programs/bin/bcbio_nextgen.py", line 238, in <module>
    main(**kwargs)
  File "/home/xix137/programs/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/xix137/programs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/home/xix137/programs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/xix137/programs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 126, in variant2pipeline
    [x[0]["description"] for x in samples]]])
  File "/home/xix137/programs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/xix137/programs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/home/xix137/programs/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 983, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/xix137/programs/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 825, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/xix137/programs/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 782, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/xix137/programs/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/home/xix137/programs/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 545, in __init__
    self.results = batch()
  File "/home/xix137/programs/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 261, in __call__
    for func, args, kwargs in self.items]
  File "/home/xix137/programs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/xix137/programs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 424, in organize_samples
    return run_info.organize(*args)
  File "/home/xix137/programs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 77, in organize
    item = add_reference_resources(item, remote_retriever)
  File "/home/xix137/programs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 195, in add_reference_resources
    data = _fill_validation_targets(data)
  File "/home/xix137/programs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 248, in _fill_validation_targets
    (vtarget, val))
ValueError: Configuration problem. Validation file not found for ['variant_regions']: capture_regions/Exome-NGv3

**Comment by chapmanb** [comment]
Max Xu;
Sorry about the issue. These inputs are meant as shorthand references to capture regions that bcbio installs automatically. Is it possible you're using hg38 here? It looks like right now the install only includes those for hg19 and GRCh37. If that explains the issue I can add that to the install and a upgrade of the data will copy them in so that syntax will work. Sorry again about the problems and hope I've guessed correctly at the issue.

**Comment by maxabruzzi** [comment]
Hi Brad, 

Thank you so much for your input! I did not change anything in the configuration file for this example so I believe I'm still using GRCh37. Anyways, I think it is probably something from my own mistake but I have not really spent time to look into so I could pose a better formulated question. Sorry for bothering with this. I moved on to the cancer-dream-syn3 example and had that worked without a problem. Please feel free to close this thread. I look forward to the new release. Thanks again!

Max

**Comment by chapmanb** [comment]
Max;
Thanks for helping debug and glad you had success with a different run setup. I've added these capture regions for hg38 to be complete and if folks need them in the future. Happy to help if you run into more issues. Thanks again.
