### ISSUE TITLE
Titancna cytoband hg19/GRCh37

### ISSUE THREAD

**Issue by apastore** [bcbio/bcbio-nextgen#2546]
Hi Brad, I see that Titancna now complain about cytoband with hg19/GRCh37 .

Thanks!
Alessandro 
Error in cytoband[, "chrom"] : incorrect number of dimensions

[2018-10-26T01:17Z] lt14: Optimal state path computation: Using 4 cores.
[2018-10-26T01:17Z] ls06: Optimal state path computation: Using 4 cores.
[2018-10-26T01:18Z] lt14: Writing results to /scratch/pastore/tmpXGtGGm/R_83411_16_cluster01.titan.txt, /scratch/pastore/tmpXGtGGm/R_83411_16_cluster01.segs.txt, /scratch/pastore/tmpXGtGGm/R_83411_16_cluster01.params.txt
[2018-10-26T01:18Z] lt14: titan: Saving parameters to /scratch/pastore/tmpXGtGGm/R_83411_16_cluster01.params.txt
[2018-10-26T01:18Z] lt14: $dens.bw
[2018-10-26T01:18Z] lt14: [1] 0.6061776
[2018-10-26T01:18Z] lt14: $scat
[2018-10-26T01:18Z] lt14: [1] 0.6357545
[2018-10-26T01:18Z] lt14: $S_Dbw
[2018-10-26T01:18Z] lt14: [1] 1.241932
[2018-10-26T01:18Z] ls06: Writing results to /scratch/pastore/tmpAOASF7/B12626_16_I_1_cluster01.titan.txt, /scratch/pastore/tmpAOASF7/B12626_16_I_1_cluster01.segs.txt, /scratch/pastore/tmpAOASF7/B12626_16_I_1_cluster01.params.txt
[2018-10-26T01:18Z] ls06: titan: Saving parameters to /scratch/pastore/tmpAOASF7/B12626_16_I_1_cluster01.params.txt
[2018-10-26T01:18Z] ls06: $dens.bw
[2018-10-26T01:18Z] ls06: [1] NaN
[2018-10-26T01:18Z] ls06: $scat
[2018-10-26T01:18Z] ls06: [1] Inf
[2018-10-26T01:18Z] ls06: $S_Dbw
[2018-10-26T01:18Z] ls06: [1] NaN
[2018-10-26T01:18Z] lt14: Error in cytoband[, "chrom"] : incorrect number of dimensions
[2018-10-26T01:18Z] lt14: Calls: plotIdiogram
[2018-10-26T01:18Z] lt14: In addition: Warning messages:
[2018-10-26T01:18Z] lt14: 1: In .replace_seqlevels_style(x_seqlevels, value) :
[2018-10-26T01:18Z] lt14:   found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
[2018-10-26T01:18Z] lt14: 2: In .replace_seqlevels_style(x_seqlevels, value) :
[2018-10-26T01:18Z] lt14:   found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
[2018-10-26T01:18Z] lt14: 3: In .replace_seqlevels_style(x_seqlevels, value) :
[2018-10-26T01:18Z] lt14:   found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
[2018-10-26T01:18Z] lt14: 4: In .replace_seqlevels_style(x_seqlevels, value) :
[2018-10-26T01:18Z] lt14:   found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
[2018-10-26T01:18Z] lt14: 5: In .replace_seqlevels_style(x_seqlevels, value) :
[2018-10-26T01:18Z] lt14:   found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
[2018-10-26T01:18Z] lt14: Execution halted
[2018-10-26T01:18Z] lt14: Uncaught exception occurred
Traceback (most recent call last):
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; unset R_HOME && unset R_LIBS && export PATH=/lila/data/abdelwao-lab/pastorea/bcbio/anaconda/bin:$PATH && titanCNA.R --id R_83411_16 --hetFile /lila/data/abdelwao-lab/pastorea/Project/Alternative/Alternative/work/structural/R_83411_16/titancna/batch_R_83411_16-annotated-annotated-somatic-priority-vardict-prep.csv --cnFile /lila/data/abdelwao-lab/pastorea/Project/Alternative/Alternative/work/structural/R_83411_16/titancna/R_83411_16-normalized.cn --numClusters 1 --ploidy 2 --numCores 4 --outDir /scratch/pastore/tmpXGtGGm --libdir None --chrs "c('1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','X')"  --genomeBuild hg19 --alphaK=2500 --alphaKHigh=2500
There were 11 warnings (use warnings() to see them)
Attaching package: 'Biostrings'
The following object is masked from 'package:base':
    strsplit
Running TITAN...
titan: Loading data /lila/data/abdelwao-lab/pastorea/Project/Alternative/Alternative/work/structural/R_83411_16/titancna/batch_R_83411_16-annotated-annotated-somatic-priority-vardict-prep.csv
titan: Loading GC content and mappability corrected log2 ratios...
Warning message:
In `[<-.data.table`(x, j = name, value = value) :
  Supplied 376159 items to be assigned to 377322 items of column 'chr' (recycled leaving remainder of 1163 items).
titan: Extracting read depth...
Removed Chrs: 
titan: Loading default parameters
titan: Using 4 cores.
titan: Parameter estimation
Optimal state path computation: Using 4 cores.
Writing results to /scratch/pastore/tmpXGtGGm/R_83411_16_cluster01.titan.txt, /scratch/pastore/tmpXGtGGm/R_83411_16_cluster01.segs.txt, /scratch/pastore/tmpXGtGGm/R_83411_16_cluster01.params.txt
titan: Saving parameters to /scratch/pastore/tmpXGtGGm/R_83411_16_cluster01.params.txt
$dens.bw
[1] 0.6061776
$scat
[1] 0.6357545
$S_Dbw
[1] 1.241932
Error in cytoband[, "chrom"] : incorrect number of dimensions
Calls: plotIdiogram
In addition: Warning messages:
1: In .replace_seqlevels_style(x_seqlevels, value) :
  found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
2: In .replace_seqlevels_style(x_seqlevels, value) :
  found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
3: In .replace_seqlevels_style(x_seqlevels, value) :
  found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
4: In .replace_seqlevels_style(x_seqlevels, value) :
  found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
5: In .replace_seqlevels_style(x_seqlevels, value) :
  found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
Execution halted
' returned non-zero exit status 1
[2018-10-26T01:18Z] lt14: Unexpected error
Traceback (most recent call last):
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 52, in _setup_logging
    yield config
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 436, in detect_sv
    return ipython.zip_args(apply(structural.detect_sv, *args))
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 200, in detect_sv
    for svdata in caller_fn(items):
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/titancna.py", line 35, in run
    out_dir = _run_titancna(cn_file, het_file, ploidy, num_clusters, work_dir, paired.tumor_data)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/titancna.py", line 125, in _run_titancna
    do.run(cmd.format(**locals()), "TitanCNA CNV detection: ploidy %s, cluster %s" % (ploidy, num_clusters))
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; unset R_HOME && unset R_LIBS && export PATH=/lila/data/abdelwao-lab/pastorea/bcbio/anaconda/bin:$PATH && titanCNA.R --id R_83411_16 --hetFile /lila/data/abdelwao-lab/pastorea/Project/Alternative/Alternative/work/structural/R_83411_16/titancna/batch_R_83411_16-annotated-annotated-somatic-priority-vardict-prep.csv --cnFile /lila/data/abdelwao-lab/pastorea/Project/Alternative/Alternative/work/structural/R_83411_16/titancna/R_83411_16-normalized.cn --numClusters 1 --ploidy 2 --numCores 4 --outDir /scratch/pastore/tmpXGtGGm --libdir None --chrs "c('1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','X')"  --genomeBuild hg19 --alphaK=2500 --alphaKHigh=2500
There were 11 warnings (use warnings() to see them)
Attaching package: 'Biostrings'
The following object is masked from 'package:base':
    strsplit
Running TITAN...
titan: Loading data /lila/data/abdelwao-lab/pastorea/Project/Alternative/Alternative/work/structural/R_83411_16/titancna/batch_R_83411_16-annotated-annotated-somatic-priority-vardict-prep.csv
titan: Loading GC content and mappability corrected log2 ratios...
Warning message:
In `[<-.data.table`(x, j = name, value = value) :
  Supplied 376159 items to be assigned to 377322 items of column 'chr' (recycled leaving remainder of 1163 items).
titan: Extracting read depth...
Removed Chrs: 
titan: Loading default parameters
titan: Using 4 cores.
titan: Parameter estimation
Optimal state path computation: Using 4 cores.
Writing results to /scratch/pastore/tmpXGtGGm/R_83411_16_cluster01.titan.txt, /scratch/pastore/tmpXGtGGm/R_83411_16_cluster01.segs.txt, /scratch/pastore/tmpXGtGGm/R_83411_16_cluster01.params.txt
titan: Saving parameters to /scratch/pastore/tmpXGtGGm/R_83411_16_cluster01.params.txt
$dens.bw
[1] 0.6061776
$scat
[1] 0.6357545
$S_Dbw
[1] 1.241932
Error in cytoband[, "chrom"] : incorrect number of dimensions
Calls: plotIdiogram
In addition: Warning messages:
1: In .replace_seqlevels_style(x_seqlevels, value) :
  found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
2: In .replace_seqlevels_style(x_seqlevels, value) :
  found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
3: In .replace_seqlevels_style(x_seqlevels, value) :
  found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
4: In .replace_seqlevels_style(x_seqlevels, value) :
  found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
5: In .replace_seqlevels_style(x_seqlevels, value) :
  found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
Execution halted
' returned non-zero exit status 1
[2018-10-26T01:18Z] ls06: Error in cytoband[, "chrom"] : incorrect number of dimensions
[2018-10-26T01:18Z] ls06: Calls: plotIdiogram
[2018-10-26T01:18Z] ls06: In addition: Warning messages:
[2018-10-26T01:18Z] ls06: 1: In .replace_seqlevels_style(x_seqlevels, value) :
[2018-10-26T01:18Z] ls06:   found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
[2018-10-26T01:18Z] ls06: 2: In .replace_seqlevels_style(x_seqlevels, value) :
[2018-10-26T01:18Z] ls06:   found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
[2018-10-26T01:18Z] ls06: 3: In .replace_seqlevels_style(x_seqlevels, value) :
[2018-10-26T01:18Z] ls06:   found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
[2018-10-26T01:18Z] ls06: 4: In .replace_seqlevels_style(x_seqlevels, value) :
[2018-10-26T01:18Z] ls06:   found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
[2018-10-26T01:18Z] ls06: 5: In .replace_seqlevels_style(x_seqlevels, value) :
[2018-10-26T01:18Z] ls06:   found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
[2018-10-26T01:18Z] ls06: Execution halted
[2018-10-26T01:18Z] ls06: Uncaught exception occurred
Traceback (most recent call last):
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; unset R_HOME && unset R_LIBS && export PATH=/lila/data/abdelwao-lab/pastorea/bcbio/anaconda/bin:$PATH && titanCNA.R --id B12626_16_I_1 --hetFile /lila/data/abdelwao-lab/pastorea/Project/Alternative/Alternative/work/structural/B12626_16_I_1/titancna/batch_B12626_16_I_1-annotated-annotated-somatic-priority-vardict-prep.csv --cnFile /lila/data/abdelwao-lab/pastorea/Project/Alternative/Alternative/work/structural/B12626_16_I_1/titancna/B12626_16_I_1-normalized.cn --numClusters 1 --ploidy 2 --numCores 4 --outDir /scratch/pastore/tmpAOASF7 --libdir None --chrs "c('1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','X')"  --genomeBuild hg19 --alphaK=2500 --alphaKHigh=2500
There were 11 warnings (use warnings() to see them)
Attaching package: 'Biostrings'
The following object is masked from 'package:base':
    strsplit
Running TITAN...
titan: Loading data /lila/data/abdelwao-lab/pastorea/Project/Alternative/Alternative/work/structural/B12626_16_I_1/titancna/batch_B12626_16_I_1-annotated-annotated-somatic-priority-vardict-prep.csv
titan: Loading GC content and mappability corrected log2 ratios...
Warning message:
In `[<-.data.table`(x, j = name, value = value) :
  Supplied 189666 items to be assigned to 190163 items of column 'chr' (recycled leaving remainder of 497 items).
titan: Extracting read depth...
Removed Chrs: 
titan: Loading default parameters
titan: Using 4 cores.
titan: Parameter estimation
Optimal state path computation: Using 4 cores.
Writing results to /scratch/pastore/tmpAOASF7/B12626_16_I_1_cluster01.titan.txt, /scratch/pastore/tmpAOASF7/B12626_16_I_1_cluster01.segs.txt, /scratch/pastore/tmpAOASF7/B12626_16_I_1_cluster01.params.txt
titan: Saving parameters to /scratch/pastore/tmpAOASF7/B12626_16_I_1_cluster01.params.txt
$dens.bw
[1] NaN
$scat
[1] Inf
$S_Dbw
[1] NaN
Error in cytoband[, "chrom"] : incorrect number of dimensions
Calls: plotIdiogram
In addition: Warning messages:
1: In .replace_seqlevels_style(x_seqlevels, value) :
  found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
2: In .replace_seqlevels_style(x_seqlevels, value) :
  found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
3: In .replace_seqlevels_style(x_seqlevels, value) :
  found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
4: In .replace_seqlevels_style(x_seqlevels, value) :
  found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
5: In .replace_seqlevels_style(x_seqlevels, value) :
  found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
Execution halted
' returned non-zero exit status 1
[2018-10-26T01:18Z] ls06: Unexpected error
Traceback (most recent call last):
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 52, in _setup_logging
    yield config
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 436, in detect_sv
    return ipython.zip_args(apply(structural.detect_sv, *args))
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 200, in detect_sv
    for svdata in caller_fn(items):
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/titancna.py", line 35, in run
    out_dir = _run_titancna(cn_file, het_file, ploidy, num_clusters, work_dir, paired.tumor_data)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/titancna.py", line 125, in _run_titancna
    do.run(cmd.format(**locals()), "TitanCNA CNV detection: ploidy %s, cluster %s" % (ploidy, num_clusters))
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; unset R_HOME && unset R_LIBS && export PATH=/lila/data/abdelwao-lab/pastorea/bcbio/anaconda/bin:$PATH && titanCNA.R --id B12626_16_I_1 --hetFile /lila/data/abdelwao-lab/pastorea/Project/Alternative/Alternative/work/structural/B12626_16_I_1/titancna/batch_B12626_16_I_1-annotated-annotated-somatic-priority-vardict-prep.csv --cnFile /lila/data/abdelwao-lab/pastorea/Project/Alternative/Alternative/work/structural/B12626_16_I_1/titancna/B12626_16_I_1-normalized.cn --numClusters 1 --ploidy 2 --numCores 4 --outDir /scratch/pastore/tmpAOASF7 --libdir None --chrs "c('1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','X')"  --genomeBuild hg19 --alphaK=2500 --alphaKHigh=2500
There were 11 warnings (use warnings() to see them)
Attaching package: 'Biostrings'
The following object is masked from 'package:base':
    strsplit
Running TITAN...
titan: Loading data /lila/data/abdelwao-lab/pastorea/Project/Alternative/Alternative/work/structural/B12626_16_I_1/titancna/batch_B12626_16_I_1-annotated-annotated-somatic-priority-vardict-prep.csv
titan: Loading GC content and mappability corrected log2 ratios...
Warning message:
In `[<-.data.table`(x, j = name, value = value) :
  Supplied 189666 items to be assigned to 190163 items of column 'chr' (recycled leaving remainder of 497 items).
titan: Extracting read depth...
Removed Chrs: 
titan: Loading default parameters
titan: Using 4 cores.
titan: Parameter estimation
Optimal state path computation: Using 4 cores.
Writing results to /scratch/pastore/tmpAOASF7/B12626_16_I_1_cluster01.titan.txt, /scratch/pastore/tmpAOASF7/B12626_16_I_1_cluster01.segs.txt, /scratch/pastore/tmpAOASF7/B12626_16_I_1_cluster01.params.txt
titan: Saving parameters to /scratch/pastore/tmpAOASF7/B12626_16_I_1_cluster01.params.txt
$dens.bw
[1] NaN
$scat
[1] Inf
$S_Dbw
[1] NaN
Error in cytoband[, "chrom"] : incorrect number of dimensions
Calls: plotIdiogram
In addition: Warning messages:
1: In .replace_seqlevels_style(x_seqlevels, value) :
  found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
2: In .replace_seqlevels_style(x_seqlevels, value) :
  found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
3: In .replace_seqlevels_style(x_seqlevels, value) :
  found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
4: In .replace_seqlevels_style(x_seqlevels, value) :
  found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
5: In .replace_seqlevels_style(x_seqlevels, value) :
  found more than one best sequence renaming map compatible with seqname style "NCBI" for this object, using the first one
Execution halted
' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Alessandro;
Sorry about this issue. Are you running this with hg19 (chr1 UCSC style chromosomes) or GRCh37 (1 NCBI style chromosomes)? I'm guessing GRCh37 since the command line is missing the `--genomeStyle UCSC` which we'd expect for hg19.

I've tested the new version, which generalizes to support hg38, with hg19 and hg38 but not yet GRCh37 so this may be something we're missing on the command line. I'd need to loop in @gavinha to see if we're doing something wrong here. We have a titanCNA.R command line with:
```
--chrs "c('1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','X')" --genomeBuild hg19
```
Is there anything else we're missing for NCBI coordinates? Thanks for any pointers; dealing with the different naming conventions for chromosomes is frustrating so we've stuck with only chr-style for build 38 but unfortunately have both for build 37.

**Comment by roryk** [comment]
Thanks, we haven't had any other issues crop up because of this, so this might have been a one-off problem. Please let us know if you are still running in the problem, thank you!
