### ISSUE TITLE
peddy failling again in bcbio dev version 

### ISSUE THREAD

**Issue by apastore** [bcbio/bcbio-nextgen#2547]
2

018-10-26 20:31:39 lt16 peddy.pca[71745] INFO loaded and subsetted thousand-genomes genotypes (shape: (2504, 6)) in 0.5 seconds
2018-10-26 20:31:42 lt16 peddy.pca[71745] INFO ran randomized PCA on thousand-genomes samples at 6 sites in 2.8 seconds
/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/sklearn/decomposition/base.py:133: RuntimeWarning: divide by zero encountered in divide
  X_transformed /= np.sqrt(self.explained_variance_)
Traceback (most recent call last):
  File "/home/pastore/data/bcbio/anaconda/bin/peddy", line 11, in <module>
    load_entry_point('peddy==0.4.2', 'console_scripts', 'peddy')()
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/peddy/cli.py", line 207, in peddy
    in ("ped_check", "het_check", "sex_check")]):
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/peddy/cli.py", line 43, in run
    prefix=prefix, **kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/peddy/peddy.py", line 878, in het_check
    pca_df, background_pca_df = pca(pca_plot, sitesfile, gt_types, sites)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/peddy/pca.py", line 81, in pca
    pred = clf.predict(genotype_matrix)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/sklearn/utils/metaestimators.py", line 115, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/sklearn/pipeline.py", line 307, in predict
    return self.steps[-1][-1].predict(Xt)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/sklearn/svm/base.py", line 548, in predict
    y = super(BaseSVC, self).predict(X)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/sklearn/svm/base.py", line 308, in predict
    X = self._validate_for_predict(X)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/sklearn/svm/base.py", line 439, in _validate_for_predict
    X = check_array(X, accept_sparse='csr', dtype=np.float64, order="C")
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py", line 453, in check_array
    _assert_all_finite(array)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py", line 44, in _assert_all_finite
    " or a value too large for %r." % X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

[2018-10-27T00:31Z] lt16: Unexpected error
Traceback (most recent call last):
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 52, in _setup_logging
    yield config
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 177, in run_peddy
    return ipython.zip_args(apply(peddy.run_peddy, *args))
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/peddy.py", line 99, in run_peddy
    do.run(cmd.format(**locals()), message.format(**locals()))
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /home/pastore/data/bcbio/anaconda/bin/peddy -p 4  --plot --prefix /scratch/pastore/tmpWN4MhP/batch_FL_51608-P5-B5 /lila/data/abdelwao-lab/pastorea/Project/GALIUM/GALIUM/work/qc/batch_FL_51608-P5-B5/peddy/batch_FL_51608-P5-B5-annotated-germline.vcf.gz /lila/data/abdelwao-lab/pastorea/Project/GALIUM/GALIUM/work/qc/batch_FL_51608-P5-B5/peddy/batch_FL_51608-P5-B5-annotated-germline.ped 2> /scratch/pastore/tmpWN4MhP/run-stderr.log
' returned non-zero exit status 1

**Comment by apastore** [comment]
Thanks a lot for your help ! Yes ! is a super small gene panel only 100 genes

**Comment by chapmanb** [comment]
Alessandro and Brent;
Thanks for confirming. It sounds like catching the error and skipping here is the right thing. It's hard to say what will and won't work with peddy beforehand since it depends on overlaps with the sites, but if we error our in this way we're better off just cleanly skipping. Hope the workaround in bcbio gets your analysis finished and thanks again for the help debugging
