### ISSUE TITLE
Bcbio.  Ensemble intersection calling: batch1. Failed to create symbolic link

### ISSUE THREAD

**Issue by Anniestasy** [bcbio/bcbio-nextgen#2549]
I was running Variant calling for normal/tumor samples using bcbio with 4 variant callers.
If I understood right, there is some problem with one of the last steps, merging vcf files:

[2018-10-27T18:52Z] Ensemble consensus calls for batch1: mutect2,freebayes,vardict,varscan
[2018-10-27T18:52Z] Ensemble intersection calling: batch1
[2018-10-27T18:52Z] 2018-10-27 20:52:38 ws1-ThinkStation-XXXX INFO [bcbio.run.itx] - ln: failed to create symbolic link '/home/477267/mnt/000000-My_Documents/VM-home/bcbio-project/config/bcbiotx/tmpoJ7i3C/batch1-ensemble-work/txtmp6863220941794675262/mutect2-batch1-vepeffects-annotated-noeff-nomultiallelic-nofilter.vcf.gz': Operation not supported
[2018-10-27T18:52Z] 2018-10-27 20:52:38 ws1-ThinkStation-XXXX ERROR [bcbio.run.itx] -
[2018-10-27T18:52Z] java.lang.Exception: Shell command failed: ln -s /home/477267/mnt/000000-My_Documents/VM-home/bcbio-project/config/bcbiotx/tmpoJ7i3C/batch1-ensemble-work/mutect2-batch1-vepeffects-annotated-noeff-nomultiallelic-nofilter.vcf.gz /home/477267/mnt/000000-My_Documents/VM-home/bcbio-project/config/bcbiotx/tmpoJ7i3C/batch1-ensemble-work/txtmp6863220941794675262/mutect2-batch1-vepeffects-annotated-noeff-nomultiallelic-nofilter.vcf.gz
[2018-10-27T18:52Z]                      ln: failed to create symbolic link '/home/477267/mnt/000000-My_Documents/VM-home/bcbio-project/config/bcbiotx/tmpoJ7i3C/batch1-ensemble-work/txtmp6863220941794675262/mutect2-batch1-vepeffects-annotated-noeff-nomultiallelic-nofilter.vcf.gz': Operation not supported
[2018-10-27T18:52Z]                             bcbio.run.itx/check-run        itx.clj:  168
[2018-10-27T18:52Z]                             bcbio.run.itx/check-run        itx.clj:  172
[2018-10-27T18:52Z]    bcbio.variation.ensemble.prep/tabix-index-vcf/fn       prep.clj:   32
[2018-10-27T18:52Z]       bcbio.variation.ensemble.prep/tabix-index-vcf       prep.clj:   28
[2018-10-27T18:52Z]       bcbio.variation.ensemble.prep/bgzip-index-vcf       prep.clj:   51
[2018-10-27T18:52Z]                          clojure.lang.RestFn.invoke    RestFn.java:  410
[2018-10-27T18:52Z] bcbio.variation.ensemble.intersect/maybe-nofiltered  intersect.clj:   71
[2018-10-27T18:52Z] bcbio.variation.ensemble.intersect/ensemble-vcfs/fn  intersect.clj:   82
[2018-10-27T18:52Z]                                 clojure.core/map/fn       core.clj: 2622
[2018-10-27T18:52Z]                           clojure.lang.LazySeq.sval   LazySeq.java:   40
[2018-10-27T18:52Z]                            clojure.lang.LazySeq.seq   LazySeq.java:   49
[2018-10-27T18:52Z]                          clojure.lang.LazySeq.first   LazySeq.java:   71
[2018-10-27T18:52Z]                               clojure.lang.RT.first        RT.java:  653
[2018-10-27T18:52Z]                                  clojure.core/first       core.clj:   55
[2018-10-27T18:52Z] bcbio.variation.ensemble.vcfsample/consistent-order  vcfsample.clj:   60
[2018-10-27T18:52Z]    bcbio.variation.ensemble.intersect/ensemble-vcfs  intersect.clj:   82
[2018-10-27T18:52Z]            bcbio.variation.ensemble.intersect/-main  intersect.clj:  140
[2018-10-27T18:52Z]                         clojure.lang.RestFn.applyTo    RestFn.java:  137
[2018-10-27T18:52Z]                                  clojure.core/apply       core.clj:  630
[2018-10-27T18:52Z]                bcbio.variation.recall.main/-main/fn       main.clj:   34
[2018-10-27T18:52Z]                   bcbio.variation.recall.main/-main       main.clj:   33
[2018-10-27T18:52Z]                         clojure.lang.RestFn.applyTo    RestFn.java:  137
[2018-10-27T18:52Z]                    bcbio.variation.recall.main.main               :
[2018-10-27T18:52Z] 2018-10-27 20:52:38 ws1-ThinkStation-XXXX ERROR [bcbio.variation.recall.main] -
[2018-10-27T18:52Z] java.lang.Exception: Shell command failed: ln -s /home/477267/mnt/000000-My_Documents/VM-home/bcbio-project/config/bcbiotx/tmpoJ7i3C/batch1-ensemble-work/mutect2-batch1-vepeffects-annotated-noeff-nomultiallelic-nofilter.vcf.gz /home/477267/mnt/000000-My_Documents/VM-home/bcbio-project/config/bcbiotx/tmpoJ7i3C/batch1-ensemble-work/txtmp6863220941794675262/mutect2-batch1-vepeffects-annotated-noeff-nomultiallelic-nofilter.vcf.gz
[2018-10-27T18:52Z]                      ln: failed to create symbolic link '/home/477267/mnt/000000-My_Documents/VM-home/bcbio-project/config/bcbiotx/tmpoJ7i3C/batch1-ensemble-work/txtmp6863220941794675262/mutect2-batch1-vepeffects-annotated-noeff-nomultiallelic-nofilter.vcf.gz': Operation not supported
[2018-10-27T18:52Z]                             bcbio.run.itx/check-run        itx.clj:  168
[2018-10-27T18:52Z]                             bcbio.run.itx/check-run        itx.clj:  172
[2018-10-27T18:52Z]    bcbio.variation.ensemble.prep/tabix-index-vcf/fn       prep.clj:   32
[2018-10-27T18:52Z]       bcbio.variation.ensemble.prep/tabix-index-vcf       prep.clj:   28
[2018-10-27T18:52Z]       bcbio.variation.ensemble.prep/bgzip-index-vcf       prep.clj:   51
[2018-10-27T18:52Z]                          clojure.lang.RestFn.invoke    RestFn.java:  410
[2018-10-27T18:52Z] bcbio.variation.ensemble.intersect/maybe-nofiltered  intersect.clj:   71
[2018-10-27T18:52Z] bcbio.variation.ensemble.intersect/ensemble-vcfs/fn  intersect.clj:   82
[2018-10-27T18:52Z]                                 clojure.core/map/fn       core.clj: 2622
[2018-10-27T18:52Z]                           clojure.lang.LazySeq.sval   LazySeq.java:   40
[2018-10-27T18:52Z]                            clojure.lang.LazySeq.seq   LazySeq.java:   49
[2018-10-27T18:52Z]                          clojure.lang.LazySeq.first   LazySeq.java:   71
[2018-10-27T18:52Z]                               clojure.lang.RT.first        RT.java:  653
[2018-10-27T18:52Z]                                  clojure.core/first       core.clj:   55
[2018-10-27T18:52Z] bcbio.variation.ensemble.vcfsample/consistent-order  vcfsample.clj:   60
[2018-10-27T18:52Z]    bcbio.variation.ensemble.intersect/ensemble-vcfs  intersect.clj:   82
[2018-10-27T18:52Z]            bcbio.variation.ensemble.intersect/-main  intersect.clj:  140
[2018-10-27T18:52Z]                         clojure.lang.RestFn.applyTo    RestFn.java:  137
[2018-10-27T18:52Z]                                  clojure.core/apply       core.clj:  630
[2018-10-27T18:52Z]                bcbio.variation.recall.main/-main/fn       main.clj:   34
[2018-10-27T18:52Z]                   bcbio.variation.recall.main/-main       main.clj:   33
[2018-10-27T18:52Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/media/hdc/opt/install/bin/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/media/hdc/opt/install/bin/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; export PATH=/media/hdc/opt/install/bin/bcbio/anaconda/bin:$PATH &&  /media/hdc/opt/install/bin/bcbio/anaconda/bin/bcbio-variation-recall ensemble --cores=1 --numpass 2 --names mutect2,freebayes,vardict,varscan --nofiltered /home/477267/mnt/000000-My_Documents/VM-home/bcbio-project/config/bcbiotx/tmpoJ7i3C/batch1-ensemble.vcf.gz /media/hdc/opt/install/bin/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa /home/477267/mnt/000000-My_Documents/VM-home/bcbio-project/config/mutect2/batch1-vepeffects-annotated-noeff-nomultiallelic.vcf.gz /home/477267/mnt/000000-My_Documents/VM-home/bcbio-project/config/freebayes/batch1-vepeffects-annotated-filter-noeff-nomultiallelic.vcf.gz /home/477267/mnt/000000-My_Documents/VM-home/bcbio-project/config/vardict/batch1-vepeffects-annotated-noeff-nomultiallelic.vcf.gz /home/477267/mnt/000000-My_Documents/VM-home/bcbio-project/config/varscan/batch1-vepeffects-annotated-noeff-nomultiallelic.vcf.gz
2018-10-27 20:52:38 ws1-ThinkStation-XXXX INFO [bcbio.run.itx] - ln: failed to create symbolic link '/home/477267/mnt/000000-My_Documents/VM-home/bcbio-project/config/bcbiotx/tmpoJ7i3C/batch1-ensemble-work/txtmp6863220941794675262/mutect2-batch1-vepeffects-annotated-noeff-nomultiallelic-nofilter.vcf.gz': Operation not supported
2018-10-27 20:52:38 ws1-ThinkStation-XXXX ERROR [bcbio.run.itx] 
..........etc.

**Comment by chapmanb** [comment]
Thanks much for the detailed report and apologies about the issue. It looks like the problem is that the type of filesystem you're running on have a restriction on making symbolic links:
```
 ln: failed to create symbolic link '/home/477267/mnt/000000-My_Documents/VM-home/bcbio-project/config/bcbiotx/tmpoJ7i3C/batch1-ensemble-work/txtmp6863220941794675262/mutect2-batch1-vepeffects-annotated-noeff-nomultiallelic-nofilter.vcf.gz': Operation not supported
```
It looks like you might be running in a virtual machine or other non-standard environment but it's hard to tell. What type of filesystem is your work directory?
```
/home/477267/mnt/000000-My_Documents/VM-home/bcbio-project/config
```
If you're not able to adjust where you're running you could try setting the temporary directory to someplace local, rather than on this problem filesystem to work around the issue:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#temporary-directory

Hope this helps.

**Comment by Anniestasy** [comment]
There was problem of CIFS protocol that my colleague used for mounting the storage. Now we fixed it.
Thank you for your help!
Now I have one more question:
Before the bcbio run, I convert bam files to fastq with "bedtools bamtofastq", and I'm thinking, that is why I have this error now. But I could be wrong, and how is it possible to fix it?
[2018-10-30T10:06Z] Align unmapped reads to viral genome
[2018-10-30T10:06Z] [M::bwa_idx_load_from_disk] read 0 ALT contigs
[2018-10-30T10:06Z] Invalid alignment: Query name contains illegal symbols
[2018-10-30T10:06Z] /media/hdc/opt/install/bin/bcbio/anaconda/share/biobambam-2.0.87-1/bin/../lib/libmaus2.so.2(libmaus2::util::StackTrace::StackTrace()+0x4c)[0x7fe8f5ec2f8c]
[2018-10-30T10:06Z] bamtofastq(libmaus2::exception::LibMausException::LibMausException()+0x20)[0x41a680]
[2018-10-30T10:06Z] bamtofastq()[0x44213c]
[2018-10-30T10:06Z] bamtofastq()[0x45a9af]
[2018-10-30T10:06Z] bamtofastq()[0x4158b4]
[2018-10-30T10:06Z] bamtofastq()[0x4169c8]
[2018-10-30T10:06Z] bamtofastq()[0x41210a]
[2018-10-30T10:06Z] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7fe8f27c0b97]
[2018-10-30T10:06Z] bamtofastq()[0x412912]
[2018-10-30T10:06Z] [main] Version: 0.7.17-r1188
[2018-10-30T10:06Z] [main] CMD: bwa mem -t 1 /media/hdc/opt/install/bin/bcbio/genomes/Hsapiens/GRCh37/viral/gdc-viral.fa -
[2018-10-30T10:06Z] [main] Real time: 0.473 sec; CPU: 0.005 sec
[2018-10-30T10:06Z] [V] Reading alignments from source.
[2018-10-30T10:06Z] [V] read 0 alignments
[2018-10-30T10:06Z] [V] producing sorted output
[2018-10-30T10:06Z] [V] wrote 0 alignments
[2018-10-30T10:06Z] [E::bgzf_flush] File write failed (wrong size)
[2018-10-30T10:06Z] samtools view: writing to standard output failed: Broken pipe
[2018-10-30T10:06Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/media/hdc/opt/install/bin/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/media/hdc/opt/install/bin/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; samtools view -u -f 4 /home/477267/mnt/000000-My_Documents/VM-home/bcbio-project/config/align/tumor/tumor-sort.bam | bamtofastq collate=0 | bwa mem -t 1 /media/hdc/opt/install/bin/bcbio/genomes/Hsapiens/GRCh37/viral/gdc-viral.fa - | bamsort tmpfile=/home/477267/mnt/000000-My_Documents/VM-home/bcbio-project/config/bcbiotx/tmpgZEYKe/tumor-gdc-viral-tmp inputthreads=1 outputthreads=1 inputformat=sam index=1 indexfilename=/home/477267/mnt/000000-My_Documents/VM-home/bcbio-project/config/bcbiotx/tmpgZEYKe/tumor-gdc-viral.bam.bai O=/home/477267/mnt/000000-My_Documents/VM-home/bcbio-project/config/bcbiotx/tmpgZEYKe/tumor-gdc-viral.bam
[M::bwa_idx_load_from_disk] read 0 ALT contigs
Invalid alignment: Query name contains illegal symbols
/media/hdc/opt/install/bin/bcbio/anaconda/share/biobambam-2.0.87-1/bin/../lib/libmaus2.so.2(libmaus2::util::StackTrace::StackTrace()+0x4c)[0x7fe8f5ec2f8c]
bamtofastq(libmaus2::exception::LibMausException::LibMausException()+0x20)[0x41a680]
bamtofastq()[0x44213c]
bamtofastq()[0x45a9af]
bamtofastq()[0x4158b4]
bamtofastq()[0x4169c8]
bamtofastq()[0x41210a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7fe8f27c0b97]
bamtofastq()[0x412912]
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -t 1 /media/hdc/opt/install/bin/bcbio/genomes/Hsapiens/GRCh37/viral/gdc-viral.fa -
[main] Real time: 0.473 sec; CPU: 0.005 sec
[V] Reading alignments from source.
[V] read 0 alignments
[V] producing sorted output
[V] wrote 0 alignments
[E::bgzf_flush] File write failed (wrong size)
samtools view: writing to standard output failed: Broken pipe
[E::bgzf_close] File write failed
samtools view: error closing standard output: -1
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/media/hdc/opt/install/dir/bin/bcbio_nextgen.py", line 242, in <module>
    main(**kwargs)
  File "/media/hdc/opt/install/dir/bin/bcbio_nextgen.py", line 47, in main
    run_main(**kwargs)
  File "/media/hdc/opt/install/bin/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/media/hdc/opt/install/bin/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/media/hdc/opt/install/bin/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 192, in variant2pipeline
    samples = qcsummary.generate_parallel(samples, run_parallel)
  File "/media/hdc/opt/install/bin/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 39, in generate_parallel
    qced = run_parallel("pipeline_summary", to_analyze)
  File "/media/hdc/opt/install/bin/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/media/hdc/opt/install/bin/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/media/hdc/opt/install/bin/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 986, in __call__
    while self.dispatch_one_batch(iterator):
  File "/media/hdc/opt/install/bin/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 825, in dispatch_one_batch
    self._dispatch(tasks)
  File "/media/hdc/opt/install/bin/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 782, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/media/hdc/opt/install/bin/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/media/hdc/opt/install/bin/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 545, in __init__
    self.results = batch()
  File "/media/hdc/opt/install/bin/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 261, in __call__
    for func, args, kwargs in self.items]
  File "/media/hdc/opt/install/bin/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "/media/hdc/opt/install/bin/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 204, in pipeline_summary
    return qcsummary.pipeline_summary(*args)
  File "/media/hdc/opt/install/bin/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 70, in pipeline_summary
    data["summary"] = _run_qc_tools(work_bam, work_data)
  File "/media/hdc/opt/install/bin/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 161, in _run_qc_tools
    out = qc_fn(bam_file, data, cur_qc_dir)
  File "/media/hdc/opt/install/bin/bcbio/anaconda/lib/python2.7/site-packages/bcbio/qc/viral.py", line 42, in run
    do.run(cmd.format(**locals()), "Align unmapped reads to viral genome")
  File "/media/hdc/opt/install/bin/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/media/hdc/opt/install/bin/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; samtools view -u -f 4 /home/477267/mnt/000000-My_Documents/VM-home/bcbio-project/config/align/tumor/tumor-sort.bam | bamtofastq collate=0 | bwa mem -t 1 /media/hdc/opt/install/bin/bcbio/genomes/Hsapiens/GRCh37/viral/gdc-viral.fa - | bamsort tmpfile=/home/477267/mnt/000000-My_Documents/VM-home/bcbio-project/config/bcbiotx/tmpgZEYKe/tumor-gdc-viral-tmp inputthreads=1 outputthreads=1 inputformat=sam index=1 indexfilename=/home/477267/mnt/000000-My_Documents/VM-home/bcbio-project/config/bcbiotx/tmpgZEYKe/tumor-gdc-viral.bam.bai O=/home/477267/mnt/000000-My_Documents/VM-home/bcbio-project/config/bcbiotx/tmpgZEYKe/tumor-gdc-viral.bam
[M::bwa_idx_load_from_disk] read 0 ALT contigs
Invalid alignment: Query name contains illegal symbols
/media/hdc/opt/install/bin/bcbio/anaconda/share/biobambam-2.0.87-1/bin/../lib/libmaus2.so.2(libmaus2::util::StackTrace::StackTrace()+0x4c)[0x7fe8f5ec2f8c]
bamtofastq(libmaus2::exception::LibMausException::LibMausException()+0x20)[0x41a680]
bamtofastq()[0x44213c]
bamtofastq()[0x45a9af]
bamtofastq()[0x4158b4]
bamtofastq()[0x4169c8]
bamtofastq()[0x41210a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7fe8f27c0b97]
bamtofastq()[0x412912]
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -t 1 /media/hdc/opt/install/bin/bcbio/genomes/Hsapiens/GRCh37/viral/gdc-viral.fa -
[main] Real time: 0.473 sec; CPU: 0.005 sec
[V] Reading alignments from source.
[V] read 0 alignments
[V] producing sorted output
[V] wrote 0 alignments
[E::bgzf_flush] File write failed (wrong size)
samtools view: writing to standard output failed: Broken pipe
[E::bgzf_close] File write failed
samtools view: error closing standard output: -1
' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Thanks for following up and glad you resolved the initial problem. For the new error, it looks like the relevant issue is that there is something in the original read names that makes bwa unhappy:
```
[2018-10-30T10:06Z] Invalid alignment: Query name contains illegal symbols
```
The confusing thing to me is that the input to this step is coming from a BAM that has already been aligned with bcbio so I'm not sure why it would have failed at the initial step. My guess is that this might be a temporary error streaming from your filesystem and restarting would get the analysis finished. Does it fail consistently with this issue if you re-run?

If so and you suspect issues with the initial inputs, bcbio can take BAM files as inputs and will handle converting into fastq and realigning, so you don't need to do any preparation up front.

Sorry to not know exactly what is going on but I hope this helps.

**Comment by Anniestasy** [comment]
Thank you for your help and fast response!
I think. for now I will close this issue :)
