### ISSUE TITLE
salmon/wasabi error due to R package library

### ISSUE THREAD

**Issue by mjsteinbaugh** [bcbio/bcbio-nextgen#2551]
@roryk I seem to have hit upon an issue with salmon/wasabi if a user has a personal R package library defined. I'm running into this error on O2 with the `/n/app/bcbio/tools/bin/bcbio_nextgen.py` install, and I can reproduce the issue on a different VM using the stable v1.1 bcbio release. The RNA-seq pipeline using salmon as an expression caller will error if `R_LIBS_USER` is defined in `~/.Renviron`. For example:

```
R_LIBS_USER="~/R/library/3.5"
```

This causes a conflict with the internal bcbio R package library, for example at `/n/app/bcbio/dev/anaconda/lib/R/library` on O2.

If you disable `R_LIBS_USER`, then salmon will run correctly, and `prepare_fish_for_sleuth` won't error out due to a package library mismatch. I'm wondering if there's a way to better isolate the bcbio R environment from a user's R environment, so we can avoid this issue.

Here's a representative error message:

```
[2018-10-28T08:00Z] compute-a-16-83.o2.rc.hms.harvard.edu: Converting Sailfish to Sleuth format.
[2018-10-28T08:00Z] compute-a-16-83.o2.rc.hms.harvard.edu: Error: package or namespace load failed for 'w
asabi' in dyn.load(file, DLLpath = DLLpath, ...):
[2018-10-28T08:00Z] compute-a-16-83.o2.rc.hms.harvard.edu:  unable to load shared object '/home/XXX/R/l
ibrary/x86_64-pc-linux-gnu/3.5/bioc-3.7-release-20181024/data.table/libs/datatable.so':
[2018-10-28T08:00Z] compute-a-16-83.o2.rc.hms.harvard.edu:   /home/XXX/R/library/x86_64-pc-linux-gnu/3.
5/bioc-3.7-release-20181024/data.table/libs/datatable.so: undefined symbol: LENGTH_EX
[2018-10-28T08:00Z] compute-a-16-83.o2.rc.hms.harvard.edu: Execution halted
[2018-10-28T08:00Z] compute-a-16-83.o2.rc.hms.harvard.edu: Uncaught exception occurred
Traceback (most recent call last):
  File "/n/app/bcbio/dev/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/n/app/bcbio/dev/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_r
un
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /n/app/bcbio/dev/anaconda/bin/Rscript -e 'library("wasabi")
; prepare_fish_for_sleuth(c("/n/data1/XXX/work/bcbiotx/tmpeSHZQE/quant"))'
Error: package or namespace load failed for 'wasabi' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/XXX/R/library/x86_64-pc-linux-gnu/3.5/bioc-3.7-release-20181024/da
ta.table/libs/datatable.so':
  /home/XXX/R/library/x86_64-pc-linux-gnu/3.5/bioc-3.7-release-20181024/data.table/libs/datatable.so: u
ndefined symbol: LENGTH_EX
Execution halted
' returned non-zero exit status 1
[2018-10-28T08:00Z] compute-a-16-83.o2.rc.hms.harvard.edu: Unexpected error
Traceback (most recent call last):
  File "/n/app/bcbio/dev/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 52, in _setup_logging
    yield config
  File "/n/app/bcbio/dev/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 219, in run_salmon_reads
    return ipython.zip_args(apply(salmon.run_salmon_reads, *args))
  File "/n/app/bcbio/dev/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/salmon.py", line 48, in run_salmon_reads
    out_file = salmon_quant_reads(fq1, fq2, salmon_dir, gtf_file, fasta_file, data)
  File "/n/app/bcbio/dev/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/salmon.py", line 89, in salmon_quant_reads
    sailfish.sleuthify_sailfish(tx_out_dir)
  File "/n/app/bcbio/dev/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/sailfish.py", line 76, in sleuthify_sailfish
    do.run(cmd.format(**locals()), "Converting Sailfish to Sleuth format.")
  File "/n/app/bcbio/dev/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/n/app/bcbio/dev/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /n/app/bcbio/dev/anaconda/bin/Rscript -e 'library("wasabi"); prepare_fish_for_sleuth(c("/n/data1/cores/bcbio/PIs/nathan_shapiro/appendicitis_rnaseq/grant_samples/bcbio/2018-10-27/work/bcbiotx/tmpeSHZQE/quant"))'
Error: package or namespace load failed for 'wasabi' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/XXX/R/library/x86_64-pc-linux-gnu/3.5/bioc-3.7-release-20181024/data.table/libs/datatable.so':
  /home/XXX/R/library/x86_64-pc-linux-gnu/3.5/bioc-3.7-release-20181024/data.table/libs/datatable.so: undefined symbol: LENGTH_EX
Execution halted
' returned non-zero exit status 1
```

**Comment by roryk** [comment]
Hi @mjsteinbaugh,

We fixed this here https://github.com/bcbio/bcbio-nextgen/commit/5342f35c993c4325204cff48bac5e4429c80d796 so an update and a re-run should be good to go.
