### ISSUE TITLE
problem installing hg19 genome

### ISSUE THREAD

**Issue by chenzler** [bcbio/bcbio-nextgen#2564]
I installed bcbio successfully, but when I try to run upgrade to add the hg19 genome, I get an error. 
I'm running:
bcbio_nextgen.py upgrade -u stable --data --genomes hg19 --datatarget variation

The error seems to be from a problem contacting the Broad's ftp site to download the hapmap vcf; over the last week, I've sometimes been able to access their site from the command line (though often I get the "Sorry, max 25 users -- try again later" error), but I can never get the upgrade script to connect successfully. I have the hg19 GATK bundle stored locally; is there anyway to link to that instead so I can bypass the download?

Error:
--2018-11-05 10:46:22--  ftp://gsapubftp-anonymous:*password*@ftp.broadinstitute.org/bundle/hg19/hapmap_3.3.hg19.sites.vcf.gz
           => ‘-’
Resolving ftp.broadinstitute.org... 69.173.80.251
Connecting to ftp.broadinstitute.org|69.173.80.251|:21... connected.
Logging in as gsapubftp-anonymous ... 
Login incorrect.

gzip: stdin: unexpected end of file
Traceback (most recent call last):
  File "/home/lmnp/shared/bin/bcbio/bcbio-nextgen/bin/bcbio_nextgen.py", line 223, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/home/lmnp/shared/bin/bcbio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 100, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/home/lmnp/shared/bin/bcbio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 308, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/panfs/roc/groups/0/lmnp/shared/bin/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 63, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/panfs/roc/groups/0/lmnp/shared/bin/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 109, in _setup_vm
    configure_instance(options, actions)
  File "/panfs/roc/groups/0/lmnp/shared/bin/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 269, in configure_instance
    setup_biodata(options)
  File "/panfs/roc/groups/0/lmnp/shared/bin/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 251, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/panfs/roc/groups/0/lmnp/shared/bin/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 340, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/panfs/roc/groups/0/lmnp/shared/bin/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 469, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/panfs/roc/groups/0/lmnp/shared/bin/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 836, in _install_with_ggd
    ggd.install_recipe(env.cwd, recipe_file, gid)
  File "/panfs/roc/groups/0/lmnp/shared/bin/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 31, in install_recipe
    recipe["recipe"]["full"]["recipe_type"])
  File "/panfs/roc/groups/0/lmnp/shared/bin/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 63, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/home/lmnp/shared/bin/bcbio/bcbio/anaconda/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bash', '/panfs/roc/groups/0/lmnp/shared/bin/bcbio/bcbio/genomes/Hsapiens/hg19/txtmp/ggd-run.sh']' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Sorry about this issue. This is a temporary problem with the Broad servers. When they get overloaded with requests they return this error. The best approach is to wait and re-try the upgrade command. bcbio will pick up where it left off and if the server is happier should hopefully proceed. Hope this helps get your upgrade finished.

**Comment by chenzler** [comment]
Thanks, it did eventually work!

**Comment by Priyankanator** [comment]
Hi, I am having same problems..when I looked at the website of broadinstitute it mentions this -
https://gatk.broadinstitute.org/hc/en-us/articles/360035890811-Resource-bundle
The FTP server is intended for people who wish to download files to run on them locally. However, FTP is local to the Broad Institute (there are no mirrors), it has tight limits on concurrent downloads, and users in some countries have reported difficulties accessing it due to e.g. firewalls. For these (and other) reasons, FTP Server Access will be disabled by June 1, 2020.
