### ISSUE TITLE
hts_nim_tools NULL bed file in chip experiments 

### ISSUE THREAD

**Issue by apastore** [bcbio/bcbio-nextgen#2573]
Hi Brad, I see this error in the QC step,

Thanks for your support!

[2018-11-14T02:29Z] lt07: QC: IgG chipqc
[2018-11-14T02:29Z] lt07: Uncaught exception occurred
Traceback (most recent call last):
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; hts_nim_tools count-reads -t 4 -F 780 NULL /Project/med12/med12_chip/work/align/IgG/IgG-sort.bam > /scratch/pastore/tmpZrgV6q/NULL-780-counts.txt
[E::hts_open_format] Failed to open file NULL
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
' returned non-zero exit status 1
[2018-11-14T02:29Z] lt07: Unexpected error
Traceback (most recent call last):
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 52, in _setup_logging
    yield config
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 303, in pipeline_summary
    return ipython.zip_args(apply(qcsummary.pipeline_summary, *args))
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 70, in pipeline_summary
    data["summary"] = _run_qc_tools(work_bam, work_data)
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 162, in _run_qc_tools
    out = qc_fn(bam_file, data, cur_qc_dir)
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/qc/chipseq.py", line 27, in run
    out.update(_reads_in_peaks(bam_file, peaks, sample))
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/qc/chipseq.py", line 34, in _reads_in_peaks
    rip = number_of_mapped_reads(sample, bam_file, bed_file = peaks_file)
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/readstats.py", line 93, in number_of_mapped_reads
    do.run(cmd.format(**locals()), "Count mapped reads: %s" % (dd.get_sample_name(data)))
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)

**Comment by apastore** [comment]
I have to add I was re-runing an experiment adding more samples.

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the issue. It looks like one of the macs runs failed and didn't produce any peak files, and the QC output was not handling it correctly. I pushed a fix to development that should skip over these samples and avoid the issue. If you update with `bcbio_nextgen.py upgrade -u development` and re-run it should hopefully work correctly for you. Please let us know if you run into any other issues.
