### ISSUE TITLE
multiqc issues with bcbio WES pipeline

### ISSUE THREAD

**Issue by Fazulur** [bcbio/bcbio-nextgen#2578]
Dear bcbio team,

I am getting MultiQC related error when I run whole exome analysis using bcbio-nextgen variant calling pipeline. Some how MultiQC peddy module was broken. Peddy ran without errors with bcbio pipleline. Please find below the error log.

[2018-11-15T06:36Z]local: KeyError: 'ancestry-prediction'
[2018-11-15T06:36Z]local: ============================================================
[2018-11-15T06:36Z]local: [INFO   ]        bcftools : Found 1 stats reports
[2018-11-15T06:36Z]local: [INFO   ]          snpeff : Found 1 reports
[2018-11-15T06:36Z]local: [INFO   ]          fastqc : Found 1 reports
[2018-11-15T06:36Z]local: [INFO   ]         multiqc : Compressing plot data
[2018-11-15T06:36Z]local: [INFO   ]         multiqc : Report      : ../../bcbiotx/tmpCENQTL/multiqc_report.html
[2018-11-15T06:36Z]local: [INFO   ]         multiqc : Data        : ../../bcbiotx/tmpCENQTL/multiqc_data
[2018-11-15T06:36Z]local: [INFO   ]         multiqc : MultiQC complete
[2018-11-15T06:36Z]local: Uncaught exception occurred
Traceback (most recent call last):
  File "bcbio-v1.0.8/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "bcbio-v1.0.8/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; export PATH=bcbio-v1.0.8/anaconda/bin:$PATH &&  bcbio-v1.0.8/anaconda/bin/multiqc -f -l
[INFO   ]         multiqc : This is MultiQC v1.6.dev0
[INFO   ]         multiqc : Template    : default
Searching 25 files..
[INFO   ]     verifybamid : Found 1 reports
[INFO   ]           bcbio : Found 1 reports
[INFO   ]        samtools : Found 1 stats reports
[INFO   ]        samtools : Found 1 idxstats reports
[INFO   ]           peddy : Found 2 reports
[ERROR  ]         multiqc : Oops! The 'peddy' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    peddy/sample.background_pca.json
============================================================
Module peddy raised an exception: Traceback (most recent call last):
  File "bcbio-v1.0.8/anaconda/bin/multiqc", line 440, in multiqc
    output = mod()
  File "bcbio-v1.0.8/anaconda/lib/python2.7/site-packages/multiqc/modules/peddy/peddy.py", line 87, in __init__
    self.peddy_pca_plot()
  File "bcbio-v1.0.8/anaconda/lib/python2.7/site-packages/multiqc/modules/peddy/peddy.py", line 219, in peddy_pca_plot
    'color': ancestry_colors.get(d['ancestry-prediction'], default_color)
KeyError: 'ancestry-prediction'
============================================================
Please find below attached peddy file
[sample.background_pca.json.txt.zip](https://github.com/bcbio/bcbio-nextgen/files/2591571/sample.background_pca.json.txt.zip)

With WGS pipeline, it is able to generate multiQC on peddy results.
Please help me to resolve this.

Thanks In Advance
Fazulur Rehaman

**Comment by chapmanb** [comment]
Fazulur;
Thanks much for the debugging work and figuring out the underlying problem. The new peddy release (0.4.3) with this fix is available from bioconda, so updating with `bcbio_conda install -c conda-forge -c bioconda peddy` (or a standard `--tools` update) should get the latest version with the fix. Hope this gets everything running smoothly for your samples.

**Comment by Fazulur** [comment]
Hi Brad,

Thanks a lot. I will upgrade to new version.

Thanks & Regards
Fazulur Rehaman
