### ISSUE TITLE
bcbio_prepare_samples.py deletes the original input files

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#2579]
I am using the script `bcbio_prepare_samples.py` even when the original input files don't need to be merged, in order to do bulk renaming and have a "cleaner" sample CSV file and work directory. However, in some cases, I noticed that the script removes the original FASTQ files, while in others it does not.

For example, when using the following CSV file, the original files are NOT removed:

```
samplename,description,batch
/home/amizeranschi/bcbio-stuff/automated-VC-test/fastq-files/sample1-R1-L001.fastq.gz,sample1,testingVC
/home/amizeranschi/bcbio-stuff/automated-VC-test/fastq-files/sample1-R1-L002.fastq.gz,sample1,testingVC
/home/amizeranschi/bcbio-stuff/automated-VC-test/fastq-files/sample1-R2-L001.fastq.gz,sample1,testingVC
/home/amizeranschi/bcbio-stuff/automated-VC-test/fastq-files/sample1-R2-L002.fastq.gz,sample1,testingVC
/home/amizeranschi/bcbio-stuff/automated-VC-test/fastq-files/sample2-R1-L001.fastq.gz,sample2,testingVC
/home/amizeranschi/bcbio-stuff/automated-VC-test/fastq-files/sample2-R1-L002.fastq.gz,sample2,testingVC
/home/amizeranschi/bcbio-stuff/automated-VC-test/fastq-files/sample2-R2-L001.fastq.gz,sample2,testingVC
/home/amizeranschi/bcbio-stuff/automated-VC-test/fastq-files/sample2-R2-L002.fastq.gz,sample2,testingVC
```

Meanwhile, when using the following CSV file, the original FASTQ files get deleted, although the script seems to work fine otherwise (i.e. the outputs are created identically as for the previous CSV file).

```
samplename,description,batch
/home/amizeranschi/bcbio-stuff/automated-VC-test/fastq-files/sample1-R1.fastq.gz,sample1,testingVC
/home/amizeranschi/bcbio-stuff/automated-VC-test/fastq-files/sample1-R2.fastq.gz,sample1,testingVC
/home/amizeranschi/bcbio-stuff/automated-VC-test/fastq-files/sample2-R1.fastq.gz,sample2,testingVC
/home/amizeranschi/bcbio-stuff/automated-VC-test/fastq-files/sample2-R2.fastq.gz,sample2,testingVC
```

My initial guess was that the script deletes the original files to avoid file name clashes, but the output file names are different from the original ones, for my test scenario (e.g. the original file `sample1-R1.fastq.gz` gets renamed to `sample1_R1.fastq.gz`)

How can I prevent the original FASTQ files from getting removed, when using the second CSV file? 

I am running the script as such:

```
bcbio_prepare_samples.py --out ${bcbio_exp_name}-merged --csv ${bcbio_exp_name}.csv
```

**Comment by chapmanb** [comment]
Thanks much for the report and sorry for the confusion. It looks like Lorena adjusted this recently to move the file rather than symlink:

https://github.com/bcbio/bcbio-nextgen/commit/1d54360d8acb1b3c69d6a0e95827e1b08aff355f#diff-b00e89f4a9678f65963b50a7ded468b4R135

@lpantano -- what do you think about restoring the previous symlink approach rather than renaming single files for fastq merges? Or is the new approach part of a bigger plan?

**Comment by amizeranschi** [comment]
Yes, it would be great for me if the original FASTQ files could be kept in place.

**Comment by lpantano** [comment]
Hey,

I just pushed the fix to this. It will work as before, and to move files the parameter `--remove-source` can be used.

sorry about this.

**Comment by amizeranschi** [comment]
Great, thank you very much!

One question: what is a good way of getting the latest versions of the modified files on my system, without manually checking out from GitHub?

I don't have a full local copy of Bcbio-nextgen installed at the moment. I'm testing the Bcbio_vm + CWL workflow, which I've installed following [these instructions](https://bcbio-nextgen.readthedocs.io/en/latest/contents/cwl.html#install-bcbio-vm-with-containers). 

I ran `bcbio_nextgen.py upgrade -u development` as I normally did when testing bcbio-nextgen, but this resulted in several conda packages getting downgraded, including numpy:

```
bcbio_nextgen.py upgrade -u development
Upgrading bcbio
Solving environment: ...working... done

# All requested packages already installed.

Solving environment: done

## Package Plan ##

  environment location: /home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda

  added / updated specs: 
    - libgcc-ng


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    readline-7.0               |       haf1bffa_1         381 KB  conda-forge
    cryptography-2.3.1         |   py27hdffb7b8_0         964 KB  conda-forge
    cryptography-vectors-2.3.1 |        py27_1000        30.5 MB  conda-forge
    libgcc-ng-7.2.0            |       hdf63c60_3         6.1 MB  conda-forge
    numpy-base-1.15.0          |   py27h3dfced4_0         4.1 MB
    scipy-1.1.0                |   py27hc49cb51_0        18.0 MB
    tk-8.6.9                   |       ha92aebf_0         3.1 MB  conda-forge
    numpy-1.15.0               |   py27h1b885b7_0          36 KB
    ------------------------------------------------------------
                                           Total:        63.1 MB

The following NEW packages will be INSTALLED:

    cryptography-vectors: 2.3.1-py27_1000       conda-forge

The following packages will be UPDATED:

    cryptography:         2.3.1-py27hc365091_0              --> 2.3.1-py27hdffb7b8_0  conda-forge
    tk:                   8.6.8-hbc83047_0                  --> 8.6.9-ha92aebf_0      conda-forge

The following packages will be DOWNGRADED:

    libgcc-ng:            8.2.0-hdf63c60_1                  --> 7.2.0-hdf63c60_3      conda-forge
    numpy:                1.15.4-py27h1d66e8a_0             --> 1.15.0-py27h1b885b7_0            
    numpy-base:           1.15.4-py27h81de0dd_0             --> 1.15.0-py27h3dfced4_0            
    readline:             7.0-h7b6447c_5                    --> 7.0-haf1bffa_1        conda-forge
    scipy:                1.1.0-py27hfa4b5c9_1              --> 1.1.0-py27hc49cb51_0             
```

This got the latest updates (the original FASTQ files aren't getting deleted anymore), but now Python prints a lot of warnings, which seem to be related to the Numpy package downgrade:

```
bcbio_prepare_samples.py --out ${bcbio_exp_name}-merged --csv ${bcbio_exp_name}.csv
/home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda/lib/python2.7/site-packages/cyvcf2/__init__.py:1: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .cyvcf2 import (VCF, Variant, Writer, r_ as r_unphased, par_relatedness,
[2018-11-22T15:10Z] Skipping header.
[2018-11-22T15:10Z] Resource requests: sambamba, samtools; memory: 1.00; cores: 1, 1
[2018-11-22T15:10Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2018-11-22T15:10Z] Resource requests: sambamba, samtools; memory: 1.00; cores: 1, 1
[2018-11-22T15:10Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2018-11-22T15:10Z] Timing: prepare bcbio samples
/home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda/lib/python2.7/site-packages/pandas/_libs/__init__.py:4: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
/home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda/lib/python2.7/site-packages/pandas/__init__.py:26: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (hashtable as _hashtable,
/home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda/lib/python2.7/site-packages/pandas/core/dtypes/common.py:6: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos, lib
/home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda/lib/python2.7/site-packages/pandas/core/util/hashing.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import hashing, tslib
/home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda/lib/python2.7/site-packages/pandas/core/indexes/base.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (lib, index as libindex, tslib as libts,
/home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda/lib/python2.7/site-packages/pandas/tseries/offsets.py:21: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.tslibs.offsets as liboffsets
/home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda/lib/python2.7/site-packages/pandas/core/ops.py:16: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos as libalgos, ops as libops
/home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda/lib/python2.7/site-packages/pandas/core/indexes/interval.py:32: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs.interval import (
/home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda/lib/python2.7/site-packages/pandas/core/internals.py:14: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import internals as libinternals
/home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda/lib/python2.7/site-packages/pandas/core/sparse/array.py:33: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.sparse as splib
/home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda/lib/python2.7/site-packages/pandas/core/window.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.window as _window
/home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda/lib/python2.7/site-packages/pandas/core/groupby/groupby.py:68: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (lib, reduction,
/home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda/lib/python2.7/site-packages/pandas/core/reshape/reshape.py:30: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos as _algos, reshape as _reshape
/home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda/lib/python2.7/site-packages/pandas/io/parsers.py:45: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.parsers as parsers
/home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda/lib/python2.7/site-packages/pandas/io/pytables.py:50: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos, lib, writers as libwriters
[2018-11-22T15:10Z] multiprocessing: prepare_bcbio_samples
```

**Comment by chapmanb** [comment]
Sorry about the numpy warnings. I'm not sure what caused it to downgrade on your install, sometimes the conda package dependencies can get pretty complex. Could you try doing:
```
bcbio_conda install -c conda-forge -c biconda 'numpy>=1.15.4'
```
to restore the previous version? It would be useful to know if that tries to change/downgrade other packages as we could figure out what change in your update linked to it. With that information we could improve the version pinning to avoid the downgrade for other updates. Thanks for the help debugging.

**Comment by amizeranschi** [comment]
OK, it looks like the numpy-base is getting downgraded further:

```
conda install -c conda-forge -c bioconda 'numpy>=1.15.4'
Solving environment: done

## Package Plan ##

  environment location: /home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda

  added / updated specs: 
    - numpy[version='>=1.15.4']


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-1.15.4               |py27_blas_openblashb06ca3d_0         8.9 MB  conda-forge
    libopenblas-0.2.20         |       h9ac9557_7         8.8 MB
    numpy-base-1.14.3          |   py27h0ea5e3f_1         4.0 MB
    scipy-1.1.0                |py27_blas_openblashb06ca3d_202        39.4 MB  conda-forge
    openblas-0.3.3             |       ha44fe06_1        13.7 MB  conda-forge
    blas-1.1                   |         openblas           1 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        74.8 MB

The following NEW packages will be INSTALLED:

    libopenblas: 0.2.20-h9ac9557_7                
    openblas:    0.3.3-ha44fe06_1      conda-forge

The following packages will be UPDATED:

    blas:        1.0-mkl                           --> 1.1-openblas                         conda-forge
    numpy:       1.15.0-py27h1b885b7_0             --> 1.15.4-py27_blas_openblashb06ca3d_0  conda-forge [blas_openblas]
    scipy:       1.1.0-py27hc49cb51_0              --> 1.1.0-py27_blas_openblashb06ca3d_202 conda-forge [blas_openblas]

The following packages will be DOWNGRADED:

    numpy-base:  1.15.0-py27h3dfced4_0             --> 1.14.3-py27h0ea5e3f_1    
```

**Comment by amizeranschi** [comment]
The `bcbio_prepare_samples.py` doesn't run anymore, after the last upgrade:

```
bcbio_prepare_samples.py --out ${bcbio_exp_name}-merged --csv ${bcbio_exp_name}.csv
Traceback (most recent call last):
  File "/home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda/bin/bcbio_prepare_samples.py", line 14, in <module>
    from bcbio.install import _get_data_dir
  File "/home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 27, in <module>
    from bcbio.cwl import create
  File "/home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio/cwl/create.py", line 18, in <module>
    from bcbio.cwl import defs, workflow
  File "/home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio/cwl/workflow.py", line 8, in <module>
    from bcbio.pipeline import alignment
  File "/home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 11, in <module>
    from bcbio import bam, utils
  File "/home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio/bam/__init__.py", line 8, in <module>
    import numpy
  File "/home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/amizeranschi/bcbio-stuff/bcbio-vm/anaconda/lib/python2.7/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: libgfortran.so.3: cannot open shared object file: No such file or directory
```

**Comment by chapmanb** [comment]
Sorry about the continued issues, it seems like the numpy-base downgrade was an issue. I'm not entirely sure what is happening here but you might want some combo of:
```
bcbio_conda install -c conda-forge -c biconda 'numpy-base>=1.15.4 numpy>=1.15.4'
```
to try and get back to the previous state before the upgrades. Hope this fixes it for you.

**Comment by amizeranschi** [comment]
The command `conda install -c conda-forge -c bioconda numpy-base>=1.15.4 numpy>=1.15.4` doesn't seem to be running on the previous install. Nothing gets printed after more than 20 minutes of running, so I assume it's stuck.

I've also just realized something that might be worth mentioning. When setting up bcbio_vm, I'm also installing gatk4 and ensembl-vep from conda. This is because I also want these packages available locally, so that I don't need to run them from within Docker. To be more precise, this is how I install Bcbio_vm:

```
wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
bash Miniconda2-latest-Linux-x86_64.sh -b -p ${bcbio_path}/anaconda
${bcbio_path}/anaconda/bin/conda install --yes -c conda-forge -c bioconda bcbio-nextgen gatk4 ensembl-vep
${bcbio_path}/anaconda/bin/conda install --yes -c conda-forge -c bioconda bcbio-nextgen-vm
```

Perhaps the addition of the gatk4 and the ensembl-vep packages is somehow messing up the dependencies and resulting in the numpy downgrade, when upgrading bcbio_nextgen to the latest development version. 

Is there any other way of upgrading the `bcbio_prepare_samples.py` script, without running `bcbio_nextgen.py upgrade -u development`?

**Comment by chapmanb** [comment]
Thanks for the additional details on your setup. The downside of conda is that it can get in some unique states depending on the packages installed. I don't think you did anything wrong, but it'll hard for us remotely to replicate exactly what is going on.

Waiting for the solver to finish on the install updating numpy-base is the way to go. It's possible you're accidentally redirecting the output on the command line, so make sure you have the `>` quoted in the command. You can also just separately upgrade `numpy-base` as a first pass:
```
conda install -c conda-forge -c bioconda 'numpy-base>=1.15.4'
```
You'll need to wait for it to finish resolving, even if it's taking an exceptionally long time. Hopefully that'll get your install working correctly.

**Comment by amizeranschi** [comment]
My bad, the lack of quotes got the `>` character to redirect the output and I didn't realize this. The update worked fine.

Thanks a lot for your help!
