### ISSUE TITLE
ValueError: too many values to unpack with lsf memory option

### ISSUE THREAD

**Issue by Fazulur** [bcbio/bcbio-nextgen#2593]
Dear Brad,

bcbio is giving the below error when I specified reserve memory lsf option under resources. 

Command

**bcbio_nextgen.py test.yaml -t ipython -s lsf -n 64 -q normal -p test -r "R=rusage[mem=20g]" -r P=test**

Error:

2018-12-12 08:47:53.826 [IPClusterStart] WARNING | Config option `mem` not recognized by `BcbioLSFControllerLauncher`.
2018-12-12 08:47:53.828 [IPClusterStart] Starting ipcluster with [daemon=True]
2018-12-12 08:47:53.845 [IPClusterStart] Creating pid file: test_bcbio/wgs/test_bcbio_memory/log/ipython/pid/ipcluster-41be293e-251c-43d4-a946-7
2018-12-12 08:47:53.845 [IPClusterStart] Starting Controller with cluster_helper.cluster.BcbioLSFControllerLauncher
2018-12-12 08:47:53.846 [IPClusterStart] ERROR | Controller start failed
Traceback (most recent call last):
  File “bcbio-v1.1.1/anaconda/lib/python2.7/site-packages/ipyparallel/apps/ipclusterapp.py", line 537, in start_controller
    self.controller_launcher.start()
  File "bcbio-v1.1.1/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py", line 225, in start
    self.context["resources"] = _format_lsf_resources(self.resources)
  File "bcbio-v1.1.1/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py", line 196, in _format_lsf_resources
    arg, val = r.split("=")
ValueError: too many values to unpack

Please help me to resolve this error.

Thanks In Advance
Fazulur Rehaman

**Comment by chapmanb** [comment]
Fazulur;
Thanks for the report. In general we don't control memory usage for engines this way in bcbio. It supplies memory using the parallelization (number of cores) and memory per core specified in the `bcbio_system.yaml` file. This allows it to scale up and down as cores change, rather than being locked in for all calls across the system. Additionally it avoids us needing to have a custom way to specify for every scheduler.

Happy to offer more specific advice with a better understanding of what you're aiming for with the memory adjustment. Hope this helps.

**Comment by Fazulur** [comment]
Dear Brad,

Thanks a lot for detailed explanation about bcbio memory usage.

Actually, when I submit gatk-variant pipeline on whole genome dataset with 256 cores using lsf as scheduler, job takes around 19 hours to finish. And I observe more memory is reserved per job and cpu efficiency is also very low.

For one sample we have to use 256 cores which is very huge and during the run time I observed only one or two nodes utilizing cpu and rest of them having <5% usage. 
I ran with 128 cores as well and it is taking long to finish pipeline. 

Here is the table with with turnaround time for each step.

Alignment-preparation | 1hour 40min
Alignment | 3.5hour
**BQSR&APPLYBQSR | 12 hour**
VaraintCalling | 50min
Calculatevarianteffects & Annotation | 40min
QC | 30min
Archive cram | 4hour

BQSR step using SPARK and is taking long to finish. spark is integrated with lsf in our hpc. Please suggest steps which will speed up the spark steps in pipeline.

Could you please suggest me how can I process more samples with less cores and more cpu utilization.

Thanks In Advance
Fazulur Rehaman

**Comment by chapmanb** [comment]
Fazulur;
Thanks for describing the underlying issue. The BQSR steps can be a slow limiting step, and we typically avoid them unless we have problematic input data. If you definitely need to run them, a couple of thoughts:

- Are you running GATK4? It has Spark multicore usage for BQSR where GATK3 does not?
- If you're running GATK4, can you confirm the poor CPU usage is trying to allocate to multiple cores? Do you know what command is taking a long time and can post what bcbio runs from `log/bcbio-nextgen-commands.log`?
- If you want to try allocating additional memory to help improve you can try increasing the GATK memory allocated per core:
```
resources:
   gatk:
      jvm_opts: ["-Xms2g", "-Xmx8g"]
```
https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#sample-or-run-specific-resources

Hope this helps with identifying the underlying cause of the slowdown.

**Comment by Fazulur** [comment]
Dear Brad,

Thanks a lot for your quick response. Please find below the details.

**Are you running GATK4? It has Spark multicore usage for BQSR where GATK3 does not?**

yes, I am using gatk4.

**Do you know what command is taking a long time and can post what bcbio runs from log/bcbio-nextgen-commands.log?**

Here are the BQSR and ApplyBQSR commands 

[2018-12-10T17:13Z] local: export SPARK_USER=fazulur unset JAVA_HOME && export PATH=bcbio-v1.1.1/anaconda/bin:$PATH && gatk --java-options '-Xms5g -Xmx99g -Djava.io.tmpdir=bcbiotx/tmpfFYdnu' BaseRecalibratorSpark -I align/test/test-sort.bam --spark-master local[8] --output bcbiotx/tmpfFYdnu/test-sort-recal.grp --reference bcbio-v1.1.1/genomes/Hsapiens/hs37d5/seq/hs37d5.fa --conf spark.driver.host=localhost --conf spark.network.timeout=800 --conf spark.executor.heartbeatInterval=100 --conf spark.local.dir=bcbiotx/tmpfFYdnu --known-sites bcbio-v1.1.1/genomes/Hsapiens/hs37d5/variation/dbsnp-151.vcf.gz -L align/test/test-sort-callable_sample.bed --interval-set-rule INTERSECTION
[2018-12-10T20:11Z] local: export SPARK_USER=fazulur unset JAVA_HOME && export PATH=bcbio-v1.1.1/anaconda/bin:$PATH && gatk --java-options '-Xms5g -Xmx99g -Djava.io.tmpdir=bcbiotx/tmpVRzm4t' ApplyBQSRSpark --spark-master local[8] --input align/test/test-sort.bam --output bcbiotx/tmpVRzm4t/test-sort-recal.bam --bqsr-recal-file align/test/test-sort-recal.grp --conf spark.local.dir=bcbiotx/tmpVRzm4t --conf spark.driver.host=localhost --conf spark.network.timeout=800 --static-quantized-quals 10 --static-quantized-quals 20 --static-quantized-quals 30 --jdk-deflater --jdk-inflater

### Few lines from bcbio-next.log 

[2018-12-10T15:50Z] hpcfatnode01.research.sidra.local: Timing: callable regions
[2018-12-10T15:50Z] hpcfatnode01.research.sidra.local: ipython: prep_samples
[2018-12-10T15:50Z] hpcfatnode01.research.sidra.local: ipython: postprocess_alignment
**[2018-12-10T15:59Z] hpcfatnode01.research.sidra.local: SRR2098182: Assigned coverage as 'genome' with 90.4% genome coverage and 0.0% offtarget coverage
[2018-12-10T17:12Z] hpcfatnode01.research.sidra.local: Prepare BQSR tables with GATK: SRR2098182** 
[2018-12-10T20:11Z] hpcfatnode01.research.sidra.local: Applying BQSR recalibration with GATK: SRR2098182 
[2018-12-10T22:24Z] hpcfatnode01.research.sidra.local: ipython: combine_sample_regions
[2018-12-10T22:24Z] hpcfatnode01.research.sidra.local: Identified 251 parallel analysis blocks
Block sizes:
  min: 4262
  5%: 34149.0
  25%: 612741.0
  median: 16034895.0
  75%: 17549125.0
  95%: 21870151.0
  99%: 31560057.5
  max: 43086024
Between block sizes:
  min: 251
  5%: 273.2
  25%: 314.0
  median: 455.0
  75%: 1126.0
  95%: 15473.0
  99%: 117996.48
  max: 3000000

And also please find attached LSF summary on bcbio job which tells about memory and cpu usage.

[bcbio-job-summary.xlsx](https://github.com/bcbio/bcbio-nextgen/files/2693280/bcbio-job-summary.xlsx)

**If you want to try allocating additional memory to help improve you can try increasing the GATK memory allocated per core**

I am specifying the sample specific resources as well in sample yaml config like below.

resources:
  default:
    cores: 8
    jvm_opts: [-Xms5g, -Xmx15g]

Please suggest me how can I improve pipeline.

Thanks In Advance
Fazulur Rehaman

**Comment by chapmanb** [comment]
Fazulur;
Thanks for the detailed feedback. It looks like you're effectively giving the GATK4 Spark commands plenty of memory (99g) and 8 cores so bcbio's translation of your inputs works as expected. I'm not entirely sure if I'm interpreting the LSF output correctly but if you're distributing this over multiple machines and only have a single sample the recalibration steps will only happen on one machine, which is likely the one showing resource usage during this step. bcbio doesn't try to distribute the run of this over multiple machines so can only make use of the resources on a single machine.

You might want to ssh into the machine and monitor CPU/memory during runtime but my guess is that it's moving along effectively, but WGS recalibration is slow and can take a long time to go through larger BAM files.

So I'm not sure if there's much you can do to make bcbio able to get this step faster, and would be better off in terms of effective resource usage here by not assigning so many cores and using them to push through additional other samples in parallel. One practical solution is also to run off recalibration unless you feel it necessary for this sample.

Sorry to not have a better solution but hope this helps.

**Comment by roryk** [comment]
Thanks, closing as this was answered without any followup-- I think Brad's recommendations make sense.
