### ISSUE TITLE
Pipeline should error when using svcallers that require cnvkit without having it specified

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2595]
Case in point: I was trying to test PureCN and TitanCNA on a dataset and I forgot to put `cnvkit` inside `svcaller`. I got an error that was rather hard to understand:

```
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 52, in _setup_logging
    yield config
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 418, in calculate_sv_bins
    return ipython.zip_args(apply(regions.calculate_sv_bins, *args))
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/regions.py", line 47, in calculate_sv_bins
    target_bed, anti_bed, gcannotated_tsv = calcfns[cnvkit.bin_approach(data)](data, cnv_group,
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 47, in bin_approach
    if norm_file.endswith(("-crstandardized.tsv", "-crdenoised.tsv")):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

My guess is that it was expecting something that was not created because CNVkit was not run.
Probably it would be best to error out.

**Comment by chapmanb** [comment]
Luca;
Thanks for trying out the new callers and for the helpful feedback. I added a check up front which will now give you a useful message if CNVkit or GATK4 CNV calling is not available when using a heterogeneity or SV caller that depend on them. Thanks again.
