### ISSUE TITLE
installation error: permission denied

### ISSUE THREAD

**Issue by kimoyerr** [bcbio/bcbio-nextgen#2597]
Hi,

I am trying to install bcbio-nextgen on my personal directory on a centos cluster storage space. I get the following permission denied error. Could someone please let me know what I am doing wrong. Thanks!!

Downloading and Extracting Packages
readline-7.0         | 381 KB    | ##################################### | 100%
numpy-1.15.0         | 35 KB     | ##################################### | 100%
scipy-1.1.0          | 18.0 MB   | ##################################### | 100%
libopenblas-0.2.20   | 8.8 MB    | ##################################### | 100%
libgcc-ng-7.2.0      | 6.1 MB    | ##################################### | 100%
numpy-base-1.15.0    | 4.1 MB    | ##################################### | 100%
tk-8.6.9             | 3.1 MB    | ##################################### | 100%
sqlite-3.26.0        | 1.6 MB    | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Solving environment: done

## Package Plan ##

  environment location: /inscripta/shared/kyerr/bcbio/stable/anaconda

  added / updated specs:
    - libgcc-ng

The following packages will be UPDATED:

    libgcc-ng: 7.2.0-hdf63c60_3 conda-forge --> 7.2.0-hdf63c60_3 conda-forge

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Upgrade of bcbio-nextgen code complete.
Traceback (most recent call last):
  File "/inscripta/shared/kyerr/bcbio/stable/anaconda/bin/bcbio_nextgen.py", line 221, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/inscripta/shared/kyerr/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 76, in upgrade_bcbio
    _set_matplotlib_default_backend()
  File "/inscripta/shared/kyerr/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 154, in _set_matplotlib_default_backend
    out_file.write(line)
  File "/inscripta/shared/kyerr/bcbio/stable/anaconda/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/inscripta/shared/kyerr/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/distributed/transaction.py", line 75, in file_transaction
    _move_tmp_files(safe, orig)
  File "/inscripta/shared/kyerr/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/distributed/transaction.py", line 92, in _move_tmp_files
    _move_file_with_sizecheck(safe, orig)
  File "/inscripta/shared/kyerr/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/distributed/transaction.py", line 114, in _move_file_with_sizecheck
    open(tmp_file, 'wb').close()
IOError: [Errno 13] Permission denied: '/etc/matplotlib/matplotlibrc.bcbiotmp'
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 265, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/inscripta/shared/kyerr/bcbio/stable/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--upgrade=stable', '--tooldir=tools', '--aligners=hisat2', '--aligners=minimap2', '--aligners=bowtie2', '--datatarget=rnaseq', '--genomes=hg38', '--genomes=hg19', '--cores=8', '--isolate', '--data']' returned non-zero exit status 1
[kyerr@cose006 bcbio]$

**Comment by chapmanb** [comment]
Thank you for the report and apologies about the issue. At this step bcbio is trying to customize the local matplotlib install, but it looks like it's picking up a global file instead that it doesn't have permissions to edit. I'm not entirely sure why it uses the global file but it might be due to having `MATPLOTLIBRC` set in your environmental variables:

https://matplotlib.org/users/customizing.html#the-matplotlibrc-file

I pushed a fix that will skip doing this as part of the install if we don't haver permissions but that might be hard to get into your install in the current state, so unsetting this environmental variable if present would be the best workaround. Hope this explains what is happening and gets you a clean installation.
