### ISSUE TITLE
centos7 slurm bcbio fails with ipython option

### ISSUE THREAD

**Issue by dauss75** [bcbio/bcbio-nextgen#2605]
I have machines with centos 7 and slurm installed and bcbio runs worked fine with a cluster.  Then, with the ipython parameter, but I find following errors in /log/ipython/log/:

[sequencer@av1pbm-ngs1 log]$ more ipcluster-d7da00c9-fd96-4ad0-a546-7101eba33b7c-183932.log
2018-12-24 09:59:13.400 [IPClusterStart] Starting ipcluster with [daemon=True]
2018-12-24 09:59:13.409 [IPClusterStart] Creating pid file: /isilon/RnD/test/test2/log/ipython/pid/ipcluster-d7da00c9-fd96-4ad0-a546-71
01eba33b7c.pid
2018-12-24 09:59:13.411 [IPClusterStart] Starting Controller with cluster_helper.cluster.BcbioSLURMControllerLauncher
2018-12-24 09:59:13.412 [IPClusterStart] Starting BcbioSLURMControllerLauncher: ['sbatch', u'./SLURM_controllera38d5373-7d62-484e-b67e-
3430e6be6575']
2018-12-24 09:59:13.412 [IPClusterStart] adding queue settings to batch script
2018-12-24 09:59:13.413 [IPClusterStart] Writing batch script: ./SLURM_controllera38d5373-7d62-484e-b67e-3430e6be6575
2018-12-24 09:59:13.441 [IPClusterStart] ERROR | Controller start failed
Traceback (most recent call last):
  File "/home/sequencer/local/share/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/apps/ipclusterapp.py", line 537, in start_co
ntroller
    self.controller_launcher.start()
  File "/home/sequencer/local/share/bcbio/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py", line 515, in start
    return super(BcbioSLURMControllerLauncher, self).start(1)
  File "/home/sequencer/local/share/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/apps/launcher.py", line 1164, in start
    output = check_output(self.args, env=os.environ)
  File "/home/sequencer/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['sbatch', u'./SLURM_controllera38d5373-7d62-484e-b67e-3430e6be6575']' returned non-zero exit status 1
2018-12-24 10:14:20.479 [IPClusterStart] SIGINT received, stopping launchers...
2018-12-24 10:14:20.479 [IPClusterStart] ERROR | IPython cluster: stopping

Then, I submitted the batch script created by ipython and got this error.
[sequencer@av1pbm-ngs1 test2]$ sbatch SLURM_controllera38d5373-7d62-484e-b67e-3430e6be6575
sbatch: error: Memory specification can not be satisfied
sbatch: error: Batch job submission failed: Requested node configuration is not available

Then, I modified the batch script and resubmitted.  I don't see errors, but also don't see bcbio producing outputs.

-rwxrwx--- 1 sequencer docker 1109 Dec 24 11:21 ipcontroller-d7da00c9-fd96-4ad0-a546-7101eba33b7c-184837.log
[sequencer@av1pbm-ngs1 log]$ more ipcontroller-d7da00c9-fd96-4ad0-a546-7101eba33b7c-184837.log
2018-12-24 10:22:58.186 [VMFixIPControllerApp] Hub listening on tcp://*:33867 for registration.
2018-12-24 10:22:58.189 [VMFixIPControllerApp] Hub using DB backend: 'NoDB'
2018-12-24 10:22:58.457 [VMFixIPControllerApp] hub::created hub
2018-12-24 10:22:58.457 [VMFixIPControllerApp] writing connection info to /isilon/RnD/test/test2/log/ipython/security/ipcontroller-d7da
00c9-fd96-4ad0-a546-7101eba33b7c-client.json
2018-12-24 10:22:58.465 [VMFixIPControllerApp] writing connection info to /isilon/RnD/test/test2/log/ipython/security/ipcontroller-d7da
00c9-fd96-4ad0-a546-7101eba33b7c-engine.json
2018-12-24 10:22:58.472 [VMFixIPControllerApp] task::using Python leastload Task scheduler
2018-12-24 10:22:58.473 [VMFixIPControllerApp] Heartmonitor started
2018-12-24 10:22:58.493 [VMFixIPControllerApp] Creating pid file: /isilon/RnD/test/test2/log/ipython/pid/ipcontroller-d7da00c9-fd96-4ad
0-a546-7101eba33b7c.pid
2018-12-24 10:22:58.507 [VMFixIPControllerApp] client::client '\x00k\x8bEg' requested 'connection_request'
2018-12-24 10:22:58.508 [VMFixIPControllerApp] client::client ['\x00k\x8bEg'] connected
[sequencer@av1pbm-ngs1 log]$ tail -f ipcontroller-d7da00c9-fd96-4ad0-a546-7101eba33b7c-184837.log
2018-12-24 10:22:58.186 [VMFixIPControllerApp] Hub listening on tcp://*:33867 for registration.
2018-12-24 10:22:58.189 [VMFixIPControllerApp] Hub using DB backend: 'NoDB'
2018-12-24 10:22:58.457 [VMFixIPControllerApp] hub::created hub
2018-12-24 10:22:58.457 [VMFixIPControllerApp] writing connection info to /isilon/RnD/test/test2/log/ipython/security/ipcontroller-d7da00c9-fd96-4ad0-a546-7101eba33b7c-client.json
2018-12-24 10:22:58.465 [VMFixIPControllerApp] writing connection info to /isilon/RnD/test/test2/log/ipython/security/ipcontroller-d7da00c9-fd96-4ad0-a546-7101eba33b7c-engine.json
2018-12-24 10:22:58.472 [VMFixIPControllerApp] task::using Python leastload Task scheduler
2018-12-24 10:22:58.473 [VMFixIPControllerApp] Heartmonitor started
2018-12-24 10:22:58.493 [VMFixIPControllerApp] Creating pid file: /isilon/RnD/test/test2/log/ipython/pid/ipcontroller-d7da00c9-fd96-4ad0-a546-7101eba33b7c.pid
2018-12-24 10:22:58.507 [VMFixIPControllerApp] client::client '\x00k\x8bEg' requested 'connection_request'
2018-12-24 10:22:58.508 [VMFixIPControllerApp] client::client ['\x00k\x8bEg'] connected

**Comment by chapmanb** [comment]
Segun;
Thanks for the report and apologies about the issues. If the bcbio controller died during submission the whole bcbio job will shut down and you won't be able to re-start it by running the `sbatch` command separately. The IPython setup needs a concurrent controller and engines with the main bcbio job to dispatch jobs.

Are you able to resolve what was causing the initial bcbio submission failure in an automated way so bcbio can produce a working controller script for submission? If so, do that and then re-run the bcbio job so it'll be able to correctly setup the whole environment. If not, let us know what is wrong and we can try to offer advice for fixing.

Hope this helps and gets your analysis running.
