### ISSUE TITLE
Can not find bed.gz.tbi file

### ISSUE THREAD

**Issue by hliu2016** [bcbio/bcbio-nextgen#2614]
Hi, I am running the variant2 pipeline on a shared file system. I always run into the file not found error as below:

> /bio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py in get_size(path='/bio/data/NA12878-illumina/final/bedprep/NA12878-sort-callable_sample-merged.bed.gz.tbi
> ')
>     229         or the size of all files in `path` if it's a directory.
>     230         Analogous to `du -s`.
>     231     """
>     232     if os.path.isfile(path):
>     233         return os.path.getsize(path)
> --> 234     return sum(get_size(os.path.join(path, f)) for f in os.listdir(path))
>         path = '/bio/data/NA12878-illumina/final/bedprep/NA12878-sort-callable_sample-merged.bed.gz.tbi'
>     235
>     236
>     237 def file_uptodate(fname, cmp_fname):
>     238     """Check if a file exists, is non-empty and is more recent than cmp_fname.
> OSError: [Errno 2] No such file or directory: '/bio/data/NA12878-illumina/final/bedprep/NA12878-sort-callable_sample-merged.bed.gz.tbi'

However, if I rerun the same command, such as bcbio_nextgen ../config/NA12878-wgs.yaml -n 32, the pipeline can be sucessfully completed. Is this problem caused by the shared file system? if so, how to fix it. Thanks in advance.

**Comment by chapmanb** [comment]
Sorry about this issue and thanks for the detailed report. Are you running into this issue with the latest bcbio version, or a previous one? There were some race conditions which you'd only see on shared filesystems. We've had some fixes for this, but it's possible that you're running into something we've missed.

If this is the latest version, could you share the full traceback so we can determine where in the process it's happening? Thanks for the help debugging.

**Comment by hliu2016** [comment]
@chapmanb 
Thanks for your quick reply. I am using the lastest release version. My shared file system is glusterfs. 
Sometimes, I have to rerun the same command twice to finish the pipeline. The full traceback is very long, so I attached the whole output as below: 
[nohup.txt](https://github.com/bcbio/bcbio-nextgen/files/2743036/nohup.txt)

**Comment by hliu2016** [comment]
@chapmanb 
I have noticed that if I use only one core "-n 1", bcbio does not report this error. However, when multicores is used, this error always occurred at least one times. 

I wonder if this problem is related to the write cache of the shared file system, as I found the file actually  exist.

**Comment by chapmanb** [comment]
Thanks much for the detailed error log and for the additional debugging. This was incredibly helpful in identifying the underlying issue. Based on the traceback I believe this could occur when you don't have a `variant_regions` input set in your configuration. In this case we use the calculated callable regions for calling, but were trying to merge/clean that file during parallel variant calling steps. When run in parallel on a shared filesystem this could lead to the same file being processed at multiple times and errors like these. I pushed a fix to avoid this extra prep step, which is not necessary for this file since it's pre-merged and cleaned.

Please let us know if you still hit issues and hope this fixes the problem for you. Thanks again for the help debugging and fixing.

**Comment by chapmanb** [comment]
That's exactly right. Ideally `variant_regions` will be set to the target regions BED file of your capture kit so you avoid calling in off target regions. Hope this helps.

**Comment by amizeranschi** [comment]
@chapmanb I'm running into the same issue (missing `file.bed.gz.tbi`) with bcbio_nextgen v. 1.2.0a. When checking for the reportedly missing bed.gz.tbi file, it does appear to exist. Perhaps this is a synchronization issue and it got created after the crash occurred?

I'm running the analysis using ipython parallel on an SGE cluster which uses NFS.

Note, the issue only appears with `mark_duplicates: false`. If this is set to `true`, the analysis runs fine.

This is the template:

```
---
details:
  - analysis: variant2
    genome_build: sacCer3_BRF
    resources:
      default:
        memory: 2G
        cores: 32
        jvm_opts: ["-Xms1000m", "-Xmx2000m"]
    algorithm:
      aligner: bwa
      effects: false
      mark_duplicates: false
      recalibrate: false
      realign: false
      variantcaller: gatk-haplotype
      jointcaller: gatk-haplotype-joint
      ploidy: 2
      tools_off: [gemini, contamination, peddy]
      tools_on: qualimap_full
      variant_regions: ../config/variant_regions.bed
```

The samples are WGS in yeast. The variant_regions.bed file contains the whole genomic regions. I created it like this:

```
awk 'BEGIN {FS="\t"}; {print $1 FS "0" FS $2}' /export/home/ncit/external/a.mizeranschi/bcbio_nextgen/genomes/Scerevisiae/sacCer3_BRF/seq/sacCer3_BRF.fa.fai > variant_regions.bed
```

The full error is below:

```
[2020-01-12T14:41Z] haswell-wn29.grid.pub.ro: end of bam qc
[2020-01-12T14:41Z] haswell-wn29.grid.pub.ro: Computing report...
[2020-01-12T14:41Z] haswell-wn29.grid.pub.ro: Writing HTML report...
[2020-01-12T14:41Z] haswell-wn29.grid.pub.ro: HTML report created successfully
[2020-01-12T14:41Z] haswell-wn29.grid.pub.ro: Finished
[2020-01-12T14:41Z] haswell-wn29.grid.pub.ro: Fix Name Qualimap for BRF_fastq
2020-01-12 16:41:32.890 [IPClusterStop] Using existing profile dir: '/export/home/ncit/external/a.mizeranschi/automated-VC-test-BRF/testingVC-merged/work/log/ipython'
2020-01-12 16:41:32.903 [IPClusterStop] Stopping cluster [pid=28317] with [signal=<Signals.SIGINT: 2>]
2020-01-12 16:41:33.934 [IPClusterStop] Using existing profile dir: '/export/home/ncit/external/a.mizeranschi/automated-VC-test-BRF/testingVC-merged/work/log/ipython'
2020-01-12 16:41:33.941 [IPClusterStop] Stopping cluster [pid=28317] with [signal=<Signals.SIGINT: 2>]
Running bcbio version: 1.2.0a
global config: /export/home/ncit/external/a.mizeranschi/automated-VC-test-BRF/testingVC-merged/work/bcbio_system.yaml
run info config: /export/home/ncit/external/a.mizeranschi/automated-VC-test-BRF/testingVC-merged/config/testingVC-merged.yaml
1 Engines running
Sending a shutdown signal to the controller and engines.
10 Engines running
Sending a shutdown signal to the controller and engines.
320 Engines running
Sending a shutdown signal to the controller and engines.
10 Engines running
Sending a shutdown signal to the controller and engines.
Traceback (most recent call last):
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/tools/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 58, in run_main
    fc_dir, run_info_yaml)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 192, in variant2pipeline
    samples = qcsummary.generate_parallel(samples, run_parallel)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/pipeline/qcsummary.py", line 42, in generate_parallel
    qced = run_parallel("pipeline_summary", to_analyze)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipython.py", line 137, in run
    for data in view.map_sync(fn, items, track=False):
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/ipyparallel/client/view.py", line 344, in map_sync
    return self.map(f,*sequences,**kwargs)
  File "</export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/decorator.py:decorator-gen-140>", line 2, in map
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/ipyparallel/client/view.py", line 52, in sync_results
    ret = f(self, *args, **kwargs)
  File "</export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/decorator.py:decorator-gen-139>", line 2, in map
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/ipyparallel/client/view.py", line 37, in save_ids
    ret = f(self, *args, **kwargs)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/ipyparallel/client/view.py", line 1114, in map
    return pf.map(*sequences)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/ipyparallel/client/remotefunction.py", line 299, in map
    return self(*sequences, __ipp_mapping=True)
  File "</export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/decorator.py:decorator-gen-122>", line 2, in __call__
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/ipyparallel/client/remotefunction.py", line 80, in sync_view_results
    return f(self, *args, **kwargs)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/ipyparallel/client/remotefunction.py", line 285, in __call__
    return r.get()
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/ipyparallel/client/asyncresult.py", line 169, in get
    raise self.exception()
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/ipyparallel/client/asyncresult.py", line 228, in _resolve_result
    results = error.collect_exceptions(results, self._fname)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/ipyparallel/error.py", line 233, in collect_exceptions
    raise e
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/ipyparallel/error.py", line 231, in collect_exceptions
    raise CompositeError(msg, elist)
ipyparallel.error.CompositeError: one or more exceptions from call to method: pipeline_summary
[3:apply]: FileNotFoundError: [Errno 2] No such file or directory: '/export/home/ncit/external/a.mizeranschi/automated-VC-test-BRF/testingVC-merged/work/bedprep/cleaned-variant_regions-merged-merged.bed.gz.tbi'
```
