### ISSUE TITLE
batch error 

### ISSUE THREAD

**Issue by DiyaVaka** [bcbio/bcbio-nextgen#2631]
Traceback (most recent call last):
  File "/mnt/bcbio/tools/bin/bcbio_nextgen.py", line 238, in <module>
    main(**kwargs)
  File "/mnt/bcbio/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 190, in variant2pipeline
    samples = peddy.run_peddy_parallel(samples, run_parallel)
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/peddy.py", line 32, in run_peddy_parallel
    samples = parallel_fn("run_peddy", [[x] for x in to_run])
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(x) for x in items):
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 983, in __call__
    if self.dispatch_one_batch(iterator):
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 825, in dispatch_one_batch
    self._dispatch(tasks)
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 782, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 545, in __init__
    self.results = batch()
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 261, in __call__
    for func, args, kwargs in self.items]
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 23, in run_peddy
    return peddy.run_peddy(*args)
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/peddy.py", line 99, in run_peddy
    do.run(cmd.format(**locals()), message.format(**locals()))
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /mnt/bcbio/anaconda/bin/peddy -p 16  --plot --prefix /mnt/bcbiotx/tmpE7qxEY/batch1 /mnt/qc/batch1/peddy/batch1-effects-annotated-filter-germline.vcf.gz /mnt/qc/batch1/peddy/batch1-effects-annotated-filter-germline.ped 2> /mnt/bcbiotx/tmpE7qxEY/run-stderr.log
' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Diya;
Thanks much for the report. It looks from this part of the traceback like peddy is failing but what you've included I don't see any useful error messages there. If you run peddy outside of bcbio:
```
/mnt/bcbio/anaconda/bin/peddy -p 16 --plot --prefix peddy-batch1-test /mnt/qc/batch1/peddy/batch1-effects-annotated-filter-germline.vcf.gz /mnt/qc/batch1/peddy/batch1-effects-annotated-filter-germline.ped 
```
Does it still fail? Knowing the error message you're seeing could help us either fix the issue or correctly recognize and avoid failing on a problematic input. Thanks for the help debugging.

**Comment by DiyaVaka** [comment]
Hi Brad,

running it outside did not fail.

[ec2-user@ip-172-31-43-105 mnt]$ /mnt/bcbio/anaconda/bin/peddy -p 16 --plot --prefix peddy-batch1-test /mnt/qc/batch1/peddy/batch1-effects-annotated-filter-germline.vcf.gz /mnt/qc/batch1/peddy/batch1-effects-annotated-filter-germline.ped
2019-01-16 20:06:16 ip-172-31-43-105 peddy.cli[32096] INFO Running Peddy version 0.4.3
2019-01-16 20:06:16 ip-172-31-43-105 peddy.cli[32096] INFO ped_check
2019-01-16 20:06:18 ip-172-31-43-105 peddy.peddy[32096] INFO plotting
2019-01-16 20:06:19 ip-172-31-43-105 peddy.cli[32096] INFO ran in 2.7 seconds
2019-01-16 20:06:19 ip-172-31-43-105 peddy.cli[32096] INFO het_check
2019-01-16 20:06:21 ip-172-31-43-105 peddy.pca[32096] INFO loaded and subsetted thousand-genomes genotypes (shape: (2504, 7421)) in 0.5 seconds
2019-01-16 20:06:22 ip-172-31-43-105 peddy.pca[32096] INFO ran randomized PCA on thousand-genomes samples at 7421 sites in 1.7 seconds
2019-01-16 20:06:22 ip-172-31-43-105 peddy.pca[32096] INFO Projected thousand-genomes genotypes and sample genotypes and predicted ancestry via SVM in 0.1 seconds
/mnt/bcbio/anaconda/lib/python2.7/site-packages/peddy/peddy.py:916: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  df = pd.concat((df, pca_df), axis=1)
2019-01-16 20:06:23 ip-172-31-43-105 peddy.cli[32096] INFO ran in 4.3 seconds
2019-01-16 20:06:23 ip-172-31-43-105 peddy.cli[32096] INFO sex_check
2019-01-16 20:06:23 ip-172-31-43-105 peddy.peddy[32096] INFO sex-check: 64 skipped / 1344 kept
2019-01-16 20:06:24 ip-172-31-43-105 peddy.cli[32096] INFO ran in 0.3 seconds

**Comment by chapmanb** [comment]
Diya;
Thanks for following up on this. Does it fail consistently when running bcbio? I wonder if you hit some kind of temporary filesystem or memory issue. If it does, could you try running non-parallel with `-n 1` to see if we can get a more useful error message to help determine why it fails? Thanks again.

**Comment by DiyaVaka** [comment]
Ok i tried running it again in non-parallel and it worked. Thanks,
