### ISSUE TITLE
mutect error

### ISSUE THREAD

**Issue by DiyaVaka** [bcbio/bcbio-nextgen#2636]
Hi Brad,

for couple of samples I am getting mutect errors
Using GATK jar /mnt/bcbio/anaconda/share/gatk4-4.0.12.0-0/gatk-package-4.0.12.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xms681m -Xmx3181m -XX:+UseSerialGC -Djava.io.tmpdir=/mnt/bcbiotx/tmpYJGFBK -jar /mnt/bcbio/anaconda/share/gatk4-4.0.12.0-0/gatk-package-4.0.12.0-local.jar FilterMutectCalls --variant /mnt/bcbiotx/tmpYJGFBK/batch1-12_0_15622555-raw.vcf.gz --output /mnt/bcbiotx/tmpYJGFBK/batch1-12_0_15622555-raw-filt.vcf.gz
20:30:13.755 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/mnt/bcbio/anaconda/share/gatk4-4.0.12.0-0/gatk-package-4.0.12.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
20:30:14.348 INFO  FilterMutectCalls - ------------------------------------------------------------
20:30:14.374 INFO  FilterMutectCalls - The Genome Analysis Toolkit (GATK) v4.0.12.0
20:30:14.375 INFO  FilterMutectCalls - For support and documentation go to https://software.broadinstitute.org/gatk/
20:30:14.375 INFO  FilterMutectCalls - Executing as ec2-user@ip-172-31-34-140 on Linux v4.14.88-72.73.amzn1.x86_64 amd64
20:30:14.376 INFO  FilterMutectCalls - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_152-release-1056-b12
20:30:14.376 INFO  FilterMutectCalls - Start Date/Time: January 18, 2019 8:30:13 PM UTC
20:30:14.376 INFO  FilterMutectCalls - ------------------------------------------------------------
20:30:14.376 INFO  FilterMutectCalls - ------------------------------------------------------------
20:30:14.377 INFO  FilterMutectCalls - HTSJDK Version: 2.18.1
20:30:14.377 INFO  FilterMutectCalls - Picard Version: 2.18.16
20:30:14.377 INFO  FilterMutectCalls - HTSJDK Defaults.COMPRESSION_LEVEL : 2
20:30:14.377 INFO  FilterMutectCalls - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
20:30:14.377 INFO  FilterMutectCalls - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
20:30:14.377 INFO  FilterMutectCalls - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
20:30:14.377 INFO  FilterMutectCalls - Deflater: IntelDeflater
20:30:14.377 INFO  FilterMutectCalls - Inflater: IntelInflater
20:30:14.377 INFO  FilterMutectCalls - GCS max retries/reopens: 20
20:30:14.377 INFO  FilterMutectCalls - Requester pays: disabled
20:30:14.378 INFO  FilterMutectCalls - Initializing engine
20:30:14.865 INFO  FeatureManager - Using codec VCFCodec to read file file:///mnt/bcbiotx/tmpYJGFBK/batch1-12_0_15622555-raw.vcf.gz
20:30:14.934 INFO  FilterMutectCalls - Done initializing engine
20:30:15.060 INFO  ProgressMeter - Starting traversal
20:30:15.082 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
20:30:15.083 INFO  FilterMutectCalls - Starting first pass through the variants
20:30:15.506 INFO  FilterMutectCalls - Shutting down engine
[January 18, 2019 8:30:15 PM UTC] org.broadinstitute.hellbender.tools.walkers.mutect.FilterMutectCalls done. Elapsed time: 0.03 minutes.
Runtime.totalMemory()=691404800
java.lang.IllegalArgumentException: errorRateLog10 must be good probability but got NaN
        at org.broadinstitute.hellbender.utils.QualityUtils.phredScaleLog10ErrorRate(QualityUtils.java:321)
        at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2FilteringEngine.lambda$applyGermlineVariantFilter$10(Mutect2FilteringEngine.java:207)
        at java.util.stream.DoublePipeline$3$1.accept(DoublePipeline.java:231)
        at java.util.Spliterators$DoubleArraySpliterator.forEachRemaining(Spliterators.java:1198)
        at java.util.Spliterator$OfDouble.forEachRemaining(Spliterator.java:822)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.util.stream.IntPipeline.toArray(IntPipeline.java:502)
        at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2FilteringEngine.applyGermlineVariantFilter(Mutect2FilteringEngine.java:207)
        at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2FilteringEngine.calculateFilters(Mutect2FilteringEngine.java:436)
        at org.broadinstitute.hellbender.tools.walkers.mutect.FilterMutectCalls.firstPassApply(FilterMutectCalls.java:120)
        at org.broadinstitute.hellbender.engine.TwoPassVariantWalker.lambda$traverseVariants$0(TwoPassVariantWalker.java:76)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.broadinstitute.hellbender.engine.TwoPassVariantWalker.traverseVariants(TwoPassVariantWalker.java:74)
        at org.broadinstitute.hellbender.engine.TwoPassVariantWalker.traverse(TwoPassVariantWalker.java:27)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:966)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
' returned non-zero exit status 3
___________________________________________________________________________

**Comment by chapmanb** [comment]
Diya;
Thanks for the report and sorry about the issue. This is a bug in GATK4 4.0.12.0 (https://github.com/broadinstitute/gatk/issues/5553) that is fixed in development and should work cleanly in the next GATK4 release. In the short term it seems like you could work around the issue by downgrading to 4.0.10.0:
```
bcbio_conda install -c conda-forge -c bioconda gatk4=4.0.10.0
```
Hope this helps as a workaround.

**Comment by chapmanb** [comment]
Diya;
Thanks for your work debugging and re-running and apologies about the additional issue. It looks like there is something problematic about the VCF file in that the header expects two samples -- I'm inferring a tumor/normal pair -- but the sample line it lists only has a single sample:
```
error: more sample names in header than sample fields
samples: NG017 NG40
line: 1 14107360 rs41269807 T A . PASS ClippingRankSum=-2.538;DP=725;ECNT=1;FS=2.722;MQ=60;MQ0=0;MQRankSum=0;NLOD=92.62;N_ART_LOD=-2.499;POP_AF=1e-06;P_CONTAM=0;P_GERMLINE=-92.99;ReadPosRankSum=1.81;TLOD=725.59;AC=1;AN=4 GT:AD:AF:DP:F1R2:F2R1:MBQ:MFRL:MMQ:MPOS:SA_MAP_AF:SA_POST_PROB 0/1:181,216:0.546:397:76,111
```
Did something change with the setup of sample pairing in the configuration? I'm not sure why you'd have this disconnect but it's worth looking into your problem input VCF (`/mnt/mutect2/batch1-effects-annotated.vcf.gz`) to see if you can identify what went wrong. Hope this helps.

**Comment by lbeltrame** [comment]
I get a similar error, with the exception that I don't even *know* what the error is, because bcftools doesn't tell:

```
[W::vcf_parse] INFO 'POP_AF' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'P_CONTAM' is not defined in the header, assuming Type=String
[W::vcf_parse] INFO 'P_GERMLINE' is not defined in the header, assuming Type=String
[W::vcf_parse_format] FORMAT 'MBQ' is not defined in the header, assuming Type=String
[W::vcf_parse_format] FORMAT 'MFRL' is not defined in the header, assuming Type=String
[W::vcf_parse_format] FORMAT 'MMQ' is not defined in the header, assuming Type=String
[W::vcf_parse_format] FORMAT 'MPOS' is not defined in the header, assuming Type=String
[W::vcf_parse_format] FORMAT 'SA_MAP_AF' is not defined in the header, assuming Type=String
[W::vcf_parse_format] FORMAT 'SA_POST_PROB' is not defined in the header, assuming Type=String
Encountered error, cannot proceed. Please check the error output above.
```

**Comment by gabeng** [comment]
@DiyaVaka did you just resume the bcbio job after downgrading to `gatk 4.0.10.0`? I ran into the same error and it turns out that Mutect2 applies much different annotations in newer versions. I guess that preliminary results of different versions cannot be merged or filtered.

**Comment by gabeng** [comment]
That's why I am so keen on the new "major" release 4.1.
Oh, darn. I just noticed that Brad has already released bcbio 1.1.3. I had hoped that it would contain `gatk 4.1`.

**Comment by DiyaVaka** [comment]
Hi.

After I downgrade mutect worked but batch was failing..

Thanks,

Dedeepya Vaka
Bioinformatics Programmer IV
Institute of Human Genetics
513 Parnassus Ave., HSE S965E
San Franscisco, CA 94143
W 415-502-3570
dedeepya.vaka@ucsf.edu


________________________________

**Comment by chapmanb** [comment]
Thanks all for the discussion and debugging. Ben is exactly right that if you have a project with partial 4.0.12.0 and partial 4.0.10.0 it will fail downstream due to different annotations between the versions. Unfortunately when merging we only get from a single VCF so will have these missing in the VCF header. The best thing to do is remove the mutect2 directory when restarting, which is a good plan scientifically so you don't have a mix of calls from different versions.

I'm also looking forward to 4.1 with the fixes for this issue. I didn't have a good timeframe on that and a bcbio release with fixes was overdue so got that out today, but can always have another upcoming release with 4.1 once that's out and we have a chance to test. Thanks again.

**Comment by DiyaVaka** [comment]
Hi All,

Exactly this is what I did.. just got rid of mutect2 from the pipeline and it worked. I plan to run
ru mutect2 independently on this pair

Dedeepya Vaka
Bioinformatics Programmer IV
Institute of Human Genetics
513 Parnassus Ave., HSE S965E
San Franscisco, CA 94143
W 415-502-3570
dedeepya.vaka@ucsf.edu


________________________________
