### ISSUE TITLE
Small RNA-Seq error

### ISSUE THREAD

**Issue by keenhl** [bcbio/bcbio-nextgen#2642]
I am trying to run the small rnaseq pipeline using default config parameters.   The read trimming proceeds correctly as well as the STAR alignment.  Then the following error occurs.  Any thoughts about this error and which approach should I take to debug.

Thank you.

[2019-01-22T17:58Z] Running STAR aligner on /project2C/project2C/work/seqcluster/prepare/seqs.fastq and /bcbio/stable/genomes/Hsapiens/hg19/star/
[2019-01-22T18:04Z] [bam_sort_core] merging from 0 files and 16 in-memory blocks...
Traceback (most recent call last):
  File "/bcbio/tools/bin/bcbio_nextgen.py", line 238, in <module>
    main(**kwargs)
  File "/bcbio/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 328, in smallrnaseqpipeline
    samples = run_parallel("srna_alignment", [samples])
  File "/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(x) for x in items):
  File "/bcbio/stable/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 917, in __call__
    if self.dispatch_one_batch(iterator):
  File "/bcbio/stable/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/bcbio/stable/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/bcbio/stable/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/bcbio/stable/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "/bcbio/stable/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 172, in srna_alignment
    return seqcluster.run_align(*args)
  File "/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/srna/group.py", line 69, in run_align
    sample = process_alignment(data[0][0], [seq_out, None])
  File "/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 128, in process_alignment
    data = align_to_sort_bam(fastq1, fastq2, aligner, data)
  File "/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 78, in align_to_sort_bam
    names, align_dir, data)
  File "/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 153, in _align_from_fastq
    out = align_fn(fastq1, fastq2, align_ref, names, align_dir, data)
  File "/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/star.py", line 100, in align
    data = _update_data(star_dirs.final_out, star_dirs.out_dir, names, data)
  File "/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/star.py", line 143, in _update_data
    sjbed = junction2bed(sjfile)
  File "/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/star.py", line 221, in junction2bed
    base, _ = os.path.splitext(junction_file)
  File "/bcbio/stable/anaconda/lib/python2.7/posixpath.py", line 98, in splitext
    return genericpath._splitext(p, sep, altsep, extsep)
  File "/bcbio/stable/anaconda/lib/python2.7/genericpath.py", line 99, in _splitext
    sepIndex = p.rfind(sep)
AttributeError: 'NoneType' object has no attribute 'rfind'

**Comment by rdocking** [comment]
Just saw the same thing, using bcbio 1.1.2 - here's my YAML template:

```
details:
  - analysis: smallRNA-seq
    algorithm:
      trim_reads: false
      aligner: star
      expression_caller: [seqbuster]
      species: hsa
    genome_build: hg19
upload:
  dir: ../final
```

This was running locally. I suspect the error stems from this:

```
[2019-01-22T18:32Z] Running STAR aligner on /projects/karsanlab/rdocking/KARSANBIO-1229_isomirs/KARSANBIO-1651_reprocessing/two_libs/work/seqcluster/prepare/seqs.fastq and /projects/rdocking_prj/software/bcbio-nextgen/data/genomes/Hsapiens/hg19/star/
[2019-01-22T18:35Z] [bam_sort_core] merging from 0 files and 8 in-memory blocks...
Traceback (most recent call last):
```

Maybe no output produced from the aligner?

**Comment by rdocking** [comment]
Actually, I re-ran the STAR command, and a BAM file was produced, so I don't think that's the source of the error. Looks like something after STAR and before the next step in bcbio.

**Comment by keenhl** [comment]
Same here.  A valid BAM file is produced.

**Comment by rdocking** [comment]
I upgraded to the latest development version and re-started: it looks like I'm past the alignment stage and on to the annotation stage.

**Comment by lpantano** [comment]
Thanks @rdocking, there was an issue a while ago with that. Let me know if the updated version doesn't work.

@keenhl, sorry about the issue. Can you tell me if you are using the last development version, or what version are you using? As well, if it is already the last devel version, can you send me the log/*debug.log file entirely somehow. I can see better the steps done until that moment and think about possible next steps.

Thanks both!

**Comment by rdocking** [comment]
The current development version ran to completion without error - thanks for looking @lpantano !

**Comment by keenhl** [comment]
@lpantano Thanks for your help.  I upgraded to the latest development version and it gets past the previous step, but then dies with the following error.  It looks like the problem is the lack of the hairpin.fa file.   I can send you the entire log file that would help. Thanks.

`
[2019-01-23T16:49Z] Aligning lane 10_18-063_100_20190114000_S10_L003 with star aligner
[2019-01-23T16:49Z] Running STAR aligner on /keenhl/project2C/project2C/work/trimmed/10_18-063_100_20190114000_S10_L003/10_18-063_100_20190114000_S10_L003_R1_001.clean.fastq.gz and /keenhl/bcbio/stable/genomes/Hsapiens/hg19/star/
[keenhl@argon-login-2 work]$ tail small1.e1009816 
  File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/srna/sample.py", line 223, in _align
    do.run(cmd.format(**locals()), "Running razers3 against hairpins with %s" % infile)
  File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /keenhl/bcbio/stable/galaxy/../anaconda/bin/razers3 -dr 0 -i 80 -rr 90 -f -o /keenhl/project2C/project2C/work/bcbiotx/tmp9TUVIs/10_18-063_100_20190114000_S10_L003.bam ../srnaseq/hairpin.fa /keenhl/project2C/project2C/work/trimmed/10_18-063_100_20190114000_S10_L003/10_18-063_100_20190114000_S10_L003_R1_001.clean_trimmed.fastq
Failed to open genome file ../srnaseq/hairpin.fa
Exiting ...
' returned non-zero exit status 253`

**Comment by keenhl** [comment]
Set the the srnaseq genomes directory using the following command and everything seems to be working.  Will update once the run finishes.  Thanks @lpantano for your help.

` bcbio_nextgen.py upgrade -u development --data --genomes TAIR10 --datatarget smallrna`

**Comment by keenhl** [comment]
Update:  finished the miRDeep step (I think), but then threw another error (see below)

[2019-01-23T19:26Z] creating PDF files
[2019-01-23T19:26Z] ended: 13:26:38
[2019-01-23T19:26Z] total:0h:4m:16s
[2019-01-23T19:26Z] fasta and bed files have been created in subfolder mirna_results_res
[2019-01-23T19:26Z] miRDeep runtime:
[2019-01-23T19:26Z] started: 12:50:26
[2019-01-23T19:26Z] ended: 13:26:38
[2019-01-23T19:26Z] total:0h:36m:12s
Traceback (most recent call last):
  File "/keenhl/bcbio/tools/bin/bcbio_nextgen.py", line 238, in <module>
    main(**kwargs)
  File "/keenhl/bcbio/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 326, in smallrnaseqpipeline
    samples = run_parallel("srna_alignment", [samples])
  File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 917, in __call__
    if self.dispatch_one_batch(iterator):
  File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 54, in wrapper
    return f(*args, **kwargs)
  File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 172, in srna_alignment
    return seqcluster.run_align(*args)
  File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/srna/group.py", line 79, in run_align
    novel_db = mirdeep.run(data)
  File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/srna/mirdeep.py", line 49, in run
    novel_db = _parse_novel(out_file, dd.get_species(data[0][0]))
  File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/srna/mirdeep.py", line 102, in _parse_novel
    fa_handle.write(">{sps}-{name} {start}\n{pre}\n").format(**locals())
AttributeError: 'NoneType' object has no attribute 'format'

**Comment by jxshi** [comment]
> Update: finished the miRDeep step (I think), but then threw another error (see below)
> 
> [2019-01-23T19:26Z] creating PDF files
> [2019-01-23T19:26Z] ended: 13:26:38
> [2019-01-23T19:26Z] total:0h:4m:16s
> [2019-01-23T19:26Z] fasta and bed files have been created in subfolder mirna_results_res
> [2019-01-23T19:26Z] miRDeep runtime:
> [2019-01-23T19:26Z] started: 12:50:26
> [2019-01-23T19:26Z] ended: 13:26:38
> [2019-01-23T19:26Z] total:0h:36m:12s
> Traceback (most recent call last):
> File "/keenhl/bcbio/tools/bin/bcbio_nextgen.py", line 238, in 
> main(**kwargs)
> File "/keenhl/bcbio/tools/bin/bcbio_nextgen.py", line 46, in main
> run_main(**kwargs)
> File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 45, in run_main
> fc_dir, run_info_yaml)
> File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
> for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
> File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 326, in smallrnaseqpipeline
> samples = run_parallel("srna_alignment", [samples])
> File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
> return run_multicore(fn, items, config, parallel=parallel)
> File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
> for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
> File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 917, in **call**
> if self.dispatch_one_batch(iterator):
> File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
> self._dispatch(tasks)
> File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 716, in _dispatch
> job = self._backend.apply_async(batch, callback=cb)
> File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
> result = ImmediateResult(func)
> File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 549, in **init**
> self.results = batch()
> File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 225, in **call**
> for func, args, kwargs in self.items]
> File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 54, in wrapper
> return f(*args, **kwargs)
> File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 172, in srna_alignment
> return seqcluster.run_align(*args)
> File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/srna/group.py", line 79, in run_align
> novel_db = mirdeep.run(data)
> File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/srna/mirdeep.py", line 49, in run
> novel_db = _parse_novel(out_file, dd.get_species(data[0][0]))
> File "/keenhl/bcbio/stable/anaconda/lib/python2.7/site-packages/bcbio/srna/mirdeep.py", line 102, in _parse_novel
> fa_handle.write(">{sps}-{name} {start}\n{pre}\n").format(**locals())
> AttributeError: 'NoneType' object has no attribute 'format'

Same error here.

```AttributeError: 'NoneType' object has no attribute 'format'```

**Comment by chapmanb** [comment]
Thank you for the report and apologies, this was a bug I introduced when trying to clean up some code recently. If you update to the latest development version:
```
bcbio_nextgen.py upgrade -u development
```
it should hopefully work cleanly for you now. Thanks for this help identifying issues and please let us know if you run into any other problems.
