### ISSUE TITLE
miraligner/Main : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by keenhl** [bcbio/bcbio-nextgen#2646]
Hi, I am trying to run the srnaseq pipeline and I get the following JAVA error.

Do miRNA annotation for /keenhl/project3/project3/work/trimmed/10_18-063_100_20190114000_S10_L003/10_18-063_100_20190114000_S10_L003_R1_001.clean_trimmed.fastq
[2019-01-24T17:37Z] Exception in thread "main" java.lang.UnsupportedClassVersionError: miraligner/Main : Unsupported major.minor version 52.0
[2019-01-24T17:37Z] 	at java.lang.ClassLoader.defineClass1(Native Method)
[2019-01-24T17:37Z] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
[2019-01-24T17:37Z] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[2019-01-24T17:37Z] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
[2019-01-24T17:37Z] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
[2019-01-24T17:37Z] Uncaught exception occurred

## here are the installed versions of JAVA 

java -version 

openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)

./bcbio/stable/anaconda/bin/java -version 

openjdk version "1.8.0_192"
OpenJDK Runtime Environment (Zulu 8.33.0.1-linux64) (build 1.8.0_192-b01)
OpenJDK 64-Bit Server VM (Zulu 8.33.0.1-linux64) (build 25.192-b01, mixed mode)

if I echo $JAVA_HOME, the result is blank

## bcbio version

I am running the latest development version of bcbio (upgraded earlier today)

**Comment by lpantano** [comment]
Hi,

sorry about this issue.

Can you get the command line from the log/bcbio-nextgen-command.log
file. Any of the one calling miraligner will be enough.

Thanks!

Lorena Pantano, P.h.D

Research Scientist

Biostatistics Department

Harvard T.H. Chan School of Public Health

https://mirtop.github.io

https://lpantano.github.io


I'll be out of office from Dec-17th to Jan9th

**Comment by keenhl** [comment]
Thanks.   


[2019-01-24T01:35Z] unset JAVA_HOME  && export PATH=/Shared/Bioinformatics/data/keenhl/bcbio/stable/anaconda/bin:$PATH &&  /Shared/Bioinformatics/data/keenhl/bcbio/stable/galaxy/../anaconda/bin/miraligner -Xms750m -Xmx3500m -freq -sub 1 -trim 3 -add 3 -minl 16 -s hsa -i /Shared/Bioinformatics/data/keenhl/project3/project3/work/trimmed/10_18-063_100_20190114000_S10_L003/10_18-063_100_20190114000_S10_L003_R1_001.clean_trimmed.fastq -db /Shared/Bioinformatics/data/keenhl/bcbio/stable/genomes/Hsapiens/hg19/srnaseq  -o /Shared/Bioinformatics/data/keenhl/project3/project3/work/bcbiotx/tmp2Re4JC/10_18-063_100_20190114000_S10_L003

**Comment by lpantano** [comment]
Hi,

I would try these different strategies:

1-make sure the last version of miraligner is installed:

`bcbio_conda update -c conda-forge -c biodonca seqbuster`

2- run the command locally to reproduce the error

I got the same version than you show and seqbuster 3.1-2 and all seems to work.

Let me know if the update doesn't fix the error.

**Comment by lpantano** [comment]
Hi,

it seems somehow it got the other java version even if we are forcing the
java installed with bcbio. I will try to get help on this.


Lorena Pantano, P.h.D

Research Scientist

Biostatistics Department

Harvard T.H. Chan School of Public Health

https://mirtop.github.io

https://lpantano.github.io


I'll be out of office from Dec-17th to Jan9th

**Comment by lpantano** [comment]
Hi,

As a wild test, can you modify the file:

and comment these lines:

/Shared/Bioinformatics/data/keenhl/bcbio/stable/anaconda/bin/miraligner

```
if [ -z "${JAVA_HOME:=}" ]; then
  if [ -e "$JAVA_HOME/bin/java" ]; then
      java="$JAVA_HOME/bin/java"
  fi
fi
```

**Comment by keenhl** [comment]
I commented out the lines mentioned above, and ran the above commands.  It worked without error.  I will try re-running the entire pipeline.

**Comment by lpantano** [comment]
ok, let me know. That is weird because we specifically unset java_home before running.

**Comment by lpantano** [comment]
awesome! I'll do that!

**Comment by keenhl** [comment]
Thanks @lpantano , @chapmanb .  The entire pipeline finished successfully after making the changes referenced above.

**Comment by lpantano** [comment]
Thanks!
