### ISSUE TITLE
Peddy error

### ISSUE THREAD

**Issue by matthdsm** [bcbio/bcbio-nextgen#2671]
Hi Brad,

Back again with another question.
I'm still looking for an ideal solution to the problem mentioned in #2567, but in the mean time I encountered the following error:
```
[2019-02-06T10:35Z] Running peddy on /kyukon/data/gent/vo/000/gvo00082/vsc41443/D1820101/work/gatk-haplotype/D1820101.vcf.gz against /kyukon/data/gent/vo/000/gvo00082/vsc41443/D1820101/work/gatk-haplotype/D1820101.ped.
[2019-02-06T10:35Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/data/gent/vo/000/gvo00082/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/data/gent/vo/000/gvo00082/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /data/gent/vo/000/gvo00082/bcbio/anaconda/bin/peddy -p 8 --sites hg38 --plot --prefix /scratch/gent/vo/000/gvo00082/vsc41443/bcbio/tmpIoitZs/D1820101-joint /kyukon/data/gent/vo/000/gvo00082/vsc41443/D1820101/work/gatk-haplotype/D1820101.vcf.gz /kyukon/data/gent/vo/000/gvo00082/vsc41443/D1820101/work/gatk-haplotype/D1820101.ped 2> /scratch/gent/vo/000/gvo00082/vsc41443/bcbio/tmpIoitZs/run-stderr.log
' returned non-zero exit status 1
[2019-02-06T10:35Z] Skipping peddy because no variants overlap with checks: D1820101-joint

```

This doesn't break anything, but I'm a bit paranoid about errors in the log. Do you have an explanation/solution for this?

Thanks
M

**Comment by chapmanb** [comment]
Matthias;
peddy can error out if there are not enough variants overlapping with the expected sites to do a proper PCA. This can happen with panel inputs or other smaller cases. There isn't a great way to know beforehand if there's going to be enough overlap, so we take the approach of catching these errors and proceeding without peddy:

https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/variation/peddy.py#L108

So, nothing to worry about here. Hope this helps explain what is going on.
