### ISSUE TITLE
vcf_ann failed running mutect2

### ISSUE THREAD

**Issue by hliu2016** [bcbio/bcbio-nextgen#2678]
I try to run mutect2 on a tumor-only sample. The yaml file is as below:
```
upload:
  dir: ../final
details:
  - files: [../input/L40_R1.fastq.gz, ../input/L40_R2.fastq.gz]
    description: wangzicheng
    metadata:
      #batch: L40
      #sex: female
      phenotype: tumor
    analysis: variant2
    genome_build: hg38
    algorithm:
      aligner: bwa
      mark_duplicates: true
      recalibrate: gatk
      realign: false
      effects: snpeff
      variantcaller: [mutect2]
      variant_regions: /bio/zhengu/LungCancer_11.bed
      remove_lcr: true
      tools_off: [gemini]
```

I have noticed #2426 and try to switch off vcfanno using tools_off options. However, it does not work for my running. The error information is as below:
```

[2019-02-10T12:18Z] =============================================
[2019-02-10T12:18Z] vcfanno version 0.3.1 [built with go1.11]
[2019-02-10T12:18Z] see: https://github.com/brentp/vcfanno
[2019-02-10T12:18Z] =============================================
[2019-02-10T12:18Z] vcfanno.go:115: found 61 sources from 5 files
[2019-02-10T12:18Z] vcfanno.go:143: using 2 worker threads to decompress query file
[2019-02-10T12:18Z] api.go:804: WARNING: using op 'self' when with Number='1' for 'AC_ACR' from '/bio/bcbio/genomes/Hsapiens/hg38/variation/gnomad_exome.vcf.gz' can result in out-of-order values when the query is multi-allelic
[2019-02-10T12:18Z] api.go:805:        : this is not an issue if the query has been decomposed.
[2019-02-10T12:18Z] api.go:804: WARNING: using op 'self' when with Number='1' for 'AN' from '/bio/bcbio/genomes/Hsapiens/hg38/variation/gnomad_exome.vcf.gz' can result in out-of-order values when the query is multi-allelic
[2019-02-10T12:18Z] api.go:805:        : this is not an issue if the query has been decomposed.
[2019-02-10T12:18Z] api.go:804: WARNING: using op 'self' when with Number='1' for 'AN_ANR' from '/bio/bcbio/genomes/Hsapiens/hg38/variation/gnomad_exome.vcf.gz' can result in out-of-order values when the query is multi-allelic
[2019-02-10T12:18Z] api.go:805:        : this is not an issue if the query has been decomposed.
[2019-02-10T12:18Z] api.go:804: WARNING: using op 'self' when with Number='1' for 'AN_AMR' from '/bio/bcbio/genomes/Hsapiens/hg38/variation/gnomad_exome.vcf.gz' can result in out-of-order values when the query is multi-allelic
[2019-02-10T12:18Z] api.go:805:        : this is not an issue if the query has been decomposed.
[2019-02-10T12:18Z] api.go:804: WARNING: using op 'self' when with Number='1' for 'AN_ASJ' from '/bio/bcbio/genomes/Hsapiens/hg38/variation/gnomad_exome.vcf.gz' can result in out-of-order values when the query is multi-allelic
[2019-02-10T12:18Z] api.go:805:        : this is not an issue if the query has been decomposed.
[2019-02-10T12:18Z] api.go:804: WARNING: using op 'self' when with Number='1' for 'AN_EAS' from '/bio/bcbio/genomes/Hsapiens/hg38/variation/gnomad_exome.vcf.gz' can result in out-of-order values when the query is multi-allelic
[2019-02-10T12:18Z] api.go:805:        : this is not an issue if the query has been decomposed.
[2019-02-10T12:18Z] api.go:804: WARNING: using op 'self' when with Number='1' for 'AN_FIN' from '/bio/bcbio/genomes/Hsapiens/hg38/variation/gnomad_exome.vcf.gz' can result in out-of-order values when the query is multi-allelic
[2019-02-10T12:18Z] api.go:805:        : this is not an issue if the query has been decomposed.
[2019-02-10T12:18Z] api.go:804: WARNING: using op 'self' when with Number='1' for 'AN_NFE' from '/bio/bcbio/genomes/Hsapiens/hg38/variation/gnomad_exome.vcf.gz' can result in out-of-order values when the query is multi-allelic
[2019-02-10T12:18Z] api.go:805:        : this is not an issue if the query has been decomposed.
[2019-02-10T12:18Z] api.go:804: WARNING: using op 'self' when with Number='1' for 'AN_OTH' from '/bio/bcbio/genomes/Hsapiens/hg38/variation/gnomad_exome.vcf.gz' can result in out-of-order values when the query is multi-allelic
[2019-02-10T12:18Z] api.go:805:        : this is not an issue if the query has been decomposed.
[2019-02-10T12:18Z] api.go:804: WARNING: using op 'self' when with Number='1' for 'AN_SAS' from '/bio/bcbio/genomes/Hsapiens/hg38/variation/gnomad_exome.vcf.gz' can result in out-of-order values when the query is multi-allelic
[2019-02-10T12:18Z] api.go:805:        : this is not an issue if the query has been decomposed.
[2019-02-10T12:18Z] vcfanno.go:187: Info Error: max_aaf_all not found in INFO >> this error/warning may occur many times. reporting once here...
[2019-02-10T12:18Z] vcfanno.go:187: Info Error: clinvar_sig not found in INFO >> this error/warning may occur many times. reporting once here...
[2019-02-10T12:18Z] vcfanno.go:187: Info Error: AN_ANR not found in header >> this error/warning may occur many times. reporting once here...
[2019-02-10T12:18Z] vcfanno.go:241: annotated 121 variants in 0.09 seconds (1305.3 / second)
[2019-02-10T12:18Z] tabix index wangzicheng-mutect2-annotated-gemini.vcf.gz
[2019-02-10T12:18Z] Timing: peddy check
[2019-02-10T12:18Z] multiprocessing: run_peddy
Traceback (most recent call last):
  File "/bio/bcbio/anaconda/bin/bcbio_nextgen.py", line 238, in <module>
    main(**kwargs)
  File "/bio/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/bio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/bio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/bio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 190, in variant2pipeline
    samples = peddy.run_peddy_parallel(samples, run_parallel)
  File "/bio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/peddy.py", line 32, in run_peddy_parallel
    samples = parallel_fn("run_peddy", [[x] for x in to_run])
  File "/bio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/bio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/bio/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 917, in __call__
    if self.dispatch_one_batch(iterator):
  File "/bio/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/bio/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/bio/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/bio/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "/bio/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/bio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "/bio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 23, in run_peddy
    return peddy.run_peddy(*args)
  File "/bio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/peddy.py", line 63, in run_peddy
    vcinfo = variant.extract_germline_vcinfo(d, peddy_dir)
  File "/bio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/qc/variant.py", line 140, in extract_germline_vcinfo
    raise NotImplementedError
NotImplementedError
```

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the issue. Is it possible you're running an older bcbio version? This should be fixed in the 1.1.2 and 1.1.3 releases if you're able to upgrade:

https://github.com/bcbio/bcbio-nextgen/commit/ec76c44ebe0a1bf436839f60482c4615100b5468#diff-90458b3fe804d92ceebabda7cec07cb4

Hope this helps get your analysis finished.

**Comment by hliu2016** [comment]
@chapmanb 
Thanks for your prompt reply. Yes, my bcbio version shows to be 1.1.1 by runing bcbio_nextgen.py version. I try to upgrade bcbio by running the `bcbio_nextgen.py upgrade --tools`  command, but it only upgrade some tools such as gatk. Would you tell me how to upgrade bcbio, but keep other things unchanged?

**Comment by chapmanb** [comment]
Thanks for confirming it's an older version. To upgrade the code you want to run: `bcbio_nextgen.py upgrade -u stable` or `bcbio_nextgen.py upgrade -u development` for either the last release or the current development version. Hope this helps.

**Comment by hliu2016** [comment]
@chapmanb  
Thank you very much. it does work!
