### ISSUE TITLE
Reference genome installation fails: AttributeError: 'Env' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by WimSpee** [bcbio/bcbio-nextgen#2679]
Hi, 

See the error below. I am running the genome installation script without a forcing a python. The  Python 2.7.15  version specified in the shebang of the script is used.  (the one in the anaconda bin directory of bcbio)
```
Traceback (most recent call last):
  File "/data/workspace/my_user/tmp_bcbio_1.1.3_development/tools/bin/bcbio_setup_genome.py", line 301, in <module>
    indexed[index] = index_fn(env, fasta_file)
  File "/data/run/Projects/DA-1341/w_bcbio_latest/add_reference/cloudbiolinux/cloudbio/biodata/genomes.py", line 440, in decorator
    return func(*args, **kwargs)
  File "/data/run/Projects/DA-1341/w_bcbio_latest/add_reference/cloudbiolinux/cloudbio/biodata/genomes.py", line 748, in _index_star
    _index_w_command(env, dir_name, cmd, ref_file)
  File "/data/workspace/my_user/tmp_bcbio_1.1.3_development/tools/bin/bcbio_setup_genome.py", line 123, in _index_w_command
    out_dir = os.path.join(build_path, dir_name)
  File "/data/workspace/my_user/tmp_bcbio_1.1.3_development/data/anaconda/lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
AttributeError: 'Env' object has no attribute 'startswith'
```

Line 301 was changed in a recent commit
https://github.com/bcbio/bcbio-nextgen/commit/f3d3d75e1cc05e476afe03506714148ebca57bdc

Changing line 301 to how it was before the commit does not solve the issue. Then this error is thrown. 

```
Traceback (most recent call last):
  File "/data/workspace/my_user/tmp_bcbio_1.1.3_development/tools/bin/bcbio_setup_genome.py", line 302, in <module>
    indexed[index] = index_fn(fasta_file)
TypeError: _index_bwa() takes exactly 2 arguments (1 given)
```

Thank you.

**Comment by chapmanb** [comment]
Wim;
Thank you for the report and apologies about the problem. I hadn't correctly updated the _index_w_command change in bcbio_setup_genome.py to match the new function signature in cloudbiolinux. I've just pushed a fix for this which I hope will resolve the issue and let this run cleanly. I haven't used bcbio_setup_genome.py as much so if I missed anything else at all please feel free to reopen here and we can work more on it. Thanks again.

**Comment by WimSpee** [comment]
Thank you.
