### ISSUE TITLE
Filtering Strelka2 calls results in: ValueError: operands could not be broadcast together with shapes (2,3) (2,)

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#2706]
Hello,

During a VC run with multiple callers (`variantcaller: [gatk-haplotype, freebayes, strelka2, platypus, samtools]`), I got the following error:

```
[2019-03-01T04:46Z] haswell-wn30.grid.pub.ro: Filtering Strelka2 calls with allele fraction threshold of 0.1
[2019-03-01T04:46Z] haswell-wn30.grid.pub.ro: Unexpected error
Traceback (most recent call last):
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 52, in _setup_logging
    yield config
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 382, in variantcall_sample
    return ipython.zip_args(apply(genotype.variantcall_sample, *args))
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 374, in variantcall_sample
    out_file = caller_fn(align_bams, items, ref_file, assoc_files, region, out_file)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/strelka2.py", line 33, in run
    return _af_annotate_and_filter(paired, items, call_file, out_file)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/strelka2.py", line 262, in _af_annotate_and_filter
    af = np.true_divide(alt_counts, dp)
ValueError: operands could not be broadcast together with shapes (2,3) (2,)
```

I found a possible solution here: https://howtothink.readthedocs.io/en/latest/PvL_06.html#broadcasting  and it looks like it worked for this case.

After modifying line 262 in `/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/strelka2.py` from

```
                        af = np.true_divide(alt_counts, dp)
```

to

```
                        af = np.true_divide(alt_counts, dp[:, None])
```

the analysis finished successfully.

**Comment by chapmanb** [comment]
Thanks much for the report and the suggested fix. It looks like this happens when you have multiple alleles, and I pushed your fix for that case. Thanks again.
