### ISSUE TITLE
Possible issues related to work/cromwell_work/persist/metadata.lobs

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#2722]
Hello,

During Cromwell runs, I'm always getting errors such as the following:

```
[2019-03-11 20:50:39,25] [info] lob file truncated to usage
[2019-03-11 20:50:40,13] [[38;5;1merror[0m] WriteMetadataActor Failed to properly process data
java.sql.BatchUpdateException: lob is no longer valid
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeBatch(Unknown Source)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$14(JdbcActionComponent.scala:532)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:386)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:381)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:448)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:501)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:526)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:30)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:27)
	at slick.dbio.DBIOAction$$anon$4.$anonfun$run$3(DBIOAction.scala:239)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:239)
	at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:237)
	at slick.dbio.SynchronousDatabaseAction$$anon$7.run(DBIOAction.scala:486)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Although these events don't crash the whole run, they are marked as `error`, so they seem worth taking into account.

I also noticed that the file `work/cromwell_work/persist/metadata.lobs` is taking up 36 GB of space for a run with 100 small FASTQ files. Is it normal for it to get this big?

I'm running these tests using a local bcbio install, on the NFS file system of a cluster running SGE. Could these errors be related to the "high cluster load" problems that I mentioned here: https://github.com/bcbio/bcbio-nextgen/issues/2721?

**Comment by chapmanb** [comment]
These are all related to scaling and I'll move discussion to #2721 and the cromwell issue rather than splitting into multiple places. Hopefully exploring a MySQL backend avoids these issues.
