### ISSUE TITLE
bcbio 1.1.4a returning sqlite3.OperationalError: disk I/O error in first moments of run

### ISSUE THREAD

**Issue by lento2002** [bcbio/bcbio-nextgen#2724]
at first few moments of a run getting below (file system is Lustre FSX on AWS), no special mount options.  rebooted respected head node and workers already re: locks.  any insight greatly appreciated

Traceback (most recent call last):
  File "/mnt/fsx/usr/local/bin/bcbio_nextgen.py", line 238, in <module>
    main(**kwargs)
  File "/mnt/fsx/usr/local/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 238, in rnaseqpipeline
    samples = rnaseq_prep_samples(config, run_info_yaml, parallel, dirs, samples)
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 410, in rnaseq_prep_samples
    [x[0]["description"] for x in samples]]])
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 921, in __call__
    if self.dispatch_one_batch(iterator):
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 424, in organize_samples
    return run_info.organize(*args)
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 81, in organize
    item["config"]["algorithm"]["qc"] = qcsummary.get_qc_tools(item)
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 96, in get_qc_tools
    if gtf.is_qualimap_compatible(dd.get_gtf_file(data)):
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/gtf.py", line 355, in is_qualimap_compatible
    db = get_gtf_db(gtf)
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/gtf.py", line 45, in get_gtf_db
    return gffutils.FeatureDB(db_file)
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/gffutils/interface.py", line 131, in __init__
    ''')
sqlite3.OperationalError: disk I/O error

**Comment by lento2002** [comment]
took a bit of a chance and nuked gffutils (tried subsequent upgrade and got below):  so  reinstalling with.....   bcbio_conda update -c conda-forge -c bioconda gffutils . hope that works.

    import gffutils
ImportError: No module named gffutils
[root@ip-10-0-0-44 site-packages]# bcbio_nextgen.py upgrade -u development
Traceback (most recent call last):
  File "/mnt/fsx/usr/local/bin/bcbio_nextgen.py", line 37, in <module>
    from bcbio import install, utils, workflow
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 26, in <module>
    from bcbio.cwl import create
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/cwl/create.py", line 20, in <module>
    from bcbio.cwl import defs, workflow
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/cwl/workflow.py", line 9, in <module>
    from bcbio.pipeline import alignment
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 13, in <module>
    from bcbio.ngsalign import (bbmap, bowtie, bwa, tophat, bowtie2, minimap2,
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/bwa.py", line 13, in <module>
    from bcbio.rnaseq import gtf
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/gtf.py", line 1, in <module>
    import gffutils
ImportError: No module named gffutils
[root@ip-10-0-0-44 site-packages]# bcbio_conda update -c conda-forge -c gffutils

CondaValueError: no package names supplied
# If you want to update to a newer version of Anaconda, type:
#
# $ conda update --prefix /mnt/fsx/usr/local/share/bcbio/anaconda anaconda


[root@ip-10-0-0-44 site-packages]# bcbio/anaconda/bin/conda install -c conda-forge -c bioconda gffutils
bash: bcbio/anaconda/bin/conda: No such file or directory
[root@ip-10-0-0-44 site-packages]# bcbio_conda update -c conda-forge -c bioconda gffutils

**Comment by lento2002** [comment]
still getting same general error....perhaps that wasn't wisest idea..

[root@ip-10-0-0-44 site-packages]# bcbio_nextgen.py upgrade -u development
Traceback (most recent call last):
  File "/mnt/fsx/usr/local/bin/bcbio_nextgen.py", line 37, in <module>
    from bcbio import install, utils, workflow
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 26, in <module>
    from bcbio.cwl import create
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/cwl/create.py", line 20, in <module>
    from bcbio.cwl import defs, workflow
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/cwl/workflow.py", line 9, in <module>
    from bcbio.pipeline import alignment
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/alignment.py", line 13, in <module>
    from bcbio.ngsalign import (bbmap, bowtie, bwa, tophat, bowtie2, minimap2,
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/bwa.py", line 13, in <module>
    from bcbio.rnaseq import gtf
  File "/mnt/fsx/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/gtf.py", line 1, in <module>
    import gffutils
ImportError: No module named gffutils

**Comment by lento2002** [comment]
also tried...
conda install -c bcbio gffutils .    after that finished same error 'no module named gffutils...' preceding ran w/o error though and seemingly installs gffuitls ?

**Comment by chapmanb** [comment]
Thanks for this report and sorry about the issues. You definitely need gffutils installed within the bcbio environment, so fixing that would be the first step to getting this running:
```
bcbio_conda install -c conda-forge -c bioconda gffutils --yes
```
With that in place, it should hopefully get bcbio running again.

For the original issue, it sounds like something with the Lustre FSX distributed filesystem you're using prevents use of sqlite3, which gffutils needs for its local database. Unfortunately I don't have any experience with this filesystem, but it might be worth asking on a Lustre specific help channel to see if anyone knows configuration options to allow sqlite access.

Hope this helps with getting your analysis run.

**Comment by roryk** [comment]
Closing this as this is pretty stale as part of a cleanup, please reopen if this didn't fix your problem. Thank you!
