### ISSUE TITLE
customize spark configuration with gatk-variant pipeline

### ISSUE THREAD

**Issue by Fazulur** [bcbio/bcbio-nextgen#2739]
Dear Bcbio team,

I am trying to replace localhost with some host from recalibrate.py script and trying to minimize  the turnaround time for BaseRecalibratorSpark and ApplyBQSRSpark steps.
I tested GATK4  BaseRecalibratorSpark and ApplyBQSRSpark with LSF scheduler and within 2 hours recalibration step was finished. Master node is able to allocate workers to multiple nodes efficiently.

I tried to change the below recalibrate.py from bcbio installation
bcbio-nextgen-1.0.9-py27_0/lib/python2.7/site-packages/bcbio/variation/recalibrate.py
bcbio-nextgen-1.1.2a-py27_2/lib/python2.7/site-packages/bcbio/variation/recalibrate.py
bcbio-nextgen-1.0.8-py27_0/lib/python2.7/site-packages/bcbio/variation/recalibrate.py
bcbio-nextgen-1.1.2a-py27_3/lib/python2.7/site-packages/bcbio/variation/recalibrate.py

"--spark-master", "local[%s]" % cores
to
"--spark-master", "spark://[node IP]:6311" % cores

When I run bcbio_nextgen.py using LSF as scheduler, still it is taking localhost as spark-master.
Could you please advice me is there any additional files I need to update and is there any configuration to customize default spark options?

Thanks In Advance
Fazulur Rehaman

**Comment by chapmanb** [comment]
Fazulur;
Thanks for the suggestion. We haven't had the chance to work on local spark clusters but happy to help support this use case. We added the ability to specify your custom locations with a `gatk-spark` resources parameter:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/parallel.html#spark

which should then propagate to the GATK tools using Spark. Please let us know if you run into any issues and thanks again.

**Comment by Fazulur** [comment]
Dear Brad,

Thanks a lot for your quick response.

As suggested, I have added gatk-spark resource parameter to yaml, but it is not picking spark-master specified in configuration. Still it is considering default local host.

Here is the sample specific yaml config

details:
- algorithm:
    aligner: bwa
    recalibrate: gatk
    tools_on: [gvcf]
    tools_off: [vqsr]
    variantcaller: [gatk-haplotype]
  analysis: variant2
  description: ‘test’
  files:
  - test_R1.fastq
  - test_R2.fastq
  genome_build: GRCh37
fc_name: ‘test’
resources:
  gatk-spark:
        options: [--spark-master, 'spark://**[sparkcluster]**:6311']
  default:
    cores: 8
    jvm_opts: [-Xms5g, -Xmx15g]
upload:
  dir: ../final

### BQSR command from log

[2019-04-02T11:25Z] [hostname].research:     java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xms454m -Xmx3181m -Djava.io.tmpdir=bcbiotx/tmp_JQJFc -jar anaconda/share/gatk4-4.1.0.0-0/gatk-package-4.1.0.0-local.jar BaseRecalibratorSpark -I align/test/test-sort.bam **--spark-master local[1]** --output bcbiotx/tmp_JQJFc/test-sort-recal.grp --reference genomes Hsapiens/GRCh37/seq/GRCh37.fa --conf spark.driver.host=localhost --conf spark.network.timeout=800 --conf spark.executor.heartbeatInterval=100 --conf spark.local.dir=bcbiotx/tmp_JQJFc --known-sites genomes/Hsapiens/GRCh37/variation/dbsnp-151.vcf.gz -L callable_sample.bed --interval-set-rule INTERSECTION

Is there anything am I missing in configuration. 
Please suggest me how can I proceed further.

Thanks In Advance
Fazulur Rehaman

**Comment by chapmanb** [comment]
Fazulur;
Thanks for trying this out. Are you testing with the latest development version?
```
bcbio_nextgen.py upgrade -u development
```
I just pushed support for this functionality based on your suggestion, and the log you posted looks like it's using an older version based on the command line argument order. Hope this fixes it for you.

**Comment by Fazulur** [comment]
Dear Brad,

As per your suggestion, we upgraded to development version and now we are facing new issues.

Here is ipcluster log

2019-04-11 08:38:41.765 [IPClusterStart] ERROR | Engine start failed
Traceback (most recent call last):
  File "BCBIO/v1.1.3/anaconda/lib/python3.6/site-packages/ipyparallel/apps/ipclusterapp.py", line 338, in start_engines
    self.engine_launcher.start(self.n)
  File "BCBIO/v1.1.3/anaconda/lib/python3.6/site-packages/cluster_helper/cluster.py", line 178, in start
    mem = lsf.parse_memory(float(self.mem))
  File "BCBIO/v1.1.3/anaconda/lib/python3.6/site-packages/cluster_helper/lsf.py", line 121, in parse_memory
    lsf_unit = get_lsf_units(resource=True)
  File "BCBIO/v1.1.3/anaconda/lib/python3.6/site-packages/cluster_helper/lsf.py", line 99, in get_lsf_units
    lsf_units = apply_bparams(get_lsf_units_from_stream)
  File "BCBIO/v1.1.3/anaconda/lib/python3.6/site-packages/cluster_helper/lsf.py", line 80, in apply_bparams
    return fn(output.split("\n"))
TypeError: a bytes-like object is required, not 'str'

Could you please help us to resolve this issue.

Thanks In Advance
Fazulur Rehaman

**Comment by chapmanb** [comment]
Fazulur;
Thanks for the report and sorry about the issue. We pushed a fix to ipython-cluster-helper to avoid the problem so if you either run another update or just the problem package:
```
bcbio_conda install -c conda-forge -c bioconda ipython-cluster-helper
```
it'll hopefully work cleanly now. Please let us know if you hit any other issues.

**Comment by Fazulur** [comment]
Dear Brad,

Thanks a lot for fixing this issue.

I tried adding spark master to sample specific configuration. It is picking up the spark master from sample config.

[2019-04-15T08:06Z] testcluster: 19/04/15 11:06:36 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://testcluster:7077...
[2019-04-15T08:06Z] testcluster: 19/04/15 11:06:36 INFO TransportClientFactory: Successfully created connection to testcluster/172.32.65.40:7077 after 30 ms (0 ms spent in bootstraps)

but i am getting the below error while running BaseRecalibratorSpark.

[2019-04-15T08:08Z] testcluster: 19/04/15 11:08:21 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, 172.32.65.40, executor 2): java.io.IOException: org.apache.spark.SparkException: Failed to register classes with Kryo
[2019-04-15T08:08Z] testcluster:         at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1310)
[2019-04-15T08:08Z] testcluster:         at org.apache.spark.broadcast.TorrentBroadcast.readBroadcastBlock(TorrentBroadcast.scala:206)
[2019-04-15T08:08Z] testcluster:         at org.apache.spark.broadcast.TorrentBroadcast._value$lzycompute(TorrentBroadcast.scala:66)
[2019-04-15T08:08Z] testcluster:         at org.apache.spark.broadcast.TorrentBroadcast._value(TorrentBroadcast.scala:66)
[2019-04-15T08:08Z] testcluster:         at org.apache.spark.broadcast.TorrentBroadcast.getValue(TorrentBroadcast.scala:96)
[2019-04-15T08:08Z] testcluster:         at org.apache.spark.broadcast.Broadcast.value(Broadcast.scala:70)
[2019-04-15T08:08Z] testcluster:         at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:81)
[2019-04-15T08:08Z] testcluster:         at org.apache.spark.scheduler.Task.run(Task.scala:108)
[2019-04-15T08:08Z] testcluster:         at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
[2019-04-15T08:08Z] testcluster:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[2019-04-15T08:08Z] testcluster:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[2019-04-15T08:08Z] testcluster:         at java.lang.Thread.run(Thread.java:745)
[2019-04-15T08:08Z] testcluster: Caused by: org.apache.spark.SparkException: Failed to register classes with Kryo
[2019-04-15T08:08Z] testcluster:         at org.apache.spark.serializer.KryoSerializer.newKryo(KryoSerializer.scala:139)
[2019-04-15T08:08Z] testcluster:         at org.apache.spark.serializer.KryoSerializerInstance.borrowKryo(KryoSerializer.scala:292)
[2019-04-15T08:08Z] testcluster:         at org.apache.spark.serializer.KryoSerializerInstance.<init>(KryoSerializer.scala:277)
[2019-04-15T08:08Z] testcluster:         at org.apache.spark.serializer.KryoSerializer.newInstance(KryoSerializer.scala:186)
[2019-04-15T08:08Z] testcluster:         at org.apache.spark.broadcast.TorrentBroadcast$.unBlockifyObject(TorrentBroadcast.scala:290)
[2019-04-15T08:08Z] testcluster:         at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$readBroadcastBlock$1.apply(TorrentBroadcast.scala:226)
[2019-04-15T08:08Z] testcluster:         at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1303)
[2019-04-15T08:08Z] testcluster:         ... 11 more
[2019-04-15T08:08Z] testcluster: Caused by: java.lang.ClassNotFoundException: org.broadinstitute.hellbender.engine.spark.GATKRegistrator
[2019-04-15T08:08Z] testcluster:         at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[2019-04-15T08:08Z] testcluster:         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[2019-04-15T08:08Z] testcluster:         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[2019-04-15T08:08Z] testcluster:         at java.lang.Class.forName0(Native Method)
[2019-04-15T08:08Z] testcluster:         at java.lang.Class.forName(Class.java:348)
[2019-04-15T08:08Z] testcluster:         at org.apache.spark.serializer.KryoSerializer$$anonfun$newKryo$5.apply(KryoSerializer.scala:134)
[2019-04-15T08:08Z] testcluster:         at org.apache.spark.serializer.KryoSerializer$$anonfun$newKryo$5.apply(KryoSerializer.scala:134)
[2019-04-15T08:08Z] testcluster:         at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[2019-04-15T08:08Z] testcluster:         at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[2019-04-15T08:08Z] testcluster:         at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
[2019-04-15T08:08Z] testcluster:         at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
[2019-04-15T08:08Z] testcluster:         at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[2019-04-15T08:08Z] testcluster:         at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
[2019-04-15T08:08Z] testcluster:         at org.apache.spark.serializer.KryoSerializer.newKryo(KryoSerializer.scala:134)
[2019-04-15T08:08Z] testcluster:         ... 17 more

Do I need to specify any specific spark option while creating spark cluster. Also please let me know how the spark cluster from the code itself is getting build.It will help me launch my spark cluster with same parameters.

Thanks In Advance
Fazulur Rehaman

**Comment by chapmanb** [comment]
Fazulur;
Sorry for the delay in getting back with you on this. Unfortunately I haven't run GATK on a separate Spark cluster so am not sure how to diagnose or fix this. This might be a better question for the GATK forum. If there is anything we can end up doing on bcbio side happy to try and adjust to make it possible. Sorry to not know more but hope this helps some.

**Comment by Fazulur** [comment]
Dear Brad,

Thanks a lot for your suggestions. I will write to GATK forum.

Thanks & Regards
Fazulur Rehaman
