### ISSUE TITLE
apply function in ipythontasks.py not compatible with python3

### ISSUE THREAD

**Issue by jessie-wangjie** [bcbio/bcbio-nextgen#2741]
Traceback (most recent call last):
  File "anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 52, in _setup_logging
    yield config
  File "anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 530, in organize_samples
    return ipython.zip_args(apply(run_info.organize, *args))
NameError: name 'apply' is not defined

**Comment by rdocking** [comment]
Just hit the same issue with bcbio 1.1.4:

```
Traceback (most recent call last):
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 52, in _setup_logging
    yield config
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 530, in organize_samples
    return ipython.zip_args(apply(run_info.organize, *args))
NameError: name 'apply' is not defined
```

Tail end of the other traceback:

```
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/ipyparallel/error.py", line 233, in collect_exceptions
    raise e
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/ipyparallel/error.py", line 231, in collect_exceptions
    raise CompositeError(msg, elist)
ipyparallel.error.CompositeError: one or more exceptions from call to method: organize_samples
[2:apply]: NameError: name 'apply' is not defined
```

**Comment by rdocking** [comment]
Looks like the `apply` function is there ~80 times in this file:

https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/distributed/ipythontasks.py

And no longer exists in Python 3:

https://stackoverflow.com/questions/23921781/name-error-name-apply-is-not-defined

**Comment by roryk** [comment]
Heya, thanks everyone, looks like we have a little bit more to clean up. I think we can just delete the apply calls and just call the function, let me test if that actually works.

**Comment by chapmanb** [comment]
Thanks so much for this report and sorry about missing this during the python3 migration. We've pushed a fix to the latest development version if you update with:
```
bcbio_nextgen.py upgrade -u development
```
and re-run it should hopefully work cleanly. Please let us know if you find any other issues. We're going to try to clean up any additional problems and have a new release right away to have a solid stable working version.

**Comment by rdocking** [comment]
Confirmed that this is working in the latest development version - thanks for the quick fix!

**Comment by radio1988** [comment]
So happy to see that the same issue I had was solved. However, when I ran the code `bcbio_nextgen.py upgrade -u development`, I got the following error, can you help solving this problem? Thanks!

This was tested on Mac, and bcbio_nextgen is installed though anaconda with bioconda channel added. My bcbio_nextgen version is 1.1.3a0

```
Upgrading bcbio
Traceback (most recent call last):
  File "/Users/rui/anaconda3/envs/py35/bin/bcbio_nextgen.py", line 221, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/Users/rui/anaconda3/envs/py35/lib/python3.5/site-packages/bcbio/install.py", line 60, in upgrade_bcbio
    anaconda_dir = _update_conda_devel()
  File "/Users/rui/anaconda3/envs/py35/lib/python3.5/site-packages/bcbio/install.py", line 308, in _update_conda_devel
    channels = _get_conda_channels(conda_bin)
  File "/Users/rui/anaconda3/envs/py35/lib/python3.5/site-packages/bcbio/install.py", line 276, in _get_conda_channels
    config = yaml.load(subprocess.check_output([conda_bin, "config", "--show"]))
  File "/Users/rui/anaconda3/envs/py35/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/Users/rui/anaconda3/envs/py35/lib/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/rui/anaconda3/envs/py35/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/Users/rui/anaconda3/envs/py35/lib/python3.5/subprocess.py", line 1211, in _execute_child
    executable = os.fsencode(executable)
  File "/Users/rui/anaconda3/envs/py35/lib/python3.5/os.py", line 864, in fsencode
    raise TypeError("expect bytes or str, not %s" % type(filename).__name__)
TypeError: expect bytes or str, not NoneType
```

**Comment by roryk** [comment]
Hi @radio1988, unfortunately bcbio doesn't work on macs-- many of the tools it uses don't work on macs, so you're likely to run into an impossible number of troubles getting it to work.

**Comment by radio1988** [comment]
Hi Rory, thanks for saving my time!
