### ISSUE TITLE
mirdeep TypeError in bcbio 1.1.4

### ISSUE THREAD

**Issue by rdocking** [bcbio/bcbio-nextgen#2743]
Hi guys - maybe one more issue cropping up with the new 1.1.4 release. Running the small RNA pipeline, I encountered this error when the pipeline was parsing the mirdeep2 results:

```
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/bcbio/srna/group.py", line 79, in run_align
    novel_db = mirdeep.run(data)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/bcbio/srna/mirdeep.py", line 49, in run
    novel_db = _parse_novel(out_file, dd.get_species(data[0][0]))
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/bcbio/srna/mirdeep.py", line 93, in _parse_novel
    if score < 1:
TypeError: '<' not supported between instances of 'str' and 'int'
```

This is happening in mirdeep.py:

https://github.com/bcbio/bcbio-nextgen/blob/08fdf3b06900ea0201217bfec8202b6ba5a87384/bcbio/srna/mirdeep.py#L93

I think it's parsing the mirdeep2 output that looks like this:

```
novel miRNAs predicted by miRDeep2
provisional id  miRDeep2 score  estimated probability that the miRNA candidate is a true positive       rfam alert      total read count        mature read count       loop read count star read count significant randfold p-value
    miRBase miRNA   example miRBase miRNA with the same seed        UCSC browser    NCBI blastn     consensus mature sequence       consensus star sequence consensus precursor sequence    precursor coordinate
chr17_29597     16085.5 52 +/- 17%      -       31553   31518   0       35      -       -       -       -       -       aaguuucucugaacguguagagc cuauacuuucagggaucau     cuauacuuucagggaucauuucuauaguguguuacuagagaaguuucucugaacguguagag
c chr17:18967382..18967445:-
chr17_28864     16085.5 52 +/- 17%      -       31553   31518   0       35      -       -       -       -       -       aaguuucucugaacguguagagc cuauacuuucagggaucau     cuauacuuucagggaucauuucuauaguguguuacuagagaaguuucucugaacguguagag
c chr17:18965228..18965291:+
```

This is getting parsed as a string in Python3:

```
>>> with open('tester.csv') as in_handle:
...     for line in in_handle:
...             cols = line.strip().split("\t")
...             print(cols)
...             print(type(cols[1]))
...
['chr17_29597', '16085.5', '52 +/- 17%', '-', '31553', '31518', '0', '35', '-', '-', '-', '-', '-', 'aaguuucucugaacguguagagc', 'cuauacuuucagggaucau', 'cuauacuuucagggaucauuucuauaguguguuacuagagaaguuucucugaacguguagagc', 'chr17:18967382..18967445:-']
<class 'str'>
```

Thanks for looking into this! cc @lpantano

**Comment by lpantano** [comment]
Hi,

thanks for looking into this!. I pushed a fix here: 9970d60a

I hope that fix it, let me know if other issues come up.

**Comment by rdocking** [comment]
Thanks for checking this out! The fix applied doesn't quite correct the issue:

```
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/bcbio/srna/mirdeep.py", line 49, in run
    novel_db = _parse_novel(out_file, dd.get_species(data[0][0]))
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/bcbio/srna/mirdeep.py", line 93, in _parse_novel
    if int(score) < 1:
ValueError: invalid literal for int() with base 10: '16085.5'
```

Maybe converting to a float first would resolve this?

```
>>> foo = '16085.5'
>>> type(foo)
<class 'str'>
>>> int(foo)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: '16085.5'
>>> float(foo)
16085.5
>>> int(float(foo))
16085
```

I'm not really sure what the mirdeep code is looking for here, so I'm not sure if this conversion is appropriate.

**Comment by lpantano** [comment]
Oh! thank you. I messed up.

I pushed another fix  582c8c2, i hope this works. I converted to float directly.

**Comment by rdocking** [comment]
Thanks :)

**Comment by rdocking** [comment]
Confirming that this is fixed now - thanks!
