### ISSUE TITLE
ftp issue w/broad or something else?

### ISSUE THREAD

**Issue by lento2002** [bcbio/bcbio-nextgen#2744]
[root@ip-10-0-0-44 config]# bcbio_nextgen.py upgrade --data --genomes hg38 --genomes mm10  --aligners hisat2 --aligners star --aligners bwa --cores 8

Not sure if this deterministically fails or not?  Perhaps it could fail more gracefully, if login is actually correct and there isn't an issue with broad-ftp....?

Running GGD recipe: hg38 1000g_omni_snps 20160105
--2019-04-04 11:01:28--  ftp://gsapubftp-anonymous:*password*@ftp.broadinstitute.org/bundle/hg38//1000G_omni2.5.hg38.vcf.gz.tbi
           => ‘variation/1000G_omni2.5.vcf.gz.tbi’
Resolving ftp.broadinstitute.org (ftp.broadinstitute.org)... 69.173.80.251
Connecting to ftp.broadinstitute.org (ftp.broadinstitute.org)|69.173.80.251|:21... connected.
Logging in as gsapubftp-anonymous ... 
Login incorrect.
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 221, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/mnt/fsx/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 105, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/mnt/fsx/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 347, in upgrade_bcbio_data
    args.cores, ["ggd", "s3", "raw"])
  File "/home/bcbioadmin/pact_175_rnaseq/config/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 350, in install_data_local
    _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
  File "/home/bcbioadmin/pact_175_rnaseq/config/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 476, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/home/bcbioadmin/pact_175_rnaseq/config/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 846, in _install_with_ggd
    ggd.install_recipe(os.getcwd(), env.system_install, recipe_file, gid)
  File "/home/bcbioadmin/pact_175_rnaseq/config/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"], system_install)
  File "/home/bcbioadmin/pact_175_rnaseq/config/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/mnt/fsx/share/bcbio/anaconda/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/mnt/fsx/share/bcbio/anaconda/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bash', '/mnt/fsx/share/bcbio/genomes/Hsapiens/hg38/txtmp/ggd-run.sh']' returned non-zero exit status 6.

**Comment by lento2002** [comment]
Seemingly intermittent

**Comment by chapmanb** [comment]
Sorry about these issues. This is an intermittent problem with the Broad FTP servers. They can report this when they get oversubscribed or are otherwise unhappy. Unfortunately just re-trying is the best approach we can offer right now. Hope a re-start gets it finished for you.
