### ISSUE TITLE
Issue with STDOUT when upgrading 1.1.4 with hg38 data

### ISSUE THREAD

**Issue by lento2002** [bcbio/bcbio-nextgen#2745]
Seeing the below when trying...  No idea why this may be happening earlier installs didnt seem to have this problem.  First time I've seen this error.  Any thoughts extremely appreciated.  Thanks!

bcbio_nextgen.py upgrade --data --genomes hg38 --genomes mm10  --aligners hisat2 --aligners star --aligners bwa --cores 8

TypeError: unsupported operand type(s) for +: 'range' and 'list'
2019/04/04 11:47:11 EOF
89.255.203.115
Connecting to nc.hartwigmedicalfoundation.nl (nc.hartwigmedicalfoundation.nl)|89.255.203.115|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7832443 (7.5M) [application/x-gzip]
Saving to: ‘STDOUT’

-                                                      0%[                                                                                                                      ]  40.00K   116KB/s    in 0.3s    

Cannot write to ‘-’ (Success).
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 221, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/mnt/fsx/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 105, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/mnt/fsx/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 347, in upgrade_bcbio_data
    args.cores, ["ggd", "s3", "raw"])
  File "/home/bcbioadmin/pact_175_rnaseq/config/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 350, in install_data_local
    _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
  File "/home/bcbioadmin/pact_175_rnaseq/config/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 476, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/home/bcbioadmin/pact_175_rnaseq/config/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 846, in _install_with_ggd
    ggd.install_recipe(os.getcwd(), env.system_install, recipe_file, gid)
  File "/home/bcbioadmin/pact_175_rnaseq/config/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"], system_install)
  File "/home/bcbioadmin/pact_175_rnaseq/config/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/mnt/fsx/share/bcbio/anaconda/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/mnt/fsx/share/bcbio/anaconda/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bash', '/mnt/fsx/share/bcbio/genomes/Hsapiens/hg38/txtmp/ggd-run.sh']' returned non-zero exit status 1.
[root@ip-10-0-0-44 config]# bcbio_nextgen.py upgrade --data --genomes hg38 --genomes mm10  --aligners hisat2 --aligners star --aligners bwa --cores 8

**Comment by chapmanb** [comment]
Thanks for this report and sorry about all the problems. This is due to python3 versus python2 incompatibilities and I pushed a fix to cloudbiolinux to avoid the issue. If you remove the cached cloudbiolinux:
```
rm -rf tmpbcbio-install
```
and re-run your upgrade command it should pick up where it left off and hopefully work cleanly now. Thanks again for all the patience working through these issues.
