### ISSUE TITLE
mirge2 in python2 env missing numpy

### ISSUE THREAD

**Issue by rdocking** [bcbio/bcbio-nextgen#2750]
Hi guys - 

  Another 1.1.4 issue that is hopefully simple to address. When running the small RNA pipeline, miRge2.0 crashes like so:

```
subprocess.CalledProcessError: Command 'set -o pipefail; /projects/rdocking_prj/software/bcbio-nextgen/tools/bin/miRge2.0 annotate -s /projects/karsanscratch/rdocking/KARSANBIO-1672_reprocessing/aml_pmp_mirna/work/bcbiotx/tmp1epobksk/sample_file.txt -o /projects/karsanscratch/rdocking/KARSANBIO-1672_reprocessing/aml_pmp_mirna/work/bcbiotx/tmp1epobksk -pb /projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/bin -lib /projects/rdocking_prj/software/tool_testing/mirge_libraries -sp human   -di -ai -gff
Traceback (most recent call last):
  File "/projects/rdocking_prj/software/bcbio-nextgen/tools/bin/miRge2.0", line 11, in <module>
    load_entry_point('mirge==2.0', 'console_scripts', 'miRge2.0')()
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/envs/python2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/envs/python2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/envs/python2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/envs/python2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/envs/python2/lib/python2.7/site-packages/mirge/__main__.py", line 37, in <module>
    from scipy.spatial import cKDTree
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/envs/python2/lib/python2.7/site-packages/scipy/__init__.py", line 62, in <module>
    from numpy import show_config as show_numpy_config
ImportError: No module named numpy
' returned non-zero exit status 1.
```

From what I can tell, numpy exists in the `python3` env, but not in the `python2` env. I'll see if I can confirm this by explicitly adding numpy to the python2 env.

**Comment by rdocking** [comment]
This seems to resolve the issue:

```
[2019-04-04 14:18:05]{rdocking@clingen01}/projects/rdocking_prj/software/bcbio-nextgen/data/> ./anaconda/bin/conda install --name python2 numpy
```

**Comment by lpantano** [comment]
Thanks!. I am updating mirge2 recipe so install numpy in the 2.7 env.

**Comment by lpantano** [comment]
Hi, can you tell  me the version of numpy you installed?

**Comment by lpantano** [comment]
Hi again, 

sorry, I don't know why is not installed because the conda recipe has numpy for this tool, so I am confused about this.

@chapmanb, do you know why installing numpy will resolve the issue, if it is a dependency of the tool anyway and it is in the bioconda recipe?

**Comment by rdocking** [comment]
```
[2019-04-08 15:34:51]{rdocking@clingen01}/projects/rdocking_prj/software/bcbio-nextgen/> ./data/anaconda/bin/conda list -n python2

# Name                    Version                   Build  Channel
...
numpy                     1.15.4          py27h8b7e671_1002    conda-forge

```

It's a possibility that my conda envs became messed up since I've been running lots of upgrades lately - this may be an issue specific to my install.

**Comment by roryk** [comment]
Sorry about this. We've been seeing some similar issues with numpy where an older version is getting installed, I haven't been able to figure out why it is happening. We should be on numpy 1.16+. 

Does ```bcbio_conda install -n python2 -c conda-forge -c bioconda 'numpy>=1.16' get an upgraded version of numpy in the `python2` environment? It might also fix the numpy is missing issue as well.

**Comment by chapmanb** [comment]
I'll echo Rory's suggestion to try and fix and resolve the issue. What ends up happening is that numpy gets installed with mirge2 thanks to the dependency specification, but then gets removed or downgraded due to conflicting dependencies at a different point during a later install/upgrade. Typically this is dependent on the composition of the environment as it gets upgraded over time so is a bit hard to pin down and fix. Not wanting to make you do a ton of diagnostic digging, applying Rory's approach should fix it and get you moving going forward. Hope this helps.

**Comment by rdocking** [comment]
Here's the package plan after I tried Rory's command:

```
[2019-04-09 08:39:29]{rdocking@clingen01}/projects/rdocking_prj/software/bcbio-nextgen/> bcbio_conda install -n python2 -c conda-forge -c bioconda 'numpy>=1.16'
WARNING: The conda.compat module is deprecated and will be removed in a future release.
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/envs/python2

  added / updated specs:
    - numpy[version='>=1.16']


The following packages will be UPDATED:

  blas                         pkgs/main::blas-1.0-openblas --> conda-forge::blas-2.4-openblas
  numpy                            1.15.4-py27h8b7e671_1002 --> 1.16.2-py27h8b7e671_1
  openblas                              0.3.3-h9ac9557_1001 --> 0.3.5-h9ac9557_1001

The following packages will be DOWNGRADED:

  libblas                           3.8.0-5_h6e990d7_netlib --> 3.8.0-4_openblas
  libcblas                          3.8.0-5_h6e990d7_netlib --> 3.8.0-4_openblas
  liblapack                         3.8.0-5_h6e990d7_netlib --> 3.8.0-4_openblas
  liblapacke                        3.8.0-5_h6e990d7_netlib --> 3.8.0-4_openblas
  optitype                                     1.3.2-py27_3 --> 1.3.2-py27_1
  phylowgs                          20181105-py27hc2ebfaa_0 --> 20150714-py27_1
```

I've been able to work around this, so it's not blocking me at all right now - thanks for looking into it!

**Comment by roryk** [comment]
Thanks, this should be fixed now!
