### ISSUE TITLE
Pandas dtype issue in sRNA pipeline

### ISSUE THREAD

**Issue by rdocking** [bcbio/bcbio-nextgen#2752]
Hi there - one more issue I've run into running the sRNA pipeline with the 1.1.4 series. I've made it up to the final QC step now, and hit this issue:

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/projects/rdocking_prj/software/bcbio-nextgen/tools/bin/bcbio_nextgen.py", line 238, in <module>
    main(**kwargs)
  File "/projects/rdocking_prj/software/bcbio-nextgen/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 349, in smallrnaseqpipeline
    samples = qcsummary.generate_parallel(samples, run_parallel)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/bcbio/pipeline/qcsummary.py", line 42, in generate_parallel
    qced = run_parallel("pipeline_summary", to_analyze)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 924, in __call__
    while self.dispatch_one_batch(iterator):
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 208, in pipeline_summary
    return qcsummary.pipeline_summary(*args)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/bcbio/pipeline/qcsummary.py", line 73, in pipeline_summary
    data["summary"] = _run_qc_tools(work_bam, work_data)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/bcbio/pipeline/qcsummary.py", line 165, in _run_qc_tools
    out = qc_fn(bam_file, data, cur_qc_dir)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/bcbio/qc/srna.py", line 17, in run
    m.update(_mirbase_stats(data, out_dir))
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/bcbio/qc/srna.py", line 27, in _mirbase_stats
    _get_stats_from_miraligner(mirbase_fn, out_file, "seqbuster")
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/bcbio/qc/srna.py", line 38, in _get_stats_from_miraligner
    na_values=["."])
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 490, in pandas._libs.parsers.TextReader.__cinit__
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/pandas/core/dtypes/common.py", line 2017, in pandas_dtype
    dtype))
TypeError: data type 'string' not understood
```

The error is being thrown from pandas, but the offending bcbio code is here:

```
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/bcbio/qc/srna.py", line 17, in run
    m.update(_mirbase_stats(data, out_dir))
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/bcbio/qc/srna.py", line 27, in _mirbase_stats
    _get_stats_from_miraligner(mirbase_fn, out_file, "seqbuster")
  File "/projects/rdocking_prj/software/bcbio-nextgen/data/anaconda/lib/python3.6/site-packages/bcbio/qc/srna.py", line 38, in _get_stats_from_miraligner
    na_values=["."])
```

Googling around, I found this SO answer that seems to point at a possible fix:

https://stackoverflow.com/questions/43652161/numpy-typeerror-data-type-string-not-understood

Looking at the code, my suspicion is that this:

https://github.com/bcbio/bcbio-nextgen/blob/ecd736a3beb0dcd6d0d2c1487acc49306d412d53/bcbio/qc/srna.py#L34-L38

Needs to be converted to use `'str'` instead of `'string'`. I'll try hot-fixing my local copy and see if that fixes it.

**Comment by rdocking** [comment]
Confirmed that the fix suggested above successfully works around the issue. Let me know if you'd like a pull request here or if it's simplest to fix directly.

**Comment by roryk** [comment]
Pull request would be great, I've been trying to get more folks to submit them when they fix stuff so they get credit and we get more people involved with developing!

**Comment by rdocking** [comment]
OK - will do!
