### ISSUE TITLE
Installation errors with latest development version

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#2758]
Hi,

When attempting to create a fresh bcbio install, I see the following:

```
Reading packages from /export/home/ncit/external/a.mizeranschi/bcbio_nextgen/tmpbcbio-install/cloudbiolinux/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml
Creating conda environment: python3
Creating conda environment: samtools0
Creating conda environment: dv
Creating conda environment: python2
Checking for problematic or migrated packages in default environment
# Installing into conda environment default: age-metasv, bamtools=2.4.0, bamutil, bbmap, bcbio-prioritize, bcbio-variation, bcbio-variation-recall, bcftools, bedtools=2.27.1, bio-vcf, biobambam, bowtie, bowtie2, break-point-inspector, bwa, bwakit, cage, cancerit-allelecount, chipseq-greylist, cnvkit, coincbc, cramtools, cufflinks, cyvcf2, deeptools, delly, duphold>=0.0.9, ensembl-vep=95.*, express, extract-sv-reads, fastp, fastqc>=0.11.8=1, fgbio, freebayes=1.1.0.46, gatk, gatk4, geneimpacts, genesplicer, gffcompare, goleft, grabix, gridss, gsort, gvcfgenotyper, h5py, hmftools-amber, hmftools-cobalt, hmftools-purple, hmmlearn, hts-nim-tools, htslib, impute2, kallisto>=0.43.1, kraken, lofreq, maxentscan, mbuffer, minimap2, mintmap, mirdeep2=2.0.0.7, mirtop, moreutils, mosdepth, multiqc, multiqc-bcbio, ngs-disambiguate, novoalign, octopus>=0.5.1b, oncofuse, parallel, pbgzip, perl-sanger-cgp-battenberg, picard, pindel, pizzly, preseq, pyloh, pysam>=0.14.0, pythonpy, qsignature, qualimap, rapmap, razers3=3.5.0, rtg-tools, sailfish, salmon, sambamba, samblaster, samtools, scalpel, seq2c, seqbuster, seqcluster, seqtk, sickle-trim, simple_sv_annotation, singlecell-barcodes, snap-aligner=1.0dev.97, snpeff=4.3.1t, solvebio, spades, star=2.6.1d, stringtie, subread, survivor, tdrmapper, tophat-recondition, ucsc-bedgraphtobigwig, ucsc-bedtobigbed, ucsc-bigbedinfo, ucsc-bigbedsummary, ucsc-bigbedtobed, ucsc-bigwiginfo, ucsc-bigwigsummary, ucsc-bigwigtobedgraph, ucsc-bigwigtowig, ucsc-fatotwobit, ucsc-gtftogenepred, ucsc-liftover, ucsc-wigtobigwig, vardict, vardict-java, variantbam, varscan, vcfanno, vcflib, verifybamid2, viennarna, vqsr_cnn, vt, wham, anaconda-client, awscli, bzip2, ncurses, nodejs, p7zip, readline, s3gof3r, xz, perl-app-cpanminus, perl-archive-extract, perl-archive-zip, perl-bio-db-sam, perl-cgi, perl-dbi, perl-encode-locale, perl-file-fetch, perl-file-sharedir, perl-file-sharedir-install, perl-ipc-system-simple, perl-lwp-protocol-https, perl-lwp-simple, perl-statistics-descriptive, perl-time-hires, perl-vcftools-vcf, bioconductor-annotate, bioconductor-biocgenerics, bioconductor-biocinstaller, bioconductor-biocstyle, bioconductor-biostrings, bioconductor-biovizbase, bioconductor-bsgenome.hsapiens.ucsc.hg19, bioconductor-bsgenome.hsapiens.ucsc.hg38, bioconductor-bubbletree, bioconductor-cn.mops, bioconductor-copynumber, bioconductor-degreport, bioconductor-deseq2, bioconductor-dexseq, bioconductor-dnacopy, bioconductor-genomeinfodbdata, bioconductor-genomicranges, bioconductor-iranges, bioconductor-limma, bioconductor-purecn, bioconductor-rtracklayer, bioconductor-titancna, r-base, r-basejump=0.7.2, r-bcbiornaseq>=0.2.7, r-cghflasso, r-chbutils, r-devtools, r-dplyr, r-dt, r-ggdendro, r-ggplot2, r-ggrepel>=0.7, r-gplots, r-gsalib, r-knitr, r-pheatmap, r-plyr, r-pscbs, r-reshape, r-rmarkdown, r-rsqlite, r-sleuth, r-snow, r-stringi, r-viridis>=0.5, r-wasabi, r=3.5.1, xorg-libxt
# Installing into conda environment dv: deepvariant
# Installing into conda environment python2: cpat, cutadapt=1.16, dkfz-bias-filter, gemini, gvcf-regions, hap.py, hisat2, htseq=0.9.1, lumpy-sv, macs2, manta, metasv, mirge, optitype, peddy, phylowgs, platypus-variant, sentieon, smcounter2, smoove, strelka, svtools, svtyper, theta2, tophat, umis, vawk, vcf2db
# Installing into conda environment python3: atropos, crossmap
# Installing into conda environment samtools0: ericscript
Creating manifest of installed packages in /export/home/ncit/external/a.mizeranschi/bcbio_nextgen/manifest
Third party tools upgrade complete.
Upgrading bcbio-nextgen data files
List of genomes to get (from the config file at '{'genomes': [{'dbkey': 'sacCer3', 'indexes': ['seq'], 'annotations': ['transcripts'], 'name': 'S cerevisiae (sacCer3)'}], 'genome_indexes': ['bwa', 'bowtie2', 'hisat2', 'star', 'rtg'], 'install_liftover': False, 'install_uniref': False}'): S cerevisiae (sacCer3)
Running GGD recipe: sacCer3 seq 94
Traceback (most recent call last):
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/bin/bcbio_nextgen.py", line 221, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 106, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 348, in upgrade_bcbio_data
    args.cores, ["ggd", "s3", "raw"])
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 350, in install_data_local
    _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 476, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 846, in _install_with_ggd
    ggd.install_recipe(os.getcwd(), env.system_install, recipe_file, gid)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"], system_install)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.7/subprocess.py", line 389, in check_output
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.7/subprocess.py", line 481, in run
subprocess.CalledProcessError: Command '['bash', '/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/genomes/Scerevisiae/sacCer3/txtmp/ggd-run.sh']' returned non-zero exit status 1.

```

What could be causing this?

**Comment by amizeranschi** [comment]
In addition to the stuff mentioned above, I also found a few other error messages during the install:

```
Traceback (most recent call last):
  File "sort-contigs.py", line 12, in <module>
    import StringIO
ModuleNotFoundError: No module named 'StringIO'
/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/package/shared.py:11: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  full_data = yaml.load(in_handle)
Upgrading bcbio
Upgrading bcbio-nextgen to latest development version
Upgrade of bcbio-nextgen development code complete.
```

This seems to lead to an incomplete bcbio install:

```
Installing isolated base python installation
Installing bcbio-nextgen
Installing data and third party dependencies
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 287, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/bin/bcbio_nextgen.py', 'upgrade', '-u', 'development', '--tooldir=/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/tools', '--genomes', 'sacCer3', '--datatarget', 'variation', '--datatarget', 'rnaseq', '--datatarget', 'smallrna', '--aligners', 'bwa', '--aligners', 'bowtie2', '--aligners', 'hisat2', '--aligners', 'star', '--isolate', '--cores', '32', '--data']' returned non-zero exit status 1
```

```
$ bcbio_nextgen.py
Traceback (most recent call last):
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/tools/bin/bcbio_nextgen.py", line 34, in <module>
    from bcbio.setpath import prepend_bcbiopath
ModuleNotFoundError: No module named 'bcbio'
```

There were also some instances of the following warning:

```
WARNING: The conda.compat module is deprecated and will be removed in a future release.
```

**Comment by chapmanb** [comment]
Thank you for the report and apologies about the installation issues. The first issue is due to python3 incompatibilities with a script used in preparing the sacCer3 genome. The latest cloudbiolinux uses bcbio's python2 environment python for this which should resolve it.

Sorry about the missing bcbio-nextgen module. We've had reports of this happening in some cases but I'm still not sure about the underlying cause. 

You should hopefully be able to fix and finish the install with:
```
rm -rf tmpbcbio-install
bcbio_conda install -c conda-forge -c bioconda -y 'bcbio-nextgen>1.1.4`
bcbio_nextgen.py upgrade -u development
bcbio_nextgen.py upgrade --tools --data
```
Hopefully this gets you a clean working bcbio installation going forward. Thank you again for the report.

**Comment by amizeranschi** [comment]
Thank you for your help, this got things working for me.
