### ISSUE TITLE
Is this py3 problem?

### ISSUE THREAD

**Issue by jessie-wangjie** [bcbio/bcbio-nextgen#2767]
I'm using svprioritize: cancer/civic in the config file.

Traceback (most recent call last):
  File "anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 52, in _setup_logging
    yield config
  File "anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 447, in detect_sv
    return ipython.zip_args(apply(structural.detect_sv, *args))
  File "anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 80, in apply
    return object(*args, **kwargs)
  File "anaconda/lib/python3.6/site-packages/bcbio/structural/__init__.py", line 205, in detect_sv
    for svdata in caller_fn(items):
  File "anaconda/lib/python3.6/site-packages/bcbio/structural/prioritize.py", line 37, in run
    for vcaller, vfile, post_prior_fn in inputs]
  File "anaconda/lib/python3.6/site-packages/bcbio/structural/prioritize.py", line 37, in <listcomp>
    for vcaller, vfile, post_prior_fn in inputs]
  File "anaconda/lib/python3.6/site-packages/bcbio/structural/prioritize.py", line 90, in _prioritize_vcf
    gene_list = _find_gene_list_from_bed(prioritize_by, out_file, data)
  File "anaconda/lib/python3.6/site-packages/bcbio/structural/prioritize.py", line 72, in _find_gene_list_from_bed
    for r in pybedtools.BedTool(bed_file):
  File "pybedtools/cbedtools.pyx", line 754, in pybedtools.cbedtools.IntervalIterator.__next__
  File "anaconda/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 749: ordinal not in range(128)

**Comment by chapmanb** [comment]
Jie;
Thank you for the report and apologies about the issues. This does look like another location where python3 is extra picky about encodings and is complaining about a non-ascii character in your input BED file. If you update to the latest development:
```
bcbio_nextgen.py upgrade -u development
```
it has a fix that will hopefully resolve the issue by correctly opening the input file with a `utf-8` encoding. Hope this gets your analysis finished cleanly, and please let us know if you continue to hit problems.
