### ISSUE TITLE
Version conflict with matplotlib

### ISSUE THREAD

**Issue by thommohr** [bcbio/bcbio-nextgen#2779]
Dear developers, 

the mutek2/freebayes pipeline throws the next error:
apparently matplotlib is too "modern"

[2019-04-13T04:36Z] Run multiqc
[2019-04-13T04:36Z] Traceback (most recent call last):
[2019-04-13T04:36Z]   File "/opt/bcbio/anaconda/lib/python3.6/site-packages/multiqc/utils/plugin_hooks.py", line 14, in <module>
[2019-04-13T04:36Z]     hook_functions[nicename].append(entry_point.load())
[2019-04-13T04:36Z] KeyError: 'before_config'
[2019-04-13T04:36Z] During handling of the above exception, another exception occurred:
[2019-04-13T04:36Z] Traceback (most recent call last):
[2019-04-13T04:36Z]   File "/opt/bcbio/anaconda/bin/multiqc", line 34, in <module>
[2019-04-13T04:36Z]     from multiqc.utils import report, plugin_hooks, megaqc, util_functions, lint_helpers, config, log
[2019-04-13T04:36Z]   File "/opt/bcbio/anaconda/lib/python3.6/site-packages/multiqc/utils/plugin_hooks.py", line 16, in <module>
[2019-04-13T04:36Z]     hook_functions[nicename] = [entry_point.load()]
[2019-04-13T04:36Z]   File "/opt/bcbio/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2433, in load
[2019-04-13T04:36Z]     self.require(*args, **kwargs)
[2019-04-13T04:36Z]   File "/opt/bcbio/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in require
[2019-04-13T04:36Z]     items = working_set.resolve(reqs, env, installer, extras=self.extras)
[2019-04-13T04:36Z]   File "/opt/bcbio/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
[2019-04-13T04:36Z]     raise VersionConflict(dist, req).with_context(dependent_req)
[2019-04-13T04:36Z] pkg_resources.ContextualVersionConflict: (matplotlib 3.0.3 (/srv/opt/bcbio/anaconda/lib/python3.6/site-packages), Requirement.parse('matplotlib<3.0.0,>=2.1.1'), {'multiqc'})
[2019-04-13T04:36Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; export PATH=/srv/opt/bcbio/anaconda/bin:"$PATH" && export LC_ALL=C.utf8 && export LANG=C.utf8 &&/opt/bcbio/anaconda/bin/multiqc -f -l /srv/workspace/rprojects/tmohr/MEDUNI/TUMOR/SKCM/SIBILIA-SKCM0010/project_hg38/work/qc/multiqc/list_files.txt  -o /srv/workspace/rprojects/tmohr/MEDUNI/TUMOR/SKCM/SIBILIA-SKCM0010/project_hg38/work/bcbiotx/tmpl0hg4h3k
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/multiqc/utils/plugin_hooks.py", line 14, in <module>
    hook_functions[nicename].append(entry_point.load())
KeyError: 'before_config'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/bin/multiqc", line 34, in <module>
    from multiqc.utils import report, plugin_hooks, megaqc, util_functions, lint_helpers, config, log
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/multiqc/utils/plugin_hooks.py", line 16, in <module>
    hook_functions[nicename] = [entry_point.load()]
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2433, in load
    self.require(*args, **kwargs)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (matplotlib 3.0.3 (/srv/opt/bcbio/anaconda/lib/python3.6/site-packages), Requirement.parse('matplotlib<3.0.0,>=2.1.1'), {'multiqc'})
' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/bcbio/bin/bcbio_nextgen.py", line 238, in <module>
    main(**kwargs)
  File "/opt/bcbio/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 190, in variant2pipeline
    samples = qcsummary.generate_parallel(samples, run_parallel)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/qcsummary.py", line 58, in generate_parallel
    return [[utils.to_single_data(d)] for d in run_parallel("multiqc_summary", [out])]
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 921, in __call__
    if self.dispatch_one_batch(iterator):
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 220, in multiqc_summary
    return multiqc.summary(*args)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/qc/multiqc.py", line 68, in summary
    do.run(cmd.format(**locals()), "Run multiqc")
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; export PATH=/srv/opt/bcbio/anaconda/bin:"$PATH" && export LC_ALL=C.utf8 && export LANG=C.utf8 &&/opt/bcbio/anaconda/bin/multiqc -f -l /srv/workspace/rprojects/tmohr/MEDUNI/TUMOR/SKCM/SIBILIA-SKCM0010/project_hg38/work/qc/multiqc/list_files.txt  -o /srv/workspace/rprojects/tmohr/MEDUNI/TUMOR/SKCM/SIBILIA-SKCM0010/project_hg38/work/bcbiotx/tmpl0hg4h3k
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/multiqc/utils/plugin_hooks.py", line 14, in <module>
    hook_functions[nicename].append(entry_point.load())
KeyError: 'before_config'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/bin/multiqc", line 34, in <module>
    from multiqc.utils import report, plugin_hooks, megaqc, util_functions, lint_helpers, config, log
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/multiqc/utils/plugin_hooks.py", line 16, in <module>
    hook_functions[nicename] = [entry_point.load()]
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2433, in load
    self.require(*args, **kwargs)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (matplotlib 3.0.3 (/srv/opt/bcbio/anaconda/lib/python3.6/site-packages), Requirement.parse('matplotlib<3.0.0,>=2.1.1'), {'multiqc'})
' returned non-zero exit status 1.

**Comment by roryk** [comment]
Thanks, it looks like multiqc only supports matplotlib < 3 since they don't want to drop python2 support and matplotlib >3 doesn't support python 2. If you do a `bcbio_conda install -c conda-forge matplotlib=2.2.3` you should get a matplotlib that works with multiqc.

**Comment by mbootwalla** [comment]
Hi @roryk I get a similar error right now with multiqc and matplotlib. The version of matplotlib that is available with my current bcbio install is 3.1.3 but multiqc requires <3.1.2 or >=2.1.1. I tried the bcbio_conda command that you listed above to install both version 3.1.1 and also tried installing version 2.2.3 but I still get an error from multiqc. Any suggestions as to what I can do to fix this. 

Here's the error that I'm getting -

CalledProcessError: Command 'set -o pipefail; export PATH=/gpfs/fs1/data/bcbio_data_1.1.9/anaconda/bin:"$PATH" && export LC_ALL=en_US.utf8 && export LANG=en_US.utf8 &&  /gpfs/fs1/data/bcbio_data_1.1.9/anaconda/bin/multiqc -f -l /gpfs/fs1/SES/Validation_HiSeq/180410_K00187_0035_AHMFM3BBXX/bcbio_20180410/work_dragen_prioritization/qc/multiqc/list_files.txt  -o /gpfs/fs1/SES/Validation_HiSeq/180410_K00187_0035_AHMFM3BBXX/bcbio_20180410/work_dragen_prioritization/bcbiotx/tmp1ovqjtj3

Traceback (most recent call last):
  File "/gpfs/fs1/data/bcbio_data_1.1.9/anaconda/lib/python3.6/site-packages/multiqc/utils/plugin_hooks.py", line 14, in <module>
    hook_functions[nicename].append(entry_point.load())
KeyError: 'before_config'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/gpfs/fs1/data/bcbio_data_1.1.9/anaconda/bin/multiqc", line 6, in <module>
    from multiqc.__main__ import multiqc
  File "/gpfs/fs1/data/bcbio_data_1.1.9/anaconda/lib/python3.6/site-packages/multiqc/__init__.py", line 16, in <module>
    from .multiqc import run
  File "/gpfs/fs1/data/bcbio_data_1.1.9/anaconda/lib/python3.6/site-packages/multiqc/multiqc.py", line 38, in <module>
    from .utils import report, plugin_hooks, megaqc, util_functions, lint_helpers, config, log
  File "/gpfs/fs1/data/bcbio_data_1.1.9/anaconda/lib/python3.6/site-packages/multiqc/utils/plugin_hooks.py", line 16, in <module>
    hook_functions[nicename] = [entry_point.load()]
  File "/gpfs/fs1/data/bcbio_data_1.1.9/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2442, in load
    self.require(*args, **kwargs)
  File "/gpfs/fs1/data/bcbio_data_1.1.9/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2465, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/gpfs/fs1/data/bcbio_data_1.1.9/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (matplotlib 3.1.3 (/gpfs/fs1/data/bcbio_data_1.1.9/anaconda/lib/python3.6/site-packages), Requirement.parse('matplotlib<3.1.2,>=2.1.1'), {'multiqc'})
' returned non-zero exit status 1.
