### ISSUE TITLE
Hang when running distributed

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2787]
When trying to running distributed with IPython, the processes hang at the time of cluster startup. Looking at the processes, I found

```
python -c from multiprocessing.semaphore_tracker import main;main(7)
```

And that hangs forever, preventing any cluster startup and thus any analysis. I can't seem to find where this is called though.

**Comment by roryk** [comment]
Hi @lbeltrame, huh. Does doing what is suggested here https://github.com/joblib/joblib/issues/841 let that command run if you do it?

**Comment by lbeltrame** [comment]
Thanks for the hint. This tells me that unfortunately that stuff was a red herring. The actual cause is (likely) the command spawned by ipython-cluster-helper, for example:

```
/opt/bcbio/anaconda/bin/python -E -c "import resource; cur_proc, max_proc = resource.getrlimit(resource.RLIMIT_NPROC); target_proc = min(max_proc, 10240) if max_proc > 0 else 10240; resource.setrlimit(resource.RLIMIT_NPROC, (max(cur_proc, target_proc), max_proc)); cur_hdls, max_hdls = resource.getrlimit(resource.RLIMIT_NOFILE); target_hdls = min(max_hdls, 10240) if max_hdls > 0 else 10240; resource.setrlimit(resource.RLIMIT_NOFILE, (max(cur_hdls, target_hdls), max_hdls)); from ipyparallel.apps.ipclusterapp import launch_new_instance; launch_new_instance()" start --IPClusterEngines.early_shutdown=240 --delay=10 --debug --n=10 --BcbioSLURMEngineSetLauncher.cores=8 --BcbioSLURMEngineSetLauncher.resources=\'mem=45G\' --BcbioSLURMEngineSetLauncher.mem=\'32.1\' --BcbioSLURMEngineSetLauncher.tag=\'\' --IPClusterStart.engine_launcher_class=cluster_helper.cluster.BcbioSLURMEngineSetLauncher --SLURMLauncher.queue=\'main\' --cluster-id=957bf26b-ca72-421b-9ea2-7051b3fc13b7 --BcbioSLURMControllerLauncher.mem=\'\' --BcbioSLURMEngineSetLauncher.tag=\'\' --BcbioSLURMControllerLauncher.tag=\'\' --BcbioSLURMControllerLauncher.cores=1 --BcbioSLURMControllerLauncher.resources=\'mem=45G\' --IPClusterStart.controller_launcher_class=cluster_helper.cluster.BcbioSLURMControllerLauncher --profile-dir=/mnt/lizardfs/data/bioinformatics/einar/sWGS7/work/log/ipython --BcbioSLURMEngineSetLauncher.machines=0 --BcbioSLURMEngineSetLauncher.timelimit=\'30-23:59:00\' --BcbioSLURMControllerLauncher.timelimit=\'30-23:59:00\' --BcbioSLURMEngineSetLauncher.account=imn --BcbioSLURMControllerLauncher.account=imn 
```
that exits immediately with exit code 1 and no output (the controller doesn't even leave a PID there): I tested it by launching it manually.

**Comment by roryk** [comment]
Thanks-- debugging the ipython-cluster-helper issues in bcbio is hard. You can figure out if it is bcbio related or ipython-cluster-helper related by trying to run the script here: https://github.com/roryk/ipython-cluster-helper/blob/master/example/example.py. If that works then the issue is somewhere in bcbio.

**Comment by lbeltrame** [comment]
Tested the script: it hangs with "0 engines running" when trying to use SLURM, and of course nothing is submitted.  It also hangs locally.  A strace shows that the controller somehow is not started (the JSON file is not created).

**Comment by roryk** [comment]
Huh-- if you do `sinfo -V` which verison of SLURM is running?

**Comment by roryk** [comment]
Also, is this a new scheduler? You've been running stuff for a while so it is weird this would crop up on the old scheduler.

**Comment by lbeltrame** [comment]
No, it's not new, I've tested this with 2 different schedulers on two different OSes (Ubuntu 14.04 and 18.04) that used to work with bcbio pre-py3 upgrade (which was a rough ride).

**Comment by roryk** [comment]
Thanks-- is it the same controller doesn't make the YAML file for each?

**Comment by roryk** [comment]
Wait, does it make the job submission scripts for the controller/engines?

**Comment by lbeltrame** [comment]
As I said earlier, no, the submissions aren't made.

`example.py` with `--local` also hangs with no engines running (in case it wasn't clear from above). Is the process launched in `_start()` for the cluster helper supposed to be long-lasting? Because it looks like it's exiting immediately.

**Comment by lbeltrame** [comment]
The log only reports 

```
2019-04-16 16:45:19.495 [IPClusterStart] Starting ipcluster with [daemon=True]
```

Then the process exits (I've also tried running it manually).

**Comment by roryk** [comment]
Gotcha-- if you run the example script with python2, does it also have the same problem?

**Comment by lbeltrame** [comment]
It does work, indeed. 

```
/opt/bcbio/anaconda/envs/python2/lib/python2.7/site-packages/ipyparallel/client/client.py:459: RuntimeWarning: 
            Controller appears to be listening on localhost, but not on this machine.
            If this is true, you should specify Client(...,sshserver='you@akane')
            or instruct your controller to listen on an external IP.
  RuntimeWarning)
3 Engines running
First check to see if we can talk to the engines.
This long computation that waits for 5 seconds before returning takes a while to run serially..
[('akane', 60), ('akane', 63), ('akane', 66), ('akane', 69), ('akane', 72), ('akane', 75), ('akane', 78), ('akane', 81), ('akane', 84), ('akane', 87), ('akane', 90), ('akane', 93), ('akane', 96), ('akane', 99), ('akane', 102), ('akane', 105), ('akane', 108), ('akane', 111), ('akane', 114), ('akane', 117)]
That took 20.0219638348 seconds.
Running it in parallel goes much faster...
```

**Comment by roryk** [comment]
Awesome, thanks for all the information, that helps narrow down the problem immensely.

**Comment by lbeltrame** [comment]
Anything I can try debugging? I found it of course when I had to run some important stuff. ;)

**Comment by roryk** [comment]
That warning isn't something that pops up for me. For example, with python3:

```
⌂3930% [rdk4@compute-a-16-37:/n/data1/cores/bcbio/rory_kirchner/dev/ipython-cluster-helper/example] [base] master+* ± python example.py --local
[ProfileCreate] Generating default config file: '/home/rdk4/.ipython/profile_eefad2ce-6056-11e9-af0a-149ecf441556/ipython_config.py'
[ProfileCreate] Generating default config file: '/home/rdk4/.ipython/profile_eefad2ce-6056-11e9-af0a-149ecf441556/ipython_kernel_config.py'
[ProfileCreate] Generating default config file: '/home/rdk4/.ipython/profile_eefad2ce-6056-11e9-af0a-149ecf441556/ipcontroller_config.py'
[ProfileCreate] Generating default config file: '/home/rdk4/.ipython/profile_eefad2ce-6056-11e9-af0a-149ecf441556/ipengine_config.py'
[ProfileCreate] Generating default config file: '/home/rdk4/.ipython/profile_eefad2ce-6056-11e9-af0a-149ecf441556/ipcluster_config.py'
2019-04-16 10:50:12.391 [IPClusterStart] IPYTHONDIR set to: /home/rdk4/.ipython
2019-04-16 10:50:12.392 [IPClusterStart] Using existing profile dir: '/home/rdk4/.ipython/profile_eefad2ce-6056-11e9-af0a-149ecf441556'
2019-04-16 10:50:12.392 [IPClusterStart] Searching path ['/n/data1/cores/bcbio/rory_kirchner/dev/ipython-cluster-helper/example', '/home/rdk4/.ipython/profile_eefad2ce-6056-11e9-af0a-149ecf441556', '/home/rdk4/local/share/bcbio/anaconda/etc/ipython', '/usr/local/etc/ipython', '/etc/ipython'] for config files
2019-04-16 10:50:12.393 [IPClusterStart] Attempting to load config file: ipython_config.py
2019-04-16 10:50:12.393 [IPClusterStart] Looking for ipython_config in /etc/ipython
2019-04-16 10:50:12.393 [IPClusterStart] Looking for ipython_config in /usr/local/etc/ipython
2019-04-16 10:50:12.393 [IPClusterStart] Looking for ipython_config in /home/rdk4/local/share/bcbio/anaconda/etc/ipython
2019-04-16 10:50:12.393 [IPClusterStart] Looking for ipython_config in /home/rdk4/.ipython/profile_eefad2ce-6056-11e9-af0a-149ecf441556
2019-04-16 10:50:12.394 [IPClusterStart] Loaded config file: /home/rdk4/.ipython/profile_eefad2ce-6056-11e9-af0a-149ecf441556/ipython_config.py
2019-04-16 10:50:12.394 [IPClusterStart] Looking for ipython_config in /n/data1/cores/bcbio/rory_kirchner/dev/ipython-cluster-helper/example
2019-04-16 10:50:12.395 [IPClusterStart] Attempting to load config file: ipcluster_adb417b5_08eb_476b_9063_d1869c9c5151_config.py
2019-04-16 10:50:12.395 [IPClusterStart] Looking for ipcontroller_config in /etc/ipython
2019-04-16 10:50:12.395 [IPClusterStart] Looking for ipcontroller_config in /usr/local/etc/ipython
2019-04-16 10:50:12.395 [IPClusterStart] Looking for ipcontroller_config in /home/rdk4/local/share/bcbio/anaconda/etc/ipython
2019-04-16 10:50:12.396 [IPClusterStart] Looking for ipcontroller_config in /home/rdk4/.ipython/profile_eefad2ce-6056-11e9-af0a-149ecf441556
2019-04-16 10:50:12.396 [IPClusterStart] Loaded config file: /home/rdk4/.ipython/profile_eefad2ce-6056-11e9-af0a-149ecf441556/ipcontroller_config.py
2019-04-16 10:50:12.396 [IPClusterStart] Looking for ipcontroller_config in /n/data1/cores/bcbio/rory_kirchner/dev/ipython-cluster-helper/example
2019-04-16 10:50:12.397 [IPClusterStart] Attempting to load config file: ipcluster_adb417b5_08eb_476b_9063_d1869c9c5151_config.py
2019-04-16 10:50:12.397 [IPClusterStart] Looking for ipengine_config in /etc/ipython
2019-04-16 10:50:12.397 [IPClusterStart] Looking for ipengine_config in /usr/local/etc/ipython
2019-04-16 10:50:12.397 [IPClusterStart] Looking for ipengine_config in /home/rdk4/local/share/bcbio/anaconda/etc/ipython
2019-04-16 10:50:12.397 [IPClusterStart] Looking for ipengine_config in /home/rdk4/.ipython/profile_eefad2ce-6056-11e9-af0a-149ecf441556
2019-04-16 10:50:12.398 [IPClusterStart] Loaded config file: /home/rdk4/.ipython/profile_eefad2ce-6056-11e9-af0a-149ecf441556/ipengine_config.py
2019-04-16 10:50:12.398 [IPClusterStart] Looking for ipengine_config in /n/data1/cores/bcbio/rory_kirchner/dev/ipython-cluster-helper/example
2019-04-16 10:50:12.399 [IPClusterStart] Attempting to load config file: ipcluster_adb417b5_08eb_476b_9063_d1869c9c5151_config.py
2019-04-16 10:50:12.399 [IPClusterStart] Looking for ipcluster_config in /etc/ipython
2019-04-16 10:50:12.399 [IPClusterStart] Looking for ipcluster_config in /usr/local/etc/ipython
2019-04-16 10:50:12.399 [IPClusterStart] Looking for ipcluster_config in /home/rdk4/local/share/bcbio/anaconda/etc/ipython
2019-04-16 10:50:12.399 [IPClusterStart] Looking for ipcluster_config in /home/rdk4/.ipython/profile_eefad2ce-6056-11e9-af0a-149ecf441556
2019-04-16 10:50:12.400 [IPClusterStart] Loaded config file: /home/rdk4/.ipython/profile_eefad2ce-6056-11e9-af0a-149ecf441556/ipcluster_config.py
2019-04-16 10:50:12.400 [IPClusterStart] Looking for ipcluster_config in /n/data1/cores/bcbio/rory_kirchner/dev/ipython-cluster-helper/example
3 Engines running
First check to see if we can talk to the engines.
This long computation that waits for 5 seconds before returning takes a while to run serially..
[('compute-a-16-37.o2.rc.hms.harvard.edu', 60), ('compute-a-16-37.o2.rc.hms.harvard.edu', 63), ('compute-a-16-37.o2.rc.hms.harvard.edu', 66), ('compute-a-16-37.o2.rc.hms.harvard.edu', 69), ('compute-a-16-37.o2.rc.hms.harvard.edu', 72), ('compute-a-16-37.o2.rc.hms.harvard.edu', 75), ('compute-a-16-37.o2.rc.hms.harvard.edu', 78), ('compute-a-16-37.o2.rc.hms.harvard.edu', 81), ('compute-a-16-37.o2.rc.hms.harvard.edu', 84), ('compute-a-16-37.o2.rc.hms.harvard.edu', 87), ('compute-a-16-37.o2.rc.hms.harvard.edu', 90), ('compute-a-16-37.o2.rc.hms.harvard.edu', 93), ('compute-a-16-37.o2.rc.hms.harvard.edu', 96), ('compute-a-16-37.o2.rc.hms.harvard.edu', 99), ('compute-a-16-37.o2.rc.hms.harvard.edu', 102), ('compute-a-16-37.o2.rc.hms.harvard.edu', 105), ('compute-a-16-37.o2.rc.hms.harvard.edu', 108), ('compute-a-16-37.o2.rc.hms.harvard.edu', 111), ('compute-a-16-37.o2.rc.hms.harvard.edu', 114), ('compute-a-16-37.o2.rc.hms.harvard.edu', 117)]
That took 20.022165298461914 seconds.
Running it in parallel goes much faster...
[('compute-a-16-37.o2.rc.hms.harvard.edu', 60), ('compute-a-16-37.o2.rc.hms.harvard.edu', 63), ('compute-a-16-37.o2.rc.hms.harvard.edu', 66), ('compute-a-16-37.o2.rc.hms.harvard.edu', 69), ('compute-a-16-37.o2.rc.hms.harvard.edu', 72), ('compute-a-16-37.o2.rc.hms.harvard.edu', 75), ('compute-a-16-37.o2.rc.hms.harvard.edu', 78), ('compute-a-16-37.o2.rc.hms.harvard.edu', 81), ('compute-a-16-37.o2.rc.hms.harvard.edu', 84), ('compute-a-16-37.o2.rc.hms.harvard.edu', 87), ('compute-a-16-37.o2.rc.hms.harvard.edu', 90), ('compute-a-16-37.o2.rc.hms.harvard.edu', 93), ('compute-a-16-37.o2.rc.hms.harvard.edu', 96), ('compute-a-16-37.o2.rc.hms.harvard.edu', 99), ('compute-a-16-37.o2.rc.hms.harvard.edu', 102), ('compute-a-16-37.o2.rc.hms.harvard.edu', 105), ('compute-a-16-37.o2.rc.hms.harvard.edu', 108), ('compute-a-16-37.o2.rc.hms.harvard.edu', 111), ('compute-a-16-37.o2.rc.hms.harvard.edu', 114), ('compute-a-16-37.o2.rc.hms.harvard.edu', 117)]
That took 7.263223648071289 seconds.
Sending a shutdown signal to the controller and engines.
2019-04-16 10:50:56.123 [IPClusterStop] Stopping cluster [pid=149695] with [signal=<Signals.SIGINT: 2>]
```
I'm curious where the daemon=True message is coming from that you are seeing, I don't see that when I run it.

**Comment by roryk** [comment]
What version of ipython is installed? 
```
ipython --version
6.5.0
ipcontroller --version
6.2.3
```

**Comment by lbeltrame** [comment]
That warning is probably due to the way the hostname is configured, another possible red herring, I only saw it when running it on py2, I think with py3 doesn't go as far.

```
ipython --version
7.4.0

ipcontroller --version
6.2.3
```

I'm starting to think it has to do with the version of IPython? I had a lot of trouble upgrading bcbio, I wonder if something broke in the way.

**Comment by roryk** [comment]
It could be-- we have SLURM as the scheduler or the main work compute so it should be working, does downgrading ipython help any? Sorry to be taking shots in the dark, it's tough to do this type of debugging over github.

**Comment by lbeltrame** [comment]
That's what I'm trying right now (conda dependency resolution is super slow though).

**Comment by roryk** [comment]
Great, sorry for the problems, the migration to python3 has been painful but hopefully we're getting to the end of the problems. We are kind of forced to do it because there are a bunch of libraries sunsetting python2 support.

**Comment by lbeltrame** [comment]
That doesn't work, unfortunately. Still "0 engines running".

**Comment by roryk** [comment]
Thanks, it still doesn't make the SLURM job submission files at all? The local running still hangs and does nothing?

**Comment by lbeltrame** [comment]
Correct. That's what happens (tested on two different machines to make sure things aren't a local issue).

**Comment by roryk** [comment]
Thanks-- do you think you could create a clean environment that just has ipython-cluster-helper in it and test? If you do `conda create -n ipc -c bioconda python=3 ipython-cluster-helper` that should get you an environment that has python3 and ipython-cluster-helper and nothing else to try to further isolate the problem.

**Comment by lbeltrame** [comment]
I'm trying this, probably will follow up tomorrow if I don't finish.

**Comment by roryk** [comment]
Thanks so much, sorry that this sucks, I hope we can figure out what is going on.

**Comment by lbeltrame** [comment]
Looks like it works in an isolated environment but not in my regular one. I wonder what's the difference.

**Comment by lbeltrame** [comment]
It looks there's a swallowed exception. If I run the controller interactively (`daemonize` set to `False`):

```
/opt/bcbio/anaconda/bin/python -E -c "import resource; cur_proc, max_proc = resource.getrlimit(resource.RLIMIT_NPROC); target_proc = min(max_proc, 10240) if max_proc > 0 else 10240; resource.setrlimit(resource.RLIMIT_NPROC, (max(cur_proc, target_proc), max_proc)); cur_hdls, max_hdls = resource.getrlimit(resource.RLIMIT_NOFILE); target_hdls = min(max_hdls, 10240) if max_hdls > 0 else 10240; resource.setrlimit(resource.RLIMIT_NOFILE, (max(cur_hdls, target_hdls), max_hdls)); from ipyparallel.apps.ipclusterapp import launch_new_instance; launch_new_instance()" start --daemonize=False --log-to-file --debug --cluster-id=28640d42-0446-4f2e-b09b-bc2a01f32923 --n=3 --profile=fe5c4af0-6091-11e9-90dc-00e081c674ed
```

```
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/ipyparallel/apps/ipclusterapp.py", line 668, in start
    return self.subapp.start()
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/ipyparallel/apps/ipclusterapp.py", line 584, in start
    self.loop.add_callback(start)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/traitlets/traitlets.py", line 591, in _validate
    value = self.validate(obj, value)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/traitlets/traitlets.py", line 1677, in validate
    self.error(obj, value)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/traitlets/traitlets.py", line 1524, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'loop' trait of an IPClusterStart instance must be an IOLoop, but a value of class 'zmq.eventloop.ioloop.ZMQIOLoop' (i.e. <zmq.eventloop.ioloop.ZMQIOLoop object at 0x7f0f68d46da0>) was specified.
```

**Comment by roryk** [comment]
Thanks, do any tips from this thread help? https://github.com/jupyter/jupyter/issues/334

**Comment by roryk** [comment]
Would be good to compare the versions of the packages mentioned in that thread with the ones in the bcbio environment, it might be that one or more of them are mismatched.

**Comment by lbeltrame** [comment]
I'm currently trying to put packages at the same version as in the test environment:

```
conda install -c conda-forge -c bioconda python=3 traitlets==4.3.2=py36_0 ipykernel==5.1.0=py36h39e3cac_02 ipyparallel==6.2.3=py36_0 pyzmq=18.0.0=py36he6710b0_0
```

**Comment by lbeltrame** [comment]
This looks like it works (the example.py program does not work with the scheduler, but bcbio is now spawning controllers and engines, and tasks are actually carried out). I'll keep this open to make sure everything is OK for a bit, though.

**Comment by roryk** [comment]
Huh, confusing that the example program doesn't work.

**Comment by lbeltrame** [comment]
The pipeline did a full run as advertised, so this indeed was a bad case of version mismatch (why ipcluster would fail silently without any error when daemonizing is weird, though). Closing.

**Comment by roryk** [comment]
Thanks-- did you figure out which version mismatch was causing the problem? I can update the bioconda recipe to reflect it if we can figure out what it is.

**Comment by lbeltrame** [comment]
Honestly, I didn't as I had to put things in working order ASAP. That said, the version which jumped was pyzmq, up to 18.0.0 (that was 16.something in the broken environment).

**Comment by roryk** [comment]
Thanks! Glad you got it worked out.
