### ISSUE TITLE
align rnaseq with umi 

### ISSUE THREAD

**Issue by dauss75** [bcbio/bcbio-nextgen#2794]
Hello,
I am ultimately trying to detect gene fusion, but have got an error from alignment. 
The UMI is added to fastq read name as UMI_XXXXXXXX where X is a base sequence.

To simplify the problem, I commented out everything except the alignment as follows:

- algorithm:
    aligner: star
    mark_duplicates: true
    umi_type: fastq_name
    transcriptome_align: True
    quality_format: standard

The error looks like with UMI, but I am not sure what exactly is happening.

[2019-04-18T20:50Z] Index BAM file: SeraseqDNARNA2.bam
Traceback (most recent call last):
  File "/isilon/prod/apps/bcbio/bin/bcbio_nextgen.py", line 238, in <module>
    main(**kwargs)
  File "/isilon/prod/apps/bcbio/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/isilon/prod/apps/bcbio-data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/isilon/prod/apps/bcbio-data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/isilon/prod/apps/bcbio-data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 245, in rnaseqpipeline
    samples = run_parallel("process_alignment", samples)
  File "/isilon/prod/apps/bcbio-data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/isilon/prod/apps/bcbio-data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/isilon/prod/apps/bcbio-data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 917, in __call__
    if self.dispatch_one_batch(iterator):
  File "/isilon/prod/apps/bcbio-data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/isilon/prod/apps/bcbio-data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/isilon/prod/apps/bcbio-data/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/isilon/prod/apps/bcbio-data/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "/isilon/prod/apps/bcbio-data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/isilon/prod/apps/bcbio-data/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 54, in wrapper
    return f(*args, **kwargs)
  File "/isilon/prod/apps/bcbio-data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 119, in process_alignment
    return sample.process_alignment(*args)
  File "/isilon/prod/apps/bcbio-data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 132, in process_alignment
    f1, f2, avg_cov = postalign.umi_consensus(data)
  File "/isilon/prod/apps/bcbio-data/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/postalign.py", line 190, in umi_consensus
    umi_method, umi_tag = _check_umi_type(align_bam)
TypeError: 'NoneType' object is not iterable

**Comment by dauss75** [comment]
I looked a little more around the problem.

In postalign.py, it looks for tags --  "RX", "XC", but when I look at the bam I got from star aligner, I don't see any of these tags.  

NDX550138:22:HHMY2AFXY:1:21208:18955:12784:UMI_GGTGGGATAG       163     1       137797  60      17S77M1I44M     =       138002  318     ACGAATATACTCATTTTTTGGGGAAGCTGTGGACCGACCAAGGCCGCCAGGAGATGGGTAGGCACTGAGTCCAAAAAGGTTGTTG
AGAGGCAGGAAATCGGGCCTGGAGACCCAACCAGGAAGAAGAGCTGGGCCCGGA  EEE/EA/E//6A/EEEEEEEEAEEEEEEEEE6/EEEEEE6AEEEEEEEEAE/EEEE/EE/EAEEEEE/EEEEE6EAEEEEAEEEE/E//<E////A/6E<EAEEEEE6EAEE<//E/AA/</E//<<EEEEEAAEEEEE     NH:i:1  HI:i:1  NM:i:
3       MD:Z:3A54G62    AS:i:222        RG:Z:SeraseqDNARNA2

Could you kindly let me know what I am missing here?

Thanks,
Segun

**Comment by dauss75** [comment]
OK.  I figured I had to configure better in the yaml file and it seems working now.

**Comment by roryk** [comment]
Sorry, we don't support standard RNA-seq analyses with UMI-- we haven't seen any protocols at all where full-length transcripts are being used with UMI. 3' DGE data and single-cell RNA-seq both work with fragments of the full RNA, so all of the downstream quantification tools will fail since they are expecting full length transcripts. 

See https://github.com/bcbio/bcbio-nextgen/issues/2070 for some more discussion as well. You might get data back from the standard RNA-seq pipeline, but it will not be taking the UMI into account so it will be incorrect.

**Comment by roryk** [comment]
We also don't support fusion calling with tag based data.--  you are probably not going to be able to find fusions since the tag data only hits a small part of the transcript. If you have tag-based data I think what you are asking to do is probably a waste of time, you'd need full length transcript data to detect fusions.

**Comment by dauss75** [comment]
Thanks Rory.
That's very interesting.  My interest is with only fusion detection and my colleague has his own pipeline outside of bcbio and uses UMIs to collapse using fgbio (although I need to check how my colleague's pipeline works).  For now, I will need to do my homework.  Thanks anyway for the comments!

**Comment by roryk** [comment]
Heya, if the FASTQ files you are putting in already have the duplicate
reads for each UMI removed then bcbio will work fine running normally—
essentially the UMI is already taken into account so you can ignore it. So
if you can get your FASTQ files into that state then you are all set.
