### ISSUE TITLE
'<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by jxshi** [bcbio/bcbio-nextgen#2795]
Hi,

Fresh install of mm10 and rn6 reference genome in bcbio-nextgen encountered the following error.
This is the command that I used:
```
python bcbio_nextgen_install.py /home/zdjzyx01/local/share/bcbio --tooldir=/home/zdjzyx01/local  --genomes mm10 --genomes rn6 --aligners bwa --aligners bowtie2 --aligners star --aligners bowtie --aligners hisat2
```
This is the error message:
```
List of genomes to get (from the config file at '{'genomes': [{'dbkey': 'mm10', 'name': 'Mouse (mm10)', 'indexes': ['twobit'], 'annotations': ['problem_regions', 'dbsnp', 'vcfanno', 'transcripts', 'rmsk', 'mirbase']}, {'dbkey': 'rn6', 'name': 'Rat (rn6)', 'indexes': ['seq', 'twobit'], 'annotations': ['transcripts', 'mirbase']}], 'genome_indexes': ['bwa', 'bowtie2', 'star', 'bowtie', 'hisat2', 'rtg'], 'install_liftover': False, 'install_uniref': False}'): Mouse (mm10), Rat (rn6)
Moving on to next genome prep method after trying ggd
GGD recipe not available for mm10 seq
Downloading genome from s3: mm10 seq
Moving on to next genome prep method after trying s3
No pre-computed indices for mm10 seq
Preparing genome mm10 with index seq
Moving on to next genome prep method after trying raw
'<' not supported between instances of 'str' and 'int'
Traceback (most recent call last):
  File "/home/zdjzyx01/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 221, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/home/zdjzyx01/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 106, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/home/zdjzyx01/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 348, in upgrade_bcbio_data
    args.cores, ["ggd", "s3", "raw"])
  File "/public/home/zdjzyx01/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 350, in install_data_local
    _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
  File "/public/home/zdjzyx01/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 491, in _prep_genomes
    .format(idx, gid, last_exc))
OSError: Could not prepare index seq for mm10 by any method
Traceback (most recent call last):
  File "/public/home/zdjzyx01/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 476, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/public/home/zdjzyx01/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 514, in _prep_raw_index
    ref_file = _get_ref_seq(manager)
  File "/public/home/zdjzyx01/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 506, in _get_ref_seq
    ref_file, base_zips = manager.download(seq_dir)
  File "/public/home/zdjzyx01/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 126, in download
    result = self._karyotype_sort(result)
  File "/public/home/zdjzyx01/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 82, in _karyotype_sort
    return sorted(xs, key=karyotype_keyfn)
TypeError: '<' not supported between instances of 'str' and 'int'

Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 288, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 45, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/home/zdjzyx01/local/share/bcbio/anaconda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/zdjzyx01/local/share/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/home/zdjzyx01/local', '--genomes', 'mm10', '--genomes', 'rn6', '--aligners', 'bwa', '--aligners', 'bowtie2', '--aligners', 'star', '--aligners', 'bowtie', '--aligners', 'hisat2', '--data']' returned non-zero exit status 1.
```
Please let me know if you need additional information.

Thank you in advance!

Jianxiang

**Comment by chapmanb** [comment]
Jianxiang;
Thanks much for the report and sorry about the issue. This is due to the transition to python 3, which is stricter about comparisons and sorting in the code used for these genomes. We pushed a fix to cloudbiolinux so if you remove the cached one on your system (`rm -rf tmpbcbio-install`) and re-run the upgrade/install in place it should pick up where it left off and hopefully work cleanly for you. Please let us know if you run into any other issues.

**Comment by jxshi** [comment]
Awsome! Thank you very much for your quick fix.

Cheers!

Jianxiang

**Comment by erinijapranckeviciene** [comment]
Hi @chapmanb,

First of all thank you and team for developing this great tool bcbio_nextgen !

Although this issue is closed, I came across same situation as @jxshi 

 TypeError: '<' not supported between instances of 'str' and 'int' 

but in different place. Output is below. 
>
[2019-07-30T12:27Z] vcfanno.go:115: found 1 sources from 1 files
[2019-07-30T12:27Z] vcfanno.go:143: using 2 worker threads to decompress query file
[2019-07-30T12:27Z] vcfanno.go:187: Info Error: rs_ids not found in INFO >> this error/warning may occur many times. reporting once here...
[2019-07-30T12:27Z] vcfanno.go:187: Info Error: rs_ids not found in INFO >> this error/warning may occur many times. reporting once here...
[2019-07-30T12:27Z] vcfanno.go:241: annotated 8920 variants in 6.87 seconds (1298.8 / second)
[2019-07-30T12:27Z] tabix index batch1-vepeffects-annotated.vcf.gz
[2019-07-30T12:27Z] Filtering for NA12878-1_S3, gatk-haplotype
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 204, in postprocess_variants
    return variation.postprocess_variants(*args)
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/variation.py", line 114, in postprocess_variants
    data, orig_items)
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/genotype.py", line 42, in variant_filtration
    return gatkfilter.run(call_file, ref_file, vrn_files, data)
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/gatkfilter.py", line 19, in run
    if includes_missingalt(data):
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/gatkfilter.py", line 274, in includes_missingalt
    return version >= MISSINGALT_VERSION
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/distutils/version.py", line 70, in __ge__
    c = self._cmp(other)
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/projects/analysis/bcbio/anaconda/bin/bcbio_nextgen.py", line 238, in <module>
    main(**kwargs)
  File "/projects/analysis/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 164, in variant2pipeline
    samples = run_parallel("postprocess_variants", samples)
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
TypeError: '<' not supported between instances of 'str' and 'int'

It seems happening in
 `/projects/analysis/bcbio/anaconda/lib/python3.6/distutils/version.py` line 337 

> 
 326	
   327	    def __repr__ (self):
   328	        return "LooseVersion ('%s')" % str(self)
   329	
   330	
   331	    def _cmp (self, other):
   332	        if isinstance(other, str):
   333	            other = LooseVersion(other)
   334	
   335	        if self.version == other.version:
   336	            return 0
   **337	        if self.version < other.version:**
   338	            return -1
   339	        if self.version > other.version:
   340	            return 1
   341	
   342	
   343	# end class LooseVersion

**Comment by roryk** [comment]
Thanks for opening the issue and extra thanks for figuring out and posting the solution! Were you trying to run with GATK3, or is this a GATK4 run? We should be catching if GATK is not installed, so I'm confused how this slipped by.

**Comment by erinijapranckeviciene** [comment]
This is GATK3 run. Although I posted an update, still something is not right. That test run completed, but the second run crashed.  I am a bit confused because: 
1) On the clean system I installed GATK without registering: `bcbio_nextgen.py upgrade --tools --toolplus gatk=/path/to/gatk/GenomeAnalysisTK.jar`
2) My input was BAM  and the run completed. 
3) Second run with input fastq  gave the message that I posted. I traced some  outputs in  and there was a message "did you register gatk3?"  So I register like this `gatk3-register /path/to/GenomeAnalysisTK.tar.bz2` and after that the run finished, so I posted an update. 
4) I started a new run and now I am experiencing issues again:

[2019-07-30T17:36Z] Aligning lane NA12878-1_S3 with bwa aligner
[2019-07-30T17:36Z] Timing: callable regions
[2019-07-30T17:36Z] multiprocessing: prep_samples
[2019-07-30T17:36Z] multiprocessing: postprocess_alignment
[2019-07-30T17:36Z] NA12878-1_S3: Assigned coverage as 'regional' with 0.2% genome coverage and 0.0% offtarget coverage
[2019-07-30T17:36Z] Prepare BQSR tables with GATK: NA12878-1_S3 
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 148, in postprocess_alignment
    return sample.postprocess_alignment(*args)
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sample.py", line 263, in postprocess_alignment
    data = recalibrate.prep_recal(data)
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/recalibrate.py", line 35, in prep_recal
    data)
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/recalibrate.py", line 128, in _gatk_base_recalibrator
    parallel_gc=True)
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/broad/__init__.py", line 359, in run_gatk
    cl = self.cl_gatk(params, tmp_dir, memscale=memscale, parallel_gc=parallel_gc)
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/broad/__init__.py", line 280, in cl_gatk
    if self._has_gatk_conda_wrapper():
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/broad/__init__.py", line 265, in _has_gatk_conda_wrapper
    print( stdout.find("GATK jar file not found") )
TypeError: a bytes-like object is required, not 'str'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/projects/analysis/bcbio/anaconda/bin/bcbio_nextgen.py", line 238, in <module>
    main(**kwargs)
  File "/projects/analysis/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 136, in variant2pipeline
    samples = run_parallel("postprocess_alignment", samples)
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/projects/analysis/bcbio/anaconda/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
TypeError: a bytes-like object is required, not 'str'


If I wished to unregister GATK3  -  and get beck to the initial state how can I do that?   

Now I am running  NA12878 chr22 to make sure that config that I need will complete. Perhaps I can share my experiments if that would help.

**Comment by chapmanb** [comment]
Thanks much for the report and fix that worked for your case. This should be fixed in the latest development:

https://github.com/bcbio/bcbio-nextgen/commit/c0c144bb967b965fd31ace6c17108fd4e87ca80a

but has not yet made it into a stable release. If you update with:
```
bcbio_nextgen.py upgrade -u development
```
it should get you a version that works cleanly with GATK 3. Hope this gets everything working for you.

**Comment by erinijapranckeviciene** [comment]
Thank you very much for the  fixes in -u development option !
