### ISSUE TITLE
issues with launching jobs with LSF

### ISSUE THREAD

**Issue by sudeshna-das** [bcbio/bcbio-nextgen#2803]
I am trying to run RNA-Seq analysis with bcbio using the following configuration file:

-----
#!/bin/bash

#BSUB -u nobody
#BSUB -o submit_bcbio.%J.out
#BSUB -J submit_bcbio.sh
#BSUB -q big
#BSUB -R rusage[mem=8000]

module load python/2.7.3
module load bcbio-nextgen/1.0.4

export PATH=/data/mindinformatics/software/src/hisat/hisat2-2.1.0:$PATH
export PATH=/data/mindinformatics/software/bin:/apps/lib-osver/bcbio/1.0.4/anaconda/bin:$PATH

bcbio_nextgen.py ../config/alignment.yaml \
    -n 8 -t ipython -s lsf -q big -r t=4-00:00 --timeout 2000

After a few hours I get "**0 Engines running**" multiple times and here is the error log:

[sd587@eris1n2 log]$ more ipcluster-076e082f-6759-4e14-83ac-781183d7c064-3805.log 
2019-04-27 17:08:49.710 [IPClusterStart] WARNING | Config option `mem` not recognized by `BcbioLSFControllerLauncher`.
2019-04-27 17:08:49.715 [IPClusterStart] Starting ipcluster with [daemon=True]
2019-04-27 17:08:49.722 [IPClusterStart] Creating pid file: /data/mindinformatics/projects/DGE/alignment/work/log/ipython/pid/
ipcluster-076e082f-6759-4e14-83ac-781183d7c064.pid
2019-04-27 17:08:49.724 [IPClusterStart] Starting Controller with cluster_helper.cluster.BcbioLSFControllerLauncher
2019-04-27 17:08:49.725 [IPClusterStart] adding PBS queue settings to batch script
2019-04-27 17:08:49.725 [IPClusterStart] adding job array settings to batch script
2019-04-27 17:08:49.726 [IPClusterStart] Writing batch script: ./lsf_controllerbddad0c8-59da-4591-8bde-d52ede1a573e
2019-04-27 17:08:49.734 [IPClusterStart] Starting BcbioLSFControllerLauncher: bsub<"./lsf_controllerbddad0c8-59da-4591-8bde-d5
2ede1a573e"
2019-04-27 17:08:49.804 [IPClusterStart] ERROR | Controller start failed
Traceback (most recent call last):
  File "/apps/lib-osver/bcbio/1.0.4/anaconda/lib/python2.7/site-packages/ipyparallel/apps/ipclusterapp.py", line 503, in start
_controller
    self.controller_launcher.start()
  File "/apps/lib-osver/bcbio/1.0.4/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py", line 219, in start
    return super(BcbioLSFControllerLauncher, self).start()
  File "/apps/lib-osver/bcbio/1.0.4/anaconda/lib/python2.7/site-packages/ipyparallel/apps/launcher.py", line 1305, in start
    return super(LSFControllerLauncher, self).start(1)
  File "/apps/lib-osver/bcbio/1.0.4/anaconda/lib/python2.7/site-packages/ipyparallel/apps/launcher.py", line 1286, in start
    job_id = self.parse_job_id(output)
  File "/apps/lib-osver/bcbio/1.0.4/anaconda/lib/python2.7/site-packages/ipyparallel/apps/launcher.py", line 1103, in parse_jo
b_id
    raise LauncherError("Job id couldn't be determined: %s" % output)
LauncherError: Job id couldn't be determined:

Thanks for any pointers!

Sudeshna

**Comment by chapmanb** [comment]
Sudeshna;
Thanks for the report and apologies about the issues. It appears that IPython is having issues submitting to the LSF queue, so the jobs are never making it onto the cluster. My suggestion is to try submitting outside of bcbio:
```
bsub<"./lsf_controllerbddad0c8-59da-4591-8bde-d52ede1a573e"
```
which will hopefully give some useful error messages about what the scheduler dislikes about the submission batch scripts. That should help us tweak the settings to it'll work cleanly.

I did some work trying to get bcbio running on the partners cluster a few years back and if I remember correctly it was quite tricky because the different queue types are very picky about matching the actual resource allocations -- so if you ask for `big` but don't ask for enough memory or cores it'll reject it.

Hopefully the combination of that vague memory and manually submitting helps.

**Comment by sudeshna-das** [comment]
Thank you Brad, that is very helpful! It looks like request mismatch to resource issue. Here are the queues available at Partner's and the controller. 

![image](https://user-images.githubusercontent.com/8116214/56871199-6a676180-69e8-11e9-9243-9610c6db169f.png)


Here is what the lsf_controllerbddad0c8-59da-4591-8bde-d52ede1a573e output is:
# LSBATCH: User input
#!/bin/sh


#BSUB -q big
#BSUB -J bcbio-c
#BSUB -n 4
#BSUB -oo bcbio-ipcontroller.bsub.%J

/apps/lib-osver/bcbio/1.0.4/anaconda/bin/python -E -c 'import resource; cur_proc, max_proc = resource.getrlimit(resource.RLIMIT_NPROC); tar
get_proc = min(max_proc, 10240) if max_proc > 0 else 10240; resource.setrlimit(resource.RLIMIT_NPROC, (max(cur_proc, target_proc), max_proc
)); cur_hdls, max_hdls = resource.getrlimit(resource.RLIMIT_NOFILE); target_hdls = min(max_hdls, 10240) if max_hdls > 0 else 10240; resourc
e.setrlimit(resource.RLIMIT_NOFILE, (max(cur_hdls, target_hdls), max_hdls)); from cluster_helper.cluster import VMFixIPControllerApp; VMFix
IPControllerApp.launch_instance()' --ip=* --log-to-file --profile-dir="/data/mindinformatics/projects/DGE/alignment/work/log/ipython" --clu
ster-id="be0a7c37-fa4f-45b7-b293-e47cd0c41be9" --nodb --hwm=1 --scheme=leastload --HeartMonitor.max_heartmonitor_misses=720 --HeartMonitor.
period=5000


I tried running the controller with no luck. Thanks for any advice!

Sudeshna

**Comment by chapmanb** [comment]
Sudeshna;
Thanks for helping debug. When you run `bsub < lsf_controllerXXX` with the bcbio generated batch script, does it report any error messages? Submitting outside of bcbio and debugging would be the best way to identify the mismatches and try to select the correct queues. Hope this helps.

**Comment by sudeshna-das** [comment]
HI Brad,

There are no error messages. It has been running all night and killed it
this morning. Here are the log messages with  bsub < lsf_controllerXXX

[sd587@eris1n2 log]$ more
ipcontroller-9e36bb35-b834-4b33-85fd-f37f132c4d6a-6842.log

2019-04-29 00:27:27.692 [VMFixIPControllerApp] Hub listening on
tcp://*:51247 for registration.

2019-04-29 00:27:27.694 [VMFixIPControllerApp] Hub using DB backend: 'NoDB'

2019-04-29 00:27:27.949 [VMFixIPControllerApp] hub::created hub

2019-04-29 00:27:27.950 [VMFixIPControllerApp] writing connection info to
/data/mindinformatics/projects/DGE/al

ignment/work/log/ipython/security/ipcontroller-9e36bb35-b834-4b33-85fd-f37f132c4d6a-client.json

2019-04-29 00:27:27.957 [VMFixIPControllerApp] writing connection info to
/data/mindinformatics/projects/DGE/al

ignment/work/log/ipython/security/ipcontroller-9e36bb35-b834-4b33-85fd-f37f132c4d6a-engine.json

2019-04-29 00:27:27.964 [VMFixIPControllerApp] task::using Python leastload
Task scheduler

2019-04-29 00:27:27.964 [VMFixIPControllerApp] Heartmonitor started

2019-04-29 00:27:27.976 [VMFixIPControllerApp] Creating pid file:
/data/mindinformatics/projects/DGE/alignment/

work/log/ipython/pid/ipcontroller-9e36bb35-b834-4b33-85fd-f37f132c4d6a.pid

2019-04-29 00:27:27.989 [VMFixIPControllerApp] client::client '\x00k\x8bEg'
requested 'connection_request'

2019-04-29 00:27:27.989 [VMFixIPControllerApp] client::client
['\x00k\x8bEg'] connected


Sender: LSF System <lsfadmin@cn027>

Subject: Job 732590: <bcbio-c> Exited


Job <bcbio-c> was submitted from host <eris1n2> by user <sd587> in cluster
<cmucluster>.

Job was executed on host(s) <cn027>, in queue <big>, as user <sd587> in
cluster <cmucluster>.

</PHShome/sd587> was used as the home directory.

</data/mindinformatics/projects/DGE/alignment/work> was used as the working
directory.

Started at Mon Apr 29 00:27:26 2019

Results reported at Mon Apr 29 06:24:25 2019


Your job looked like:


------------------------------------------------------------

# LSBATCH: User input

#!/bin/sh



#BSUB -q big

#BSUB -J bcbio-c

#BSUB -n 1

#BSUB -oo bcbio-ipcontroller.bsub.%J


/apps/lib-osver/bcbio/1.0.4/anaconda/bin/python -E -c 'import resource;
cur_proc, max_proc = resource.getrlimit

(resource.RLIMIT_NPROC); target_proc = min(max_proc, 10240) if max_proc > 0
else 10240; resource.setrlimit(reso

urce.RLIMIT_NPROC, (max(cur_proc, target_proc), max_proc)); cur_hdls,
max_hdls = resource.getrlimit(resource.RL

IMIT_NOFILE); target_hdls = min(max_hdls, 10240) if max_hdls > 0 else
10240; resource.setrlimit(resource.RLIMIT

_NOFILE, (max(cur_hdls, target_hdls), max_hdls)); from
cluster_helper.cluster import VMFixIPControllerApp; VMFi

xIPControllerApp.launch_instance()' --ip=* --log-to-file
--profile-dir="/data/mindinformatics/projects/DGE/alig

nment/work/log/ipython" --cluster-id="9e36bb35-b834-4b33-85fd-f37f132c4d6a"
--nodb --hwm=1 --scheme=leastload -

-HeartMonitor.max_heartmonitor_misses=720 --HeartMonitor.period=5000



------------------------------------------------------------


TERM_OWNER: job killed by owner.

Exited with signal termination: Alarm clock.


Resource usage summary:


    CPU time   :     31.03 sec.

    Max Memory :       238 MB

    Max Swap   :      6101 MB


    Max Processes  :         8

    Max Threads    :        19


The output (if any) follows:


2019-04-29 00:27:27.680 [VMFixIPControllerApp] Using existing profile dir:
u'/data/mindinformatics/projects/DGE

/alignment/work/log/ipython'

2019-04-29 00:27:27.987 [scheduler] Scheduler started [leastload]

2019-04-29 06:24:25.345 [scheduler] Interrupted, exiting...

CRITICAL:scheduler:Interrupted, exiting...

And when I ran bcbio I get:

[sd587@eris1n2 log]$ more
ipcluster-9e36bb35-b834-4b33-85fd-f37f132c4d6a-6034.log

2019-04-29 00:02:52.537 [IPClusterStart] WARNING | Config option `mem` not
recognized by `BcbioLSFControllerLau

ncher`.

2019-04-29 00:02:52.541 [IPClusterStart] Starting ipcluster with
[daemon=True]

2019-04-29 00:02:52.549 [IPClusterStart] Creating pid file:
/data/mindinformatics/projects/DGE/alignment/work/l

og/ipython/pid/ipcluster-9e36bb35-b834-4b33-85fd-f37f132c4d6a.pid

2019-04-29 00:02:52.551 [IPClusterStart] Starting Controller with
cluster_helper.cluster.BcbioLSFControllerLaun

cher

2019-04-29 00:02:52.552 [IPClusterStart] adding PBS queue settings to batch
script

2019-04-29 00:02:52.552 [IPClusterStart] adding job array settings to batch
script

2019-04-29 00:02:52.552 [IPClusterStart] Writing batch script:
./lsf_controller014c7be8-78d6-4f46-a6ce-0b13c112

69d4

2019-04-29 00:02:52.558 [IPClusterStart] Starting
BcbioLSFControllerLauncher: bsub<"./lsf_controller014c7be8-78

d6-4f46-a6ce-0b13c11269d4"

2019-04-29 00:02:52.601 [IPClusterStart] Job submitted with job id:
u'732586'

2019-04-29 00:02:52.602 [IPClusterStart] Process 'bsub' started: u'732586'

2019-04-29 00:03:02.612 [IPClusterStart] Starting 1 Engines with
cluster_helper.cluster.BcbioLSFEngineSetLaunch

er

2019-04-29 00:03:02.751 [IPClusterStart] adding PBS queue settings to batch
script

2019-04-29 00:03:02.752 [IPClusterStart] adding job array settings to batch
script

2019-04-29 00:03:02.753 [IPClusterStart] Writing batch script:
./lsf_engined9a328c4-8eaa-4970-a7bc-45bc12e1bfc2

2019-04-29 00:03:02.762 [IPClusterStart] Starting
BcbioLSFEngineSetLauncher: bsub<"./lsf_engined9a328c4-8eaa-49

70-a7bc-45bc12e1bfc2"

2019-04-29 00:03:02.811 [IPClusterStart] ERROR | Engine start failed

Traceback (most recent call last):

  File
"/apps/lib-osver/bcbio/1.0.4/anaconda/lib/python2.7/site-packages/ipyparallel/apps/ipclusterapp.py",
lin

e 332, in start_engines

    self.engine_launcher.start(self.n)

  File
"/apps/lib-osver/bcbio/1.0.4/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py",
line 183,

in start

    return super(BcbioLSFEngineSetLauncher, self).start(n)

  File
"/apps/lib-osver/bcbio/1.0.4/anaconda/lib/python2.7/site-packages/ipyparallel/apps/launcher.py",
line 12

86, in start

    job_id = self.parse_job_id(output)

  File
"/apps/lib-osver/bcbio/1.0.4/anaconda/lib/python2.7/site-packages/ipyparallel/apps/launcher.py",
line 11

03, in parse_job_id

    raise LauncherError("Job id couldn't be determined: %s" % output)

LauncherError: Job id couldn't be determined:

**Comment by sudeshna-das** [comment]
HI Brad,


I tried running the lsf_engine and this maybe a better clue:


[sd587@eris1n2 work]$ bsub < lsf_engined9a328c4-8eaa-4970-a7bc-45bc12e1bfc2

Error in rusage section: The merged job-level and application-level rusage
value is outside the range set by RESRSV_LIMIT defined in lsb.queues. Job
not submitted.



#!/bin/sh



#BSUB -q big

#BSUB -J bcbio-e[1-1]

#BSUB -oo bcbio-ipengine.bsub.%%J

#BSUB -n 1

#BSUB -R "span[hosts=1]"

#BSUB -R "rusage[mem=1024]"


/apps/lib-osver/bcbio/1.0.4/anaconda/bin/python -E -c 'import resource;
cur_proc, max_proc = resource.getrlimit

(resource.RLIMIT_NPROC); target_proc = min(max_proc, 10240) if max_proc > 0
else 10240; resource.setrlimit(reso

urce.RLIMIT_NPROC, (max(cur_proc, target_proc), max_proc)); cur_hdls,
max_hdls = resource.getrlimit(resource.RL

IMIT_NOFILE); target_hdls = min(max_hdls, 10240) if max_hdls > 0 else
10240; resource.setrlimit(resource.RLIMIT

_NOFILE, (max(cur_hdls, target_hdls), max_hdls)); from
ipyparallel.apps.ipengineapp import launch_new_instance;

 launch_new_instance()' --timeout=960 --IPEngineApp.wait_for_url_file=960
--EngineFactory.max_heartbeat_misses=

120
--profile-dir="/data/mindinformatics/projects/DGE/alignment/work/log/ipython"
--cluster-id="9e36bb35-b834-4

b33-85fd-f37f132c4d6a"


Thanks!

Sudeshna

**Comment by roryk** [comment]
Hi Sudeshna,

This is tough to debug not being on the cluster, I'd contact the admins at Partners and see if they can figure out why that LSF file is throwing the error. It looks like `rusage[mem=1024]` is the problem but it is hard to know why without having access to the cluster. That is probably either too big or too little for the queue you are selecting, they might have some better suggestions. The admins will definitely be about 100x better at figuring out than we will be.

**Comment by roryk** [comment]
Closing this, as it is stale-- let us know if the folks at Partners weren't able to help.
