### ISSUE TITLE
ChIP-Seq: MACS2 still requires Python 2

### ISSUE THREAD

**Issue by LMannarino** [bcbio/bcbio-nextgen#2808]
Hi all,
 I have run a ChIP-Seq analysis using MACS2 for peak calling. 
It gives me the following error:

```
[2019-04-30T06:43Z] akane: Traceback (most recent call last):
[2019-04-30T06:43Z] akane:   File "/opt/bcbio-tools/bin/macs2", line 622, in <module>
[2019-04-30T06:43Z] akane:     main()
[2019-04-30T06:43Z] akane:   File "/opt/bcbio-tools/bin/macs2", line 56, in main
[2019-04-30T06:43Z] akane:     from MACS2.callpeak_cmd import run
[2019-04-30T06:43Z] akane: Traceback (most recent call last):
[2019-04-30T06:43Z] akane:   File "/opt/bcbio/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 31, in <module>
[2019-04-30T06:43Z] akane:   File "/opt/bcbio-tools/bin/macs2", line 622, in <module>
[2019-04-30T06:43Z] akane:     from MACS2.OptValidator import opt_validate
[2019-04-30T06:43Z] akane:     main()
[2019-04-30T06:43Z] akane:   File "/opt/bcbio/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/OptValidator.py", line 27, in <module>
[2019-04-30T06:43Z] akane:   File "/opt/bcbio-tools/bin/macs2", line 56, in main
[2019-04-30T06:43Z] akane:     from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
[2019-04-30T06:43Z] akane:     from MACS2.callpeak_cmd import run
[2019-04-30T06:43Z] akane:   File "__init__.pxd", line 861, in init MACS2.IO.Parser (MACS2/IO/Parser.c:22634)
[2019-04-30T06:43Z] akane:   File "/opt/bcbio/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 31, in <module>
[2019-04-30T06:43Z] akane: ValueError: numpy.ufunc has the wrong size, try recompiling
[2019-04-30T06:43Z] akane:     from MACS2.OptValidator import opt_validate
[2019-04-30T06:43Z] akane:   File "/opt/bcbio/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/OptValidator.py", line 27, in <module>
[2019-04-30T06:43Z] akane:     from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
[2019-04-30T06:43Z] akane:   File "__init__.pxd", line 861, in init MACS2.IO.Parser (MACS2/IO/Parser.c:22634)
[2019-04-30T06:43Z] akane: ValueError: numpy.ufunc has the wrong size, try recompiling
[2019-04-30T06:43Z] akane: Uncaught exception occurred
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /opt/bcbio-tools/bin/macs2 callpeak -t /mnt/lizardfs/data/bioinformatics/laura/ChIP-Seq/Liposarcomi/LPS-308/LPS-308/work/bamclean/DL221_H3K27Ac/DL221_H3K27Ac-fixrg_chrom_filter.bam -c /mnt/lizardfs/data/bioinformatics/laura/ChIP-Seq/Liposarcomi/LPS-308/LPS-308/work/bamclean/DL221_input/DL221_input-fixrg_chrom_filter.bam   -g 3137161264 -n DL221_H3K27Ac -B -q 0.01
Traceback (most recent call last):
  File "/opt/bcbio-tools/bin/macs2", line 622, in <module>
    main()
  File "/opt/bcbio-tools/bin/macs2", line 56, in main
    from MACS2.callpeak_cmd import run
  File "/opt/bcbio/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 31, in <module>
    from MACS2.OptValidator import opt_validate
  File "/opt/bcbio/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/OptValidator.py", line 27, in <module>
    from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
  File "__init__.pxd", line 861, in init MACS2.IO.Parser (MACS2/IO/Parser.c:22634)
ValueError: numpy.ufunc has the wrong size, try recompiling
' returned non-zero exit status 1.
[2019-04-30T06:43Z] akane: Uncaught exception occurred
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /opt/bcbio-tools/bin/macs2 callpeak -t /mnt/lizardfs/data/bioinformatics/laura/ChIP-Seq/Liposarcomi/LPS-308/LPS-308/work/bamclean/HeLa_H3K27Ac/HeLa_H3K27Ac-fixrg_chrom_filter.bam -c /mnt/lizardfs/data/bioinformatics/laura/ChIP-Seq/Liposarcomi/LPS-308/LPS-308/work/bamclean/HeLa_input/HeLa_input-fixrg_chrom_filter.bam   -g 3137161264 -n HeLa_H3K27Ac -B -q 0.01
Traceback (most recent call last):
  File "/opt/bcbio-tools/bin/macs2", line 622, in <module>
    main()
  File "/opt/bcbio-tools/bin/macs2", line 56, in main
    from MACS2.callpeak_cmd import run
  File "/opt/bcbio/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 31, in <module>
    from MACS2.OptValidator import opt_validate
  File "/opt/bcbio/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/OptValidator.py", line 27, in <module>
    from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
  File "__init__.pxd", line 861, in init MACS2.IO.Parser (MACS2/IO/Parser.c:22634)
ValueError: numpy.ufunc has the wrong size, try recompiling
' returned non-zero exit status 1.
[2019-04-30T06:43Z] akane: Unexpected error
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/chipseq/macs2.py", line 31, in run
    do.run(cmd.format(**locals()), "macs2 for %s" % name)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /opt/bcbio-tools/bin/macs2 callpeak -t /mnt/lizardfs/data/bioinformatics/laura/ChIP-Seq/Liposarcomi/LPS-308/LPS-308/work/bamclean/DL221_H3K27Ac/DL221_H3K27Ac-fixrg_chrom_filter.bam -c /mnt/lizardfs/data/bioinformatics/laura/ChIP-Seq/Liposarcomi/LPS-308/LPS-308/work/bamclean/DL221_input/DL221_input-fixrg_chrom_filter.bam   -g 3137161264 -n DL221_H3K27Ac -B -q 0.01
Traceback (most recent call last):
  File "/opt/bcbio-tools/bin/macs2", line 622, in <module>
    main()
  File "/opt/bcbio-tools/bin/macs2", line 56, in main
    from MACS2.callpeak_cmd import run
  File "/opt/bcbio/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 31, in <module>
    from MACS2.OptValidator import opt_validate
  File "/opt/bcbio/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/OptValidator.py", line 27, in <module>
    from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
  File "__init__.pxd", line 861, in init MACS2.IO.Parser (MACS2/IO/Parser.c:22634)
ValueError: numpy.ufunc has the wrong size, try recompiling
' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 52, in _setup_logging
    yield config
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 134, in peakcalling
    return ipython.zip_args(apply(peaks.calling, *args))
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 80, in apply
    return object(*args, **kwargs)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/chipseq/peaks.py", line 53, in calling
    dd.get_chip_method(data), data["resources"], data)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/chipseq/macs2.py", line 34, in run
    raise RuntimeWarning("macs2 terminated with an error.\n"
RuntimeWarning: macs2 terminated with an error.
Please, check the message and report error if it is related to bcbio.
You can add specific options for the sample setting resources as explained in docs: https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#sample-specific-resources
[2019-04-30T06:43Z] akane: Unexpected error
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/chipseq/macs2.py", line 31, in run
    do.run(cmd.format(**locals()), "macs2 for %s" % name)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /opt/bcbio-tools/bin/macs2 callpeak -t /mnt/lizardfs/data/bioinformatics/laura/ChIP-Seq/Liposarcomi/LPS-308/LPS-308/work/bamclean/HeLa_H3K27Ac/HeLa_H3K27Ac-fixrg_chrom_filter.bam -c /mnt/lizardfs/data/bioinformatics/laura/ChIP-Seq/Liposarcomi/LPS-308/LPS-308/work/bamclean/HeLa_input/HeLa_input-fixrg_chrom_filter.bam   -g 3137161264 -n HeLa_H3K27Ac -B -q 0.01
Traceback (most recent call last):
  File "/opt/bcbio-tools/bin/macs2", line 622, in <module>
    main()
  File "/opt/bcbio-tools/bin/macs2", line 56, in main
    from MACS2.callpeak_cmd import run
  File "/opt/bcbio/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 31, in <module>
    from MACS2.OptValidator import opt_validate
  File "/opt/bcbio/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/OptValidator.py", line 27, in <module>
    from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
  File "__init__.pxd", line 861, in init MACS2.IO.Parser (MACS2/IO/Parser.c:22634)
ValueError: numpy.ufunc has the wrong size, try recompiling
' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 52, in _setup_logging
    yield config
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 134, in peakcalling
    return ipython.zip_args(apply(peaks.calling, *args))
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 80, in apply
    return object(*args, **kwargs)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/chipseq/peaks.py", line 53, in calling
    dd.get_chip_method(data), data["resources"], data)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/chipseq/macs2.py", line 34, in run
    raise RuntimeWarning("macs2 terminated with an error.\n"
RuntimeWarning: macs2 terminated with an error.
Please, check the message and report error if it is related to bcbio.
You can add specific options for the sample setting resources as explained in docs: https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#sample-specific-resources
2019-04-30 08:43:43.953 [IPClusterStop] Using existing profile dir: '/mnt/lizardfs/data/bioinformatics/laura/ChIP-Seq/Liposarcomi/LPS-308/LPS-308/work/log/ipython'
2019-04-30 08:43:43.970 [IPClusterStop] Stopping cluster [pid=1232] with [signal=<Signals.SIGINT: 2>]
2019-04-30 08:43:44.808 [IPClusterStop] Using existing profile dir: '/mnt/lizardfs/data/bioinformatics/laura/ChIP-Seq/Liposarcomi/LPS-308/LPS-308/work/log/ipython'
2019-04-30 08:43:44.822 [IPClusterStop] Stopping cluster [pid=1232] with [signal=<Signals.SIGINT: 2>]
4 Engines running
Sending a shutdown signal to the controller and engines.
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/bin/bcbio_nextgen.py", line 238, in <module>
    main(**kwargs)
  File "/opt/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 53, in run_main
    fc_dir, run_info_yaml)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 380, in chipseqpipeline
    samples = peaks.peakcall_prepare(samples, run_parallel)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/chipseq/peaks.py", line 41, in peakcall_prepare
    after_process = run_parallel("peakcalling", to_process)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipython.py", line 137, in run
    for data in view.map_sync(fn, items, track=False):
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/ipyparallel/client/view.py", line 344, in map_sync
    return self.map(f,*sequences,**kwargs)
  File "</opt/bcbio/anaconda/lib/python3.6/site-packages/decorator.py:decorator-gen-139>", line 2, in map
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/ipyparallel/client/view.py", line 52, in sync_results
    ret = f(self, *args, **kwargs)
  File "</opt/bcbio/anaconda/lib/python3.6/site-packages/decorator.py:decorator-gen-138>", line 2, in map
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/ipyparallel/client/view.py", line 37, in save_ids
    ret = f(self, *args, **kwargs)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/ipyparallel/client/view.py", line 1114, in map
    return pf.map(*sequences)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/ipyparallel/client/remotefunction.py", line 299, in map
    return self(*sequences, __ipp_mapping=True)
  File "</opt/bcbio/anaconda/lib/python3.6/site-packages/decorator.py:decorator-gen-121>", line 2, in __call__
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/ipyparallel/client/remotefunction.py", line 80, in sync_view_results
    return f(self, *args, **kwargs)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/ipyparallel/client/remotefunction.py", line 285, in __call__
    return r.get()
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/ipyparallel/client/asyncresult.py", line 169, in get
    raise self.exception()
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/ipyparallel/client/asyncresult.py", line 228, in _resolve_result
    results = error.collect_exceptions(results, self._fname)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/ipyparallel/error.py", line 233, in collect_exceptions
    raise e
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/ipyparallel/error.py", line 231, in collect_exceptions
    raise CompositeError(msg, elist)
ipyparallel.error.CompositeError: one or more exceptions from call to method: peakcalling
[1:apply]: RuntimeWarning: macs2 terminated with an error.
Please, check the message and report error if it is related to bcbio.
You can add specific options for the sample setting resources as explained in docs: https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#sample-specific-resources
[3:apply]: RuntimeWarning: macs2 terminated with an error.
Please, check the message and report error if it is related to bcbio.
You can add specific options for the sample setting resources as explained in docs: https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#sample-specific-resources
```

I guess this is due to MACS2 still running with Pyhton 2 environment. Could it be fixed?

Thanks,
Laura

**Comment by roryk** [comment]
Hi Laura,

Sorry about that, we ran into this too. The reason why this is happening is there is an old numpy that is getting picked up in the python2 environment. I don't know why it isn't getting cleaned up, but it isn't.

If you do:

```bash
ls -ld /opt/bcbio/anaconda/envs/python2/lib/python2.7/site-packages/numpy*
```

I think you will see there are mutliple numpys there, one of which is old. Ours looks like this:

```bash
/n/app/bcbio/dev/anaconda/envs/python2/lib/python2.7/site-packages/numpy  /n/app/bcbio/dev/anaconda/envs/python2/lib/python2.7/site-packages/numpy-1.15.4.dist-info
```

If you do see that, you can nuke them by doing:

```bash
rm -r /opt/bcbio/anaconda/envs/python2/lib/python2.7/site-packages/numpy*
```

that will get rid of all of the numpys. And you can install a current one into the python2 environment by doing:

```bash
bcbio_conda install -n python2 -c bioconda numpy
```

**Comment by LMannarino** [comment]
Hi,
 this solved the problem.

Thank you very much.

Laura

**Comment by roryk** [comment]
Great! Thanks for following up, glad that worked.
