### ISSUE TITLE
bcbio hangs during the bgzip/grabix indexing step

### ISSUE THREAD

**Issue by parlar** [bcbio/bcbio-nextgen#2811]
I've noticed that bcbio always hangs during bgzip+grabix indexing of fastq.gz files. I have to terminate the process (ctrl-c) and restart the pipeline to make it continue.

Could be a local issue with my installation / vmware esxi centos 7.6 server. As mentioned in earlier issue, bcbio also fails to install the bioconductor-genomeinfodbdata package, so I have to make a work-around to install it (manual installation of the R package + otherfiles needed for conda to see the package as installed).

Perhaps not so many people use Centos these days, would you rather recommend something like Ubuntu for bcbio-nextgen?

```
[2019-05-06T15:03Z] Configuring 2 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2019-05-06T15:03Z] Index input with grabix: Oncospan_S4_R1_001.ss_17532001.fastq.gz
[2019-05-06T15:04Z] Index input with grabix: Oncospan_S4_R2_001.ss_17532001.fastq.gz
^CProcess ForkPoolWorker-4:
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/pool.py", line 149, in get
    return recv()
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 238, in <module>
    main(**kwargs)
  File "/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 128, in variant2pipeline
    samples = run_parallel("prep_align_inputs", samples)
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/multiprocessing/pool.py", line 664, in get
    self.wait(timeout)
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/multiprocessing/pool.py", line 661, in wait
    self._event.wait(timeout)
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
```

**Comment by naumenko-sa** [comment]
Hi Pär!

Please don't underestimate the number of machines running RHEL/Centos. What happens if you run the last command from bcbio-nextgen-commands.log?

S.

**Comment by roryk** [comment]
How long are you waiting for it to run? Depending on how big the file is, indexing can take a while.

Does indexing the Oncospan_S4_R2_001.fastq.gz file manually hang or take forever? if you just run grabix on the command line, not the one in tmp but your original FASTQ files? That /storage/userdata/common/green/calling/work/bcbiotx/tmpyhpf05f4/Oncospan_S4_R2_001.fastq.gz file is just a symlink, to the original file, so it is trying to index that.

I'd try running grabix on the original file and then if that worked, try symlinking the file and running grabix on the symlink and seeing if that hangs somehow.

**Comment by roryk** [comment]
/storage/userdata/common/green/calling/work/bcbiotx/tmpyhpf05f4/Oncospan_S4_R2_001.fastq.gz

 is just a symlink back to the input FASTQ file. If you run grabix on the original FASTQ file, does it work? If so, if you make a symlink to the FASTQ file and then run grabix on that, does that work?

**Comment by roryk** [comment]
Whoa, github is messed up, your comment is 4 hours in the future.

**Comment by parlar** [comment]
This time I ran, I think, 12 samples and it did not hang until the running grabix index on the 11th. So it's a spurious error that might be difficult to reproduce.   

Now I did not wait that long, perhaps 10-20 min after activity ceased. Previously I have left it over night before realizing I have to kill bcbio and restart. 

By the judge of top, nothing at all is happening on the machine: the bcbio_nextgen.py script is not showing up in the list but it is there when I check with ps.  

I'll continue to investigate.

**Comment by chapmanb** [comment]
Pär;
How did you produce the fastq files? I've seen grabix hang in the past on problematic fastqs (https://github.com/arq5x/grabix/issues/17) although at least those issues should be fixed. One problematic fastq input is concatenating gziped files without unzipping and re-bgzipping them (`cat a.fq.gz b.fq.gz > final.fq.gz`). That should work but sometimes produces invalid fastqs for reasons I still can't figure out. One practical suggestion is to try re-preparing the fastq `gunzip orig.fq.gz | bgzip -c > fixed.fq.gz` outside of bcbio to see if that resolves the problem. Hope this helps.

**Comment by parlar** [comment]
running ```bcbio_nextgen.pl -t local -n 1``` seems to prevent the the grabix index step from hanging. Will try to upgrade python to 3.7.3, or whatever the latest iteration is now, and see if that does any good.

**Comment by parlar** [comment]
The fastq files were produced using bcl2fastq directly I think for all files, but I'll double check.

**Comment by roryk** [comment]
Hi @parlar,

Is this still happening, or are you all set?

**Comment by roryk** [comment]
Closing, as I think Brad suggested what we usually see as these kind of errors. It's usually one of two things: the gzipped FASTQ files were catted together or there was a flaky filesystem or something non-reproducible like that. Please reopen if it you're still having the problem.
