### ISSUE TITLE
vep issue: --most_severe and --biotype cannot be combined

### ISSUE THREAD

**Issue by parlar** [bcbio/bcbio-nextgen#2813]
Getting the error msg below from vep using the latest devel version of bcbio-nextgen. 

```MSG: ERROR: Can't use --most_severe and --biotype together```

```
[2019-05-07T07:19Z] Ensembl variant effect predictor : HD200
[2019-05-07T07:19Z] Possible precedence issue with control flow operator at /usr/local/share/bcbio/anaconda/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 845.
[2019-05-07T07:19Z] -------------------- EXCEPTION --------------------
[2019-05-07T07:19Z] MSG: ERROR: Can't use --most_severe and --biotype together
[2019-05-07T07:19Z] STACK Bio::EnsEMBL::VEP::Config::check_config /usr/local/share/bcbio/anaconda/share/ensembl-vep-96.0-0/modules/Bio/EnsEMBL/VEP/Config.pm:643
[2019-05-07T07:19Z] STACK Bio::EnsEMBL::VEP::Config::new /usr/local/share/bcbio/anaconda/share/ensembl-vep-96.0-0/modules/Bio/EnsEMBL/VEP/Config.pm:473
[2019-05-07T07:19Z] STACK Bio::EnsEMBL::VEP::BaseRunner::new /usr/local/share/bcbio/anaconda/share/ensembl-vep-96.0-0/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:92
[2019-05-07T07:19Z] STACK toplevel /usr/local/share/bcbio/anaconda/bin/vep:209
[2019-05-07T07:19Z] Date (localtime)    = Tue May  7 09:19:31 2019
[2019-05-07T07:19Z] Ensembl API version = 96
[2019-05-07T07:19Z] ---------------------------------------------------
[2019-05-07T07:19Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset PERL5LIB && export PATH=/usr/local/share/bcbio/anaconda/bin:"$PATH" && /usr/local/share/bcbio/anaconda/bin/vep --vcf -o stdout -i /home/pela09/Project/Green/calling2/work/freebayes/batch1.vcf.gz --species homo_sapiens --no_stats --cache --offline --dir /usr/local/share/bcbio/genomes/Hsapiens/hg38/vep --symbol --numbers --biotype --total_length --canonical --gene_phenotype --ccds --uniprot --domains --regulatory --protein --tsl --appris --af --max_af --af_1kg --af_esp --af_gnomad --pubmed --variant_class --allele_number --fasta /usr/local/share/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa.gz --plugin LoF,human_ancestor_fa:false,loftee_path:/usr/local/share/bcbio/anaconda/share/ensembl-vep-96.0-0 --plugin G2P,file:/home/pela09/Project/Green/calling2/variation/G2P.csv --sift b --polyphen b --hgvsg --hgvs --shift_hgvs 1 --most_severe --merged | sed '/^#/! s/;;/;/g' | bgzip -c > /home/pela09/Project/Green/calling2/work/bcbiotx/tmpwsg8o9fq/batch1-vepeffects.vcf.gz
```

**Comment by chapmanb** [comment]
Pär;
Thanks much for the report. It looks like the new `--most_severe` flag in the latest VEP has a lot of conflicts with other options. I tried to flag all these based on the documentation and move them out of the commandline options when `--most_severe` gets used if you have `clinical_reporting` set in your configuration. Hope this gets it working cleanly for you.

**Comment by parlar** [comment]
Still fails but it works when clinical_reporting is commented out. 

Not clear what the conflict is. ```--biotype``` is not present so it's obviously something else.

**Comment by chapmanb** [comment]
Pär;
Thanks for testing this out. Do you get any useful error messages during the latest failure? Definitely happy to continue fixing with any pointers. Thanks again.

**Comment by lbeltrame** [comment]
From a look at the VEP sources:

```perl

     {
       flags => ['vcf'],
       set   => {
         output_format => 'vcf',
         symbol => 1,
         biotype => 1,
         numbers => 1
       }   
     },  
```

Setting VCF output like bcbio does automatically sets biotype, hence causing the conflict.

**Comment by alhafidzhamdan** [comment]
Hi there - I've just encountered this issue also.
I'm running bcbio-1.1.5 through an SGE and it is difficult to upgrade to the latest version of bcbio.
This is part of the log:

> [2020-01-23T04:52Z] Using GATK jar /gpfs/igmmfs01/eddie/NextGenResources/bcbio-1.1.5/anaconda/share/gatk4-4.1.4.1-1/gatk-package-4.1.4.1-local.jar
[2020-01-23T04:52Z] Running:
[2020-01-23T04:52Z]     java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xms454m -Xmx5g -XX:+UseSerialGC -Djava.io.tmpdir=/gpfs/igmmfs01/eddie/
Glioblastoma-WGS/bcbio/work/DO11501/bcbiotx/tmpp0sivdd1 -jar /gpfs/igmmfs01/eddie/NextGenResources/bcbio-1.1.5/anaconda/share/gatk4-4.1.4.1-1/gatk-package-4.1.4.1-local.jar GatherVcfs -I /gpfs/igmmfs01/eddie/Glioblastoma-WGS/bcbio/work/DO11501/vardict/DO1
1501-files.list -O /gpfs/igmmfs01/eddie/Glioblastoma-WGS/bcbio/work/DO11501/bcbiotx/tmp3ww484gx/DO11501.vcf.gz
[2020-01-23T04:52Z] tabix index DO11501.vcf.gz
[2020-01-23T04:52Z] Resource requests: bcbio_variation, fastqc, gatk, gatk-vqsr, gemini, kraken, preseq, qsignature, sambamba, samtools; memory: 3.00, 3.00, 6.00, 3.00, 3.00, 3.00, 3.00, 3.00, 3.00, 3.00; cores: 16, 16, 1, 16, 16, 16, 16, 16, 16, 16
[2020-01-23T04:52Z] Configuring 1 jobs to run, using 8 cores each with 48.1g of memory reserved for each job
[2020-01-23T04:52Z] Timing: joint squaring off/backfilling
[2020-01-23T04:52Z] Timing: variant post-processing
[2020-01-23T04:52Z] multiprocessing: postprocess_variants
[2020-01-23T04:52Z] Finalizing variant calls: DO11501T, vardict
[2020-01-23T04:52Z] Calculating variation effects for DO11501T, vardict
[2020-01-23T04:52Z] Ensembl variant effect predictor : DO11501T
[2020-01-23T04:52Z] Possible precedence issue with control flow operator at /gpfs/igmmfs01/eddie/NextGenResources/bcbio-1.1.5/anaconda/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 805.
[2020-01-23T04:52Z] ERROR: Can't use --most_severe and --biotype together
[2020-01-23T04:52Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/exports/igmm/eddie/NextGenResources/bcbio-1.1.5/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/exports/igmm/eddie/NextGenResources/bcbio-1.1.5/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset PERL5LIB && export PATH=/gpfs/igmmfs01/eddie/NextGenResources/bcbio-1.1.5/anaconda/bin:"$PATH" && /exports/igmm/eddie/NextGenResources/bcbio-1.1.5/anaconda/bin/vep --vcf -o stdout -i /gpfs/igmmfs01/eddie/Glioblastoma-WGS/bcbio/work/DO11501/vardict/DO11501.vcf.gz --fork 8 -e --species homo_sapiens --no_stats --cache --offline --dir /gpfs/igmmfs01/eddie/NextGenResources/bcbio-1.1.5/genomes/Hsapiens/hg38/vep --total_length --gene_phenotype --regulatory --af --max_af --af_1kg --af_esp --af_gnomad --pubmed --variant_class --allele_number --fasta /gpfs/igmmfs01/eddie/NextGenResources/bcbio-1.1.5/genomes/Hsapiens/hg38/seq/hg38.fa.gz --plugin LoF,human_ancestor_fa:false,loftee_path:/gpfs/igmmfs01/eddie/NextGenResources/bcbio-1.1.5/anaconda/share/ensembl-vep-98.0-0 --plugin G2P,file:/gpfs/igmmfs01/eddie/Glioblastoma-WGS/bcbio/work/variation/G2P.csv --sift b --polyphen b --humdiv --hgvsg --hgvs --shift_hgvs 1 --most_severe --merged | sed '/^#/! s/;;/;/g' | bgzip -c > /gpfs/igmmfs01/eddie/Glioblastoma-WGS/bcbio/work/DO11501/bcbiotx/tmpwp7_72v5/DO11501-vepeffects.vcf.gz
Possible precedence issue with control flow operator at /gpfs/igmmfs01/eddie/NextGenResources/bcbio-1.1.5/anaconda/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 805.
ERROR: Can't use --most_severe and --biotype together
' returned non-zero exit status 2.
Traceback (most recent call last):
  File "/exports/igmm/eddie/NextGenResources/bcbio-1.1.5/to

- How do I either change bcbio configuration so that it doesn't turn on biotype automatically or the VEP parameters so that most_severe and biotype don't crash?

It's probably pretty basic but I've tried this in the yaml file...adding "-e" to VEP resources but not sure if that's the right to do, or if i've done it the right way.

details:
- algorithm:
    aligner: false
    mark_duplicates: false
    remove_lcr: true
    mixup_check: qsignature
    variantcaller: 
      somatic: [vardict, strelka2, mutect2]
      germline: [gatk-haplotype]
    min_allele_fraction: 5
    indelcaller: false
    effects: vep
    effects_transcripts: canonical
    ensemble:
      numpass: 2
      use_filtered: false
    tools_off: [gemini]
    tools_on: [gatk4]
  analysis: variant2
  genome_build: hg38
  resources:
    vep: 
      options: ["-e"] 



Any help is much appreciated!!

**Comment by lbeltrame** [comment]
This a bug that needs to be raised with the VEP people, I think. You can't solve the conflict because the VEP sets biotype to 1 when outputting VCF.
