### ISSUE TITLE
Unclear documentation on how to generate a tumor-only panel for CNV

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2815]
I have a fairly complex analysis which involves doing tumor-only variant calling with MuTect + a panel of normals already made and CNVkit for CNV. For the CNV analysis *only* there is a large (60) number of samples that are there just to provide a reference. However, the pipeline tries to find cases in the batch (they're all the same batch) and fails:

```python

Traceback (most recent call last):
  File "/opt/bcbio/anaconda/bin/bcbio_nextgen.py", line 238, in <module>
    main(**kwargs)
  File "/opt/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 178, in variant2pipeline
    samples = structural.run(samples, run_parallel, "standard")
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/__init__.py", line 184, in run
    for xs in to_process.values()))
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 917, in __call__
    if self.dispatch_one_batch(iterator):
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 324, in detect_sv
    return structural.detect_sv(*args)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/__init__.py", line 205, in detect_sv
    for svdata in caller_fn(items):
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/cnvkit.py", line 57, in run
    return _cnvkit_by_type(items, background)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/cnvkit.py", line 71, in _cnvkit_by_type
    return _run_cnvkit_population(items, background)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/cnvkit.py", line 154, in _run_cnvkit_population
    ckouts = _run_cnvkit_shared(inputs, background)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/cnvkit.py", line 207, in _run_cnvkit_shared
    if tz.get_in(["depth", "bins", "normalized"], inputs[0]):
IndexError: list index out of range
```

That's because `inputs` is empty because (obviously) there are no cases in this batch.

A typical entry for one of these samples:

```yaml

 - algorithm:
       aligner: false
       effects: vep
       effects_transcripts: canonical
       exclude_regions:
       - polyx
       - lcr
       - altcontigs
       - highdepth
       mark_duplicates: true 
       min_allele_fraction: 1
       mixup_check: qsignature
       platform: illumina
       quality_format: Standard
       realign: false
       recalibrate: false
       svcaller: cnvkit
       tools_off: upload_alignment
       variant_regions: oneseq_liftover
       variantcaller: false
     analysis: variant2
     description: SC-99
     files:
     - /bioinformatics/einar/normals/SC-99-ready.bam
     genome_build: hg38 
     metadata:
       batch: pon_build
       sex: female
       svclass: control
```

Case samples are, instead:

```yaml
- algorithm:
       aligner: bwa
       background:
         variant: /bioinformatics/einar/MuTect_PoN.hg38.vcf.gz
       effects: vep
       effects_transcripts: canonical
       exclude_regions:
       - polyx
       - lcr
       - altcontigs
       - highdepth
       mark_duplicates: true
       min_allele_fraction: 1
       mixup_check: qsignature
       platform: illumina
       quality_format: Standard
       realign: false
       recalibrate: false
       svcaller: cnvkit 
       tools_off:
       - fastqc
       - contamination
       - viral
       - coverage_qc
       variant_regions: oneseq_liftover
       variantcaller:
       - mutect2
       - vardict
     analysis: variant2
     description: S8
     files:
     - /data/sequencing/nextseq500/S8_S13_R1_001.fastq.gz
     - /data/sequencing/nextseq500/S8_S13_R2_001.fastq.gz
     genome_build: hg38
     metadata:
       batch: S8_vs_reference
       phenotype: tumor
       sex: female

```
As you can see, the controls are tagged with `svclass` but the sampels aren't. I can't seem to find why bcbio wants to use the controls as a paired case/control sample. The [docs](https://bcbio-nextgen.readthedocs.io/en/latest/contents/pipelines.html#somatic-tumor-only-cnvs) only mention the use of `svclass`.

The template used to generate everything was

```yaml

---
details:
  - analysis: variant2
    genome_build: hg38
    algorithm:
        aligner: bwa
        mark_duplicates: true
        recalibrate: false
        realign: false
        variantcaller: false
        platform: illumina
        quality_format: Standard
        variant_regions: my_regions
        effects_transcripts: canonical
        effects: vep
        min_allele_fraction: 1
        mixup_check: qsignature
        tools_off:
          - fastqc
          - contamination
          - viral
          - coverage_qc
    metadata:
        sex: female
upload:
    dir: ../final/
globals:
    oneseq_liftover: /data/bioinformatics/regions/Agilent_OneSeq_BackBone_Genes_merged.hg38.bed
```

What's wrong here? I can provide (privately) the full YAML file.

**Comment by lbeltrame** [comment]
Ok, as far as I can read, this works by having the reference in the same batch as the tumor. However this means that it is impossible to do a background analysis and variant calling in the same step. Did I understand correctly?

**Comment by chapmanb** [comment]
Luca;
Thanks for the detailed report and apologies about the confusion. You're exactly right that the idea is to build a panel of normals and do the actual analysis in two separate runs. Setting up the panel of normals is a one time operation and then once you have the PoN in place you can avoid needing to include the control samples in your other analyses. Hope this will work for you.

**Comment by roryk** [comment]
Hope this clarification helped!
