### ISSUE TITLE
upgrading to development fails

### ISSUE THREAD

**Issue by parlar** [bcbio/bcbio-nextgen#2817]
You're probably already aware of it? Otherwise, see below:

```
(base) [pela09@vs476 ~]$ bcbio_nextgen.py upgrade -u development --tools --data
Upgrading bcbio
Collecting package metadata: ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /usr/local/share/bcbio/anaconda

  added / updated specs:
    - bcbio-nextgen[version='>=1.1.5']


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bcbio-nextgen-1.1.6a       |           py36_0         2.1 MB  bioconda
    ------------------------------------------------------------
                                           Total:         2.1 MB

The following packages will be UPDATED:

  bcbio-nextgen                                1.1.5-py36_0 --> 1.1.6a-py36_0



CondaFileIOError: '/usr/local/share/bcbio/anaconda/pkgs/bcbio-nextgen-1.1.6a-py36_0.tar.bz2'. contains unsafe path: bin/bcbio_nextgen.py

Traceback (most recent call last):
  File "/usr/local/share/bcbio/tools/bin/bcbio_nextgen.py", line 221, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 60, in upgrade_bcbio
    anaconda_dir = _update_conda_devel()
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 297, in _update_conda_devel
    ["bcbio-nextgen>=%s" % version.__version__.replace("a0", "a")])
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/conda', 'install', '--quiet', '--yes', '-c', 'bioconda', '-c', 'conda-forge', 'bcbio-nextgen>=1.1.5']' returned non-zero exit status 1.
```

**Comment by roryk** [comment]
Heya-- I can't reproduce this error on our installation. Does this give you any clues: https://github.com/conda/conda/issues/8423 in particular this comment? https://github.com/conda/conda/issues/8423#issuecomment-475702893
