### ISSUE TITLE
filter_vcf_by_sex: write in Unicode to prevent decoding errors

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2819]
Example that breaks everything:

```
clinvar_sig=Benign;clinvar_disease_name=Pheochromocytoma|Hereditary_cancer-predisposing_syndrome|Roussy-Lévy_syndrome|
```

And `filter_vcf_by_sex`:

```python
with open(tx_out_file, "w") as out_handle:
```

This breaks completely a few lines later, when writing:

```python

Traceback (most recent call last):
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 52, in _setup_logging
    yield config
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 308, in postprocess_variants
    return ipython.zip_args(apply(variation.postprocess_variants, *args))
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 80, in apply
    return object(*args, **kwargs)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/variation.py", line 114, in postprocess_variants
    data, orig_items)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/genotype.py", line 30, in variant_filtration
    call_file = ploidy.filter_vcf_by_sex(call_file, items)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/ploidy.py", line 89, in filter_vcf_by_sex
    out_handle.write(line)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 1370: ordinal not in range(128)
```

**Comment by roryk** [comment]
Hi Luca,

I think I fixed this, if you update and rerun you should be all set. Let me know if this didn't actually fix it.

**Comment by lbeltrame** [comment]
FTR, there's a similar issue in `bcbio/variation/damage.py`, line 55:

```
with utils.open_gzipsafe(in_file) as in_handle:
    with open(tx_out_file, "w") as out_handle:
```
This one needs the encoding as well.

**Comment by chapmanb** [comment]
Luca;
Thanks much for the heads up. I pushed a complementary fix to that output function as well. Please let us know if you run into any other problems at all.
