### ISSUE TITLE
bcbio missing "tools_off" option

### ISSUE THREAD

**Issue by matthdsm** [bcbio/bcbio-nextgen#2823]
Hi Brad,

We've been having some issues after a recent update to the latest stable. When we try to use GATK3 by specifying `tools_off: gatk4`. I get the following error:
```
Traceback (most recent call last):
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 52, in _setup_logging
    yield config
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 393, in variantcall_sample
    return ipython.zip_args(apply(genotype.variantcall_sample, *args))
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 80, in apply
    return object(*args, **kwargs)
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/genotype.py", line 377, in variantcall_sample
    out_file = caller_fn(align_bams, items, ref_file, assoc_files, region, out_file)
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/gatk.py", line 180, in haplotype_caller
    parallel_gc=_use_spark(num_cores, gatk_type, items, spark_opts))
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/bcbio/broad/__init__.py", line 355, in run_gatk
    cl = self.cl_gatk(params, tmp_dir, memscale=memscale, parallel_gc=parallel_gc)
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/bcbio/broad/__init__.py", line 276, in cl_gatk
    if self._has_gatk_conda_wrapper():
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/bcbio/broad/__init__.py", line 262, in _has_gatk_conda_wrapper
    return stdout.find("GATK jar file not found") == -1
TypeError: a bytes-like object is required, not 'str'
```

This originates [here](https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/broad/__init__.py#L254), which checks if the jar file is registered.

Any ideas how to fix this? The gatk jar file is registered and usable. gatk3 can be run manually without issues (using the conda wrapper).

Thanks
M

**Comment by roryk** [comment]
Hi @mattdsm,

If you change this line:

                    stdout = subprocess.check_output(cmd, stderr=subprocess.STDOUT, shell=True)

to

                    stdout = subprocess.check_output(cmd, stderr=subprocess.STDOUT, shell=True, encoding="UTF-8")

Does that fix the problem for you?

**Comment by roryk** [comment]
in this file: /home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/bcbio/broad/__init__.py

**Comment by matthdsm** [comment]
Hi Rory,

Thanks, that did fix it for me!
I'll open a quick PR with the fix
Cheers
M

**Comment by chapmanb** [comment]
Matthias -- thanks much for the report and testing and PRing this so quickly. Rory -- thanks for the fix suggestion. Sorry about all these trailing python 3 issues, hopefully we're getting to the end of them.
