### ISSUE TITLE
Correcting the AD value when breaking MNPs into multiple SNPs

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#2825]
Hello,

I read somewhere that Bcbio has this "policy" of breaking down MNPs into multiple SNPs. This appears to also have the unwanted effect of rendering Freebayes' AD values meaningless. Here's an example:

```
chrI	1505	.	T	G	2498.54	PASS	AC=2;AF=0.5;AN=4;DECOMPOSED;LEN=1;NS=2;TYPE=snp	GT:GQ:DP:AD:RO:QR:AO:QA:GL	1|0:160:74:0,33,41:0:0:33,41:1179,1464:-150.315,-98.6372,-88.7032,-51.927,0,-39.5847	1|0:160:76:0,41,35:0:0:41,35:1476,1248:-131.218,-76.8083,-64.4661,-54.6424,0,-44.1064
chrI	1506	.	T	G	2498.54	PASS	AC=4;AF=1;AN=4;DECOMPOSED;LEN=1;NS=2;TYPE=snp	GT:GQ:DP:AD:RO:QR:AO:QA:GL	1|1:160:74:0,33,41:0:0:33,41:1179,1464:-150.315,-98.6372,-88.7032,-51.927,0,-39.5847	1|1:160:76:0,41,35:0:0:41,35:1476,1248:-131.218,-76.8083,-64.4661,-54.6424,0,-44.1064
```

The previous two SNPs were likely part of an MNP called by Freebayes. The AD value (`0,33,41`) suggests a multiallelic event. 

My question is: would it be possible to correct the AD value as well, into something like `0,33` and `0,41` respectively?

For the record, I came upon this issue while trying to run `WhatsHap` on a VCF file createdy by Bcbio for Freebayes. This is the error it ran into: 

```
This is WhatsHap 0.18 running under Python 3.6.8
Working on 2 samples from 2 families
Traceback (most recent call last):
  File "/export/home/ncit/external/a.mizeranschi/sra-tools/anaconda/lib/python3.6/site-packages/vcf/parser.py", line 481, in _parse_samples
    sampdat[i] = int(vals)
ValueError: invalid literal for int() with base 10: '33,41'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/export/home/ncit/external/a.mizeranschi/sra-tools/anaconda/bin/whatshap", line 12, in <module>
    sys.exit(main())
  File "/export/home/ncit/external/a.mizeranschi/sra-tools/anaconda/lib/python3.6/site-packages/whatshap/__main__.py", line 83, in main
    module.main(args)
  File "/export/home/ncit/external/a.mizeranschi/sra-tools/anaconda/lib/python3.6/site-packages/whatshap/phase.py", line 1114, in main
    run_whatshap(**vars(args))
  File "/export/home/ncit/external/a.mizeranschi/sra-tools/anaconda/lib/python3.6/site-packages/whatshap/phase.py", line 663, in run_whatshap
    for variant_table in vcf_reader:
  File "/export/home/ncit/external/a.mizeranschi/sra-tools/anaconda/lib/python3.6/site-packages/whatshap/vcf.py", line 328, in __iter__
    for chromosome, records in self._group_by_chromosome():
  File "/export/home/ncit/external/a.mizeranschi/sra-tools/anaconda/lib/python3.6/site-packages/whatshap/vcf.py", line 305, in _group_by_chromosome
    for record in self._vcf_reader:
  File "/export/home/ncit/external/a.mizeranschi/sra-tools/anaconda/lib/python3.6/site-packages/vcf/parser.py", line 586, in __next__
    samples = self._parse_samples(row[9:], fmt, record)
  File "/export/home/ncit/external/a.mizeranschi/sra-tools/anaconda/lib/python3.6/site-packages/vcf/parser.py", line 483, in _parse_samples
    sampdat[i] = float(vals)
ValueError: could not convert string to float: '33,41'
```

**Comment by chapmanb** [comment]
Thanks much for the discussion. Unfortunately a downside of the decomposition is that some attributes don't get recalculated and no longer match the final alleles. We haven't written code to recalculate and fix all of these; I've been hoping someone would take this on more generally but unfortunately it hasn't happened yet. Practically, if attributes are causing issues feeding into downstream tools you can remove them as part of your post-analysis with:
```
bcftools annotate -x INFO/AD -O z -o calls-cleaned.vcf.gz calls-orig.vcf.gz
```
for any problematic attributes. Hope this will work for you.

**Comment by amizeranschi** [comment]
Many thanks for the reply and for the suggested fix.

Is there any way to turn off the decomposition of complex variants/MNPs into multiple SNPs? It could be useful to have this option as well, along with Bcbio's default behavior.

**Comment by chapmanb** [comment]
We don't currently have this option based on our past experience but it is something we could revisit. Rather than duplicating the conversation, I've answered in #2768 and we can move further discussion there. Thanks again.
