### ISSUE TITLE
Converting Sailfish to Sleuth format: invalid 'n' argument

### ISSUE THREAD

**Issue by komalsrathi** [bcbio/bcbio-nextgen#2843]
Hi,

I have just updated the bcbio-nextgen installation to test GATK3.8 on RNA-seq data and using the latest version 1.1.5. 

I have also checked that the R package `wasabi` is properly installed under bcbio R installation. Is there any other reason why I am getting the following error:

```
[2019-06-03T18:14Z] Quantifying transcripts in /mnt/isilon/dbhi_bfx/rathik/mendelian_rnaseq/gatk_output/27571P_gatk3/Sample_1__27571P-dedup.splitN_chrX_1_converted.fastq.gz and /mnt/isilon/dbhi_bfx/rathik/mendelian_rnaseq/gatk_output/27571P_gatk3/Sample_1__27571P-dedup.splitN_chrX_2_converted.fastq.gz with Salmon.
[2019-06-03T18:14Z] Version Info: This is the most recent version of salmon.
[2019-06-03T18:14Z] ### salmon (mapping-based) v0.14.0
[2019-06-03T18:14Z] ### [ program ] => salmon
[2019-06-03T18:14Z] ### [ command ] => quant
[2019-06-03T18:14Z] ### [ libType ] => { IU }
[2019-06-03T18:14Z] ### [ index ] => { /mnt/isilon/dbhi_bfx/rathik/mendelian_rnaseq/gatk_output/27571P_gatk3/salmon/index/GRCh37 }
[2019-06-03T18:14Z] ### [ threads ] => { 2 }
[2019-06-03T18:14Z] ### [ seqBias ] => { }
[2019-06-03T18:14Z] ### [ output ] => { /mnt/isilon/dbhi_bfx/rathik/mendelian_rnaseq/gatk_output/27571P_gatk3/bcbiotx/tmpj30ii9a7/quant }
[2019-06-03T18:14Z] ### [ gcBias ] => { }
[2019-06-03T18:14Z] ### [ mates1 ] => { /dev/fd/63 }
[2019-06-03T18:14Z] ### [ mates2 ] => { /dev/fd/62 }
[2019-06-03T18:14Z] ### [ numBootstraps ] => { 30 }
[2019-06-03T18:14Z] Logs will be written to /mnt/isilon/dbhi_bfx/rathik/mendelian_rnaseq/gatk_output/27571P_gatk3/bcbiotx/tmpj30ii9a7/quant/logs
[2019-06-03T18:14Z] [2019-06-03 14:14:07.009] [jointLog] [info] Fragment incompatibility prior below threshold.  Incompatible fragments will be ignored.
[2019-06-03T18:14Z] [2019-06-03 14:14:07.009] [jointLog] [warning]
[2019-06-03T18:14Z] NOTE: It appears you are running salmon without the `--validateMappings` option.
[2019-06-03T18:14Z] Mapping validation can generally improve both the sensitivity and specificity of mapping,
[2019-06-03T18:14Z] with only a moderate increase in use of computational resources.
[2019-06-03T18:14Z] Mapping validation is planned to become a default option (i.e. turned on by default) in
[2019-06-03T18:14Z] the next release of salmon.
[2019-06-03T18:14Z] Unless there is a specific reason to do this (e.g. testing on clean simulated data),
[2019-06-03T18:14Z] `--validateMappings` is generally recommended.
[2019-06-03T18:14Z] [2019-06-03 14:14:07.009] [jointLog] [info] parsing read library format
[2019-06-03T18:14Z] [2019-06-03 14:14:07.009] [jointLog] [info] There is 1 library.
[2019-06-03T18:14Z] [2019-06-03 14:14:07.123] [jointLog] [info] Loading Quasi index
[2019-06-03T18:14Z] [2019-06-03 14:14:07.124] [jointLog] [info] Loading 32-bit quasi index
[2019-06-03T18:14Z] [2019-06-03 14:14:07.125] [stderrLog] [info] Loading Suffix Array
[2019-06-03T18:14Z] [2019-06-03 14:14:08.497] [stderrLog] [info] Loading Transcript Info
[2019-06-03T18:14Z] [2019-06-03 14:14:08.776] [stderrLog] [info] Loading Rank-Select Bit Array
[2019-06-03T18:14Z] [2019-06-03 14:14:08.833] [stderrLog] [info] There were 194,993 set bits in the bit array
[2019-06-03T18:14Z] [2019-06-03 14:14:08.860] [stderrLog] [info] Computing transcript lengths
[2019-06-03T18:14Z] [2019-06-03 14:14:08.860] [stderrLog] [info] Waiting to finish loading hash
[2019-06-03T18:14Z] [2019-06-03 14:14:17.674] [jointLog] [info] done
[2019-06-03T18:14Z] [2019-06-03 14:14:17.674] [jointLog] [info] Index contained 194,993 targets
processed 3,500,000 fragments03 14:14:17.674] [stderrLog] [info] Done loading index
[2019-06-03T18:14Z] hits: 9,383,452, hits per frag:  2.68867
[2019-06-03T18:14Z] [2019-06-03 14:14:59.341] [jointLog] [info] Computed 12,258 rich equivalence classes for further processing
[2019-06-03T18:14Z] [2019-06-03 14:14:59.341] [jointLog] [info] Counted 3,471,592 total reads in the equivalence classes
[2019-06-03T18:14Z] [2019-06-03 14:14:59.345] [jointLog] [info] Number of fragments discarded because they have only dovetail (discordant) mappings : 12,280
[2019-06-03T18:14Z] [2019-06-03 14:14:59.403] [jointLog] [warning] Only 3471592 fragments were mapped, but the number of burn-in fragments was set to 5000000.
[2019-06-03T18:14Z] The effective lengths have been computed using the observed mappings.
[2019-06-03T18:14Z] [2019-06-03 14:14:59.403] [jointLog] [info] Mapping rate = 91.5431%
[2019-06-03T18:14Z] [2019-06-03 14:14:59.403] [jointLog] [info] finished quantifyLibrary()
[2019-06-03T18:14Z] [2019-06-03 14:14:59.438] [jointLog] [info] Starting optimizer
[2019-06-03T18:14Z] [2019-06-03 14:14:59.543] [jointLog] [info] Marked 0 weighted equivalence classes as degenerate
[2019-06-03T18:14Z] [2019-06-03 14:14:59.569] [jointLog] [info] iteration = 0 | max rel diff. = 1655.63
[2019-06-03T18:14Z] [2019-06-03 14:14:59.777] [jointLog] [info] iteration 11, adjusting effective lengths to account for biases
[2019-06-03T18:15Z] [2019-06-03 14:15:23.567] [jointLog] [info] Computed expected counts (for bias correction)
[2019-06-03T18:15Z] [2019-06-03 14:15:23.568] [jointLog] [info] processed bias for 0.0% of the transcripts
[2019-06-03T18:15Z] [2019-06-03 14:15:44.628] [jointLog] [info] processed bias for 100.0% of the transcripts
[2019-06-03T18:15Z] [2019-06-03 14:15:45.492] [jointLog] [info] iteration = 100 | max rel diff. = 1.4007
[2019-06-03T18:15Z] [2019-06-03 14:15:46.336] [jointLog] [info] iteration = 200 | max rel diff. = 1.19872
[2019-06-03T18:15Z] [2019-06-03 14:15:47.198] [jointLog] [info] iteration = 300 | max rel diff. = 0.383948
[2019-06-03T18:15Z] [2019-06-03 14:15:48.032] [jointLog] [info] iteration = 400 | max rel diff. = 0.0317077
[2019-06-03T18:15Z] [2019-06-03 14:15:48.738] [jointLog] [info] iteration = 486 | max rel diff. = 0.00595611
[2019-06-03T18:15Z] [2019-06-03 14:15:48.757] [jointLog] [info] Finished optimizer
[2019-06-03T18:15Z] [2019-06-03 14:15:48.757] [jointLog] [info] writing output
[2019-06-03T18:15Z] [2019-06-03 14:15:49.059] [jointLog] [info] Starting Bootstrapping
[2019-06-03T18:15Z] [2019-06-03 14:15:49.066] [jointLog] [info] Will draw 30 bootstrap samples
[2019-06-03T18:15Z] [2019-06-03 14:15:49.066] [jointLog] [info] Optimizing over 12,258 equivalence classes
[2019-06-03T18:15Z] [2019-06-03 14:15:49.074] [jointLog] [info] Marked 0 weighted equivalence classes as degenerate
[2019-06-03T18:15Z] [2019-06-03 14:15:58.642] [jointLog] [info] wrote 1 bootstraps
[2019-06-03T18:16Z] [2019-06-03 14:16:07.156] [jointLog] [info] wrote 2 bootstraps
[2019-06-03T18:16Z] [2019-06-03 14:16:20.653] [jointLog] [info] wrote 3 bootstraps
[2019-06-03T18:16Z] [2019-06-03 14:16:31.130] [jointLog] [info] wrote 4 bootstraps
[2019-06-03T18:16Z] [2019-06-03 14:16:38.805] [jointLog] [info] wrote 5 bootstraps
[2019-06-03T18:16Z] [2019-06-03 14:16:47.938] [jointLog] [info] wrote 6 bootstraps
[2019-06-03T18:16Z] [2019-06-03 14:16:56.876] [jointLog] [info] wrote 7 bootstraps
[2019-06-03T18:17Z] [2019-06-03 14:17:07.423] [jointLog] [info] wrote 8 bootstraps
[2019-06-03T18:17Z] [2019-06-03 14:17:13.469] [jointLog] [info] wrote 9 bootstraps
[2019-06-03T18:17Z] [2019-06-03 14:17:20.129] [jointLog] [info] wrote 10 bootstraps
[2019-06-03T18:17Z] [2019-06-03 14:17:31.399] [jointLog] [info] wrote 11 bootstraps
[2019-06-03T18:17Z] [2019-06-03 14:17:43.045] [jointLog] [info] wrote 12 bootstraps
[2019-06-03T18:17Z] [2019-06-03 14:17:54.310] [jointLog] [info] wrote 13 bootstraps
[2019-06-03T18:18Z] [2019-06-03 14:18:01.399] [jointLog] [info] wrote 14 bootstraps
[2019-06-03T18:18Z] [2019-06-03 14:18:09.802] [jointLog] [info] wrote 15 bootstraps
[2019-06-03T18:18Z] [2019-06-03 14:18:18.861] [jointLog] [info] wrote 16 bootstraps
[2019-06-03T18:18Z] [2019-06-03 14:18:26.019] [jointLog] [info] wrote 17 bootstraps
[2019-06-03T18:18Z] [2019-06-03 14:18:37.824] [jointLog] [info] wrote 18 bootstraps
[2019-06-03T18:18Z] [2019-06-03 14:18:49.561] [jointLog] [info] wrote 19 bootstraps
[2019-06-03T18:18Z] [2019-06-03 14:18:59.337] [jointLog] [info] wrote 20 bootstraps
[2019-06-03T18:19Z] [2019-06-03 14:19:08.599] [jointLog] [info] wrote 21 bootstraps
[2019-06-03T18:19Z] [2019-06-03 14:19:17.153] [jointLog] [info] wrote 22 bootstraps
[2019-06-03T18:19Z] [2019-06-03 14:19:26.864] [jointLog] [info] wrote 23 bootstraps
[2019-06-03T18:19Z] [2019-06-03 14:19:36.771] [jointLog] [info] wrote 24 bootstraps
[2019-06-03T18:19Z] [2019-06-03 14:19:43.770] [jointLog] [info] wrote 25 bootstraps
[2019-06-03T18:19Z] [2019-06-03 14:19:54.561] [jointLog] [info] wrote 26 bootstraps
[2019-06-03T18:20Z] [2019-06-03 14:20:07.015] [jointLog] [info] wrote 27 bootstraps
[2019-06-03T18:20Z] [2019-06-03 14:20:14.029] [jointLog] [info] wrote 28 bootstraps
[2019-06-03T18:20Z] [2019-06-03 14:20:20.663] [jointLog] [info] wrote 29 bootstraps
[2019-06-03T18:20Z] [2019-06-03 14:20:31.170] [jointLog] [info] wrote 30 bootstraps
[2019-06-03T18:20Z] [2019-06-03 14:20:31.174] [jointLog] [info] Finished Bootstrapping
[2019-06-03T18:20Z] Converting Sailfish to Sleuth format.
[2019-06-03T18:20Z] Error in readBin(bootCon, "integer", n = expected.n) :
[2019-06-03T18:20Z]   invalid 'n' argument
[2019-06-03T18:20Z] Calls: prepare_fish_for_sleuth ... tryCatchList -> tryCatchOne -> <Anonymous> -> readBin
[2019-06-03T18:20Z] Execution halted
[2019-06-03T18:20Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /mnt/isilon/dbhi_bfx/bin/bcbio-nextgen/bcbio/anaconda/bin/Rscript --no-environ -e 'library("wasabi"); prepare_fish_for_sleuth(c("/mnt/isilon/dbhi_bfx/rathik/mendelian_rnaseq/gatk_output/27571P_gatk3/bcbiotx/tmpj30ii9a7/quant"))'
Error in readBin(bootCon, "integer", n = expected.n) : 
  invalid 'n' argument
Calls: prepare_fish_for_sleuth ... tryCatchList -> tryCatchOne -> <Anonymous> -> readBin
Execution halted
' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/local/bin/bcbio_nextgen.py", line 238, in <module>
    main(**kwargs)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/local/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 253, in rnaseqpipeline
    samples = rnaseq.quantitate_expression_parallel(samples, run_parallel)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/rnaseq.py", line 207, in quantitate_expression_parallel
    samples = run_parallel("run_salmon_reads", samples)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 949, in __call__
    if self.dispatch_one_batch(iterator):
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 791, in dispatch_one_batch
    self._dispatch(tasks)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 748, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 183, in apply_async
    result = ImmediateResult(func)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 543, in __init__
    self.results = batch()
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 224, in __call__
    for func, args, kwargs in self.items]
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 224, in <listcomp>
    for func, args, kwargs in self.items]
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 63, in run_salmon_reads
    return salmon.run_salmon_reads(*args)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python3.6/site-packages/bcbio/rnaseq/salmon.py", line 49, in run_salmon_reads
    out_file = salmon_quant_reads(fq1, fq2, salmon_dir, gtf_file, fasta_file, data)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python3.6/site-packages/bcbio/rnaseq/salmon.py", line 91, in salmon_quant_reads
    sailfish.sleuthify_sailfish(tx_out_dir)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python3.6/site-packages/bcbio/rnaseq/sailfish.py", line 76, in sleuthify_sailfish
    do.run(cmd.format(**locals()), "Converting Sailfish to Sleuth format.")
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /mnt/isilon/dbhi_bfx/bin/bcbio-nextgen/bcbio/anaconda/bin/Rscript --no-environ -e 'library("wasabi"); prepare_fish_for_sleuth(c("/mnt/isilon/dbhi_bfx/rathik/mendelian_rnaseq/gatk_output/27571P_gatk3/bcbiotx/tmpj30ii9a7/quant"))'
Error in readBin(bootCon, "integer", n = expected.n) : 
  invalid 'n' argument
Calls: prepare_fish_for_sleuth ... tryCatchList -> tryCatchOne -> <Anonymous> -> readBin
Execution halted
' returned non-zero exit status 1.
```

**Comment by roryk** [comment]
Hi Komal,

Salmon 0.14 was released yesterday, which I guess wasabi doesn't support, I just opened up an issue on their repository. I'm working on supporting Salmon 0.14 in bcbio, but it will be a few days before I can finish it. In the meantime you can install salmon 0.13 by doing:

```
bcbio_conda install -c bioconda salmon=0.13.1
```

which will fix this problem.

**Comment by rob-p** [comment]
@roryk --- nothing explicit about 0.14.0 should break wasabi, but if you happen to have a MWE, I'd be happy to take a look and figure out a fix.

**Comment by roryk** [comment]
Thanks! It might be a red herring, I'll close and re-open if it turns out to be a wasabi problem. Sorry about that.

**Comment by komalsrathi** [comment]
I reinstalled Salmon 0.13.1 and it worked. Thanks!

**Comment by roryk** [comment]
Hi @rob-p,

I attached a tiny example where it isn't working-- I ran our mini test suite and copied the quant directories for a 0.13 and a 0.14 run. The 0.14 run gives the same error as in this issue but 0.13 works fine.

[wasabi-example.tar.gz](https://github.com/bcbio/bcbio-nextgen/files/3249088/wasabi-example.tar.gz)

**Comment by rob-p** [comment]
Ahh, I see what it is.  Since v0.14.0 incorporates the decoy-aware transcriptome, what was previously 
`num_targets`, was renamed to `num_valid_targets` within `meta_info.json`.  I can fix this upstream in wasabi, but could you edit the meta_info.json in the v0.14.0 directory quickly and see if that fixes the issue?

**Comment by roryk** [comment]
Awesome, thanks so much. Yup, that fixed it.

**Comment by roryk** [comment]
Hi @komalsrathi,

The new version of wasabi which supports Salmon 0.14 is up on bioconda now, so this issue should be all set going forward. Thanks everyone!
