### ISSUE TITLE
chipseq pipeline failing unit tests on clean install

### ISSUE THREAD

**Issue by mjsteinbaugh** [bcbio/bcbio-nextgen#2853]
I'm seeing a macs2 issue that I think is related to conda, popping up on one of my VMs with a clean install of bcbio:

```sh
./run_tests.sh chipseq
```

```
[2019-06-10T20:36Z] Resource requests: macs2; memory: 8.00; cores: 1
[2019-06-10T20:36Z] Configuring 1 jobs to run, using 1 cores each with 8.00g of memory reserved for each job
[2019-06-10T20:36Z] Timing: peakcalling
[2019-06-10T20:36Z] Skipping peak calling. No input sample for Test1
[2019-06-10T20:36Z] multiprocessing: peakcalling
[2019-06-10T20:36Z] macs2 for Test2
[2019-06-10T20:36Z] Traceback (most recent call last):
[2019-06-10T20:36Z]   File "/data00/bcbio/v1.1.5/tools/bin/macs2", line 622, in <module>
[2019-06-10T20:36Z]     main()
[2019-06-10T20:36Z]   File "/data00/bcbio/v1.1.5/tools/bin/macs2", line 56, in main
[2019-06-10T20:36Z]     from MACS2.callpeak_cmd import run
[2019-06-10T20:36Z]   File "/data00/bcbio/v1.1.5/install/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 31, in <module>
[2019-06-10T20:36Z]     from MACS2.OptValidator import opt_validate
[2019-06-10T20:36Z]   File "/data00/bcbio/v1.1.5/install/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/OptValidator.py", line 27, in <module>
[2019-06-10T20:36Z]     from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
[2019-06-10T20:36Z]   File "__init__.pxd", line 861, in init MACS2.IO.Parser (MACS2/IO/Parser.c:22634)
[2019-06-10T20:36Z] ValueError: numpy.ufunc has the wrong size, try recompiling
[2019-06-10T20:36Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/data00/bcbio/v1.1.5/install/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/data00/bcbio/v1.1.5/install/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /data00/bcbio/v1.1.5/tools/bin/macs2 callpeak -t /data00/bcbio/git/tests/test_automated_output/align/Test2/Test2-sort.unique_chrom.bam -c /data00/bcbio/git/tests/test_automated_output/align/Test1/Test1-sort.unique_chrom.bam   -g 36572 -n Test2 -B --nomodel
Traceback (most recent call last):
  File "/data00/bcbio/v1.1.5/tools/bin/macs2", line 622, in <module>
    main()
  File "/data00/bcbio/v1.1.5/tools/bin/macs2", line 56, in main
    from MACS2.callpeak_cmd import run
  File "/data00/bcbio/v1.1.5/install/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 31, in <module>
    from MACS2.OptValidator import opt_validate
  File "/data00/bcbio/v1.1.5/install/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/OptValidator.py", line 27, in <module>
    from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
  File "__init__.pxd", line 861, in init MACS2.IO.Parser (MACS2/IO/Parser.c:22634)
ValueError: numpy.ufunc has the wrong size, try recompiling
' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/data00/bcbio/v1.1.5/install/anaconda/lib/python3.6/site-packages/bcbio/chipseq/macs2.py", line 31, in run
    do.run(cmd.format(**locals()), "macs2 for %s" % name)
  File "/data00/bcbio/v1.1.5/install/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/data00/bcbio/v1.1.5/install/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /data00/bcbio/v1.1.5/tools/bin/macs2 callpeak -t /data00/bcbio/git/tests/test_automated_output/align/Test2/Test2-sort.unique_chrom.bam -c /data00/bcbio/git/tests/test_automated_output/align/Test1/Test1-sort.unique_chrom.bam   -g 36572 -n Test2 -B --nomodel
Traceback (most recent call last):
  File "/data00/bcbio/v1.1.5/tools/bin/macs2", line 622, in <module>
    main()
  File "/data00/bcbio/v1.1.5/tools/bin/macs2", line 56, in main
    from MACS2.callpeak_cmd import run
  File "/data00/bcbio/v1.1.5/install/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 31, in <module>
    from MACS2.OptValidator import opt_validate
  File "/data00/bcbio/v1.1.5/install/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/OptValidator.py", line 27, in <module>
    from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
  File "__init__.pxd", line 861, in init MACS2.IO.Parser (MACS2/IO/Parser.c:22634)
ValueError: numpy.ufunc has the wrong size, try recompiling
' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data00/bcbio/v1.1.5/tools/bin/bcbio_nextgen.py", line 238, in <module>
    main(**kwargs)
  File "/data00/bcbio/v1.1.5/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/data00/bcbio/v1.1.5/install/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/data00/bcbio/v1.1.5/install/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/data00/bcbio/v1.1.5/install/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 380, in chipseqpipeline
```

I can reproduce this error installing the development version of bcbio from GitHub as well.

**Comment by mjsteinbaugh** [comment]
This error related to numpy is new, and I wasn't seeing it in bcbio installs last month:

```
ValueError: numpy.ufunc has the wrong size, try recompiling
```

**Comment by roryk** [comment]
We've run into this before, I think if you look in site-packages/numpy, you'll see multiple versions of numpy there. If that is true, if you just delete them all and re-install numpy from conda it should fix this problem. I don't know how the different versions are getting stuck in there, but they are.

**Comment by mjsteinbaugh** [comment]
OK for reference, here's what I'm seeing on my machine:

```
./anaconda/envs/python2/lib/python2.7/site-packages/numpy
./anaconda/envs/python2/lib/python2.7/site-packages/numpy-1.15.4.dist-info
./anaconda/envs/python3/lib/python3.6/site-packages/numpy
./anaconda/envs/python3/lib/python3.6/site-packages/numpy-1.16.4.dist-info

./anaconda/lib/python3.6/site-packages/numpy
./anaconda/lib/python3.6/site-packages/numpy-1.16.4.dist-info

./anaconda/pkgs/numpy-1.14.6-py27he5ce36f_1201
./anaconda/pkgs/numpy-1.14.6-py27he5ce36f_1201/lib/python2.7/site-packages/numpy
./anaconda/pkgs/numpy-1.14.6-py27he5ce36f_1201/lib/python2.7/site-packages/numpy-1.14.6.dist-info
./anaconda/pkgs/numpy-1.14.6-py27he5ce36f_1201/lib/python2.7/site-packages/numpy/core/include/numpy
./anaconda/pkgs/numpy-1.15.4-py27_blas_openblash1522bff_1000
./anaconda/pkgs/numpy-1.15.4-py27_blas_openblash1522bff_1000/lib/python2.7/site-packages/numpy
./anaconda/pkgs/numpy-1.15.4-py27_blas_openblash1522bff_1000/lib/python2.7/site-packages/numpy-1.15.4.dist-info
./anaconda/pkgs/numpy-1.15.4-py27_blas_openblash1522bff_1000/lib/python2.7/site-packages/numpy/core/include/numpy
./anaconda/pkgs/numpy-1.16.4-py36h95a1406_0
./anaconda/pkgs/numpy-1.16.4-py36h95a1406_0/lib/python3.6/site-packages/numpy
./anaconda/pkgs/numpy-1.16.4-py36h95a1406_0/lib/python3.6/site-packages/numpy-1.16.4.dist-info
./anaconda/pkgs/numpy-1.16.4-py36h95a1406_0/lib/python3.6/site-packages/numpy/core/include/numpy
```

**Comment by mjsteinbaugh** [comment]
PS The unit tests are working fine for v1.1.3 on my machine, only erroring out on v1.1.5 and/or development installs, so I'm guessing this is a Python 2.7 / 3.6 issue.

**Comment by mjsteinbaugh** [comment]
See related issue #1105

**Comment by mjsteinbaugh** [comment]
Here are the numpy versions in the relevant conda environments:

```sh
conda env list
```

```
# conda environments:
#
                         /data00/bcbio/development/install/anaconda
                         /data00/bcbio/development/install/anaconda/envs/dv
                         /data00/bcbio/development/install/anaconda/envs/python2
                         /data00/bcbio/development/install/anaconda/envs/python3
                         /data00/bcbio/development/install/anaconda/envs/samtools0
base                  *  /usr/local/miniconda3
```

```sh
conda list -p /data00/bcbio/development/install/anaconda | grep numpy
```

```
numpy                     1.16.4           py36h95a1406_0    conda-forge
```

```sh
conda list -p /data00/bcbio/development/install/anaconda/envs/dv | grep numpy
```

```
numpy                     1.14.6          py27he5ce36f_1201    conda-forge
```

```sh
conda list -p /data00/bcbio/development/install/anaconda/envs/python2 | grep numpy
```

```
numpy                     1.15.4          py27_blas_openblash1522bff_1000  [blas_openblas]  conda-forge
```

```sh
conda list -p /data00/bcbio/development/install/anaconda/envs/python3 | grep numpy
```

```
numpy                     1.16.4           py36h95a1406_0    conda-forge
```

**Comment by mjsteinbaugh** [comment]
I can confirm that upgrading numpy in the python2 environment fixes this issue, and the chipseq unit test will then pass.

```sh
bcbio_conda install --name python2 numpy
```

```
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /data00/bcbio/development/install/anaconda/envs/python2

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-1.16.4               |   py27h95a1406_0         4.2 MB  conda-forge
    optitype-1.3.2             |           py27_1         4.6 MB  bioconda
    phylowgs-20150714          |           py27_1         930 KB  bioconda
    scikit-learn-0.20.3        |   py27ha8026db_1         5.8 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        15.5 MB

The following packages will be UPDATED:

  blas                                         1.1-openblas --> 2.7-openblas
  gsl                        2.4-blas_openblash5c7cb9b_1004 --> 2.4-h294904e_1006
  libblas                           3.8.0-5_h6e990d7_netlib --> 3.8.0-7_openblas
  libcblas                          3.8.0-5_h6e990d7_netlib --> 3.8.0-7_openblas
  liblapack                         3.8.0-5_h6e990d7_netlib --> 3.8.0-7_openblas
  liblapacke                        3.8.0-5_h6e990d7_netlib --> 3.8.0-7_openblas
  numpy              1.15.4-py27_blas_openblash1522bff_1000 --> 1.16.4-py27h95a1406_0
  openblas                              0.3.3-h9ac9557_1001 --> 0.3.5-h9ac9557_1001
  scikit-learn          0.20.3-py27_blas_openblashebff5e3_0 --> 0.20.3-py27ha8026db_1
  scipy                  1.2.1-py27_blas_openblash1522bff_0 --> 1.2.1-py27h09a28d5_1

The following packages will be DOWNGRADED:

  optitype                                     1.3.2-py27_3 --> 1.3.2-py27_1
  phylowgs                          20181105-py27hc2ebfaa_0 --> 20150714-py27_1
```

```sh
bcbio_conda list --name python2 | grep numpy
```

```
numpy                     1.16.4           py27h95a1406_0    conda-forge
```

**Comment by roryk** [comment]
Thanks, we've fixed a bunch of install issues since this issue was open. Please let us know if this isn't working now, I think it should be fine.
