### ISSUE TITLE
GATK4: creating a panel of normals fails

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2875]
I have a setup with 1 tumor sample and 20+ normal samples. I wanted to create a reference for both CNVkit and GATK CNV:

```yaml
# Example normal
- algorithm:
       aligner: false
       exclude_regions:
       - altcontigs
       - highdepth
       - polyx
       mark_duplicates: false
       mixup_check: qsignature
       platform: illumina
       quality_format: Standard
       realign: false
       recalibrate: false
       variant_regions: my_regions
       svcaller:
       - cnvkit
       - gatk-cnv
       tools_off: upload_alignment
       tools_on: svplots
       variantcaller: false
     analysis: variant2
     description: 18-blood
          metadata:
       batch: exome-pon
       phenotype: normal
       sex: female
       svclass: background
[...]
# Example tumor
 - algorithm:
       aligner: false
       exclude_regions:
       - altcontigs
       - highdepth
       - polyx
       mark_duplicates: false
       mixup_check: qsignature
       platform: illumina
       quality_format: Standard
       realign: false
       recalibrate: false
       variant_regions: my_regions
       svcaller:
       - cnvkit
       - gatk-cnv
       tools_off: upload_alignment
       tools_on: svplots
       variantcaller: false
     analysis: variant2
     description: '115'
     files:
     - 115-ready.bam
     genome_build: hg38
     metadata:
       batch: exome-pon
       phenotype: tumor
       sex: female
```

However, later on, the GATK tries to use the CNVkit sgmented output as its input in `ModelSegments` and badly fails due to:

a. The file missing a SAM-style header
b. "Out of order" chromosome names (alt contigs after regular oens)

```
java.lang.IllegalArgumentException: The collection is empty: The input header does not contain any read groups.  Cannot determine a sample name.
        at org.broadinstitute.hellbender.utils.Utils.nonEmpty(Utils.java:618)
        at org.broadinstitute.hellbender.tools.copynumber.formats.metadata.MetadataUtils.readSampleName(MetadataUtils.java:23)
        at org.broadinstitute.hellbender.tools.copynumber.formats.metadata.MetadataUtils.fromHeader(MetadataUtils.java:46)
        at org.broadinstitute.hellbender.tools.copynumber.formats.collections.AbstractRecordCollection.<init>(AbstractRecordCollection.java:82)
        at org.broadinstitute.hellbender.tools.copynumber.formats.collections.AbstractLocatableCollection.<init>(AbstractLocatableCollection.java:58)
        at org.broadinstitute.hellbender.tools.copynumber.formats.collections.AbstractSampleLocatableCollection.<init>(AbstractSampleLocatableCollection.java:44)
        at org.broadinstitute.hellbender.tools.copynumber.formats.collections.CopyRatioCollection.<init>(CopyRatioCollection.java:49)
        at org.broadinstitute.hellbender.tools.copynumber.ModelSegments.readOptionalFileOrNull(ModelSegments.java:599)
        at org.broadinstitute.hellbender.tools.copynumber.ModelSegments.doWork(ModelSegments.java:480)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
        at org.broadinstitute.hellbender.Main.main(Main.java:291)
```

I take this was never supposed to happen. I'll re-test shortly with only `gatk-cnv`.

**Comment by lbeltrame** [comment]
And my tests confirm my initial suspicion: you *can't* make a panel of normals with at least CNVkit and GATK together. 

That's because 

https://github.com/bcbio/bcbio-nextgen/blob/5786cb7a951a402c06e66980d93d3cc91e2424c1/bcbio/structural/gatkcnv.py#L87 

ends up finding the already-processed CNVkit file.

**Comment by chapmanb** [comment]
Luca;
Apologies about the issues and thanks for identifying the root cause. You're right that these should not be used together due to differences in normalization. The documentation and latest development now mention this and raise an error if used together. Hope creating them separately works for your needs.
