### ISSUE TITLE
error with macs2 peak calling

### ISSUE THREAD

**Issue by PatrickJReed** [bcbio/bcbio-nextgen#2877]
Hey all, 

I'm running up against an issue with a chip-seq pipeline. It's crashing when it gets to macs...
Any help would be appreciated...
Point in output where crashes:

[2019-07-10T18:55Z] Timing: disambiguation
[2019-07-10T18:55Z] multiprocessing: clean_chipseq_alignment
[2019-07-10T19:07Z] Resource requests: macs2; memory: 8.00; cores: 1
[2019-07-10T19:07Z] Configuring 24 jobs to run, using 1 cores each with 8.00g of memory reserved for each job
[2019-07-10T19:07Z] Timing: peakcalling
[2019-07-10T19:07Z] Skipping peak calling. No input sample for H1_Input
[2019-07-10T19:07Z] Skipping peak calling. No input sample for H9_Input
[2019-07-10T19:07Z] multiprocessing: peakcalling
[2019-07-10T19:08Z] macs2 for H1UNG_Cas9empty_14_B
[2019-07-10T19:08Z] macs2 for H1UNG_Cas9guides_14_A
[2019-07-10T19:08Z] Traceback (most recent call last):
[2019-07-10T19:08Z]   File "/usr/local/bin/macs2", line 622, in <module>
[2019-07-10T19:08Z]     main()
[2019-07-10T19:08Z]   File "/usr/local/bin/macs2", line 56, in main
[2019-07-10T19:08Z]     from MACS2.callpeak_cmd import run
[2019-07-10T19:08Z]   File "/usr/local/share/bcbio/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 31, in <module>
[2019-07-10T19:08Z]     from MACS2.OptValidator import opt_validate
[2019-07-10T19:08Z]   File "/usr/local/share/bcbio/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/OptValidator.py", line 27, in <module>
[2019-07-10T19:08Z]     from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
[2019-07-10T19:08Z]   File "__init__.pxd", line 861, in init MACS2.IO.Parser (MACS2/IO/Parser.c:22634)
[2019-07-10T19:08Z] ValueError: numpy.ufunc has the wrong size, try recompiling
[2019-07-10T19:08Z] Traceback (most recent call last):
[2019-07-10T19:08Z]   File "/usr/local/bin/macs2", line 622, in <module>
[2019-07-10T19:08Z]     main()
[2019-07-10T19:08Z]   File "/usr/local/bin/macs2", line 56, in main
[2019-07-10T19:08Z]     from MACS2.callpeak_cmd import run
[2019-07-10T19:08Z]   File "/usr/local/share/bcbio/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 31, in <module>
[2019-07-10T19:08Z]     from MACS2.OptValidator import opt_validate
[2019-07-10T19:08Z]   File "/usr/local/share/bcbio/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/OptValidator.py", line 27, in <module>
[2019-07-10T19:08Z]     from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
[2019-07-10T19:08Z]   File "__init__.pxd", line 861, in init MACS2.IO.Parser (MACS2/IO/Parser.c:22634)
[2019-07-10T19:08Z] ValueError: numpy.ufunc has the wrong size, try recompiling
[2019-07-10T19:08Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /usr/local/bin/macs2 callpeak -t /raidixshare_log-g/Dylan/190617_PE75/RepairSeq_062819/work/align/H1UNG_Cas9empty_14_B/H1UNG_Cas9empty_14_B-sort.unique_chrom.bam -c /raidixshare_log-g/Dylan/190617_PE75/RepairSeq_062819/work/align/H1_Input/H1_Input-sort.unique_chrom.bam -f BAMPE  -g 3217346917 -n H1UNG_Cas9empty_14_B -B
Traceback (most recent call last):
  File "/usr/local/bin/macs2", line 622, in <module>
    main()
  File "/usr/local/bin/macs2", line 56, in main
    from MACS2.callpeak_cmd import run
  File "/usr/local/share/bcbio/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 31, in <module>
    from MACS2.OptValidator import opt_validate
  File "/usr/local/share/bcbio/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/OptValidator.py", line 27, in <module>
    from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
  File "__init__.pxd", line 861, in init MACS2.IO.Parser (MACS2/IO/Parser.c:22634)
ValueError: numpy.ufunc has the wrong size, try recompiling
' returned non-zero exit status 1.
[2019-07-10T19:08Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /usr/local/bin/macs2 callpeak -t /raidixshare_log-g/Dylan/190617_PE75/RepairSeq_062819/work/align/H1UNG_Cas9guides_14_A/H1UNG_Cas9guides_14_A-sort.unique_chrom.bam -c /raidixshare_log-g/Dylan/190617_PE75/RepairSeq_062819/work/align/H1_Input/H1_Input-sort.unique_chrom.bam -f BAMPE  -g 3217346917 -n H1UNG_Cas9guides_14_A -B
Traceback (most recent call last):
  File "/usr/local/bin/macs2", line 622, in <module>
    main()
  File "/usr/local/bin/macs2", line 56, in main
    from MACS2.callpeak_cmd import run
  File "/usr/local/share/bcbio/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 31, in <module>
    from MACS2.OptValidator import opt_validate
  File "/usr/local/share/bcbio/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/OptValidator.py", line 27, in <module>
    from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
  File "__init__.pxd", line 861, in init MACS2.IO.Parser (MACS2/IO/Parser.c:22634)
ValueError: numpy.ufunc has the wrong size, try recompiling
' returned non-zero exit status 1.

my config is here:
details:
- analysis: chip-seq
  metadata:
    description:
  genome_build: hg38
  algorithm:
    aligner: bowtie2
    trim_reads: read_through
    peakcaller: [macs2]

**Comment by chapmanb** [comment]
Patrick;
Thanks for the report and apologies about the issues. It looks like an incorrect numpy environment gets imported compared to what macs expects:
```
ValueError: numpy.ufunc has the wrong size, try recompiling
```
This could either be due to:

- Your PYTHONPATH or `~/.local/lib/python2.7/site-packages` including a different numpy version.
- Something incorrect about numpy in your bcbio install.

If it's not a conflicting version, then you can try fixing the one in bcbio with:
```
bcbio_conda install -n python2 -c bioconda -c conda-forge numpy
```
Hope this helps identify the issue.

**Comment by PatrickJReed** [comment]
bcbio_conda install -n python2 -c bioconda -c conda-forge numpy
solved the problem, Thanks so much!

**Comment by roryk** [comment]
Thanks for closing the loop!

**Comment by lbeltrame** [comment]
We're getting the same error, but numpy is up to date:

```
/opt/bcbio/anaconda/bin/conda install -n python2 -c bioconda -c conda-forge numpy
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
```

This is kind of a blocker for many analyses, so any tips on how to fix it would be welcome.
