### ISSUE TITLE
Timeout at /home/jshi/local/share/bcbio/anaconda/lib/5.26.2/Net/FTP.pm line 583.

### ISSUE THREAD

**Issue by jxshi** [bcbio/bcbio-nextgen#2896]
Hi, 

I tried to upgrade bcbio-nextgen to the latest development version by using the following command. 
```
bcbio_nextgen.py upgrade -u development --tools --data --genomes rn6
```
But it popped up an error message when install ```vep``` data. This is the error message.
```
List of genomes to get (from the config file at '{'genomes': [{'dbkey': 'rn6', 'name': 'Rat (rn6)', 'indexes': ['seq', 'twobit'], 'annotations': ['transcripts', 'mirbase']}], 'genome_indexes': ['bwa', 'bowtie2', 'rtg', 'twobit', 'star', 'hisat2', 'bowtie'], 'install_liftover': False, 'install_uniref': False}'): Rat (rn6)
--2019-08-06 22:24:15--  http://ftp.ensembl.org/pub/release-97/variation/vep/homo_sapiens_merged_vep_97_GRCh38.tar.gz
Resolving ftp.ensembl.org (ftp.ensembl.org)... 193.62.193.8
Connecting to ftp.ensembl.org (ftp.ensembl.org)|193.62.193.8|:80... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

Traceback (most recent call last):
  File "/home/jshi/local/bin/bcbio_nextgen.py", line 221, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/home/jshi/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 106, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/home/jshi/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 352, in upgrade_bcbio_data
    _upgrade_vep_data(galaxy_home, tooldir)
  File "/home/jshi/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 402, in _upgrade_vep_data
    effects.prep_vep_cache(dbkey, ref_file, tooldir)
  File "/home/jshi/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/effects.py", line 117, in prep_vep_cache
    do.run("%s && %s" % (perl_exports, " ".join(cmd)), "Prepare VEP directory for %s" % ensembl_name)
  File "/home/jshi/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/jshi/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset PERL5LIB && export PATH=/home/jshi/local/share/bcbio/anaconda/bin:"$PATH" && /home/jshi/local/bin/vep_install -a c -s homo_sapiens_merged_vep_97_GRCh38 -c /home/jshi/local/share/bcbio/genomes/Hsapiens/hg38/vep -u /home/jshi/local/share/bcbio/genomes/Hsapiens/hg38/vep/homo_sapiens_merged/txtmp --NO_UPDATE --VERSION 97
 - getting list of available cache files
NB: Remember to use --merged when running the VEP with this cache!
 - downloading ftp://ftp.ensembl.org/pub/release-97/variation/indexed_vep_cache/homo_sapiens_merged_vep_97_GRCh38.tar.gz
Timeout at /home/jshi/local/share/bcbio/anaconda/lib/5.26.2/Net/FTP.pm line 583.
' returned non-zero exit status 255.
```

I tried to run the command separately to check if it would work. But it popped up the same error message.
```
 /home/jshi/local/bin/vep_install -a c -s homo_sapiens_merged_vep_97_GRCh38 -c /home/jshi/local/share/bcbio/genomes/Hsapiens/hg38/vep -u /home/jshi/local/share/bcbio/genomes/Hsapiens/hg38/vep/homo_sapiens_merged/txtmp --merged --NO_UPDATE --VERSION 97
```
I tried for like ten times and all failed with the same error. Can you check for me please? Thank you!

Best,
Jianxiang

**Comment by chapmanb** [comment]
Jianxiang;
Thank you for the report and apologies about the issue. This appears to be a network error which could either be caused by some problem at the Ensembl FTP site or from something in your local network.

Testing from my current location I'm able to access and download the file:
```
wget ftp://ftp.ensembl.org/pub/release-97/variation/indexed_vep_cache/homo_sapiens_merged_vep_97_GRCh38.tar.gz
```
If you retry now at a later time is it working cleanly? Does running this wget outside of the VEP download infrastructure work?

Hope this helps and things are now working cleanly.

**Comment by jxshi** [comment]
Hi @chapmanb ,

I think you are right about the problem, my server has unstable internet connections. But it's quite weird for ```bcbio-nextgen``` to download ```homo_sapiens_merged_vep_97_GRCh38.tar.gz``` file twice into two different locations.
```The file is already fully retrieved; nothing to do.```, this message indicate that ```homo_sapiens_merged_vep_97_GRCh38.tar.gz``` file has already been downloaded in the following location.
```
~/local/share/bcbio/genomes/Hsapiens/hg38/vep/tmp/
```
Then ```bcbio-nextgen``` then began to download the same file in another location, which is quite weird.
```
~/local/share/bcbio/genomes/Hsapiens/hg38/vep/homo_sapiens_merged/txtmp
```

Can you check this for me please? Thank you!

Best,
Jianxiang

**Comment by roryk** [comment]
Hi Jianxiang,

Could you post the log where you are seeing this behavior? It is hard to know what is happening without seeing the actual log.

**Comment by jxshi** [comment]
Hi @roryk ,

Here is the log when ```bcbio-nextgen``` was downloading ```homo_sapiens_merged_vep_97_GRCh38.tar.gz```.
```
# Installing into conda environment dv: deepvariant
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

# Installing into conda environment python2: bismark=0.22.1, cpat, cutadapt=1.16, dkfz-bias-filter, gemini, gvcf-regions, hap.py, hisat2, htseq=0.9.1, lumpy-sv, macs2, manta, metasv, mirge, optitype, peddy, phylowgs, platypus-variant, sentieon, smcounter2, smoove, strelka, svtools, svtyper, theta2, tophat, umis, vawk, vcf2db
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

# Installing into conda environment python3: atropos, crossmap
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

# Installing into conda environment samtools0: ericscript
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Creating manifest of installed packages in /home/jshi/local/share/bcbio/manifest
Third party tools upgrade complete.
Upgrading bcbio-nextgen data files
--2019-08-11 08:40:12--  https://github.com/chapmanb/cloudbiolinux/archive/master.tar.gz
Resolving github.com (github.com)... 13.229.188.59
Connecting to github.com (github.com)|13.229.188.59|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master [following]
--2019-08-11 08:40:18--  https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master
Resolving codeload.github.com (codeload.github.com)... 54.251.140.56
Connecting to codeload.github.com (codeload.github.com)|54.251.140.56|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘STDOUT’

     0K ........ ........ ........ ........ ........ ........ 2.11M
  3072K ........ ........ ........ .......                    8.21M=1.7s

2019-08-11 08:40:25 (2.98 MB/s) - written to stdout [5189136]

List of genomes to get (from the config file at '{'genomes': [{'dbkey': 'rn6', 'name': 'Rat (rn6)', 'indexes': ['seq', 'twobit'], 'annotations': ['transcripts', 'mirbase']}], 'genome_indexes': ['bwa', 'bowtie2', 'rtg', 'twobit', 'star', 'hisat2', 'bowtie'], 'install_liftover': False, 'install_uniref': False}'): Rat (rn6)
--2019-08-11 08:41:21--  http://ftp.ensembl.org/pub/release-97/variation/vep/homo_sapiens_merged_vep_97_GRCh38.tar.gz
Resolving ftp.ensembl.org (ftp.ensembl.org)... 193.62.193.8
Connecting to ftp.ensembl.org (ftp.ensembl.org)|193.62.193.8|:80... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.
```
 While it's downloading, I manually checked the following file folder where the file was stored: ```~/local/share/bcbio/genomes/Hsapiens/hg38/vep/homo_sapiens_merged/txtmp
```. When the file size reached around 16GB, it stopped to increase. Then ```bcbio-nextgen``` removed the file and began to download ```homo_sapiens_merged_vep_97_GRCh38.tar.gz``` again.

When the internet met intermittent error, the following error message popped up:
```
    The file is already fully retrieved; nothing to do.

Traceback (most recent call last):
  File "/home/jshi/local/bin/bcbio_nextgen.py", line 221, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/home/jshi/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 106, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/home/jshi/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 352, in upgrade_bcbio_data
    _upgrade_vep_data(galaxy_home, tooldir)
  File "/home/jshi/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 402, in _upgrade_vep_data
    effects.prep_vep_cache(dbkey, ref_file, tooldir)
  File "/home/jshi/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/effects.py", line 117, in prep_vep_cache
    do.run("%s && %s" % (perl_exports, " ".join(cmd)), "Prepare VEP directory for %s" % ensembl_name)
  File "/home/jshi/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/jshi/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset PERL5LIB && export PATH=/home/jshi/local/share/bcbio/anaconda/bin:"$PATH" && /home/jshi/local/bin/vep_install -a c -s homo_sapiens_merged_vep_97_GRCh38 -c /home/jshi/local/share/bcbio/genomes/Hsapiens/hg38/vep -u /home/jshi/local/share/bcbio/genomes/Hsapiens/hg38/vep/homo_sapiens_merged/txtmp --NO_UPDATE --VERSION 97
 - getting list of available cache files
NB: Remember to use --merged when running the VEP with this cache!
 - downloading ftp://ftp.ensembl.org/pub/release-97/variation/indexed_vep_cache/homo_sapiens_merged_vep_97_GRCh38.tar.gz
Timeout at /home/jshi/local/share/bcbio/anaconda/lib/5.26.2/Net/FTP.pm line 583.
' returned non-zero exit status 255.
```

**Comment by jxshi** [comment]
Hi @roryk ,

I manually downloaded ```homo_sapiens_merged_vep_97_GRCh38.tar.gz``` and unzipped it in ```~/local/share/bcbio/genomes/Hsapiens/hg38/vep/homo_sapiens_merged/```. I guess it will work.

Thank you!

Best,
Jianxiang

**Comment by roryk** [comment]
Great! Glad that got it moving for you-- I couldn't figure out why it was downloading it twice, so good idea with the workaround.

**Comment by jxshi** [comment]
Thank you for you help!

Maybe it's just because my unstable internet connection.

Cheers!
Jianxiang
