### ISSUE TITLE
Error installing bcbio

### ISSUE THREAD

**Issue by gis-nlsim** [bcbio/bcbio-nextgen#2897]
Hi,
I've been having trouble installing bcbio.  Could you kindly advise me on how I can overcome this?

My installation command is:
python bcbio_nextgen_install.py <a directory in my home directory> --tooldir=<a directory in my home directory>  --genomes GRCh37 --aligners bwa --aligners bowtie2

The following is the error I got.

Resolving ftp.broadinstitute.org (ftp.broadinstitute.org)... 69.173.80.251
Connecting to ftp.broadinstitute.org (ftp.broadinstitute.org)|69.173.80.251|:21... connected.
Logging in as gsapubftp-anonymous ...
Login incorrect.

gzip: stdin: unexpected end of file
Traceback (most recent call last):
  File "/home/ubuntu/bcbio/stable/anaconda/bin/bcbio_nextgen.py", line 221, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/home/ubuntu/bcbio/stable/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 106, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/home/ubuntu/bcbio/stable/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 348, in upgrade_bcbio_data
    args.cores, ["ggd", "s3", "raw"])
  File "/home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 354, in install_data_local
    _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
  File "/home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 480, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 856, in _install_with_ggd
    ggd.install_recipe(os.getcwd(), env.system_install, recipe_file, gid)
  File "/home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"], system_install)
  File "/home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/home/ubuntu/bcbio/stable/anaconda/lib/python3.6/subprocess.py", line 356, in check_output
    def __repr__(self):
  File "/home/ubuntu/bcbio/stable/anaconda/lib/python3.6/subprocess.py", line 438, in run
    4) Backslashes are interpreted literally, unless they
subprocess.CalledProcessError: Command '['bash', '/home/ubuntu/bcbio/stable/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 288, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 45, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/ubuntu/bcbio/stable/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/home/ubuntu/tools', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Sorry about these issues. This is an intermittent problem with the Broad FTP servers. They can report this when they get oversubscribed or are otherwise unhappy. Unfortunately just re-trying is the best approach. If you re-run the upgrade command:
```
/home/ubuntu/bcbio/stable/anaconda/bin/bcbio_nextgen.py upgrade --tooldir=/home/ubuntu/tools --genomes GRCh37 --aligners bwa --aligners bowtie2 --data
```
it should pick up where it left off and hopefully the FTP server at Broad will be happier. Hope this helps get your install finished.

**Comment by roryk** [comment]
Thanks everyone, closing this issue as this is almost assuredly the problem. Please reopen if you continue to have problems. Thanks!
