### ISSUE TITLE
File location resolver finds multiple locations on GCP

### ISSUE THREAD

**Issue by conkiztador** [bcbio/bcbio-nextgen#2900]
Hi,

I'm following the [cloud docs](https://bcbio-nextgen.readthedocs.io/en/latest/contents/cloud.html#data-preparation) for generating CWL and running via GCP.

During the `bcbio_vm.py cwl` step, I'm getting the following error:
```kieran@bcbio:~/examples/bwa-gatk-illumina/config$ ~/install/bcbio-vm/anaconda/bin/bcbio_vm.py cwl --systemconfig bcbio-system.yaml  /home/kieran/examples/bwa-gatk-illumina/config/NA12878/config/NA12878.yaml
[2019-07-29T03:50Z] INFO: Using input YAML configuration: /home/kieran/examples/bwa-gatk-illumina/config/NA12878/config/NA12878.yaml
[2019-07-29T03:50Z] INFO: Checking sample YAML configuration: /home/kieran/examples/bwa-gatk-illumina/config/NA12878/config/NA12878.yaml
Traceback (most recent call last):
  File "/home/kieran/install/bcbio-vm/anaconda/bin/bcbio_vm.py", line 354, in <module>
    args.func(args)
  File "/home/kieran/install/bcbio-vm/anaconda/lib/python3.7/site-packages/bcbio/cwl/main.py", line 11, in run
    world = run_info.organize(dirs, config, run_info_yaml, is_cwl=True, integrations=integrations)
  File "/home/kieran/install/bcbio-vm/anaconda/lib/python3.7/site-packages/bcbio/pipeline/run_info.py", line 82, in organize
    item["config"]["algorithm"]["vcfanno"] = vcfanno.find_annotations(item, remote_retriever)
  File "/home/kieran/install/bcbio-vm/anaconda/lib/python3.7/site-packages/bcbio/variation/vcfanno.py", line 123, in find_annotations
    for x in retriever.add_remotes([conffn, luafn], data["config"])]
  File "/home/kieran/install/bcbio-vm/anaconda/lib/python3.7/site-packages/bcbio/variation/vcfanno.py", line 123, in <listcomp>
    for x in retriever.add_remotes([conffn, luafn], data["config"])]
  File "/home/kieran/install/bcbio-vm/anaconda/lib/python3.7/site-packages/bcbio/distributed/objectstore.py", line 639, in is_remote
    _get_storage_manager(fname)
  File "/home/kieran/install/bcbio-vm/anaconda/lib/python3.7/site-packages/bcbio/distributed/objectstore.py", line 627, in _get_storage_manager
    if manager.check_resource(resource):
  File "/home/kieran/install/bcbio-vm/anaconda/lib/python3.7/site-packages/bcbio/distributed/objectstore.py", line 356, in check_resource
    if resource and resource.startswith("s3://"):
AttributeError: 'list' object has no attribute 'startswith'
```

I instrumented the bcbio code a bit and it looks like its picking up multiple files from different genomes in the reference data sets. Here's the example it originally choked on:
```
[2019-07-29T04:18Z] INFO: Checking sample YAML configuration: /home/kieran/examples/bwa-gatk-illumina/config/NA12878/config/NA12878.yaml
['gs://bcbiodata/collections/GRCh37/validation/giab-NA12878/truth_small_variants.vcf.gz', 'gs://bcbiodata/collections/hg38/validation/giab-NA12878/truth_small_variants.vcf.gz']
```

I was able to work around this by copying data from just one of the datasets to another bucket and using that as the gs.ref value inside bcbio-system.yaml.

Is this a bug or am I missing some config somewhere?

**Comment by roryk** [comment]
Sorry for the problem-- I'm not familiar with this part of the code, but I can see if I can reproduce and figure out what is happening. I'm tagging @chapmanb as he knows this part of the code inside and out and might have a quick answer. I'm glad you were able to work around it though, thanks for reporting the issue and telling us a workaround, that is super helpful!

**Comment by chapmanb** [comment]
Kieran;
Thanks so much for the detailed report and apologies about the issue. You're exactly right that we should have been keying the lookup of the vcfanno files here on the genome so we don't get more than one option. It's a small one line fix you could path directly which will fix it, and we'll roll it into the next update to the bcbio conda recipe. Thanks again for the report and hope this gets you going.

**Comment by conkiztador** [comment]
Thanks Brad and Rory for the super quick response and fix! Will try this out shortly.

**Comment by roryk** [comment]
Thanks everyone!
