### ISSUE TITLE
fastrnaseq unit test failure

### ISSUE THREAD

**Issue by mjsteinbaugh** [bcbio/bcbio-nextgen#2901]
Hi guys, I'm seeing the `fastrnaseq` unit test fail for the latest development version on my VM:

```sh
./run_tests.sh fastrnaseq
```

```
integration/test_automated_analysis.py::test_2_fastrnaseq Running bcbio version: 1.1.6a
global config: /data00/bcbio/git/tests/test_automated_output/bcbio_system.yaml
flowcell directory: /data00/bcbio/git/tests/data/test_fusion
run info config: /data00/bcbio/git/tests/data/automated/run_info-fastrnaseq.yaml
[2019-08-14T15:57Z] System YAML configuration: /data00/bcbio/git/tests/test_automated_output/bcbio_system.yaml
[2019-08-14T15:57Z] Resource requests: picard; memory: 3.00; cores: 16
[2019-08-14T15:57Z] Configuring 1 jobs to run, using 1 cores each with 3.00g of memory reserved for each job
[2019-08-14T15:57Z] Timing: organize samples
[2019-08-14T15:57Z] multiprocessing: organize_samples
[2019-08-14T15:57Z] Using input YAML configuration: /data00/bcbio/git/tests/data/automated/run_info-fastrnaseq.yaml
[2019-08-14T15:57Z] Checking sample YAML configuration: /data00/bcbio/git/tests/data/automated/run_info-fastrnaseq.yaml
[2019-08-14T15:57Z] Testing minimum versions of installed programs
[2019-08-14T15:57Z] multiprocessing: prepare_sample
[2019-08-14T15:57Z] Preparing Test1
[2019-08-14T15:57Z] Preparing Test2
[2019-08-14T15:57Z] Resource requests: samtools; memory: 3.00; cores: 16
[2019-08-14T15:57Z] Configuring 1 jobs to run, using 1 cores each with 3.00g of memory reserved for each job
[2019-08-14T15:57Z] Timing: fastrnaseq
[2019-08-14T15:57Z] multiprocessing: run_salmon_index
Traceback (most recent call last):
  File "/data00/bcbio/development/tools/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==1.1.6a0', 'bcbio_nextgen.py')
  File "/data00/bcbio/development/install/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/data00/bcbio/development/install/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/data00/bcbio/development/install/anaconda/lib/python3.6/site-packages/bcbio_nextgen-1.1.6a0-py3.6.egg/EGG-INFO/scripts/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/data00/bcbio/development/install/anaconda/lib/python3.6/site-packages/bcbio_nextgen-1.1.6a0-py3.6.egg/EGG-INFO/scripts/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/data00/bcbio/development/install/anaconda/lib/python3.6/site-packages/bcbio_nextgen-1.1.6a0-py3.6.egg/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/data00/bcbio/development/install/anaconda/lib/python3.6/site-packages/bcbio_nextgen-1.1.6a0-py3.6.egg/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/data00/bcbio/development/install/anaconda/lib/python3.6/site-packages/bcbio_nextgen-1.1.6a0-py3.6.egg/bcbio/pipeline/main.py", line 286, in fastrnaseqpipeline
    samples = rnaseq.fast_rnaseq(samples, run_parallel)
  File "/data00/bcbio/development/install/anaconda/lib/python3.6/site-packages/bcbio_nextgen-1.1.6a0-py3.6.egg/bcbio/pipeline/rnaseq.py", line 14, in fast_rnaseq
    samples = run_parallel("run_salmon_index", [samples])
  File "/data00/bcbio/development/install/anaconda/lib/python3.6/site-packages/bcbio_nextgen-1.1.6a0-py3.6.egg/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/data00/bcbio/development/install/anaconda/lib/python3.6/site-packages/bcbio_nextgen-1.1.6a0-py3.6.egg/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/data00/bcbio/development/install/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 921, in __call__
    if self.dispatch_one_batch(iterator):
  File "/data00/bcbio/development/install/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/data00/bcbio/development/install/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/data00/bcbio/development/install/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/data00/bcbio/development/install/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "/data00/bcbio/development/install/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/data00/bcbio/development/install/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/data00/bcbio/development/install/anaconda/lib/python3.6/site-packages/bcbio_nextgen-1.1.6a0-py3.6.egg/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/data00/bcbio/development/install/anaconda/lib/python3.6/site-packages/bcbio_nextgen-1.1.6a0-py3.6.egg/bcbio/distributed/multitasks.py", line 75, in run_salmon_index
    return salmon.run_salmon_index(*args)
  File "/data00/bcbio/development/install/anaconda/lib/python3.6/site-packages/bcbio_nextgen-1.1.6a0-py3.6.egg/bcbio/rnaseq/salmon.py", line 149, in run_salmon_index
    assert file_exists(fasta_file), "%s was not found, exiting." % fasta_file
NameError: name 'fasta_file' is not defined
FAILED
```

**Comment by mjsteinbaugh** [comment]
Can confirm that this test passes for bcbio v1.1.5 on the same machine.

**Comment by roryk** [comment]
Thanks Mike, good catch. Fixed!

**Comment by mjsteinbaugh** [comment]
Awesome thanks Rory
