### ISSUE TITLE
Small RNA-seq analysis pipeline stalled in "De-duplication with biobambam" step

### ISSUE THREAD

**Issue by jxshi** [bcbio/bcbio-nextgen#2902]
Hi @lpantano ,

I was using ```smallRNA-seq``` pipeline to analysis some small RNAseq data from ```homo sapiens```. However, the pipeline seemed stalled at ```De-duplication with biobambam"```step.

Here is the configure file for this run:
```
upload:
  dir: ../final
details:
  - analysis: smallRNA-seq
    algorithm:
      aligner: star # any other aligner is supported.
      # change adapter according project
      #adapters: ["GTTCAGAGTTCTACAGTCCGACGATC"]
      expression_caller: [seqcluster, mirdeep2]
      # expression_caller: [trna, seqcluster, mirdeep2, mirge] Read docs to know how to use
      # miRge tools: https://bcbio-nextgen.readthedocs.io/en/latest/contents/pipelines.html#smallrna-seq
      species: hsa
    genome_build: GRCh37
      #resources:
          #atropos:
          #options: ["-u 4", "-u -4"]
#  mirge:
#    options: ["-lib /home/jshi/local/share/bcbio/miRge_lib"]
```
Here is the log output:
```

[2019-08-15T03:05Z] Resource requests: fastqc, picard; memory: 3.00, 3.00; cores: 16, 16
[2019-08-15T03:05Z] Configuring 1 jobs to run, using 16 cores each with 48.1g of memory reserved for each job
[2019-08-15T03:05Z] Timing: quality control
[2019-08-15T03:05Z] multiprocessing: pipeline_summary
[2019-08-15T03:05Z] QC: tumorfxz atropos
[2019-08-15T03:05Z] QC: tumorfxz fastqc
[2019-08-15T03:05Z] Produced HTML report /data/proj/research/shixiaojing/smallRNA/gcsmall/work/qc/tumorfxz/fastqc/fastqc_report.html
[2019-08-15T03:05Z] QC: tumorfxz qualimap_rnaseq
[2019-08-15T03:05Z] De-duplication with biobambam
[2019-08-15T03:05Z] [V] output compression level -1
```
And I also tried to turn off ```seqcluster``` tool to re-run the pipeline, but it didn't work. Can you check this for me please? Thanks!

Best Regards,
Jianxiang

**Comment by lpantano** [comment]
Hi,

Thanks for the details. 

Can I ask you what protocol was used for this? small RNA is referring to mi-RNA like sequences, so the data should be around 20-40 nt long.

Can you check if the trimming seems ok? as you have it now, it would try to guess the adapter, but some time that doesn't work. You can check the log for some samples and see if the adapter was found in the majority of the reads.

I am not sure by is stalled there, it is the first time I see that. I hope knowing the kind of data this is I can discard is a data-related issue or not.

cheers

**Comment by jxshi** [comment]
Hi @lpantano ,

Sorry for the late reply. I tried several different way to re-run the ```small RNA-seq``` pipeline. This is mi-RNA seq data and some of the clean read length is less than 20 nt long.

The adapter sequence is ```GTTCAGAGTTCTACAGTCCGACGATC```. So I uncommented ```adapters: ["GTTCAGAGTTCTACAGTCCGACGATC"]``` line in the configuration file to run on raw data, which is 51 nt long. But after ```atropos``` trimming step, very few or none reads were kept in ```trimmed/samplename/*.clean.fq.gz``` file. Here is the error log:
```
Running bcbio version: 1.1.6a
global config: /data/proj/research/shixiaojing/smallRNA/gcsmall_raw/work/bcbio_system.yaml
run info config: /data/proj/research/shixiaojing/smallRNA/gcsmall_raw/config/gcsmall_raw.yaml
[2019-08-16T06:20Z] Using input YAML configuration: /data/proj/research/shixiaojing/smallRNA/gcsmall_raw/config/gcsmall_raw.yaml
[2019-08-16T06:20Z] Checking sample YAML configuration: /data/proj/research/shixiaojing/smallRNA/gcsmall_raw/config/gcsmall_raw.yaml
[2019-08-16T06:20Z] Testing minimum versions of installed programs
[2019-08-16T06:20Z] multiprocessing: prepare_sample
[2019-08-16T06:20Z] Preparing tumorfxz
[2019-08-16T06:20Z] Preparing normalfxz
[2019-08-16T06:20Z] Preparing normalgyn
[2019-08-16T06:20Z] Preparing tumorgyn
[2019-08-16T06:20Z] Preparing tumorlhj
[2019-08-16T06:20Z] Preparing normallhj
[2019-08-16T06:20Z] Preparing normallxg
[2019-08-16T06:20Z] Preparing tumorlxg
[2019-08-16T06:20Z] Preparing tumorwzx
[2019-08-16T06:20Z] Preparing normalwzx
[2019-08-16T06:20Z] Preparing normalzdd
[2019-08-16T06:20Z] Preparing tumorzdd
[2019-08-16T06:20Z] Timing: adapter trimming
[2019-08-16T06:20Z] multiprocessing: trim_srna_sample
[2019-08-16T06:20Z] No UMI transform specified, assuming pre-transformed data.
[2019-08-16T06:20Z] No UMI transform specified, assuming pre-transformed data.
[2019-08-16T06:20Z] No UMI transform was specified, but /data/proj/research/shixiaojing/smallRNA/raw_data/fengxinzhou-2428020-zheng_raw.fq.gz does not look pre-transformed. Assuming non-umi data.
[2019-08-16T06:20Z] No UMI transform was specified, but /data/proj/research/shixiaojing/smallRNA/raw_data/fengxinzhou-2428020-pang_raw.fq.gz does not look pre-transformed. Assuming non-umi data.
[2019-08-16T06:20Z] No UMI transform specified, assuming pre-transformed data.
[2019-08-16T06:20Z] No UMI transform specified, assuming pre-transformed data.
[2019-08-16T06:20Z] No UMI transform was specified, but /data/proj/research/shixiaojing/smallRNA/raw_data/gaoyunian-2456725-T_raw.fq.gz does not look pre-transformed. Assuming non-umi data.
[2019-08-16T06:20Z] No UMI transform was specified, but /data/proj/research/shixiaojing/smallRNA/raw_data/gaoyunian-2456725-N_raw.fq.gz does not look pre-transformed. Assuming non-umi data.
[2019-08-16T06:20Z] No UMI transform specified, assuming pre-transformed data.
[2019-08-16T06:20Z] No UMI transform specified, assuming pre-transformed data.
[2019-08-16T06:20Z] No UMI transform was specified, but /data/proj/research/shixiaojing/smallRNA/raw_data/liuhanjie-2025827-pang_raw.fq.gz does not look pre-transformed. Assuming non-umi data.
[2019-08-16T06:20Z] No UMI transform was specified, but /data/proj/research/shixiaojing/smallRNA/raw_data/liuhanjie-2025827-zheng_raw.fq.gz does not look pre-transformed. Assuming non-umi data.
[2019-08-16T06:20Z] Adapter is set up in config file, but trim_reads is not true.If you want to skip trimming, skip adapter option from config.
[2019-08-16T06:20Z] Adapter is set up in config file, but trim_reads is not true.If you want to skip trimming, skip adapter option from config.
[2019-08-16T06:20Z] remove adapter for tumorlhj
[2019-08-16T06:20Z] remove adapter for normallhj
[2019-08-16T06:21Z] Running seqcluster collapse in /data/proj/research/shixiaojing/smallRNA/gcsmall_raw/work/trimmed/tumorlhj/liuhanjie-2025827-pang_raw.clean.fq.gz.
[2019-08-16T06:21Z] INFO Run collapse
[2019-08-16T06:21Z] INFO Sequences loaded: 0
[2019-08-16T06:21Z] INFO Writing 0 sequences to /data/proj/research/shixiaojing/smallRNA/gcsmall_raw/work/trimmed/tumorlhj/liuhanjie-2025827-pang_raw.clean_trimmed.fastq
[2019-08-16T06:21Z] INFO It took 0.000 minutes
[2019-08-16T06:21Z] ['collapse', '-o', '/data/proj/research/shixiaojing/smallRNA/gcsmall_raw/work/trimmed/tumorlhj', '-f', '/data/proj/research/shixiaojing/smallRNA/gcsmall_raw/work/trimmed/tumorlhj/liuhanjie-2025827-pang_raw.clean.fq.gz', '-m', '1', '--min_size', '16']
[2019-08-16T06:21Z] No UMI transform specified, assuming pre-transformed data.
[2019-08-16T06:21Z] No UMI transform was specified, but /data/proj/research/shixiaojing/smallRNA/raw_data/lixiguo-2493093-zheng_raw.fq.gz does not look pre-transformed. Assuming non-umi data.
[2019-08-16T06:21Z] Adapter is set up in config file, but trim_reads is not true.If you want to skip trimming, skip adapter option from config.
[2019-08-16T06:21Z] remove adapter for normallxg
[2019-08-16T06:22Z] Running seqcluster collapse in /data/proj/research/shixiaojing/smallRNA/gcsmall_raw/work/trimmed/normallhj/liuhanjie-2025827-zheng_raw.clean.fq.gz.
[2019-08-16T06:22Z] INFO Run collapse
[2019-08-16T06:22Z] INFO Sequences loaded: 0
[2019-08-16T06:22Z] INFO Writing 0 sequences to /data/proj/research/shixiaojing/smallRNA/gcsmall_raw/work/trimmed/normallhj/liuhanjie-2025827-zheng_raw.clean_trimmed.fastq
[2019-08-16T06:22Z] INFO It took 0.000 minutes
[2019-08-16T06:22Z] ['collapse', '-o', '/data/proj/research/shixiaojing/smallRNA/gcsmall_raw/work/trimmed/normallhj', '-f', '/data/proj/research/shixiaojing/smallRNA/gcsmall_raw/work/trimmed/normallhj/liuhanjie-2025827-zheng_raw.clean.fq.gz', '-m', '1', '--min_size', '16']
[2019-08-16T06:22Z] No UMI transform specified, assuming pre-transformed data.
[2019-08-16T06:22Z] No UMI transform was specified, but /data/proj/research/shixiaojing/smallRNA/raw_data/lixiguozhong_raw.fq.gz does not look pre-transformed. Assuming non-umi data.
[2019-08-16T06:22Z] No UMI transform specified, assuming pre-transformed data.
[2019-08-16T06:22Z] No UMI transform was specified, but /data/proj/research/shixiaojing/smallRNA/raw_data/wangzhixin-2418700-pang_raw.fq.gz does not look pre-transformed. Assuming non-umi data.
[2019-08-16T06:22Z] No UMI transform specified, assuming pre-transformed data.
[2019-08-16T06:22Z] No UMI transform was specified, but /data/proj/research/shixiaojing/smallRNA/raw_data/wangzhixin-2418700-zheng_raw.fq.gz does not look pre-transformed. Assuming non-umi data.
[2019-08-16T06:22Z] No UMI transform specified, assuming pre-transformed data.
[2019-08-16T06:22Z] No UMI transform was specified, but /data/proj/research/shixiaojing/smallRNA/raw_data/zhangdongdongzheng_raw.fq.gz does not look pre-transformed. Assuming non-umi data.
[2019-08-16T06:22Z] Adapter is set up in config file, but trim_reads is not true.If you want to skip trimming, skip adapter option from config.
[2019-08-16T06:22Z] remove adapter for normalzdd
[2019-08-16T06:22Z] Running seqcluster collapse in /data/proj/research/shixiaojing/smallRNA/gcsmall_raw/work/trimmed/normallxg/lixiguo-2493093-zheng_raw.clean.fq.gz.
[2019-08-16T06:22Z] INFO Run collapse
[2019-08-16T06:22Z] INFO Sequences loaded: 0
[2019-08-16T06:22Z] INFO Writing 0 sequences to /data/proj/research/shixiaojing/smallRNA/gcsmall_raw/work/trimmed/normallxg/lixiguo-2493093-zheng_raw.clean_trimmed.fastq
[2019-08-16T06:22Z] INFO It took 0.000 minutes
[2019-08-16T06:22Z] ['collapse', '-o', '/data/proj/research/shixiaojing/smallRNA/gcsmall_raw/work/trimmed/normallxg', '-f', '/data/proj/research/shixiaojing/smallRNA/gcsmall_raw/work/trimmed/normallxg/lixiguo-2493093-zheng_raw.clean.fq.gz', '-m', '1', '--min_size', '16']
[2019-08-16T06:22Z] No UMI transform specified, assuming pre-transformed data.
[2019-08-16T06:22Z] No UMI transform was specified, but /data/proj/research/shixiaojing/smallRNA/raw_data/zhangdongdongzhong_raw.fq.gz does not look pre-transformed. Assuming non-umi data.
[2019-08-16T06:22Z] Adapter is set up in config file, but trim_reads is not true.If you want to skip trimming, skip adapter option from config.
[2019-08-16T06:22Z] remove adapter for tumorzdd
[2019-08-16T06:23Z] Running seqcluster collapse in /data/proj/research/shixiaojing/smallRNA/gcsmall_raw/work/trimmed/normalzdd/zhangdongdongzheng_raw.clean.fq.gz.
[2019-08-16T06:23Z] INFO Run collapse
[2019-08-16T06:23Z] INFO Sequences loaded: 0
[2019-08-16T06:23Z] INFO Writing 0 sequences to /data/proj/research/shixiaojing/smallRNA/gcsmall_raw/work/trimmed/normalzdd/zhangdongdongzheng_raw.clean_trimmed.fastq
[2019-08-16T06:23Z] INFO It took 0.000 minutes
[2019-08-16T06:23Z] ['collapse', '-o', '/data/proj/research/shixiaojing/smallRNA/gcsmall_raw/work/trimmed/normalzdd', '-f', '/data/proj/research/shixiaojing/smallRNA/gcsmall_raw/work/trimmed/normalzdd/zhangdongdongzheng_raw.clean.fq.gz', '-m', '1', '--min_size', '16']
[2019-08-16T06:24Z] Running seqcluster collapse in /data/proj/research/shixiaojing/smallRNA/gcsmall_raw/work/trimmed/tumorzdd/zhangdongdongzhong_raw.clean.fq.gz.
[2019-08-16T06:24Z] INFO Run collapse
[2019-08-16T06:24Z] INFO Sequences loaded: 0
[2019-08-16T06:24Z] INFO Writing 0 sequences to /data/proj/research/shixiaojing/smallRNA/gcsmall_raw/work/trimmed/tumorzdd/zhangdongdongzhong_raw.clean_trimmed.fastq
[2019-08-16T06:24Z] INFO It took 0.000 minutes
[2019-08-16T06:24Z] ['collapse', '-o', '/data/proj/research/shixiaojing/smallRNA/gcsmall_raw/work/trimmed/tumorzdd', '-f', '/data/proj/research/shixiaojing/smallRNA/gcsmall_raw/work/trimmed/tumorzdd/zhangdongdongzhong_raw.clean.fq.gz', '-m', '1', '--min_size', '16']
[2019-08-16T06:24Z] Resource requests: picard, samtools, star; memory: 3.00, 3.00, 3.00; cores: 16, 16, 16
[2019-08-16T06:24Z] Configuring 1 jobs to run, using 16 cores each with 48.1g of memory reserved for each job
[2019-08-16T06:24Z] Timing: prepare
[2019-08-16T06:24Z] multiprocessing: seqcluster_prepare
[2019-08-16T06:24Z] Timing: seqcluster alignment
[2019-08-16T06:24Z] multiprocessing: srna_alignment
Traceback (most recent call last):
  File "/home/jshi/local/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/home/jshi/local/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/jshi/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/home/jshi/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/jshi/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 326, in smallrnaseqpipeline
    samples = run_parallel("srna_alignment", [samples])
  File "/home/jshi/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/jshi/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/home/jshi/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 921, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/jshi/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/jshi/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/jshi/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/home/jshi/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "/home/jshi/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/home/jshi/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/jshi/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/home/jshi/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 176, in srna_alignment
    return seqcluster.run_align(*args)
  File "/home/jshi/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/srna/group.py", line 69, in run_align
    sample = process_alignment(data[0][0], [seq_out, None])
  File "/home/jshi/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sample.py", line 184, in process_alignment
    "If it is a fastq file (not pre-aligned BAM or CRAM), "
ValueError: Could not process input file from sample configuration.
/data/proj/research/shixiaojing/smallRNA/gcsmall_raw/work/seqcluster/prepare/seqs.fastq
Is the path to the file correct or is empty?
If it is a fastq file (not pre-aligned BAM or CRAM), is an aligner specified in the input configuration?
```

Here is the file information of trimmed ```fastq``` files.
```
-rw-rw-r-- 1 jshi jshi   0 8月  16 14:24 trimmed/tumorzdd/zhangdongdongzhong_raw.clean.fq.gz
-rw-rw-r-- 1 jshi jshi   0 8月  16 14:23 trimmed/normalzdd/zhangdongdongzheng_raw.clean.fq.gz
-rw-rw-r-- 1 jshi jshi   0 8月  16 14:22 trimmed/normallxg/lixiguo-2493093-zheng_raw.clean.fq.gz
-rw-rw-r-- 1 jshi jshi   0 8月  16 14:22 trimmed/normallhj/liuhanjie-2025827-zheng_raw.clean.fq.gz
-rw-rw-r-- 1 jshi jshi   0 8月  16 14:21 trimmed/tumorlhj/liuhanjie-2025827-pang_raw.clean.fq.gz
-rw-rw-r-- 1 jshi jshi 309 8月  16 10:06 trimmed/normalwzx/wangzhixin-2418700-zheng_raw.clean.fq.gz
-rw-rw-r-- 1 jshi jshi 314 8月  16 10:05 trimmed/tumorwzx/wangzhixin-2418700-pang_raw.clean.fq.gz
-rw-rw-r-- 1 jshi jshi 104 8月  16 10:05 trimmed/tumorlxg/lixiguozhong_raw.clean.fq.gz
-rw-rw-r-- 1 jshi jshi 234 8月  16 10:02 trimmed/tumorgyn/gaoyunian-2456725-T_raw.clean.fq.gz
-rw-rw-r-- 1 jshi jshi 957 8月  16 10:02 trimmed/normalgyn/gaoyunian-2456725-N_raw.clean.fq.gz
-rw-rw-r-- 1 jshi jshi 104 8月  16 10:00 trimmed/normalfxz/fengxinzhou-2428020-zheng_raw.clean.fq.gz
-rw-rw-r-- 1 jshi jshi 104 8月  16 10:00 trimmed/tumorfxz/fengxinzhou-2428020-pang_raw.clean.fq.gz
```

Thanks!

Best,
Jianxiang

**Comment by lpantano** [comment]
Hi,

the pipeline won't run ok if there is not trimming. You said you used this as adapter: "GTTCAGAGTTCTACAGTCCGACGATC" and this is the error you get?  or this is the error you get when you don't trim your data?

If this is the error when you do trimming, it seems there are not enough sequences under that size, 
`seqs.fastq` would be empty if I am not wrong, you can check that. 

Can you run, 2 samples, using the adapter you think it is, and tell me what error you get?

thanks for keep trying.

cheers

**Comment by jxshi** [comment]
Hi @lpantano ,

I have tried ```bcbio-nextgen``` small RNA-seq pipeline on another set of small RNA data from ```Rattus norvegicus```, it went through. So I think ```bcbio-nextgen``` small RNA-seq pipeline should be OK, there might be something wrong with the data. So I will close this issue now. I will report back if I figure out the problem with small RNA-seq data from ```Homo sapiens```.

Thank you and cheers!

Jianxiang

**Comment by roryk** [comment]
Thanks for closing the loop Jianxiang!
