### ISSUE TITLE
Issue with preseq

### ISSUE THREAD

**Issue by gabeng** [bcbio/bcbio-nextgen#2925]
I ran into an issue when activating `preseq`. 
This is the stack trace:
```
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 190, in variant2pipeline
    samples = qcsummary.generate_parallel(samples, run_parallel)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/pipeline/qcsummary.py", line 42, in generate_parallel
    qced = run_parallel("pipeline_summary", to_analyze)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 924, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 212, in pipeline_summary
    return qcsummary.pipeline_summary(*args)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/pipeline/qcsummary.py", line 73, in pipeline_summary
    data["summary"] = _run_qc_tools(work_bam, work_data)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/pipeline/qcsummary.py", line 165, in _run_qc_tools
    out = qc_fn(bam_file, data, cur_qc_dir)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/qc/preseq.py", line 37, in run
    params = _get_preseq_params(data, preseq_cmd, int(samtools_stats["Total_reads"]))
KeyError: 'Total_reads'
```

I suppose that this line
https://github.com/bcbio/bcbio-nextgen/blob/a3473775db06540c10b5f20ddc2043b8cc99d1f8/bcbio/qc/preseq.py#L31
should rather be:

```
samtools_stats = samtools.run(bam_file, data, samtools_stats_dir)["metrics"]
```
Should I open a pull request?

**Comment by roryk** [comment]
Hi Ben,

Thanks-- does changing that line fix it? If so, pull requests are always welcome. Thanks so much for all of your improvements, it is so helpful to have folks catching this stuff.

**Comment by gabeng** [comment]
Rory,

yes, I can now confirm now that it fixed it. Will create a pull request.
However, `preseq` is so slow that I will not run it routinely. 20+min per sample and not multi-threading. Still great to have the option.

**Comment by roryk** [comment]
Thanks Ben!

**Comment by roryk** [comment]
If you add in the body of your commit message:

Fixes #2925.

 when it gets merged in it will automatically close this issue if you want to be fancy.

**Comment by gabeng** [comment]
Darn, just created the pull request. Will do that next time.

**Comment by roryk** [comment]
Thank you!
