### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by kokyriakidis** [bcbio/bcbio-nextgen#2955]
I get the following error when I run the install command:

```
ERROR conda.core.link:_execute(700): An error occurred while installing package 'bioconda::deepvariant-0.8.0-py27h7333d49_0'.
Rolling back transaction: done

LinkError: post-link script failed for package bioconda::deepvariant-0.8.0-py27h7333d49_0
location of failed script: /RED/RESOURCES/bcbio/anaconda/envs/dv/bin/.deepvariant-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: 
stderr: Copying gs://deepvariant/models/DeepVariant/0.8.0/DeepVariant-inception_v3-0.8.0+data-wgs_standard/model.ckpt.data-00000-of-00001...
CommandException: Couldn't write tracker file (/home/kokyriakidis/.gsutil/tracker-files/sliced_download_TRACKER_94b43a90d8c5b9342d3b4cc2e8d4b09007dd0b8f.00001__JSON.etag): Permission denied. This can happen if gsutil is configured to save tracker files to an unwritable directory)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/RED/RESOURCES/bcbio/anaconda/envs/dv/share/google-cloud-sdk-264.0.0-0/platform/gsutil/gslib/metrics_reporter.py", line 111, in ReportMetrics
    handler = logging.FileHandler(log_file_path, mode='w')
  File "/RED/RESOURCES/bcbio/anaconda/envs/dv/lib/python2.7/logging/__init__.py", line 920, in __init__
    StreamHandler.__init__(self, self._open())
  File "/RED/RESOURCES/bcbio/anaconda/envs/dv/lib/python2.7/logging/__init__.py", line 950, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: u'/home/kokyriakidis/.gsutil/metrics.log'

return code: 1

()

Traceback (most recent call last):
  File "/RED/RESOURCES/bcbio/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/RED/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 90, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/RED/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 495, in upgrade_thirdparty_tools
    cbl_conda.install_in(_get_conda_bin(), args.tooldir, package_yaml)
  File "/RED/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 89, in install_in
    "{py_version} {pkgs_str}".format(**locals()), shell=True)
  File "/RED/RESOURCES/bcbio/anaconda/lib/python3.6/subprocess.py", line 311, in check_call
    ...               "ls -l non_existent_file ; exit 0"],
subprocess.CalledProcessError: Command 'export BOTO_CONFIG=/ignoreglobal && /RED/RESOURCES/bcbio/anaconda/bin/conda install -y -n dv -c conda-forge -c bioconda python=2 'deepvariant'' returned non-zero exit status 1.
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 288, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 45, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/RED/RESOURCES/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/RED/TOOLS', '--genomes', 'hg38', '--distribution', 'ubuntu', '-u', 'development', '--aligners', 'bowtie', '--aligners', 'bowtie2', '--aligners', 'bwa', '--aligners', 'minimap2', '--aligners', 'star', '--aligners', 'hisat2', '--datatarget', 'variation', '--datatarget', 'rnaseq', '--datatarget', 'smallrna', '--datatarget', 'gemini', '--datatarget', 'cadd', '--datatarget', 'vep', '--datatarget', 'dbnsfp', '--datatarget', 'battenberg', '--datatarget', 'kraken', '--datatarget', 'ericscript', '--datatarget', 'gnomad', '--cores', '20', '--toolplus', 'gatk=/home/kokyriakidis/gatk-4.1.2.0/gatk-package-4.1.2.0-local.jar', '--data']' returned non-zero exit status 1

```

The command I run is:
```
python bcbio_nextgen_install.py /RED/RESOURCES/bcbio --tooldir=/RED/TOOLS --genomes hg38 --distribution ubuntu -u development --aligners bowtie --aligners bowtie2 --aligners bwa --aligners minimap2 --aligners star --aligners hisat2 --datatarget variation --datatarget rnaseq --datatarget smallrna --datatarget gemini --datatarget cadd --datatarget vep --datatarget dbnsfp --datatarget battenberg --datatarget kraken --datatarget ericscript --datatarget gnomad --cores 20 --toolplus gatk='/home/kokyriakidis/gatk-4.1.2.0/gatk-package-4.1.2.0-local.jar'
```

And the the folder /RED was treated with sudo chmod 777.

Any thoughts?

**Comment by roryk** [comment]
What is the permissions on `/home/kokyriakidis/.gsutil/metrics.log`?

**Comment by kokyriakidis** [comment]
Hmm, somehow the new created files had not write permission. I had to change that with umask.

Thanks for your time!

**Comment by roryk** [comment]
Anytime, thanks for following up! Sorry for the installation problems, it has been unusually rocky for the past month or so.

**Comment by kokyriakidis** [comment]
Another recommendation is to move all database resources to aws or something else. It takes forever to download them. The download speed is too low

**Comment by roryk** [comment]
Sorry, we try to host as few things as possible ourselves because it is very expensive to pay for folks to download them.

**Comment by kokyriakidis** [comment]
Can I move these files when I download them to another computer and install bcbio without the flag to download these databases? and then just paste them in the folder?

**Comment by roryk** [comment]
Yes, if you copy over the `galaxy` and `genomes` directory from your install to your new one, that will give you what you need. You will also need to edit the files in `galaxy/tool-data/` to point to the right directories.

**Comment by kokyriakidis** [comment]
Thanks so much for the info!
