### ISSUE TITLE
Frustration downloading gnomad genomes

### ISSUE THREAD

**Issue by kokyriakidis** [bcbio/bcbio-nextgen#2956]
Although it downloaded gnomad.genomes.r2.1.sites.grch38.chr1_noVEP.vcf.gz and the *.tbi, these files went missing and the file "gnomad.genomes.r2.1.sites.grch38.chr1_noVEP.vcf.gz " started downloading again? Any thoughts? @roryk 

```
Saving to: ‘gnomad.genomes.r2.1.sites.grch38.chr1_noVEP.vcf.gz’

gnomad.genomes.r2.1 100%[===================>]  27,10G   713KB/s    in 12h 51m 

2019-09-27 22:32:26 (614 KB/s) - ‘gnomad.genomes.r2.1.sites.grch38.chr1_noVEP.vcf.gz’ saved [29101164808/29101164808]

--2019-09-27 22:32:26--  http://ftp.ensemblorg.ebi.ac.uk/pub/data_files/homo_sapiens/GRCh38/variation_genotype/gnomad/r2.1/genomes/gnomad.genomes.r2.1.sites.grch38.chr1_noVEP.vcf.gz.tbi
Resolving ftp.ensemblorg.ebi.ac.uk (ftp.ensemblorg.ebi.ac.uk)... 193.62.193.8
Connecting to ftp.ensemblorg.ebi.ac.uk (ftp.ensemblorg.ebi.ac.uk)|193.62.193.8|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 223851 (219K) [application/x-gzip]
Saving to: ‘gnomad.genomes.r2.1.sites.grch38.chr1_noVEP.vcf.gz.tbi’

gnomad.genomes.r2.1 100%[===================>] 218,60K   441KB/s    in 0,5s    

2019-09-27 22:32:27 (441 KB/s) - ‘gnomad.genomes.r2.1.sites.grch38.chr1_noVEP.vcf.gz.tbi’ saved [223851/223851]

--2019-09-27 22:33:14--  http://ftp.ensemblorg.ebi.ac.uk/pub/data_files/homo_sapiens/GRCh38/variation_genotype/gnomad/r2.1/genomes/gnomad.genomes.r2.1.sites.grch38.chr1_noVEP.vcf.gz
Resolving ftp.ensemblorg.ebi.ac.uk (ftp.ensemblorg.ebi.ac.uk)... 193.62.193.8
Connecting to ftp.ensemblorg.ebi.ac.uk (ftp.ensemblorg.ebi.ac.uk)|193.62.193.8|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 29101164808 (27G) [application/x-gzip]
Saving to: ‘gnomad.genomes.r2.1.sites.grch38.chr1_noVEP.vcf.gz’

gnomad.genomes.r2.1 6%[>                      ]  1,69G   670KB/s    eta 13h 47m 
```

**Comment by naumenko-sa** [comment]
Hi Konstantinos @kokyriakidis !

Thanks for reporting the issue and apologies that gnomad genome installation did not work for you.
I've fixed the recipe for gnomad genome and have tested it:
https://github.com/chapmanb/cloudbiolinux/pull/323

Usually Brad is super-fast at merging, but if you want to try it even faster, you could 
substitute the recipe directly in your bcbio installation:
- the recipe: https://github.com/naumenko-sa/cloudbiolinux/blob/master/ggd-recipes/hg38/gnomad.yaml
- how to apply the recipe to the interrupted installation:
https://github.com/chapmanb/cloudbiolinux/blob/master/doc/hacking.md#testing-a-ggd-recipe

I have finished a small test, and I started a full-size one on the machine I have. 

I am very curious what will be the running time of the recipe in your environment. 
- how long the downloading of 460G gnomad vcf takes place;
- what is your location;
- how long the filtration goes;
- what is the size of the resulting file;

It would be a great contribution to bcbio if you provided those estimates for your system.

We had a big debate on whether we should switch to gnomad2.1.1 at all, 
because of its huge size compared to the previous 2.0.1 release.

Sergey

**Comment by kokyriakidis** [comment]
Hi @naumenko-sa 

I modified the ggd-recipe for gnomad I saved it and then I rerun the command:

```
python bcbio_nextgen_install.py /RED/RESOURCES/bcbio --tooldir=/RED/TOOLS --genomes hg38 --distribution ubuntu -u development --aligners bowtie --aligners bowtie2 --aligners bwa --aligners minimap2 --aligners star --aligners hisat2 --datatarget variation --datatarget rnaseq --datatarget smallrna --datatarget gemini --datatarget cadd --datatarget vep --datatarget dbnsfp --datatarget battenberg --datatarget kraken --datatarget ericscript --datatarget gnomad --cores 20 --toolplus gatk='/home/kokyriakidis/gatk-4.1.2.0/gatk-package-4.1.2.0-local.jar'
```

But after 2 minuted I get this:
```
python bcbio_nextgen_install.py /RED/RESOURCES/bcbio --tooldir=/RED/TOOLS --genomes hg38 --distribution ubuntu -u development --aligners bowtie --aligners bowtie2 --aligners bwa --aligners minimap2 --aligners star --aligners hisat2 --datatarget variation --datatarget rnaseq --datatarget smallrna --datatarget gemini --datatarget cadd --datatarget vep --datatarget dbnsfp --datatarget battenberg --datatarget kraken --datatarget ericscript --datatarget gnomad --cores 20 --toolplus gatk='/home/kokyriakidis/gatk-4.1.2.0/gatk-package-4.1.2.0-local.jar'
Checking required dependencies
Installing isolated base python installation
Installing bcbio-nextgen
--2019-09-28 09:45:45--  https://raw.githubusercontent.com/bcbio/bcbio-nextgen/master/requirements-conda.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.192.133, 151.101.128.133, 151.101.64.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.192.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20 [text/plain]
Saving to: ‘requirements-conda.txt’

requirements-conda. 100%[===================>]      20  --.-KB/s    in 0s      

2019-09-28 09:45:45 (1,89 MB/s) - ‘requirements-conda.txt’ saved [20/20]

Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /RED/RESOURCES/bcbio/anaconda

  added / updated specs:
    - bcbio-nextgen==1.1.5
    - python=3.6


The following NEW packages will be INSTALLED:

  bcbio-nextgen      bioconda/linux-64::bcbio-nextgen-1.1.5-py36_0


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Collecting bcbio-nextgen from git+https://github.com/bcbio/bcbio-nextgen.git#egg=bcbio-nextgen
  Cloning https://github.com/bcbio/bcbio-nextgen.git to /tmp/pip-install-zqbhx1t1/bcbio-nextgen
  Running command git clone -q https://github.com/bcbio/bcbio-nextgen.git /tmp/pip-install-zqbhx1t1/bcbio-nextgen
Building wheels for collected packages: bcbio-nextgen
  Building wheel for bcbio-nextgen (setup.py) ... done
  Created wheel for bcbio-nextgen: filename=bcbio_nextgen-1.1.6a0-cp36-none-any.whl size=2483493 sha256=12c3fab1c7c4151a400eccbfaa4a736d6067c19d316d7a92436263d72b567f6b
  Stored in directory: /tmp/pip-ephem-wheel-cache-hr_6_mim/wheels/c0/af/8f/75201c9fda71b27e67f797ef794dbade910690b2e3fa36c16c
Successfully built bcbio-nextgen
Installing collected packages: bcbio-nextgen
  Found existing installation: bcbio-nextgen 1.1.6a0
    Uninstalling bcbio-nextgen-1.1.6a0:
      Successfully uninstalled bcbio-nextgen-1.1.6a0
Successfully installed bcbio-nextgen-1.1.6a0
Installing data and third party dependencies
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 288, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 43, in main
    args.tooldir)
  File "bcbio_nextgen_install.py", line 162, in write_system_config
    with contextlib.closing(urllib_request.urlopen(base_url)) as in_handle:
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -2] Name or service not known>
```
Any thoughts?

**Comment by kokyriakidis** [comment]
@naumenko-sa 

I got these warnings when the gnomad download finished

```
Warning: The tag "AC_nfe_bgr" not defined in the header
Warning: The tag "AN_nfe_bgr" not defined in the header
Warning: The tag "AF_nfe_bgr" not defined in the header
Warning: The tag "nhomalt_nfe_bgr" not defined in the header
Warning: The tag "AC_sas_male" not defined in the header
Warning: The tag "AN_sas_male" not defined in the header
Warning: The tag "AF_sas_male" not defined in the header
Warning: The tag "nhomalt_sas_male" not defined in the header
Warning: The tag "AC_sas" not defined in the header
Warning: The tag "AN_sas" not defined in the header
Warning: The tag "AF_sas" not defined in the header
Warning: The tag "nhomalt_sas" not defined in the header
Warning: The tag "AC_nfe_swe" not defined in the header
Warning: The tag "AN_nfe_swe" not defined in the header
Warning: The tag "AF_nfe_swe" not defined in the header
Warning: The tag "nhomalt_nfe_swe" not defined in the header
Warning: The tag "AC_eas_jpn" not defined in the header
Warning: The tag "AN_eas_jpn" not defined in the header
Warning: The tag "AF_eas_jpn" not defined in the header
Warning: The tag "nhomalt_eas_jpn" not defined in the header
Warning: The tag "AC_eas_kor" not defined in the header
Warning: The tag "AN_eas_kor" not defined in the header
Warning: The tag "AF_eas_kor" not defined in the header
Warning: The tag "nhomalt_eas_kor" not defined in the header
Warning: The tag "AC_eas_oea" not defined in the header
Warning: The tag "AN_eas_oea" not defined in the header
Warning: The tag "AF_eas_oea" not defined in the header
Warning: The tag "nhomalt_eas_oea" not defined in the header
Warning: The tag "AC_sas_female" not defined in the header
Warning: The tag "AN_sas_female" not defined in the header
Warning: The tag "AF_sas_female" not defined in the header
Warning: The tag "nhomalt_sas_female" not defined in the header

```
Is this something to worry about?

**Comment by kokyriakidis** [comment]
I also got the following error after some time but I rerun my command and everything works now. 

```
Running GGD recipe: hg38 dream-syn4-crossmap 2014-08-09
--2019-09-30 01:42:37--  https://s3.amazonaws.com/bcbio_nextgen/dream/synthetic_challenge_set4_tumour_25pctmasked_truth-crossmap-hg38.tar.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... failed: Name or service not known.
wget: unable to resolve host address ‘s3.amazonaws.com’
Traceback (most recent call last):
  File "/RED/RESOURCES/bcbio/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/RED/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 106, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/RED/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 348, in upgrade_bcbio_data
    args.cores, ["ggd", "s3", "raw"])
  File "/RED/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 354, in install_data_local
    _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
  File "/RED/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 480, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/RED/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 868, in _install_with_ggd
    ggd.install_recipe(os.getcwd(), env.system_install, recipe_file, gid)
  File "/RED/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"], system_install)
  File "/RED/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/RED/RESOURCES/bcbio/anaconda/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/RED/RESOURCES/bcbio/anaconda/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bash', '/RED/RESOURCES/bcbio/genomes/Hsapiens/hg38/txtmp/ggd-run.sh']' returned non-zero exit status 4.
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 288, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 45, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/RED/RESOURCES/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/RED/TOOLS', '--genomes', 'hg38', '--distribution', 'ubuntu', '-u', 'development', '--aligners', 'bowtie', '--aligners', 'bowtie2', '--aligners', 'bwa', '--aligners', 'minimap2', '--aligners', 'star', '--aligners', 'hisat2', '--datatarget', 'variation', '--datatarget', 'rnaseq', '--datatarget', 'smallrna', '--datatarget', 'gemini', '--datatarget', 'cadd', '--datatarget', 'vep', '--datatarget', 'dbnsfp', '--datatarget', 'battenberg', '--datatarget', 'kraken', '--datatarget', 'ericscript', '--datatarget', 'gnomad', '--cores', '20', '--toolplus', 'gatk=/home/kokyriakidis/gatk-4.1.2.0/gatk-package-4.1.2.0-local.jar', '--data']' returned non-zero exit status 1
```

**Comment by naumenko-sa** [comment]
Hi Konstantinos @kokyriakidis!

Thanks for testing the recipe!

I think it is safe to ignore these warning: we are using the same list of vcf tags to include for both gnomad genome and exome, and it looks like genome file does not contain certain sub-population, i.e. bgr (Bulgarian genomes). Probably, there is just no genomes from these sub-populations to include, but they had exomes sequenced.

Thanks for benchmarking as well! 
So it was 19h + 13h for downloading + filtering = 32h,
and the file size was reduced from 743G to 55G. 

I think it is a reasonable price to have gnomad 2.1.1 for variant prioritization, we don't need to switch back to 2.0.1

Sergey

**Comment by kokyriakidis** [comment]
Yes! Just stick to 2.1.1 which has better download times! Thanks for your help! :-)
