### ISSUE TITLE
CmdNotFound: umis

### ISSUE THREAD

**Issue by parlar** [bcbio/bcbio-nextgen#2970]
I'm having issues starting run with UMIs using both version 1.1.5 and 1.1.6a. Does not seem to find `umis`. Any ideas?

//Pär

```
[2019-10-08T13:12Z] Aligning lane NA12878-twist-UMI-INHEAD with bwa aligner
Traceback (most recent call last):
  File "/home/pela09/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/home/pela09/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/pela09/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/home/pela09/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/pela09/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 133, in variant2pipeline
    samples = run_parallel("process_alignment", samples)
  File "/home/pela09/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/pela09/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/home/pela09/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 921, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/pela09/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/pela09/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/pela09/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/home/pela09/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "/home/pela09/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/home/pela09/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/pela09/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/home/pela09/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 124, in process_alignment
    return sample.process_alignment(*args)
  File "/home/pela09/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sample.py", line 128, in process_alignment
    data = align_to_sort_bam(fastq1, fastq2, aligner, data)
  File "/home/pela09/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/alignment.py", line 88, in align_to_sort_bam
    names, align_dir, data)
  File "/home/pela09/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/alignment.py", line 163, in _align_from_fastq
    out = align_fn(fastq1, fastq2, align_ref, names, align_dir, data)
  File "/home/pela09/bcbio/anaconda/lib/python3.6/site-packages/bcbio/ngsalign/bwa.py", line 170, in align_pipe
    names, rg_info, data)
  File "/home/pela09/bcbio/anaconda/lib/python3.6/site-packages/bcbio/ngsalign/bwa.py", line 177, in _align_mem
    with postalign.tobam_cl(data, out_file, pair_file != "") as (tobam_cl, tx_out_file):
  File "/home/pela09/bcbio/anaconda/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/pela09/bcbio/anaconda/lib/python3.6/site-packages/bcbio/ngsalign/postalign.py", line 43, in tobam_cl
    yield (_sam_to_grouped_umi_cl(data, umi_consensus, tx_out_file), tx_out_file)
  File "/home/pela09/bcbio/anaconda/lib/python3.6/site-packages/bcbio/ngsalign/postalign.py", line 154, in _sam_to_grouped_umi_cl
    config_utils.get_program("umis", data["config"])))
  File "/home/pela09/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/config_utils.py", line 191, in get_program
    return _get_program_cmd(name, pconfig, config, default)
  File "/home/pela09/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/config_utils.py", line 217, in wrap
    raise CmdNotFound(" ".join(map(repr, (fn.__name__ if six.PY3 else fn.func_name, name, pconfig, default))))
bcbio.pipeline.config_utils.CmdNotFound: '_get_program_cmd' 'umis' {} None
```

Here's a sample of the config file:
```
---
upload:
  dir: ../final
details:
  - files: [/storage/userdata/pela09/green/Data/NA12878-twist-UMI-INHEAD_S1_R1_001.fastq.gz, /storage/userdata/pela09/green/Data/NA12878-twist-UMI-INHEAD_S1_R2_001.fastq.gz]
    description: NA12878-twist-UMI-INHEAD
    metadata:
      batch: batch1
      sex: female
    analysis: variant2
    genome_build: hg38
    algorithm:
      aligner: bwa
      mark_duplicates: true
      umi_type: fastq_name
      variantcaller: [gatk]
      min_allele_fraction: 3
      quality_format: Standard
      coverage_interval: regional
      merge_bamprep: true
      variant_regions: /storage/userdata/pela09/green/Twist_Exome_Target_hg38.bed
      ensemble:
        numpass: 1
```

**Comment by roryk** [comment]
Hi Pär,

Sorry about that-- it is weird that it is not finding umis, it should be in:

`/home/pela09/bcbio/anaconda/bin/`

is it not in there? If it is not, is it in `/home/pela09/bcbio/share/anaconda/envs/python2/bin/umis`?

If I remember right I fixed `umis` so it supports python3, so we might not to have it live in the python2 environment anymore.

**Comment by parlar** [comment]
Thanks for a fast response! 

umis is found in:
```
~/bcbio/anaconda/envs/python2/bin/umis
~/bcbio/tools/bin/umis  (where i've put tools)
```

But it is a bit weird, or perhaps I have misunderstood something? It is looking for umis during the alignment phase. But the fastqs have already been preprocessed with fastp to put the umis (barcodes) in the read names. Why does bcbio need umis (the program) during the alignment step? Is it not fgbio that does the rest of the work during post processing?

I will try installing umis to the base env.

**Comment by roryk** [comment]
Hi Pär,

If you add `~/bcbio/tools/bin/umis` to your PATH you should be all set. `umis` is used at the last step, to move the UMI from the read name in the BAM file to a tag, using the `umis bamtag` subcommand.

**Comment by roryk** [comment]
Thanks, I updated `cloudbiolinux` to not stick this in a separate environment now. v1.0.3 of umis supports python3 so I think this shouldn't be a problem going forward.
