### ISSUE TITLE
Incompatible packages error when building docker image

### ISSUE THREAD

**Issue by gabeng** [bcbio/bcbio-nextgen#2971]
Hi,

I tried to build a docker image from the current development version, but ran into issues with dependencies.
Does your bcbio_docker build job complete without errors?

```
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed
[91m
UnsatisfiableError: The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (python):

  - bcbio-nextgen -> python

The following specifications were found to be incompatible with each other:



Package xz conflicts for:
python=3.6 -> xz[version='5.2.*|>=5.2.3,<5.3.0a0|>=5.2.3,<6.0a0|>=5.2.4,<5.3.0a0|>=5.2.4,<6.0a0']
libxml2 -> xz[version='5.0.*|5.2.*|>=5.2.3,<5.3.0a0|>=5.2.3,<6.0a0|>=5.2.4,<5.3.0a0|>=5.2.4,<6.0a0']
zstd -> xz[version='>=5.2.4,<5.3.0a0|>=5.2.4,<6.0a0']
libarchive -> xz[version='5.0.*|5.2.*|>=5.2.3,<5.3.0a0|>=5.2.3,<6.0a0|>=5.2.4,<5.3.0a0|>=5.2.4,<6.0a0']
Package tk conflicts for:
python=3.6 -> tk[version='8.5.*|8.6.*|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
Package libgcc-ng conflicts for:
bzip2 -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
ncurses -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
xz -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
python=3.6 -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
lzo -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
openssl -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
readline -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
conda-package-handling -> libgcc-ng[version='>=7.3.0']
lz4-c -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
cryptography -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
libxml2 -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
yaml -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
pycosat -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
blas -> libgcc-ng[version='>=7.3.0']
zstd -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
libarchive -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
libedit -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
sqlite -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
libffi -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
ruamel_yaml -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
tk -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
cffi -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
zlib -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
Package cryptography-vectors conflicts for:
cryptography -> cryptography-vectors[version='2.3.*|2.3.1.*']
Package certifi conflicts for:
requests -> certifi[version='>=2017.4.17']
setuptools -> certifi[version='>=2016.09']
urllib3 -> certifi
Package tqdm conflicts for:
conda-package-handling -> tqdm
Package python conflicts for:
conda[version='>=4.7.12'] -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
urllib3 -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
tqdm -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
six -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
certifi -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
chardet -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
python-libarchive-c -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
setuptools -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
pysocks -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
requests -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
idna -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
pyopenssl -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
wheel -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
conda-package-handling -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
cffi -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
pycparser -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
asn1crypto -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
cryptography -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
pip -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
pycosat -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
ruamel_yaml -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
Package zstd conflicts for:
libarchive -> zstd[version='>=1.3.3,<1.3.4.0a0|>=1.3.7,<1.3.8.0a0|>=1.4.0,<1.4.1.0a0']
Package conda-env conflicts for:
conda[version='>=4.7.12'] -> conda-env[version='>=2.6']
Package libstdcxx-ng conflicts for:
zstd -> libstdcxx-ng[version='>=4.9|>=7.3.0']
libffi -> libstdcxx-ng[version='>=4.9|>=7.2.0|>=7.3.0']
ncurses -> libstdcxx-ng[version='>=4.9|>=7.2.0|>=7.3.0']
python=3.6 -> libstdcxx-ng[version='>=4.9|>=7.2.0|>=7.3.0']
sqlite -> libstdcxx-ng[version='>=4.9|>=7.3.0']
lz4-c -> libstdcxx-ng[version='>=4.9|>=7.3.0']
Package libffi conflicts for:
cffi -> libffi[version='>=3.2.1,<3.3.0a0|>=3.2.1,<4.0a0']
python=3.6 -> libffi[version='3.2.*|>=3.2.1,<3.3.0a0|>=3.2.1,<4.0a0']
Package ruamel_yaml conflicts for:
conda[version='>=4.7.12'] -> ruamel_yaml[version='>=0.11.14,<0.16']
Package cytoolz conflicts for:
conda[version='>=4.7.12'] -> cytoolz[version='>=0.8.1']
Package python-libarchive-c conflicts for:
conda-package-handling -> python-libarchive-c
Package toolz conflicts for:
bcbio-nextgen -> toolz
Package zlib conflicts for:
libarchive -> zlib[version='1.2.*|>=1.2.11,<1.3.0a0']
zstd -> zlib[version='>=1.2.11,<1.3.0a0']
python=3.6 -> zlib[version='1.2.*|1.2.11|1.2.8|>=1.2.11,<1.3.0a0']
libxml2 -> zlib[version='1.2.*|1.2.11|>=1.2.11,<1.3.0a0']
tk -> zlib[version='>=1.2.11,<1.3.0a0']
Package bzip2 conflicts for:
python=3.6 -> bzip2[version='>=1.0.6,<2.0a0']
libarchive -> bzip2[version='1.0.*|>=1.0.6,<2.0a0']
Package lz4 conflicts for:
zstd -> lz4
Package six conflicts for:
cryptography -> six[version='>=1.4.1']
conda-package-handling -> six
pyopenssl -> six[version='>=1.5.2']
Package ipaddress conflicts for:
cryptography -> ipaddress
urllib3 -> ipaddress
Package joblib conflicts for:
bcbio-nextgen -> joblib[version='>=0.12']
Package pytest conflicts for:
bcbio-nextgen -> pytest
Package openssl conflicts for:
bcbio-nextgen -> openssl[version='>=1.1.1c,<1.1.2a']
libarchive -> openssl[version='1.0.*|>=1.0.2l,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a']
python=3.6 -> openssl[version='1.0.*|1.0.*,>=1.0.2l,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1c,<1.1.2a']
cryptography -> openssl[version='1.0.*,>=1.0.2n,<1.0.3a|1.0.*|1.0.*,>=1.0.2m,<1.0.3a|1.0.*,>=1.0.2o,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a']
Package msgpack-python conflicts for:
bcbio-nextgen -> msgpack-python
Package wheel conflicts for:
pip -> wheel
Package ncurses conflicts for:
python=3.6 -> ncurses[version='5.9|5.9.*|6.0.*|>=6.0,<7.0a0|>=6.1,<6.2.0a0|>=6.1,<7.0a0']
libedit -> ncurses[version='5.9|6.0.*|>=6.1,<6.2.0a0|>=6.1,<7.0a0']
readline -> ncurses[version='5.9.*|6.0.*|>=6.0,<7.0a0|>=6.1,<6.2.0a0|>=6.1,<7.0a0']
sqlite -> ncurses[version='5.9|5.9.*|>=6.1,<6.2.0a0']
Package chardet conflicts for:
requests -> chardet[version='>=3.0.2,<3.1.0']
Package requests conflicts for:
bcbio-nextgen -> requests
conda[version='>=4.7.12'] -> requests[version='>=2.18.4,<3']
Package libedit conflicts for:
sqlite -> libedit[version='>=3.1.20170329,<3.2.0a0|>=3.1.20181209,<3.2.0a0']
Package cryptography conflicts for:
pyopenssl -> cryptography[version='>=1.3|>=1.3.4|>=1.9|>=2.1.4|>=2.2.1']
urllib3 -> cryptography[version='>=1.3.4']
Package yaml conflicts for:
ruamel_yaml -> yaml[version='>=0.1.7,<0.2.0a0']
Package pycrypto conflicts for:
bcbio-nextgen -> pycrypto
Package openblas conflicts for:
blas -> openblas
Package pysocks conflicts for:
urllib3 -> pysocks[version='>=1.5.6,<2.0,!=1.5.7']
Package mkl conflicts for:
blas -> mkl
Package h5py conflicts for:
bcbio-nextgen -> h5py
Package lz4-c conflicts for:
zstd -> lz4-c[version='>=1.8.1.2,<1.8.2.0a0|>=1.8.3,<1.8.4.0a0']
libarchive -> lz4-c[version='>=1.8.0,<1.9.0a0|>=1.8.1.2,<1.8.2.0a0|>=1.8.1.2,<1.9.0a0|>=1.8.3,<1.8.4.0a0']
Package enum34 conflicts for:
cryptography -> enum34
conda[version='>=4.7.12'] -> enum34
Package setuptools conflicts for:
pip -> setuptools
ruamel_yaml -> setuptools
conda[version='>=4.7.12'] -> setuptools[version='>=31.0.1']
wheel -> setuptools
Package _libgcc_mutex conflicts for:
libgcc-ng -> _libgcc_mutex=[build=main]
Package scipy conflicts for:
bcbio-nextgen -> scipy[version='>=1.3.0']
Package pyyaml conflicts for:
bcbio-nextgen -> pyyaml
Package libarchive conflicts for:
conda-package-handling -> libarchive[version='>=3.3.3']
python-libarchive-c -> libarchive
Package futures conflicts for:
conda-package-handling -> futures
conda[version='>=4.7.12'] -> futures[version='>=3.0.0']
Package bioblend conflicts for:
bcbio-nextgen -> bioblend
Package pyopenssl conflicts for:
conda[version='>=4.7.12'] -> pyopenssl[version='>=16.2.0']
urllib3 -> pyopenssl[version='>=0.14']
Package py conflicts for:
bcbio-nextgen -> py
Package readline conflicts for:
sqlite -> readline[version='6.2.*|7.0.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0']
python=3.6 -> readline[version='6.2.*|7.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0']
Package ipyparallel conflicts for:
bcbio-nextgen -> ipyparallel[version='>=6.0.2']
Package liblapacke conflicts for:
blas -> liblapacke==3.8.0[build='9_openblas|9_mkl|8_openblas|8_mkl|7_openblas|7_h6e990d7_netlib|6_mkl|6_h6e990d7_netlib|5_mkl|4_mkl|4_h6e990d7_netlib|11_mkl|10_mkl|10_openblas|11_openblas|12_mkl|12_openblas|13_mkl|13_openblas|4_openblas|5_h6e990d7_netlib|5_openblas|6_openblas|7_mkl|*netlib']
Package sqlite conflicts for:
python=3.6 -> sqlite[version='3.13.*|3.20.*|>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.24.0,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.28.0,<4.0a0|>=3.29.0,<4.0a0']
Package idna conflicts for:
requests -> idna[version='>=2.5,<2.6|>=2.5,<2.7|>=2.5,<2.8|>=2.5,<2.9']
urllib3 -> idna[version='>=2.0.0']
cryptography -> idna[version='>=2.1']
Package pybedtools conflicts for:
bcbio-nextgen -> pybedtools
Package libiconv conflicts for:
libarchive -> libiconv[version='>=1.15,<1.16.0a0']
libxml2 -> libiconv[version='1.15|>=1.15,<1.16.0a0']
Package fadapa conflicts for:
bcbio-nextgen -> fadapa
Package seaborn conflicts for:
bcbio-nextgen -> seaborn
Package libxml2 conflicts for:
libarchive -> libxml2[version='>=2.9.4,<2.10.0a0|>=2.9.7,<2.10.0a0|>=2.9.8,<2.10.0a0|>=2.9.9,<2.10.0a0']
Package beautifulsoup4 conflicts for:
bcbio-nextgen -> beautifulsoup4
Package conda-build conflicts for:
conda[version='>=4.7.12'] -> conda-build[version='>=3']
Package icu conflicts for:
libxml2 -> icu[version='56.*|58.*|>=58.2,<59.0a0|>=64.2,<65.0a0']
Package tabulate conflicts for:
bcbio-nextgen -> tabulate
Package cffi conflicts for:
cryptography -> cffi[version='>=1.7']
Package pip conflicts for:
bcbio-nextgen -> pip
python=3.6 -> pip
Package lzo conflicts for:
libarchive -> lzo[version='>=2.10,<3.0a0']
Package conda-package-handling conflicts for:
conda[version='>=4.7.12'] -> conda-package-handling[version='>=1.3.0']
Package urllib3 conflicts for:
requests -> urllib3[version='>=1.21.1,<1.22|>=1.21.1,<1.23|>=1.21.1,<1.24|>=1.21.1,<1.25|>=1.21.1,<1.26,!=1.25.0,!=1.25.1']
Package boto conflicts for:
bcbio-nextgen -> boto
Package ipython-cluster-helper conflicts for:
bcbio-nextgen -> ipython-cluster-helper[version='>=0.6.1']
Package libgfortran-ng conflicts for:
blas -> libgfortran-ng[version='>=7,<8.0a0']
Package seqcluster conflicts for:
bcbio-nextgen -> seqcluster
Package pandas conflicts for:
bcbio-nextgen -> pandas
Package geneimpacts conflicts for:
bcbio-nextgen -> geneimpacts
Package pyvcf conflicts for:
bcbio-nextgen -> pyvcf
Package libblas conflicts for:
blas -> libblas==3.8.0[build='9_openblas|9_mkl|9_blis|8_blis|7_openblas|7_h6e990d7_netlib|7_blis|6_mkl|6_h6e990d7_netlib|5_openblas|5_mkl|5_h6e990d7_netlib|4_mkl|4_h6e990d7_netlib|4_blis|13_openblas|12_openblas|12_blis|11_mkl|10_blis|10_mkl|10_openblas|11_blis|11_openblas|12_mkl|13_blis|13_mkl|4_openblas|5_blis|6_blis|6_openblas|7_mkl|8_mkl|8_openblas']
Package arrow conflicts for:
bcbio-nextgen -> arrow
Package ca-certificates conflicts for:
openssl -> ca-certificates
Package htslib conflicts for:
bcbio-nextgen -> htslib
Package _low_priority conflicts for:
libarchive -> _low_priority
Package biopython conflicts for:
bcbio-nextgen -> biopython
Package psutil conflicts for:
bcbio-nextgen -> psutil
Package yamllint conflicts for:
bcbio-nextgen -> yamllint
Package python-dateutil conflicts for:
bcbio-nextgen -> python-dateutil[version='>=2.5.0']
Package blas conflicts for:
nomkl -> blas=[build=openblas]
Package pysam conflicts for:
bcbio-nextgen -> pysam[version='>=0.13.0']
Package pycosat conflicts for:
conda[version='>=4.7.12'] -> pycosat[version='>=0.6.3']
Package pytest-mock conflicts for:
bcbio-nextgen -> pytest-mock
Package asn1crypto conflicts for:
cryptography -> asn1crypto[version='>=0.21.0']
Package cyvcf2 conflicts for:
bcbio-nextgen -> cyvcf2
Package pycparser conflicts for:
cffi -> pycparser
Package expat conflicts for:
libarchive -> expat[version='>=2.2.4,<3.0a0|>=2.2.5,<2.3.0a0']
Package pytest-cov conflicts for:
bcbio-nextgen -> pytest-cov[version='>=2.6.1']
Package matplotlib conflicts for:
bcbio-nextgen -> matplotlib
Package mock conflicts for:
bcbio-nextgen -> mock
Package liblapack conflicts for:
blas -> liblapack==3.8.0[build='9_openblas|9_mkl|8_openblas|8_mkl|7_openblas|7_h6e990d7_netlib|6_mkl|6_h6e990d7_netlib|5_mkl|4_mkl|4_h6e990d7_netlib|11_mkl|10_mkl|10_openblas|11_openblas|12_mkl|12_openblas|13_mkl|13_openblas|4_openblas|5_h6e990d7_netlib|5_openblas|6_openblas|7_mkl|*netlib']
Package gffutils conflicts for:
bcbio-nextgen -> gffutils
Package statsmodels conflicts for:
bcbio-nextgen -> statsmodels
Package dnapi conflicts for:
bcbio-nextgen -> dnapi
Package libcblas conflicts for:
blas -> libcblas==3.8.0[build='9_openblas|9_mkl|9_blis|8_blis|7_openblas|7_h6e990d7_netlib|7_blis|6_mkl|6_h6e990d7_netlib|5_openblas|5_mkl|5_h6e990d7_netlib|4_mkl|4_h6e990d7_netlib|4_blis|13_openblas|12_openblas|12_blis|11_mkl|10_blis|10_mkl|10_openblas|11_blis|11_openblas|12_mkl|13_blis|13_mkl|4_openblas|5_blis|6_blis|6_openblas|7_mkl|8_mkl|8_openblas']
Package logbook conflicts for:
bcbio-nextgen -> logbook

[0mChecking required dependencies
Installing isolated base python installation
Installing bcbio-nextgen
[91mTraceback (most recent call last):
  File "bcbio_nextgen_install.py", line 288, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 39, in main
    bcbio = install_conda_pkgs(anaconda, args)
  File "bcbio_nextgen_install.py", line 106, in install_conda_pkgs
    ["--only-deps", "bcbio-nextgen", TARGETPY], env=env)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
[0m[91m    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio-nextgen/anaconda/bin/conda', 'install', '--yes', '-c', 'bioconda', '-c', 'conda-forge', '--only-deps', 'bcbio-nextgen', 'python=3.6']' returned non-zero exit status 1
```

**Comment by chapmanb** [comment]
Ben;
Thanks for the report and apologies about these issues. I've been trying to reproduce locally to see if I could understand the root cause of all those incompatibilities but it seems to be installing cleanly. I'm not sure what is going on with your Docker build and will dig more. Sorry to not know right now and thanks again for testing it out.

**Comment by gabeng** [comment]
My build job now succeeded (bcbio 1.1.7). Not sure what the issue was. Closing this now.

**Comment by roryk** [comment]
Hi Ben! I was just about to ask, good timing. Thanks for following up!

**Comment by mrityunjayravi** [comment]
Hi,
I am getting below error

(base) PS C:\Users\mrravi> conda install -c menpo dlib
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining pyparsing:   4%|██▎                                                           | 2/53 [00:00<00:00, 63.92it/s]|failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - dlib -> python[version='2.7.*|3.5.*']
  - dlib -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0']

Your python: python=3.6

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:



Package setuptools conflicts for:
dlib -> python=2.7 -> pip -> setuptools
python=3.6 -> pip -> setuptools
Package wheel conflicts for:
dlib -> python=2.7 -> pip -> wheel
python=3.6 -> pip -> wheel
Package pip conflicts for:
dlib -> python=2.7 -> pip
python=3.6 -> pip
Package certifi conflicts for:
dlib -> python=2.7 -> pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26|>=2017.4.17']
python=3.6 -> pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26|>=2017.4.17']
Package wincertstore conflicts for:
python=3.6 -> pip -> setuptools -> wincertstore[version='>=0.2']
dlib -> python=2.7 -> pip -> setuptools -> wincertstore[version='>=0.2']
Package ca-certificates conflicts for:
python=3.6 -> pip -> requests -> urllib3[version='>=1.21.1,<1.24'] -> cryptography[version='>=1.3.4'] -> openssl=1.0 -> ca-certificates
dlib -> python=2.7 -> ca-certificates
Package msgpack-python conflicts for:
python=3.6 -> pip -> cachecontrol -> msgpack-python
dlib -> python=2.7 -> pip -> cachecontrol -> msgpack-python
