### ISSUE TITLE
support for unaligned bam/cram

### ISSUE THREAD

**Issue by matthdsm** [bcbio/bcbio-nextgen#3011]
Hi,

Are there any plans for/support for using unaligned bam/cram files as input files? We're looking into converting our archiving strategy from fastq to cram, since this should result in more space efficient storage.

Thanks
M

**Comment by matthdsm** [comment]
also, the GATK pipeline starts from uBam, so it'd be nice to have feature parity there.
Starting from the uBam also should improve the use of UMI's in the pipeline (read that somewhere on the GATK blog)

**Comment by roryk** [comment]
Hi Matt,

Wow, I somehow missed this was a thing. Have you tried running bcbio and turning on the aligner while using the unaligned BAM file? bcbio should convert the BAM file to FASTQ if the aligner is requested. I'm curious if at least that part works out of the box.

**Comment by matthdsm** [comment]
Hi Rory,

I did some further digging, and [the GATK reference pipeline](https://github.com/gatk-workflows/gatk4-exome-analysis-pipeline) goes somewhat like this:
- demultiplex to uBam
- on the fly uBam > fastq > bam using pipes
- merge the uBam and bam to retain unmapped reads and UMI data and whatnot.
- further processing

At the end of the pipeline, the mapped/merged bam is compressed to cram and can be used for archiving, which is also more space efficient than compressed fastq. Some quick tests show about 33% less data usage when storing cram vs fastq.gz (lossless).

**Comment by matthdsm** [comment]
Also, I can confirm bcbio autmatically converts the uBam back to fq when an aligner is specified.

**Comment by matthdsm** [comment]
There's also cram support, but only for mapped cram files, since the cram conversion is done by BioBamBam and uses range queries.

Traceback:
```
[2019-11-18T11:26Z] CRAM to fastq chr1:12145-12310
[2019-11-18T11:26Z] [E] ScramDecoder: reference sequence chr1 does not exist
[2019-11-18T11:26Z] ScramDecoder: failed to open file /home/matdsmet/bcbio_annotation/test_runs/uBam/input/DNA025865_S95_R1_001.cram in CRAM read mode via callback with range.
[2019-11-18T11:26Z] /home/galaxy/bcbio/anaconda/share/biobambam-2.0.87-1/bin/../lib/libmaus2.so.2(libmaus2::util::StackTrace::StackTrace()+0x4c)[0x7fd670a8ef8c]
[2019-11-18T11:26Z] bamtofastq(libmaus2::exception::LibMausException::LibMausException()+0x20)[0x41a680]
[2019-11-18T11:26Z] bamtofastq()[0x484f4e]
[2019-11-18T11:26Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; bamtofastq filename=/home/matdsmet/bcbio_annotation/test_runs/uBam/input/DNA025865_S95_R1_001.cram inputformat=cram T=/tmp/bcbio/tmpr78dpbvb/DNA025865_S95_R1_001-chr1_12145_12310-s1-sort gz=1 collate=1 colsbs=2097152 exclude=SECONDARY,SUPPLEMENTARY F=/tmp/bcbio/tmpr78dpbvb/DNA025865_S95_R1_001-chr1_12145_12310-p1.fq.gz F2=/tmp/bcbio/tmpr78dpbvb/DNA025865_S95_R1_001-chr1_12145_12310-p2.fq.gz S=/tmp/bcbio/tmpr78dpbvb/DNA025865_S95_R1_001-chr1_12145_12310-s1.fq.gz O=/tmp/bcbio/tmpr78dpbvb/DNA025865_S95_R1_001-chr1_12145_12310-o1.fq.gz O2=/tmp/bcbio/tmpr78dpbvb/DNA025865_S95_R1_001-chr1_12145_12310-o2.fq.gz reference=/home/galaxy/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa ranges='chr1:12145-12310'
[E] ScramDecoder: reference sequence chr1 does not exist
ScramDecoder: failed to open file /home/matdsmet/bcbio_annotation/test_runs/uBam/input/DNA025865_S95_R1_001.cram in CRAM read mode via callback with range.
/home/galaxy/bcbio/anaconda/share/biobambam-2.0.87-1/bin/../lib/libmaus2.so.2(libmaus2::util::StackTrace::StackTrace()+0x4c)[0x7fd670a8ef8c]
bamtofastq(libmaus2::exception::LibMausException::LibMausException()+0x20)[0x41a680]
bamtofastq()[0x484f4e]
bamtofastq()[0x48793d]
bamtofastq()[0x48e205]
bamtofastq()[0x415f73]
bamtofastq()[0x4169fe]
bamtofastq()[0x41210a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7fd66d44df45]
bamtofastq()[0x412912]

' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/galaxy/bcbio/tools/bin/bcbio_nextgen.py", line 238, in <module>
    main(**kwargs)
  File "/home/galaxy/bcbio/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 128, in variant2pipeline
    samples = run_parallel("prep_align_inputs", samples)
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 921, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 180, in prep_align_inputs
    return alignprep.create_inputs(*args)
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/bcbio/ngsalign/alignprep.py", line 43, in create_inputs
    data["files"] = prep_fastq_inputs(data["files"], data)
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/bcbio/ngsalign/alignprep.py", line 339, in prep_fastq_inputs
    out = _bgzip_from_cram(in_files[0], data["dirs"], data)
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/bcbio/ngsalign/alignprep.py", line 424, in _bgzip_from_cram
    fastqs, part_dir = _cram_to_fastq_regions(regions, cram_file, dirs, data)
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/bcbio/ngsalign/alignprep.py", line 492, in _cram_to_fastq_regions
    data["config"])
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 921, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 63, in wrapper
    out = f(*args, **kwargs)
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/bcbio/ngsalign/alignprep.py", line 524, in _cram_to_fastq_region
    do.run(cmd.format(**locals()), "CRAM to fastq %s" % region if region else "")
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/galaxy/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; bamtofastq filename=/home/matdsmet/bcbio_annotation/test_runs/uBam/input/DNA025865_S95_R1_001.cram inputformat=cram T=/tmp/bcbio/tmpr78dpbvb/DNA025865_S95_R1_001-chr1_12145_12310-s1-sort gz=1 collate=1 colsbs=2097152 exclude=SECONDARY,SUPPLEMENTARY F=/tmp/bcbio/tmpr78dpbvb/DNA025865_S95_R1_001-chr1_12145_12310-p1.fq.gz F2=/tmp/bcbio/tmpr78dpbvb/DNA025865_S95_R1_001-chr1_12145_12310-p2.fq.gz S=/tmp/bcbio/tmpr78dpbvb/DNA025865_S95_R1_001-chr1_12145_12310-s1.fq.gz O=/tmp/bcbio/tmpr78dpbvb/DNA025865_S95_R1_001-chr1_12145_12310-o1.fq.gz O2=/tmp/bcbio/tmpr78dpbvb/DNA025865_S95_R1_001-chr1_12145_12310-o2.fq.gz reference=/home/galaxy/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa ranges='chr1:12145-12310'
[E] ScramDecoder: reference sequence chr1 does not exist
ScramDecoder: failed to open file /home/matdsmet/bcbio_annotation/test_runs/uBam/input/DNA025865_S95_R1_001.cram in CRAM read mode via callback with range.
/home/galaxy/bcbio/anaconda/share/biobambam-2.0.87-1/bin/../lib/libmaus2.so.2(libmaus2::util::StackTrace::StackTrace()+0x4c)[0x7fd670a8ef8c]
bamtofastq(libmaus2::exception::LibMausException::LibMausException()+0x20)[0x41a680]
bamtofastq()[0x484f4e]
bamtofastq()[0x48793d]
bamtofastq()[0x48e205]
bamtofastq()[0x415f73]
bamtofastq()[0x4169fe]
bamtofastq()[0x41210a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7fd66d44df45]
bamtofastq()[0x412912]

' returned non-zero exit status 1.
```

**Comment by matthdsm** [comment]
xref #3107, because merging ubam with bam could also be included in the archiving strategy

**Comment by matthdsm** [comment]
apparently, most of the logic is already there, it's just missing som plumbing I suppose:
https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/broad/picardrun.py#L154

**Comment by matthdsm** [comment]
Upon further inspection, all the moving parts are already present, it really just needs plumbing
@roryk,
I'd need plug the `picard_fastq_to_bam` and `picard_sam_to_bam` into or alignment part of the pipeline. Do you have a guide of some sorts on where to start?

Thanks
M
