### ISSUE TITLE
MACS2: revenge of NumPy

### ISSUE THREAD

**Issue by mjsteinbaugh** [bcbio/bcbio-nextgen#3014]
Hey @roryk, I'm seeing the wrong version of numpy pop up for macs2 again in the ChIP-seq pipeline. @sjhosui mentioned also seeing this too. See related issues #2853 and #1105.

Here's the error:

```
numpy.ufunc has the wrong size, try recompiling
```

I can reproduce this running the `chipseq` unit test on a clean install of v1.1.8. Here's the log:

```
[2019-11-14T16:42Z] Timing: peakcalling
[2019-11-14T16:42Z] Skipping peak calling. No input sample for Test1
[2019-11-14T16:42Z] multiprocessing: peakcalling
[2019-11-14T16:42Z] macs2 for Test2
[2019-11-14T16:42Z] Traceback (most recent call last):
[2019-11-14T16:42Z]   File "/usr/local/bcbio/stable/tools/bin/macs2", line 622, in <module>
[2019-11-14T16:42Z]     main()
[2019-11-14T16:42Z]   File "/usr/local/bcbio/stable/tools/bin/macs2", line 56, in main
[2019-11-14T16:42Z]     from MACS2.callpeak_cmd import run
[2019-11-14T16:42Z]   File "/data00/bcbio/v1.1.8/install/anaconda/envs/python2/lib/python2.7/site-pac                       kages/MACS2/callpeak_cmd.py", line 31, in <module>
[2019-11-14T16:42Z]     from MACS2.OptValidator import opt_validate
[2019-11-14T16:42Z]   File "/data00/bcbio/v1.1.8/install/anaconda/envs/python2/lib/python2.7/site-pac                       kages/MACS2/OptValidator.py", line 27, in <module>
[2019-11-14T16:42Z]     from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
[2019-11-14T16:42Z]   File "__init__.pxd", line 861, in init MACS2.IO.Parser (MACS2/IO/Parser.c:22634                       )
[2019-11-14T16:42Z] ValueError: numpy.ufunc has the wrong size, try recompiling
[2019-11-14T16:42Z] Uncaught exception occurred
```

I tried to do some conda sleuthing yesterday but I can't force the internal python2 conda environment to install the correct version of numpy. When I try to do this, conda ends up running in an infinite loop.

Here's the unsuccessful steps I tried:

```sh
bcbio_conda install --yes --force-reinstall --name python2 numpy
bcbio_conda install --yes --force-reinstall --name python2 macs2
```

No dice, still see the error. Also, I'm not seeing multiple versions of numpy installed inside the python2 environment, so attempting to wipe and reinstall doesn't seem to work.

Checking the environments, here's what I'm seeing with conda:

```sh
conda list -p /usr/local/bcbio/v1.1.8/install/anaconda/envs/python2 | grep numpy
## numpy                     1.11.3           py27h2aefc1b_9
## numpy-base                1.11.3           py27h7cdd4dd_9
```

```sh
conda list -p /usr/local/bcbio/v1.1.8/install/anaconda/envs/python2 | grep macs2
## macs2                     2.1.2           py27r351h14c3975_1    bioconda
```

```sh
conda list -p /usr/local/bcbio/v1.1.8/install/anaconda/envs/python3 | grep macs2
## not installed (expected)
```

We're expecting numpy 1.16.4 here instead, which I can confirm in my v1.1.5 install:

```sh
conda list -p /usr/local/bcbio/v1.1.5/install/anaconda/envs/python2 | grep numpy
## numpy                     1.16.4           py27h95a1406_0    conda-forge
```

The MACS2 version is the same for that previous release:

```sh
conda list -p /usr/local/bcbio/v1.1.5/install/anaconda/envs/python2 | grep macs2
## macs2                     2.1.2           py27r351h14c3975_1    bioconda
```

Here's a list of the current options to install numpy 1.16.4:

```sh
conda search numpy=1.16.4
```

```
Loading channels: done
# Name                       Version           Build  Channel
numpy                         1.16.4  py27h7e9f1db_0  pkgs/main
numpy                         1.16.4  py27h95a1406_0  conda-forge
numpy                         1.16.4  py27h99e49ec_0  pkgs/main
numpy                         1.16.4  py36h7e9f1db_0  pkgs/main
numpy                         1.16.4  py36h95a1406_0  conda-forge
numpy                         1.16.4  py36h99e49ec_0  pkgs/main
numpy                         1.16.4  py37h7e9f1db_0  pkgs/main
numpy                         1.16.4  py37h95a1406_0  conda-forge
numpy                         1.16.4  py37h99e49ec_0  pkgs/main
```

Trying to force the same version of numpy in my v1.1.5 install isn't working, so I'm out of ideas:

```sh
bcbio_conda install \
    --name=python2 \
    --channel=conda-forge \
    numpy=1.16.4=py27h95a1406_0
```

```
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
[...]
Examining openblas-devel
[...]
<endless conda loop>
```

The `openblas-devel` recipe seems to be the culprit, but I'm not sure how yet.

**Comment by mjsteinbaugh** [comment]
PS any chance we can just bump MACS2 to the current 2.2.5 release that supports Python 3? Maybe that's the easier fix here.

**Comment by mjsteinbaugh** [comment]
To follow up on this, I can confirm that the `chipseq` unit tests pass for my v1.1.5 install but currently fail for v1.1.7 and v1.1.8, which have the numpy version mismatch for the internal conda python2 environment.

**Comment by mjsteinbaugh** [comment]
@roryk This is still failing on 1.1.9:

```
[2019-12-16T13:00Z] Timing: peakcalling
[2019-12-16T13:00Z] Skipping peak calling. No input sample for Test1
[2019-12-16T13:00Z] multiprocessing: peakcalling
[2019-12-16T13:00Z] macs2 for Test2
[2019-12-16T13:00Z] Traceback (most recent call last):
[2019-12-16T13:00Z]   File "/n/app/bcbio/stable/tools/bin/macs2", line 622, in <module>
[2019-12-16T13:00Z]     main()
[2019-12-16T13:00Z]   File "/n/app/bcbio/stable/tools/bin/macs2", line 56, in main
[2019-12-16T13:00Z]     from MACS2.callpeak_cmd import run
[2019-12-16T13:00Z]   File "/n/app/bcbio/1.1.9/install/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 31, in <module>
[2019-12-16T13:00Z]     from MACS2.OptValidator import opt_validate
[2019-12-16T13:00Z]   File "/n/app/bcbio/1.1.9/install/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/OptValidator.py", line 27, in <module>
[2019-12-16T13:00Z]     from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
[2019-12-16T13:00Z]   File "__init__.pxd", line 861, in init MACS2.IO.Parser (MACS2/IO/Parser.c:22634)
[2019-12-16T13:00Z] ValueError: numpy.ufunc has the wrong size, try recompiling
[2019-12-16T13:00Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/n/app/bcbio/1.1.9/install/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/n/app/bcbio/1.1.9/install/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /n/app/bcbio/stable/tools/bin/macs2 callpeak -t /data00/n/app/bcbio/git/tests/test_automated_output/align/Test2/Test2-sort_chrom-noMito.unique-noduplicates.bam -c /data00/n/app/bcbio/git/tests/test_automated_output/align/Test1/Test1-sort_chrom-noMito.unique-noduplicates.bam  -g 36572 -n Test2 --bdg --nomodel
Traceback (most recent call last):
  File "/n/app/bcbio/stable/tools/bin/macs2", line 622, in <module>
    main()
  File "/n/app/bcbio/stable/tools/bin/macs2", line 56, in main
    from MACS2.callpeak_cmd import run
  File "/n/app/bcbio/1.1.9/install/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 31, in <module>
    from MACS2.OptValidator import opt_validate
  File "/n/app/bcbio/1.1.9/install/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/OptValidator.py", line 27, in <module>
    from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
  File "__init__.pxd", line 861, in init MACS2.IO.Parser (MACS2/IO/Parser.c:22634)
ValueError: numpy.ufunc has the wrong size, try recompiling
' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/n/app/bcbio/1.1.9/install/anaconda/lib/python3.6/site-packages/bcbio/chipseq/macs2.py", line 41, in run
    do.run(cmd.format(**locals()), "macs2 for %s" % name)
  File "/n/app/bcbio/1.1.9/install/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/n/app/bcbio/1.1.9/install/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /n/app/bcbio/stable/tools/bin/macs2 callpeak -t /data00/n/app/bcbio/git/tests/test_automated_output/align/Test2/Test2-sort_chrom-noMito.unique-noduplicates.bam -c /data00/n/app/bcbio/git/tests/test_automated_output/align/Test1/Test1-sort_chrom-noMito.unique-noduplicates.bam  -g 36572 -n Test2 --bdg --nomodel
Traceback (most recent call last):
  File "/n/app/bcbio/stable/tools/bin/macs2", line 622, in <module>
    main()
  File "/n/app/bcbio/stable/tools/bin/macs2", line 56, in main
    from MACS2.callpeak_cmd import run
  File "/n/app/bcbio/1.1.9/install/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 31, in <module>
    from MACS2.OptValidator import opt_validate
  File "/n/app/bcbio/1.1.9/install/anaconda/envs/python2/lib/python2.7/site-packages/MACS2/OptValidator.py", line 27, in <module>
    from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
  File "__init__.pxd", line 861, in init MACS2.IO.Parser (MACS2/IO/Parser.c:22634)
ValueError: numpy.ufunc has the wrong size, try recompiling
' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/n/app/bcbio/stable/tools/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/n/app/bcbio/stable/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/n/app/bcbio/1.1.9/install/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/n/app/bcbio/1.1.9/install/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/n/app/bcbio/1.1.9/install/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 382, in chipseqpipeline
    samples = peaks.peakcall_prepare(samples, run_parallel)
  File "/n/app/bcbio/1.1.9/install/anaconda/lib/python3.6/site-packages/bcbio/chipseq/peaks.py", line 41, in peakcall_prepare
    after_process = run_parallel("peakcalling", to_process)
  File "/n/app/bcbio/1.1.9/install/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/n/app/bcbio/1.1.9/install/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/n/app/bcbio/1.1.9/install/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1003, in __call__
    if self.dispatch_one_batch(iterator):
  File "/n/app/bcbio/1.1.9/install/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 834, in dispatch_one_batch
    self._dispatch(tasks)
  File "/n/app/bcbio/1.1.9/install/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 753, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/n/app/bcbio/1.1.9/install/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 201, in apply_async
    result = ImmediateResult(func)
  File "/n/app/bcbio/1.1.9/install/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 582, in __init__
    self.results = batch()
  File "/n/app/bcbio/1.1.9/install/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/n/app/bcbio/1.1.9/install/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/n/app/bcbio/1.1.9/install/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/n/app/bcbio/1.1.9/install/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 181, in peakcalling
    return peaks.calling(*args)
  File "/n/app/bcbio/1.1.9/install/anaconda/lib/python3.6/site-packages/bcbio/chipseq/peaks.py", line 55, in calling
    dd.get_chip_method(data), data["resources"], data)
  File "/n/app/bcbio/1.1.9/install/anaconda/lib/python3.6/site-packages/bcbio/chipseq/macs2.py", line 44, in run
    raise RuntimeWarning("macs2 terminated with an error. "
RuntimeWarning: macs2 terminated with an error. Please, check the message and report error if it is related to bcbio. You can add specific options for the sample setting resources as explained in docs: https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#sample-specific-resources
FAILED

================================================ FAILURES =================================================
______________________________________________ test_chipseq _______________________________________________

install_test_files = None, data_dir = '/data00/n/app/bcbio/git/tests/data/automated'

    @pytest.mark.chipseq
    def test_chipseq(install_test_files, data_dir):
        """
        Run a chip-seq alignment with Bowtie2
        """
        with make_workdir() as workdir:
            cl = ["bcbio_nextgen.py",
                  get_post_process_yaml(data_dir, workdir),
                  os.path.join(data_dir, os.pardir, "test_chipseq"),
                  os.path.join(data_dir, "run_info-chipseq.yaml")]
>           subprocess.check_call(cl)

integration/test_automated_analysis.py:190:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

popenargs = (['bcbio_nextgen.py', '/data00/n/app/bcbio/git/tests/test_automated_output/bcbio_system.yaml', '/data00/n/app/bcbio/git/tests/data/automated/../test_chipseq', '/data00/n/app/bcbio/git/tests/data/automated/run_info-chipseq.yaml'],)
kwargs = {}, retcode = 1
cmd = ['bcbio_nextgen.py', '/data00/n/app/bcbio/git/tests/test_automated_output/bcbio_system.yaml', '/data00/n/app/bcbio/git/tests/data/automated/../test_chipseq', '/data00/n/app/bcbio/git/tests/data/automated/run_info-chipseq.yaml']

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.

        The arguments are the same as for the call function.  Example:

        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['bcbio_nextgen.py', '/data00/n/app/bcbio/git/tests/test_automated_output/bcbio_system.yaml', '/data00/n/app/bcbio/git/tests/data/automated/../test_chipseq', '/data00/n/app/bcbio/git/tests/data/automated/run_info-chipseq.yaml']' returned non-zero exit status 1.

/n/app/bcbio/1.1.9/install/anaconda/lib/python3.6/subprocess.py:291: CalledProcessError
============================================ warnings summary =============================================
/n/app/bcbio/1.1.9/install/anaconda/lib/python3.6/site-packages/Bio/Alphabet/__init__.py:26
  /n/app/bcbio/1.1.9/install/anaconda/lib/python3.6/site-packages/Bio/Alphabet/__init__.py:26: PendingDeprecationWarning: We intend to remove or replace Bio.Alphabet in 2020, ideally avoid using it explicitly in your code. Please get in touch if you will be adversely affected by this. https://github.com/biopython/biopython/issues/2046
    PendingDeprecationWarning)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
============================== 1 failed, 82 deselected, 1 warning in 34.73s ===============================
```

**Comment by roryk** [comment]
I think these issues should be solved now, macs2 has python3 support and is now in the base bcbio environment.
