### ISSUE TITLE
GGD recipe error during data upgrade for v1.1.8

### ISSUE THREAD

**Issue by mjsteinbaugh** [bcbio/bcbio-nextgen#3021]
I'm hitting a CloudBioLinux / GGD recipe error when attempting to upgrade the data for my install:

```sh
bcbio_nextgen.py upgrade --upgrade="stable" --data
```

Here's the log:

```
Upgrading bcbio-nextgen data files
[...]
Running GGD recipe: hg38 hapmap_snps 20160105
Traceback (most recent call last):
  File "/n/app/bcbio/stable/tools/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/data00/bcbio/v1.1.8/install/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 106, in upgrade$bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/data00/bcbio/v1.1.8/install/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 369, in upgrade_bcbio_data
    args.cores, ["ggd", "s3", "raw"])
  File "/home/mike/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 354, in install_data_local
    _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
  File "/home/mike/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 480, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/home/mike/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 868, in _install_with_ggd
    ggd.install_recipe(os.getcwd(), env.system_install, recipe_file, gid)
  File "/home/mike/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"], system_install)
  File "/home/mike/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/data00/bcbio/v1.1.8/install/anaconda/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/data00/bcbio/v1.1.8/install/anaconda/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bash', '/data00/n/app/bcbio/v1.1.8/install/genomes/Hsapiens/hg38/txtmp/g
gd-run.sh']' returned non-zero exit status 6.
```

**Comment by mjsteinbaugh** [comment]
Ah OK re-running I got a more verbose error. Here's what's up:

```
Running GGD recipe: hg38 hapmap_snps 20160105
Running GGD recipe: hg38 1000g_omni_snps 20160105
--2019-11-22 15:41:24--  ftp://gsapubftp-anonymous:*password*@ftp.broadinstitute.org/bundle/hg38//1000G_omni2.5.hg38.vcf$
gz
           => ‘variation/1000G_omni2.5.vcf.gz’
Resolving ftp.broadinstitute.org (ftp.broadinstitute.org)... 69.173.70.223
Connecting to ftp.broadinstitute.org (ftp.broadinstitute.org)|69.173.70.223|:21... connected.
Logging in as gsapubftp-anonymous ...
Login incorrect.
Traceback (most recent call last):
  File "/n/app/bcbio/stable/tools/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/data00/bcbio/v1.1.8/install/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 106, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/data00/bcbio/v1.1.8/install/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 369, in upgrade_bcbio_d
ata
    args.cores, ["ggd", "s3", "raw"])
  File "/tmp/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 354, in install_data_local
    _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
  File "/tmp/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 480, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/tmp/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 868, in _install_with_ggd
    ggd.install_recipe(os.getcwd(), env.system_install, recipe_file, gid)
  File "/tmp/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"], system_install)
  File "/tmp/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/data00/bcbio/v1.1.8/install/anaconda/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/data00/bcbio/v1.1.8/install/anaconda/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bash', '/data00/n/app/bcbio/v1.1.8/install/genomes/Hsapiens/hg38/txtmp/ggd-run.
sh']' returned non-zero exit status 6.
```

Seems like the login at `ftp.broadinstitute.org` is no longer working.

**Comment by chapmanb** [comment]
Mike;
Tackled this one over in the cloudbiolinux report, but unfortunately this is a confusing error message from the Broad FTP server when it's overloaded. Hopefully retrying at a later point will get it working cleanly for you.

**Comment by mjsteinbaugh** [comment]
In case anybody else hits this error, I'm still seeing this problem with a clean install of bcbio-nextgen 1.1.9 (see related cloudbiolinux issue https://github.com/chapmanb/cloudbiolinux/issues/329)
