### ISSUE TITLE
Dependency error in mamba package installation

### ISSUE THREAD

**Issue by fleza** [bcbio/bcbio-nextgen#3041]
Hi, I ran bcbio_nextgen.py upgrade command to install tools this way:

```
mkdir -p /tmp/bcbio-nextgen-install && cd /tmp/bcbio-nextgen-install && \
    /usr/local/share/bcbio-nextgen/anaconda/bin/bcbio_nextgen.py upgrade -u stable --isolate \
    --tooldir=/usr/local --tools --toolconf /tool.yaml && \
    cd /usr/local && \
    /usr/local/share/bcbio-nextgen/anaconda/bin/conda clean --yes --tarballs --source-cache && \
    rm -rf /usr/local/share/bcbio-nextgen/anaconda/pkgs/scipy-0.19.1-np113py27_nomkl_0 && \
    rm -rf /usr/local/share/bcbio-nextgen/anaconda/zulu*.tar.gz && \
    rm -rf /tmp/bcbio-nextgen-install
```

This is the tool.yaml file content:
```
bio_nextgen:
- atropos;env=python3
- bedtools=2.27.1
- fastqc=0.11.7=5
- gffread
- goleft
- hisat2
- hts-nim-tools
- kallisto>=0.43.1
- mosdepth
- matplotlib<3.0.0,>=2.1.1
- multiqc
- multiqc-bcbio
- picard
- pizzly
- pysam>=0.13.0
- pythonpy
- qsignature
- qualimap
- r-base
- r-wasabi
- r=3.5.1
- sailfish
- salmon
- sambamba
- samtools
- seqtk
- star
- subread
- tophat;env=python2
- xorg-libxt
channels:
- conda-forge
- bioconda
minimal:
- awscli
- bzip2
- ncurses
- nomkl
- readline
- ucsc-fatotwobit
```
But I got this dependency error:

```
failed with initial frozen solve. Retrying with flexible solve.

Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (conda):

  - mamba -> conda[version='4.6.*|4.6.*|4.7.*|>=4.7.12,<4.8']

The following specifications were found to be incompatible with each other:



Package conda-package-handling conflicts for:
mamba -> conda=4.6 -> conda-package-handling[version='>=1.3.0']
conda[version='>=4.8.0'] -> conda-package-handling[version='>=1.3.0']
Package conda conflicts for:
conda[version='>=4.8.0']

Upgrading bcbio
Upgrade of bcbio-nextgen code complete.
Upgrading third party tools to latest versions
Reading packages from /bcbio-rnaseq.yaml
Creating conda environment: python3
Creating conda environment: python2
Checking for problematic or migrated packages in default environment
Initalling initial set of packages for default environment with mamba
Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 90, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 516, in upgrade_thirdparty_tools
    cbl_conda.install_in(_get_conda_bin(), args.tooldir, package_yaml)
  File "/tmp/bcbio-nextgen-install/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 70, in install_in
    _initial_base_install(conda_bin, [ps for (n, ps) in _split_by_condaenv(packages) if n is None][0], check_channels)
  File "/tmp/bcbio-nextgen-install/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 121, in _initial_base_install
    "{py_version} mamba".format(**locals()), shell=True)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/local/share/bcbio-nextgen/anaconda/bin/conda install -y  -c conda-forge -c bioconda python=3.6 mamba' returned non-zero exit status 1.
```

**Comment by roryk** [comment]
Hi Fleza,

What's your use-case for using toolconf? Could you just use the tools that bcbio installs?

**Comment by fleza** [comment]
I am using these docker images to build a bcbio-rnaseq version [bcbio automated Docker builds](https://github.com/bcbio/bcbio_docker).

**Comment by roryk** [comment]
Oh, gotcha. Do you need me to update the docker to 1.1.9? I can do that so you don't have to build your own if that would help.

**Comment by fleza** [comment]
I am building my own image with base image ubuntu 18.04 and using your scripts, it can help me, thanks

**Comment by roryk** [comment]
Gotcha, we see the same issue when we try to bump:

https://travis-ci.org/bcbio/bcbio_docker/jobs/624699234

**Comment by fleza** [comment]
Hi, do you know how to solve this?

**Comment by hujingchu** [comment]
Hi, I got the same problem, has the problem got fixed?

**Comment by narotha** [comment]
Hi, I also have the same problem

I ran this installation: 
```
python bcbio_nextgen_install.py ~/usr/local/share/bcbio --tooldir=~/usr/local 
--genomes hg38 --datatarget rnaseq --aligners star
```

And I got this error message: 

```
UnsatisfiableError: The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (conda):

  - mamba -> conda[version='4.6.*|4.6.*|4.7.*|>=4.7.12,<4.8']

The following specifications were found to be incompatible with each other:

Package conda-package-handling conflicts for:
conda[version='>=4.8.0'] -> conda-package-handling[version='>=1.3.0']
mamba -> conda[version='>=4.7.12,<4.8'] -> conda-package-handling[version='>=1.3.0']
Package conda conflicts for:
conda[version='>=4.8.0']
```

Do you know how to solve this?

**Comment by chapmanb** [comment]
Thanks for all the reports and sorry for the issue. It appears as if mamba is currently pinned to only support conda 4.8 so causes these package incompatibilities with the latest version. For now, I disabled mamba to avoid the error. If you remove any cached cloudbiolinux installs (`rm -rf tmpbcbio-install`) and re-run it should hopefully avoid mamba and install cleanly.

**Comment by naumenko-sa** [comment]
Hello!

Re-opening this issue, as without mamba fresh installation takes ~24h which is a bit long especially for AWS installs where you pay $/sec. mamba developers are about to lift up the <conda4.8 limitation and then we will plug mamba back and test installation time again.

Thanks @chapmanb for the direction on how to resolve long installation times!

SN
