### ISSUE TITLE
peaksettings not defined

### ISSUE THREAD

**Issue by apastore** [bcbio/bcbio-nextgen#3043]
when I run chip-seq without a specific antibody defined, I encounter the following error.
Thanks!

[2019-12-14T01: 11Z] lt03: Resource requests: macs2; memory: 1.00; cores: 1
[2019-12-14T01:11Z] lt03: Configuring 2 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
2019-12-13 20:11:58.440 [IPClusterStart] Using existing profile dir: '/lila/data/abdelwao-lab/pastorea/Project/aao/GSE36749/GSE36749/work/log/ipython'
2019-12-13 20:11:58.440 [IPClusterStart] Searching path ['/lila/data/abdelwao-lab/pastorea/Project/aao/GSE36749/GSE36749/work', '/lila/data/abdelwao-lab/pastorea/Project/aao/GSE36749/GSE36749/work/log/ipython', '/home/pastore/data/bcbio/anaconda/etc/ipython', '/usr/local/etc/ipython', '/etc/ipython'] for config files
2019-12-13 20:11:58.440 [IPClusterStart] Attempting to load config file: ipython_config.py
2019-12-13 20:11:58.441 [IPClusterStart] Looking for ipython_config in /etc/ipython
2019-12-13 20:11:58.441 [IPClusterStart] Looking for ipython_config in /usr/local/etc/ipython
2019-12-13 20:11:58.441 [IPClusterStart] Looking for ipython_config in /home/pastore/data/bcbio/anaconda/etc/ipython
2019-12-13 20:11:58.441 [IPClusterStart] Looking for ipython_config in /lila/data/abdelwao-lab/pastorea/Project/aao/GSE36749/GSE36749/work/log/ipython
2019-12-13 20:11:58.441 [IPClusterStart] Loaded config file: /lila/data/abdelwao-lab/pastorea/Project/aao/GSE36749/GSE36749/work/log/ipython/ipython_config.py
2019-12-13 20:11:58.441 [IPClusterStart] Looking for ipython_config in /lila/data/abdelwao-lab/pastorea/Project/aao/GSE36749/GSE36749/work
2019-12-13 20:11:58.442 [IPClusterStart] Attempting to load config file: ipcluster_54937639_def7_4fc1_901f_ecf5773fe88d_config.py
2019-12-13 20:11:58.442 [IPClusterStart] Looking for ipcontroller_config in /etc/ipython
2019-12-13 20:11:58.442 [IPClusterStart] Looking for ipcontroller_config in /usr/local/etc/ipython
2019-12-13 20:11:58.442 [IPClusterStart] Looking for ipcontroller_config in /home/pastore/data/bcbio/anaconda/etc/ipython
2019-12-13 20:11:58.442 [IPClusterStart] Looking for ipcontroller_config in /lila/data/abdelwao-lab/pastorea/Project/aao/GSE36749/GSE36749/work/log/ipython
2019-12-13 20:11:58.443 [IPClusterStart] Loaded config file: /lila/data/abdelwao-lab/pastorea/Project/aao/GSE36749/GSE36749/work/log/ipython/ipcontroller_config.py
2019-12-13 20:11:58.443 [IPClusterStart] Looking for ipcontroller_config in /lila/data/abdelwao-lab/pastorea/Project/aao/GSE36749/GSE36749/work
2019-12-13 20:11:58.443 [IPClusterStart] Attempting to load config file: ipcluster_54937639_def7_4fc1_901f_ecf5773fe88d_config.py
2019-12-13 20:11:58.443 [IPClusterStart] Looking for ipengine_config in /etc/ipython
2019-12-13 20:11:58.444 [IPClusterStart] Looking for ipengine_config in /usr/local/etc/ipython
2019-12-13 20:11:58.444 [IPClusterStart] Looking for ipengine_config in /home/pastore/data/bcbio/anaconda/etc/ipython
2019-12-13 20:11:58.444 [IPClusterStart] Looking for ipengine_config in /lila/data/abdelwao-lab/pastorea/Project/aao/GSE36749/GSE36749/work/log/ipython
2019-12-13 20:11:58.444 [IPClusterStart] Loaded config file: /lila/data/abdelwao-lab/pastorea/Project/aao/GSE36749/GSE36749/work/log/ipython/ipengine_config.py
2019-12-13 20:11:58.444 [IPClusterStart] Looking for ipengine_config in /lila/data/abdelwao-lab/pastorea/Project/aao/GSE36749/GSE36749/work
2019-12-13 20:11:58.445 [IPClusterStart] Attempting to load config file: ipcluster_54937639_def7_4fc1_901f_ecf5773fe88d_config.py
2019-12-13 20:11:58.445 [IPClusterStart] Looking for ipcluster_config in /etc/ipython
2019-12-13 20:11:58.445 [IPClusterStart] Looking for ipcluster_config in /usr/local/etc/ipython
2019-12-13 20:11:58.445 [IPClusterStart] Looking for ipcluster_config in /home/pastore/data/bcbio/anaconda/etc/ipython
2019-12-13 20:11:58.445 [IPClusterStart] Looking for ipcluster_config in /lila/data/abdelwao-lab/pastorea/Project/aao/GSE36749/GSE36749/work/log/ipython
2019-12-13 20:11:58.445 [IPClusterStart] Loaded config file: /lila/data/abdelwao-lab/pastorea/Project/aao/GSE36749/GSE36749/work/log/ipython/ipcluster_config.py
2019-12-13 20:11:58.445 [IPClusterStart] Looking for ipcluster_config in /lila/data/abdelwao-lab/pastorea/Project/aao/GSE36749/GSE36749/work
[2019-12-14T01:12Z] lt03: Timing: peakcalling
[2019-12-14T01:12Z] lt03: Skipping peak calling. No input sample for MDAH087_IgG_ChIPSeq_GSM900167
[2019-12-14T01:12Z] lt03: ipython: peakcalling
[2019-12-14T01:13Z] ls08: Unexpected error
Traceback (most recent call last):
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 54, in _setup_logging
    yield config
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 145, in peakcalling
    return ipython.zip_args(apply(peaks.calling, *args))
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 82, in apply
    return object(*args, **kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/chipseq/peaks.py", line 55, in calling
    dd.get_chip_method(data), data["resources"], data)
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/chipseq/macs2.py", line 40, in run
    cmd += peaksettings
UnboundLocalError: local variable 'peaksettings' referenced before assignment
[2019-12-14T01:13Z] ls08: Unexpected error
Traceback (most recent call last):
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 54, in _setup_logging
    yield config
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 145, in peakcalling
    return ipython.zip_args(apply(peaks.calling, *args))
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 82, in apply
    return object(*args, **kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/chipseq/peaks.py", line 55, in calling
    dd.get_chip_method(data), data["resources"], data)
  File "/home/pastore/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/chipseq/macs2.py", line 40, in run
    cmd += peaksettings
UnboundLocalError: local variable 'peaksettings' referenced before assignment
[pastore@lilac GSE36749]$ bpeek 13469395

**Comment by naumenko-sa** [comment]
Hi @apastore !

Sorry about the issue!
Could you please provide your bcbio.yaml file?
Could you also try to run it without ipcluster, just as a multithreaded job, i.e. 
```
bcbio_nextgen.py ../config/bcbio.yaml -n 10
```
Sergey

**Comment by naumenko-sa** [comment]
Closing for now. Please re-open if you still see an issue there.
