### ISSUE TITLE
Mapping step failed

### ISSUE THREAD

**Issue by kokyriakidis** [bcbio/bcbio-nextgen#3044]
Hi @roryk 

I got the following error:
```
[2019-12-18T16:32Z] Aligning lane KONSTANTINOS with bwa aligner
[2019-12-18T16:32Z] multiprocessing: delayed_bam_merge
[2019-12-18T16:32Z] Timing: callable regions
[2019-12-18T16:32Z] multiprocessing: prep_samples
[2019-12-18T16:32Z] multiprocessing: postprocess_alignment
[2019-12-18T16:32Z] Calculating coverage: KONSTANTINOS variant_regions
[2019-12-18T16:32Z] fatal.nim(39)            sysFatal
[2019-12-18T16:32Z] Error: unhandled exception: mosdepth.nim(292, 20) `(rec.start <= mate.stop)` A00910:57:HWLFCDSXX:2:1275:24695:34867	83	chr1	212419319	5S48M3D45M	=	2123947	-342	TGGTGGTAGTTAGGGTCACGGCTGTAGTTAGGGTCATGGTGGTAGTTAGGGTCGTGGTGGTTAGGTTCATGGTGGTAGTTAGGGTCACGGCTGTAGTT	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NM:i:8	MD:Z:26C4C6G9^ACG12G6C25	AS:i:59	XS:i:49	RG:Z:KONSTANTINOS	SA:Z:chrUn_JTFH01000929v1_decoy,384,+,45M3D53M,0,8;	pa:f:0.922	MQ:i:0	ms:i:3554	mc:i:2123939	MC:Z:8S83M11S
[2019-12-18T16:32Z] A00910:57:HWLFCDSXX:2:1275:24695:34867	163	chr1	2122061	7	26S64M12S	=	2122061	64	TGGTGGTAGTTAGGGTCACGGCTGTAGTTAGGGTCATGGTGGTAGTTAGGGTCGTGGTGGTTAGGTTCATGGTGGTAGTTAGGGTCACGGCTGTAGTTATGT	FFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFF,FFFFF:FFF::FFFFFFFF:FFFFFFF,,FFFFFF,FFF	NM:i:3	MD:Z:10C28G10G13	AS:i:49	XS:i:44	RG:Z:KONSTANTINOS	SA:Z:chrUn_JTFH01000929v1_decoy,23,-,3S42M3D57M,0,8;	pa:f:0.754	MQ:i:0	ms:i:3614	mc:i:2122132	MC:Z:26S64M8S [AssertionError]
[2019-12-18T16:32Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; export MOSDEPTH_Q0=NO_COVERAGE && export MOSDEPTH_Q1=LOW_COVERAGE && export MOSDEPTH_Q2=CALLABLE && mosdepth -t 19 -F 1804 -Q 1 --no-per-base --by /media/kokyriakidis/REDPRO/work/coverage/KONSTANTINOS/target-genome.bed --quantize 0:1:4: /media/kokyriakidis/REDPRO/work/bcbiotx/tmprpr0rwyo/KONSTANTINOS-variant_regions /media/kokyriakidis/REDPRO/work/align/KONSTANTINOS/KONSTANTINOS-sort.bam 
fatal.nim(39)            sysFatal
Error: unhandled exception: mosdepth.nim(292, 20) `(rec.start <= mate.stop)` A00910:57:HWLFCDSXX:2:1275:24695:34867	83	chr1	2124193	19	5S48M3D45M	=	2123947	-342	TGGTGGTAGTTAGGGTCACGGCTGTAGTTAGGGTCATGGTGGTAGTTAGGGTCGTGGTGGTTAGGTTCATGGTGGTAGTTAGGGTCACGGCTGTAGTT	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NM:i:8	MD:Z:26C4C6G9^ACG12G6C25	AS:i:59	XS:i:49	RG:Z:KONSTANTINOS	SA:Z:chrUn_JTFH01000929v1_decoy,384,+,45M3D53M,0,8;	pa:f:0.922	MQ:i:0	ms:i:3554	mc:i:2123939	MC:Z:8S83M11S
A00910:57:HWLFCDSXX:2:1275:24695:34867	163	chr1	2122061	7	26S64M12S	=	2122061	64	TGGTGGTAGTTAGGGTCACGGCTGTAGTTAGGGTCATGGTGGTAGTTAGGGTCGTGGTGGTTAGGTTCATGGTGGTAGTTAGGGTCACGGCTGTAGTTATGT	FFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFF,FFFFF:FFF::FFFFFFFF:FFFFFFF,,FFFFFF,FFF	NM:i:3	MD:Z:10C28G10G13	AS:i:49	XS:i:44	RG:Z:KONSTANTINOS	SA:Z:chrUn_JTFH01000929v1_decoy,23,-,3S42M3D57M,0,8;	pa:f:0.754	MQ:i:0	ms:i:3614	mc:i:2122132	MC:Z:26S64M8S [AssertionError]
' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 138, in variant2pipeline
    samples = run_parallel("postprocess_alignment", samples)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1003, in __call__
    if self.dispatch_one_batch(iterator):
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 834, in dispatch_one_batch
    self._dispatch(tasks)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 753, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 201, in apply_async
    result = ImmediateResult(func)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 582, in __init__
    self.results = batch()
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 153, in postprocess_alignment
    return sample.postprocess_alignment(*args)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sample.py", line 256, in postprocess_alignment
    covinfo = callable.sample_callable_bed(bam_file_ready, ref_file, data)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/bam/callable.py", line 45, in sample_callable_bed
    callable_bed, depth_files = coverage.calculate(bam_file, data, sv_bed)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/coverage.py", line 100, in calculate
    per_base=per_base)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/coverage.py", line 238, in run_mosdepth
    do.run(cmd.format(**locals()), message.format(**locals()))
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; export MOSDEPTH_Q0=NO_COVERAGE && export MOSDEPTH_Q1=LOW_COVERAGE && export MOSDEPTH_Q2=CALLABLE && mosdepth -t 19 -F 1804 -Q 1 --no-per-base --by /media/kokyriakidis/REDPRO/work/coverage/KONSTANTINOS/target-genome.bed --quantize 0:1:4: /media/kokyriakidis/REDPRO/work/bcbiotx/tmprpr0rwyo/KONSTANTINOS-variant_regions /media/kokyriakidis/REDPRO/work/align/KONSTANTINOS/KONSTANTINOS-sort.bam 
fatal.nim(39)            sysFatal
Error: unhandled exception: mosdepth.nim(292, 20) `(rec.start <= mate.stop)` A00910:57:HWLFCDSXX:2:1275:24695:34867	83	chr1	2124193	19	5S48M3D45M	=	2123947	-342	TGGTGGTAGTTAGGGTCACGGCTGTAGTTAGGGTCATGGTGGTAGTTAGGGTCGTGGTGGTTAGGTTCATGGTGGTAGTTAGGGTCACGGCTGTAGTT	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NM:i:8	MD:Z:26C4C6G9^ACG12G6C25	AS:i:59	XS:i:49	RG:Z:KONSTANTINOS	SA:Z:chrUn_JTFH01000929v1_decoy,384,+,45M3D53M,0,8;	pa:f:0.922	MQ:i:0	ms:i:3554	mc:i:2123939	MC:Z:8S83M11S
A00910:57:HWLFCDSXX:2:1275:24695:34867	163	chr1	2122061	7	26S64M12S	=	2122061	64	TGGTGGTAGTTAGGGTCACGGCTGTAGTTAGGGTCATGGTGGTAGTTAGGGTCGTGGTGGTTAGGTTCATGGTGGTAGTTAGGGTCACGGCTGTAGTTATGT	FFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFF,FFFFF:FFF::FFFFFFFF:FFFFFFF,,FFFFFF,FFF	NM:i:3	MD:Z:10C28G10G13	AS:i:49	XS:i:44	RG:Z:KONSTANTINOS	SA:Z:chrUn_JTFH01000929v1_decoy,23,-,3S42M3D57M,0,8;	pa:f:0.754	MQ:i:0	ms:i:3614	mc:i:2122132	MC:Z:26S64M8S [AssertionError]
' returned non-zero exit status 1.
```

My template is
```
upload:
  dir: ../final
details:
  - files:
    - ../input/KONSTANTINOS_1.fastq.gz
    - ../input/KONSTANTINOS_2.fastq.gz
    description: KONSTANTINOS
    metadata:
      sex: male
    analysis: variant2
    genome_build: hg38
    algorithm:
      trim_reads: atropos
      adapters: [polyx]
      aligner: bwa
      realign: false
      recalibrate: false
      mark_duplicates: true
      maxcov_downsample: false
      tools_on: [noalt_calling]
      variantcaller:
      - gatk-haplotype
      effects: none
```

My fastq files are from a novaseq 6000 run and they are 144GB combined.

I am using bcbio version 1.2.0a

**Comment by kokyriakidis** [comment]
It was a mosdepth error. Brentp fixed it.

https://github.com/brentp/mosdepth/issues/99

**Comment by naumenko-sa** [comment]
thanks for pushing this issue forward!
will keep open for now as we are on mosdepth 0.2.6.
SN

**Comment by naumenko-sa** [comment]
I'm still facing some issues when updating mosdepth.
I've updated bioconda recipe to fetch mosdepth 0.2.9
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/mosdepth/meta.yaml

```bcbio_nextgen.py upgrade -u development --tools``` won't update mosdepth.

Trying 
```
conda install --force-reinstall -c bioconda mosdepth=0.2.9
```
result:
```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package zlib conflicts for:
python=3.6 -> zlib[version='>=1.2.11,<1.3.0a0']
mosdepth=0.2.9 -> htslib[version='>=1.10.2,<1.11.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']
```

zlib and htslib versions:
```
zlib                      1.2.11               h7b6447c_3 
htslib                    1.9                  ha228f0b_7    bioconda
```

It seems htslib is old, there is a new one:
```
conda search -c bioconda htslib
htslib                        1.10.2      h78d89cc_0  bioconda
```

Trying to update htslib:
```
conda install --force-reinstall -c bioconda htslib=1.10.2
Package openssl conflicts for:
htslib=1.10.2 -> libcurl[version='>=7.64.1,<8.0a0'] -> openssl[version='>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a']
htslib=1.10.2 -> openssl[version='>=1.1.1a,<1.1.2a']

Package _libgcc_mutex conflicts for:
htslib=1.10.2 -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]
python=3.6 -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]

Package libgcc-ng conflicts for:
htslib=1.10.2 -> libgcc-ng[version='>=7.3.0']
htslib=1.10.2 -> xz[version='>=5.2.4,<5.3.0a0'] -> libgcc-ng[version='>=7.2.0']
```

It seems we are going doing the rabbit hole of package dependencies.  
I'd appreciate any ideas to resolve this update.

SN

**Comment by roryk** [comment]
Hi Sergey,

I think we're going to have to look at all the packages that bcbio installs that use htslib and increment the build number so they get built with the new htslib version. We should ask the bioconda folks first though.

**Comment by naumenko-sa** [comment]
Thanks, Rory,
I see, htslib got updated to 1.10.2 ~3month ago, so the build numbers in the dependent packages have not been updated yet.
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/htslib/meta.yaml

When ppl do fresh AWS bcbio installations, they will get new htslib, right, 
and all new builds, and if there are any bugs, it would be hard to reproduce in the stalled
installations with htslib 1.9, so that could be a reason to jump through the recipes.

If that makes sense, I could ping bioconda and go through the list:

arriba-1.1.0-h10824c4_1
ataqv-1.1.1-py36h568a559_0
bcftools-1.9-h68d8f2e_9
cancerit-allelecount-4.0.2-ha228f0b_1
cyvcf2-0.11.6-py36hce88a48_0
delly-0.8.2-h43566fd_1
duphold-0.2.1-hfb13731_0
ensembl-vep-99.2-pl526hecc5488_0
freebayes-1.1.0.46-py36h82df9c4_5
hts-nim-tools-0.1.5-he527e40_2
lofreq-2.1.4-py36hc3dfafe_0
octopus-0.5.2b-hd4b4d59_2
pindel-0.2.5b9-he527e40_3
sambamba-0.7.1-h148d290_1
samtools-1.9-h10a08f8_12
scalpel-0.5.4-h7376a40_2
verifybamid2-1.0.6-he56e5df_0

SN

**Comment by roryk** [comment]
Thanks everyone, sorry for being slow fixing this-- the issue was the bioconda recipe for the newer versions of mosdepth has a `conda_build_config.yaml` file in it, which specifies it needs htslib1.10. bioconda is standardized on htslib1.9 at the moment, so this causes conflicts with other pacakges and forces us to install an old version of mosdepth which has this bug. I created an htslib1.10 environment where packages needing htslib1.10 can live, and now we get the newer version of mosdepth with this fix. If you do a `--tools` update you should pull in  the fixed version.

**Comment by naumenko-sa** [comment]
thanks, the update work fine. mosdepth 0.2.9!
