### ISSUE TITLE
subprocess.CalledProcessError: Command 'set -o pipefail; export LC_ALL=en_US.utf8 && export LANG=en_US.utf8

### ISSUE THREAD

**Issue by biosurgeon** [bcbio/bcbio-nextgen#3049]
Hi. I'm in trouble to run bcbio_nextgen. The subjects have multiple tumors with one paired normal sample. It seemed that ensemble calling was completed, but there are some problems from gemini? (I'm not sure because there are multiple files in  ../work/gemini/ folders including ensemble vcfs and conf/lua files) or peddy?.   I've tried update gemini and other tools and data, but same error occured. I've searched to find similar error (because I solved some problems before), but I have no idea what is wrong....  Could you help me?   the error was like below. Thank you!!

========================================
[2019-12-27T20:08Z] multiprocessing: combine_calls
[2019-12-27T20:08Z] Ensemble consensus calls for GCMET_001_tu1: vardict,strelka2,mutect2
[2019-12-27T20:08Z] Ensemble consensus calls for GCMET_001_tu2: vardict,strelka2,mutect2
[2019-12-27T20:08Z] Ensemble consensus calls for GCMET_002_tu1: vardict,strelka2,mutect2
[2019-12-27T20:08Z] Ensemble consensus calls for GCMET_002_tu2: vardict,strelka2,mutect2
[2019-12-27T20:08Z] Ensemble consensus calls for GCMET_002_tu3: vardict,strelka2,mutect2
[2019-12-27T20:08Z] Ensemble consensus calls for GCMET_002_tu4: vardict,strelka2,mutect2
[2019-12-27T20:08Z] Ensemble consensus calls for GCMET_002_tu5: vardict,strelka2,mutect2
[2019-12-27T20:08Z] Ensemble consensus calls for GCMET_002_tu6: vardict,strelka2,mutect2
[2019-12-27T20:08Z] Ensemble consensus calls for GCMET_003_tu1: vardict,strelka2,mutect2
[2019-12-27T20:08Z] Ensemble consensus calls for GCMET_003_tu2: vardict,strelka2,mutect2
[2019-12-27T20:08Z] Ensemble consensus calls for GCMET_003_tu3: vardict,strelka2,mutect2
[2019-12-27T20:08Z] Ensemble consensus calls for GCMET_003_tu4: vardict,strelka2,mutect2
[2019-12-27T20:08Z] Ensemble consensus calls for GCMET_003_tu5: vardict,strelka2,mutect2
[2019-12-27T20:08Z] Ensemble consensus calls for GCMET_001_CN_N-germline: freebayes,gatk-haplotype,strelka2
[2019-12-27T20:08Z] Ensemble consensus calls for GCMET_002_CN_N-germline: freebayes,gatk-haplotype,strelka2
[2019-12-27T20:08Z] Ensemble consensus calls for GCMET_003_CN_N-germline: freebayes,gatk-haplotype,strelka2
[2019-12-27T20:08Z] Timing: validation summary
[2019-12-27T20:08Z] Timing: structural variation
[2019-12-27T20:08Z] multiprocessing: detect_sv
[2019-12-27T20:08Z] multiprocessing: finalize_sv
[2019-12-27T20:08Z] Timing: structural variation
[2019-12-27T20:08Z] multiprocessing: detect_sv
[2019-12-27T20:08Z] multiprocessing: finalize_sv
[2019-12-27T20:08Z] Timing: structural variation ensemble
[2019-12-27T20:08Z] Timing: structural variation validation
[2019-12-27T20:08Z] multiprocessing: validate_sv
[2019-12-27T20:08Z] Timing: heterogeneity
[2019-12-27T20:08Z] Timing: population database
[2019-12-27T20:08Z] multiprocessing: prep_gemini_db
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_001_CN_liver_tu
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_001_CN_liver_tu
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_001_CN_liver_tu
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_001_CN_liver_tu
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_001_CN_T_tu
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_001_CN_T_tu
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_001_CN_T_tu
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_001_CN_T_tu
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_002_CN_LND1_tu
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_002_CN_LND1_tu
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_002_CN_LND1_tu
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_002_CN_LND1_tu
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_002_CN_T1_tu
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_002_CN_T1_tu
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_002_CN_T1_tu
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_002_CN_T1_tu
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_002_CN_T2_tu
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_002_CN_T2_tu
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_002_CN_T2_tu
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_002_CN_T2_tu
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_002_CT1_liver1_tu
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_002_CT1_liver1_tu
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_002_CT1_liver1_tu
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_002_CT1_liver1_tu
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_002_CT1_liver2_tu
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_002_CT1_liver2_tu
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_002_CT1_liver2_tu
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_002_CT1_liver2_tu
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_002_CT1_liver3_tu
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_002_CT1_liver3_tu
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_002_CT1_liver3_tu
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_002_CT1_liver3_tu
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_003_CN_LN4_tu
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_003_CN_LN4_tu
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_003_CN_LN4_tu
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_003_CN_LN4_tu
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_003_CN_LN6_tu
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_003_CN_LN6_tu
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_003_CN_LN6_tu
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_003_CN_LN6_tu
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_003_CN_T_tu
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_003_CN_T_tu
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_003_CN_T_tu
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_003_CN_T_tu
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_003_CT1_liver1_tu
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_003_CT1_liver1_tu
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_003_CT1_liver1_tu
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_003_CT1_liver1_tu
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_003_CT1_liver2_tu
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_003_CT1_liver2_tu
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_003_CT1_liver2_tu
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_003_CT1_liver2_tu
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_001_CN_N
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_001_CN_N
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_001_CN_N
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_001_CN_N
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_002_CN_N
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_002_CN_N
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_002_CN_N
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_002_CN_N
[2019-12-27T20:08Z] Not running gemini, no samples with variants found: GCMET_003_CN_N
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_003_CN_N
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_003_CN_N
[2019-12-27T20:08Z] Not running gemini, not configured in tools_on: GCMET_003_CN_N
[2019-12-27T20:08Z] Timing: peddy check
[2019-12-27T20:08Z] multiprocessing: run_peddy
[2019-12-27T20:08Z] Running peddy on /scratch/laki98/GCMET/work/qc/GCMET_001_tu1/peddy/GCMET_001_tu1-effects-annotated-germline.vcf.gz against /scratch/laki98/GCMET/work/qc/GCMET_001_tu1/peddy/GCMET_001_tu1-effects-annotated-germline.ped.
[2019-12-27T20:08Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/laki98/nextgen/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/laki98/nextgen/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; export LC_ALL=en_US.utf8 && export LANG=en_US.utf8 &&  /home/laki98/nextgen/bin/peddy -p 1  --plot --prefix /scratch/laki98/GCMET/work/bcbiotx/tmpwdha8ail/GCMET_001_tu1 /scratch/laki98/GCMET/work/qc/GCMET_001_tu1/peddy/GCMET_001_tu1-effects-annotated-germline.vcf.gz /scratch/laki98/GCMET/work/qc/GCMET_001_tu1/peddy/GCMET_001_tu1-effects-annotated-germline.ped 2> /scratch/laki98/GCMET/work/bcbiotx/tmpwdha8ail/run-stderr.log
' returned non-zero exit status 1.
[2019-12-27T20:08Z] Traceback (most recent call last):
  File "/home/laki98/nextgen/bin/peddy", line 11, in <module>
    load_entry_point('peddy==0.4.3', 'console_scripts', 'peddy')()
  File "/home/laki98/nextgen/anaconda/envs/python2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/laki98/nextgen/anaconda/envs/python2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/laki98/nextgen/anaconda/envs/python2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/laki98/nextgen/anaconda/envs/python2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/laki98/nextgen/anaconda/envs/python2/lib/python2.7/site-packages/peddy/__main__.py", line 3, in <module>
    from .cli import peddy as cli
  File "/home/laki98/nextgen/anaconda/envs/python2/lib/python2.7/site-packages/peddy/cli.py", line 17, in <module>
    from cyvcf2 import VCF
  File "/home/laki98/nextgen/anaconda/envs/python2/lib/python2.7/site-packages/cyvcf2/__init__.py", line 1, in <module>
    from .cyvcf2 import (VCF, Variant, Writer, r_ as r_unphased, par_relatedness,
  File "cyvcf2/cyvcf2.pyx", line 19, in init cyvcf2.cyvcf2
  File "__init__.pxd", line 1038, in numpy.import_array
ImportError: numpy.core.multiarray failed to import

Traceback (most recent call last):
  File "/home/laki98/nextgen/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/home/laki98/nextgen/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/laki98/nextgen/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/home/laki98/nextgen/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/laki98/nextgen/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 190, in variant2pipeline
    samples = peddy.run_peddy_parallel(samples, run_parallel)
  File "/home/laki98/nextgen/anaconda/lib/python3.6/site-packages/bcbio/variation/peddy.py", line 32, in run_peddy_parallel
    samples = parallel_fn("run_peddy", [[x] for x in to_run])
  File "/home/laki98/nextgen/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/laki98/nextgen/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/home/laki98/nextgen/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1003, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/laki98/nextgen/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 834, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/laki98/nextgen/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 753, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/laki98/nextgen/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 201, in apply_async
    result = ImmediateResult(func)
  File "/home/laki98/nextgen/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 582, in __init__
    self.results = batch()
  File "/home/laki98/nextgen/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/home/laki98/nextgen/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/laki98/nextgen/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/home/laki98/nextgen/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 24, in run_peddy
    return peddy.run_peddy(*args)
  File "/home/laki98/nextgen/anaconda/lib/python3.6/site-packages/bcbio/variation/peddy.py", line 103, in run_peddy
    do.run(cmd.format(**locals()), message.format(**locals()))
  File "/home/laki98/nextgen/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/laki98/nextgen/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; export LC_ALL=en_US.utf8 && export LANG=en_US.utf8 &&  /home/laki98/nextgen/bin/peddy -p 1  --plot --prefix /scratch/laki98/GCMET/work/bcbiotx/tmpwdha8ail/GCMET_001_tu1 /scratch/laki98/GCMET/work/qc/GCMET_001_tu1/peddy/GCMET_001_tu1-effects-annotated-germline.vcf.gz /scratch/laki98/GCMET/work/qc/GCMET_001_tu1/peddy/GCMET_001_tu1-effects-annotated-germline.ped 2> /scratch/laki98/GCMET/work/bcbiotx/tmpwdha8ail/run-stderr.log
' returned non-zero exit status 1.

**Comment by naumenko-sa** [comment]
Hi @biosurgeon!

Sorry about the issues! 
Could you please post your yaml config file?

Sergey

**Comment by biosurgeon** [comment]
Hi, @naumenko-sa 

could you check the below my yaml config file?
[GCMET_1to3.pdf](https://github.com/bcbio/bcbio-nextgen/files/4008781/GCMET_1to3.pdf)

Young

**Comment by biosurgeon** [comment]
Now I skip peddy and the process is on going well. (I just  move the peddy command file into somewhere..)
I think the system used numpy in phython3, not in python2, so it seemed the problem was due to python PATH... 
I tried to update numpy but numpy was installed in python3 only and I also moved the updated numpy folder into  python2, but there was another error, (ImportError: cannot import name _distributor_init)

Is there anyone who let me know how  I solve this problem?  Pipeline without peddy will be OK?

Thanks

**Comment by naumenko-sa** [comment]
Hi!

Sorry about the delay in responding!

Peddy is one of the quality control tools:
https://github.com/brentp/peddy 
So it is not affecting variant calling. However, peddy works ok in many other projects.

Gemini should not be a problem, as since v1.1.1 we are not creating gemini databases by default.

What version of bcbio are you using? In the last releases many python3/python2 bugs were fixed.  What is your output of: `bcbio_nextgen.py -v`

Sergey

**Comment by biosurgeon** [comment]
Hi, Sergey, 

Thanks for the reply.  

The version of bcbio is 1.2.0a.    
I updated bcbio (data and tools) several times, as I hoped it will solve the problem.

There are so many pythons in my system (in server), so I wonder it could be a reason...

Do you have any suggestion?

Thanks

Young

[laki98@master config]$ whereis python
python: /usr/bin/python2.7 /usr/bin/python2.7-config /usr/bin/python /usr/lib/python2.7 /usr/lib64/python2.7 /etc/python /usr/include/python2.7 /home/laki98/nextgen/anaconda/bin/python3.6-config /home/laki98/nextgen/anaconda/bin/python3.6m /home/laki98/nextgen/anaconda/bin/python /home/laki98/nextgen/anaconda/bin/python3.6 /home/laki98/nextgen/anaconda/bin/python3.6m-config / /usr/share/man/man1/python.1.gz

[laki98@master work]$ which python
~/nextgen/anaconda/bin/python

**Comment by naumenko-sa** [comment]
Hi Young!

I think it is typical to have many pythons on a system these days. If you have your `bcbio/tools/bin` and `bcbio/anaconda/bin` in the PATH you should be fine. Moreover, for the most tools bcbio unsets PATH and makes sure it calls the tool it has on board.

Looking at your yaml config, I see several potential issues:
- `batch: [GCMET_001_tu1, GCMET_001_tu2`. batch is used to specify a tumor-normal pair. I doubt if a sample could be in two batches at the same time, at least I have not tried it this way. You may try to decouple them and do 2 bcbio runs, or one bcbio run with 4 samples;
- min_allele_fraction: 0; it is in %. typically we set it to 5% or 1%. You'd want to filter out false positives. Without UMIs you cannot call these <1% VAF variants.
- strelka2 does not support python3, there might be issues: https://github.com/Illumina/strelka/issues/156. We have not used it much last time. You may try to remove strelka from your list.
- try to simplify your project; maybe for starters just use vardict for tumor and gatk-haplotype for germline, without ensemble calling. I see, you got this from the documentation, so it is our fault. There we should simplify it, too. Once you get your project finished, you may try a more complex setup. 

Sergey

**Comment by biosurgeon** [comment]
Hi Sergey, 

Thanks for the comments and suggestions. 
I attach the log file below. 
My PATH includes ../nextgen/anaconda/bin and ../nextgen/bin (you mean this? because there is no bcbio/tools/bin to me.. galaxy, genomes, anaconda folders are belong to ../nextgen/ )...

1. I ran bcbio with multiple samples (maximun 4 tumors with one paired normal, so max 4 tumors in one batch) in other environment and there was no error.. so I thought it works.. but I'll try to decouple them, and compare the outcome. (I'm not sure how long it will take, but I will post the result if possible)
2. For other three issues (min_allele_fraction, strelka2, simplifying), I'll try. 

Thank you so much!!

Young

[log_files.txt](https://github.com/bcbio/bcbio-nextgen/files/4038516/log_files.txt)

**Comment by naumenko-sa** [comment]
HI @biosurgeon !

Closing this issue for now. Please feel free to reopen if you are experiencing any issues!

SN
