### ISSUE TITLE
bcbio_setup_genome.py not working

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#3051]
Hello,

I'm having trouble running bcbio_setup_genome.py using syntax that has worked for me in the past. Have its settings been changed within the last months?

This is the command I'm running:

```
bcbio_setup_genome.py -c 14 -f sacCer3_BRF.fa -g sacCer3_bcbio_lncRNA_BRF.gtf -i bwa bowtie2 hisat2 star seq -n Scerevisiae -b sacCer3_BRF
```

This command has worked for me around 6 months ago for these FASTA and GTF files, when using a previous version of bcbio_nextgen. I'm now using the latest development version (`1.2.0a`).

The output seems to imply that my syntax is wrong, but I can't figure out why.

```
bcbio_setup_genome.py -c 14 -f sacCer3_BRF.fa -g sacCer3_bcbio_lncRNA_BRF.gtf -i bwa bowtie2 hisat2 star seq -n Scerevisiae -b sacCer3_BRF
usage: bcbio_setup_genome.py [-h] [-c CORES] -f FASTA [--gff3] [-g GTF] -n
                             NAME -b BUILD
                             [-i [{bwa,rtg,hisat2,bbmap,bowtie,bowtie2,minimap2,novoalign,twobit,bismark,snap,star,seq} [{bwa,rtg,hisat2,bbmap,bowtie,bowtie2,minimap2,novoalign,twobit,bismark,snap,star,seq} ...]]]
                             [--ercc] [--mirbase MIRBASE]
                             [--srna_gtf SRNA_GTF] --buildversion BUILDVERSION

Set up a custom genome for bcbio-nextgen. This will place the genome under
name/build in the genomes directory in your bcbio-nextgen installation.

optional arguments:
  -h, --help            show this help message and exit
  -c CORES, --cores CORES
                        number of cores to use
  -f FASTA, --fasta FASTA
                        FASTA file of the genome.
  --gff3                File is a GFF3 file.
  -g GTF, --gtf GTF     GTF file of the transcriptome
  -n NAME, --name NAME  Name of organism, for example Hsapiens.
  -b BUILD, --build BUILD
                        Build of genome, for example hg19.
  -i [{bwa,rtg,hisat2,bbmap,bowtie,bowtie2,minimap2,novoalign,twobit,bismark,snap,star,seq} [{bwa,rtg,hisat2,bbmap,bowtie,bowtie2,minimap2,novoalign,twobit,bismark,snap,star,seq} ...]], --indexes [{bwa,rtg,hisat2,bbmap,bowtie,bowtie2,minimap2,novoalign,twobit,bismark,snap,star,seq} [{bwa,rtg,hisat2,bbmap,bowtie,bowtie2,minimap2,novoalign,twobit,bismark,snap,star,seq} ...]]
                        Space separated list of indexes to make
  --ercc                Add ERCC spike-ins.
  --mirbase MIRBASE     species in mirbase for smallRNAseq data.
  --srna_gtf SRNA_GTF   gtf to use for smallRNAseq data.
  --buildversion BUILDVERSION
                        String describing build of genome used. Examples:
                        Ensembl_94, EnsemblMetazoa_94, Flybase_21, etc

Current genomes

index	hg38	/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/genomes/Hsapiens/hg38/seq/hg38.fa
```

**Comment by chapmanb** [comment]
Thanks for the question. The latest development version has a new option `--buildversion` which specifies the version of the GTF/GFF transcript file. If you add that to help define the transcript file you pass it should work cleanly with the rest of your syntax. Hope this helps get it running for you.

**Comment by amizeranschi** [comment]
@chapmanb thanks a lot for the reply. And have a happy New Year!

I've added `--buildversion None` to my previous command and the script worked for a while, but ended up crashing. I'm still not sure why, but I'm certain it used to work for me in the past, with these FASTA and GTF files.

If it helps, I found reference to a similar error in a discussion from 2015: https://github.com/bcbio/bcbio-nextgen/issues/935#issuecomment-122030422.


Here's the last part of the output:

```
Creating the seq index.
INFO	2020-01-01 19:22:07	CreateSequenceDictionary	

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    CreateSequenceDictionary -REFERENCE /export/home/ncit/external/a.mizeranschi/bcbio_nextgen/genomes/Scerevisiae/sacCer3_BRF/seq/sacCer3_BRF.fa -OUTPUT /export/home/ncit/external/a.mizeranschi/bcbio_nextgen/genomes/Scerevisiae/sacCer3_BRF/seq/sacCer3_BRF.dict
**********


19:22:08.314 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/share/picard-2.21.6-0/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Wed Jan 01 19:22:08 EET 2020] CreateSequenceDictionary OUTPUT=/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/genomes/Scerevisiae/sacCer3_BRF/seq/sacCer3_BRF.dict REFERENCE=/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/genomes/Scerevisiae/sacCer3_BRF/seq/sacCer3_BRF.fa    TRUNCATE_NAMES_AT_WHITESPACE=true NUM_SEQUENCES=2147483647 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Wed Jan 01 19:22:08 EET 2020] Executing as amizeranschi@asas on Linux 3.10.0-957.1.3.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_192-b01; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.21.6-SNAPSHOT
[Wed Jan 01 19:22:08 EET 2020] picard.sam.CreateSequenceDictionary done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=502792192
usage: prepare_tx_gff.py [-h] [-c CORES] [--gtf GTF] [--fasta FASTA]
                         [--genome-dir GENOME_DIR] [--tophat] [--kallisto]
                         organism org_build
prepare_tx_gff.py: error: unrecognized arguments: --buildversion sacCer3_BRF
Traceback (most recent call last):
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/tools/bin/bcbio_setup_genome.py", line 313, in <module>
    subprocess.check_call(cmd.format(**locals()), shell=True)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/bin/python /export/home/ncit/external/a.mizeranschi/yeast/GTF/cloudbiolinux/utils/prepare_tx_gff.py --buildversion None --cores 14 --genome-dir /export/home/ncit/external/a.mizeranschi/bcbio_nextgen/genomes --gtf /export/home/ncit/external/a.mizeranschi/bcbio_nextgen/genomes/Scerevisiae/sacCer3_BRF/rnaseq/ref-transcripts.gtf Scerevisiae sacCer3_BRF' returned non-zero exit status 2.
```

**Comment by chapmanb** [comment]
Happy New Year. Hope you're having a great holidays and getting some relaxation time. It looks like you have an older cached version of cloudbiolinux without the `--buildversion` command. If you remove the current one:
```
rm -rf /export/home/ncit/external/a.mizeranschi/yeast/GTF/cloudbiolinux
```
and re-run it should download the latest and hopefully work cleanly.

**Comment by amizeranschi** [comment]
Thanks a lot, that fixed got things working neatly.

Wishing you a relaxing holiday as well.
