### ISSUE TITLE
clouldbiolinux debugging to reduce bcbio installation time

### ISSUE THREAD

**Issue by naumenko-sa** [bcbio/bcbio-nextgen#3054]
Hello!

The time of a fresh installation of bcbio is currently an issue (~14h for bcbio code and tools, without data). After re-activating mamba it dropped from 24h to 14h. There is a potential to reduce it more (another 10h?) by using mamba in the second round of conda environment installations (for dp = DeepVariant which is currently stalls for long in solving).

To debug installation, I tried to run QuickStart example in https://github.com/chapmanb/cloudbiolinux:
```
mkdir /data/cloudbiolinux_test
cd /data/cloudbiolinux_test
git clone https://github.com/chapmanb/cloudbiolinux.git
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh -b -p /data/cloudbiolinux_test/cblenv
# make sure there is no other conda in the PATH
export PATH=/data/cloudbiolinux_test/cloudbiolinux:/data/cloudbiolinux_test/cblenv/bin:.:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
conda install -y -c bioconda -c conda-forge pip fabric pyyaml
cd cloudbiolinux
fab -f fabfile.py -H localhost install_biolinux:flavor=ngs_pipeline_minimal --set keep_isolated=true
```

The last command was not successful with:
```
Traceback (most recent call last):
  File "/data/cloudbiolinux_test/cblenv/bin/fab", line 10, in <module>
    sys.exit(program.run())
  File "/data/cloudbiolinux_test/cblenv/lib/python3.7/site-packages/invoke/program.py", line 373, in run
    self.parse_collection()
  File "/data/cloudbiolinux_test/cblenv/lib/python3.7/site-packages/invoke/program.py", line 465, in parse_collection
    self.load_collection()
  File "/data/cloudbiolinux_test/cblenv/lib/python3.7/site-packages/fabric/main.py", line 87, in load_collection
    super(Fab, self).load_collection()
  File "/data/cloudbiolinux_test/cblenv/lib/python3.7/site-packages/invoke/program.py", line 696, in load_collection
    module, parent = loader.load(coll_name)
  File "/data/cloudbiolinux_test/cblenv/lib/python3.7/site-packages/invoke/loader.py", line 76, in load
    module = imp.load_module(name, fd, path, desc)
  File "/data/cloudbiolinux_test/cblenv/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/data/cloudbiolinux_test/cblenv/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/cloudbiolinux_test/cloudbiolinux/fabfile.py", line 22, in <module>
    from fabric.api import *
ModuleNotFoundError: No module named 'fabric.api'
```

I tried using miniconda for python2, checked PATH and PYTHONPATH.
from python I can import fabric:
```
which python
/data/cloudbiolinux_test/cblenv/bin/python
python
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fabric
```
Is it python2/python3 issue, or maybe fabric1/fabric2?
http://www.fabfile.org/upgrading.html#upgrading

I'd be happy to contribute more in improving bcbio installation!

Sergey

**Comment by chapmanb** [comment]
Sergey -- the latest cloudbiolinux now includes mamba used in environments as well with the hope of gaining additional efficiency. I hope this will help with install and resolve speeds, and please let me know if anything doesn't work as expected. I've done some basic testing but could definitely use more eyes on it. Thanks so much for benchmarking this and the patience with install speeds.

With regards to cloudbiolinux debugging, we don't really make use of fabric anymore because of all the churn and those docs are out of date. The best way to test cloudbiolinux updates with bcbio is to link locally to your cloudbiolinux with changes and run upgrades using it:
```
mkdir -p tmpbcbio-install
ln -s /path/to/your/cloudbiolinux tmpbcbio-install
```
Sorry for all the trickiness with this and hope this helps gets things faster.

**Comment by naumenko-sa** [comment]
Thanks Brad!
