### ISSUE TITLE
bcbio fails when testing with large numbers of (small) samples

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#3063]
Hello,

I'm having some trouble getting bcbio to run with a large number of samples. My input data consists of very small FASTQ files containing only a few reads extracted from each of the 1000Genomes samples (2535 samples in total). My aim is to test if bcbio can cope with such a large number of samples at once without running into system limits due to e.g. too many open files or too many arguments etc.

I'm running the analysis on an SGE cluster using ipython parallel. The nodes have 32 cores and around 128 GB of memory each.

I've specified my resources as such:

```
---
details:
  - analysis: variant2
    genome_build: hg38
    resources:
      default:
        memory: 3G
        cores: 16
        jvm_opts: ["-Xms800m", "-Xmx3000m"]
      gatk-haplotype:
        options: ["--verbosity ERROR"]
      gatk:
        options: ["--verbosity ERROR"]
      picard:
        options: ["VERBOSITY=ERROR"]
    algorithm:
      aligner: bwa
      mark_duplicates: true
      recalibrate: false
      realign: false
      effects: false
      tools_off: [gemini, contamination, peddy, vqsr]
      tools_on: qualimap_full
      variantcaller: gatk-haplotype
      jointcaller: gatk-haplotype-joint
      ploidy: 2
      variant_regions: ../config/variant_regions.bed
```

However, it looks like the `jvm_opts` setting is not accounted for when running HaplotypeCaller. Instead, `-Xmx1g` seems to be hardcoded into the `--java-options` setting for gatk (see below). This results in memory issues (`Exception in thread "main" java.lang.OutOfMemoryError: Java heap space`).

@chapmanb why are the gatk java memory settings ending up like this? 

The full errors that I'm getting are listed below:

```
Using GATK jar /export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/share/gatk4-4.1.4.1-1/gatk-package-4.1.4.1-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xms681m -Xmx1g -XX:+UseSerialGC -Djava.io.tmpdir=/export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/work/bcbiotx/tmp6esj9s4r -jar /export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/share/gatk4-4.1.4.1-1/gatk-package-4.1.4.1-local.jar HaplotypeCaller -R /export/home/ncit/external/a.mizeranschi/bcbio_nextgen/genomes/Hsapiens/hg38/seq/hg38.fa --annotation MappingQualityRankSumTest --annotation MappingQualityZero --annotation QualByDepth --annotation ReadPosRankSumTest --annotation RMSMappingQuality --annotation BaseQualityRankSumTest --annotation FisherStrand --annotation MappingQuality --annotation DepthPerAlleleBySample --annotation Coverage -I /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/work/align/HG01518/HG01518-sort.bam -L /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/work/gatk-haplotype/chr1/HG01518-chr1_0_50142832-regions.bed --interval-set-rule INTERSECTION --annotation ClippingRankSumTest --annotation DepthPerSampleHC --native-pair-hmm-threads 1 --verbosity ERROR --emit-ref-confidence GVCF -GQB 10 -GQB 20 -GQB 30 -GQB 40 -GQB 60 -GQB 80 -ploidy 2 --output /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/work/bcbiotx/tmp6esj9s4r/HG01518-chr1_0_50142832.vcf.gz
' returned non-zero exit status 1.
[2020-01-20T08:09Z] haswell-wn35.grid.pub.ro: Unexpected error
Traceback (most recent call last):
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 54, in _setup_logging
    yield config
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 439, in variantcall_sample
    return ipython.zip_args(apply(genotype.variantcall_sample, *args))
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 82, in apply
    return object(*args, **kwargs)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/variation/genotype.py", line 377, in variantcall_sample
    out_file = caller_fn(align_bams, items, ref_file, assoc_files, region, out_file)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/variation/gatk.py", line 180, in haplotype_caller
    parallel_gc=_use_spark(num_cores, gatk_type, items, spark_opts))
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/broad/__init__.py", line 365, in run_gatk
    log_error=log_error)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && export PATH=/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/bin:"$PATH" && gatk --java-options '-Xms681m -Xmx1g -XX:+UseSerialGC -Djava.io.tmpdir=/export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/work/bcbiotx/tmp6esj9s4r' HaplotypeCaller -R /export/home/ncit/external/a.mizeranschi/bcbio_nextgen/genomes/Hsapiens/hg38/seq/hg38.fa --annotation MappingQualityRankSumTest --annotation MappingQualityZero --annotation QualByDepth --annotation ReadPosRankSumTest --annotation RMSMappingQuality --annotation BaseQualityRankSumTest --annotation FisherStrand --annotation MappingQuality --annotation DepthPerAlleleBySample --annotation Coverage -I /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/work/align/HG01518/HG01518-sort.bam -L /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/work/gatk-haplotype/chr1/HG01518-chr1_0_50142832-regions.bed --interval-set-rule INTERSECTION --annotation ClippingRankSumTest --annotation DepthPerSampleHC --native-pair-hmm-threads 1 --verbosity ERROR --emit-ref-confidence GVCF -GQB 10 -GQB 20 -GQB 30 -GQB 40 -GQB 60 -GQB 80 -ploidy 2 --output /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/work/bcbiotx/tmp6esj9s4r/HG01518-chr1_0_50142832.vcf.gz
[January 20, 2020 10:09:19 AM EET] org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller done. Elapsed time: 1.44 minutes.
Runtime.totalMemory()=1037959168
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.apache.commons.math3.util.MathArrays.copyOfRange(MathArrays.java:827)
	at org.apache.commons.math3.stat.descriptive.rank.Percentile.copyOf(Percentile.java:479)
	at org.apache.commons.math3.stat.descriptive.rank.Percentile.removeAndSlice(Percentile.java:527)
	at org.apache.commons.math3.stat.descriptive.rank.Percentile.getWorkArray(Percentile.java:455)
	at org.apache.commons.math3.stat.descriptive.rank.Percentile.evaluate(Percentile.java:351)
	at org.apache.commons.math3.stat.descriptive.rank.Percentile.evaluate(Percentile.java:302)
	at org.apache.commons.math3.stat.descriptive.AbstractUnivariateStatistic.evaluate(AbstractUnivariateStatistic.java:121)
	at org.broadinstitute.hellbender.utils.MathUtils.median(MathUtils.java:839)
	at org.broadinstitute.hellbender.utils.variant.writers.GVCFBlock.getMedianDP(GVCFBlock.java:75)
	at org.broadinstitute.hellbender.utils.variant.writers.HomRefBlock.createHomRefGenotype(HomRefBlock.java:73)
	at org.broadinstitute.hellbender.utils.variant.writers.GVCFBlock.toVariantContext(GVCFBlock.java:49)
	at org.broadinstitute.hellbender.utils.variant.writers.GVCFBlockCombiner.emitCurrentBlock(GVCFBlockCombiner.java:177)
	at org.broadinstitute.hellbender.utils.variant.writers.GVCFBlockCombiner.signalEndOfInput(GVCFBlockCombiner.java:227)
	at org.broadinstitute.hellbender.utils.variant.writers.GVCFWriter.close(GVCFWriter.java:70)
	at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller.closeTool(HaplotypeCaller.java:246)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1052)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
	at org.broadinstitute.hellbender.Main.main(Main.java:292)

```

**Comment by amizeranschi** [comment]
For what it's worth, here's what is set up in `bcbio_nextgen/galaxy/bcbio_system.yaml`. 

```
resources:
  # default options, used if other items below are not present
  # avoids needing to configure/adjust for every program
  default:
    memory: 3G
    cores: 16
    jvm_opts: ["-Xms750m", "-Xmx3500m"]
  # Can also set program specific options
  # gatk:
  #   jvm_opts: ["-Xms500m", "-Xmx3500m"]
  snpeff:
    jvm_opts: ["-Xms750m", "-Xmx3g"]
  qualimap:
    memory: 4g
  express:
    memory: 8g
  dexseq:
    memory: 10g
  macs2:
    memory: 8g
  seqcluster:
    memory: 8g
```

**Comment by chapmanb** [comment]
Thanks for the detailed report and apologies about the problems. It's unexpected that bcbio has such low memory usage here, the JVM options are not hardcoded and should be retrieved from your configuration, relative to what bcbio things is happening in the run environment. Here's where it makes that determination if you want to debug in detail:

https://github.com/bcbio/bcbio-nextgen/blob/b4dfed16c3e53f992cc94706ee8e418428018861/bcbio/broad/__init__.py#L311

My initial guess would be that bcbio doesn't detect the amount of cores and memory per node on your cluster in the way you expected. If you look in `provenance/*ipython*yaml` for the system and queue you're running this on, do the cores and memory match your expectations? If your cluster is heterogeneous and it's not finding what you expect, you can also set this:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/parallel.html#determining-available-cores-and-memory-per-machine

Hope this helps identify the problem.

**Comment by amizeranschi** [comment]
Thanks for looking into this. My cluster is heterogeneous as a whole, but the queue that I've used (called `campus-haswell.q` below) is not. All the queue's nodes have the same configuration: 32 cores and around 128 GB of memory.

I have the following right at the start of the bcbio log:

```
[2020-01-20T16:45Z] haswell-wn42.grid.pub.ro: System YAML configuration: /export/home/ncit/external/a.mizeranschi/bcbio_nextgen/galaxy/bcbio_system.yaml.
[2020-01-20T16:45Z] haswell-wn42.grid.pub.ro: Locale set to en_US.utf8.
[2020-01-20T16:45Z] haswell-wn42.grid.pub.ro: Couldn't get machine information from resource query function for queue 'campus-haswell.q' on scheduler "sge"; submitting job to queue
Traceback (most recent call last):
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/provenance/system.py", line 48, in _get_machine_info
    return sched_info_dict[parallel["scheduler"].lower()](parallel.get("queue", ""))
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/provenance/system.py", line 141, in _sge_info
    mem_info[machine_keys[min_ratio_index]]["mem_total"]
TypeError: 'dict_keys' object does not support indexing
[2020-01-20T16:45Z] haswell-wn42.grid.pub.ro: Resource requests: ; memory: 1.00; cores: 1
[2020-01-20T16:45Z] haswell-wn42.grid.pub.ro: Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[ProfileCreate] Generating default config file: '/export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/work/log/ipython/ipython_config.py'
[ProfileCreate] Generating default config file: '/export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/work/log/ipython/ipython_kernel_config.py'
[ProfileCreate] Generating default config file: '/export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/work/log/ipython/ipcontroller_config.py'
[ProfileCreate] Generating default config file: '/export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/work/log/ipython/ipengine_config.py'
[ProfileCreate] Generating default config file: '/export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/work/log/ipython/ipcluster_config.py'
2020-01-20 18:45:48.460 [IPClusterStart] Using existing profile dir: '/export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/work/log/ipython'
```

However, the file that you mentioned earlier DOES contain the correct configuration of my cluster's queue:

```
$ cat /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/work/provenance/system-ipython-campus-haswell.q.yaml
- cores: 32
  memory: 124.9
  name: haswell-wn37.grid.pub.ro
```

**Comment by roryk** [comment]
Thanks, sorry about that, we don't often run clusters with SGE and it looks like we missed this issue moving to python3.

**Comment by chapmanb** [comment]
Thanks for helping debug. I pushed a small fix for the SGE issue, although I don't think that's the root cause of your issues since the backup cluster submission approach seems to be working.

For trying to identify the memory issue, the next step would be to look for `Resource requests:` specifications in your `log/bcbio-nextgen.log` file. This should help determine what type of resources bcbio thinks it needs to allocate when running each job. This might help give some clues about why it's not using your specified 3Gb of memory per run and identify the underlying issue. Thanks again for helping work on this.

**Comment by amizeranschi** [comment]
Below are the resource requests. Note: the cluster node `haswell-wn42.grid.pub.ro` is where the main bcbio process is running, while the others are executing the `bcbio-c` and `bcbio-e` jobs.

```
$ grep "Resource requests:" /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/work/log/bcbio-nextgen-debug.log | head -n 10
[2020-01-22T13:20Z] haswell-wn42.grid.pub.ro: Resource requests: ; memory: 1.00; cores: 1
[2020-01-22T13:21Z] haswell-wn42.grid.pub.ro: Resource requests: bwa, sambamba, samtools; memory: 3.00, 3.00, 3.00; cores: 4, 4, 4
[2020-01-22T13:24Z] haswell-wn31.grid.pub.ro: Resource requests: ; memory: 1.00; cores: 1
[2020-01-22T13:24Z] haswell-wn31.grid.pub.ro: Resource requests: ; memory: 1.00; cores: 1
[2020-01-22T13:24Z] haswell-wn33.grid.pub.ro: Resource requests: ; memory: 1.00; cores: 1
[2020-01-22T13:24Z] haswell-wn31.grid.pub.ro: Resource requests: ; memory: 1.00; cores: 1
[2020-01-22T13:24Z] haswell-wn33.grid.pub.ro: Resource requests: ; memory: 1.00; cores: 1
[2020-01-22T13:24Z] haswell-wn38.grid.pub.ro: Resource requests: ; memory: 1.00; cores: 1
[2020-01-22T13:24Z] haswell-wn38.grid.pub.ro: Resource requests: ; memory: 1.00; cores: 1
[2020-01-22T13:24Z] haswell-wn33.grid.pub.ro: Resource requests: ; memory: 1.00; cores: 1

$ grep "Resource requests:" /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/work/log/bcbio-nextgen-debug.log | tail -n 10
[2020-01-22T13:24Z] haswell-wn39.grid.pub.ro: Resource requests: ; memory: 1.00; cores: 1
[2020-01-22T13:24Z] haswell-wn35.grid.pub.ro: Resource requests: ; memory: 1.00; cores: 1
[2020-01-22T13:24Z] haswell-wn32.grid.pub.ro: Resource requests: ; memory: 1.00; cores: 1
[2020-01-22T13:24Z] haswell-wn34.grid.pub.ro: Resource requests: ; memory: 1.00; cores: 1
[2020-01-22T13:24Z] haswell-wn40.grid.pub.ro: Resource requests: ; memory: 1.00; cores: 1
[2020-01-22T13:24Z] haswell-wn30.grid.pub.ro: Resource requests: ; memory: 1.00; cores: 1
[2020-01-22T13:24Z] haswell-wn38.grid.pub.ro: Resource requests: ; memory: 1.00; cores: 1
[2020-01-22T13:24Z] haswell-wn30.grid.pub.ro: Resource requests: ; memory: 1.00; cores: 1
[2020-01-22T13:24Z] haswell-wn34.grid.pub.ro: Resource requests: ; memory: 1.00; cores: 1
[2020-01-22T13:45Z] haswell-wn42.grid.pub.ro: Resource requests: gatk, gatk-haplotype, picard; memory: 1.00; cores: 1, 1, 1
```

**Comment by chapmanb** [comment]
Thanks for the additional details. I think I see the underlying issue now. The memory specifications look like:
```
      default:
        memory: 3G
        cores: 16
        jvm_opts: ["-Xms800m", "-Xmx3000m"]
      gatk-haplotype:
        options: ["--verbosity ERROR"]
```
For the three programs it's using to determine memory usage for the GATK run part of the code. The specifications don't inherit so you end up with `gatk-haplotype`, `gatk` and `picard` not specifying any cores, the default doesn't get read, and you end up with a "I don't know what to do" specification of just 1 core and 1 Gb of memory. If you adjust to:
```
      gatk-haplotype:
        cores: 16
        jvm_opts: ["-Xms800m", "-Xmx3000m"]
        options: ["--verbosity ERROR"]
```
it should hopefully allocate the amount of memory and cores you've specified and work correctly. Sorry about the confusion and hope this fixes it for you.

**Comment by amizeranschi** [comment]
OK, I was expecting the default `jvm_opts` would apply to gatk-haplotype as well. I've specified this in the YAML template now:

```
    resources:
      default:
        memory: 3G
        cores: 8
        jvm_opts: ["-Xms800m", "-Xmx3500m"]
      gatk-haplotype:
        options: ["--verbosity ERROR"]
        jvm_opts: ["-Xms800m", "-Xmx7g"]
        cores: 8
      gatk:
        options: ["--verbosity ERROR"]
        jvm_opts: ["-Xms800m", "-Xmx3500m"]
      picard:
        options: ["VERBOSITY=ERROR"]
        jvm_opts: ["-Xms800m", "-Xmx2300m"]
```

And it does make a difference this time:

```
[2020-01-23T04:41Z] haswell-wn42.grid.pub.ro: Resource requests: gatk, gatk-haplotype, picard; memory: 3.50, 7.00, 2.30; cores: 1, 8, 1
```

This got rid of the `java.lang.OutOfMemoryError: Java heap space` errors.

Note, I also tried specifying 8 cores for HaplotypeCaller. It looks like bcbio does mention this in the `Resource requests` above. However, the `--native-pair-hmm-threads` setting in the HaplotypeCaller command below doesn't reflect this:

```
[2020-01-23T05:14Z] haswell-wn34.grid.pub.ro: unset JAVA_HOME && export PATH=/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/bin:"$PATH" && gatk --java-options '-Xms727m -Xmx6g -XX:+UseSerialGC -Djava.io.tmpdir=/export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/work/bcbiotx/tmp9h9scbnq' HaplotypeCaller -R /export/home/ncit/external/a.mizeranschi/bcbio_nextgen/genomes/Hsapiens/hg38/seq/hg38.fa --annotation MappingQualityRankSumTest --annotation MappingQualityZero --annotation QualByDepth --annotation ReadPosRankSumTest --annotation RMSMappingQuality --annotation BaseQualityRankSumTest --annotation FisherStrand --annotation MappingQuality --annotation DepthPerAlleleBySample --annotation Coverage -I /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/work/align/NA20847/NA20847-sort.bam -L /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/work/gatk-haplotype/chrX/NA20847-chrX_98930886_118075218-regions.bed --interval-set-rule INTERSECTION --annotation ClippingRankSumTest --annotation DepthPerSampleHC --native-pair-hmm-threads 1 --verbosity ERROR --emit-ref-confidence GVCF -GQB 10 -GQB 20 -GQB 30 -GQB 40 -GQB 60 -GQB 80 -ploidy 2 --output /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/work/bcbiotx/tmp9h9scbnq/NA20847-chrX_98930886_118075218.vcf.gz
```

I assume this is intentional, but I wanted to ask: what is the logic here? Is parallelization only meant to be achieved by splitting up the analysis regions, and running each on one core?

**Comment by roryk** [comment]
@amizeranschi you nailed the reasoning-- it's better to run 8x more regions simultaneously than 1 more slowly.

**Comment by amizeranschi** [comment]
OK, cool. Thanks for clarifying.
