### ISSUE TITLE
Most_severe and Biotype not compatible.

### ISSUE THREAD

**Issue by alhafidzhamdan** [bcbio/bcbio-nextgen#3068]
Hi there - I've just encountered this issue also.
I'm running bcbio-1.1.5 through an SGE and it is difficult to upgrade to the latest version of bcbio.
This is part of the log:

> [2020-01-23T04:52Z] Using GATK jar /gpfs/igmmfs01/eddie/NextGenResources/bcbio-1.1.5/anaconda/share/gatk4-4.1.4.1-1/gatk-package-4.1.4.1-local.jar
[2020-01-23T04:52Z] Running:
[2020-01-23T04:52Z]     java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xms454m -Xmx5g -XX:+UseSerialGC -Djava.io.tmpdir=/gpfs/igmmfs01/eddie/
Glioblastoma-WGS/bcbio/work/DO11501/bcbiotx/tmpp0sivdd1 -jar /gpfs/igmmfs01/eddie/NextGenResources/bcbio-1.1.5/anaconda/share/gatk4-4.1.4.1-1/gatk-package-4.1.4.1-local.jar GatherVcfs -I /gpfs/igmmfs01/eddie/Glioblastoma-WGS/bcbio/work/DO11501/vardict/DO1
1501-files.list -O /gpfs/igmmfs01/eddie/Glioblastoma-WGS/bcbio/work/DO11501/bcbiotx/tmp3ww484gx/DO11501.vcf.gz
[2020-01-23T04:52Z] tabix index DO11501.vcf.gz
[2020-01-23T04:52Z] Resource requests: bcbio_variation, fastqc, gatk, gatk-vqsr, gemini, kraken, preseq, qsignature, sambamba, samtools; memory: 3.00, 3.00, 6.00, 3.00, 3.00, 3.00, 3.00, 3.00, 3.00, 3.00; cores: 16, 16, 1, 16, 16, 16, 16, 16, 16, 16
[2020-01-23T04:52Z] Configuring 1 jobs to run, using 8 cores each with 48.1g of memory reserved for each job
[2020-01-23T04:52Z] Timing: joint squaring off/backfilling
[2020-01-23T04:52Z] Timing: variant post-processing
[2020-01-23T04:52Z] multiprocessing: postprocess_variants
[2020-01-23T04:52Z] Finalizing variant calls: DO11501T, vardict
[2020-01-23T04:52Z] Calculating variation effects for DO11501T, vardict
[2020-01-23T04:52Z] Ensembl variant effect predictor : DO11501T
[2020-01-23T04:52Z] Possible precedence issue with control flow operator at /gpfs/igmmfs01/eddie/NextGenResources/bcbio-1.1.5/anaconda/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 805.
[2020-01-23T04:52Z] ERROR: Can't use --most_severe and --biotype together
[2020-01-23T04:52Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/exports/igmm/eddie/NextGenResources/bcbio-1.1.5/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/exports/igmm/eddie/NextGenResources/bcbio-1.1.5/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset PERL5LIB && export PATH=/gpfs/igmmfs01/eddie/NextGenResources/bcbio-1.1.5/anaconda/bin:"$PATH" && /exports/igmm/eddie/NextGenResources/bcbio-1.1.5/anaconda/bin/vep --vcf -o stdout -i /gpfs/igmmfs01/eddie/Glioblastoma-WGS/bcbio/work/DO11501/vardict/DO11501.vcf.gz --fork 8 -e --species homo_sapiens --no_stats --cache --offline --dir /gpfs/igmmfs01/eddie/NextGenResources/bcbio-1.1.5/genomes/Hsapiens/hg38/vep --total_length --gene_phenotype --regulatory --af --max_af --af_1kg --af_esp --af_gnomad --pubmed --variant_class --allele_number --fasta /gpfs/igmmfs01/eddie/NextGenResources/bcbio-1.1.5/genomes/Hsapiens/hg38/seq/hg38.fa.gz --plugin LoF,human_ancestor_fa:false,loftee_path:/gpfs/igmmfs01/eddie/NextGenResources/bcbio-1.1.5/anaconda/share/ensembl-vep-98.0-0 --plugin G2P,file:/gpfs/igmmfs01/eddie/Glioblastoma-WGS/bcbio/work/variation/G2P.csv --sift b --polyphen b --humdiv --hgvsg --hgvs --shift_hgvs 1 --most_severe --merged | sed '/^#/! s/;;/;/g' | bgzip -c > /gpfs/igmmfs01/eddie/Glioblastoma-WGS/bcbio/work/DO11501/bcbiotx/tmpwp7_72v5/DO11501-vepeffects.vcf.gz
Possible precedence issue with control flow operator at /gpfs/igmmfs01/eddie/NextGenResources/bcbio-1.1.5/anaconda/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 805.
ERROR: Can't use --most_severe and --biotype together
' returned non-zero exit status 2.
Traceback (most recent call last):
  File "/exports/igmm/eddie/NextGenResources/bcbio-1.1.5/to

- How do I either change bcbio configuration so that it doesn't turn on biotype automatically or the VEP parameters so that most_severe and biotype don't crash?

It's probably pretty basic but I've tried this in the yaml file...adding "-e" to VEP resources but not sure if that's the right to do, or if i've done it the right way.

details:
- algorithm:
    aligner: false
    mark_duplicates: false
    remove_lcr: true
    mixup_check: qsignature
    variantcaller: 
      somatic: [vardict, strelka2, mutect2]
      germline: [gatk-haplotype]
    min_allele_fraction: 5
    indelcaller: false
    effects: vep
    effects_transcripts: canonical
    ensemble:
      numpass: 2
      use_filtered: false
    tools_off: [gemini]
    tools_on: [gatk4]
  analysis: variant2
  genome_build: hg38
  resources:
    vep: 
      options: ["-e"] 

Any help is much appreciated!!

**Comment by matthdsm** [comment]
Hi,

Just remove the line `effects_transcripts: canonical` from your config. That's the one which adds the `most_severe` param to vep.
see here 
https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/variation/effects.py#L187

Cheers
M

**Comment by roryk** [comment]
Thanks for answering Matthias!

**Comment by alhafidzhamdan** [comment]
> Hi,
> 
> Just remove the line `effects_transcripts: canonical` from your config. That's the one which adds the `most_severe` param to vep.
> see here
> https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/variation/effects.py#L187
> 
> Cheers
> M

Thank you! Much appreciated!
