### ISSUE TITLE
GenomicsDBImport fails with 2500 samples: OSError: [Errno 7] Argument list too long: '/bin/bash'

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#3074]
Hello,

I've been running tests with 2500 small samples (around 100 reads each) to see if bcbio can cope with them on an SGE cluster. I'm running bcbio version 1.2.0a.

So far, I managed to run HaplotypeCaller to call variants from them independently (no batching) and produce GVCF files. Now, I'm trying to run a separate analysis directly from the GVCF files, for joint genotyping.

Following from an earlier discussion (https://github.com/bcbio/bcbio-nextgen/issues/2336), I've set up a CSV file for all the GVCF files, grouping them in a single batch. Then, I'm feeding these files as input to bcbio and it appears to create a YAML configuration file correctly. This is the template that I've used:

```
# Template for whole genome Illumina variant calling with GATK pipeline
---
details:
  - analysis: variant2
    genome_build: hg38
    resources:
      default:
        memory: 3G
        cores: 4
        jvm_opts: ["-Xms800m", "-Xmx3500m"]
      gatk-haplotype:
        options: ["--verbosity ERROR"]
        jvm_opts: ["-Xms800m", "-Xmx3500m"]
      gatk:
        options: ["--verbosity ERROR"]
        jvm_opts: ["-Xms800m", "-Xmx3500m"]
      picard:
        options: ["VERBOSITY=ERROR"]
        jvm_opts: ["-Xms800m", "-Xmx3500m"]
    algorithm:
      aligner: false
      recalibrate: false
      realign: false
      effects: false
      tools_off: [gemini, contamination, peddy, vqsr]
      jointcaller: gatk-haplotype-joint
      ploidy: 2
      variant_regions: ../config/variant_regions.bed
```

However, bcbio is crashing during the joint squaring off/backfilling step when running on all the 2500 samples. It works fine with just 10 samples, so it looks like the large number of samples is causing GATK's GenomicsDBImport to trip some kind of OS limit: `OSError: [Errno 7] Argument list too long: '/bin/bash'`. 

I've looked into `bcbio-nextgen-commands.log` and GenomicsDBImport is being executed on all the 2500 samples simultaneously, with the option `--batch-size 50`, which doesn't seem to help in my case:

```
[2020-01-30T06:56Z] haswell-wn29.grid.pub.ro: unset JAVA_HOME && export PATH=/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/bin:"$PATH" && gatk --java-options '-Xms800m -Xmx11466m -XX:+UseSerialGC -Djava.io.tmpdir=/export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/work/joint/gatk-haplotype-joint/testingVC/chr7/bcbiotx/tmp2bu4nmgf' GenomicsDBImport --reader-threads 4 --genomicsdb-workspace-path testingVC-chr7_0_141973873_genomicsdb -L chr7:1-141973873 --variant /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/work/precalled/HG00096-joint-gatk-haplotype-annotated-precalled.vcf.gz --variant /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/work/precalled/HG00097-joint-gatk-haplotype-annotated-precalled.vcf.gz --variant /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/work/precalled/HG00099-joint-gatk-haplotype-annotated-precalled.vcf.gz [...] --batch-size 50
```

Is there anything I can do to get GenomicsDBImport working with such a large number of samples? I'll cross-post this to GATK's issue tracker as well, in case they have a solution.

Here's the full stack trace:

```
[2020-01-30T06:56Z] haswell-wn42.grid.pub.ro: Timing: joint squaring off/backfilling
[2020-01-30T06:56Z] haswell-wn42.grid.pub.ro: ipython: square_batch_region
[2020-01-30T06:56Z] haswell-wn29.grid.pub.ro: GATK: GenomicsDBImport
[2020-01-30T06:56Z] haswell-wn29.grid.pub.ro: Uncaught exception occurred
Traceback (most recent call last):
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 85, in _do_run
    env=env,
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: '/bin/bash'
[2020-01-30T06:56Z] haswell-wn29.grid.pub.ro: Unexpected error
Traceback (most recent call last):
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 54, in _setup_logging
    yield config
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 563, in square_batch_region
    return ipython.zip_args(apply(joint.square_batch_region, *args))
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 82, in apply
    return object(*args, **kwargs)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/variation/joint.py", line 183, in square_batch_region
    gatkjoint.run_region(data, region, vrn_files, out_file)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/variation/gatkjoint.py", line 23, in run_region
    genomics_db = _run_genomicsdb_import(vrn_files, region, out_file, data)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/variation/gatkjoint.py", line 65, in _run_genomicsdb_import
    broad_runner.run_gatk(params, memscale=memscale)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/broad/__init__.py", line 365, in run_gatk
    log_error=log_error)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 85, in _do_run
    env=env,
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: '/bin/bash'
2020-01-30 08:56:56.344 [IPClusterStop] Using existing profile dir: '/export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/work/log/ipython'
2020-01-30 08:56:56.353 [IPClusterStop] Stopping cluster [pid=1545] with [signal=<Signals.SIGINT: 2>]
2020-01-30 08:56:57.176 [IPClusterStop] Using existing profile dir: '/export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/work/log/ipython'
2020-01-30 08:56:57.182 [IPClusterStop] Stopping cluster [pid=1545] with [signal=<Signals.SIGINT: 2>]
Running bcbio version: 1.2.0a
global config: /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/work/bcbio_system.yaml
run info config: /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC/config/testingVC.yaml
1 Engines running
Sending a shutdown signal to the controller and engines.
1 Engines running
Sending a shutdown signal to the controller and engines.
12 Engines running
Sending a shutdown signal to the controller and engines.
78 Engines running
Sending a shutdown signal to the controller and engines.
Traceback (most recent call last):
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/tools/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 58, in run_main
    fc_dir, run_info_yaml)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 164, in variant2pipeline
    samples = joint.square_off(samples, run_parallel)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/variation/joint.py", line 142, in square_off
    "vrn_file", ["region", "sam_ref", "config"])
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/distributed/split.py", line 35, in grouped_parallel_split_combine
    final_output = parallel_fn(parallel_name, split_args)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipython.py", line 137, in run
    for data in view.map_sync(fn, items, track=False):
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/ipyparallel/client/view.py", line 344, in map_sync
    return self.map(f,*sequences,**kwargs)
  File "</export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/decorator.py:decorator-gen-140>", line 2, in map
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/ipyparallel/client/view.py", line 52, in sync_results
    ret = f(self, *args, **kwargs)
  File "</export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/decorator.py:decorator-gen-139>", line 2, in map
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/ipyparallel/client/view.py", line 37, in save_ids
    ret = f(self, *args, **kwargs)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/ipyparallel/client/view.py", line 1114, in map
    return pf.map(*sequences)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/ipyparallel/client/remotefunction.py", line 299, in map
    return self(*sequences, __ipp_mapping=True)
  File "</export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/decorator.py:decorator-gen-122>", line 2, in __call__
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/ipyparallel/client/remotefunction.py", line 80, in sync_view_results
    return f(self, *args, **kwargs)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/ipyparallel/client/remotefunction.py", line 285, in __call__
    return r.get()
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/ipyparallel/client/asyncresult.py", line 169, in get
    raise self.exception()
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/ipyparallel/client/asyncresult.py", line 228, in _resolve_result
    results = error.collect_exceptions(results, self._fname)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/ipyparallel/error.py", line 233, in collect_exceptions
    raise e
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python3.6/site-packages/ipyparallel/error.py", line 231, in collect_exceptions
    raise CompositeError(msg, elist)
ipyparallel.error.CompositeError: one or more exceptions from call to method: square_batch_region
[78:apply]: OSError: [Errno 7] Argument list too long: '/bin/bash'
```

**Comment by matthdsm** [comment]
Hi,

I think this has nothing to do with bcbio, but with the sheer amount of samples you're trying to process. The OS has a limit to the amount of arguments you can pass to the command line.

I think the way to go in your case is to [incrementally import](https://github.com/GenomicsDB/GenomicsDB/wiki/Incremental-import-into-GenomicsDB) you samples into GenomicsDB and go from there. Once you've joint-GT'ed your samples from gDB, you can pull the resulting vcf through bcbio for the annotation and QC.

Or you can check out [Hail](hail.is) if you want to play around with Spark clusters..

Cheers
M

**Comment by amizeranschi** [comment]
@matthdsm Thanks for the suggestions. I'm not sure how I could pull the resulting VCF file through bcbio for the annotation and QC. Would this be similar to how I was using GVCF files as input for joint genotyping (as described in https://github.com/bcbio/bcbio-nextgen/issues/2336)?

In the mean time, I noticed that bcbio can run `CombineGVCFs` instead of `GenomicsDBImport` based on the recursive GVCF batching solution implemented here: https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/variation/gatkjoint.py#L139.

Unfortunately, this only works with gatk3: https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/variation/gatkjoint.py#L22.

It would help to be able to still use gatk4, while disabling `GenomicsDBImport` in favor of `CombineGVCFs`. @roryk @chapmanb Could you add an option such as `tools_off: genomicsdb` to enable this? 

Alternatively, could you implement this TSV-file-based solution suggested on the GATK issue tracker, here: https://github.com/broadinstitute/gatk/issues/6428? This looks like it could fix OS errors with `CombineGVCFs` for large sample batches in the long run.

**Comment by roryk** [comment]
Hi everyone,

Yup, we can do the TSV file-based solution, that seems like the most straightforward way to go.

**Comment by roryk** [comment]
Thanks @amizeranschi! I fixed this to use the TSV option so we should be good to go.

**Comment by amizeranschi** [comment]
This worked great, thanks a lot for the fix. Looks like bcbio is ready to handle thousands of samples. Now, if only NGS prices could drop some more.
