### ISSUE TITLE
sqlite3.InterfaceError while running vcf2db.py

### ISSUE THREAD

**Issue by waemm** [bcbio/bcbio-nextgen#3087]
Hi, 

I am running a single tumor only analysis using mutect and vardict. I think this issue is similar to https://github.com/bcbio/bcbio-nextgen/issues/2567 - it appears there is some malformed data that is being passed to sqlalchemy. Any help on how I can get this running again or what is going on would be greatly appreciated!

Thanks
Warren

Attached logs: 
[logs.zip](https://github.com/bcbio/bcbio-nextgen/files/4185450/logs.zip)

[2020-02-11T10:38Z] GEMINI: create database with vcf2db
...
[2020-02-11T10:39Z] gnomad_af_nfe -1.0
[2020-02-11T10:39Z] gnomad_af_oth -1.0
[2020-02-11T10:39Z] gnomad_af_popmax -1.0
[2020-02-11T10:39Z] gnomad_af_sas -1.0
[2020-02-11T10:39Z] gnomad_an (248486, 247120)
[2020-02-11T10:39Z] gt_alt_depths i�
[2020-02-11T10:39Z] gt_alt_freqs D'�$H{�?
[2020-02-11T10:39Z] gt_depths iI
[2020-02-11T10:39Z] gt_phases ?
[2020-02-11T10:39Z] gt_quals f��
[2020-02-11T10:39Z] gt_ref_depths i�
[2020-02-11T10:39Z] gt_types i
[2020-02-11T10:39Z] gts G/A
...

[2020-02-11T10:39Z] Traceback (most recent call last):
[2020-02-11T10:39Z]   File "/shared/pipeline-user/tools/local/bin/vcf2db.py", line 924, in <module>
[2020-02-11T10:39Z]     impacts_extras=a.impacts_field, aok=a.a_ok)
[2020-02-11T10:39Z]   File "/shared/pipeline-user/tools/local/bin/vcf2db.py", line 234, in __init__
[2020-02-11T10:39Z]     self.load()
[2020-02-11T10:39Z]   File "/shared/pipeline-user/tools/local/bin/vcf2db.py", line 319, in load
[2020-02-11T10:39Z]     i = self._load(self.cache, create=True, start=1)
[2020-02-11T10:39Z]   File "/shared/pipeline-user/tools/local/bin/vcf2db.py", line 312, in _load
[2020-02-11T10:39Z]     self.insert(variants, expanded, keys, i, create=create)
[2020-02-11T10:39Z]   File "/shared/pipeline-user/tools/local/bin/vcf2db.py", line 374, in insert
[2020-02-11T10:39Z]     vilengths, variant_impacts)
[2020-02-11T10:39Z]   File "/shared/pipeline-user/tools/local/bin/vcf2db.py", line 402, in _insert
[2020-02-11T10:39Z]     self.__insert(v_objs, self.metadata.tables['variants'].insert())
[2020-02-11T10:39Z]   File "/shared/pipeline-user/tools/local/bin/vcf2db.py", line 436, in __insert
[2020-02-11T10:39Z]     raise e
[2020-02-11T10:39Z] sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Error binding parameter 113 - probably unsupported type.
[2020-02-11T10:39Z] [SQL: INSERT INTO variants (variant_id, chrom, start, "end", vcf_id, ref, alt, qual, filter, type, sub_type, call_rate, num_hom_ref, num_het, num_hom_alt, num_unknown, aaf, gene, ensembl_gene_id, transcript, is_exonic, is_coding, is_lof, is_splicing, is_canonical, exon, codon_change, aa_change, aa_length, biotype, impact, impact_so, impact_severity, polyphen_pred, polyphen_score, sift_pred, sift_score, adjaf, af, bias, db, decomposed, dkfzbias, dp, duprate, epr, hiaf, hicnt, hicov, len, lof, lseq, mq, msi, msilen, nm, nmd, oddratio, old_variant, pmean, pstd, qstd, refbias, rseq, sample, sbf, shift3, sn, spanpair, splitread, varbias, vd, ac_adj_exac_afr, ac_adj_exac_amr, ac_adj_exac_eas, ac_adj_exac_fin, ac_adj_exac_nfe, ac_adj_exac_oth, ac_adj_exac_sas, ac_exac_all, af_adj_exac_afr, af_adj_exac_amr, af_adj_exac_eas, af_adj_exac_fin, af_adj_exac_nfe, af_adj_exac_oth, af_adj_exac_sas, af_esp_aa, af_esp_all, af_esp_ea, af_exac_all, an_adj_exac_afr, an_adj_exac_amr, an_adj_exac_eas, an_adj_exac_fin, an_adj_exac_nfe, an_adj_exac_oth, an_adj_exac_sas, an_exac_all, clinvar_disease_name, clinvar_sig, common_pathogenic, gnomad_ac, gnomad_af, gnomad_af_afr, gnomad_af_amr, gnomad_af_asj, gnomad_af_eas, gnomad_af_fin, gnomad_af_nfe, gnomad_af_oth, gnomad_af_popmax, gnomad_af_sas, gnomad_an, max_aaf_all, num_exac_het, num_exac_hom, rs_ids, gts, gt_types, gt_phases, gt_depths, gt_ref_depths, gt_alt_depths, gt_quals, gt_alt_freqs) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[2020-02-11T10:39Z] [parameters: (1020, u'chr1', 13369357, 13369358, u'rs12123444', u'G', u'A', 210.0, None, 'snp', 'ts', 1.0, 0, 1, 0, 0, 0.5, u'PRAMEF19', None, u'ENST00000376101.2', 1, 1, 0, 0, 0, u'3/3', u'c.942C>T', u'p.Cys314Cys', 410, u'protein_coding', u'synonymous_variant', u'synonymous_variant', 'LOW', None, None, None, None, 0.0, 0.15219999849796295, u'2:2', 0, 0, 'None', 841, 0.0, u'pass', 0.15219999849796295, 128, 841, None, 'None', u'GACGTGTCATTGCCGTGAAA', 37.5, 1.0, 1.0, 2.9000000953674316, 'None', 1.097749948501587, 'None', 48.20000076293945, 1.0, 0.0, u'362:351', u'CAGAAAGTGGTGAGGTTGGA', u'TD1717_17-120082-A3', 0.6327099800109863, 1, 256.0, 0, 0, u'62:66', 128, 3.0, 0.0, 3.0, 10.0, 13.0, 1.0, 6.0, 36.0, 0.0003322300035506487, 0.0, 0.0003472199896350503, 0.0015215999446809292, 0.0002003599947784096, 0.0011211000382900238, 0.0003649200079962611, -1.0, -1.0, -1.0, 0.00030513000092469156, 9030.0, 11522.0, 8640.0, 6572.0, 64884.0, 892.0, 16442.0, 117982.0, None, None, 0, 244501, 0.9894000291824341, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, (248486, 247120), 0.0015215999446809292, 36.0, 0.0, u'rs12123444',[2020-02-11T10:39Z] Traceback (most recent call last):
[2020-02-11T10:39Z]   File "/shared/pipeline-user/tools/local/bin/vcf2db.py", line 924, in <module>
[2020-02-11T10:39Z]     impacts_extras=a.impacts_field, aok=a.a_ok)
[2020-02-11T10:39Z]   File "/shared/pipeline-user/tools/local/bin/vcf2db.py", line 234, in __init__
[2020-02-11T10:39Z]     self.load()
[2020-02-11T10:39Z]   File "/shared/pipeline-user/tools/local/bin/vcf2db.py", line 319, in load
[2020-02-11T10:39Z]     i = self._load(self.cache, create=True, start=1)
[2020-02-11T10:39Z]   File "/shared/pipeline-user/tools/local/bin/vcf2db.py", line 312, in _load
[2020-02-11T10:39Z]     self.insert(variants, expanded, keys, i, create=create)
[2020-02-11T10:39Z]   File "/shared/pipeline-user/tools/local/bin/vcf2db.py", line 374, in insert
[2020-02-11T10:39Z]     vilengths, variant_impacts)
[2020-02-11T10:39Z]   File "/shared/pipeline-user/tools/local/bin/vcf2db.py", line 402, in _insert
[2020-02-11T10:39Z]     self.__insert(v_objs, self.metadata.tables['variants'].insert())
[2020-02-11T10:39Z]   File "/shared/pipeline-user/tools/local/bin/vcf2db.py", line 436, in __insert
[2020-02-11T10:39Z]     raise e
[2020-02-11T10:39Z] sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Error binding parameter 113 - probably unsupported type.
[2020-02-11T10:39Z] [SQL: INSERT INTO variants (variant_id, chrom, start, "end", vcf_id, ref, alt, qual, filter, type, sub_type, call_rate, num_hom_ref, num_het, num_hom_alt, num_unknown, aaf, gene, ensembl_gene_id, transcript, is_exonic, is_coding, is_lof, is_splicing, is_canonical, exon, codon_change, aa_change, aa_length, biotype, impact, impact_so, impact_severity, polyphen_pred, polyphen_score, sift_pred, sift_score, adjaf, af, bias, db, decomposed, dkfzbias, dp, duprate, epr, hiaf, hicnt, hicov, len, lof, lseq, mq, msi, msilen, nm, nmd, oddratio, old_variant, pmean, pstd, qstd, refbias, rseq, sample, sbf, shift3, sn, spanpair, splitread, varbias, vd, ac_adj_exac_afr, ac_adj_exac_amr, ac_adj_exac_eas, ac_adj_exac_fin, ac_adj_exac_nfe, ac_adj_exac_oth, ac_adj_exac_sas, ac_exac_all, af_adj_exac_afr, af_adj_exac_amr, af_adj_exac_eas, af_adj_exac_fin, af_adj_exac_nfe, af_adj_exac_oth, af_adj_exac_sas, af_esp_aa, af_esp_all, af_esp_ea, af_exac_all, an_adj_exac_afr, an_adj_exac_amr, an_adj_exac_eas, an_adj_exac_fin, an_adj_exac_nfe, an_adj_exac_oth, an_adj_exac_sas, an_exac_all, clinvar_disease_name, clinvar_sig, common_pathogenic, gnomad_ac, gnomad_af, gnomad_af_afr, gnomad_af_amr, gnomad_af_asj, gnomad_af_eas, gnomad_af_fin, gnomad_af_nfe, gnomad_af_oth, gnomad_af_popmax, gnomad_af_sas, gnomad_an, max_aaf_all, num_exac_het, num_exac_hom, rs_ids, gts, gt_types, gt_phases, gt_depths, gt_ref_depths, gt_alt_depths, gt_quals, gt_alt_freqs) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[2020-02-11T10:39Z] [parameters: (1020, u'chr1', 13369357, 13369358, u'rs12123444', u'G', u'A', 210.0, None, 'snp', 'ts', 1.0, 0, 1, 0, 0, 0.5, u'PRAMEF19', None, u'ENST00000376101.2', 1, 1, 0, 0, 0, u'3/3', u'c.942C>T', u'p.Cys314Cys', 410, u'protein_coding', u'synonymous_variant', u'synonymous_variant', 'LOW', None, None, None, None, 0.0, 0.15219999849796295, u'2:2', 0, 0, 'None', 841, 0.0, u'pass', 0.15219999849796295, 128, 841, None, 'None', u'GACGTGTCATTGCCGTGAAA', 37.5, 1.0, 1.0, 2.9000000953674316, 'None', 1.097749948501587, 'None', 48.20000076293945, 1.0, 0.0, u'362:351', u'CAGAAAGTGGTGAGGTTGGA', u'TD1717_17-120082-A3', 0.6327099800109863, 1, 256.0, 0, 0, u'62:66', 128, 3.0, 0.0, 3.0, 10.0, 13.0, 1.0, 6.0, 36.0, 0.0003322300035506487, 0.0, 0.0003472199896350503, 0.0015215999446809292, 0.0002003599947784096, 0.0011211000382900238, 0.0003649200079962611, -1.0, -1.0, -1.0, 0.00030513000092469156, 9030.0, 11522.0, 8640.0, 6572.0, 64884.0, 892.0, 16442.0, 117982.0, None, None, 0, 244501, 0.9894000291824341, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, (248486, 247120), 0.0015215999446809292, 36.0, 0.0, u'rs12123444', <read-only buffer for 0x7fca868fdae0, size -1, offset 0 at 0x7fca80ea8170>, <read-only buffer for 0x7fca868fdab0, size -1, offset 0 at 0x7fca80ea8a30>, <read-only buffer for 0x7fca868fdb40, size -1, offset 0 at 0x7fca80ea81b0>, <read-only buffer for 0x7fca868fdb10, size -1, offset 0 at 0x7fca80ea8830>, <read-only buffer for 0x7fca868fdb70, size -1, offset 0 at 0x7fca80ea8030>, <read-only buffer for 0x7fca868fdba0, size -1, offset 0 at 0x7fca80ea88b0>, <read-only buffer for 0x7fca868fdbd0, size -1, offset 0 at 0x7fca80ea8070>, <read-only buffer for 0x7fca868fdc00, size -1, offset 0 at 0x7fca80ea8930>)]]

**Comment by naumenko-sa** [comment]
Hi Warren!

Could you please also attach you yaml config file? Are you using gnomad vcf to annotate variants?

Sergey

**Comment by waemm** [comment]
Hi @naumenko-sa , thanks for your reply! I have it installed in my bcbio/variation directory and it is normally included in the vcf yes. Below are my yaml files. I'm wondering if this is an issue with Gemini? I was looking at the VCF files and they don't appear to be corrupt. Could this be an issue with the installation ?
[yamls.zip](https://github.com/bcbio/bcbio-nextgen/files/4190683/yamls.zip)

**Comment by naumenko-sa** [comment]
Hi Warren!

Thanks for reporting the details!
I think it is indeed the same issue as you referenced.

1. `tools_on: gemini` triggers annotation with genomes/Hsapiens/hg38/config/vcfanno/gemini.conf
2. genomes/Hsapiens/hg38/variation/gnomad_exome.vcf.gz
3. The original gnomad_exome had two variants at chr:13369358:
```
chr1	13369358	rs759667351	G	A	37141.8	PASS	AC=22;AC_afr=0;AC_afr_female=0;AC_afr_male=0;AC_amr=0;AC_amr_female=0;AC_amr_male=0;AC_asj=0;AC_asj_female=0;AC_asj_male=0;AC_eas=0;AC_eas_female=0;AC_eas_jpn=0;AC_eas_kor=0;AC_eas_male=0;AC_eas_oea=0;AC_female=11;AC_fin=20;AC_fin_female=9;AC_fin_male=11;AC_male=11;AC_nfe=1;AC_nfe_bgr=0;AC_nfe_est=0;AC_nfe_female=1;AC_nfe_male=0;AC_nfe_nwe=0;AC_nfe_onf=1;AC_nfe_seu=0;AC_nfe_swe=0;AC_oth=1;AC_oth_female=1;AC_oth_male=0;AC_popmax=1;AC_raw=91;AC_sas=0;AC_sas_female=0;AC_sas_male=0;AF=8.85362e-05;AF_afr=0;AF_afr_female=0;AF_afr_male=0;AF_amr=0;AF_amr_female=0;AF_amr_male=0;AF_asj=0;AF_asj_female=0;AF_asj_male=0;AF_eas=0;AF_eas_female=0;AF_eas_jpn=0;AF_eas_kor=0;AF_eas_male=0;AF_eas_oea=0;AF_female=9.68395e-05;AF_fin=0.000929023;AF_fin_female=0.000873108;AF_fin_male=0.000980392;AF_male=8.15443e-05;AF_nfe=8.90313e-06;AF_nfe_bgr=0;AF_nfe_est=0;AF_nfe_female=2.02569e-05;AF_nfe_male=0;AF_nfe_nwe=0;AF_nfe_onf=3.28904e-05;AF_nfe_seu=0;AF_nfe_swe=0;AF_oth=0.000165017;AF_oth_female=0.000347464;AF_oth_male=0;AF_popmax=8.90313e-06;AF_raw=0.000363802;AF_sas=0;AF_sas_female=0;AF_sas_male=0;AN=248486;AN_afr=15076;AN_afr_female=9072;AN_afr_male=6004;AN_amr=34574;AN_amr_female=20264;AN_amr_male=14310;AN_asj=10018;AN_asj_female=4874;AN_asj_male=5144;AN_eas=18344;AN_eas_female=9294;AN_eas_jpn=152;AN_eas_kor=3812;AN_eas_male=9050;AN_eas_oea=14380;AN_female=113590;AN_fin=21528;AN_fin_female=10308;AN_fin_male=11220;AN_male=134896;AN_nfe=112320;AN_nfe_bgr=2658;AN_nfe_est=238;AN_nfe_female=49366;AN_nfe_male=62954;AN_nfe_nwe=41572;AN_nfe_onf=30404;AN_nfe_seu=11386;AN_nfe_swe=26062;AN_oth=6060;AN_oth_female=2878;AN_oth_male=3182;AN_popmax=112320;AN_raw=250136;AN_sas=30566;AN_sas_female=7534;AN_sas_male=23032;BaseQRankSum=-1.811;ClippingRankSum=0.2;DP=7214740;FS=25.545;InbreedingCoeff=0.0039;MQ=27.87;MQRankSum=2.21;QD=2.35;ReadPosRankSum=0.597;SOR=3.325;allele_type=snv;faf95=5.988e-05;faf99=5.94e-05;n_alt_alleles=1;nhomalt=0;nhomalt_afr=0;nhomalt_afr_female=0;nhomalt_afr_male=0;nhomalt_amr=0;nhomalt_amr_female=0;nhomalt_amr_male=0;nhomalt_asj=0;nhomalt_asj_female=0;nhomalt_asj_male=0;nhomalt_eas=0;nhomalt_eas_female=0;nhomalt_eas_jpn=0;nhomalt_eas_kor=0;nhomalt_eas_male=0;nhomalt_eas_oea=0;nhomalt_female=0;nhomalt_fin=0;nhomalt_fin_female=0;nhomalt_fin_male=0;nhomalt_male=0;nhomalt_nfe=0;nhomalt_nfe_bgr=0;nhomalt_nfe_est=0;nhomalt_nfe_female=0;nhomalt_nfe_male=0;nhomalt_nfe_nwe=0;nhomalt_nfe_onf=0;nhomalt_nfe_seu=0;nhomalt_nfe_swe=0;nhomalt_oth=0;nhomalt_oth_female=0;nhomalt_oth_male=0;nhomalt_popmax=0;nhomalt_raw=0;nhomalt_sas=0;nhomalt_sas_female=0;nhomalt_sas_male=0;popmax=nfe;variant_type=snv
chr1	13369358	rs12123444	G	A	4.52089e+08	PASS	AC=244501;AC_afr=14738;AC_afr_female=8780;AC_afr_male=5958;AC_amr=34012;AC_amr_female=19906;AC_amr_male=14106;AC_asj=9935;AC_asj_female=4830;AC_asj_male=5105;AC_eas=18218;AC_eas_female=9240;AC_eas_jpn=150;AC_eas_kor=3818;AC_eas_male=8978;AC_eas_oea=14250;AC_female=111572;AC_fin=21185;AC_fin_female=10154;AC_fin_male=11031;AC_male=132929;AC_nfe=110186;AC_nfe_bgr=2597;AC_nfe_est=230;AC_nfe_female=48346;AC_nfe_male=61840;AC_nfe_nwe=40751;AC_nfe_onf=29721;AC_nfe_seu=11241;AC_nfe_swe=25646;AC_oth=5970;AC_oth_female=2835;AC_oth_male=3135;AC_popmax=18218;AC_raw=247148;AC_sas=30257;AC_sas_female=7481;AC_sas_male=22776;AF=0.989402;AF_afr=0.996754;AF_afr_female=0.996821;AF_afr_male=0.996654;AF_amr=0.996952;AF_amr_female=0.997095;AF_amr_male=0.99675;AF_asj=0.99749;AF_asj_female=0.997522;AF_asj_male=0.99746;AF_eas=0.99978;AF_eas_female=1;AF_eas_jpn=1;AF_eas_kor=1;AF_eas_male=0.999555;AF_eas_oea=0.999719;AF_female=0.990097;AF_fin=0.983428;AF_fin_female=0.984105;AF_fin_male=0.982805;AF_male=0.98882;AF_nfe=0.984243;AF_nfe_bgr=0.98074;AF_nfe_est=0.966387;AF_nfe_female=0.984163;AF_nfe_male=0.984306;AF_nfe_nwe=0.984371;AF_nfe_onf=0.982123;AF_nfe_seu=0.990396;AF_nfe_swe=0.98434;AF_oth=0.990378;AF_oth_female=0.991259;AF_oth_male=0.989583;AF_popmax=0.99978;AF_raw=0.989186;AF_sas=0.991513;AF_sas_female=0.993229;AF_sas_male=0.99095;AN=247120;AN_afr=14786;AN_afr_female=8808;AN_afr_male=5978;AN_amr=34116;AN_amr_female=19964;AN_amr_male=14152;AN_asj=9960;AN_asj_female=4842;AN_asj_male=5118;AN_eas=18222;AN_eas_female=9240;AN_eas_jpn=150;AN_eas_kor=3818;AN_eas_male=8982;AN_eas_oea=14254;AN_female=112688;AN_fin=21542;AN_fin_female=10318;AN_fin_male=11224;AN_male=134432;AN_nfe=111950;AN_nfe_bgr=2648;AN_nfe_est=238;AN_nfe_female=49124;AN_nfe_male=62826;AN_nfe_nwe=41398;AN_nfe_onf=30262;AN_nfe_seu=11350;AN_nfe_swe=26054;AN_oth=6028;AN_oth_female=2860;AN_oth_male=3168;AN_popmax=18222;AN_raw=249850;AN_sas=30516;AN_sas_female=7532;AN_sas_male=22984;BaseQRankSum=-0.221;ClippingRankSum=0;DP=16511401;FS=0;InbreedingCoeff=0.0021;MQ=26.63;MQRankSum=0.297;QD=27.53;ReadPosRankSum=0;SOR=0.577;allele_type=snv;faf95=0.986112;faf99=0.986112;n_alt_alleles=1;nhomalt=120944;nhomalt_afr=7345;nhomalt_afr_female=4376;nhomalt_afr_male=2969;nhomalt_amr=16954;nhomalt_amr_female=9924;nhomalt_amr_male=7030;nhomalt_asj=4955;nhomalt_asj_female=2409;nhomalt_asj_male=2546;nhomalt_eas=9107;nhomalt_eas_female=4620;nhomalt_eas_jpn=75;nhomalt_eas_kor=1909;nhomalt_eas_male=4487;nhomalt_eas_oea=7123;nhomalt_female=55228;nhomalt_fin=10414;nhomalt_fin_female=4995;nhomalt_fin_male=5419;nhomalt_male=65716;nhomalt_nfe=54213;nhomalt_nfe_bgr=1273;nhomalt_nfe_est=111;nhomalt_nfe_female=23784;nhomalt_nfe_male=30429;nhomalt_nfe_nwe=20052;nhomalt_nfe_onf=14590;nhomalt_nfe_seu=5567;nhomalt_nfe_swe=12620;nhomalt_oth=2956;nhomalt_oth_female=1405;nhomalt_oth_male=1551;nhomalt_popmax=9107;nhomalt_raw=122248;nhomalt_sas=15000;nhomalt_sas_female=3715;nhomalt_sas_male=11285;popmax=eas;variant_type=snv
```
4. vcf2db.py tried to insert (248486, 247120) into gnomad_an into variants table and crashed.

Does it sound logical to you?

Since I was fixing that bug, I have two gnomad_exome files, and the one without duplicated does not have this issue. So it should be running fine with the fixed one.

Could you please check your gnomad_exome.vcf.gz, how many variants does it have in that position?

```bcftools view gnomad_exome.no_duplicates.vcf.gz chr1:13369358-13369358```

And please also report when did you install this gnomad vcf? Is this bug present in the latest vcf we installing with  `https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/hg38/gnomad_exome.yaml`

If that is the case, and the gnomad we are installing has duplicate records, I will need to fix the recipe.

Thanks for helping to make bcbio better!

Sergey

**Comment by waemm** [comment]
@naumenko-sa thanks for your reply! I 100% agree with your analysis and indeed, the gnomad_exome.vcf.gz I have contains two variants at that position.

I downloaded this probably a week ago so I imagine it is the newest version? So I can manually remove this record in the mean time to make sure it progresses? 

Also, would it be better to ensure all duplicate entries like this are removed? I imagine this would crash on any other such positions as well ?

Thanks again for your help!

**Comment by naumenko-sa** [comment]
@waemm thanks for confirming!
Now I see, we had normalization and duplicates removal in the recipe before.

https://github.com/chapmanb/cloudbiolinux/commit/0202508cd453c31462c8b05ef7125a239af4667d#diff-edbcf6f016ed6dbf0e759bec31e7f8a3

But then I removed it because I though this was not an issue in the new gnomad release anymore, and this procedure increased installation time. Since the issue it is still here, I will revert the recipe back. 

It will take me some time to test the recipe before committing, in the meanwhile you may try to fix your gnomad_exome: 

```
mv gnomad_exome.vcf.gz gnomad_exome.duplicates.vcf.gz
mv gnomad_exome.vcf.gz.tbi gnomad_exome.duplicates.vcf.gz.tbi
export ref=/where/reference/located/hg38.fa
bcftools view -f PASS -Ov gnomad_exome.duplicates.vcf.gz | vt decompose -s - | vt normalize -r $ref -n - | vt uniq - | grep -v "##contig=" | bgzip -c > gnomad_exome.vcf.gz
tabix gnomad_exome.vcf.gz
```

Sergey

**Comment by naumenko-sa** [comment]
with the updated recipe there is only one variant in that position in gnomad_exome.vcf.gz, so it should be fixed.

**Comment by waemm** [comment]
Thanks @naumenko-sa ! Much appreciated!!
