### ISSUE TITLE
miRNA pipeline

### ISSUE THREAD

**Issue by kokyriakidis** [bcbio/bcbio-nextgen#3103]
Hi everyone,

I want to analyze the data of this study:
```
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE68246
```
Which contains transcriptome profiling of miRNAs in 2 different cell types. I would like to perform differential mirna expression between the 2 types. 

As I can understand from the documentation, the smallRNA-seq pipeline just countifies miRNAs from a sample. Am I right?

Can you reccomend how should I proceede, which tools to use and the correct config file?

Thank you so much for the support! @lpantano

**Comment by naumenko-sa** [comment]
Hi @kokyriakidis !

Authors shared processed data (counts):
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE68246

So, you may start with counts and do DE.

To go from reads to counts you may use this template:
https://github.com/bcbio/bcbio-nextgen/blob/master/config/templates/illumina-srnaseq.yaml

SN

**Comment by lpantano** [comment]
what @naumenko-sa says is good plan and the right pointers.

**Comment by kokyriakidis** [comment]
Thanks everyone,

Do I do DE with the same tools as with regular reads (DESeq2 etc)?

Do I use all expression callers in this yaml? What about mirge2?

**Comment by lpantano** [comment]
Yes, you can use DESeq2.

If you don’t put anything you will quantify miRNA directly. Mirge2 is
another option, but you will need manual installation of their libraries,
so it may fail. You can leave seqcluster to get more stats about the data.

**Comment by kokyriakidis** [comment]
Sorry for the dump question, but I cannot understand something:
Let's say we do not specify anything. First, Star is gonna align them to the genome. Which tool will then quantify them?

If I add only seqcluster, then it will quantify them?

Finaly, If I add mirge, it is also going to quantify them. So all of them will do the same?

**Comment by lpantano** [comment]
Sure, without anything there will be quantification of mirnas and isomirs
with razers3 and mirtop. Alignment to the genome is for QC metrics and
seqcluster will try to get you clusters of small RNAs of any other types.

mirge is another Mirna quantifier.


From: Konstantinos Kyriakidis <notifications@github.com>
<notifications@github.com>
Reply: bcbio/bcbio-nextgen
<reply@reply.github.com>
<reply@reply.github.com>
Date: February 21, 2020 at 3:34:40 AM
To: bcbio/bcbio-nextgen <bcbio-nextgen@noreply.github.com>
<bcbio-nextgen@noreply.github.com>
Cc: Lorena Pantano <lorena.pantano@gmail.com> <lorena.pantano@gmail.com>,
Mention <mention@noreply.github.com> <mention@noreply.github.com>
Subject:  Re: [bcbio/bcbio-nextgen] miRNA pipeline (#3103)

Sorry for the dump question, but I cannot understand something:
Let's say we do not specify anything. First, Star is gonna align them to
the genome. Which tool will then quantify them?

If I add only seqcluster, then it will quantify them?

Finaly, If I add mirge, it is also going to quantify them. So all of them
will do the same?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bcbio/bcbio-nextgen/issues/3103?email_source=notifications&email_token=AAML6HDW64Y23Y7KZZSLT2DRD6GZ7A5CNFSM4KYKCYH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMR536A#issuecomment-589553144>,
or unsubscribe

**Comment by roryk** [comment]
Thank you so much for answering these questions Lorena. We miss you. <3

**Comment by kokyriakidis** [comment]
I get the following error when I add trna in the yaml:

```
[2020-02-21T23:27Z] tRNA for MCF_7_Monolayer_rep1_1
[2020-02-21T23:27Z] /RED/BCBIO/RESOURCES/bcbio/anaconda/share/java/mintmap/MINTmap.pl (MINTmap_v1) starting
[2020-02-21T23:27Z] Loading spliced tRNA sequences
[2020-02-21T23:27Z] Loading tRF annotations
[2020-02-21T23:27Z] Loading Lookup Table
[2020-02-21T23:27Z] Reading in fastq file
[2020-02-21T23:27Z] Running Java-based MINTplates
[2020-02-21T23:27Z] Redundant argument in printf at /RED/BCBIO/RESOURCES/bcbio/anaconda/share/java/mintmap/MINTmap.pl line 416.
[2020-02-21T23:27Z] Redundant argument in printf at /RED/BCBIO/RESOURCES/bcbio/anaconda/share/java/mintmap/MINTmap.pl line 416.
[2020-02-21T23:27Z] Generating output:
[2020-02-21T23:27Z] Creating output file: MCF_7_Monolayer_rep1_1-MINTmap_v1-exclusive-tRFs.expression.txt
[2020-02-21T23:27Z] Creating output file: MCF_7_Monolayer_rep1_1-MINTmap_v1-exclusive-tRFs.expression.html
[2020-02-21T23:27Z] Creating output file: MCF_7_Monolayer_rep1_1-MINTmap_v1-exclusive-tRFs.countsmeta.txt
[2020-02-21T23:27Z] Creating output file: MCF_7_Monolayer_rep1_1-MINTmap_v1-ambiguous-tRFs.expression.txt
[2020-02-21T23:27Z] Creating output file: MCF_7_Monolayer_rep1_1-MINTmap_v1-ambiguous-tRFs.expression.html
[2020-02-21T23:27Z] Creating output file: MCF_7_Monolayer_rep1_1-MINTmap_v1-ambiguous-tRFs.countsmeta.txt
Traceback (most recent call last):
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/shutil.py", line 544, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'MCF_7_Monolayer_rep1_1-MINTmap_v1-ambiguous-tRFs.expression.html' -> '/media/kokyriakidis/PRODUCTION/MIRPROJ/mirqc_bcbio/work/trna_mint/MCF_7_Monolayer_rep1_1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 345, in smallrnaseqpipeline
    samples = run_parallel("srna_annotation", samples)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1003, in __call__
    if self.dispatch_one_batch(iterator):
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 834, in dispatch_one_batch
    self._dispatch(tasks)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 753, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 201, in apply_async
    result = ImmediateResult(func)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 582, in __init__
    self.results = batch()
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 165, in srna_annotation
    return srna.sample_annotation(*args)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/srna/sample.py", line 146, in sample_annotation
    data['trna'] = _mint_trna_annotation(data)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/srna/sample.py", line 336, in _mint_trna_annotation
    shutil.move(filename, work_dir)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/shutil.py", line 558, in move
    copy_function(src, real_dst)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/media/kokyriakidis/PRODUCTION/MIRPROJ/mirqc_bcbio/work/trna_mint/MCF_7_Monolayer_rep1_1'

```
I think I get the same error when I DO NOT add trna but I add mirdeep2. 

Any thoughts?

**Comment by lpantano** [comment]
Not sure what is happening because it seems it is running indeed tRNA but
you say you turned it off? Can you show the yaml input file?



From: Konstantinos Kyriakidis <notifications@github.com>
<notifications@github.com>
Reply: bcbio/bcbio-nextgen
<reply@reply.github.com>
<reply@reply.github.com>
Date: February 21, 2020 at 6:35:02 PM
To: bcbio/bcbio-nextgen <bcbio-nextgen@noreply.github.com>
<bcbio-nextgen@noreply.github.com>
Cc: Lorena Pantano <lorena.pantano@gmail.com> <lorena.pantano@gmail.com>,
Mention <mention@noreply.github.com> <mention@noreply.github.com>
Subject:  Re: [bcbio/bcbio-nextgen] miRNA pipeline (#3103)

I get the following error when I add trna in the yaml:

[2020-02-21T23:27Z] tRNA for MCF_7_Monolayer_rep1_1
[2020-02-21T23:27Z]
/RED/BCBIO/RESOURCES/bcbio/anaconda/share/java/mintmap/MINTmap.pl
(MINTmap_v1) starting
[2020-02-21T23:27Z] Loading spliced tRNA sequences
[2020-02-21T23:27Z] Loading tRF annotations
[2020-02-21T23:27Z] Loading Lookup Table
[2020-02-21T23:27Z] Reading in fastq file
[2020-02-21T23:27Z] Running Java-based MINTplates
[2020-02-21T23:27Z] Redundant argument in printf at
/RED/BCBIO/RESOURCES/bcbio/anaconda/share/java/mintmap/MINTmap.pl line
416.
[2020-02-21T23:27Z] Redundant argument in printf at
/RED/BCBIO/RESOURCES/bcbio/anaconda/share/java/mintmap/MINTmap.pl line
416.
[2020-02-21T23:27Z] Generating output:
[2020-02-21T23:27Z] Creating output file:
MCF_7_Monolayer_rep1_1-MINTmap_v1-exclusive-tRFs.expression.txt
[2020-02-21T23:27Z] Creating output file:
MCF_7_Monolayer_rep1_1-MINTmap_v1-exclusive-tRFs.expression.html
[2020-02-21T23:27Z] Creating output file:
MCF_7_Monolayer_rep1_1-MINTmap_v1-exclusive-tRFs.countsmeta.txt
[2020-02-21T23:27Z] Creating output file:
MCF_7_Monolayer_rep1_1-MINTmap_v1-ambiguous-tRFs.expression.txt
[2020-02-21T23:27Z] Creating output file:
MCF_7_Monolayer_rep1_1-MINTmap_v1-ambiguous-tRFs.expression.html
[2020-02-21T23:27Z] Creating output file:
MCF_7_Monolayer_rep1_1-MINTmap_v1-ambiguous-tRFs.countsmeta.txt
Traceback (most recent call last):
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/shutil.py",
line 544, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory:
'MCF_7_Monolayer_rep1_1-MINTmap_v1-ambiguous-tRFs.expression.html' ->
'/media/kokyriakidis/PRODUCTION/MIRPROJ/mirqc_bcbio/work/trna_mint/MCF_7_Monolayer_rep1_1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/bin/bcbio_nextgen.py",
line 245, in <module>
    main(**kwargs)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/bin/bcbio_nextgen.py",
line 46, in main
    run_main(**kwargs)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py",
line 50, in run_main
    fc_dir, run_info_yaml)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py",
line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py",
line 345, in smallrnaseqpipeline
    samples = run_parallel("srna_annotation", samples)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py",
line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py",
line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1,
backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py",
line 1003, in __call__
    if self.dispatch_one_batch(iterator):
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py",
line 834, in dispatch_one_batch
    self._dispatch(tasks)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py",
line 753, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py",
line 201, in apply_async
    result = ImmediateResult(func)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py",
line 582, in __init__
    self.results = batch()
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py",
line 256, in __call__
    for func, args, kwargs in self.items]
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py",
line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py",
line 55, in wrapper
    return f(*args, **kwargs)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py",
line 165, in srna_annotation
    return srna.sample_annotation(*args)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/srna/sample.py",
line 146, in sample_annotation
    data['trna'] = _mint_trna_annotation(data)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/srna/sample.py",
line 336, in _mint_trna_annotation
    shutil.move(filename, work_dir)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/shutil.py",
line 558, in move
    copy_function(src, real_dst)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/shutil.py",
line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/shutil.py",
line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory:
'/media/kokyriakidis/PRODUCTION/MIRPROJ/mirqc_bcbio/work/trna_mint/MCF_7_Monolayer_rep1_1'


I think I get the same error when I DO NOT add trna but I add mirdeep2.

Any thoughts?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bcbio/bcbio-nextgen/issues/3103?email_source=notifications&email_token=AAML6HAVGMGCYBPZNXITYVLREBQKLA5CNFSM4KYKCYH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMUN6SI#issuecomment-589881161>,
or unsubscribe

**Comment by kokyriakidis** [comment]
Hi @lpantano !

When I add tRNA it runs for a while and displays this error message I sent you.

The yaml is:
```
upload:
  dir: ../final
details:
  - analysis: smallRNA-seq
    algorithm:
      aligner: star
      adapters: ["TGGAATTCTCGGGTGCCAAGG"]
      species: hsa
      expression_caller: [trna, seqcluster]
    description: miRChina
    genome_build: GRCh37
```

Also, any comment about the difference in adapter?

**Comment by lpantano** [comment]
Just un case, can you try hg19?



From: Konstantinos Kyriakidis <notifications@github.com>
<notifications@github.com>
Reply: bcbio/bcbio-nextgen
<reply@reply.github.com>
<reply@reply.github.com>
Date: February 24, 2020 at 9:40:44 AM
To: bcbio/bcbio-nextgen <bcbio-nextgen@noreply.github.com>
<bcbio-nextgen@noreply.github.com>
Cc: Lorena Pantano <lorena.pantano@gmail.com> <lorena.pantano@gmail.com>,
Mention <mention@noreply.github.com> <mention@noreply.github.com>
Subject:  Re: [bcbio/bcbio-nextgen] miRNA pipeline (#3103)

Hi @lpantano <https://github.com/lpantano> !

When I add tRNA it runs for a while and displays this error message I sent
you.

The yaml is:

upload:
  dir: ../final
details:
  - analysis: smallRNA-seq
    algorithm:
      aligner: star
      adapters: ["TGGAATTCTCGGGTGCCAAGG"]
      species: hsa
      expression_caller: [trna, seqcluster]
    description: miRChina
    genome_build: GRCh37

Also, any comment about the difference in adapter?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bcbio/bcbio-nextgen/issues/3103?email_source=notifications&email_token=AAML6HAP6ZRZOG5ADNSYNNTREPL6XA5CNFSM4KYKCYH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMYBBWY#issuecomment-590352603>,
or unsubscribe

**Comment by kokyriakidis** [comment]
I am downlaoding the hg19 relase now in bcbio. I tried also with hg38 but no luck
