### ISSUE TITLE
matplotlib problem

### ISSUE THREAD

**Issue by parlar** [bcbio/bcbio-nextgen#3125]
getting this error using the latest stable release of bcbio_nextgen (1.2.0)

```pkg_resources.ContextualVersionConflict: (matplotlib 3.1.2 (/home/bcbio/bcbio/anaconda/lib/python3.6/site-packages), Requirement.parse('matplotlib<3.1.2,>=2.1.1'), {'multiqc'})```

reverting matplotlib-base 3.1.2 to 3.1.1 (conda-forge) solved the issue.

**Comment by naumenko-sa** [comment]
Thanks for the reporting @parlar !

How did you find the issue? What did you run?

On a potentially related note, I'm experiencing issues with updating multiqc to 1.8 (it is a major update):
It won't update with ```bcbio_nextgen.py upgrade --tools``

```
Manual installation shows dependency issues:
bcbio_conda install -c bioconda multiqc=1.8
Collecting package metadata (current_repodata.json): done
Solving environment: / 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - bioconda/noarch::multiqc-bcbio==0.2.8=py_0
done


## Package Plan ##

  environment location: /n/app/bcbio/dev/anaconda

  added / updated specs:
    - multiqc=1.8


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    multiqc-1.8                |             py_1         792 KB  bioconda
    networkx-2.1               |           py36_0         1.9 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         2.6 MB

The following NEW packages will be INSTALLED:

  multiqc            bioconda/noarch::multiqc-1.8-py_1

The following packages will be SUPERSEDED by a higher-priority channel:

  networkx            conda-forge/noarch::networkx-2.4-py_0 --> conda-forge/linux-64::networkx-2.1-py36_0


Proceed ([y]/n)? 

Downloading and Extracting Packages
multiqc-1.8          | 792 KB    | ################################################################################################################################################################################################### | 100% 
networkx-2.1         | 1.9 MB    | ################################################################################################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

So it installs, but won't work:

```
multiqc .
Traceback (most recent call last):
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/multiqc/utils/plugin_hooks.py", line 14, in <module>
    hook_functions[nicename].append(entry_point.load())
KeyError: 'before_config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/n/app/bcbio/tools/bin/multiqc", line 6, in <module>
    from multiqc.__main__ import multiqc
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/multiqc/__init__.py", line 16, in <module>
    from .multiqc import run
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/multiqc/multiqc.py", line 38, in <module>
    from .utils import report, plugin_hooks, megaqc, util_functions, lint_helpers, config, log
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/multiqc/utils/plugin_hooks.py", line 16, in <module>
    hook_functions[nicename] = [entry_point.load()]
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    self.require(*args, **kwargs)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2466, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (matplotlib 3.1.3 (/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages), Requirement.parse('matplotlib<3.1.2,>=2.1.1'), {'multiqc'})
```

So I reverted multiqc to 1.7 or now.

SN

**Comment by roryk** [comment]
I think this is all set. I have multiqc 1.8 installed and it seems to be working fine, closing for now but re-open if it ends up being a new issue. bioconda switched the matplotlib package they are using which might have caused some of these issues.
