### ISSUE TITLE
Example pipeline - validation file not found

### ISSUE THREAD

**Issue by tony-travis** [bcbio/bcbio-nextgen#3126]
Automated install of "bcbio-nextgen" v1.2.0 using example scripts on Github, then attempting to run the first example pipeline: [Exome variant calling with validation - hg38](https://bcbio-nextgen.readthedocs.io/en/latest/contents/intro.html#exome-variant-calling-with-validation-hg38) fails with error: "Validation file not found for ['variant_regions']: capture_regions/Exome-NGv3"

**Comment by naumenko-sa** [comment]
Hi Tony @tony-travis!

Thanks for reporting. Shame on us - our entry use case is not working.

I've pushed a fix.  `variant_regions` should not be among validation targets.

Please update to the latest development and try again:
```bcbio_nextgen.py upgrade -u development```

Let us know if you see any other issues.

Sergey

**Comment by tony-travis** [comment]
Hi, Sergey.

I've done "bcbio_nextgen.py upgrade -u development" and "done wget https://raw.github.com/bcbio/bcbio-nextgen/master/config/examples/NA12878-exome-methodcmp-getdata.sh" again, but now get requests for huge amounts of memory that fail (system has 128GiB RAM):

manager@brigante:/work/manager/NA12878-exome-eval/work$ bcbio_nextgen.py ../config/NA12878-exome-methodcmp.yaml |& tee bcbio_nextgen.log
[2020-03-17T10:50Z] System YAML configuration: /work/local/share/bcbio/galaxy/bcbio_system.yaml.
[2020-03-17T10:50Z] Locale set to C.UTF-8.
[2020-03-17T10:50Z] Resource requests: bwa, sambamba, samtools; memory: 3.00, 3.00, 3.00; cores: 16, 16, 16
[2020-03-17T10:50Z] Configuring 1 jobs to run, using 1 cores each with 3.00g of memory reserved for each job
[2020-03-17T10:50Z] Timing: organize samples
[2020-03-17T10:50Z] multiprocessing: organize_samples
[2020-03-17T10:50Z] Using input YAML configuration: /work/manager/NA12878-exome-eval/config/NA12878-exome-methodcmp.yaml
[2020-03-17T10:50Z] Checking sample YAML configuration: /work/manager/NA12878-exome-eval/config/NA12878-exome-methodcmp.yaml
[2020-03-17T10:50Z] Retreiving program versions from /work/local/share/bcbio/manifest/python-packages.yaml.
[2020-03-17T10:50Z] Retreiving program versions from /work/local/share/bcbio/manifest/r-packages.yaml.
[2020-03-17T10:50Z] Testing minimum versions of installed programs
[2020-03-17T10:50Z] Timing: alignment preparation
[2020-03-17T10:50Z] multiprocessing: prep_align_inputs
Running bcbio version: 1.2.0
global config: /work/manager/NA12878-exome-eval/work/bcbio_system.yaml
run info config: /work/manager/NA12878-exome-eval/config/NA12878-exome-methodcmp.yaml
[2020-03-17T10:50Z] Skipping trimming of NA12878.
[2020-03-17T10:50Z] Resource requests: ; memory: 1.00; cores: 1
[2020-03-17T10:50Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2020-03-17T10:50Z] multiprocessing: disambiguate_split
[2020-03-17T10:50Z] Timing: alignment
[2020-03-17T10:50Z] multiprocessing: process_alignment
[2020-03-17T10:50Z] Aligning lane NA12878 with bwa aligner
[2020-03-17T10:50Z] bwa mem alignment from fastq: NA12878
[2020-03-17T10:50Z] [bwt_restore_bwt] Failed to allocate 18446744073709551576 bytes at bwt.c line 452: Cannot allocate memory
[2020-03-17T10:50Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/work/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/work/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && /work/local/share/bcbio/galaxy/../anaconda/bin/bwa mem   -c 250 -M -t 1  -R '@RG\tID:NA12878\tPL:illumina\tPU:NA12878\tSM:NA12878' -v 1 /work/local/share/bcbio/genomes/Hsapiens/hg38/bwa/hg38.fa <(grabix grab /work/manager/NA12878-exome-eval/work/align_prep/NA12878-NGv3-LAB1360-A_1.fastq.gz 1 80000000) <(grabix grab /work/manager/NA12878-exome-eval/work/align_prep/NA12878-NGv3-LAB1360-A_2.fastq.gz 1 80000000)  | /work/local/share/bcbio/galaxy/../anaconda/bin/samtools sort -n -@ 1 -m 1G -O bam -T /work/manager/NA12878-exome-eval/work/bcbiotx/tmprco33tzi/NA12878-sort-1_80000000-sorttmp-namesort -o /work/manager/NA12878-exome-eval/work/bcbiotx/tmprco33tzi/NA12878-sort-1_80000000.bam -
[bwt_restore_bwt] Failed to allocate 18446744073709551576 bytes at bwt.c line 452: Cannot allocate memory
' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/work/local/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/work/local/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/work/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/work/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/work/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 133, in variant2pipeline
    samples = run_parallel("process_alignment", samples)
  File "/work/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/work/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/work/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1004, in __call__
    if self.dispatch_one_batch(iterator):
  File "/work/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 835, in dispatch_one_batch
    self._dispatch(tasks)
  File "/work/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 754, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/work/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 209, in apply_async
    result = ImmediateResult(func)
  File "/work/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 590, in __init__
    self.results = batch()
  File "/work/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/work/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/work/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/work/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 124, in process_alignment
    return sample.process_alignment(*args)
  File "/work/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sample.py", line 128, in process_alignment
    data = align_to_sort_bam(fastq1, fastq2, aligner, data)
  File "/work/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/alignment.py", line 88, in align_to_sort_bam
    names, align_dir, data)
  File "/work/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/alignment.py", line 163, in _align_from_fastq
    out = align_fn(fastq1, fastq2, align_ref, names, align_dir, data)
  File "/work/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/ngsalign/bwa.py", line 170, in align_pipe
    names, rg_info, data)
  File "/work/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/ngsalign/bwa.py", line 181, in _align_mem
    [do.file_nonempty(tx_out_file), do.file_reasonable_size(tx_out_file, fastq_file)])
  File "/work/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/work/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && /work/local/share/bcbio/galaxy/../anaconda/bin/bwa mem   -c 250 -M -t 1  -R '@RG\tID:NA12878\tPL:illumina\tPU:NA12878\tSM:NA12878' -v 1 /work/local/share/bcbio/genomes/Hsapiens/hg38/bwa/hg38.fa <(grabix grab /work/manager/NA12878-exome-eval/work/align_prep/NA12878-NGv3-LAB1360-A_1.fastq.gz 1 80000000) <(grabix grab /work/manager/NA12878-exome-eval/work/align_prep/NA12878-NGv3-LAB1360-A_2.fastq.gz 1 80000000)  | /work/local/share/bcbio/galaxy/../anaconda/bin/samtools sort -n -@ 1 -m 1G -O bam -T /work/manager/NA12878-exome-eval/work/bcbiotx/tmprco33tzi/NA12878-sort-1_80000000-sorttmp-namesort -o /work/manager/NA12878-exome-eval/work/bcbiotx/tmprco33tzi/NA12878-sort-1_80000000.bam -
[bwt_restore_bwt] Failed to allocate 18446744073709551576 bytes at bwt.c line 452: Cannot allocate memory
' returned non-zero exit status 1.

**Comment by roryk** [comment]
What type of machine are you running this on?

It is strange it is requesting so much memory, and the log file has some oddities in it. `[2020-03-17T10:50Z] Resource requests: ; memory: 1.00; cores: 1
[2020-03-17T10:50Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job` is strange. 

I'm not sure what is going on, we've never seen this before AFAIK.

**Comment by tony-travis** [comment]
It's a Supermicro server:
manager@brigante:/work/manager/NA12878-exome-eval/work$ lsb_release -d
Description:	Ubuntu 18.04.4 LTS
manager@brigante:/work/manager/NA12878-exome-eval/work$ uname -a
Linux brigante 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
manager@brigante:/work/manager/NA12878-exome-eval/work$ free -g
              total        used        free      shared  buff/cache   available
Mem:            125           6           3           0         115         118
Swap:            15           0          15
manager@brigante:/work/manager/NA12878-exome-eval/work$ lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              12
On-line CPU(s) list: 0-11
Thread(s) per core:  1
Core(s) per socket:  6
Socket(s):           2
NUMA node(s):        2
Vendor ID:           AuthenticAMD
CPU family:          16
Model:               8
Model name:          Six-Core AMD Opteron(tm) Processor 8435
Stepping:            0
CPU MHz:             800.000
CPU max MHz:         2600.0000
CPU min MHz:         800.0000
BogoMIPS:            5637.21
Virtualisation:      AMD-V
L1d cache:           64K
L1i cache:           64K
L2 cache:            512K
L3 cache:            6144K
NUMA node0 CPU(s):   0-5
NUMA node1 CPU(s):   6-11
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt hw_pstate vmmcall npt lbrv svm_lock nrip_save pausefilter

**Comment by tony-travis** [comment]
[strangeness] I omitted the "-n 8" from the example pipeline invocation when I got the memory allocation error and tried again.

**Comment by tony-travis** [comment]
This is what happened with "-n 8":
manager@brigante:/work/manager/NA12878-exome-eval/work$ bcbio_nextgen.py ../config/NA12878-exome-methodcmp.yaml -n 8 |& tee bcbio_nextgen.log
[2020-03-17T10:33Z] System YAML configuration: /work/local/share/bcbio/galaxy/bcbio_system.yaml.
[2020-03-17T10:33Z] Locale set to C.UTF-8.
[2020-03-17T10:33Z] Resource requests: bwa, sambamba, samtools; memory: 3.00, 3.00, 3.00; cores: 16, 16, 16
[2020-03-17T10:33Z] Configuring 1 jobs to run, using 8 cores each with 24.1g of memory reserved for each job
[2020-03-17T10:33Z] Timing: organize samples
[2020-03-17T10:33Z] multiprocessing: organize_samples
[2020-03-17T10:33Z] Using input YAML configuration: /work/manager/NA12878-exome-eval/config/NA12878-exome-methodcmp.yaml
[2020-03-17T10:33Z] Checking sample YAML configuration: /work/manager/NA12878-exome-eval/config/NA12878-exome-methodcmp.yaml
[2020-03-17T10:33Z] Retreiving program versions from /work/local/share/bcbio/manifest/python-packages.yaml.
[2020-03-17T10:33Z] Retreiving program versions from /work/local/share/bcbio/manifest/r-packages.yaml.
[2020-03-17T10:33Z] Testing minimum versions of installed programs
[2020-03-17T10:33Z] Timing: alignment preparation
[2020-03-17T10:33Z] multiprocessing: prep_align_inputs
Running bcbio version: 1.2.0
global config: /work/manager/NA12878-exome-eval/work/bcbio_system.yaml
run info config: /work/manager/NA12878-exome-eval/config/NA12878-exome-methodcmp.yaml
[2020-03-17T10:34Z] bgzip input file
[2020-03-17T10:34Z] bgzip input file
[2020-03-17T10:40Z] Skipping trimming of NA12878.
[2020-03-17T10:40Z] Resource requests: ; memory: 1.00; cores: 1
[2020-03-17T10:40Z] Configuring 2 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2020-03-17T10:40Z] Index input with grabix: NA12878-NGv3-LAB1360-A_1.fastq.gz
[2020-03-17T10:40Z] Index input with grabix: NA12878-NGv3-LAB1360-A_2.fastq.gz
[2020-03-17T10:42Z] multiprocessing: disambiguate_split
[2020-03-17T10:42Z] Timing: alignment
[2020-03-17T10:42Z] multiprocessing: process_alignment
[2020-03-17T10:42Z] Aligning lane NA12878 with bwa aligner
[2020-03-17T10:43Z] bwa mem alignment from fastq: NA12878
[2020-03-17T10:43Z] [bwt_restore_bwt] Failed to allocate 18446744073709551576 bytes at bwt.c line 452: Cannot allocate memory
[2020-03-17T10:43Z] Uncaught exception occurred
[...]

**Comment by roryk** [comment]
Could you send along the bcbio-nextgen-debug.log and the bcbio-nextgen-commands.log files from the log/ directory?

**Comment by tony-travis** [comment]
[NA12878-exome-eval_log.tgz.zip](https://github.com/bcbio/bcbio-nextgen/files/4343681/NA12878-exome-eval_log.tgz.zip)

**Comment by tony-travis** [comment]
Last tried with "-n 1"

**Comment by naumenko-sa** [comment]
Hi Tony @tony-travis!

Glad that we moved to the next step. I ran the same project on 48G/16core machine, finished fine.

Could you please check you installation?
`bwa` - is bwa working at all?

Do you have indices in your installation?
For example, 
```
ls -lh /data/genomes/Hsapiens/hg38/bwa
total 5.3G
-rw-rw-r-- 1 ubuntu ubuntu 477K Mar  9  2015 hg38.fa.alt
-rw-rw-r-- 1 ubuntu ubuntu  20K Mar  9  2015 hg38.fa.amb
-rw-rw-r-- 1 ubuntu ubuntu 438K Mar  9  2015 hg38.fa.ann
-rw-rw-r-- 1 ubuntu ubuntu 3.0G Mar  9  2015 hg38.fa.bwt
-rw-rw-r-- 1 ubuntu ubuntu 768M Mar  9  2015 hg38.fa.pac
-rw-rw-r-- 1 ubuntu ubuntu 1.5G Mar  9  2015 hg38.fa.sa
```
What are your ulimits?
```
ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 254395
max locked memory       (kbytes, -l) 16384
max memory size         (kbytes, -m) unlimited
open files                      (-n) 100000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 254395
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```
Sergey

**Comment by tony-travis** [comment]
manager@brigante:/work/manager/NA12878-exome-eval/work$ which -a bwa
/usr/bin/bwa
/work/local/bin/bwa
manager@brigante:/work/manager/NA12878-exome-eval/work$ /usr/bin/bwa |& head -4

Program: bwa (alignment via Burrows-Wheeler transformation)
Version: 0.7.17-r1188
Contact: Heng Li <lh3@sanger.ac.uk>
manager@brigante:/work/manager/NA12878-exome-eval/work$ /work/local/bin/bwa |& head -4

Program: bwa (alignment via Burrows-Wheeler transformation)
Version: 0.7.17-r1188
Contact: Heng Li <lh3@sanger.ac.uk>
manager@brigante:/work/manager/NA12878-exome-eval/work$ apt policy bwa
bwa:
  Installed: 0.7.17-1ubuntu0.1
  Candidate: 0.7.17-1ubuntu0.1
  Version table:
 *** 0.7.17-1ubuntu0.1 500
        500 http://it.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages
        100 /var/lib/dpkg/status
     0.7.17-1 500
        500 http://it.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
root@brigante:/work/local/share/bcbio/genomes/Hsapiens/hg38/bwa# ls -l
total 67583
-rw-r--r-- 1 root root        0 Mar 14 20:44 hg38.fa.alt
-rw-r--r-- 1 root root        0 Mar 14 20:36 hg38.fa.amb
-rw-r--r-- 1 root root   448319 Mar  9  2015 hg38.fa.ann
-rw-r--r-- 1 root root        0 Mar 14 20:04 hg38.fa.bwt
-rw-r--r-- 1 root root 68755820 Mar 14 20:43 hg38.fa.pac
-rw-r--r-- 1 root root        0 Mar 14 20:44 hg38.fa.sa

**Comment by tony-travis** [comment]
ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 515153
max locked memory       (kbytes, -l) 16384
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 515153
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by tony-travis** [comment]
Same issue if I prefix the PATH with the bcbio tools directory:
printenv PATH
/work/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
bcbio_nextgen.py ../config/NA12878-exome-methodcmp.yaml -n 8 |& tee bcbio_nextgen.log
...
[bwt_restore_bwt] Failed to allocate 18446744073709551576 bytes at bwt.c line 452: Cannot allocate memory
' returned non-zero exit status 1.

**Comment by naumenko-sa** [comment]
ok, thanks!

I'm attaching my [bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/4344560/bcbio-nextgen-commands.log) for the same project, 
if that helps you to debug the issue.

It looks like a machine specific issue, as it runs ok on the other one.

You have several bwa's on the machine, the bcbio one, and the system one. In general, we are trying to call tools installed by bcbio/conda. So you may try to find out what is the issue with your last command:

```
unset JAVA_HOME && \
/work/local/share/bcbio/galaxy/../anaconda/bin/bwa mem  \
 -c 250 -M -t 1  -R '@RG\tID:NA12878\tPL:illumina\tPU:NA12878\tSM:NA12878' \
 -v 1 /work/local/share/bcbio/genomes/Hsapiens/hg38/bwa/hg38.fa <(grabix grab /work/manager/NA12878-exome-eval/work/align_prep/NA12878-NGv3-LAB1360-A_1.fastq.gz 1 80000000) \
 <(grabix grab /work/manager/NA12878-exome-eval/work/align_prep/NA12878-NGv3-LAB1360-A_2.fastq.gz 1 80000000)  | \
 /work/local/share/bcbio/galaxy/../anaconda/bin/samtools sort -n -@ 1 -m 1G -O bam -T /work/manager/NA12878-exome-eval/work/bcbiotx/tmphu7xcuhv/NA12878-sort-1_80000000-sorttmp-namesort \
 -o /work/manager/NA12878-exome-eval/work/bcbiotx/tmphu7xcuhv/NA12878-sort-1_80000000.bam -
```
Try to run it as a pipe (you need to edit tmp file names), confirm the issue, then step by step.

S

**Comment by tony-travis** [comment]
OK, I've cloned the 'develop' branch and running the tests from there now - Previously ran them from the tests in the 'master' branch. I'll debug further when the tests complete. This machine ("brigante") has Ubuntu-MATE 18.04 LTS + med-bio from Debian-Med installed (Ubuntu version of med-bio).
Thanks for all your help and advice!
Tony.

**Comment by tony-travis** [comment]
The "bwa" tests in both the 'master' and 'develop' branches work OK with "hg19" e.g.:
[2020-03-17T14:42Z] Aligning lane 7_100326_FC6107FAAXX with bwa aligner
[2020-03-17T14:42Z] bwa mem alignment from fastq: Test1
[2020-03-17T14:42Z] [M::mem_pestat] skip orientation FF as there are not enough pairs
[2020-03-17T14:42Z] [M::mem_pestat] analyzing insert size distribution for orientation FR...
[2020-03-17T14:42Z] [M::mem_pestat] (25, 50, 75) percentile: (129, 150, 174)
[2020-03-17T14:42Z] [M::mem_pestat] low and high boundaries for computing mean and std.dev: (39, 264)
[2020-03-17T14:42Z] [M::mem_pestat] mean and std.dev: (151.44, 30.79)
[2020-03-17T14:42Z] [M::mem_pestat] low and high boundaries for proper pairs: (1, 309)
[2020-03-17T14:42Z] [M::mem_pestat] skip orientation RF as there are not enough pairs
[2020-03-17T14:42Z] [M::mem_pestat] skip orientation RR as there are not enough pairs
[2020-03-17T14:42Z] [main] Version: 0.7.17-r1188
[2020-03-17T14:42Z] [main] CMD: /work/local/share/bcbio/anaconda/bin/bwa mem -c 250 -M -t 1 -R @RG\tID:Test1\tPL:illumina\tPU:7_100326_FC6107FAAXX\tSM:Test1 -v 1 /work/local/src/bcbio/develop/tests/data/genomes/hg19/bwa/hg19.fa /dev/fd/63 /dev/fd/62
[2020-03-17T14:42Z] [main] Real time: 0.548 sec; CPU: 0.518 sec

**Comment by naumenko-sa** [comment]
https://github.com/bcbio/bcbio-nextgen/tree/develop is a stale branch, we really need to remove it.

everything is in master

`bcbio_nextgen.py upgrade -u development` - upgrades bcbio to the latest development (from the master branch)
`bcbio_nextgen.py upgrade -u stable` - upgrades bcbio to the latest stable version (currently 1.2.0)
https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#upgrade

**Comment by roryk** [comment]
Sorry about that, I nuked the old branch.

**Comment by tony-travis** [comment]
OK, I'm also downloading hg38 again, just to be sure - BTW, the instructions for the example pipeline do not explain that you have to download hg38 to run it.

**Comment by tony-travis** [comment]
Looks like we have a problem downloading hg38:
2020-03-17 19:16:43 (155 KB/s) - Connection closed at byte 75505664. Retrying.

--2020-03-17 19:16:44--  (try: 2)  http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa.pac
Connecting to ftp.1000genomes.ebi.ac.uk (ftp.1000genomes.ebi.ac.uk)|193.62.197.77|:80... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2020-03-17 19:16:44 ERROR 503: Service Unavailable.

**Comment by lbeltrame** [comment]
This unfortunately happens often: so far the only solution is to try again later (there's the same issue with the Broad Institute's FTP).

**Comment by tony-travis** [comment]
I've just removed /work/local/share/bcbio and /work/local then done a clean install, but had problems installing hg38:
root@brigante:/work/local/src/bcbio# python bcbio_nextgen_install.py /work/local/share/bcbio --tooldir=/work/local --genomes GRCh37 --genomes hg38 --aligners bwa --aligners bowtie2 |& tee bcbio_nextgen_install.log
[...]
Running GGD recipe: hg38 seq 1000g-20150219_1
Traceback (most recent call last):
  File "/work/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/work/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 107, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/work/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 370, in upgrade_bcbio_data
    args.cores, ["ggd", "s3", "raw"])
  File "/work/local/src/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 354, in install_data_local
    _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
  File "/work/local/src/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 480, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/work/local/src/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 875, in _install_with_ggd
    ggd.install_recipe(os.getcwd(), env.system_install, recipe_file, gid)
  File "/work/local/src/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"], system_install)
  File "/work/local/src/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/work/local/share/bcbio/anaconda/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/work/local/share/bcbio/anaconda/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bash', '/work/local/share/bcbio/genomes/Hsapiens/hg38/txtmp/ggd-run.sh']' returned non-zero exit status 8.
Checking required dependencies
Installing isolated base python installation
Installing bcbio-nextgen
Installing data and third party dependencies
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 288, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 45, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/work/local/share/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/work/local', '--genomes', 'GRCh37', '--genomes', 'hg38', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1

**Comment by naumenko-sa** [comment]
Hi @tony-travis !

1. Installing from root is not a good idea
2. you may try to install code first (no data), then data
3. data is a big installation. try one genome at a time
4. I clarified the default user story re data installation, to be merged soon. Thanks for your feedback!

SN

**Comment by tony-travis** [comment]
[bcbio_nextgen_install.log.zip](https://github.com/bcbio/bcbio-nextgen/files/4355918/bcbio_nextgen_install.log.zip)
> Hi @tony-travis !
> 
>     1. Installing from root is not a good idea

Hi, how do you recommend installing a shared copy of "bcbio_nextgen" for multiple users?

>     2. you may try to install code first (no data), then data
> 
>     3. Once you installed bcbio package, you should use it to install data, i.e.
>        `bcbio_nextgen.py upgrade -u skip --data --genomes hg38` not the installer script.
> 
>     4. data is a big installation. try one genome at a time

OK, I'll try again, step-by-step...

>     5. I clarified the default user story re data installation, to be merged soon. Thanks for your feedback!

Thanks for your help and advice,

  Tony.

**Comment by naumenko-sa** [comment]
> Hi, how do you recommend installing a shared copy of "bcbio_nextgen" for multiple users?
Up to you as a sysadmin: chmod, user group. bcbio is an isolated environment with hundreds of packages: its own python, R, conda. Mixing it with the system environment is calling for trouble.

**Comment by tony-travis** [comment]
Hmm... I installed it in /work/local, which is an isolated environment except for the PATH, which you recommend is prefixed by the bcbio-nextgen install directory and local tools directory. In fact, when I run bioconda for other applications, I use a 'wrapper' script so that the bioconda environment does not in any way conflict with the system files to avoid the trouble you are warning me about :-)

**Comment by tony-travis** [comment]
Something like this might be useful to isolate the "bcbio_nextgen" environment from the system:

"/usr/local/bin/bioconda"
#!/bin/bash
#@(#)bioconda3.sh  2019-02-23  A.J.Travis

#
# Wrapper for Bioconda Python environment
#

exec /bin/bash --rcfile /usr/local/bin/bioconda3.rc

"/usr/local/bin/bioconda3.rc"
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/bioconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/bioconda3/etc/profile.d/conda.sh" ]; then
        . "/opt/bioconda3/etc/profile.d/conda.sh"
    else
        export PATH="/opt/bioconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

**Comment by tony-travis** [comment]
The original issue was a missing validation file, now fixed, due to an error in the example pipeline. The BWA indexes problem is a secondary issue that only became apparent when the pipeline proceeded further: I've re-installed several times, but that did not fix the hg38 bwa problem. I'm now installing hg38 separately as Sergey suggested in the hope that will work.

**Comment by tony-travis** [comment]
Downloading an building the hg38 genome indexes separately worked on the fourth attempt!
```
manager@brigante:/work/local/share/bcbio/genomes/Hsapiens/hg38$ ls -lh bwa
total 5.3G
-rw-rw-r-- 1 bcbio bcbio 477K Mar  9  2015 hg38.fa.alt
-rw-rw-r-- 1 bcbio bcbio  20K Mar  9  2015 hg38.fa.amb
-rw-rw-r-- 1 bcbio bcbio 438K Mar  9  2015 hg38.fa.ann
-rw-rw-r-- 1 bcbio bcbio 3.0G Mar  9  2015 hg38.fa.bwt
-rw-rw-r-- 1 bcbio bcbio 768M Mar  9  2015 hg38.fa.pac
-rw-rw-r-- 1 bcbio bcbio 1.5G Mar  9  2015 hg38.fa.sa
```
The problem is that the installation script continues with zero-length or truncated files when errors occur downloading the genome files from http://ftp.1000genomes.ebi.ac.uk, which reports "Service not available" messages (presumably because the EBI service is too busy). There don't appear to be any networking issues when other sites are accessed by the install or update scripts.

**Comment by tony-travis** [comment]
The original issue of missing validation files has been resolved
