### ISSUE TITLE
CalledProcessError in test_4_cwl_rnaseq

### ISSUE THREAD

**Issue by hackdna** [bcbio/bcbio-nextgen#3148]
**Version info**
 - bcbio version (bcbio_nextgen.py --version): 1.2.0 (a0db761)
 - OS name and version: Ubuntu Bionic

**To Reproduce**
 - Exact bcbio command you have used: `py.test -p no:cacheprovider -p no:stepwise tests/bcbio_vm -v -s -m cwl_docker_rnaseq`
 - Your sample configuration file: N/A

**Observed behavior**
```
=================================== FAILURES ===================================
__________________________ TestCWL.test_4_cwl_rnaseq ___________________________

self = <test_docker.TestCWL object at 0x7f34f77cfa50>, install_test_files = None
data_dir = '/home/travis/build/bcbio/bcbio-nextgen/tests/data/automated'

    @pytest.mark.cwl
    @pytest.mark.cwl_docker_rnaseq
    def test_4_cwl_rnaseq(self, install_test_files, data_dir):
        """CWL: run a RNA-seq workflow using Docker.
        """
        with install_cwl_test_files(data_dir) as workdir:
            with utils.chdir(os.path.join(workdir, "rnaseq")):
                cl = ["bash", "./run_generate_cwl.sh"]
                if os.path.exists("cromwell_work"):
                    shutil.rmtree("cromwell_work")
                cl = ["bcbio_vm.py", "cwlrun", "cromwell", "rnaseq-workflow"]
>               subprocess.check_call(cl)

tests/bcbio_vm/test_docker.py:99: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

popenargs = (['bcbio_vm.py', 'cwlrun', 'cromwell', 'rnaseq-workflow'],)
kwargs = {}, retcode = 1
cmd = ['bcbio_vm.py', 'cwlrun', 'cromwell', 'rnaseq-workflow']

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.
    
        The arguments are the same as for the call function.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['bcbio_vm.py', 'cwlrun', 'cromwell', 'rnaseq-workflow']' returned non-zero exit status 1.

../../../install/bcbio-vm/anaconda/lib/python3.7/subprocess.py:363: CalledProcessError
```

**Expected behavior**
No error

**Log files**
https://travis-ci.org/github/bcbio/bcbio-nextgen/jobs/666050606

**Additional context**
In Vagrant:
```
cd tests/data/test_bcbio_cwl-master/rnaseq
bcbio_vm.py cwlrun cromwell rnaseq-workflow
```
Relevant output:
```
[2020-03-25 11:34:00,92] [info] WorkflowManagerActor Workflow 638ba748-3d9d-4e32-a5d5-98233d140eac failed (during ExecutingWorkflowState): cromwell.backend.standard.StandardAsyncExecutionActor$$anon$2: Failed to evaluate job outputs:
Bad output 'prepare_sample.prep_rec': No output binding is defined. Are you expecting the output to be inferred from a cwl.output.json file ? If so please make sure the file was effectively created.

Workflow 638ba748-3d9d-4e32-a5d5-98233d140eac transitioned to state Failed
Failed bcbio Cromwell run
-------------------------
Failure in step: prepare_sample.0
  bcbio log file     : cromwell_work/cromwell-executions/main-rnaseq.cwl/638ba748-3d9d-4e32-a5d5-98233d140eac/call-prepare_sample/shard-0/execution/log/bcbio-nextgen-debug.log
  bcbio commands file: cromwell_work/cromwell-executions/main-rnaseq.cwl/638ba748-3d9d-4e32-a5d5-98233d140eac/call-prepare_sample/shard-0/execution/log/bcbio-nextgen-commands.log
  Cromwell directory : cromwell_work/cromwell-executions/main-rnaseq.cwl/638ba748-3d9d-4e32-a5d5-98233d140eac/call-prepare_sample/shard-0
```

**Comment by hackdna** [comment]
From https://travis-ci.org/github/bcbio/bcbio-nextgen/builds/669738471:
```
cat $HOME/build/bcbio/bcbio-nextgen/tests/data/test_bcbio_cwl-master/rnaseq/cromwell_work/cromwell-executions/main-rnaseq.cwl/*/call-prepare_sample/shard-0/execution/stderr.background
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 34, in <module>
    from bcbio.setpath import prepend_bcbiopath
ModuleNotFoundError: No module named 'bcbio'
ln: failed to access '/cromwell-executions/main-rnaseq.cwl/7b678c91-dac5-4c66-95f4-74cd6fa9a675/call-prepare_sample/shard-0/execution/cwl.output.json': No such file or directory
```

**Comment by hackdna** [comment]
This test error is also reproducible in Vagrant. However:
```
vagrant@bcbio:~$ docker run -i -t quay.io/bcbio/bcbio-rnaseq /usr/local/bin/bcbio_nextgen.py --version
1.2.1
```

**Comment by hackdna** [comment]
The `docker run` command used by `bcbio_vm.py cwlrun cromwell rnaseq-workflow` refers to 
`quay.io/bcbio/bcbio-rnaseq@sha256:79bd8c658cb15642a3685cf5b6282bdc7facc6c61b8e5cb027ad5f775f5fc3dc` image version.
This reproduces the error:
```
vagrant@bcbio:~$ docker run -i -t quay.io/bcbio/bcbio-rnaseq@sha256:79bd8c658cb15642a3685cf5b6282bdc7facc6c61b8e5cb027ad5f775f5fc3dc /usr/local/bin/bcbio_nextgen.py --version
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 34, in <module>
    from bcbio.setpath import prepend_bcbiopath
ModuleNotFoundError: No module named 'bcbio'
```

**Comment by hackdna** [comment]
Also:
```
vagrant@bcbio:~$ docker run -i -t quay.io/bcbio/bcbio-rnaseq cat /usr/local/bin/bcbio_nextgen.py
#!/usr/local/share/bcbio-nextgen/anaconda/bin/python -Es
# EASY-INSTALL-SCRIPT: 'bcbio-nextgen==1.2.1','bcbio_nextgen.py'
__requires__ = 'bcbio-nextgen==1.2.1'
__import__('pkg_resources').run_script('bcbio-nextgen==1.2.1', 'bcbio_nextgen.py')
```

**Comment by hackdna** [comment]
```
vagrant@bcbio:~$ docker run -i -t quay.io/bcbio/bcbio-rnaseq@sha256:79bd8c658cb15642a3685cf5b6282bdc7facc6c61b8e5cb027ad5f775f5fc3dc /usr/local/share/bcbio-nextgen/anaconda/bin/python -c "import sys; print(sys.path)"
['', '/usr/local/share/bcbio-nextgen/anaconda/lib/python36.zip', '/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6', '/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/lib-dynload', '/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages', '/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/DNApi-1.1-py2.7.egg']

vagrant@bcbio:~$ docker run -i -t quay.io/bcbio/bcbio-rnaseq:latest /usr/local/share/bcbio-nextgen/anaconda/bin/python -c "import sys; print(sys.path)"
['', '/usr/local/share/bcbio-nextgen/anaconda/lib/python36.zip', '/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6', '/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/lib-dynload', '/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages', '/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/DNApi-1.1-py2.7.egg', '/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio_nextgen-1.2.1-py3.6.egg']
```

**Comment by roryk** [comment]
Thanks, is this all set now?

**Comment by hackdna** [comment]
Yes, looks like you've fixed it. Just need to merge #3173 to fix CWL tests in Vagrant.
