### ISSUE TITLE
Error when installing bcbio_nextgen v1.2.0

### ISSUE THREAD

**Issue by gis-nlsim** [bcbio/bcbio-nextgen#3149]
[bcbio.install.error.txt](https://github.com/bcbio/bcbio-nextgen/files/4384557/bcbio.install.error.txt)

Greetings, 
I'm encountering this error when trying to install bcbio. This happens on 2 different servers:

2020-03-26 09:30:07 (656 KB/s) - “requirements-conda.txt” saved [20/20]

Traceback (most recent call last):
  File "./bcbio_nextgen_install.py", line 301, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "./bcbio_nextgen_install.py", line 41, in main
    bcbio = install_conda_pkgs(anaconda, args)
  File "./bcbio_nextgen_install.py", line 117, in install_conda_pkgs
    channels = _get_conda_channels(conda_bin)
  File "./bcbio_nextgen_install.py", line 83, in _get_conda_channels
    config = yaml.safe_load(subprocess.check_output([conda_bin, "config", "--show"]))
  File "/mnt/projects/simngl/wgs/tools/anaconda3/lib/python3.7/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/mnt/projects/simngl/wgs/tools/anaconda3/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/mnt/projects/simngl/wgs/tools/anaconda3/lib/python3.7/site-packages/yaml/constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "/mnt/projects/simngl/wgs/tools/anaconda3/lib/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/mnt/projects/simngl/wgs/tools/anaconda3/lib/python3.7/site-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/mnt/projects/simngl/wgs/tools/anaconda3/lib/python3.7/site-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/mnt/projects/simngl/wgs/tools/anaconda3/lib/python3.7/site-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/mnt/projects/simngl/wgs/tools/anaconda3/lib/python3.7/site-packages/yaml/scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "/mnt/projects/simngl/wgs/tools/anaconda3/lib/python3.7/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/mnt/projects/simngl/wgs/tools/anaconda3/lib/python3.7/site-packages/yaml/scanner.py", line 579, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<byte string>", line 19, column 15:
            GitHub:  https://github.com/QuantStack ...

**Comment by roryk** [comment]
Thanks, sorry about that. I've been trying to speed up our installation in a few places and I broke it here. I think it should work now if you re-download the bcbio_nextgen_install.py script.

**Comment by gis-nlsim** [comment]
Thanks Dr. Kirchner, I’ve re-downloaded the bcbio_nextgen_install.py, but now it’s given me the following error:

PackagesNotFoundError: The following packages are not available from current channels:

  - bcbio-nextgen==1.2.1

Current channels:

  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 301, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 41, in main
    bcbio = install_conda_pkgs(anaconda, args)
  File "bcbio_nextgen_install.py", line 121, in install_conda_pkgs
    ["--file", os.path.basename(REMOTES["requirements"]), TARGETPY], env=env)
  File "/mnt/projects/simngl/wgs/tools/anaconda3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/mnt/projects/simngl/wgs/tools/bcbio/v1.2.0/anaconda/bin/conda', 'install', '--yes', '-c', 'bioconda', '-c', 'conda-forge', '--file', 'requirements-conda.txt', 'python=3.7']' retur\
ned non-zero exit status 1.

**Comment by roryk** [comment]
Thanks, sorry

**Comment by naumenko-sa** [comment]
It looks that bioconda picked bcbio1.2.1 up:
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bcbio-nextgen/meta.yaml

Thanks for testing - it is very timely, since the new release just has come out.

**Comment by roryk** [comment]
This should be fixed now, please re-open if it is broken still. Sorry for not testing better, my bad.
