### ISSUE TITLE
Fresh install with --genomes hg38 fails at  "Running GGD recipe: hg38 hapmap_snps 20160105"

### ISSUE THREAD

**Issue by erinijapranckeviciene** [bcbio/bcbio-nextgen#3165]
Hello bcbio team, 

I came across a situation a couple of times already when installing fresh v1.2.0 bcbio with hg38 genome . Looked for the filed issue on that, but was not able to find any, so I am posting it. 

Fresh install command: 

`python3 bcbio_nextgen_install.py /projects/bcbio/v1.2.0 --cores 30 --tooldir=/projects/bcbio/v1.2.0 --genomes hg38 --aligners bwa  -u stable --distribution ubuntu`

creates dbsp-153-orig.vcf.gz  and stops after this step. The log is following:

```python 
variation/dbsnp-153-orig.vcf.gz.t 100%[===========================================================>]   2.86M  2.01MB/s    in 1.4s

2020-04-03 14:08:08 (2.01 MB/s) - ‘variation/dbsnp-153-orig.vcf.gz.tbi’ saved [2998587/2998587]

Writing to .
Merging 210 temporary files
Cleaning
Done
Running GGD recipe: hg38 hapmap_snps 20160105
--2020-04-03 15:28:36--  ftp://gsapubftp-anonymous:*password*@ftp.broadinstitute.org/bundle/hg38//hapmap_3.3.hg38.vcf.gz
           => ‘variation/hapmap_3.3.vcf.gz’
Resolving ftp.broadinstitute.org (ftp.broadinstitute.org)... 69.173.70.223
Connecting to ftp.broadinstitute.org (ftp.broadinstitute.org)|69.173.70.223|:21... connected.
Logging in as gsapubftp-anonymous ...
Login incorrect.
Traceback (most recent call last):
  File "/projects/bcbio/v1.2.0/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/projects/bcbio/v1.2.0/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 107, in upgrade_bcbio
  File "/projects/bcbio/v1.2.0/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 370, in upgrade_bcbio_data
  File "/home/pipeline/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 354, in install_data_local
    _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
  File "/home/pipeline/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 480, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/home/pipeline/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 875, in _install_with_ggd
    ggd.install_recipe(os.getcwd(), env.system_install, recipe_file, gid)
  File "/home/pipeline/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"], system_install)
  File "/home/pipeline/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/projects/bcbio/v1.2.0/anaconda/lib/python3.7/subprocess.py", line 411, in check_output
  File "/projects/bcbio/v1.2.0/anaconda/lib/python3.7/subprocess.py", line 512, in run
subprocess.CalledProcessError: Command '['bash', '/projects/bcbio/v1.2.0/genomes/Hsapiens/hg38/txtmp/ggd-run.sh']' returned non-zero exit status 6.
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 301, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 47, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/projects/bcbio/v1.2.0/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--cores', '30', '--tooldir=/projects/bcbio/v1.2.0', '--genomes', 'hg38', '--aligners', 'bwa', '-u', 'stable', '--distribution', 'ubuntu', '--data']' returned non-zero exit status 1.
```

If I restart it will continue, but the hapmap_3.3.hg38.vcf.gz  will be left empty. 

Many thanks in advance for looking into it !

**Comment by chapmanb** [comment]
Erinija;
Sorry about the issue. This problem with the Broad ftp server is unfortunately common and due to it being overwhelmed with requests. It'll report these type of errors when there are too many connections. The best approach is just to restart your install, using the same command. It'll pick up where it left off and hopefully the FTP server will be happier and less busy. Sorry to not have a better solution but hope this gets bcbio installed for you.

**Comment by erinijapranckeviciene** [comment]
Thank you, Brad. I already did as you suggested. Just one more question before closing. The files from Broad that bcbio installs for hg38 and hg38-noalt genomes - specifically hapmap_3.3.vcf.gz - are these files the same for both genomes? Many thanks in advance !

**Comment by chapmanb** [comment]
Erinija;
Great, glad to hear the restart worked for you. Yes, those files are the same for both genomes. In general we recommend using hg38 rather than the `noalt` version as the alts can be a big advantage for many applications and `noalt` hasn't gotten the level of testing and integration. Hope this helps and thanks again for working through the install process.

**Comment by erinijapranckeviciene** [comment]
Thank you for your answer and comment. Much appreciated.
