### ISSUE TITLE
OSError: [Errno 40] Too many levels of symbolic links

### ISSUE THREAD

**Issue by gis-nlsim** [bcbio/bcbio-nextgen#3167]
**Version info**
 - bcbio version v1.2.0
 - OS name and version: RedHat 6.10 (Santiago)

**To Reproduce**
 - Run bcbio_nextgen.py on mouse with mm10 reference genome.

**Observed behavior**
bcbio failed due to too many symbolic links

Traceback (most recent call last):
  File "/home/projects/xxx/tools/bcbio/v1.2.0/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/home/projects/xxx/tools/bcbio/v1.2.0/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/project/xxx/tools/bcbio/v1.2.0/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/home/project/xxx/tools/bcbio/v1.2.0/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/project/xxx/tools/bcbio/v1.2.0/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 154, in variant2pipeline
    samples = genotype.parallel_variantcall_region(samples, run_parallel)
  File "/home/project/xxx/tools/bcbio/v1.2.0/anaconda/lib/python3.6/site-packages/bcbio/variation/genotype.py", line 208, in parallel_variantcall_region
    "vrn_file", ["region", "sam_ref", "config"]))
  File "/home/project/xxx/tools/bcbio/v1.2.0/anaconda/lib/python3.6/site-packages/bcbio/distributed/split.py", line 35, in grouped_parallel_split_combine
    final_output = parallel_fn(parallel_name, split_args)
  File "/home/project/xxx/tools/bcbio/v1.2.0/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/project/xxx/tools/bcbio/v1.2.0/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/home/project/xxx/tools/bcbio/v1.2.0/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/project/xxx/tools/bcbio/v1.2.0/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/project/xxx/tools/bcbio/v1.2.0/anaconda/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
**OSError: [Errno 40] Too many levels of symbolic links:** '/home/projects/xxx/murine/runs/SHFDT_1081/work/strelka2/chr1/SHFDT_1081-chr1_42663488_56637386.vcf.gz.tbi'

**Expected behavior**
The application should not fail due to symbolic links.

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.
[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/4436000/bcbio-nextgen-commands.log)
[bcbio-nextgen-debug-last200.log](https://github.com/bcbio/bcbio-nextgen/files/4436001/bcbio-nextgen-debug-last200.log)
[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/4436003/bcbio-nextgen.log)
[mm10.SHFDT_1081.txt](https://github.com/bcbio/bcbio-nextgen/files/4436006/mm10.SHFDT_1081.txt)

**Additional context**
None

**Comment by naumenko-sa** [comment]
Not sure, what is happening here - we have not seen a similar issue before. 

In your traceback you have bcbio1.2.0:
/home/project/xxx/tools/bcbio/v1.2.0/anaconda/lib/python3.6/s
 and in the logs it is
`/home/project/13001264/tools/bcbio/v1.1.9/anaconda/bin/freebayes`
Have you symlinked anything?

could you also post your config.yaml?
