### ISSUE TITLE
v1.2.2: Install failure due to missing mamba_bin

### ISSUE THREAD

**Issue by mjsteinbaugh** [bcbio/bcbio-nextgen#3168]
**Version info**
 - bcbio version (bcbio_nextgen.py --version): 1.2.2
 - OS name and version: Ubuntu 18 LTS

**To Reproduce**
 - Exact bcbio command you have used
 - Your sample configuration file

Using my `install-bcbio-nextgen` install script here:
https://github.com/acidgenomics/koopa/blob/master/os/linux/bin/install-bcbio-nextgen

Error log is attached.
[bcbio-nextgen-install-error.txt](https://github.com/bcbio/bcbio-nextgen/files/4440177/bcbio-nextgen-install-error.txt)

**Comment by mjsteinbaugh** [comment]
Specifically here's the traceback:

```
Traceback (most recent call last):
  File "/usr/local/opt/bcbio/1.2.2/install/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/opt/bcbio/1.2.2/install/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 70, in upgrade_bcbio
    _update_conda_packages()
  File "/usr/local/opt/bcbio/1.2.2/install/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 283, in _update_conda_packages
    if not mamba_bin:
NameError: name 'mamba_bin' is not defined
```

**Comment by mjsteinbaugh** [comment]
Hey @roryk , I just tried again tonight and I'm seeing the same error

**Comment by roryk** [comment]
Thanks, are you upgrading to the development version? I might have to push
a 1.2.3 fix for this if so, sorry about that. If you go manually edit the
change in I pushed it should fix it

**Comment by ggrimes** [comment]
I am getting a similar error when I try and install bcbio

# Input below

wget https://raw.githubusercontent.com/bcbio/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py

python bcbio_nextgen_install.py . --cores 12 --tooldir=./tools --isolate -u stable --datatarget rnaseq --genomes GRCh37 --aligners hisat2

#Error below

Installing data and third party dependencies
Upgrading bcbio
Traceback (most recent call last):
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ggrimes/bcbiotest/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ggrimes/bcbiotest/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 70, in upgrade_bcbio
    _update_conda_packages()
  File "/gpfs/igmmfs01/eddie/bioinfsvice/ggrimes/bcbiotest/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 283, in _update_conda_packages
    if not mamba_bin:
NameError: name 'mamba_bin' is not defined
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 315, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 49, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/gpfs/igmmfs01/eddie/bioinfsvice/ggrimes/bcbiotest/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--cores', '12', '--tooldir=./tools', '--isolate', '-u', 'stable', '--datatarget', 'rnaseq', '--genomes', 'GRCh37', '--aligners', 'hisat2', '--data']' returned non-zero exit status 1

**Comment by mjsteinbaugh** [comment]
@roryk I just tried installing the development version on my machine this morning and that works. I'm closing this for the time being since the issue is fixed in the current codebase. If anyone else hits this issue, wait for the v1.2.3 fix or update using the development version.

**Comment by roryk** [comment]
Thank you! I will push a new release today so other folks don't run into this. Sorry about that, thanks for following up.
