### ISSUE TITLE
v1.2.3: yaml.scanner.ScannerError

### ISSUE THREAD

**Issue by mjsteinbaugh** [bcbio/bcbio-nextgen#3185]
**Version info**
 - bcbio version (bcbio_nextgen.py --version): 1.2.3
 - OS name and version: Ubuntu 18 LTS

Clean install of stable release from bioconda is erroring out:

```
Downloading and Extracting Packages                                                                     [45/952]
bcbio-nextgen-1.2.3  | 1.6 MB    | ########## | 100%
certifi-2020.4.5.1   | 151 KB    | ########## | 100%
python-3.6.10        | 34.1 MB   | ########## | 100%
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Upgrading bcbio
Traceback (most recent call last):
  File "/usr/local/opt/bcbio/1.2.3/install/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/opt/bcbio/1.2.3/install/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 70, in u
pgrade_bcbio
    _update_conda_packages()
  File "/usr/local/opt/bcbio/1.2.3/install/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 285, in
_update_conda_packages
    channels = _get_conda_channels(conda_bin)
  File "/usr/local/opt/bcbio/1.2.3/install/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 268, in
_get_conda_channels
    config = yaml.safe_load(subprocess.check_output([conda_bin, "config", "--show"]))
  File "/usr/local/opt/bcbio/1.2.3/install/anaconda/lib/python3.6/site-packages/yaml/__init__.py", line 162, in
safe_load
    return load(stream, SafeLoader)
  File "/usr/local/opt/bcbio/1.2.3/install/anaconda/lib/python3.6/site-packages/yaml/__init__.py", line 114, in
load
    return loader.get_single_data()
  File "/usr/local/opt/bcbio/1.2.3/install/anaconda/lib/python3.6/site-packages/yaml/constructor.py", line 49, i
n get_single_data
    node = self.get_single_node()
  File "/usr/local/opt/bcbio/1.2.3/install/anaconda/lib/python3.6/site-packages/yaml/composer.py", line 36, in g
et_single_node
    document = self.compose_document()
  File "/usr/local/opt/bcbio/1.2.3/install/anaconda/lib/python3.6/site-packages/yaml/composer.py", line 58, in c
ompose_document
    self.get_event()
  File "/usr/local/opt/bcbio/1.2.3/install/anaconda/lib/python3.6/site-packages/yaml/parser.py", line 118, in ge
t_event
    self.current_event = self.state()
  File "/usr/local/opt/bcbio/1.2.3/install/anaconda/lib/python3.6/site-packages/yaml/parser.py", line 193, in pa
rse_document_end
    token = self.peek_token()
  File "/usr/local/opt/bcbio/1.2.3/install/anaconda/lib/python3.6/site-packages/yaml/scanner.py", line 129, in p
eek_token
    self.fetch_more_tokens()
  File "/usr/local/opt/bcbio/1.2.3/install/anaconda/lib/python3.6/site-packages/yaml/scanner.py", line 223, in f
etch_more_tokens
    return self.fetch_value()
  File "/usr/local/opt/bcbio/1.2.3/install/anaconda/lib/python3.6/site-packages/yaml/scanner.py", line 579, in f
etch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<byte string>", line 19, column 15:
            GitHub:  https://github.com/QuantStack ...
                  ^
Checking required dependencies
Installing isolated base python installation
Installing mamba
Installing conda-build
Installing bcbio-nextgen
Installing data and third party dependencies
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 315, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 49, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/local/cellar/python/3.8.2/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/opt/bcbio/1.2.3/install/anaconda/bin/bcbio_nextgen.py', 'up
grade', '--tooldir=/usr/local/opt/bcbio/1.2.3/tools', '--upgrade=stable', '--datatarget=rnaseq', '--datatarget=v
ariation', '--isolate']' returned non-zero exit status 1.
```

Seems like `scanner.py` needs a fix

**Comment by naumenko-sa** [comment]
Hi @mjsteinbaugh !

It looks similar to https://github.com/bcbio/bcbio-nextgen/issues/3180
let us chase it there.

Sergey

**Comment by mjsteinbaugh** [comment]
Good catch! Thanks @naumenko-sa
