### ISSUE TITLE
make deep variant work in bcbio

### ISSUE THREAD

**Issue by kokyriakidis** [bcbio/bcbio-nextgen#3187]
**Version info**
 - bcbio version (bcbio_nextgen.py --version): 1.2.3
 - OS name and version: Ubuntu 19.10

**To Reproduce**
bcbio_nextgen.py upgrade -u development --tools --data

**Observed behavior**
```
Looking for: ['python 3.6.*', 'age-metasv', 'anaconda-client', 'arriba', 'ataqv', 'awscli', 'bamtools 2.4.0.*', 'bamutil', 'bbmap', 'bcbio-prioritize', 'bcbio-variation', 'bcbio-variation-recall', 'bcftools', 'bedtools 2.27.1.*', 'bio-vcf', 'biobambam', 'bioconductor-annotate', 'bioconductor-apeglm', 'bioconductor-biocgenerics', 'bioconductor-biocinstaller', 'bioconductor-biocstyle', 'bioconductor-biostrings', 'bioconductor-biovizbase', 'bioconductor-bsgenome.hsapiens.ucsc.hg19', 'bioconductor-bsgenome.hsapiens.ucsc.hg38', 'bioconductor-bubbletree', 'bioconductor-cn.mops', 'bioconductor-copynumber', 'bioconductor-degreport', 'bioconductor-deseq2', 'bioconductor-dexseq', 'bioconductor-dnacopy', 'bioconductor-genomeinfodbdata', 'bioconductor-genomicranges', 'bioconductor-iranges', 'bioconductor-limma', 'bioconductor-rtracklayer', 'bioconductor-snpchip', 'bioconductor-titancna', 'bioconductor-vsn >=3.50.0', 'bowtie', 'bowtie2', 'break-point-inspector', 'bwa', 'bwakit', 'bzip2', 'cage', 'cancerit-allelecount', 'chipseq-greylist', 'cnvkit', 'coincbc', 'cramtools', 'cufflinks', 'cyvcf2', 'deeptools', 'delly', 'duphold', 'ensembl-vep 99.*', 'express', 'extract-sv-reads', 'fastp', 'fastqc >=0.11.8 1', 'fgbio', 'freebayes 1.1.0.46.*', 'gatk', 'gatk4', 'geneimpacts', 'genesplicer', 'gffcompare', 'goleft', 'grabix', 'gridss', 'gsort', 'gvcfgenotyper', 'h5py', 'hmftools-amber', 'hmftools-cobalt', 'hmftools-purple', 'hmmlearn', 'hts-nim-tools', 'htslib', 'impute2', 'kallisto >=0.43.1', 'kraken', 'ldc >=1.13.0', 'lofreq', 'macs2', 'maxentscan', 'mbuffer', 'minimap2', 'mintmap', 'mirdeep2 2.0.0.7.*', 'mirtop', 'moreutils', 'multiqc', 'multiqc-bcbio', 'ncurses', 'ngs-disambiguate', 'nodejs', 'novoalign', 'octopus >=0.5.1b', 'oncofuse', 'p7zip', 'parallel', 'pbgzip', 'perl-app-cpanminus', 'perl-archive-extract', 'perl-archive-zip', 'perl-bio-db-sam', 'perl-cgi', 'perl-dbi', 'perl-encode-locale', 'perl-file-fetch', 'perl-file-sharedir', 'perl-file-sharedir-install', 'perl-ipc-system-simple', 'perl-lwp-protocol-https', 'perl-lwp-simple', 'perl-sanger-cgp-battenberg', 'perl-statistics-descriptive', 'perl-time-hires', 'perl-vcftools-vcf', 'picard', 'pindel', 'pizzly', 'pyloh', 'pysam >=0.14.0', 'pythonpy', 'qsignature', 'qualimap', 'r-base', 'r-basejump 0.7.2.*', 'r-bcbiornaseq >=0.2.7', 'r-cghflasso', 'r-chbutils', 'r-devtools', 'r-dplyr', 'r-dt', 'r-ggdendro', 'r-ggplot2', 'r-ggrepel >=0.7', 'r-gplots', 'r-gsalib', 'r-knitr', 'r-pheatmap', 'r-plyr', 'r-pscbs', 'r-reshape', 'r-rmarkdown', 'r-rsqlite', 'r-sleuth', 'r-snow', 'r-stringi', 'r-viridis >=0.5', 'r-wasabi', 'r 3.5.1.*', 'rapmap', 'razers3 3.5.0.*', 'readline', 'rtg-tools', 's3gof3r', 'sailfish', 'salmon', 'sambamba', 'samblaster', 'samtools', 'scalpel', 'seq2c <2016', 'seqbuster', 'seqcluster', 'seqtk', 'sickle-trim', 'simple_sv_annotation', 'singlecell-barcodes', 'snap-aligner 1.0dev.97.*', 'snpeff 4.3.1t.*', 'solvebio', 'spades', 'staden_io_lib', 'star 2.6.1d.*', 'stringtie', 'subread', 'survivor', 'tdrmapper', 'tophat-recondition', 'trim-galore 0.6.2.*', 'ucsc-bedgraphtobigwig', 'ucsc-bedtobigbed', 'ucsc-bigbedinfo', 'ucsc-bigbedsummary', 'ucsc-bigbedtobed', 'ucsc-bigwiginfo', 'ucsc-bigwigsummary', 'ucsc-bigwigtobedgraph', 'ucsc-bigwigtowig', 'ucsc-fatotwobit', 'ucsc-gtftogenepred', 'ucsc-liftover', 'ucsc-wigtobigwig', 'umis', 'vardict', 'vardict-java', 'variantbam', 'varscan', 'vcfanno', 'vcflib', 'verifybamid2', 'viennarna', 'vqsr_cnn', 'vt', 'wham', 'xorg-libxt', 'xz']

98144 packages in https://conda.anaconda.org/conda-forge/linux-64
24970 packages in https://conda.anaconda.org/conda-forge/noarch
29259 packages in https://conda.anaconda.org/bioconda/linux-64
13244 packages in https://conda.anaconda.org/bioconda/noarch
6728 packages in https://conda.anaconda.org/r/linux-64
5025 packages in https://conda.anaconda.org/r/noarch
32458 packages in https://repo.anaconda.com/pkgs/main/linux-64
1647 packages in https://repo.anaconda.com/pkgs/main/noarch
11891 packages in https://repo.anaconda.com/pkgs/r/linux-64
5025 packages in https://repo.anaconda.com/pkgs/r/noarch

# All requested packages already installed.

Traceback (most recent call last):
  File "/RED/BCBIO/TOOLS/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 91, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 528, in upgrade_thirdparty_tools
    cbl_conda.install_in(conda_bin, args.tooldir, package_yaml)
  File "/home/kokyriakidis/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 115, in install_in
    conda_pkg_list = _install_env_pkgs(env_name, env_packages, conda_bin, conda_envs, channels)
  File "/home/kokyriakidis/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 71, in _install_env_pkgs
    "{conda_bin} list --json {env_str}".format(**locals()), shell=True))
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 19 (char 19)

```

**Comment by naumenko-sa** [comment]
Hi Konstantinos @kokyriakidis!

Thanks for reporting. This update somehow works for me cleanly, 
I suspect that in your case mamba is not working and the rescue fall back to conda is not working either.

I have addressed it here: https://github.com/chapmanb/cloudbiolinux/pull/350.

Please delete your tmpbcbio-install and try again.

Sergey

**Comment by kokyriakidis** [comment]
Hi @naumenko-sa !

It seems to move further now but it stuck here:
```
# Installing into conda environment dv: deepvariant
Encountered problems while solving.
Problem: nothing provides icu 54.* needed by r-base-3.3.1-1

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/linux-64::numpy-base==1.16.6=py36h2f8d375_0
  - bioconda/linux-64::spades==3.14.0=h2d02072_0
  - conda-forge/linux-64::openmp==7.0.0=h2d50403_0

```

**Comment by naumenko-sa** [comment]
I'm glad that the original issue is solved!

Perhaps, there are some issues in your conda environments?
Any chance that you are mixing several conda instances?
We are not using R3.3.1 in bcbio,  our main r is R3.5.1 and we have R3.6 environment for PureCN.

Your install is trying to get older versions of R, numpy-base and openmp.

here are my current versions with bcbio1.2.3:
```
numpy                     1.18.1           py36h7314795_1    conda-forge
spades                    3.14.0               h2d02072_0    bioconda
openmp                    8.0.1                         0    conda-forge
r-base                    3.5.1             hea2b9be_1007    conda-forge
```
You may try to identify the package which triggers the old installs and remove it with `conda`.
or do a quick fresh install without data?

S.

**Comment by kokyriakidis** [comment]
Hi @naumenko-sa !

A fresh install solved the problem!

Sorry for being a pain in the ass about this issue but is there a way to tell deepvariant to search for tensorflow in its environment and not in others? So I dont get the following error:
```
Computer:jobs running/jobs completed/%of started jobs/Average seconds to complete
ETA: 0s Left: 1 AVG: 0.00s  local:1/0/100%/0.0s Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_8kv4n5nn/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 44, in <module>
    import tensorflow as tf
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/tensorflow/__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/tensorflow_core/__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 947, in _find_and_load_unlocked
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/tensorflow_core/python/__init__.py", line 68, in <module>
    from tensorflow.core.protobuf.meta_graph_pb2 import TensorInfo
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/tensorflow_core/core/protobuf/meta_graph_pb2.py", line 526, in <module>
    serialized_options=None, file=DESCRIPTOR),
  File "/tmp/Bazel.runfiles_8kv4n5nn/runfiles/com_google_protobuf/python/google/protobuf/descriptor.py", line 534, in __new__
    return _message.default_pool.FindFieldByName(full_name)
KeyError: "Couldn't find field tensorflow.TensorInfo.CompositeTensor.type_spec"
parallel: This job failed:
/RED/BCBIO/RESOURCES/bcbio/anaconda/bin/python /RED/BCBIO/RESOURCES/bcbio/anaconda/envs/dv/share/deepvariant-0.10.0-3/binaries/DeepVariant/0.10.0/DeepVariant-0.10.0/make_examples.zip --mode calling --ref /RED/BCBIO/RESOURCES/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa --reads /media/kokyriakidis/PRODUCTION/BCBIO_RUNS/THOMAS/work/prealign/THOMAS/THOMAS-prealign.bam --regions /media/kokyriakidis/PRODUCTION/BCBIO_RUNS/THOMAS/work/deepvariant/chrY/THOMAS-chrY_16091111_56678506-regions-nolcr.bed --examples /media/kokyriakidis/PRODUCTION/BCBIO_RUNS/THOMAS/work/bcbiotx/tmpaar7227v/THOMAS.tfrecord@1.gz --task 0
' returned non-zero exit status 1.

```

```
KeyError: "Couldn't find field tensorflow.TensorInfo.CompositeTensor.type_spec"

```

It tries to load tensoflow from the base python env
```
 File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/tensorflow/__init__.py", line 101, in <module>
```

**Comment by naumenko-sa** [comment]
Hi @kokyriakidis !

Yes, this looks wrong: deepvariant in bcbio calls make_examples.zip using default python with  pandas 0.25.3 rather than python from dv environment, which has pandas 1.0.3

Debugging more...

S

**Comment by kokyriakidis** [comment]
Hi @naumenko-sa !

Thank you for your time! I am planning to do an extensive benchmark, if it works!

KK
