### ISSUE TITLE
bcbio.pipeline.config_utils.CmdNotFound: '_get_program_cmd' 'smoove' {} None

### ISSUE THREAD

**Issue by hocinebendou** [bcbio/bcbio-nextgen#3210]
**Version info**
 - bcbio version (bcbio_nextgen.py --version): 1.2.3
 - OS name and version: Ubuntu 18.04 bionic

**To Reproduce**
 - Exact bcbio command you have used

> bcbio_nextgen.py -t local -n 20 ../config/config.yaml

 - Your sample configuration file
```
 details:
- algorithm:
    aligner: bwa
    mark_duplicates: false
    remove_lcr: true
    variantcaller:
      somatic: vardict
      germline: freebayes
    svcaller: lumpy
    effects: snpeff
    effects_transcripts: canonical_cancer
    vcfanno: somatic
  analysis: variant2
  description: normal-sample
  files: ../input/PD44692b_N_sorted.bam
  genome_build: hg38
  metadata:
    batch: bcbio
    phenotype: normal
- algorithm:
    aligner: bwa
    mark_duplicates: false
    remove_lcr: true
    variantcaller:
      somatic: vardict
      germline: freebayes
    svcaller: lumpy
    effects: snpeff
    effects_transcripts: canonical_cancer
    vcfanno: somatic
  analysis: variant2
  description: tumor-sample
  files: ../input/PD44692a_T_sorted.bam
  genome_build: hg38
  metadata:
    batch: bcbio
    phenotype: tumor
fc_date: '2020-04-29'
fc_name: oesophageal
upload:
  dir: ../final
resources:
  default:
    memory: 2G
    cores: 8
    jvm_opts: ["-Xms1000m", "-Xmx2000m"]
```

**Observed behavior**
```
[2020-05-01T17:04Z] multiprocessing: detect_sv
Traceback (most recent call last):
  File "/tools/software/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/tools/software/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 179, in variant2pipeline
    samples = structural.run(samples, run_parallel, "standard")
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/__init__.py", line 184, in run
    for xs in to_process.values()))
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1004, in __call__
    if self.dispatch_one_batch(iterator):
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 835, in dispatch_one_batch
    self._dispatch(tasks)
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 754, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 209, in apply_async
    result = ImmediateResult(func)
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 590, in __init__
    self.results = batch()
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 359, in detect_sv
    return structural.detect_sv(*args)
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/__init__.py", line 205, in detect_sv
    for svdata in caller_fn(items):
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/lumpy.py", line 175, in run
    lumpy_vcf, exclude_file = _run_smoove(full_bams, sr_bams, disc_bams, work_dir, items)
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/lumpy.py", line 57, in _run_smoove
    smoove = config_utils.get_program("smoove", data)
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/config_utils.py", line 191, in get_program
    return _get_program_cmd(name, pconfig, config, default)
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/config_utils.py", line 217, in wrap
    raise CmdNotFound(" ".join(map(repr, (fn.__name__ if six.PY3 else fn.func_name, name, pconfig, default))))
bcbio.pipeline.config_utils.CmdNotFound: '_get_program_cmd' 'smoove' {} None
```

**Expected behavior**
bcbio should find smoove executable and run it as a command line. 

**Log files**
NA

**Additional context**
NA

**Comment by naumenko-sa** [comment]
Hi @hocinebendou !

Thanks for reporting!

Have you installed bcbio tools? 
Do you see smoove in the path? `which smoove`
Do you see smoove in conda?
`
conda list -n python2 | grep smoove
smoove                    0.2.5                         0    bioconda
`

Sergey

**Comment by hocinebendou** [comment]
Thanks Sergey,

I do see smoove in the conda list, but not with `which smoove`. If it is installed then bcbio should find it?

**Comment by pvanheus** [comment]
Hi @naumenko-sa 

I did the installation that @hocinebendou  is using. I did the install as per https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html. Specifically for our setup:

`python bcbio_nextgen_install.py --genomes hg38 --aligners bwa --aligners hisat2 --aligners minimap2 --cores ${SLURM_CPUS_PER_TASK:-1} --tooldir=/tools/software/bcbio_tools --isolate /tools/software/bcbio`

Then when Hocine hit that error I follow the recommendation to update here: https://github.com/bcbio/bcbio-nextgen/issues/2899

and then the error message changed from:

```
subprocess.CalledProcessError: Command 'set -o pipefail; export TMPDIR=/usr/people/hbendou/uct/bcbio/PD44692/work/bcbiotx/tmp0m84ms4c && smoove call --processes 8 --genotype --removepr --fasta /tools/software/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa --name normal-sample-bcbio-svs --outdir /usr/people/hbendou/uct/bcbio/PD44692/work/bcbiotx/tmp0m84ms4c --exclude /usr/people/hbendou/uct/bcbio/PD44692/work/structural/tumor-sample/lumpy/normal-sample-bcbio-svs-smoove.genotyped-exclude.bed --excludechroms '~^GL,~^HLA,~_random,~^chrUn,~alt,~decoy,chrEBV' /usr/people/hbendou/uct/bcbio/PD44692/work/align/normal-sample/normal-sample-sort.bam /usr/people/hbendou/uct/bcbio/PD44692/work/align/tumor-sample/tumor-sample-sort.bam
/bin/bash: smoove: command not found
```
to the one currently reported. Based on this latest error I tried the suggestion in https://github.com/bcbio/bcbio-nextgen/issues/902

but the error persists.

**Comment by naumenko-sa** [comment]
Hi @hocinebendou and @pvanheus !

smoove is in bcbio_tools/bin, try to add it to PATH
```
export PATH=/tools/software/bcbio_tools/bin:$PATH
```

S

**Comment by hocinebendou** [comment]
Hi @naumenko-sa 

Indeed it is. @pvanheus also suggested to add `export  PATH=/tools/software/bcbio_tools/bin:$PATH` in my scripts. The execution ended without errors. 

It would be great if PATH is updated during bcbio installation. 

Thanks Sergey and Peter.

**Comment by roryk** [comment]
Hi everyone,

Glad you got it all straightened out. The `--isolate` flag in the installation is what is causing it not to be added to the PATH, by default it will get added. See https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#automated for a more in depth description. Thanks all!

**Comment by pvanheus** [comment]
Thanks @roryk. So with `--isolate` you need to add both the path the bcbio/bin and the path to bcbio_tools/bin to the PATH?

BTW `--isolate` was used because this is installed as one user  but used by many users.

**Comment by roryk** [comment]
Hi @pvanheus,

Great, that's how we do our multi-user installs too. That's right, you need to add both of them to your PATH.

**Comment by DiyaVaka** [comment]
Hi,

I added it to my path and still it fails

Traceback (most recent call last):
  File "/mnt/speed/qc/sequencing/softwares/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/mnt/speed/qc/sequencing/softwares/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/mnt/speed/yup_temp/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/mnt/speed/yup_temp/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/mnt/speed/yup_temp/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 179, in variant2pipeline
    samples = structural.run(samples, run_parallel, "standard")
  File "/mnt/speed/yup_temp/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/__init__.py", line 184, in run
    for xs in to_process.values()))
  File "/mnt/speed/yup_temp/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/mnt/speed/yup_temp/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/mnt/speed/yup_temp/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "/mnt/speed/yup_temp/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "/mnt/speed/yup_temp/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 765, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/mnt/speed/yup_temp/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 206, in apply_async
    result = ImmediateResult(func)
  File "/mnt/speed/yup_temp/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 570, in __init__
    self.results = batch()
  File "/mnt/speed/yup_temp/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "/mnt/speed/yup_temp/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "/mnt/speed/yup_temp/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/mnt/speed/yup_temp/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 355, in detect_sv
    return structural.detect_sv(*args)
  File "/mnt/speed/yup_temp/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/__init__.py", line 205, in detect_sv
    for svdata in caller_fn(items):
  File "/mnt/speed/yup_temp/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/lumpy.py", line 175, in run
    lumpy_vcf, exclude_file = _run_smoove(full_bams, sr_bams, disc_bams, work_dir, items)
  File "/mnt/speed/yup_temp/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/lumpy.py", line 57, in _run_smoove
    smoove = config_utils.get_program("smoove", data)
  File "/mnt/speed/yup_temp/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/config_utils.py", line 191, in get_program
    return _get_program_cmd(name, pconfig, config, default)
  File "/mnt/speed/yup_temp/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/config_utils.py", line 217, in wrap
    raise CmdNotFound(" ".join(map(repr, (fn.__name__ if six.PY3 else fn.func_name, name, pconfig, default))))
bcbio.pipeline.config_utils.CmdNotFound: '_get_program_cmd' 'smoove' {} None
[sequencing@ihgseq-headnode-1 GML3888_NTC_bcbio]$ echo $PATH
/mnt/speed/qc/sequencing/softwares/bcbio/anaconda/envs/python2/bin/smoove:/opt/sge625/sge/bin/lx24-amd64:/mnt/speed/anaconda-dev/anaconda3/condabin:/home/sequencing/bcbio/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/sequencing/bin
