### ISSUE TITLE
PureCN crash

### ISSUE THREAD

**Issue by waemm** [bcbio/bcbio-nextgen#3232]
- bcbio version 1.2.3
centos 7

I was attempting to run the workflow with PureCN. 

A few minor fixes I had to make to get to this point:

> Update cnvkit to 0.9.7beta ( see https://github.com/bcbio/bcbio-nextgen/issues/3061)
> Change permissions so PureCN.R is executable
> Install the optparse package from CRAN

After this I hit an obscure error below. (See included log files for further detail.

Any help would be appreciated! 

subprocess.CalledProcessError: Command 'set -o pipefail; export R_LIBS_USER=/shared/pipeline-user/bcbio/anaconda/envs/r36/lib/R/library && unset R_HOME && unset R_LIBS && export PATH=/shared/pipeline-user/bcbio/anaconda/envs/r36/bin:"$PATH" && PureCN.R --seed 42 --out /shared/pipeline-user/run_data/Test_exomes/Test3/Test3_step1_tumor_normal/work/bcbiotx/tmpl29a7e9e/TD1717_1-113574-A1_downsampled-purecn --rds /shared/pipeline-user/run_data/Test_exomes/Test3/Test3_step1_tumor_normal/work/bcbiotx/tmpl29a7e9e/TD1717_1-113574-A1_downsampled-purecn.rds --sampleid TD1717_1-113574-A1_downsampled --genome hg38 --vcf /shared/pipeline-user/run_data/Test_exomes/Test3/Test3_step1_tumor_normal/work/structural/TD1717_1-113574-A1_downsampled/purecn/113574-effects-annotated-damage-ann-prfilter.vcf.gz --tumor /shared/pipeline-user/run_data/Test_exomes/Test3/Test3_step1_tumor_normal/work/structural/TD1717_1-113574-A1_downsampled/purecn/cnvkit/TD1717_1-113574-A1_downsampled-normalized-stdchrs-nooverlaps.cnr --segfile /shared/pipeline-user/run_data/Test_exomes/Test3/Test3_step1_tumor_normal/work/structural/TD1717_1-113574-A1_downsampled/purecn/cnvkit/TD1717_1-113574-A1_downsampled.seg --funsegmentation Hclust --maxnonclonal 0.3
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/shared/pipeline-user/bcbio/anaconda/envs/r36/lib/R/library/stringi/libs/stringi.so':
  libicui18n.so.64: cannot open shared object file: No such file or directory
Calls: make_option ... namespaceImport -> loadNamespace -> library.dynam -> dyn.load
Execution halted

[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/4663433/bcbio-nextgen-commands.log)

[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/4663434/bcbio-nextgen.log)
n):

**Comment by naumenko-sa** [comment]
Hi Warren @waemm !

I also have this issue.
I think we are hitting https://github.com/conda-forge/r-stringi-feedstock/issues/20

Sergey

**Comment by naumenko-sa** [comment]
I was lucky to fix it with:
`conda install r-stringi -n r36 -c r --force-reinstall`
(since conda-forge package is not working, we are trying r-stringi from r channel).

**Comment by waemm** [comment]
@naumenko-sa, Thank you Sergey!! It is working now!

**Comment by waemm** [comment]
@naumenko-sa, Thank you Sergey!! I thought all my problems were solved but it is crashing at a later step, looks like another issue related to R libraries : 

[2020-05-22T08:51Z] INFO [2020-05-22 08:51:56] Fitting variants for purity 0.95, tumor ploidy 1.01 and contamination 0.01.
[2020-05-22T08:51Z] INFO [2020-05-22 08:51:59] Optimized purity: 0.95
[2020-05-22T08:51Z] INFO [2020-05-22 08:51:59] Done.
[2020-05-22T08:51Z] INFO [2020-05-22 08:51:59] ------------------------------------------------------------
[2020-05-22T08:52Z] INFO [2020-05-22 08:52:00] Generating output files...
[2020-05-22T08:52Z] WARN [2020-05-22 08:52:04] No variants to plot
[2020-05-22T08:52Z] WARN [2020-05-22 08:52:04] No variants to plot
[2020-05-22T08:52Z] WARN [2020-05-22 08:52:04] No variants to plot
[2020-05-22T08:52Z] bgzip TD1717_1-113574-A1_downsampled-purecn_loh.vcf
[2020-05-22T08:52Z] tabix index TD1717_1-113574-A1_downsampled-purecn_loh.vcf.gz
[2020-05-22T08:52Z] snpEff effects : TD1717_1-113574-A1_downsampled
[2020-05-22T08:52Z] tabix index TD1717_1-113574-A1_downsampled-purecn_loh-effects.vcf.gz
[2020-05-22T08:52Z] CNVkit segment
[2020-05-22T08:52Z] /shared/pipeline-user/scratch/cnvkit/skgenome/intersect.py:11: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
[2020-05-22T08:52Z]   from pandas.core.index import Int64Index
[2020-05-22T08:52Z] Selected test sample TD1717_23-129089-D3_downsampled and control sample TD1717_21-129089-C3_downsampled
[2020-05-22T08:53Z] Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2020-05-22T08:53Z] Loaded 10847 records; skipped: 649 somatic, 151880 depth
[2020-05-22T08:53Z] Skipping 174 additional somatic records based on T/N genotypes
[2020-05-22T08:53Z] Kept 8595 heterozygous of 10673 VCF records
[2020-05-22T08:53Z] Segmenting with method 'cbs', significance threshold 0.0001, in 1 processes
[2020-05-22T08:53Z] Smoothing overshot at 2 / 15694 indices: (-1.7759484291898027, 2.491992658587971) vs. original (-4.5650900000000005, 2.37753)
[2020-05-22T08:53Z] Traceback (most recent call last):
[2020-05-22T08:53Z]   File "/shared/pipeline-user/bcbio/anaconda/bin/cnvkit.py", line 7, in <module>
[2020-05-22T08:53Z]     exec(compile(f.read(), __file__, 'exec'))
[2020-05-22T08:53Z]   File "/shared/pipeline-user/scratch/cnvkit/cnvkit.py", line 9, in <module>
[2020-05-22T08:53Z]     args.func(args)
[2020-05-22T08:53Z]   File "/shared/pipeline-user/scratch/cnvkit/cnvlib/commands.py", line 660, in _cmd_segment
[2020-05-22T08:53Z]     smooth_cbs=args.smooth_cbs)
[2020-05-22T08:53Z]   File "/shared/pipeline-user/scratch/cnvkit/cnvlib/segmentation/__init__.py", line 64, in do_segmentation
[2020-05-22T08:53Z]     for _, ca in cnarr.by_arm())))
[2020-05-22T08:53Z]   File "/shared/pipeline-user/scratch/cnvkit/cnvlib/segmentation/__init__.py", line 89, in _ds
[2020-05-22T08:53Z]     return _do_segmentation(*args)
[2020-05-22T08:53Z]   File "/shared/pipeline-user/scratch/cnvkit/cnvlib/segmentation/__init__.py", line 161, in _do_segmentation
[2020-05-22T08:53Z]     seg_out = core.call_quiet(rscript_path, '--vanilla', script_fname)
[2020-05-22T08:53Z]   File "/shared/pipeline-user/scratch/cnvkit/cnvlib/core.py", line 32, in call_quiet
[2020-05-22T08:53Z]     % (' '.join(args), err))
[2020-05-22T08:53Z] RuntimeError: Subprocess command failed:
[2020-05-22T08:53Z] $ Rscript --vanilla /shared/pipeline-user/run_data/Test_exomes/Test3/Test3_step1_tumor_normal/work/bcbiotx/tmppqyw0r24/tmpfn4ymp7d
[2020-05-22T08:53Z] b'Error: package or namespace load failed for \xe2\x80\x98DNAcopy\xe2\x80\x99 in rbind(info, getNamespaceInfo(env, "S3methods")):\n number of columns of matrices must match (see arg 2)\nIn addition: Warning message:\npackage \xe2\x80\x98DNAcopy\xe2\x80\x99 was built under R version 3.6.1 \nExecution halted\n'
[2020-05-22T08:53Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/shared/pipeline-user/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/shared/pipeline-user/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset R_HOME && unset R_LIBS && export PATH=/shared/pipeline-user/bcbio/anaconda/bin:"$PATH" && export TMPDIR=/shared/pipeline-user/run_data/Test_exomes/Test3/Test3_step1_tumor_normal/work/bcbiotx/tmppqyw0r24 && /shared/pipeline-user/bcbio/anaconda/bin/cnvkit.py segment -p 1 -o /shared/pipeline-user/run_data/Test_exomes/Test3/Test3_step1_tumor_normal/work/bcbiotx/tmppqyw0r24/TD1717_23-129089-D3_downsampled.cns /shared/pipeline-user/run_data/Test_exomes/Test3/Test3_step1_tumor_normal/work/structural/TD1717_23-129089-D3_downsampled/bins/TD1717_23-129089-D3_downsampled-normalized.cnr --vcf /shared/pipeline-user/run_data/Test_exomes/Test3/Test3_step1_tumor_normal/work/vardict/129089-effects-annotated-damage-ann.vcf.gz --sample-id TD1717_23-129089-D3_downsampled --normal-id TD1717_21-129089-C3_downsampled --drop-low-coverage
/shared/pipeline-user/scratch/cnvkit/skgenome/intersect.py:11: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import Int64Index

**Comment by naumenko-sa** [comment]
Hi Warren @waemm !

I think it is a cnvkit issue we are chasing here:
https://github.com/bcbio/bcbio-nextgen/issues/3201

Currently, I'm trying to use gatk-cnv as input to pureCN.

Please don't close this issue though - we need to fix stringi installation issue in the bcbio install for everyone, adding r channel needs some more testing.

Sergey

**Comment by waemm** [comment]
@naumenko-sa Thanks Sergey, I am not sure if this is due to the updates to PureCN or if CNVkit is using a different version of R? 

I may try the gatk-cnv route for now, thanks again for your prompt replies and help!

**Comment by waemm** [comment]
@naumenko-sa Hi Sergey, I managed to get some test data through the PurecN workflow using gatk-cnv! I have been looking through the outputs. I see there are purecn vcfs labelled as "-purecn.vcf.gz" . These don't seem to contain any additional information from PureCN though

**Comment by waemm** [comment]
Just to be clear I think there is a bug where the **purecn.vcf.gz** files do not contain any PureCN output.

**Comment by naumenko-sa** [comment]
purecn runs fine as of bcbio1.2.9
