### ISSUE TITLE
Unrecognized option: -baf when using PURPLE

### ISSUE THREAD

**Issue by rkendar** [bcbio/bcbio-nextgen#3250]
**Version info**
 - bcbio version: 1.1.5
 - Linux version 2.6.32-279.el6.x86_64

**To Reproduce**
Command generated by bcbio:
`Command 'set -o pipefail; unset DISPLAY && PURPLE -Xms750m -Xmx21840m -XX:+UseSerialGC -Djava.io.tmpdir=/work/bcbiotx/tmpzoo_w41b -amber /work/structural/WHT158/purple/amber -baf /work/structural/WHT158/purple/amber/WHT158.amber.baf -cobalt /work/structural/WHT158/purple/cobalt -gc_profile /bcbio/genomes/Hsapiens/hg38/coverage/gc/GC_profile.1000bp.cnp -output_dir /work/bcbiotx/tmpzoo_w41b -ref_genome hg38 -run_dir /work/structural/WHT158/purple -threads 16 -tumor_sample WHT158 -ref_sample WHT157 -somatic_vcf /work/strelka2/batch1-effects-annotated.vcf.gz`

**Observed behavior**
Error message:

[2020-05-29T14:43Z] 22:43:28 - Segmentation Complete
[2020-05-29T14:43Z] 22:43:28 - Complete
[2020-05-29T14:43Z] PURPLE: purity and ploidy estimation
[2020-05-29T14:43Z] 22:43:29 - Generating windows on chromosome chr22
[2020-05-29T14:43Z] 22:43:29 - PURPLE version: 2.32
[2020-05-29T14:43Z] Exception in thread "main" org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -baf
[2020-05-29T14:43Z]     at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:347)
[2020-05-29T14:43Z]     at org.apache.commons.cli.DefaultParser.handleConcatenatedOptions(DefaultParser.java:689)
[2020-05-29T14:43Z]     at org.apache.commons.cli.DefaultParser.handleShortAndLongOption(DefaultParser.java:520)
[2020-05-29T14:43Z]     at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:243)
[2020-05-29T14:43Z]     at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120)
[2020-05-29T14:43Z]     at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
[2020-05-29T14:43Z]     at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
[2020-05-29T14:43Z]     at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.createCommandLine(PurityPloidyEstimateApplication.java:365)
[2020-05-29T14:43Z]     at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.<init>(PurityPloidyEstimateApplication.java:105)
[2020-05-29T14:43Z]     at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.main(PurityPloidyEstimateApplication.java:96)
[2020-05-29T14:43Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset DISPLAY && PURPLE -Xms750m -Xmx21840m -XX:+UseSerialGC -Djava.io.tmpdir=/work/bcbiotx/tmpzoo_w41b -amber /work/structural/WHT158/purple/amber -baf /work/structural/WHT158/purple/amber/WHT158.amber.baf -cobalt /work/structural/WHT158/purple/cobalt -gc_profile /bcbio/genomes/Hsapiens/hg38/coverage/gc/GC_profile.1000bp.cnp -output_dir /work/bcbiotx/tmpzoo_w41b -ref_genome hg38 -run_dir /work/structural/WHT158/purple -threads 16 -tumor_sample WHT158 -ref_sample WHT157 -somatic_vcf /work/strelka2/batch1-effects-annotated.vcf.gz
22:43:29 - PURPLE version: 2.32
Exception in thread "main" org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -baf
        at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:347)
        at org.apache.commons.cli.DefaultParser.handleConcatenatedOptions(DefaultParser.java:689)
        at org.apache.commons.cli.DefaultParser.handleShortAndLongOption(DefaultParser.java:520)
        at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:243)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
        at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.createCommandLine(PurityPloidyEstimateApplication.java:365)
        at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.<init>(PurityPloidyEstimateApplication.java:105)
        at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.main(PurityPloidyEstimateApplication.java:96)
' returned non-zero exit status 1.
[2020-05-29T14:43Z] 22:43:30 - Generating windows on chromosome chrX
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/bcbio/anaconda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "//bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 324, in detect_sv
    return structural.detect_sv(*args)
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/__init__.py", line 205, in detect_sv
    for svdata in caller_fn(items):
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/purple.py", line 33, in run
    purple_out = _run_purple(paired, het_file, depth_file, vrn_files, work_dir)
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/purple.py", line 76, in _run_purple
    do.run(cmd, "PURPLE: purity and ploidy estimation")
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)

Do you know why it does not recognize the -baf? I've checked bcbio PURPLE script [https://github.com/bcbio/bcbio-nextgen/blob/86edda9bedb3e90b814b0c54f3efb74fdf23aba8/bcbio/structural/purple.py](url) and actually it has -baf. I am not sure what I've done wrong. Is it because I'm using the older version of bcbio?

Thank you.

**Comment by rkendar** [comment]
Hi Bcbio team,

Is there anyone can help me with this? Thank you.

**Comment by naumenko-sa** [comment]
Hi @rkendar !

Please see this discussion: #2532

Purple is not documented and not productionalized in bcbio for now.
Still, if you want to contribute to debugging, please provide your YAML file and more details on how you are running it.

Sergey
