### ISSUE TITLE
Error while addign --aligner bbmap

### ISSUE THREAD

**Issue by kokyriakidis** [bcbio/bcbio-nextgen#3255]
I get the following memory error when trying to add bbmap aligner in the latest bcbio version

```
Moving on to next genome prep method after trying ggd
GGD recipe not available for hg19 bbmap
Downloading genome from s3: hg19 bbmap
Moving on to next genome prep method after trying s3
No pre-computed indices for hg19 bbmap
Preparing genome hg19 with index bbmap
java -ea -Xmx3g -Xms1g -cp /RED/BCBIO/RESOURCES/bcbio/anaconda/opt/bbmap-38.84-0/current/ align2.BBMap build=1 overwrite=true fastareadlen=500 -Xms1g -Xmx3g path=bbmap ref=/RED/BCBIO/RESOURCES/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa
Executing align2.BBMap [build=1, overwrite=true, fastareadlen=500, -Xms1g, -Xmx3g, path=bbmap, ref=/RED/BCBIO/RESOURCES/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa]
Version 38.84

No output file.
Writing reference.
Executing dna.FastaToChromArrays2 [/RED/BCBIO/RESOURCES/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa, 1, writeinthread=false, genscaffoldinfo=true, retain, waitforwriting=false, gz=true, maxlen=536670912, writechroms=true, minscaf=1, midpad=300, startpad=8000, stoppad=8000, nodisk=false]

Set genScaffoldInfo=true
Writing chunk 1
Writing chunk 2
Writing chunk 3
Writing chunk 4
java.lang.OutOfMemoryError: Java heap space
	at shared.KillSwitch.allocByte1D(KillSwitch.java:225)
	at dna.ChromosomeArray.resize(ChromosomeArray.java:321)
	at dna.ChromosomeArray.set(ChromosomeArray.java:174)
	at dna.ChromosomeArray.set(ChromosomeArray.java:165)
	at dna.FastaToChromArrays2.makeNextChrom(FastaToChromArrays2.java:476)
	at dna.FastaToChromArrays2.makeChroms(FastaToChromArrays2.java:344)
	at dna.FastaToChromArrays2.main2(FastaToChromArrays2.java:152)
	at align2.RefToIndex.makeIndex(RefToIndex.java:147)
	at align2.BBMap.setup(BBMap.java:280)
	at align2.AbstractMapper.<init>(AbstractMapper.java:57)
	at align2.BBMap.<init>(BBMap.java:42)
	at align2.BBMap.main(BBMap.java:30)

This program ran out of memory.
Try increasing the -Xmx flag and using tool-specific memory-related parameters.
Moving on to next genome prep method after trying raw
Command 'bbmap.sh -Xms1g -Xmx3g path=bbmap ref=/RED/BCBIO/RESOURCES/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/RED/BCBIO/TOOLS/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 107, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 359, in upgrade_bcbio_data
    args.cores, ["ggd", "s3", "raw"])
  File "/home/kokyriakidis/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 354, in install_data_local
    _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
  File "/home/kokyriakidis/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 495, in _prep_genomes
    .format(idx, gid, last_exc))
OSError: Could not prepare index bbmap for hg19 by any method
Traceback (most recent call last):
  File "/home/kokyriakidis/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 480, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/home/kokyriakidis/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 519, in _prep_raw_index
    get_index_fn(idx)(env, ref_file)
  File "/home/kokyriakidis/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 678, in _index_bbmap
    (cores, 3 * int(cores), dir_name, ref_file), shell=True)
  File "/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bbmap.sh -Xms1g -Xmx3g path=bbmap ref=/RED/BCBIO/RESOURCES/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa' returned non-zero exit status 1.

```

**Comment by roryk** [comment]
Hi Konstantinos!

Sorry about that, if you try to run `bbmap.sh -Xms1g -Xmx3g path=bbmap ref=/RED/BCBIO/RESOURCES/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa` outside of bcbio and increase the `-Xmx3g` do something like `-Xmx16g` does that fix your problem? If so I'll fix it in cloudbiolinux here: https://github.com/chapmanb/cloudbiolinux/blob/7c09ed2258b41132c31348cb3a3f7cf12c44e77a/cloudbio/biodata/genomes.py#L669-L679

**Comment by kokyriakidis** [comment]
Same!

```
kokyriakidis@Konstantinos:/media/kokyriakidis/PRODUCTION/FDA/BBTOOLS-BWA-GENCORE-DEEPVARIANT/BWA-GENCORE-DEEPVARIANT/input$ bbmap.sh -Xms1g -Xmx16g path=./bbmap ref=/RED/BCBIO/RESOURCES/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa
java -ea -Xmx16g -Xms1g -cp /RED/BCBIO/RESOURCES/bcbio/anaconda/opt/bbmap-38.84-0/current/ align2.BBMap build=1 overwrite=true fastareadlen=500 -Xms1g -Xmx16g path=./bbmap ref=/RED/BCBIO/RESOURCES/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa
Executing align2.BBMap [build=1, overwrite=true, fastareadlen=500, -Xms1g, -Xmx16g, path=./bbmap, ref=/RED/BCBIO/RESOURCES/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa]
Version 38.84

No output file.
Writing reference.
Executing dna.FastaToChromArrays2 [/RED/BCBIO/RESOURCES/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa, 1, writeinthread=false, genscaffoldinfo=true, retain, waitforwriting=false, gz=true, maxlen=536670912, writechroms=true, minscaf=1, midpad=300, startpad=8000, stoppad=8000, nodisk=false]

Set genScaffoldInfo=true
Writing chunk 1
Writing chunk 2
Writing chunk 3
Writing chunk 4
Writing chunk 5
Writing chunk 6
Writing chunk 7
Set genome to 1

Loaded Reference:	0.024 seconds.
Loading index for chunk 1-7, build 1
No index available; generating from reference genome: /media/kokyriakidis/PRODUCTION/FDA/BBTOOLS-BWA-GENCORE-DEEPVARIANT/BWA-GENCORE-DEEPVARIANT/input/./bbmap/ref/index/1/chr1-3_index_k13_c2_b1.block
No index available; generating from reference genome: /media/kokyriakidis/PRODUCTION/FDA/BBTOOLS-BWA-GENCORE-DEEPVARIANT/BWA-GENCORE-DEEPVARIANT/input/./bbmap/ref/index/1/chr4-7_index_k13_c2_b1.block
Indexing threads started for block 0-3
Indexing threads started for block 4-7
java.lang.OutOfMemoryError: Java heap space
	at shared.KillSwitch.allocInt1D(KillSwitch.java:195)
	at align2.IndexMaker4$BlockMaker$CountThread.run(IndexMaker4.java:277)

This program ran out of memory.
Try increasing the -Xmx flag and using tool-specific memory-related parameters.

```

**Comment by roryk** [comment]
Can you just keep bumping up Xmx until it doesn't run out, and then tell us what the value ended up being? :)

**Comment by kokyriakidis** [comment]
-Xmx17g worked for hg19 but fails for hg38
-Xmx18g works for both

**Comment by roryk** [comment]
Awesome, thanks-- I'll set it to something like 24G then.

**Comment by roryk** [comment]
Thanks! Should be fixed going forward now. If you delete the `tmpbcbio` directory or whatever it is called where you are trying to install and restart, you'll pull down the updated cloudbiolinux with the fix.

**Comment by kokyriakidis** [comment]
Thank you very much!

**Comment by roryk** [comment]
Thanks, please reopen if it doesn't work, I haven't tested it, just made the fix.

**Comment by kokyriakidis** [comment]
Out of memory for GRCh37 with Xmx20! Xmx21 works fine locally!

**Comment by roryk** [comment]
huh, weird

**Comment by roryk** [comment]
Ok bumped it to 24G now, thank you!

**Comment by kokyriakidis** [comment]
Is there a way to supply extra options in bbmap aligner like "slow" "-k" etc?
