### ISSUE TITLE
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Error binding parameter 123 - probably unsupported type.

### ISSUE THREAD

**Issue by hocinebendou** [bcbio/bcbio-nextgen#3256]
**Version info**
 - bcbio version (bcbio_nextgen.py --version):1.2.3
 - OS name and version: Ubuntu 18.04 bionic

**To Reproduce**
 - Exact bcbio command you have used

> bcbio_nextgen.py -t local -n 20 ../config/config.yaml

 - Your sample configuration file
```
details:
- algorithm:
    aligner: bwa
    mark_duplicates: false
    remove_lcr: true
    tools_on: gemini
    variantcaller:
      somatic: vardict
      germline: freebayes
    svcaller: lumpy
    effects: snpeff
    effects_transcripts: canonical_cancer
    vcfanno: [gemini,somatic]
  analysis: variant2
  description: normal-sample
  files: ../input/PD44692b_N_sorted.bam
  genome_build: hg38
  metadata:
    batch: bcbio
    phenotype: normal
- algorithm:
    aligner: bwa
    mark_duplicates: false
    remove_lcr: true
    tools_on: gemini
    variantcaller:
      somatic: vardict
      germline: freebayes
    svcaller: lumpy
    effects: snpeff
    effects_transcripts: canonical_cancer
    vcfanno: [gemini,somatic]
  analysis: variant2
  description: tumor-sample
  files: ../input/PD44692a_T_sorted.bam
  genome_build: hg38
  metadata:
    batch: bcbio
    phenotype: tumor
fc_date: '2020-04-29'
fc_name: oesophageal
upload:
  dir: ../final
resources:
  default:
    memory: 4G
    cores: 8
    jvm_opts: ["-Xms2000m", "-Xmx4000m"]
```

**Observed behavior**
Error message or bcbio output.

**Expected behavior**
```
Traceback (most recent call last):
  File "/tools/software/bcbio_tools/bin/vcf2db.py", line 924, in <module>
    impacts_extras=a.impacts_field, aok=a.a_ok)
  File "/tools/software/bcbio_tools/bin/vcf2db.py", line 234, in __init__
    self.load()
  File "/tools/software/bcbio_tools/bin/vcf2db.py", line 322, in load
    self._load(self.vcf, create=False, start=i+1)
  File "/tools/software/bcbio_tools/bin/vcf2db.py", line 306, in _load
    self.insert(variants, expanded, keys, i)
  File "/tools/software/bcbio_tools/bin/vcf2db.py", line 374, in insert
    vilengths, variant_impacts)
  File "/tools/software/bcbio_tools/bin/vcf2db.py", line 402, in _insert
    self.__insert(v_objs, self.metadata.tables['variants'].insert())
  File "/tools/software/bcbio_tools/bin/vcf2db.py", line 436, in __insert
    raise e
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Error binding parameter 123 - probably unsupported type.
[SQL: INSERT INTO variants (variant_id, chrom, start, "end", vcf_id, ref, alt, qual, filter, type, sub_type, call_rate, num_hom_ref, num_het, num_hom_alt, num_unknown, aaf, gene, ensembl_gene_id, transcript, is_exonic, is_coding, is_lof, is_splicing, is_canonical, exon, codon_change, aa_change, aa_length, biotype, impact, impact_so, impact_severity, polyphen_pred, polyphen_score, sift_pred, sift_score, ab, abp, ac, af, an, ao, cigar, db, decomposed, dp, dpb, dpra, epp, eppr, gti, len, lof, meanalt, mqm, mqmr, ns, numalt, odds, old_multiallelic, old_variant, paired, pairedr, pao, pqa, pqr, pro, qa, qr, ro, rpl, rpp, rppr, rpr, run, saf, sap, sar, srf, srp, srr, ac_adj_exac_afr, ac_adj_exac_amr, ac_adj_exac_eas, ac_adj_exac_fin, ac_adj_exac_nfe, ac_adj_exac_oth, ac_adj_exac_sas, ac_exac_all, af_adj_exac_afr, af_adj_exac_amr, af_adj_exac_eas, af_adj_exac_fin, af_adj_exac_nfe, af_adj_exac_oth, af_adj_exac_sas, af_esp_aa, af_esp_all, af_esp_ea, af_exac_all, an_adj_exac_afr, an_adj_exac_amr, an_adj_exac_eas, an_adj_exac_fin, an_adj_exac_nfe, an_adj_exac_oth, an_adj_exac_sas, an_exac_all, clinvar_disease_name, clinvar_sig, common_pathogenic, gnomad_ac, gnomad_af, gnomad_af_afr, gnomad_af_amr, gnomad_af_asj, gnomad_af_eas, gnomad_af_fin, gnomad_af_nfe, gnomad_af_oth, gnomad_af_popmax, gnomad_af_sas, gnomad_an, max_aaf_all, num_exac_het, num_exac_hom, rs_ids, gts, gt_types, gt_phases, gt_depths, gt_ref_depths, gt_alt_depths, gt_quals, gt_alt_freqs) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (25566, u'chr1', 12827540, 12827541, u'rs182233185', u'G', u'A', 306.29998779296875, None, 'snp', 'ts', 1.0, 0, 1, 0, 0, 0.5, u'PRAMEF11', None, u'ENST00000619922.1', 1, 1, 0, 0, 0, u'3/4', u'c.583C>T', u'p.Arg195Cys', 478, u'protein_coding', u'missense_variant', u'missense_variant', 'MED', None, None, None, None, 0.33333298563957214, 15.315299987792969, 1, 0.5, 2, 17, u'1X', 1, 0, 51, 51.0, 0.0, 6.203639984130859, 7.097780227661133, 0, 1, 'None', 1.0, 45.76470184326172, 44.82350158691406, 1, 1, 70.51809692382812, None, 'None', 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 659, 1285, 34, 10.0, 4.159900188446045, 5.309510231018066, 7.0, 1, 7, 4.159900188446045, 10, 13, 7.097780227661133, 21, 504.0, 26.0, 0.0, 0.0, 4.0, 3.0, 0.0, 537.0, 0.057500001043081284, 0.002267200034111738, 0.0, 0.0, 6.263500108616427e-05, 0.0033859999384731054, 0.0, -1.0, -1.0, -1.0, 0.004611399956047535, 8762.0, 11468.0, 8454.0, 6592.0, 63862.0, 886.0, 16426.0, 116450.0, None, None, 0, 3, 0.00031895001302473247, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, (246644, 9406), 0.057500001043081284, 483.0, 27.0, u'rs182233185', <read-only buffer for 0x7fa46b128fc0, size -1, offset 0 at 0x7fa4637f17f0>, <read-only buffer for 0x7fa46b128f90, size -1, offset 0 at 0x7fa4637f1830>, <read-only buffer for 0x7fa46b12b030, size -1, offset 0 at 0x7fa4637f1870>, <read-only buffer for 0x7fa46b12b060, size -1, offset 0 at 0x7fa4637f18b0>, <read-only buffer for 0x7fa46b12b090, size -1, offset 0 at 0x7fa4637f18f0>, <read-only buffer for 0x7fa46b12b0c0, size -1, offset 0 at 0x7fa4637f1930>, <read-only buffer for 0x7fa46b12b0f0, size -1, offset 0 at 0x7fa4637f1970>, <read-only buffer for 0x7fa46b12b120, size -1, offset 0 at 0x7fa4637f19b0>)]
(Background on this error at: http://sqlalche.me/e/rvf5)
' returned non-zero exit status 1.
```

**Log files**
NA

**Additional context**
NA

**Comment by naumenko-sa** [comment]
Hi @hocinebendou!

We had a similar issue before #3087 

I think here the problematic gnomad_exome.vcf.gz record is:
`gnomad_an = (246644, 9406)` at `chr1:12827541`

If you re-install your `hg38/variation/gnomad_exome.vcf.gz`, that might help to solve the issue.
To re-install:
1. Delete gnomad_exome record from `hg38/versions.csv`
2. run `bcbio_nextgen.py upgrade -u skip --genomes hg38 --datatarget gemini`

In my updated installation this particular variant is decomposed:
```
tabix gnomad_exome.vcf.gz chr1:12827541-12827542 | grep "AN="
chr1	12827541	rs1198360404	G	A	1087.49	PASS	AC=3;AC_afr=0;AC_afr_female=0;AC_afr_male=0;AC_amr=1;AC_amr_female=1;AC_amr_male=0;AC_asj=0;AC_asj_female=0;AC_asj_male=0;AC_eas=0;AC_eas_female=0;AC_eas_jpn=0;AC_eas_kor=0;AC_eas_male=0;AC_eas_oea=0;AC_female=1;AC_fin=0;AC_fin_female=0;AC_fin_male=0;AC_male=2;AC_nfe=2;AC_nfe_bgr=0;AC_nfe_est=0;AC_nfe_female=0;AC_nfe_male=2;AC_nfe_nwe=2;AC_nfe_onf=0;AC_nfe_seu=0;AC_nfe_swe=0;AC_oth=0;AC_oth_female=0;AC_oth_male=0;AC_popmax=1;AC_raw=6;AC_sas=0;AC_sas_female=0;AC_sas_male=0;AF=0.000318945;AF_afr=0;AF_afr_female=0;AF_afr_male=0;AF_amr=0.000625;AF_amr_female=0.00125628;AF_amr_male=0;AF_asj=0;AF_asj_female=0;AF_asj_male=0;AF_eas=0;AF_eas_female=0;AF_eas_kor=0;AF_eas_male=0;AF_eas_oea=0;AF_female=0.000234852;AF_fin=0;AF_fin_female=0;AF_fin_male=0;AF_male=0.0003885;AF_nfe=0.000509684;AF_nfe_est=0;AF_nfe_female=0;AF_nfe_male=0.000938967;AF_nfe_nwe=0.000609756;AF_nfe_onf=0;AF_oth=0;AF_oth_female=0;AF_oth_male=0;AF_popmax=0.000625;AF_raw=0.000102941;AF_sas=0;AF_sas_female=0;AF_sas_male=0;AN=9406;AN_afr=952;AN_afr_female=528;AN_afr_male=424;AN_amr=1600;AN_amr_female=796;AN_amr_male=804;AN_asj=228;AN_asj_female=156;AN_asj_male=72;AN_eas=866;AN_eas_female=404;AN_eas_jpn=0;AN_eas_kor=334;AN_eas_male=462;AN_eas_oea=532;AN_female=4258;AN_fin=108;AN_fin_female=34;AN_fin_male=74;AN_male=5148;AN_nfe=3924;AN_nfe_bgr=0;AN_nfe_est=6;AN_nfe_female=1794;AN_nfe_male=2130;AN_nfe_nwe=3280;AN_nfe_onf=638;AN_nfe_seu=0;AN_nfe_swe=0;AN_oth=368;AN_oth_female=154;AN_oth_male=214;AN_popmax=1600;AN_raw=58286;AN_sas=1360;AN_sas_female=392;AN_sas_male=968;BaseQRankSum=1.95;ClippingRankSum=0.406;DP=416844;FS=0;InbreedingCoeff=-0.0337;MQ=22.92;MQRankSum=-0.323;QD=8.06;ReadPosRankSum=0.406;SOR=0.707;allele_type=snv;faf95=8.604e-05;faf99=8.623e-05;n_alt_alleles=1;nhomalt=0;nhomalt_afr=0;nhomalt_afr_female=0;nhomalt_afr_male=0;nhomalt_amr=0;nhomalt_amr_female=0;nhomalt_amr_male=0;nhomalt_asj=0;nhomalt_asj_female=0;nhomalt_asj_male=0;nhomalt_eas=0;nhomalt_eas_female=0;nhomalt_eas_jpn=0;nhomalt_eas_kor=0;nhomalt_eas_male=0;nhomalt_eas_oea=0;nhomalt_female=0;nhomalt_fin=0;nhomalt_fin_female=0;nhomalt_fin_male=0;nhomalt_male=0;nhomalt_nfe=0;nhomalt_nfe_bgr=0;nhomalt_nfe_est=0;nhomalt_nfe_female=0;nhomalt_nfe_male=0;nhomalt_nfe_nwe=0;nhomalt_nfe_onf=0;nhomalt_nfe_seu=0;nhomalt_nfe_swe=0;nhomalt_oth=0;nhomalt_oth_female=0;nhomalt_oth_male=0;nhomalt_popmax=0;nhomalt_raw=0;nhomalt_sas=0;nhomalt_sas_female=0;nhomalt_sas_male=0;popmax=amr;variant_type=snv
chr1	12827541	rs182233185	G	C	3.34571e+06	PASS	AC=1;AC_afr=0;AC_afr_female=0;AC_afr_male=0;AC_amr=0;AC_amr_female=0;AC_amr_male=0;AC_asj=0;AC_asj_female=0;AC_asj_male=0;AC_eas=0;AC_eas_female=0;AC_eas_jpn=0;AC_eas_kor=0;AC_eas_male=0;AC_eas_oea=0;AC_female=0;AC_fin=0;AC_fin_female=0;AC_fin_male=0;AC_male=1;AC_nfe=0;AC_nfe_bgr=0;AC_nfe_est=0;AC_nfe_female=0;AC_nfe_male=0;AC_nfe_nwe=0;AC_nfe_onf=0;AC_nfe_seu=0;AC_nfe_swe=0;AC_oth=0;AC_oth_female=0;AC_oth_male=0;AC_popmax=1;AC_raw=1;AC_sas=1;AC_sas_female=0;AC_sas_male=1;AF=4.05443e-06;AF_afr=0;AF_afr_female=0;AF_afr_male=0;AF_amr=0;AF_amr_female=0;AF_amr_male=0;AF_asj=0;AF_asj_female=0;AF_asj_male=0;AF_eas=0;AF_eas_female=0;AF_eas_jpn=0;AF_eas_kor=0;AF_eas_male=0;AF_eas_oea=0;AF_female=0;AF_fin=0;AF_fin_female=0;AF_fin_male=0;AF_male=7.45179e-06;AF_nfe=0;AF_nfe_bgr=0;AF_nfe_est=0;AF_nfe_female=0;AF_nfe_male=0;AF_nfe_nwe=0;AF_nfe_onf=0;AF_nfe_seu=0;AF_nfe_swe=0;AF_oth=0;AF_oth_female=0;AF_oth_male=0;AF_popmax=3.27718e-05;AF_raw=3.9946e-06;AF_sas=3.27718e-05;AF_sas_female=0;AF_sas_male=4.34934e-05;AN=246644;AN_afr=14778;AN_afr_female=8868;AN_afr_male=5910;AN_amr=34480;AN_amr_female=20208;AN_amr_male=14272;AN_asj=9962;AN_asj_female=4840;AN_asj_male=5122;AN_eas=18258;AN_eas_female=9252;AN_eas_jpn=130;AN_eas_kor=3812;AN_eas_male=9006;AN_eas_oea=14316;AN_female=112448;AN_fin=21162;AN_fin_female=10098;AN_fin_male=11064;AN_male=134196;AN_nfe=111446;AN_nfe_bgr=2516;AN_nfe_est=228;AN_nfe_female=48800;AN_nfe_male=62646;AN_nfe_nwe=41230;AN_nfe_onf=30100;AN_nfe_seu=11352;AN_nfe_swe=26020;AN_oth=6044;AN_oth_female=2860;AN_oth_male=3184;AN_popmax=30514;AN_raw=250338;AN_sas=30514;AN_sas_female=7522;AN_sas_male=22992;BaseQRankSum=4.83;ClippingRankSum=0.158;DP=19795847;FS=1.102;InbreedingCoeff=0.0793;MQ=35.75;MQRankSum=0.603;QD=13.27;ReadPosRankSum=0.241;SOR=0.58;allele_type=snv;faf95=0;faf99=0;n_alt_alleles=2;nhomalt=0;nhomalt_afr=0;nhomalt_afr_female=0;nhomalt_afr_male=0;nhomalt_amr=0;nhomalt_amr_female=0;nhomalt_amr_male=0;nhomalt_asj=0;nhomalt_asj_female=0;nhomalt_asj_male=0;nhomalt_eas=0;nhomalt_eas_female=0;nhomalt_eas_jpn=0;nhomalt_eas_kor=0;nhomalt_eas_male=0;nhomalt_eas_oea=0;nhomalt_female=0;nhomalt_fin=0;nhomalt_fin_female=0;nhomalt_fin_male=0;nhomalt_male=0;nhomalt_nfe=0;nhomalt_nfe_bgr=0;nhomalt_nfe_est=0;nhomalt_nfe_female=0;nhomalt_nfe_male=0;nhomalt_nfe_nwe=0;nhomalt_nfe_onf=0;nhomalt_nfe_seu=0;nhomalt_nfe_swe=0;nhomalt_oth=0;nhomalt_oth_female=0;nhomalt_oth_male=0;nhomalt_popmax=0;nhomalt_raw=0;nhomalt_sas=0;nhomalt_sas_female=0;nhomalt_sas_male=0;popmax=sas;variant_type=multi-snv

```

Sergey

**Comment by hocinebendou** [comment]
@naumenko-sa. @pvanheus followed your instructions. However, this time I'm getting the following error:

```
OpenBLAS blas_thread_init: pthread_create failed for thread 31 of 32: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 31668 current, 386078 max
Traceback (most recent call last):
  File "/tools/software/bcbio/anaconda/bin/py", line 11, in <module>
    load_entry_point('pythonpy==0.4.11', 'console_scripts', 'py')()
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2853, in load_entry_point
    return ep.load()
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2444, in load
    return self.resolve()
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2450, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/pythonpy/__main__.py", line 142, in <module>
    lazy_imports(args.expression, args.pre_cmd, args.post_cmd)
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/pythonpy/__main__.py", line 45, in lazy_imports
    import_matches(query)
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/pythonpy/__main__.py", line 38, in import_matches
    import_matches(query, prefix='%s.' % module_name)
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/pythonpy/__main__.py", line 38, in import_matches
    import_matches(query, prefix='%s.' % module_name)
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/pythonpy/__main__.py", line 36, in import_matches
    module = __import__(module_name)
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/vardict.py", line 25, in <module>
    from bcbio import bam, broad, utils
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/bcbio/bam/__init__.py", line 8, in <module>
    import numpy
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
KeyboardInterrupt
Failed to open -: unknown file type
Failed to open -: unknown file type
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/freebayes.py", line 330, in call_somatic
    _write_header(header)
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/freebayes.py", line 313, in _write_header
    for hline in header[:-1] + new_headers + [header[-1]]:
IndexError: list index out of range
' returned non-zero exit status 1.
``` 
Not sure why numpy is complaining? 

Thanks Sergey

**Comment by naumenko-sa** [comment]
Glad that we solved the original issue!

We were dealing with numpy/openblas before (see openblas part): #1225
https://stackoverflow.com/questions/33506042/openblas-error-when-importing-numpy-pthread-creat-error-in-blas-thread-init-fu

Does numpy work at all in your system (make sure you are running bcbio python)?
```python
import numpy as np
```

Try to check out openblas versions, here is what I see on one of the working bcbio/Ubuntu systems:
```
conda list | grep openblas
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                h5ec1e0e_6    conda-forge
```

Then try to upgrade blas library if it is outdated:
```
bcbio_conda update numpy scipy openblas
```
or 
```
bcbio_nextgen.py upgrade -u skip --tools
```

SN

**Comment by hocinebendou** [comment]
@naumenko-sa. Thanks for your reply.

I can confirm that bcbio numpy is installed. We did run the upgrade command but the error still the same error. I want to add that I'm running bcbio using slurm (sbatch command). Does the numpy problem has something to do with the parallelism of slurm?

Thanks

**Comment by naumenko-sa** [comment]
I think it is rather related to python than to slurm.

What is your python?
`which python`

Are you able to import numpy in python?
```python
import numpy as np
```

What are you libblas versions?
```
conda list | grep openblas
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                h5ec1e0e_6    conda-forge
```

SN

**Comment by hocinebendou** [comment]
Thanks @naumenko-sa 

Here are the information you requested:

**Which python?**
`/tools/software/bcbio/anaconda/bin/python`

**Are you able to import numpy in python?**
`Yes`

**What are you libblas versions?**
```
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                h5ec1e0e_6    conda-forge
```

**Comment by naumenko-sa** [comment]
Thanks! Everything looks fine.

Sorry, I don't see any clues on the bcbio side.

Maybe the issue is related to the difference between nodes of your cluster (main node vs the node where your job is actually running with sbatch?)

Can you try to 
- run it on the main node (where the environment looks ok)
- check the environment (python) on the compute nodes?

S.

**Comment by hocinebendou** [comment]
Thanks @naumenko-sa. 

It was a memory problem. We allocated more memory. This time I'm getting the following issue. Not sure why bcbio is looking for **dbsnp-153.vcf.gz** in my working directory. Is it a configuration problem? I appreciate too much your help. Thanks

```
Traceback (most recent call last):
  File "/tools/software/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/tools/software/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 165, in variant2pipeline
    samples = run_parallel("postprocess_variants", samples)
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/tools/software/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/tools/software/bcbio/anaconda/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
subprocess.CalledProcessError: Command 'set -o pipefail; vcfanno -p 8 /usr/people/hbendou/uct/bcbio/PD44692/test1/work/vardict/dbsnp.conf /usr/people/hbendou/uct/bcbio/PD44692/test1/work/vardict/bcbio-effects.vcf.gz | bcftools reheader -h /usr/people/hbendou/uct/bcbio/PD44692/test1/work/vardict/bcbio-effects-annotated-sample_header.txt | bcftools view  |  bgzip -c > /usr/people/hbendou/uct/bcbio/PD44692/test1/work/bcbiotx/tmpalcw8zs6/bcbio-effects-annotated.vcf.gz
=============================================
vcfanno version 0.3.2 [built with go1.12.1]
see: https://github.com/brentp/vcfanno
=============================================
vcfanno.go:112: [Flatten] unable to open file: //usr/people/hbendou/uct/bcbio/PD44692/test1/variation/dbsnp-153.vcf.gz in
[E::bcf_hdr_read] Input is not detected as bcf or vcf format
Failed to read the header: -
Failed to open -: unknown file type
```

**Comment by naumenko-sa** [comment]
Hi @hocinebendou !

Could you try to trace the location of the annotation files in your installation?

1. vcfanno: gemini triggers annotation with `/data/genomes/Hsapiens/hg38/config/vcfanno/gemini.conf`
2. it has dbsnp record: `file="variation/dbsnp-153.vcf.gz"`
3. check if you have the file: `/data/genomes/Hsapiens/hg38/variation/dbsnp-153.vcf.gz`
4. check hg38 resources file:
```
$ cat  /data/genomes/Hsapiens/hg38/seq/hg38-resources.yaml | grep dbsnp
dbsnp: ../variation/dbsnp-153.vcf.gz
```
S

**Comment by hocinebendou** [comment]
Hi @naumenko-sa 

I checked. There is no file `dbsnp-153.vcf.gz`. Instead I found `dbsnp-151.vcf.gz` which I suppose is an old version.

What you suggest to update it?

Thanks
Hocine

**Comment by naumenko-sa** [comment]
Yes, try to update hg38 data 

```bcbio_nextgen.py upgrade -u skip --data --genomes hg38 --datatarget variation```

Sergey

**Comment by hocinebendou** [comment]
Hi @naumenko-sa 

It worked without issues.

Thanks
