### ISSUE TITLE
OSError: b'/work/strelka2/chr3/batch6-chr3_45568726_80876695-raw.vcf.gz' if not valid bcf or vcf

### ISSUE THREAD

**Issue by wenhuanling** [bcbio/bcbio-nextgen#3258]
Hi Bcbio team, 

I encountered this particular error, which I cannot understand what is going. According to the debug log file, the error is caused due to the step: Filter Strelka2 calls with allele fraction threshold of 0.1.

Please advise on this particular error. Is it due to some error in that particular region? Or is it because there are some hidden errors with Strelka2? Sorry about the format of posting, as it is my first time doing so.

**Version info**
 - bcbio version: 1.2.0
 - Linux version 5.3.0-1019-aws

**To Reproduce**
Command generated by bcbio:
`unset JAVA_HOME && export PATH=/usr/local/share/bcbio/anaconda/bin:"$PATH" && gatk --java-options '-Xms681m -Xmx1363m -XX:+UseSerialGC -Djava.io.tmpdir=/mnt/volume1/HG38_information/work_      folder/B003/work/bcbiotx/tmphggx3hst' Mutect2 --annotation ClippingRankSumTest --annotation DepthPerSampleHC --reference /usr/local/share/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa --annotation MappingQualityRa      nkSumTest --annotation MappingQualityZero --annotation QualByDepth --annotation ReadPosRankSumTest --annotation RMSMappingQuality --annotation FisherStrand --annotation MappingQuality --annotation DepthPerAl      leleBySample --annotation Coverage --read-validation-stringency LENIENT -I /mnt/volume1/HG38_information/work_folder/B003/work/align/WHT385/WHT385-sort.bam --tumor-sample WHT385 -I /mnt/volume1/HG38_informat      ion/work_folder/B003/work/align/WHT160/WHT160-sort.bam --normal-sample WHT160 -L /mnt/volume1/HG38_information/work_folder/B003/work/mutect2/chr3/batch6-chr3_45568726_80876695-regions.bed --interval-set-rule       INTERSECTION -O /mnt/volume1/HG38_information/work_folder/B003/work/mutect2/chr3/batch6-chr3_45568726_80876695-raw.vcf.gz && sed -i 's/callable\t0.0/callable\t10.0/' /mnt/volume1/HG38_information/work_folde      r/B003/work/mutect2/chr3/batch6-chr3_45568726_80876695-raw.vcf.gz.stats && unset JAVA_HOME && export PATH=/usr/local/share/bcbio/anaconda/bin:"$PATH" && gatk --java-options '-Xms681m -Xmx1363m -XX:+UseSerial      GC -Djava.io.tmpdir=/mnt/volume1/HG38_information/work_folder/B003/work/bcbiotx/tmphggx3hst' FilterMutectCalls --reference /usr/local/share/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa --variant /mnt/volume1/HG38      _information/work_folder/B003/work/mutect2/chr3/batch6-chr3_45568726_80876695-raw.vcf.gz --output /mnt/volume1/HG38_information/work_folder/B003/work/bcbiotx/tmphggx3hst/batch6-chr3_45568726_80876695-raw-fil      t.vcf.gz`

**Observed behavior**
Command error:
    File "/usr/local/share/bcbio/anaconda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
      result = (True, func(*args, **kwds))
    File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 608, in __call__
      return self.func(*args, **kwargs)
    File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 256, in __call__
      for func, args, kwargs in self.items]
    File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 256, in <listcomp>
      for func, args, kwargs in self.items]
    File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
      return f(*args, **kwargs)
    File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 315, in variantcall_sample
      return genotype.variantcall_sample(*args)
    File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/genotype.py", line 377, in variantcall_sample
      out_file = caller_fn(align_bams, items, ref_file, assoc_files, region, out_file)
    File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/strelka2.py", line 34, in run
      return _af_annotate_and_filter(paired, items, call_file, out_file)
    File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/strelka2.py", line 243, in _af_annotate_and_filter
      vcf = cyvcf2.VCF(in_file)
    File "cyvcf2/cyvcf2.pyx", line 197, in cyvcf2.cyvcf2.VCF.__init__
  OSError: b'/mnt/volume1/HG38_information/work_folder/B003/work/strelka2/chr3/batch6-chr3_45568726_80876695-raw.vcf.gz' if not valid bcf or vcf
  """

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
      main(**kwargs)
    File "/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
      run_main(**kwargs)
    File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
      fc_dir, run_info_yaml)
    File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
      for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
    File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 154, in variant2pipeline
      samples = genotype.parallel_variantcall_region(samples, run_parallel)
    File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/genotype.py", line 208, in parallel_variantcall_region
      "vrn_file", ["region", "sam_ref", "config"]))
    File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/split.py", line 35, in grouped_parallel_split_combine
      final_output = parallel_fn(parallel_name, split_args)
    File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
      return run_multicore(fn, items, config, parallel=parallel)
    File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
      for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
    File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1017, in __call__
      self.retrieve()
    File "/usr/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 909, in retrieve
      self._output.extend(job.get(timeout=self.timeout))
    File "/usr/local/share/bcbio/anaconda/lib/python3.6/multiprocessing/pool.py", line 644, in get
      raise self._value
  OSError: b'/mnt/volume1/HG38_information/work_folder/B003/work/strelka2/chr3/batch6-chr3_45568726_80876695-raw.vcf.gz' if not valid bcf or vcf

**Comment by roryk** [comment]
Hi @wenhuanling,

Sorry about the problem, does this happen if you run it again? If you just rerun the job it will pick up where it left off. A lot of time errors like these are due to the filesystem having a hiccup. 

If it does happen again, would it be possible to send along   `/mnt/volume1/HG38_information/work_folder/B003/work/strelka2/chr3/batch6-chr3_45568726_80876695-raw.vcf.gz` so we can take a look at it?

**Comment by wenhuanling** [comment]
Hi @roryk, 

Yes, whenever I tried to rerun the job, it will end up with the same issue. 

I have attached [batch6-chr3_45568726_80876695-raw.vcf.gz](https://github.com/bcbio/bcbio-nextgen/files/4755628/batch6-chr3_45568726_80876695-raw.vcf.gz) here.

**Comment by roryk** [comment]
Thanks, it looks like the file is empty, so that must be what is causing the problem. If you delete '/mnt/volume1/HG38_information/work_folder/B003/work/strelka2/chr3/batch6-chr3_45568726_80876695-raw.vcf.gz` and restart, does it make an empty file again and give the same error?

**Comment by wenhuanling** [comment]
Hi @roryk, 

Thanks for the advice. As of now, bcbio is still running after I deleted batch6-chr3_45568726_80876695-raw.vcf.gz and restart the run. I also checked through the file, and it is not empty. Will keep an update if the run again if any other errors happen.

**Comment by roryk** [comment]
Thanks! Glad that fixed it, we have another user running into a problem with strelka too as well, I wonder if they are running into the same problem.
