### ISSUE TITLE
Single cell for other species

### ISSUE THREAD

**Issue by sunliang3361** [bcbio/bcbio-nextgen#3264]
**Version info**
 - bcbio version (bcbio_nextgen.py --version): version on O2
 - OS name and version: O2

**To Reproduce**
 - Exact bcbio command you have used
 - Your sample configuration file

**Observed behavior**
Error message or bcbio output.

**Expected behavior**

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.

**Additional context**
I saw we have transcriptome.fasta and gif files for human and mouse, if I need to process data for other species, do I need to provide the gtf and transcriptome. fa in my own directory. The BCBIO should work? Thanks.

**Comment by roryk** [comment]
Hi @sunliang3361 

That's right-- you'll also need to put a dummy genome that is supported in for `genome_build`, bcbio will just ignore it if you are specifying the `transcriptome_gtf` and `transcriptome_fasta` for the single-cell pipeline but there is code that checks if that is valid. So just put like `mm10` or whatever for that.

**Comment by roryk** [comment]
Thanks I added this problem to our technical debt section. Let me know if you're having trouble getting bcbio working with a new organism and I can help-- sometimes, depending on the organism, the input transcriptome/GTF files are malformed and need to get cleaned up.

**Comment by sunliang3361** [comment]
Thank you so much. genome_build: mm10? Just want to confirm it's correct below to add the dummy genome:
-----------
details:
- algorithm:
    cellular_barcode_correction: 1
    minimum_barcode_depth: 1000
    sample_barcodes: /home/ls360/scratch/sc_zebra/config/sample_barcodes.csv
    transcriptome_fasta: /temp_work/ch213537/NGS/p17_Burns/sc_zebra/refence/ref-transcripts.fa
    transcriptome_gtf: /temp_work/ch213537/NGS/p17_Burns/sc_zebra/refence/ref-transcripts.gtf
    umi_type: bch-indrop-v3
  analysis: scRNA-seq
  description: Burns
  files:
  - ../input/Burns_1.fq.gz
  - ../input/Burns_2.fq.gz
  - ../input/Burns_3.fq.gz
  - ../input/Burns_4.fq.gz
  genome_build: mm10
  metadata: {}
fc_name: sc-zebra
upload:
  dir: /temp_work/ch213537/NGS/p17_Burns/sc_zebra/final

**Comment by sunliang3361** [comment]
This is the error message:
[2020-06-12T23:54Z] System YAML configuration: /n/app/bcbio/dev/galaxy/bcbio_system.yaml.
[2020-06-12T23:54Z] Locale set to en_US.utf8.
[2020-06-12T23:54Z] Resource requests: picard; memory: 4.00; cores: 16
[2020-06-12T23:54Z] Configuring 1 jobs to run, using 1 cores each with 4.00g of memory reserved for each job
[2020-06-12T23:54Z] Timing: organize samples
[2020-06-12T23:54Z] multiprocessing: organize_samples
[2020-06-12T23:54Z] Using input YAML configuration: /n/scratch3/users/l/ls360/sc_zebra/config/sc-zebra.yaml
[2020-06-12T23:54Z] Checking sample YAML configuration: /n/scratch3/users/l/ls360/sc_zebra/config/sc-zebra.yaml
[2020-06-12T23:54Z] Retreiving program versions from /n/app/bcbio/dev/manifest/python-packages.yaml.
[2020-06-12T23:54Z] Retreiving program versions from /n/app/bcbio/dev/manifest/r-packages.yaml.
[2020-06-12T23:54Z] Testing minimum versions of installed programs
[2020-06-12T23:54Z] multiprocessing: prepare_sample
[2020-06-12T23:54Z] Preparing Burns
[2020-06-12T23:54Z] Resource requests: rapmap, samtools; memory: 4.00, 4.00; cores: 16, 16
[2020-06-12T23:54Z] Configuring 1 jobs to run, using 16 cores each with 64.1g of memory reserved for each job
[2020-06-12T23:54Z] Timing: singlecell-rnaseq
[2020-06-12T23:54Z] multiprocessing: run_umi_transform
[2020-06-12T23:54Z] Inserting UMI and barcode information into the read name of /n/scratch3/users/l/ls360/sc_zebra/input/Burns_1.fq.gz
[2020-06-12T23:54Z] INFO:umis.umis:Transforming /n/scratch3/users/l/ls360/sc_zebra/input/Burns_1.fq.gz.
[2020-06-12T23:54Z] INFO:umis.umis:Detected dual cellular indexes.
[2020-06-12T23:54Z] INFO:umis.umis:Detected UMI.
[2020-06-12T23:54Z] INFO:umis.umis:Detected sample.
[2020-06-13T03:38Z] multiprocessing: demultiplex_samples
Traceback (most recent call last):
  File "/n/app/bcbio/tools/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/n/app/bcbio/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 310, in singlecellrnaseqpipeline
    samples = rnaseq.singlecell_rnaseq(samples, run_parallel)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/pipeline/rnaseq.py", line 26, in singlecell_rnaseq
    demultiplexed = run_parallel("demultiplex_samples", samples)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 921, in __call__
    if self.dispatch_one_batch(iterator):
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 52, in demultiplex_samples
    return umi.demultiplex_samples(*args)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/rnaseq/umi.py", line 380, in demultiplex_samples
    bcfile = get_sample_barcodes(dd.get_sample_barcodes(data), sample_dir)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/rnaseq/umi.py", line 113, in get_sample_barcodes
    with open(fn) as inh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ls360/scratch/sc_zebra/config/sample_barcodes.csv'
