### ISSUE TITLE
Errors with installation

### ISSUE THREAD

**Issue by DiyaVaka** [bcbio/bcbio-nextgen#3265]
Installed latest verison of bcbio but running into errors even after activating the environment

bcbio_nextgen.py fc_dir ./sample_gmi.yaml -n 8
Running bcbio version: 1.2.3
global config: /pathto/bcbio_system.yaml
flowcell directory: /path/flowcell_dir/
run info config: /pathto/sample_gmi.yaml
Traceback (most recent call last):
  File "/home/sequencing/bcbio/stable/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/home/sequencing/bcbio/stable/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/sequencing/bcbio/stable/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 41, in run_main
    parallel = log.create_base_logger(config, parallel)
  File "/home/sequencing/bcbio/stable/anaconda/lib/python3.6/site-packages/bcbio/log/__init__.py", line 126, in create_base_logger
    subscriber.dispatch_in_background(_create_log_handler(config))
  File "/home/sequencing/bcbio/stable/anaconda/lib/python3.6/site-packages/bcbio/log/__init__.py", line 83, in _create_log_handler
    email = config.get("email", config.get("resources", {}).get("log", {}).get("email"))
AttributeError: 'str' object has no attribute 'get'

**Comment by roryk** [comment]
Hi @DiyaVaka,

Could you post  `./sample_gmi.yaml` so we can help debug? I am guessing that something is up with that file.

**Comment by naumenko-sa** [comment]
Also, the way bcbio called usually is:
```bash
$ ls
config
work
$ ls config
sample_gmi.yaml
$ cd work
bcbio_nextgen.py ../config/sample_gmi.yaml -n8
```

**Comment by DiyaVaka** [comment]
upload:
  dir: /coldstorage/fastq/A00269/200603_A00269_0338_BHLGCGDRXX/EX_0294/GML3281_RR030220_Fam885_bcbio/
details:
  - files: [/coldstorage/fastq/A00269/200603_A00269_0338_BHLGCGDRXX/060320_EX294/GML3281_RR030220_Fam885_bcbio/GML3281_RR030220_Fam885_R1.fastq,/coldstorage/fastq/A00269/200603_A00269_0338_BHLGCGDRXX/060320_EX294/GML3281_RR030220_Fam885_bcbio/GML3281_RR030220_Fam885_R2.fastq]
    description: GML3281_RR030220_Fam885_bcbio
    analysis: 'variant'
    genome_build: GRCh37
    lane: GML3281_RR030220_Fam885_bcbio
    algorithm:
      aligner: bwa
      trim_reads: false
      mark_duplicates: true
      recalibrate: true
      realign: false
      variantcaller: [gatk, gatk-haplotype,freebayes,vardict]
      ensemble:
       numpass: 1
       use_filtered: false
      tools_off: [gemini]
      tools_on: [qualimap_full, picard]
      coverage: /home/sequencing/bcbio/xgen-exome-research-panel-targets_6bpexpanded-merged-bed6.bed
      coverage_interval: exome
      coverage_depth: high
      variant_regions: /home/sequencing/bcbio/xgen-exome-research-panel-targets_6bpexpanded-merged-bed6.bed
      clinical_reporting: true

**Comment by naumenko-sa** [comment]
I see two potential issues:
- `analysis: variant` should be `analysis: variant2` https://bcbio-nextgen.readthedocs.io/en/latest/contents/germline_variants.html#set-analysis-parameters-in-config-na12878-yaml 
- `variantcaller: [gatk, gatk-haplotype]` gatk here calls UnifiedGenotyper which is from pre-gatk3.x era. We support gatk4 in bcbio and gatk3.8x with `tools_off: gatk4`

Could you also please keep yaml formatting, otherwise it is hard to see if there is any indentation issues.
```yaml
tools_on:
- qualimap_full
- picard
```
SN

**Comment by DiyaVaka** [comment]
thank you for the quick response. we want to keep our CLIA pipeline intact for which we used GATK3.4.6. Does that work with tools_off:gatk4

**Comment by naumenko-sa** [comment]
Well, I understand that updating the clinical pipeline is not an easy task.
The default gatk is gatk4 now, so you have to switch it off.

I have just tried it with 
```yaml
tools_off: gatk4
variantcaller: gatk
```
and it calls variants with UnifiedGenotyper for gatk3.8-1-0/bcbio1.2.3. 
If you have an earlier GATK3x registered and its interface is the same as gatk3.8, it should work as well.

It should also work with
```yaml
tools_off: gatk4
variantcaller:
- gatk
- gatk-haplotype 
```
then gatk-haplotype = HC from gatk3.x and gatk = UG from gatk3.x

SN

**Comment by DiyaVaka** [comment]
Thank you. I am trying the similar setup on aws ec2 and running into issues. Here is where my installation is
[ec2-user@xx-xx-xx-xx bcbio-vm]$ ls
anaconda  config  data  galaxy  gemini_data  genomes  liftOver
pwd=/data/install/bcbio-vm. 
Attached is my sample.yaml. 
here are my commands to execute it 
/data/install/bcbio-vm/anaconda/bin/bcbio_nextgen.py run_config $PWD/sample.yaml 
Running bcbio version: 1.2.3
global config: /home/ec2-user/NA12878/bcbio_system.yaml
flowcell directory: /home/ec2-user/NA12878/run_config
run info config: /home/ec2-user/NA12878/sample.yaml
[2020-06-26T18:57Z] System YAML configuration: /data/install/bcbio-vm/galaxy/bcbio_system.yaml.
[2020-06-26T18:57Z] Locale set to C.utf8.
[2020-06-26T18:57Z] Resource requests: bwa, gatk, sambamba, samtools; memory: 3.00, 3.00, 3.00, 3.00; cores: 16, 16, 16, 16
[2020-06-26T18:57Z] Configuring 1 jobs to run, using 1 cores each with 3.00g of memory reserved for each job
[2020-06-26T18:57Z] Timing: organize samples
[2020-06-26T18:57Z] multiprocessing: organize_samples
[2020-06-26T18:57Z] Using input YAML configuration: /home/ec2-user/NA12878/sample.yaml
[2020-06-26T18:57Z] Checking sample YAML configuration: /home/ec2-user/NA12878/sample.yaml
Traceback (most recent call last):
  File "/data/install/bcbio-vm/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/data/install/bcbio-vm/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/data/install/bcbio-vm/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/data/install/bcbio-vm/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/data/install/bcbio-vm/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 128, in variant2pipeline
    [x[0]["description"] for x in samples]]])
  File "/data/install/bcbio-vm/anaconda/lib/python3.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/data/install/bcbio-vm/anaconda/lib/python3.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/data/install/bcbio-vm/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "/data/install/bcbio-vm/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "/data/install/bcbio-vm/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 765, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/data/install/bcbio-vm/anaconda/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 206, in apply_async
    result = ImmediateResult(func)
  File "/data/install/bcbio-vm/anaconda/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 570, in __init__
    self.results = batch()
  File "/data/install/bcbio-vm/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "/data/install/bcbio-vm/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "/data/install/bcbio-vm/anaconda/lib/python3.7/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/data/install/bcbio-vm/anaconda/lib/python3.7/site-packages/bcbio/distributed/multitasks.py", line 455, in organize_samples
    return run_info.organize(*args)
  File "/data/install/bcbio-vm/anaconda/lib/python3.7/site-packages/bcbio/pipeline/run_info.py", line 81, in organize
    item = add_reference_resources(item, remote_retriever)
  File "/data/install/bcbio-vm/anaconda/lib/python3.7/site-packages/bcbio/pipeline/run_info.py", line 178, in add_reference_resources
    _check_ref_files(data["reference"], data)
  File "/data/install/bcbio-vm/anaconda/lib/python3.7/site-packages/bcbio/pipeline/run_info.py", line 235, in _check_ref_files
    raise ValueError(msg + "\n".join(problems) + "\n")
ValueError: 
Problems with input reference file None
Did not find fasta reference file for genome hg38.
Check tool-data/*.loc files to ensure paths to reference data are correct.


[sampleyaml.txt](https://github.com/bcbio/bcbio-nextgen/files/4838833/sampleyaml.txt)

**Comment by DiyaVaka** [comment]
updating the tools again fixed my issue. Thanks
