### ISSUE TITLE
Data installation with current bcbio-rnaseq docker image fails

### ISSUE THREAD

**Issue by gabeng** [bcbio/bcbio-nextgen#3271]
**Version info**
- quay.io/bcbio/bcbio-rnaseq:1.2.3-2d6a5bb
 - bcbio version (bcbio_nextgen.py --version): 1.2.3

**To Reproduce**

```
bcbio_nextgen.py upgrade -u skip --data --datatarget rnaseq --genomes GRCh37
```

**Observed behavior**
Error message or bcbio output.
```
Moving on to next genome prep method after trying ggd
GGD recipe not available for GRCh37 rtg
Downloading genome from s3: GRCh37 rtg
Moving on to next genome prep method after trying s3
No pre-computed indices for GRCh37 rtg
Preparing genome GRCh37 with index rtg
/bin/sh: 1: rtg: not found
Moving on to next genome prep method after trying raw
Command 'export PATH=/usr/local/bin:$PATH && export RTG_JAVA_OPTS='-Xms1g' && export RTG_MEM=2g && rtg format -o rtg/GRCh37.sdf /mnt/biodata/genomes/Hsapiens/GRCh37/seq/GRCh37.fa' returned non-zero exit status 127.
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 107, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 377, in upgrade_bcbio_data
    args.cores, ["ggd", "s3", "raw"])
  File "/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 354, in install_data_local
    _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
  File "/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 495, in _prep_genomes
    .format(idx, gid, last_exc))
OSError: Could not prepare index rtg for GRCh37 by any method
Traceback (most recent call last):
  File "/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 480, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 519, in _prep_raw_index
    get_index_fn(idx)(env, ref_file)
  File "/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 850, in _index_rtg
    subprocess.check_call(cmd.format(**locals()), shell=True)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'export PATH=/usr/local/bin:$PATH && export RTG_JAVA_OPTS='-Xms1g' && export RTG_MEM=2g && rtg format -o rtg/GRCh37.sdf /mnt/biodata/genomes/Hsapiens/GRCh37/seq/GRCh37.fa' returned non-zero exit status 127.
```

**Expected behavior**
The data should be installed.

I also tried this building new docker images from the current version.

**Comment by hackdna** [comment]
Unfortunately, installing data using Docker images is not supported. A [standard bcbio installation](https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#install-bcbio-package-and-tools) is required to add data.
