### ISSUE TITLE
Installed Erro

### ISSUE THREAD

**Issue by yepl** [bcbio/bcbio-nextgen#3275]
**Version info**
 - bcbio version (bcbio_nextgen.py --version):lasted
 - OS name and version:CentOS Linux release 7.7.1908 (Core)

**To Reproduce**
```bash
su root 
cd ~
python bcbio_nextgen_install.py /usr/local/share/bcbio \
--tooldir=/usr/local \
--genomes GRCh37 \
--aligners bwa --aligners bowtie2
```

**Observed behavior**

```
Installing data and third party dependencies
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 290, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 49, in main
    system_config = write_system_config(REMOTES["system_config"], args.datadir, args.tooldir)
  File "bcbio_nextgen_install.py", line 166, in write_system_config
    with contextlib.closing(urllib_request.urlopen(base_url)) as in_handle:
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 104] Connection reset by peer>
```

ERRO 2:
```bash
su root
bcbio_nextgen.py -w template freebayes-variant project1.csv sample1.bam sample2_1.fq sample2_2.fq
bcbio_nextgen.py -w template \
freebayes-variant \
project1.csv \
sample1.bam sample2_1.fq sample2_2.fq
```

```
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 239, in <module>
    setup_info = workflow.setup(kwargs["workflow"], kwargs.pop("inputs"))
  File "/usr/local/share/bcbio/anaconda/lib/python3.7/site-packages/bcbio/workflow/__init__.py", line 12, in setup
    return workflow.setup(args)
  File "/usr/local/share/bcbio/anaconda/lib/python3.7/site-packages/bcbio/workflow/template.py", line 554, in setup
    project_name, metadata, global_vars, md_file = _pname_and_metadata(args.metadata)
  File "/usr/local/share/bcbio/anaconda/lib/python3.7/site-packages/bcbio/workflow/template.py", line 336, in _pname_and_metadata
    raise ValueError("Did not find input metadata file: %s" % in_file)
ValueError: Did not find input metadata file: project1.csv
```

**Expected behavior**
how to install successly

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.

**Additional context**
CENTOS7 running on VMware Worstation Pro 15

**Comment by naumenko-sa** [comment]
Hi @yepl !

1. Could you please format the issue next time to make it easier to read? (see the example formatting above)
2. I think you may have a connection issue in the installation part. You have a complex setup: host/VMWare/Centos. Make sure all network connection works.
3. The second error is `Did not find input metadata file: project1.csv`. The script does not see your project1.csv. Make sure you have set up all the files in a project: https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#project-structure, 
https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#automated-sample-configuration.

Sergey
