### ISSUE TITLE
IPCluster fail- alignment never happens

### ISSUE THREAD

**Issue by drlaurenwasson** [bcbio/bcbio-nextgen#3279]
Hello,
I am running bcbio for the first time on a different compute cluster. I have submitted my job as a slurm script from the login node:

#!/bin/bash

#SBATCH -p general
#SBATCH --job-name=bcbionextgen
#SBATCH -c 1
#SBATCH -t 12:00:00
#SBATCH --mem-per-cpu=10G
#SBATCH -e Wei_test_bcbionextgen.err

export PATH=/proj/conlonlb/bcbio/anaconda/bin:/proj/conlonlb/bcbio/tools/bin:$PATH

bcbio_nextgen.py ../config/submission.yaml -n 64 -t ipython -s slurm -q general '-rW=100:00' --retries 3 --timeout 5000

sbatch submit_bcbio.sh

This job submitted to the cluster. I see 
63017635     Wei_test_+    general rc_fconlo+          1    RUNNING      0:0
63017635.ba+      batch            rc_fconlo+          1    RUNNING      0:0
63017635.ex+     extern            rc_fconlo+          1    RUNNING      0:0

This is the *err file
[2020-06-26T20:13Z] c0539.ll.unc.edu: System YAML configuration: /proj/conlonlb/bcbio/galaxy/bcbio_system.yaml.
[2020-06-26T20:13Z] c0539.ll.unc.edu: Locale set to en_US.utf8.
[2020-06-26T20:13Z] c0539.ll.unc.edu: Resource requests: picard; memory: 3.00; cores: 16
[2020-06-26T20:13Z] c0539.ll.unc.edu: Configuring 1 jobs to run, using 1 cores each with 3.00g of memory reserved for each job
2020-06-26 16:13:23.629 [IPClusterStart] Using existing profile dir: '/proj/conlonlb/users/wasson/submission/work/log/ipython'
2020-06-26 16:13:23.630 [IPClusterStart] Searching path ['/proj/conlonlb/users/wasson/submission/work', '/proj/conlonlb/users/wasson/submission/work/log/ipython', '/proj/conlonlb/bcbio/anaconda/etc/ipython', '/usr/local/etc/ipython', '/etc/ipython'] for config files
2020-06-26 16:13:23.631 [IPClusterStart] Attempting to load config file: ipython_config.py
2020-06-26 16:13:23.631 [IPClusterStart] Looking for ipython_config in /etc/ipython
2020-06-26 16:13:23.631 [IPClusterStart] Looking for ipython_config in /usr/local/etc/ipython
2020-06-26 16:13:23.631 [IPClusterStart] Looking for ipython_config in /proj/conlonlb/bcbio/anaconda/etc/ipython
2020-06-26 16:13:23.632 [IPClusterStart] Looking for ipython_config in /proj/conlonlb/users/wasson/submission/work/log/ipython
2020-06-26 16:13:23.632 [IPClusterStart] Loaded config file: /proj/conlonlb/users/wasson/submission/work/log/ipython/ipython_config.py
2020-06-26 16:13:23.633 [IPClusterStart] Looking for ipython_config in /proj/conlonlb/users/wasson/submission/work
2020-06-26 16:13:23.634 [IPClusterStart] Attempting to load config file: ipcluster_5f26e6c0_8e9e_413c_a0de_5257db3fb7b3_config.py
2020-06-26 16:13:23.634 [IPClusterStart] Looking for ipcontroller_config in /etc/ipython
2020-06-26 16:13:23.634 [IPClusterStart] Looking for ipcontroller_config in /usr/local/etc/ipython
2020-06-26 16:13:23.635 [IPClusterStart] Looking for ipcontroller_config in /proj/conlonlb/bcbio/anaconda/etc/ipython
2020-06-26 16:13:23.635 [IPClusterStart] Looking for ipcontroller_config in /proj/conlonlb/users/wasson/submission/work/log/ipython
2020-06-26 16:13:23.635 [IPClusterStart] Loaded config file: /proj/conlonlb/users/wasson/submission/work/log/ipython/ipcontroller_config.py
2020-06-26 16:13:23.635 [IPClusterStart] Looking for ipcontroller_config in /proj/conlonlb/users/wasson/submission/work
2020-06-26 16:13:23.637 [IPClusterStart] Attempting to load config file: ipcluster_5f26e6c0_8e9e_413c_a0de_5257db3fb7b3_config.py
2020-06-26 16:13:23.637 [IPClusterStart] Looking for ipengine_config in /etc/ipython
2020-06-26 16:13:23.637 [IPClusterStart] Looking for ipengine_config in /usr/local/etc/ipython
2020-06-26 16:13:23.637 [IPClusterStart] Looking for ipengine_config in /proj/conlonlb/bcbio/anaconda/etc/ipython
2020-06-26 16:13:23.637 [IPClusterStart] Looking for ipengine_config in /proj/conlonlb/users/wasson/submission/work/log/ipython
2020-06-26 16:13:23.638 [IPClusterStart] Loaded config file: /proj/conlonlb/users/wasson/submission/work/log/ipython/ipengine_config.py
2020-06-26 16:13:23.638 [IPClusterStart] Looking for ipengine_config in /proj/conlonlb/users/wasson/submission/work
2020-06-26 16:13:23.639 [IPClusterStart] Attempting to load config file: ipcluster_5f26e6c0_8e9e_413c_a0de_5257db3fb7b3_config.py
2020-06-26 16:13:23.639 [IPClusterStart] Looking for ipcluster_config in /etc/ipython
2020-06-26 16:13:23.639 [IPClusterStart] Looking for ipcluster_config in /usr/local/etc/ipython
2020-06-26 16:13:23.640 [IPClusterStart] Looking for ipcluster_config in /proj/conlonlb/bcbio/anaconda/etc/ipython
2020-06-26 16:13:23.640 [IPClusterStart] Looking for ipcluster_config in /proj/conlonlb/users/wasson/submission/work/log/ipython
2020-06-26 16:13:23.640 [IPClusterStart] Loaded config file: /proj/conlonlb/users/wasson/submission/work/log/ipython/ipcluster_config.py
2020-06-26 16:13:23.640 [IPClusterStart] Looking for ipcluster_config in /proj/conlonlb/users/wasson/submission/work

It did nothing for many many hours (like 6). In the ipcluster log file is this:

2020-06-26 16:13:23.825 [IPClusterStart] Starting ipcluster with [daemon=True]
2020-06-26 16:13:23.838 [IPClusterStart] Creating pid file: /proj/conlonlb/users/wasson/submission/work/log/ipython/pid/ipcluster-5f26e6c0-8e9e-413c-a0de-5257db3fb7b3.pid
2020-06-26 16:13:23.839 [IPClusterStart] Starting Controller with cluster_helper.cluster.BcbioSLURMControllerLauncher
2020-06-26 16:13:23.841 [IPClusterStart] Starting BcbioSLURMControllerLauncher: ['sbatch', './SLURM_controller0497b8e3-0930-4415-91d7-8d1c5ca739aa']
2020-06-26 16:13:23.842 [IPClusterStart] adding queue settings to batch script
2020-06-26 16:13:23.842 [IPClusterStart] Writing batch script: ./SLURM_controller0497b8e3-0930-4415-91d7-8d1c5ca739aa
2020-06-26 16:13:23.862 [IPClusterStart] ERROR | Controller start failed
Traceback (most recent call last):
  File "/proj/conlonlb/bcbio/anaconda/lib/python3.6/site-packages/ipyparallel/apps/ipclusterapp.py", line 543, in start_controller
    self.controller_launcher.start()
  File "/proj/conlonlb/bcbio/anaconda/lib/python3.6/site-packages/cluster_helper/cluster.py", line 515, in start
    return super(BcbioSLURMControllerLauncher, self).start(1)
  File "/proj/conlonlb/bcbio/anaconda/lib/python3.6/site-packages/ipyparallel/apps/launcher.py", line 1179, in start
    output = check_output(self.args, env=os.environ)
  File "/proj/conlonlb/bcbio/anaconda/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/proj/conlonlb/bcbio/anaconda/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['sbatch', './SLURM_controller0497b8e3-0930-4415-91d7-8d1c5ca739aa']' returned non-zero exit status 255.

Any ideas? Thank you

**Comment by drlaurenwasson** [comment]
I figured it out. I'm on the UNC longleaf cluster which "coupled workloads with an emphasis on aggregate job throughput over individual job performance. In particular, workloads consisting of a large number of jobs each requiring a single compute host are best suited to Longleaf. The Longleaf cluster is targeted for data science and statistical computing workloads, very large memory jobs, and GPU computing. Resources are managed through a fair-share algorithm using SLURM as the resource manager/job scheduler." 


The parallelism of the script was an issue on this cluster. Once I removed it it worked just fine.

**Comment by roryk** [comment]
Hi Lauren,

It looks like the controller startup failed: `2020-06-26 16:13:23.862 [IPClusterStart] ERROR | Controller start failed`. I'm guessing that the problem is they have their cluster configured so that you can't submit jobs from compute nodes. You can test this yourself if you open an interaction session to one of the compute nodes and try to submit jobs through it. I'm assuming you submitted the bcbio job itself as a job, did you? Or did you run the bcbio job from the login node?

**Comment by drlaurenwasson** [comment]
Hi Rory,
I did think of that, but I made a test.sh script (just making test directories) and submitted that to the cluster on a compute node and that submitted and completed.

Running the script below removed the parallelism that I had previously used on the HMS cluster, and now it does try to align, with another issue. I had closed this issue and opened a new one (#3281) 


#!/bin/bash

#SBATCH -p general
#SBATCH --job-name=Wei_test_bcbionextgen
#SBATCH -c 1
#SBATCH -t 12:00:00
#SBATCH --mem-per-cpu=10G
#SBATCH -e Wei_test_bcbionextgen.err

bcbio_nextgen.py ../config/submission.yaml -n 20

**Comment by roryk** [comment]
Gotcha, it might be that the cluster is configured such that you cannot open ports up to talk across nodes, which would be another reason for the controller not starting, but you'd have to work with the sysadmins of the cluster and see if they could relax that restriction, if they have implemented it.
