### ISSUE TITLE
rapmap error

### ISSUE THREAD

**Issue by sunliang3361** [bcbio/bcbio-nextgen#3294]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): latest on O2
- OS name and version (`lsb_release -ds`): O2 in HMS

**To Reproduce**
Exact bcbio command you have used:
```

```
Your sample configuration file:
```

```

**Observed behavior**
Error message or bcbio output:
```
[2020-07-08T12:10Z] Computing cellular barcode counts for /n/scratch3/users/l/ls360/sc_woolf/work/umis/Woolf-AGAGGATA.filtered.fq.gz.
[2020-07-08T12:18Z] Computing cellular barcode counts for /n/scratch3/users/l/ls360/sc_woolf/work/umis/Woolf-ATAGAGAG.filtered.fq.gz.
[2020-07-08T12:29Z] Computing cellular barcode counts for /n/scratch3/users/l/ls360/sc_woolf/work/umis/Woolf-CTCCTTAC.filtered.fq.gz.
[2020-07-08T12:37Z] Computing cellular barcode counts for /n/scratch3/users/l/ls360/sc_woolf/work/umis/Woolf-TATGCAGT.filtered.fq.gz.
[2020-07-08T12:48Z] multiprocessing: run_rapmap_index
Traceback (most recent call last):
  File "/n/app/bcbio/tools/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/n/app/bcbio/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 310, in singlecellrnaseqpipeline
    samples = rnaseq.singlecell_rnaseq(samples, run_parallel)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/pipeline/rnaseq.py", line 35, in singlecell_rnaseq
    samples = run_parallel("run_rapmap_index", [samples])
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 921, in __call__
    if self.dispatch_one_batch(iterator):
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 84, in run_rapmap_index
    return rapmap.run_rapmap_index(*args)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/rnaseq/rapmap.py", line 25, in run_rapmap_index
    rapmap_index(gtf_file, fasta_file, "quasi", data, rapmap_dir)
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/rnaseq/rapmap.py", line 59, in rapmap_index
    gtf_fa = fasta.strip_transcript_versions(gtf_fa, os.path.join(out_dir, os.path.basename(gtf_fa)))
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/bcbio/bam/fasta.py", line 37, in strip_transcript_versions
    for line in in_handle:
  File "/n/app/bcbio/dev/anaconda/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

```

**Expected behavior**

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.
[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/4890956/bcbio-nextgen-commands.log)
[bcbio-nextgen-debug.log](https://github.com/bcbio/bcbio-nextgen/files/4890957/bcbio-nextgen-debug.log)
[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/4890958/bcbio-nextgen.log)

**Additional context**

**Comment by naumenko-sa** [comment]
Hi @sunliang3361 !

I think you need to decompress the transcriptome reference:

/n/scratch3/users/l/ls360/sc_woolf/config/sc-woolf.yaml:
` transcriptome_fasta: /n/scratch3/users/l/ls360/sc_woolf/data/gencode.vM24.transcripts.fa.gz`

S

**Comment by sunliang3361** [comment]
Thank you, that works.

**Comment by naumenko-sa** [comment]
ok, closing then. feel free to re-open if you still see issues!
