### ISSUE TITLE
Vcfanno error on hg38.

### ISSUE THREAD

**Issue by kokyriakidis** [bcbio/bcbio-nextgen#3308]
I am getting the following error running on hg38. I have both dbsnp-151 and dbsnp-153 files in the variation folder. 

Why it cannot find it and why it uses v151 instead of v153?

```
[2020-07-18T14:56Z] Timing: heterogeneity
[2020-07-18T14:56Z] Timing: population database
[2020-07-18T14:56Z] multiprocessing: prep_gemini_db
[2020-07-18T14:56Z] Not running gemini, not configured in tools_on: ERR1955323
Traceback (most recent call last):
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 187, in variant2pipeline
    samples = population.prep_db_parallel(samples, run_parallel)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/population.py", line 405, in prep_db_parallel
    output = parallel_fn("prep_gemini_db", to_process)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 765, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 387, in prep_gemini_db
    return population.prep_gemini_db(*args)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/population.py", line 42, in prep_gemini_db
    ann_vcf = run_vcfanno(gemini_vcf, data, decomposed)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/population.py", line 121, in run_vcfanno
    decomposed=decomposed)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/vcfanno.py", line 35, in run
    conffn = _combine_files(conf_fns, out_file, data, basepath is None)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/vcfanno.py", line 63, in _combine_files
    line = _fill_file_path(line, data)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/vcfanno.py", line 88, in _fill_file_path
    assert full_file, "Did not find vcfanno input file %s" % (orig_file)
AssertionError: Did not find vcfanno input file variation/dbsnp-151.vcf.gz
```

**Comment by amizeranschi** [comment]
See also: https://github.com/bcbio/bcbio-nextgen/issues/3256#issuecomment-657174276

**Comment by kokyriakidis** [comment]
Hmmm, gemini config looks for ```"file="variation/dbsnp-151.vcf.gz"```, which I have, but hg38-resources.yaml have: 
```
variation:
  dbsnp: ../variation/dbsnp-153.vcf.gz
```

**Comment by naumenko-sa** [comment]
Thanks for reporting!

They are synchronized for new installation/updates:

https://github.com/bcbio/bcbio-nextgen/blob/master/config/genomes/hg38-resources.yaml
https://github.com/bcbio/bcbio-nextgen/blob/master/config/vcfanno/hg38-gemini.conf
https://github.com/bcbio/bcbio-nextgen/blob/master/config/vcfanno/somatic.conf
https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/hg38/dbsnp.yaml

If we ever update it again, please commit all 4 changes.

S.
