### ISSUE TITLE
smith watermanAligner error for GATK

### ISSUE THREAD

**Issue by DiyaVaka** [bcbio/bcbio-nextgen#3312]
18:43:30.525 INFO  SmithWatermanAligner - Total compute time in java Smith-Waterman : 90.54 sec
18:43:30.526 INFO  HaplotypeCaller - Shutting down engine
[July 22, 2020 6:43:30 PM GMT] org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller done. Elapsed time: 9.17 minutes.
Runtime.totalMemory()=691404800
java.lang.IllegalStateException: Smith-Waterman alignment failure. Cigar = 245M with reference length 245 but expecting reference length of 275 ref = ACACAATATAGGCATTGCATACGCGTATACACACAATATAGGCATTGCATACGCGTATACACACAATATAGGCATTGCATACGCGTATACACACAATATAGGCATTGCATACGCGTATACACACAAAATAGGCATTGTATACGCGTATACACACAAAATAGGCATTGTATACGCGTATACACACAAAATAGGCATTGTATACGCGTATACACACAAAATAGGCATTGTATACGCGTATACAATATAGGCATTGTATACGCGTATACAATATAGGC path ACACAATATAGGCATTGCATACGCGTATACACACAATATAGGCATTGCATACGCGTATACACACAATATAGGCATTGCATACGCGTATACACACAAAATAGGCATTGCATACGCGTATACACACAAAATAGGCATTGTATACGCGTATACACACAAAATAGGCATTGTATACGCGTATACACACAAAATAGGCATTGTATACGCGTATACAATATATGCATTGTATACGCGTATACAATATATGC

        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.readthreading.ReadThreadingAssembler.assembleKmerGraphsAndHaplotypeCall(ReadThreadingAssembler.java:196)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.readthreading.ReadThreadingAssembler.runLocalAssembly(ReadThreadingAssembler.java:146)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.AssemblyBasedCallerUtils.assembleReads(AssemblyBasedCallerUtils.java:269)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerEngine.callRegion(HaplotypeCallerEngine.java:541)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller.apply(HaplotypeCaller.java:212)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:200)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:173)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1048)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
        at org.broadinstitute.hellbender.Main.main(Main.java:292)
Using GATK jar /usr/local/share/bcbio-nextgen/anaconda/share/gatk4-4.1.6.0-0/gatk-package-4.1.6.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xms681m -Xmx3181m -XX:+UseSerialGC -Djava.io.tmpdir=/mnt/work/bcbiotx/tmpe7ihoo4k -jar /usr/local/share/bcbio-nextgen/anaconda/share/gatk4-4.1.6.0-0/gatk-package-4.1.6.0-local.jar HaplotypeCaller -R /usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg38/seq/hg38.fa --annotation MappingQualityRankSumTest --annotation MappingQualityZero --annotation QualByDepth --annotation ReadPosRankSumTest --annotation RMSMappingQuality --annotation BaseQualityRankSumTest --annotation FisherStrand --annotation MappingQuality --annotation DepthPerAlleleBySample --annotation Coverage -I /mnt/work/align/DS182092_PKI107A12/DS182092_PKI107A12-sort-recal.bam -L /mnt/work/gatk-haplotype/chr4/DS182092_PKI107A12-chr4_129297700_150029888-regions.bed --interval-set-rule INTERSECTION --annotation ClippingRankSumTest --annotation DepthPerSampleHC --native-pair-hmm-threads 1 -ploidy 2 --output /mnt/work/bcbiotx/tmpe7ihoo4k/DS182092_PKI107A12-chr4_129297700_150029888.vcf.gz
' returned non-zero exit status 3.
' returned non-zero exit status 1.

Can you please help?

**Comment by roryk** [comment]
Could you share the YAML file you are using to run this? It's hard to debug without knowing what the run looks like. Thanks!

**Comment by DiyaVaka** [comment]
thank you but its fixed after i upgraded gatk to 4.1.18 and change the bcbio_system.yaml to point to the new version of GATK.

**Comment by roryk** [comment]
Thanks for following up! Glad this got resolved.
