### ISSUE TITLE
Error downloading cosmic references with prepare_cosmic.py

### ISSUE THREAD

**Issue by IvantheDugtrio** [bcbio/bcbio-nextgen#3314]
**Version info**
- bcbio-nextgen 1.2.3 - development release
- CentOS 8

**To Reproduce**
Exact bcbio command you have used:
```
export COSMIC_USER="my_email"
export COSMIC_PASS="my_password"
/staging/gtcmolecular/local/bin/bcbio_python /staging/gtcmolecular/tmpbcbio-install/cloudbiolinux/utils/prepare_cosmic.py 91 /staging/gtcmolecular/local/share/bcbio/
```
Your sample configuration file:
```
N/A
```

**Observed behavior**
Error message or bcbio output:
```
2020-07-23 18:14:40,161 [I] Beginning COSMIC v91 prep for GRCh37.
2020-07-23 18:14:40,161 [I] v91/GRCh37 files exist, please use the --clean flag to overwrite the existing files if you want to reinstall.
2020-07-23 18:14:40,161 [I] Downloading COSMIC VCF files.
2020-07-23 18:14:40,162 [I] Downloading https://cancer.sanger.ac.uk/cosmic/file_download/GRCh37/cosmic/v91/VCF/CosmicCodingMuts.vcf.gz
Traceback (most recent call last):
  File "/staging/gtcmolecular/tmpbcbio-install/cloudbiolinux/utils/prepare_cosmic.py", line 246, in <module>
    main(args.cosmic_version, args.bcbio_directory, args.overwrite, args.clean)
  File "/staging/gtcmolecular/tmpbcbio-install/cloudbiolinux/utils/prepare_cosmic.py", line 56, in main
    cosmic_vcf_files = get_cosmic_vcf_files(genome_build, cosmic_version, clean)
  File "/staging/gtcmolecular/tmpbcbio-install/cloudbiolinux/utils/prepare_cosmic.py", line 205, in get_cosmic_vcf_files
    download_url = r.json()["url"]
KeyError: 'url'
```

**Expected behavior**
This is my first time running the cosmic script so I am not sure what to expect other than all VCFs were downloaded and made available for use as annotation sources for GRCh37. 

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.
N/A

**Additional context**
I noticed that the URL to download the coding and non-coding VCFs manually is different than the URL in the script.

**Comment by naumenko-sa** [comment]
Hi @IvantheDugtrio !

I'm installing cosmic-91 right now and it passes this step.
COSMIC requires a not alpha-numeric characted, and I saw a similar error when I used `!` in the COSMIC_PASS.
`export COSMIC_PASS="pass\!"` gave me that error, as requirest did not return a result.
`export COSMIC_PASS='pass!'` worked.

Sergey

**Comment by IvantheDugtrio** [comment]
Hi @naumenko-sa !

I tested it and that looks to have been the whole issue. Thanks for the assistance!

Ivan
