### ISSUE TITLE
/bin/bash: line 1: 53677 Segmentation fault

### ISSUE THREAD

**Issue by tiger815** [bcbio/bcbio-nextgen#3337]
hi 

I'm a beginner for bcbio-nextgen pipeline. 

After installation, I've been attempting to run my WES data for testing.
Unfortunately, I got an error message.

Any help is greatly appreciated.
 
Thanks

Version info
Bcbio Version info : 1.2.3
Ubuntu 18.04 and 128G ram 

tiger815@shdeep:~/NGS/KSO/KSO/work$ bcbio_nextgen.py ../config/KSO.yaml -n 8
Running bcbio version: 1.2.3
global config: /data/home/tiger815/NGS/KSO/KSO/work/bcbio_system.yaml
run info config: /data/home/tiger815/NGS/KSO/KSO/config/KSO.yaml
[2020-09-03T02:35Z] System YAML configuration: /data/bcbio/galaxy/bcbio_system.yaml.
[2020-09-03T02:35Z] Locale set to C.UTF-8.
[2020-09-03T02:35Z] Resource requests: bwa, gatk, sambamba, samtools; memory: 3.00, 3.00, 3.00, 3.00; cores: 8, 8, 8, 8
[2020-09-03T02:35Z] Configuring 1 jobs to run, using 8 cores each with 24.1g of memory reserved for each job
[2020-09-03T02:35Z] Timing: organize samples
[2020-09-03T02:35Z] multiprocessing: organize_samples
[2020-09-03T02:35Z] Using input YAML configuration: /data/home/tiger815/NGS/KSO/KSO/config/KSO.yaml
[2020-09-03T02:35Z] Checking sample YAML configuration: /data/home/tiger815/NGS/KSO/KSO/config/KSO.yaml
[2020-09-03T02:35Z] Retreiving program versions from /data/bcbio/manifest/python-packages.yaml.
[2020-09-03T02:35Z] Retreiving program versions from /data/bcbio/manifest/r-packages.yaml.
[2020-09-03T02:35Z] Testing minimum versions of installed programs
[2020-09-03T02:35Z] Timing: alignment preparation
[2020-09-03T02:35Z] multiprocessing: prep_align_inputs
[2020-09-03T02:35Z] Skipping trimming of KSO.
[2020-09-03T02:35Z] Resource requests: ; memory: 1.00; cores: 1
[2020-09-03T02:35Z] Configuring 2 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2020-09-03T02:35Z] multiprocessing: disambiguate_split
[2020-09-03T02:35Z] Timing: alignment
[2020-09-03T02:35Z] multiprocessing: process_alignment
[2020-09-03T02:35Z] Aligning lane KSO with bwa aligner
[2020-09-03T02:35Z] bwa mem alignment from fastq: KSO
[2020-09-03T02:35Z] /bin/bash: line 1: 53677 Segmentation fault      (core dumped) /data/bcbio/galaxy/../anaconda/bin/bwa mem -c 250 -M -t 8 -R '@RG\tID:KSO\tPL:illumina\tPU:KSO\tSM:KSO' -v 1 /data/bcbio/genomes/Hsapiens/hg38/bwa/hg38.fa <(grabix grab /data/home/tiger815/NGS/KSO/KSO/work/align_prep/KSO_1.fastq.gz 1 80000000) <(grabix grab /data/home/tiger815/NGS/KSO/KSO/work/align_prep/KSO_2.fastq.gz 1 80000000)
[2020-09-03T02:35Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && /data/bcbio/galaxy/../anaconda/bin/bwa mem   -c 250 -M -t 8  -R '@RG\tID:KSO\tPL:illumina\tPU:KSO\tSM:KSO' -v 1 /data/bcbio/genomes/Hsapiens/hg38/bwa/hg38.fa <(grabix grab /data/home/tiger815/NGS/KSO/KSO/work/align_prep/KSO_1.fastq.gz 1 80000000) <(grabix grab /data/home/tiger815/NGS/KSO/KSO/work/align_prep/KSO_2.fastq.gz 1 80000000)  | /data/bcbio/galaxy/../anaconda/bin/samtools sort -n -@ 8 -m 1G -O bam -T /data/home/tiger815/NGS/KSO/KSO/work/bcbiotx/tmpns14391g/KSO-sort-1_80000000-sorttmp-namesort -o /data/home/tiger815/NGS/KSO/KSO/work/bcbiotx/tmpns14391g/KSO-sort-1_80000000.bam -
/bin/bash: line 1: 53677 Segmentation fault      (core dumped) /data/bcbio/galaxy/../anaconda/bin/bwa mem -c 250 -M -t 8 -R '@RG\tID:KSO\tPL:illumina\tPU:KSO\tSM:KSO' -v 1 /data/bcbio/genomes/Hsapiens/hg38/bwa/hg38.fa <(grabix grab /data/home/tiger815/NGS/KSO/KSO/work/align_prep/KSO_1.fastq.gz 1 80000000) <(grabix grab /data/home/tiger815/NGS/KSO/KSO/work/align_prep/KSO_2.fastq.gz 1 80000000)
     53678 Done                    | /data/bcbio/galaxy/../anaconda/bin/samtools sort -n -@ 8 -m 1G -O bam -T /data/home/tiger815/NGS/KSO/KSO/work/bcbiotx/tmpns14391g/KSO-sort-1_80000000-sorttmp-namesort -o /data/home/tiger815/NGS/KSO/KSO/work/bcbiotx/tmpns14391g/KSO-sort-1_80000000.bam -
' returned non-zero exit status 139.
Traceback (most recent call last):
  File "/data/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/data/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 133, in variant2pipeline
    samples = run_parallel("process_alignment", samples)
  File "/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/data/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "/data/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "/data/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 765, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/data/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/data/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/data/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "/data/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 128, in process_alignment
    return sample.process_alignment(*args)
  File "/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sample.py", line 128, in process_alignment
    data = align_to_sort_bam(fastq1, fastq2, aligner, data)
  File "/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/alignment.py", line 87, in align_to_sort_bam
    names, align_dir, data)
  File "/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/alignment.py", line 164, in _align_from_fastq
    out = align_fn(fastq1, fastq2, align_ref, names, align_dir, data)
  File "/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/ngsalign/bwa.py", line 170, in align_pipe
    names, rg_info, data)
  File "/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/ngsalign/bwa.py", line 181, in _align_mem
    [do.file_nonempty(tx_out_file), do.file_reasonable_size(tx_out_file, fastq_file)])
  File "/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/data/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && /data/bcbio/galaxy/../anaconda/bin/bwa mem   -c 250 -M -t 8  -R '@RG\tID:KSO\tPL:illumina\tPU:KSO\tSM:KSO' -v 1 /data/bcbio/genomes/Hsapiens/hg38/bwa/hg38.fa <(grabix grab /data/home/tiger815/NGS/KSO/KSO/work/align_prep/KSO_1.fastq.gz 1 80000000) <(grabix grab /data/home/tiger815/NGS/KSO/KSO/work/align_prep/KSO_2.fastq.gz 1 80000000)  | /data/bcbio/galaxy/../anaconda/bin/samtools sort -n -@ 8 -m 1G -O bam -T /data/home/tiger815/NGS/KSO/KSO/work/bcbiotx/tmpns14391g/KSO-sort-1_80000000-sorttmp-namesort -o /data/home/tiger815/NGS/KSO/KSO/work/bcbiotx/tmpns14391g/KSO-sort-1_80000000.bam -
/bin/bash: line 1: 53677 Segmentation fault      (core dumped) /data/bcbio/galaxy/../anaconda/bin/bwa mem -c 250 -M -t 8 -R '@RG\tID:KSO\tPL:illumina\tPU:KSO\tSM:KSO' -v 1 /data/bcbio/genomes/Hsapiens/hg38/bwa/hg38.fa <(grabix grab /data/home/tiger815/NGS/KSO/KSO/work/align_prep/KSO_1.fastq.gz 1 80000000) <(grabix grab /data/home/tiger815/NGS/KSO/KSO/work/align_prep/KSO_2.fastq.gz 1 80000000)
     53678 Done                    | /data/bcbio/galaxy/../anaconda/bin/samtools sort -n -@ 8 -m 1G -O bam -T /data/home/tiger815/NGS/KSO/KSO/work/bcbiotx/tmpns14391g/KSO-sort-1_80000000-sorttmp-namesort -o /data/home/tiger815/NGS/KSO/KSO/work/bcbiotx/tmpns14391g/KSO-sort-1_80000000.bam -
' returned non-zero exit status 139.

**Comment by naumenko-sa** [comment]
Hi @tiger815 !

You got a SegmentationFault when aligning with bwa and sorting with samtools.
You may try to give more RAM to these jobs (in the yaml)
https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#resources
```
resources:
  samtools:
    cores: 8
    memory: 4G
```
S

**Comment by tiger815** [comment]
Hi @naumenko-sa . 

Thank you very much for your reply.

I tested it, and even though I modified the resources as recommended, the same error still occurred.
However, when I ran the same job on a server with 1T RAM, the job worked fine.
Could you please recommend the minimum amount of RAM to run the bcbio pipeline?

Thanks!

**Comment by roryk** [comment]
You should have been fine on the original machine-- it looks like you are running these jobs in interactive mode on your cluster, is that the case? If so are you asking for enough RAM when you submit the interactive job?

**Comment by naumenko-sa** [comment]
Thanks everyone! Closing for now. Please let us know if you are experiencing this issue!
