### ISSUE TITLE
gatk spark errors

### ISSUE THREAD

**Issue by DiyaVaka** [bcbio/bcbio-nextgen#3346]
Hi,

I am running into error with gatk haplotype caller

Using GATK jar /data/anaconda/share/gatk4-4.1.8.1-0/gatk-package-4.1.8.1-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xms750m -Xmx42998m -Djava.io.tmpdir=/data/samples/1G_bcbio/bcbiotx/tmpc1946ekl -jar /data/anaconda/share/gatk4-4.1.8.1-0/gatk-package-4.1.8.1-local.jar BaseRecalibratorSpark -I /data/samples/1G_bcbio/align/1G/1G-sort.bam --output /data/samples/1G_bcbio/bcbiotx/tmpc1946ekl/1G-sort-recal.grp --reference /data/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --spark-master local[15] --conf spark.driver.host=localhost --conf spark.network.timeout=800 --conf spark.executor.heartbeatInterval=100 --conf spark.local.dir=/data/samples/1G_bcbio/bcbiotx/tmpc1946ekl --known-sites /data/genomes/Hsapiens/GRCh37/variation/dbsnp-151.vcf.gz -L /data/samples/1G_bcbio/align/1G/1G-sort-callable_sample.bed --interval-set-rule INTERSECTION
' returned non-zero exit status 52.
[1]+  Exit 1                  nohup /data/tools/bin/bcbio_nextgen.py -n 15 ./sample.yaml
[ec2-user@ip-172-31-45-1 1G_bcbio]$ vi nohup.out 

        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
20/09/24 18:17:20 WARN SparkContext: Ignoring Exception while stopping SparkContext from shutdown hook
java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1223)
        at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:340)
        at java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:339)
        at org.apache.spark.scheduler.AsyncEventQueue.stop(AsyncEventQueue.scala:130)
        at org.apache.spark.scheduler.LiveListenerBus$$anonfun$stop$1.apply(LiveListenerBus.scala:218)
        at org.apache.spark.scheduler.LiveListenerBus$$anonfun$stop$1.apply(LiveListenerBus.scala:218)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at org.apache.spark.scheduler.LiveListenerBus.stop(LiveListenerBus.scala:218)
        at org.apache.spark.SparkContext$$anonfun$stop$7.apply$mcV$sp(SparkContext.scala:1955)
        at org.apache.spark.util.Utils$.tryLogNonFatalError(Utils.scala:1340)
        at org.apache.spark.SparkContext.stop(SparkContext.scala:1954)
        at org.apache.spark.SparkContext$$anonfun$2.apply$mcV$sp(SparkContext.scala:575)
        at org.apache.spark.util.SparkShutdownHook.run(ShutdownHookManager.scala:216)
        at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ShutdownHookManager.scala:188)
        at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1$$anonfun$apply$mcV$sp$1.apply(ShutdownHookManager.scala:188)
        at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1$$anonfun$apply$mcV$sp$1.apply(ShutdownHookManager.scala:188)
        at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1945)
        at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1.apply$mcV$sp(ShutdownHookManager.scala:188)
        at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1.apply(ShutdownHookManager.scala:188)
        at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1.apply(ShutdownHookManager.scala:188)
        at scala.util.Try$.apply(Try.scala:192)
        at org.apache.spark.util.SparkShutdownHookManager.runAll(ShutdownHookManager.scala:188)
        at org.apache.spark.util.SparkShutdownHookManager$$anon$2.run(ShutdownHookManager.scala:178)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
20/09/24 18:17:20 INFO DiskBlockManager: Shutdown hook called
20/09/24 18:17:20 INFO ShutdownHookManager: Shutdown hook called
20/09/24 18:17:20 INFO ShutdownHookManager: Deleting directory /data/samples/1G_bcbio/bcbiotx/tmpc1946ekl/spark-2f44e298-7328-473a-8c23-ebdab597b0a6/userFiles-c9316af7-d3ed-4560-ad14-154db8be23be
20/09/24 18:17:47 INFO ShutdownHookManager: Deleting directory /data/samples/1G_bcbio/bcbiotx/tmpc1946ekl/spark-2f44e298-7328-473a-8c23-ebdab597b0a6
Using GATK jar /data/anaconda/share/gatk4-4.1.8.1-0/gatk-package-4.1.8.1-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xms750m -Xmx42998m -Djava.io.tmpdir=/data/samples/1G_bcbio/bcbiotx/tmpc1946ekl -jar /data/anaconda/share/gatk4-4.1.8.1-0/gatk-package-4.1.8.1-local.jar BaseRecalibratorSpark -I /data/samples/1G_bcbio/align/1G/1G-sort.bam --output /data/samples/1G_bcbio/bcbiotx/tmpc1946ekl/1G-sort-recal.grp --reference /data/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --spark-master local[15] --conf spark.driver.host=localhost --conf spark.network.timeout=800 --conf spark.executor.heartbeatInterval=100 --conf spark.local.dir=/data/samples/1G_bcbio/bcbiotx/tmpc1946ekl --known-sites /data/genomes/Hsapiens/GRCh37/variation/dbsnp-151.vcf.gz -L /data/samples/1G_bcbio/align/1G/1G-sort-callable_sample.bed --interval-set-rule INTERSECTION
' returned non-zero exit status 52.

**Comment by roryk** [comment]
It is hard to tell without having the whole logs, but I think you are probably running out of memory. exit status 52 from spark is an OOM error.

I'd skip doing the BaseRecalibration, FWIW. It doesn't actually do very much. The Broad just tweeted today they are taking it out of their best practice pipeline (https://twitter.com/VdaGeraldine/status/1309142970973728770) so you can safely skip it IMO.
