### ISSUE TITLE
Aligner cannot find genome files

### ISSUE THREAD

**Issue by jrozycka** [bcbio/bcbio-nextgen#3369]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.4
- OS name and version (`lsb_release -ds`): Ubuntu 20.04.1 LTS

**To Reproduce**
Exact bcbio command you have used:
home/julia/Documents/bcbio/anaconda/bin/bcbio_nextgen.py upgrade -u skip --genomes hg38 --aligners star
/home/julia/Documents/bcbio/anaconda/bin/bcbio_nextgen.py /home/julia/Documents/bcbio/project1/seqc/config/seqc.yaml -n 1

Your sample configuration file:
```yaml
details:
- algorithm:
    aligner: star
    quality_format: Standard
    strandedness: unstranded
  analysis: RNA-seq
  description: mock1
  files:
  - /home/julia/Documents/bcbio/project1/input/SRR11934379.fastq
  genome_build: hg38
  metadata:
    panel: mock
- algorithm:
    aligner: star
    quality_format: Standard
    strandedness: unstranded
  analysis: RNA-seq
  description: sars1
  files:
  - /home/julia/Documents/bcbio/project1/input/SRR11934388.fastq
  genome_build: hg38
  metadata:
    panel: sars
fc_name: seqc
upload:
  dir: ../final
```

**Observed behavior**
Error message or bcbio output:

```
Running bcbio version: 1.2.4
global config: /home/julia/Documents/bcbio/project1/seqc/work/bcbio_system.yaml
run info config: /home/julia/Documents/bcbio/project1/seqc/config/seqc.yaml
[2020-11-09T17:56Z] System YAML configuration: /home/julia/Documents/bcbio/galaxy/bcbio_system.yaml.
[2020-11-09T17:56Z] Locale set to C.UTF-8.
[2020-11-09T17:56Z] Resource requests: picard; memory: 4.00; cores: 16
[2020-11-09T17:56Z] Configuring 1 jobs to run, using 1 cores each with 4.00g of memory reserved for each job
[2020-11-09T17:56Z] Timing: organize samples
[2020-11-09T17:56Z] multiprocessing: organize_samples
[2020-11-09T17:56Z] Using input YAML configuration: /home/julia/Documents/bcbio/project1/seqc/config/seqc.yaml
[2020-11-09T17:56Z] Checking sample YAML configuration: /home/julia/Documents/bcbio/project1/seqc/config/seqc.yaml
[2020-11-09T17:56Z] Retreiving program versions from /home/julia/Documents/bcbio/manifest/python-packages.yaml.
[2020-11-09T17:56Z] Retreiving program versions from /home/julia/Documents/bcbio/manifest/r-packages.yaml.
[2020-11-09T17:56Z] Testing minimum versions of installed programs
[2020-11-09T17:56Z] multiprocessing: prepare_sample
[2020-11-09T17:56Z] Preparing mock1
[2020-11-09T17:56Z] Converting /home/julia/Documents/bcbio/project1/input/SRR11934379.fastq to Sanger format.
[2020-11-09T18:06Z] Preparing sars1
[2020-11-09T18:06Z] Converting /home/julia/Documents/bcbio/project1/input/SRR11934388.fastq to Sanger format.
[2020-11-09T18:12Z] Resource requests: picard, samtools, star; memory: 4.00, 4.00, 4.00; cores: 16, 16, 16
[2020-11-09T18:12Z] Configuring 1 jobs to run, using 1 cores each with 4.00g of memory reserved for each job
[2020-11-09T18:12Z] Timing: alignment
[2020-11-09T18:12Z] multiprocessing: disambiguate_split
[2020-11-09T18:12Z] multiprocessing: process_alignment
[2020-11-09T18:12Z] Aligning lane mock1 with star aligner
Traceback (most recent call last):
  File "/home/julia/Documents/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/home/julia/Documents/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 246, in rnaseqpipeline
    samples = run_parallel("process_alignment", samples)
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1048, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 866, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 784, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 128, in process_alignment
    return sample.process_alignment(*args)
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sample.py", line 132, in process_alignment
    data = align_to_sort_bam(fastq1, fastq2, aligner, data)
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/alignment.py", line 87, in align_to_sort_bam
    names, align_dir, data)
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/alignment.py", line 164, in _align_from_fastq
    out = align_fn(fastq1, fastq2, align_ref, names, align_dir, data)
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/bcbio/ngsalign/star.py", line 65, in align
    if index_has_alts(ref_file):
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/bcbio/ngsalign/star.py", line 330, in index_has_alts
    with open(name_file) as in_handle:
FileNotFoundError: [Errno 2] No such file or directory: '/home/julia/Documents/bcbio/genomes/Hsapiens/hg38/star/chrName.txt'
```

So I found the code that was causing this and commented it out:
```python
    if index_has_alts(ref_file):
        logger.error(
            "STAR is being run on an index with ALTs which STAR is not "
            "designed for. Please remake your STAR index or use an ALT-aware "
            "aligner like hisat2")
        sys.exit(1)
```
in /home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/bcbio/ngsalign/star.py because from what I understand the index created by the pipeline doesn't have ALTs and got: 

```
Running bcbio version: 1.2.4
global config: /home/julia/Documents/bcbio/project1/seqc/work/bcbio_system.yaml
run info config: /home/julia/Documents/bcbio/project1/seqc/config/seqc.yaml
[2020-11-09T17:19Z] System YAML configuration: /home/julia/Documents/bcbio/galaxy/bcbio_system.yaml.
[2020-11-09T17:19Z] Locale set to C.UTF-8.
[2020-11-09T17:19Z] Resource requests: picard; memory: 4.00; cores: 16
[2020-11-09T17:19Z] Configuring 1 jobs to run, using 1 cores each with 4.00g of memory reserved for each job
[2020-11-09T17:19Z] Timing: organize samples
[2020-11-09T17:19Z] multiprocessing: organize_samples
[2020-11-09T17:19Z] Using input YAML configuration: /home/julia/Documents/bcbio/project1/seqc/config/seqc.yaml
[2020-11-09T17:19Z] Checking sample YAML configuration: /home/julia/Documents/bcbio/project1/seqc/config/seqc.yaml
[2020-11-09T17:19Z] Retreiving program versions from /home/julia/Documents/bcbio/manifest/python-packages.yaml.
[2020-11-09T17:19Z] Retreiving program versions from /home/julia/Documents/bcbio/manifest/r-packages.yaml.
[2020-11-09T17:19Z] Testing minimum versions of installed programs
[2020-11-09T17:19Z] multiprocessing: prepare_sample
[2020-11-09T17:19Z] Preparing mock1
[2020-11-09T17:19Z] Converting /home/julia/Documents/bcbio/project1/input/SRR11934379.fastq to Sanger format.
[2020-11-09T17:28Z] Preparing sars1
[2020-11-09T17:28Z] Converting /home/julia/Documents/bcbio/project1/input/SRR11934388.fastq to Sanger format.
[2020-11-09T17:36Z] Resource requests: picard, samtools, star; memory: 4.00, 4.00, 4.00; cores: 16, 16, 16
[2020-11-09T17:36Z] Configuring 1 jobs to run, using 1 cores each with 4.00g of memory reserved for each job
[2020-11-09T17:36Z] Timing: alignment
[2020-11-09T17:36Z] multiprocessing: disambiguate_split
[2020-11-09T17:36Z] multiprocessing: process_alignment
[2020-11-09T17:36Z] Aligning lane mock1 with star aligner
[2020-11-09T17:36Z] Running 1st pass of STAR aligner on /home/julia/Documents/bcbio/project1/seqc/work/fastq_convert/SRR11934379.groom.fastq.gz and /home/julia/Documents/bcbio/genomes/Hsapiens/hg38/star/
[2020-11-09T17:36Z] EXITING because of FATAL ERROR: could not open genome file /home/julia/Documents/bcbio/genomes/Hsapiens/hg38/star//genomeParameters.txt
[2020-11-09T17:36Z] SOLUTION: check that the path to genome files, specified in --genomeDir is correct and the files are present, and have user read permsissions
[2020-11-09T17:36Z] Nov 09 18:36:18 ...... FATAL ERROR, exiting
[2020-11-09T17:36Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /home/julia/Documents/bcbio/galaxy/../anaconda/bin/STAR --genomeDir /home/julia/Documents/bcbio/genomes/Hsapiens/hg38/star/ --readFilesIn <(gunzip -c /home/julia/Documents/bcbio/project1/seqc/work/fastq_convert/SRR11934379.groom.fastq.gz) --runThreadN 1 --outFileNamePrefix /home/julia/Documents/bcbio/project1/seqc/work/bcbiotx/tmp2k15v5e0/mock11pass/mock1 --outReadsUnmapped Fastx --outFilterMultimapNmax 10 --outStd BAM_Unsorted  --limitOutSJcollapsed 2000000 --outSAMtype BAM Unsorted --outSAMmapqUnique 60 --outSAMunmapped Within --outSAMattributes NH HI NM MD AS  --sjdbGTFfile /home/julia/Documents/bcbio/genomes/Hsapiens/hg38/rnaseq/ref-transcripts.gtf  --sjdbOverhang 150  --outSAMattrRGline ID:mock1 PL:illumina PU:mock1 SM:mock1  --outSAMstrandField intronMotif  --quantMode TranscriptomeSAM  | /home/julia/Documents/bcbio/galaxy/../anaconda/bin/samtools sort -@ 1 -m 2G  -T /home/julia/Documents/bcbio/project1/seqc/work/bcbiotx/tmp2k15v5e0/mock11pass/mock1_star/mock1-sorttmp -o /home/julia/Documents/bcbio/project1/seqc/work/bcbiotx/tmp2k15v5e0/mock11pass/mock1_star/mock1.bam /dev/stdin > /home/julia/Documents/bcbio/project1/seqc/work/bcbiotx/tmp2k15v5e0/mock11pass/mock1_star/mock1.bam 
EXITING because of FATAL ERROR: could not open genome file /home/julia/Documents/bcbio/genomes/Hsapiens/hg38/star//genomeParameters.txt
SOLUTION: check that the path to genome files, specified in --genomeDir is correct and the files are present, and have user read permsissions
Nov 09 18:36:18 ...... FATAL ERROR, exiting
' returned non-zero exit status 105.
Traceback (most recent call last):
  File "/home/julia/Documents/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/home/julia/Documents/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 246, in rnaseqpipeline
    samples = run_parallel("process_alignment", samples)
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1048, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 866, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 784, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 128, in process_alignment
    return sample.process_alignment(*args)
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sample.py", line 132, in process_alignment
    data = align_to_sort_bam(fastq1, fastq2, aligner, data)
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/alignment.py", line 87, in align_to_sort_bam
    names, align_dir, data)
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/alignment.py", line 164, in _align_from_fastq
    out = align_fn(fastq1, fastq2, align_ref, names, align_dir, data)
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/bcbio/ngsalign/star.py", line 118, in align
    do.run(cmd.format(**locals()), run_message, None)
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/julia/Documents/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /home/julia/Documents/bcbio/galaxy/../anaconda/bin/STAR --genomeDir /home/julia/Documents/bcbio/genomes/Hsapiens/hg38/star/ --readFilesIn <(gunzip -c /home/julia/Documents/bcbio/project1/seqc/work/fastq_convert/SRR11934379.groom.fastq.gz) --runThreadN 1 --outFileNamePrefix /home/julia/Documents/bcbio/project1/seqc/work/bcbiotx/tmp2k15v5e0/mock11pass/mock1 --outReadsUnmapped Fastx --outFilterMultimapNmax 10 --outStd BAM_Unsorted  --limitOutSJcollapsed 2000000 --outSAMtype BAM Unsorted --outSAMmapqUnique 60 --outSAMunmapped Within --outSAMattributes NH HI NM MD AS  --sjdbGTFfile /home/julia/Documents/bcbio/genomes/Hsapiens/hg38/rnaseq/ref-transcripts.gtf  --sjdbOverhang 150  --outSAMattrRGline ID:mock1 PL:illumina PU:mock1 SM:mock1  --outSAMstrandField intronMotif  --quantMode TranscriptomeSAM  | /home/julia/Documents/bcbio/galaxy/../anaconda/bin/samtools sort -@ 1 -m 2G  -T /home/julia/Documents/bcbio/project1/seqc/work/bcbiotx/tmp2k15v5e0/mock11pass/mock1_star/mock1-sorttmp -o /home/julia/Documents/bcbio/project1/seqc/work/bcbiotx/tmp2k15v5e0/mock11pass/mock1_star/mock1.bam /dev/stdin > /home/julia/Documents/bcbio/project1/seqc/work/bcbiotx/tmp2k15v5e0/mock11pass/mock1_star/mock1.bam 
EXITING because of FATAL ERROR: could not open genome file /home/julia/Documents/bcbio/genomes/Hsapiens/hg38/star//genomeParameters.txt
SOLUTION: check that the path to genome files, specified in --genomeDir is correct and the files are present, and have user read permsissions
Nov 09 18:36:18 ...... FATAL ERROR, exiting
' returned non-zero exit status 105.
```

```

**Expected behavior**
A clear and concise description of what you expected to happen.

Clearly either the --genomeDir argument is incorrect or some files are missing in this directory (there are .fa files and indexes in /home/julia/Documents/bcbio/genomes/Hsapiens/hg38/seq and at some point I even copied all those files to the /hg38/star folder, but that didn't help). I was trying to follow the Bulk RNA-seq user case as closely as I could, just with different data. I don't really understand what more should I do to point the location of genome files to the aligner, or maybe download the genome data in some other way.
Also probably unrelated, but the message sometimes mentions using 16 cores, although I explicitly specified to use one and my computer only has 4.

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.

**Additional context**
Add any other context about the problem here.
I am working on a laptop with just 4 cores, not sure how many would be best for my analyses. Also tried the same with hisat2 instead of star, which also couldn't see the genome files and the error message was pretty similar and with bwa, but it seemed to run out of memory.

**Comment by naumenko-sa** [comment]
Hi Julia @jrozycka !

Sorry - your issue was left unanswered.

1. Could you list the content of `/home/julia/Documents/bcbio/genomes/Hsapiens/hg38/star`? Check if STAR index is installed.
2. STAR requires up to 30G of RAM, so running it on a laptop could be problematic.
3. Resources requested (16 cores for picard) are defined in `/home/julia/Documents/bcbio/galaxy/bcbio_system.yaml` (default:)
it then adjusted by the actual amount of cores you allocated to bcbio (-n 1):
```Configuring 1 jobs to run, using 1 cores each with 4.00g of memory reserved for each job```
4. RNA-seq runs of single-ended reads (one fastq file) could be problematic as well. Paired-end data is more standard.

SN

**Comment by naumenko-sa** [comment]
@jrozycka please feel free to re-open if there is a follow-up.
