### ISSUE TITLE
Unit test failure popping up for fastrnaseq check

### ISSUE THREAD

**Issue by mjsteinbaugh** [bcbio/bcbio-nextgen#3372]
I'm seeing an issue related to encoding pop up in the bcbio unit tests, when running inside the Docker images on Quay.

Here's a reproducible example:

```sh
image="quay.io/bcbio/bcbio-rnaseq:1.2.3-2d6a5bb"
docker pull "$image"
docker run -it "$image"

cd /tmp || exit 1
wget https://github.com/bcbio/bcbio-nextgen/archive/v1.2.3.tar.gz
tar -xzvf v1.2.3.tar.gz
cd bcbio-nextgen-1.2.3/tests || exit 1
./run_tests.sh fastrnaseq
```

```
[2020-11-12T17:42Z] Combining tx2gene CSV files.
[2020-11-12T17:42Z] Loading tximport.
[2020-11-12T17:42Z] Error in library(tidyverse) : there is no package called \u2018tidyverse\u2019
[2020-11-12T17:42Z] Execution halted
[2020-11-12T17:42Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command '/usr/local/share/bcbio-nextgen/anaconda/bin/Rscript --vanilla -e library(tidyverse);salmon_files = list.files("/tmp/bcbio-nextgen-1.2.3/tests/test_automated_output/salmon", pattern="quant.sf", recursive=TRUE, full.names=TRUE);tx2gene = readr::read_csv("/tmp/bcbio-nextgen-1.2.3/tests/test_automated_output/inputs/transcriptome/tx2gene.csv", col_names=c("transcript", "gene")); samples = basename(dirname(salmon_files));names(salmon_files) = samples;txi = tximport::tximport(salmon_files, type="salmon", tx2gene=tx2gene, countsFromAbundance="lengthScaledTPM");readr::write_csv(txi$counts %>% as.data.frame() %>% tibble::rownames_to_column("gene"), "/tmp/bcbio-nextgen-1.2.3/tests/test_automated_output/bcbiotx/tmp1sppdsm9/tximport-counts.csv");readr::write_csv(txi$abundance %>% as.data.frame() %>% tibble::rownames_to_column("gene"), "/tmp/bcbio-nextgen-1.2.3/tests/test_automated_output/bcbiotx/tmp3lnwuolk/tximport-tpm.csv");
Error in library(tidyverse) : there is no package called \u2018tidyverse\u2019
Execution halted
' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 294, in fastrnaseqpipeline
    samples = rnaseq.combine_files(samples)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/pipeline/rnaseq.py", line 482, in combine_files
    tximport = load_tximport(data)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/pipeline/rnaseq.py", line 549, in load_tximport
    do.run([rcmd, "--vanilla", "-e", render_string], f"Loading tximport.")
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command '/usr/local/share/bcbio-nextgen/anaconda/bin/Rscript --vanilla -e library(tidyverse);salmon_files = list.files("/tmp/bcbio-nextgen-1.2.3/tests/test_automated_output/salmon", pattern="quant.sf", recursive=TRUE, full.names=TRUE);tx2gene = readr::read_csv("/tmp/bcbio-nextgen-1.2.3/tests/test_automated_output/inputs/transcriptome/tx2gene.csv", col_names=c("transcript", "gene")); samples = basename(dirname(salmon_files));names(salmon_files) = samples;txi = tximport::tximport(salmon_files, type="salmon", tx2gene=tx2gene, countsFromAbundance="lengthScaledTPM");readr::write_csv(txi$counts %>% as.data.frame() %>% tibble::rownames_to_column("gene"), "/tmp/bcbio-nextgen-1.2.3/tests/test_automated_output/bcbiotx/tmp1sppdsm9/tximport-counts.csv");readr::write_csv(txi$abundance %>% as.data.frame() %>% tibble::rownames_to_column("gene"), "/tmp/bcbio-nextgen-1.2.3/tests/test_automated_output/bcbiotx/tmp3lnwuolk/tximport-tpm.csv");
Error in library(tidyverse) : there is no package called \u2018tidyverse\u2019
Execution halted
' returned non-zero exit status 1.
FAILED
```

**Comment by mjsteinbaugh** [comment]
This also reproduces in the v1.2.2 Docker image.

**Comment by mjsteinbaugh** [comment]
I'm seeing a different but related R error pop up in my Docker image:

```sh
image="docker.io/acidgenomics/bcbio:stable-20201112"
docker pull "$image"
docker run -it "$image"

export PATH="/usr/local/koopa/opt/bcbio/stable/tools/bin:${PATH}"
cd /tmp || exit 1
git clone https://github.com/bcbio/bcbio-nextgen
cd bcbio-nextgen/tests || exit 1
./run_tests.sh fastrnaseq
```

```
[...]
[2020-11-13T12:58Z] Combining tx2gene CSV files.
[2020-11-13T12:58Z] Loading tximport.
[2020-11-13T12:58Z] ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──
[2020-11-13T12:58Z] ✔ ggplot2 3.3.0     ✔ purrr   0.3.4
[2020-11-13T12:58Z] ✔ tibble  3.0.1     ✔ dplyr   0.8.5
[2020-11-13T12:58Z] ✔ tidyr   1.0.2     ✔ stringr 1.4.0
[2020-11-13T12:58Z] ✔ readr   1.3.1     ✔ forcats 0.5.0
[2020-11-13T12:58Z] ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
[2020-11-13T12:58Z] ✖ dplyr::filter() masks stats::filter()
[2020-11-13T12:58Z] ✖ dplyr::lag()    masks stats::lag()
[2020-11-13T12:58Z] Error: Unknown TZ UTC
[2020-11-13T12:58Z] In addition: Warning message:
[2020-11-13T12:58Z] In OlsonNames() : no Olson database found
[2020-11-13T12:58Z] Execution halted
[2020-11-13T12:58Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command '/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/bin/Rscript --vanilla -e library(tidyverse);salmon_files = list.files("/tmp/bcbio_osdbigx3/test_automated_output/salmon", pattern="quant.sf", recursive=TRUE, full.names=TRUE);tx2gene = readr::read_csv("/tmp/bcbio_osdbigx3/test_automated_output/inputs/transcriptome/tx2gene.csv", col_names=c("transcript", "gene")); samples = basename(dirname(salmon_files));names(salmon_files) = samples;txi = tximport::tximport(salmon_files, type="salmon", tx2gene=tx2gene, countsFromAbundance="lengthScaledTPM");readr::write_csv(txi$counts %>% as.data.frame() %>% tibble::rownames_to_column("gene"), "/tmp/bcbio_osdbigx3/test_automated_output/bcbiotx/tmpgj0v9qts/tximport-counts.csv");readr::write_csv(txi$abundance %>% as.data.frame() %>% tibble::rownames_to_column("gene"), "/tmp/bcbio_osdbigx3/test_automated_output/bcbiotx/tmp9ahto8ej/tximport-tpm.csv");
── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──
✔ ggplot2 3.3.0     ✔ purrr   0.3.4
✔ tibble  3.0.1     ✔ dplyr   0.8.5
✔ tidyr   1.0.2     ✔ stringr 1.4.0
✔ readr   1.3.1     ✔ forcats 0.5.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
Error: Unknown TZ UTC
In addition: Warning message:
In OlsonNames() : no Olson database found
Execution halted
' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/local/koopa/opt/bcbio/stable/tools/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/usr/local/koopa/opt/bcbio/stable/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 297, in fastrnaseqpipeline
    samples = rnaseq.combine_files(samples)
  File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/lib/python3.6/site-packages/bcbio/pipeline/rnaseq.py", line 482, in combine_files
    tximport = load_tximport(data)
  File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/lib/python3.6/site-packages/bcbio/pipeline/rnaseq.py", line 549, in load_tximport
    do.run([rcmd, "--vanilla", "-e", render_string], f"Loading tximport.")
  File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command '/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/bin/Rscript --vanilla -e library(tidyverse);salmon_files = list.files("/tmp/bcbio_osdbigx3/test_automated_output/salmon", pattern="quant.sf", recursive=TRUE, full.names=TRUE);tx2gene = readr::read_csv("/tmp/bcbio_osdbigx3/test_automated_output/inputs/transcriptome/tx2gene.csv", col_names=c("transcript", "gene")); samples = basename(dirname(salmon_files));names(salmon_files) = samples;txi = tximport::tximport(salmon_files, type="salmon", tx2gene=tx2gene, countsFromAbundance="lengthScaledTPM");readr::write_csv(txi$counts %>% as.data.frame() %>% tibble::rownames_to_column("gene"), "/tmp/bcbio_osdbigx3/test_automated_output/bcbiotx/tmpgj0v9qts/tximport-counts.csv");readr::write_csv(txi$abundance %>% as.data.frame() %>% tibble::rownames_to_column("gene"), "/tmp/bcbio_osdbigx3/test_automated_output/bcbiotx/tmp9ahto8ej/tximport-tpm.csv");
── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──
✔ ggplot2 3.3.0     ✔ purrr   0.3.4
✔ tibble  3.0.1     ✔ dplyr   0.8.5
✔ tidyr   1.0.2     ✔ stringr 1.4.0
✔ readr   1.3.1     ✔ forcats 0.5.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
Error: Unknown TZ UTC
In addition: Warning message:
In OlsonNames() : no Olson database found
Execution halted
' returned non-zero exit status 1.
FAILED
```

So there's something we need to do in the internal R config regarding the timezone/locale. This is the culprit:

```
[2020-11-13T12:58Z] Error: Unknown TZ UTC
```

**Comment by mjsteinbaugh** [comment]
See related tidyverse issue https://github.com/tidyverse/readr/issues/952

**Comment by mjsteinbaugh** [comment]
Docker image was too stripped down and requires:

```sh
sudo apt update && sudo apt install tzdata
```

**Comment by mjsteinbaugh** [comment]
Adding that fixes the unit test on my Docker image. So there's something different about the Quay configuration.

**Comment by mjsteinbaugh** [comment]
Also, for this unit test, the output gets deleted after the test has been run. How to override that?

```sh
export BCBIO_TEST_DIR='/tmp/bcbio-fastrnaseq'
./run_tests.sh fastrnaseq
```

This works, but the `BCBIO_TEST_DIR` gets nuked after the test finishes.

**Comment by mjsteinbaugh** [comment]
Ah got it, looking at the Python code, needs the `--keep-test-dir` flag:

```sh
export BCBIO_TEST_DIR='/tmp/bcbio-fastrnaseq'
./run_tests.sh --keep-test-dir fastrnaseq
```

**Comment by mjsteinbaugh** [comment]
For reference, seeing a couple other unit test issues with 1.2.4:

```sh
./run_tests.sh chipseq
```

```
[2020-12-02T13:16Z] Compressing and sorting /tmp/bcbio-1.2.4-chipseq/test_automated_output/macs2/Test2/Test2_control_lambda.bdg.
[2020-12-02T13:16Z] Compressing and sorting /tmp/bcbio-1.2.4-chipseq/test_automated_output/macs2/Test2/Test2_treat_pileup.bdg.
[2020-12-02T13:16Z] Running greylisting on /tmp/bcbio-1.2.4-chipseq/test_automated_output/align/Test1/Test1-sort_chrom-noMito.unique-noduplicates.bam.
[2020-12-02T13:16Z] 2020-12-02 08:16:49,935:chipseq-greylist:INFO:Running greylisting on /tmp/bcbio-1.2.4-chipseq/test_automated_output/align/Test1/Test1-sort_chrom-noMito.unique-noduplicates.bam.
[2020-12-02T13:16Z] 2020-12-02 08:16:49,935:chipseq-greylist:INFO:Calculating depth over genomic regions of /tmp/bcbio-1.2.4-chipseq/test_automated_output/align/Test1/Test1-sort_chrom-noMito.unique-noduplicates.bam with sambamba.
[2020-12-02T13:16Z] sambamba 0.7.1
[2020-12-02T13:16Z]  by Artem Tarasov and Pjotr Prins (C) 2012-2019
[2020-12-02T13:16Z]     LDC 1.20.0 / DMD v2.090.1 / LLVM7.0.0 / bootstrap LDC - the LLVM D compiler (0.17.6)
[2020-12-02T13:16Z] Processing reference #2 (chr22)
[2020-12-02T13:16Z] 2020-12-02 08:16:49,975:chipseq-greylist:INFO:Estimating greylisting threshold using 100 bootstrap samples.
[2020-12-02T13:16Z] Traceback (most recent call last):
[2020-12-02T13:16Z]   File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/bin/chipseq-greylist", line 84, in <module>
[2020-12-02T13:16Z]     threshold = estimate_threshold(depth, nreps=args.bootstraps, cutoff=args.cutoff)
[2020-12-02T13:16Z]   File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/bin/chipseq-greylist", line 43, in estimate_threshold
[2020-12-02T13:16Z]     parameters = [estimate_nb_parameters(depth) for x in range(nreps)]
[2020-12-02T13:16Z]   File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/bin/chipseq-greylist", line 43, in <listcomp>
[2020-12-02T13:16Z]     parameters = [estimate_nb_parameters(depth) for x in range(nreps)]
[2020-12-02T13:16Z]   File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/bin/chipseq-greylist", line 24, in estimate_nb_parameters
[2020-12-02T13:16Z]     counts = sample_counts(depth)
[2020-12-02T13:16Z]   File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/bin/chipseq-greylist", line 21, in sample_counts
[2020-12-02T13:16Z]     return df.sample(n)["readCount"]
[2020-12-02T13:16Z]   File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 4993, in sample
[2020-12-02T13:16Z]     locs = rs.choice(axis_length, size=n, replace=replace, p=weights)
[2020-12-02T13:16Z]   File "mtrand.pyx", line 954, in numpy.random.mtrand.RandomState.choice
[2020-12-02T13:16Z] ValueError: Cannot take a larger sample than population when 'replace=False'
[2020-12-02T13:16Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/bin/chipseq-greylist --outdir /tmp/bcbio-1.2.4-chipseq/test_automated_output/bcbiotx/tmp4g65cn88/greylist /tmp/bcbio-1.2.4-chipseq/test_automated_output/align/Test1/Test1-sort_chrom-noMito.unique-noduplicates.bam
2020-12-02 08:16:49,935:chipseq-greylist:INFO:Running greylisting on /tmp/bcbio-1.2.4-chipseq/test_automated_output/align/Test1/Test1-sort_chrom-noMito.unique-noduplicates.bam.
2020-12-02 08:16:49,935:chipseq-greylist:INFO:Calculating depth over genomic regions of /tmp/bcbio-1.2.4-chipseq/test_automated_output/align/Test1/Test1-sort_chrom-noMito.unique-noduplicates.bam with sambamba.
sambamba 0.7.1
 by Artem Tarasov and Pjotr Prins (C) 2012-2019
    LDC 1.20.0 / DMD v2.090.1 / LLVM7.0.0 / bootstrap LDC - the LLVM D compiler (0.17.6)
Processing reference #2 (chr22)
2020-12-02 08:16:49,975:chipseq-greylist:INFO:Estimating greylisting threshold using 100 bootstrap samples.
Traceback (most recent call last):
  File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/bin/chipseq-greylist", line 84, in <module>
    threshold = estimate_threshold(depth, nreps=args.bootstraps, cutoff=args.cutoff)
  File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/bin/chipseq-greylist", line 43, in estimate_threshold
    parameters = [estimate_nb_parameters(depth) for x in range(nreps)]
  File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/bin/chipseq-greylist", line 43, in <listcomp>
    parameters = [estimate_nb_parameters(depth) for x in range(nreps)]
  File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/bin/chipseq-greylist", line 24, in estimate_nb_parameters
    counts = sample_counts(depth)
  File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/bin/chipseq-greylist", line 21, in sample_counts
    return df.sample(n)["readCount"]
  File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 4993, in sample
    locs = rs.choice(axis_length, size=n, replace=replace, p=weights)
  File "mtrand.pyx", line 954, in numpy.random.mtrand.RandomState.choice
ValueError: Cannot take a larger sample than population when 'replace=False'
' returned non-zero exit status 1.
[2020-12-02T13:16Z] Skipping chipseq greylisting because of small sample size: Test2
[2020-12-02T13:16Z] Calling consensus peaks on /tmp/bcbio-1.2.4-chipseq/test_automated_output/macs2/Test2/Test2_peaks.narrowPeak
[2020-12-02T13:16Z] Removing low quality peaks from /tmp/bcbio-1.2.4-chipseq/test_automated_output/macs2/Test2/Test2_peaks.narrowPeak
[2020-12-02T13:16Z] Combining summits of /tmp/bcbio-1.2.4-chipseq/test_automated_output/bcbiotx/tmpyso3169m/tmpwxq_fv5j.bed and expanding 250 bases.
Traceback (most recent call last):
  File "/usr/local/koopa/opt/bcbio/1.2.4/tools/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/usr/local/koopa/opt/bcbio/1.2.4/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 390, in chipseqpipeline
    samples = peaks.call_consensus(samples)
  File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/lib/python3.6/site-packages/bcbio/chipseq/peaks.py", line 267, in call_consensus
    os.path.splitext(consensusfile)[0] + ".saf")
  File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/lib/python3.6/site-packages/bcbio/chipseq/peaks.py", line 313, in consensus_to_saf
    df = pd.read_csv(consensusfile, sep="\t", names=CONSENSUS_HEADER)
  File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/lib/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/bcbio-1.2.4-chipseq/test_automated_output/consensus/consensus.bed'
FAILED

======================================================= FAILURES =======================================================
______________________________________________ test_chipseq_with_bowtie2 _______________________________________________

install_test_files = None, data_dir = '/tmp/bcbio-1.2.4-chipseq/data/automated'
global_config = '/tmp/bcbio-1.2.4-chipseq/test_automated_output/bcbio_system.yaml'

    @pytest.mark.chipseq
    def test_chipseq_with_bowtie2(install_test_files, data_dir, global_config):
        fc_dir = os.path.join(data_dir, os.pardir, 'test_chipseq')
        run_config = os.path.join(data_dir, 'run_info-chipseq.yaml')
>       subprocess.check_call(['bcbio_nextgen.py', global_config, fc_dir, run_config])

/home/docker/bcbio-nextgen/tests/integration/test_automated_analysis.py:123:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

popenargs = (['bcbio_nextgen.py', '/tmp/bcbio-1.2.4-chipseq/test_automated_output/bcbio_system.yaml', '/tmp/bcbio-1.2.4-chipseq/data/automated/../test_chipseq', '/tmp/bcbio-1.2.4-chipseq/data/automated/run_info-chipseq.yaml'],)
kwargs = {}, retcode = 1
cmd = ['bcbio_nextgen.py', '/tmp/bcbio-1.2.4-chipseq/test_automated_output/bcbio_system.yaml', '/tmp/bcbio-1.2.4-chipseq/data/automated/../test_chipseq', '/tmp/bcbio-1.2.4-chipseq/data/automated/run_info-chipseq.yaml']

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.

        The arguments are the same as for the call function.  Example:

        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['bcbio_nextgen.py', '/tmp/bcbio-1.2.4-chipseq/test_automated_output/bcbio_system.yaml', '/tmp/bcbio-1.2.4-chipseq/data/automated/../test_chipseq', '/tmp/bcbio-1.2.4-chipseq/data/automated/run_info-chipseq.yaml']' returned non-zero exit status 1.

/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/lib/python3.6/subprocess.py:311: CalledProcessError
=============================================== short test summary info ================================================
FAILED integration/test_automated_analysis.py::test_chipseq_with_bowtie2 - subprocess.CalledProcessError: Command '['...
========================================== 1 failed, 82 deselected in 26.62s ===========================================
```

And the srnaseq (small RNA-seq) check is hanging:

```sh
./run_tests.sh srnaseq
```

```
[2020-12-02T03:19Z] N/A% (0 of 1244) |                       | Elapsed Time: 0:00:00 ETA:  --:--:--
[2020-12-02T03:19Z] INFO 23 metaclusters from 1071 sequences
[2020-12-02T03:19Z] INFO 23 clusters found
[2020-12-02T03:19Z] INFO counts after: 18609
[2020-12-02T03:19Z] INFO # sequences after: 1244
[2020-12-02T03:19Z] INFO Solving multi-mapping events in the network of clusters
[2020-12-02T03:19Z] INFO Number of loci: 103
[2020-12-02T03:19Z] N/A% (0 of 23) |                         | Elapsed Time: 0:00:00 ETA:  --:--:--
[2020-12-02T03:19Z] INFO Seqs in clusters 1071
[2020-12-02T03:19Z] INFO Clusters too long to be analyzed: 0
[2020-12-02T03:19Z] INFO Number of clusters removed because low number of reads: 0
[2020-12-02T03:19Z] INFO Number of clusters with conflicts: 0
[2020-12-02T03:19Z] INFO counts after: 17717
[2020-12-02T03:19Z] INFO # sequences after: 1071
[2020-12-02T03:19Z] INFO Clusters up to 23
[2020-12-02T03:19Z] INFO Creating bed file
[2020-12-02T03:19Z] INFO Annotating clusters
[2020-12-02T03:19Z] INFO Creating json and count matrix
[2020-12-02T03:19Z] INFO Output file in: /tmp/bcbio-1.2.4-srnaseq/test_automated_output/seqcluster/cluster
[2020-12-02T03:19Z] INFO Finished
[2020-12-02T03:19Z] INFO It took 0.019 minutes
[2020-12-02T03:19Z] ['cluster', '-o', '/tmp/bcbio-1.2.4-srnaseq/test_automated_output/seqcluster/cluster', '-m', '/tmp/bcbio-1.2.4-srnaseq/test_automated_output/seqcluster/prepare/seqs.ma', '-a', '/tmp/bcbio-1.2.4-srnaseq/test_automated_output/align/seqs.bam', '-r', '/tmp/bcbio-1.2.4-srnaseq/data/genomes/hg19/seq/hg19.fa']
[2020-12-02T03:19Z] 100% (1244 of 1244) |####################| Elapsed Time: 0:00:00 Time:  0:00:00
[2020-12-02T03:19Z] 100% (23 of 23) |########################| Elapsed Time: 0:00:00 Time:  0:00:00
[2020-12-02T03:19Z] Run report on clusters
[2020-12-02T03:19Z] INFO Run report
[2020-12-02T03:19Z] INFO Reading sequences
[2020-12-02T03:19Z] INFO Creating profile (/tmp/bcbio-1.2.4-srnaseq/test_automated_output/seqcluster/report/profiles)
[2020-12-02T03:19Z] N/A% (0 of 23) |                         | Elapsed Time: 0:00:00 ETA:  --:--:--
^C[2020-12-02T13:16Z] Uncaught exception occurred
```

**Comment by mjsteinbaugh** [comment]
Also seeing this with the full `rnaseq` test inside Docker:

```

================================================ FAILURES =================================================
__________________________________________ test_rnaseq_with_star __________________________________________

install_test_files = None, data_dir = '/tmp/bcbio-1.2.4-rnaseq/data/automated'
global_config = '/tmp/bcbio-1.2.4-rnaseq/test_automated_output/bcbio_system.yaml'

    @pytest.mark.star
    @pytest.mark.rnaseq
    @pytest.mark.rnaseq_standard
    def test_rnaseq_with_star(install_test_files, data_dir, global_config):
        fc_dir = os.path.join(data_dir, os.pardir, 'test_fusion')
        run_config = os.path.join(data_dir, 'run_info-star.yaml')
>       subprocess.check_call(['bcbio_nextgen.py', global_config, fc_dir, run_config])

/home/docker/bcbio-nextgen/tests/integration/test_automated_analysis.py:66:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

popenargs = (['bcbio_nextgen.py', '/tmp/bcbio-1.2.4-rnaseq/test_automated_output/bcbio_system.yaml', '/tmp/bcbio-1.2.4-rnaseq/data/automated/../test_fusion', '/tmp/bcbio-1.2.4-rnaseq/data/automated/run_info-star.yaml'],)
kwargs = {}, retcode = 1
cmd = ['bcbio_nextgen.py', '/tmp/bcbio-1.2.4-rnaseq/test_automated_output/bcbio_system.yaml', '/tmp/bcbio-1.2.4-rnaseq/data/automated/../test_fusion', '/tmp/bcbio-1.2.4-rnaseq/data/automated/run_info-star.yaml']

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.

        The arguments are the same as for the call function.  Example:

        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['bcbio_nextgen.py', '/tmp/bcbio-1.2.4-rnaseq/test_automated_output/bcbio_system.yaml', '/tmp/bcbio-1.2.4-rnaseq/data/automated/../test_fusion', '/tmp/bcbio-1.2.4-rnaseq/data/automated/run_info-star.yaml']' returned non-zero exit status 1.

/usr/local/koopa/opt/bcbio/1.2.4/install/anaconda/lib/python3.6/subprocess.py:311: CalledProcessError
============================================ warnings summary =============================================
../bcbio/structural/delly.py:83
  /home/docker/bcbio-nextgen/bcbio/structural/delly.py:83: DeprecationWarning: invalid escape sequence \.
    cmd = ("bcftools view {bcf_file} | sed 's/\.,\.,\././' | bgzip -c > {tx_out_file}")

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================= short test summary info =========================================
FAILED integration/test_automated_analysis.py::test_rnaseq_with_star - subprocess.CalledProcessError: Co...
============== 1 failed, 5 passed, 1 skipped, 76 deselected, 1 warning in 148.87s (0:02:28) ===============

```

**Comment by roryk** [comment]
Hi MIke,

The full pipelines definitely won't work inside the docker image, the docker images are slimmed down and are only set up to run the CWL runs for the most part.

**Comment by mjsteinbaugh** [comment]
Gotcha @roryk !
