### ISSUE TITLE
Installation of bcbio using conda

### ISSUE THREAD

**Issue by satkins1** [bcbio/bcbio-nextgen#3383]
Hi

Apologies for the noob question but I am trying to get bcbio running on our cluster and have been unable to achieve this, even with the help of our local support.

I initially attempted to install using the bcbio_nextgen_install.py script. Whilst this ran without an issue when attempting to run an analysis this led to issues which seemed to be related to the python environment. On advice I then installed using conda in a dedicated virtual envinronment:

module load python/bioconda-3.7-2019.03
conda create --prefix=~/envs/bcbio python=3.8
source activate ~/envs/bcbio

Having done this however I was unable to identify how to appropriately ensure that the necessary tools were installed, how to install appropriate reference data or to call the bcbio. I tried using the bcbio-nextgen.py script with the upgrade command and then calling this script within the environment to run the analysis. This worked in part but failed due an inability to identify a tool 'mosdepth'.

I have been unable to find out exactly how to achieve a successful build of the package using this method or how to call it correctly.

Any advice would be most appreciated.

Thanks

**Comment by roryk** [comment]
Hi @satkins1,

Hope you are well and sorry for the problems. Just using the installer script is the way to go, bcbio sets up its own isolated conda installation and virtual environment so there is no need to install your own. If you install via the instructions [here](https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#installation) and post the error you are seeing we can help you debug further. My guess is that there is a stray python environment leaking in when you try to run bcbio which is confusing python, but we'd need to see the errors to debug further. Hope that helps!

**Comment by roryk** [comment]
Closing for now, feel free to reopen if you try the installer method and there is an error, we're happy to help debug. Thanks!

**Comment by satkins1** [comment]
Hi,

I wanted to reopen as I have tried re-installing using the instructions provided and come up against the same issues.

Specifically I have used the installer script and done so both with the Python home and path variables set and unset. I have also tried performing the upgrade to install the aligner and genome data using by specifying the path to the installer script outside and inside the conda environment that the installer script creates and finally running the analysis from outside and inside the conda environment. It is possible to get the package running and it will perform the initial alignment using bwa however it stalls at the coverage calculation step requiring mosdepth. The mosdepth tool is however within the tool directory and the install-params.yaml file appears to point to the correct tools directory. The full error message is pasted below.

Thanks

Steve

[2020-12-04T12:42Z] multiprocessing: process_alignment
[2020-12-04T12:42Z] Aligning lane A11_PBMC with bwa aligner
[2020-12-04T12:42Z] Aligning lane A11_PBMC with bwa aligner
[2020-12-04T12:42Z] Aligning lane A11_PBMC with bwa aligner
[2020-12-04T12:42Z] Aligning lane A11_Liver with bwa aligner
[2020-12-04T12:42Z] Aligning lane A11_Liver with bwa aligner
[2020-12-04T12:42Z] Aligning lane A11_Liver with bwa aligner
[2020-12-04T12:42Z] multiprocessing: delayed_bam_merge
[2020-12-04T12:42Z] Timing: callable regions
[2020-12-04T12:42Z] multiprocessing: prep_samples
[2020-12-04T12:42Z] multiprocessing: postprocess_alignment
[2020-12-04T12:42Z] Calculating coverage: A11_PBMC variant_regions
[2020-12-04T12:42Z] /usr/bin/bash: mosdepth: command not found
[2020-12-04T12:42Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/bgfs/rbataller/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/bgfs/rbataller/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; export MOSDEPTH_Q0=NO_COVERAGE && export MOSDEPTH_Q1=LOW_COVERAGE && export MOSDEPTH_Q2=CALLABLE && mosdepth -t 12 -F 1804 -Q 1 --no-per-base --by /bgfs/rbataller/coverage/A11_PBMC/target-genome.bed --quantize 0:1:4: /bgfs/rbataller/bcbiotx/tmp_9p7_mvy/A11_PBMC-variant_regions /bgfs/rbataller/align/A11_PBMC/A11_PBMC-sort.bam 
/usr/bin/bash: mosdepth: command not found
' returned non-zero exit status 127.
Traceback (most recent call last):
  File "/bgfs/rbataller/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/bgfs/rbataller/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/bgfs/rbataller/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/bgfs/rbataller/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/bgfs/rbataller/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 138, in variant2pipeline
    samples = run_parallel("postprocess_alignment", samples)
  File "/bgfs/rbataller/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/bgfs/rbataller/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/bgfs/rbataller/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1048, in __call__
    if self.dispatch_one_batch(iterator):
  File "/bgfs/rbataller/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 866, in dispatch_one_batch
    self._dispatch(tasks)
  File "/bgfs/rbataller/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 784, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/bgfs/rbataller/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/bgfs/rbataller/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/bgfs/rbataller/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/bgfs/rbataller/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/bgfs/rbataller/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/bgfs/rbataller/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 157, in postprocess_alignment
    return sample.postprocess_alignment(*args)
  File "/bgfs/rbataller/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sample.py", line 260, in postprocess_alignment
    covinfo = callable.sample_callable_bed(bam_file_ready, ref_file, data)
  File "/bgfs/rbataller/bcbio/anaconda/lib/python3.6/site-packages/bcbio/bam/callable.py", line 45, in sample_callable_bed
    callable_bed, depth_files = coverage.calculate(bam_file, data, sv_bed)
  File "/bgfs/rbataller/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/coverage.py", line 100, in calculate
    per_base=per_base)
  File "/bgfs/rbataller/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/coverage.py", line 244, in run_mosdepth
    do.run(cmd.format(**locals()), message.format(**locals()))
  File "/bgfs/rbataller/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/bgfs/rbataller/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; export MOSDEPTH_Q0=NO_COVERAGE && export MOSDEPTH_Q1=LOW_COVERAGE && export MOSDEPTH_Q2=CALLABLE && mosdepth -t 12 -F 1804 -Q 1 --no-per-base --by /bgfs/rbataller/coverage/A11_PBMC/target-genome.bed --quantize 0:1:4: /bgfs/rbataller/bcbiotx/tmp_9p7_mvy/A11_PBMC-variant_regions /bgfs/rbataller/align/A11_PBMC/A11_PBMC-sort.bam 
/usr/bin/bash: mosdepth: command not found
' returned non-zero exit status 127.

**Comment by satkins1** [comment]
Thanks rory - I understand that this issue has been fixed by the commit above - forgive the question but what is the best way of altering my installation of bcbio to ensure that it is updated to include this fix?

Steve

**Comment by roryk** [comment]
Hi @satkins1,

No worries-- if you update bcbio with:

`bcbio_nextgen.py upgrade -u development --tools --data`

it will pull in the current development code, update all of the tools and update the data, if any data has been updated. https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#upgrade has more information about the other options you can use, that same command is used to install new genomes and what not as well. Hope that helps and gets you going.
