### ISSUE TITLE
bcbio.pipeline.config_utils.CmdNotFound: '_get_program_cmd' 'ataqv' {} None

### ISSUE THREAD

**Issue by PatrickJReed** [bcbio/bcbio-nextgen#3385]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.4
- OS name and version (`lsb_release -ds`): Ubuntu 18.04.5 LTS

**To Reproduce**
Exact bcbio command you have used:
```
 sudo nohup ~/bcbio/anaconda/bin/bcbio_nextgen.py ../config/20-20ec.yaml -n 48 &
```
Your sample configuration file:
```
details:
- analysis: chip-seq
  genome_build: mm10
  algorithm:
    aligner: bwa
    peakcaller: [macs2]
    chip_method: atac
    keep_duplicates: False
    keep_multimapped: False
    strandedness: firststrand
upload:
  dir: ../final
```

**Observed behavior**
Error message or bcbio output:
```
[2020-12-01T19:15Z] System YAML configuration: /home/ubuntu/bcbio/galaxy/bcbio_system.yaml.
[2020-12-01T19:15Z] Locale set to C.UTF-8.
[2020-12-01T19:15Z] Resource requests: bwa, picard; memory: 3.00, 3.00; cores: 16, 16
[2020-12-01T19:15Z] Configuring 3 jobs to run, using 16 cores each with 48.1g of memory reserved for each job
[2020-12-01T19:15Z] Timing: organize samples
[2020-12-01T19:15Z] multiprocessing: organize_samples
Running bcbio version: 1.2.4
global config: /data/20-20ec/20-20ec/work/bcbio_system.yaml
run info config: /data/20-20ec/20-20ec/config/20-20ec.yaml
[2020-12-01T19:15Z] Using input YAML configuration: /data/20-20ec/20-20ec/config/20-20ec.yaml
[2020-12-01T19:15Z] 85152 is not a valid R name, converting to X85152.
[2020-12-01T19:15Z] 85153 is not a valid R name, converting to X85153.
[2020-12-01T19:15Z] 85154 is not a valid R name, converting to X85154.
[2020-12-01T19:15Z] 85155 is not a valid R name, converting to X85155.
[2020-12-01T19:15Z] Checking sample YAML configuration: /data/20-20ec/20-20ec/config/20-20ec.yaml
[2020-12-01T19:15Z] Retreiving program versions from /home/ubuntu/bcbio/manifest/python-packages.yaml.
[2020-12-01T19:15Z] Retreiving program versions from /home/ubuntu/bcbio/manifest/r-packages.yaml.
[2020-12-01T19:15Z] Testing minimum versions of installed programs
[2020-12-01T19:15Z] Timing: alignment
[2020-12-01T19:15Z] multiprocessing: prepare_sample
[2020-12-01T19:15Z] Preparing X85152
[2020-12-01T19:15Z] Preparing X85153
[2020-12-01T19:15Z] Preparing X85154
[2020-12-01T19:15Z] Preparing X85155
[2020-12-01T19:15Z] multiprocessing: trim_sample
[2020-12-01T19:15Z] Skipping trimming of X85152.
[2020-12-01T19:15Z] Skipping trimming of X85154.
[2020-12-01T19:15Z] Skipping trimming of X85153.
[2020-12-01T19:15Z] Skipping trimming of X85155.
[2020-12-01T19:15Z] multiprocessing: disambiguate_split
[2020-12-01T19:15Z] multiprocessing: process_alignment
[2020-12-01T19:15Z] Aligning lane X85152 with bwa aligner
[2020-12-01T19:15Z] Aligning lane X85153 with bwa aligner
[2020-12-01T19:15Z] Aligning lane X85154 with bwa aligner
[2020-12-01T19:15Z] Aligning lane X85155 with bwa aligner
[2020-12-01T19:15Z] Timing: disambiguation
[2020-12-01T19:15Z] multiprocessing: clean_chipseq_alignment
[2020-12-01T19:16Z] Resource requests: macs2; memory: 8.00; cores: 1
[2020-12-01T19:16Z] Configuring 5 jobs to run, using 1 cores each with 8.00g of memory reserved for each job
[2020-12-01T19:16Z] Timing: peakcalling
[2020-12-01T19:16Z] multiprocessing: peakcalling
[2020-12-01T19:16Z] Counting alignments in None.
[2020-12-01T19:16Z] Counting alignments in None.
[2020-12-01T19:16Z] Counting alignments in None.
[2020-12-01T19:16Z] Counting alignments in None.
[2020-12-01T19:16Z] None has less than 1000, peak calling will fail so skip this fraction.
[2020-12-01T19:16Z] Counting alignments in None.
[2020-12-01T19:16Z] None has less than 1000, peak calling will fail so skip this fraction.
[2020-12-01T19:16Z] Counting alignments in None.
[2020-12-01T19:16Z] None has less than 1000, peak calling will fail so skip this fraction.
[2020-12-01T19:16Z] Counting alignments in None.
[2020-12-01T19:16Z] None has less than 1000, peak calling will fail so skip this fraction.
[2020-12-01T19:16Z] Counting alignments in None.
[2020-12-01T19:16Z] None has less than 1000, peak calling will fail so skip this fraction.
[2020-12-01T19:16Z] Counting alignments in None.
[2020-12-01T19:16Z] None has less than 1000, peak calling will fail so skip this fraction.
[2020-12-01T19:16Z] None has less than 1000, peak calling will fail so skip this fraction.
[2020-12-01T19:16Z] Counting alignments in None.
[2020-12-01T19:16Z] Counting alignments in None.
[2020-12-01T19:16Z] None has less than 1000, peak calling will fail so skip this fraction.
[2020-12-01T19:16Z] Counting alignments in None.
[2020-12-01T19:16Z] None has less than 1000, peak calling will fail so skip this fraction.
[2020-12-01T19:16Z] Counting alignments in None.
[2020-12-01T19:16Z] None has less than 1000, peak calling will fail so skip this fraction.
[2020-12-01T19:16Z] Counting alignments in None.
[2020-12-01T19:16Z] None has less than 1000, peak calling will fail so skip this fraction.
[2020-12-01T19:16Z] Counting alignments in None.
[2020-12-01T19:16Z] None has less than 1000, peak calling will fail so skip this fraction.
[2020-12-01T19:16Z] Counting alignments in None.
[2020-12-01T19:16Z] None has less than 1000, peak calling will fail so skip this fraction.
[2020-12-01T19:16Z] Counting alignments in /data/20-20ec/20-20ec/work/align/X85153/X85153-sort-shifted_chrom-noMito.unique-noduplicates.bam.
[2020-12-01T19:16Z] None has less than 1000, peak calling will fail so skip this fraction.
[2020-12-01T19:16Z] None has less than 1000, peak calling will fail so skip this fraction.
[2020-12-01T19:16Z] Counting alignments in /data/20-20ec/20-20ec/work/align/X85152/X85152-sort-shifted_chrom-noMito.unique-noduplicates.bam.
[2020-12-01T19:16Z] None has less than 1000, peak calling will fail so skip this fraction.
[2020-12-01T19:16Z] Counting alignments in /data/20-20ec/20-20ec/work/align/X85155/X85155-sort-shifted_chrom-noMito.unique-noduplicates.bam.
[2020-12-01T19:16Z] Counting alignments in /data/20-20ec/20-20ec/work/align/X85154/X85154-sort-shifted_chrom-noMito.unique-noduplicates.bam.
[2020-12-01T19:16Z] Running peak calling with macs2 on the full fraction of /data/20-20ec/20-20ec/work/align/X85155/X85155-sort-shifted_chrom-noMito.unique-noduplicates.bam.
[2020-12-01T19:16Z] Running peak calling with macs2 on the full fraction of /data/20-20ec/20-20ec/work/align/X85152/X85152-sort-shifted_chrom-noMito.unique-noduplicates.bam.
[2020-12-01T19:16Z] Running peak calling with macs2 on the full fraction of /data/20-20ec/20-20ec/work/align/X85153/X85153-sort-shifted_chrom-noMito.unique-noduplicates.bam.
[2020-12-01T19:16Z] Running peak calling with macs2 on the full fraction of /data/20-20ec/20-20ec/work/align/X85154/X85154-sort-shifted_chrom-noMito.unique-noduplicates.bam.
[2020-12-01T19:16Z] Using peaks from full fraction since /data/20-20ec/20-20ec/work/align/X85152/X85152-sort-shifted_chrom-noMito.unique-noduplicates.bam is single-ended.
[2020-12-01T19:16Z] Using peaks from full fraction since /data/20-20ec/20-20ec/work/align/X85153/X85153-sort-shifted_chrom-noMito.unique-noduplicates.bam is single-ended.
[2020-12-01T19:16Z] Using peaks from full fraction since /data/20-20ec/20-20ec/work/align/X85154/X85154-sort-shifted_chrom-noMito.unique-noduplicates.bam is single-ended.
[2020-12-01T19:16Z] Using peaks from full fraction since /data/20-20ec/20-20ec/work/align/X85155/X85155-sort-shifted_chrom-noMito.unique-noduplicates.bam is single-ended.
[2020-12-01T19:16Z] multiprocessing: run_chipseq_count
[2020-12-01T19:16Z] Creating peak table from full BAM file because /data/20-20ec/20-20ec/work/align/X85152/X85152-sort-shifted_chrom-noMito.unique-noduplicates.bam is single-ended.
[2020-12-01T19:16Z] Creating peak table from full BAM file because /data/20-20ec/20-20ec/work/align/X85153/X85153-sort-shifted_chrom-noMito.unique-noduplicates.bam is single-ended.
[2020-12-01T19:16Z] Creating peak table from full BAM file because /data/20-20ec/20-20ec/work/align/X85154/X85154-sort-shifted_chrom-noMito.unique-noduplicates.bam is single-ended.
[2020-12-01T19:16Z] Creating peak table from full BAM file because /data/20-20ec/20-20ec/work/align/X85155/X85155-sort-shifted_chrom-noMito.unique-noduplicates.bam is single-ended.
[2020-12-01T19:16Z] Resource requests: fastqc, picard; memory: 3.00, 3.00; cores: 16, 16
[2020-12-01T19:16Z] Configuring 3 jobs to run, using 16 cores each with 48.1g of memory reserved for each job
[2020-12-01T19:16Z] Timing: quality control
[2020-12-01T19:16Z] multiprocessing: pipeline_summary
[2020-12-01T19:16Z] QC: X85152 ataqv
[2020-12-01T19:16Z] QC: X85152 chipqc
[2020-12-01T19:16Z] QC: X85152 fastqc
[2020-12-01T19:16Z] QC: X85152 samtools
[2020-12-01T19:16Z] QC: X85153 ataqv
[2020-12-01T19:16Z] samtools stats : X85152
[2020-12-01T19:16Z] FastQC: X85152
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 59, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 243, in pipeline_summary
    return qcsummary.pipeline_summary(*args)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/qcsummary.py", line 79, in pipeline_summary
    data["summary"] = _run_qc_tools(work_bam, work_data)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/qcsummary.py", line 175, in _run_qc_tools
    out = qc_fn(bam_file, data, cur_qc_dir)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/qc/atac.py", line 6, in run
    return atac.run_ataqv(data)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/chipseq/atac.py", line 159, in run_ataqv
    ataqv = config_utils.get_program("ataqv", data)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/config_utils.py", line 191, in get_program
    return _get_program_cmd(name, pconfig, config, default)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/config_utils.py", line 217, in wrap
    raise CmdNotFound(" ".join(map(repr, (fn.__name__ if six.PY3 else fn.func_name, name, pconfig, default))))
bcbio.pipeline.config_utils.CmdNotFound: '_get_program_cmd' 'ataqv' {} None
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/home/ubuntu/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 401, in chipseqpipeline
    samples = qcsummary.generate_parallel(samples, run_parallel)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/qcsummary.py", line 43, in generate_parallel
    qced = run_parallel("pipeline_summary", to_analyze)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1042, in __call__
    self.retrieve()
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 921, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
bcbio.pipeline.config_utils.CmdNotFound: '_get_program_cmd' 'ataqv' {} None
```

**Expected behavior**
finish cleanly without crashing

**Log files**
[bcbio-nextgen-2.log](https://github.com/bcbio/bcbio-nextgen/files/5624990/bcbio-nextgen-2.log)
[bcbio-nextgen-debug.log](https://github.com/bcbio/bcbio-nextgen/files/5624992/bcbio-nextgen-debug.log)
[bcbio-nextgen-commands-2.log](https://github.com/bcbio/bcbio-nextgen/files/5624993/bcbio-nextgen-commands-2.log)

**Additional context**

**Comment by roryk** [comment]
Hi Patrick! Hope you are holding up okay. Sorry for the problem-- I'm not sure why it isn't finding ataqv here. Does it exist in `~/bcbio/anaconda/bin/`? It should have a link there pointing to `../share/bcbio/anaconda/envs/r36/bin/ataqv`. If it is in `~/bcbio/anaconda/bin/`, then adding that directory to your PATH should fix the issue.

You shouldn't have to run bcbio with `sudo` if you want to not have that in and save yourself some possible headaches.

**Comment by PatrickJReed** [comment]
Hi Rory, thanks for the quick reply!  ataqv is not present in ~/bcbio/anaconda/bin/ but it is in /home/ubuntu/bcbio/tools/bin  I created the link pointing to bcbio/anaconda/envs/r36/bin/ataqv and it fixed the problem, however I'm now getting a new error:   

[2020-12-03T23:40Z] Copying web visualizer template directory /home/ubuntu/bcbio/tools/web to /data/20-20ec/20-20ec/work/bcbiotx/tmp_siossda/ataqv
[2020-12-03T23:40Z] Traceback (most recent call last):
[2020-12-03T23:40Z]   File "/home/ubuntu/bcbio/galaxy/../anaconda/bin/mkarv", line 600, in <module>
[2020-12-03T23:40Z]     shutil.copytree(args.template_directory, args.directory)
[2020-12-03T23:40Z]   File "/home/ubuntu/bcbio/anaconda/lib/python3.6/shutil.py", line 315, in copytree
[2020-12-03T23:40Z]     names = os.listdir(src)
[2020-12-03T23:40Z] FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/bcbio/tools/web'
[2020-12-03T23:40Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /home/ubuntu/bcbio/galaxy/../anaconda/bin/mkarv /data/20-20ec/20-20ec/work/bcbiotx/tmp_siossda/ataqv /data/20-20ec/20-20ec/work/qc/X85152/ataqv/X85152.ataqv.json.gz /data/20-20ec/20-20ec/work/qc/X85153/ataqv/X85153.ataqv.json.gz /data/20-20ec/20-20ec/work/qc/X85154/ataqv/X85154.ataqv.json.gz /data/20-20ec/20-20ec/work/qc/X85155/ataqv/X85155.ataqv.json.gz
Copying web visualizer template directory /home/ubuntu/bcbio/tools/web to /data/20-20ec/20-20ec/work/bcbiotx/tmp_siossda/ataqv
Traceback (most recent call last):
  File "/home/ubuntu/bcbio/galaxy/../anaconda/bin/mkarv", line 600, in <module>
    shutil.copytree(args.template_directory, args.directory)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/shutil.py", line 315, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/bcbio/tools/web'
' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/ubuntu/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/home/ubuntu/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 402, in chipseqpipeline
    samples = atac.create_ataqv_report(samples)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/chipseq/atac.py", line 248, in create_ataqv_report
    do.run(cmd, message)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /home/ubuntu/bcbio/galaxy/../anaconda/bin/mkarv /data/20-20ec/20-20ec/work/bcbiotx/tmp_siossda/ataqv /data/20-20ec/20-20ec/work/qc/X85152/ataqv/X85152.ataqv.json.gz /data/20-20ec/20-20ec/work/qc/X85153/ataqv/X85153.ataqv.json.gz /data/20-20ec/20-20ec/work/qc/X85154/ataqv/X85154.ataqv.json.gz /data/20-20ec/20-20ec/work/qc/X85155/ataqv/X85155.ataqv.json.gz
Copying web visualizer template directory /home/ubuntu/bcbio/tools/web to /data/20-20ec/20-20ec/work/bcbiotx/tmp_siossda/ataqv
Traceback (most recent call last):
  File "/home/ubuntu/bcbio/galaxy/../anaconda/bin/mkarv", line 600, in <module>
    shutil.copytree(args.template_directory, args.directory)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/shutil.py", line 315, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/bcbio/tools/web'
' returned non-zero exit status 1.

I checked and the directory /home/ubuntu/bcbio/tools/web is not present.

**Comment by roryk** [comment]
Heya, sorry for letting this slip through the cracks, are you still running into this issue?

**Comment by naumenko-sa** [comment]
please feel free to re-open if there is still an issue. We have successfully run several ATAC projects as of bcbio 1.2.7.
