### ISSUE TITLE
excel file reading  - once deprecated now errror in Python 3.9

### ISSUE THREAD

**Issue by smoe** [bcbio/bcbio-nextgen#3390]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`):
1.2.4
- OS name and version (`lsb_release -ds`):
Debian unstable

**To Reproduce**
Exact bcbio command you have used:
```
$ tests/run_tests.sh explant
```
**Observed behavior**
Error message or bcbio output:
```
=============================================================== test session starts ===============================================================
platform linux -- Python 3.9.1rc1, pytest-4.6.11, py-1.9.0, pluggy-0.13.0 -- /usr/bin/python3
rootdir: /home/steffen/med/bcbio
plugins: mock-1.10.4, xonsh-0.9.24
collected 83 items / 82 deselected / 1 selected

tests/integration/test_automated_analysis.py::test_explant_with_tophat Running bcbio version: 1.2.4
global config: /tmp/bcbio_w9qvib0o/test_automated_output/bcbio_system.yaml
flowcell directory: /tmp/bcbio_w9qvib0o/data/1_explant
run info config: /tmp/bcbio_w9qvib0o/data/automated/run_info-explant.yaml
[2020-12-07T13:31Z] System YAML configuration: /tmp/bcbio_w9qvib0o/test_automated_output/bcbio_system.yaml.
[2020-12-07T13:31Z] Locale set to C.UTF-8.
[2020-12-07T13:31Z] Resource requests: atropos, picard; memory: 2.00; cores: 4, 1
[2020-12-07T13:31Z] Configuring 1 jobs to run, using 1 cores each with 2.00g of memory reserved for each job
[2020-12-07T13:31Z] Timing: organize samples
[2020-12-07T13:31Z] multiprocessing: organize_samples
[2020-12-07T13:31Z] Using input YAML configuration: /tmp/bcbio_w9qvib0o/data/automated/run_info-explant.yaml
[2020-12-07T13:31Z] Checking sample YAML configuration: /tmp/bcbio_w9qvib0o/data/automated/run_info-explant.yaml
Traceback (most recent call last):
  File "/home/steffen/med/bcbio/scripts/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/home/steffen/med/bcbio/scripts/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/steffen/med/bcbio/bcbio/pipeline/main.py", line 49, in run_main
    _run_toplevel(config, config_file, workdir, parallel,
  File "/home/steffen/med/bcbio/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/steffen/med/bcbio/bcbio/pipeline/main.py", line 239, in rnaseqpipeline
    samples = rnaseq_prep_samples(config, run_info_yaml, parallel, dirs, samples)
  File "/home/steffen/med/bcbio/bcbio/pipeline/main.py", line 461, in rnaseq_prep_samples
    samples = run_parallel("organize_samples", [[dirs, config, run_info_yaml,
  File "/home/steffen/med/bcbio/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/steffen/med/bcbio/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/usr/lib/python3/dist-packages/joblib/parallel.py", line 1048, in __call__
    if self.dispatch_one_batch(iterator):
  File "/usr/lib/python3/dist-packages/joblib/parallel.py", line 866, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/lib/python3/dist-packages/joblib/parallel.py", line 784, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/usr/lib/python3/dist-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/usr/lib/python3/dist-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/usr/lib/python3/dist-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/steffen/med/bcbio/bcbio/utils.py", line 56, in wrapper
    return f(*args, **kwargs)
  File "/home/steffen/med/bcbio/bcbio/distributed/multitasks.py", line 459, in organize_samples
    return run_info.organize(*args)
  File "/home/steffen/med/bcbio/bcbio/pipeline/run_info.py", line 81, in organize
    item = add_reference_resources(item, remote_retriever)
  File "/home/steffen/med/bcbio/bcbio/pipeline/run_info.py", line 176, in add_reference_resources
    data["reference"] = genome.get_refs(data["genome_build"], alignment.get_aligner_with_aliases(aligner, data),
  File "/home/steffen/med/bcbio/bcbio/pipeline/genome.py", line 229, in get_refs
    galaxy_dt = _get_galaxy_data_table(name, galaxy_config["tool_data_table_config_path"])
  File "/home/steffen/med/bcbio/bcbio/pipeline/genome.py", line 215, in _get_galaxy_data_table
    for t in tdtc.getiterator("table"):
AttributeError: 'ElementTree' object has no attribute 'getiterator'
FAILED
```

**Additional context**
This is a known issue
```
$ python3 --version
Python 3.9.1rc1
```
and stackoverflow has something about it https://stackoverflow.com/questions/64264563/attributeerror-elementtree-object-has-no-attribute-getiterator-when-trying

**Comment by roryk** [comment]
Thanks for the heads up and the link to the SO thread about it.

**Comment by smoe** [comment]
Many thanks for addressing this so quickly. I just updated to HEAD and ran again, which gave me
```
steffen@wurzel:~/med/bcbio$ tests/run_tests.sh explant
============================================================= test session starts ==============================================================
platform linux -- Python 3.9.1, pytest-4.6.11, py-1.9.0, pluggy-0.13.0 -- /usr/bin/python3
rootdir: /home/steffen/med/bcbio
plugins: mock-1.10.4, xonsh-0.9.24
collected 74 items / 4 errors / 73 deselected

==================================================================== ERRORS ====================================================================
_________________________________________ ERROR collecting tests/integration/rnaseq/test_ericscript.py _________________________________________
ImportError while importing test module '/home/steffen/med/bcbio/tests/integration/rnaseq/test_ericscript.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/integration/rnaseq/test_ericscript.py:8: in <module>
    from bcbio.rnaseq import ericscript
bcbio/rnaseq/ericscript.py:21: in <module>
    from bcbio.pipeline.fastq import convert_bam_to_fastq
bcbio/pipeline/fastq.py:9: in <module>
    from bcbio.pipeline import alignment
bcbio/pipeline/alignment.py:13: in <module>
    from bcbio.ngsalign import (bbmap, bowtie, bwa, tophat, bowtie2, minimap2,
bcbio/ngsalign/bwa.py:18: in <module>
    from bcbio.heterogeneity import chromhacks
bcbio/heterogeneity/__init__.py:13: in <module>
    from bcbio.heterogeneity import bubbletree, phylowgs, theta
bcbio/heterogeneity/bubbletree.py:23: in <module>
    from bcbio.structural import shared
bcbio/structural/__init__.py:13: in <module>
    from bcbio.structural import (battenberg, cn_mops, cnvkit, delly, gatkcnv, gridss,
bcbio/structural/battenberg.py:14: in <module>
    from bcbio.variation import population, vcfutils
bcbio/variation/population.py:12: in <module>
    from bcbio import install, utils
bcbio/install.py:28: in <module>
    from bcbio.pipeline import genome, version
E   ImportError: cannot import name 'version' from 'bcbio.pipeline' (/home/steffen/med/bcbio/bcbio/pipeline/__init__.py)
_____________________________________________ ERROR collecting tests/unit/pipeline/test_rnaseq.py ______________________________________________
ImportError while importing test module '/home/steffen/med/bcbio/tests/unit/pipeline/test_rnaseq.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/unit/pipeline/test_rnaseq.py:3: in <module>
    from bcbio.pipeline import rnaseq
bcbio/pipeline/rnaseq.py:3: in <module>
    from bcbio.rnaseq import (featureCounts, cufflinks, oncofuse, count, dexseq,
bcbio/rnaseq/variation.py:5: in <module>
    from bcbio.heterogeneity import chromhacks
bcbio/heterogeneity/__init__.py:13: in <module>
    from bcbio.heterogeneity import bubbletree, phylowgs, theta
bcbio/heterogeneity/bubbletree.py:23: in <module>
    from bcbio.structural import shared
bcbio/structural/__init__.py:13: in <module>
    from bcbio.structural import (battenberg, cn_mops, cnvkit, delly, gatkcnv, gridss,
bcbio/structural/battenberg.py:14: in <module>
    from bcbio.variation import population, vcfutils
bcbio/variation/population.py:12: in <module>
    from bcbio import install, utils
bcbio/install.py:28: in <module>
    from bcbio.pipeline import genome, version
E   ImportError: cannot import name 'version' from 'bcbio.pipeline' (/home/steffen/med/bcbio/bcbio/pipeline/__init__.py)
____________________________________________ ERROR collecting tests/unit/rnaseq/test_ericscript.py _____________________________________________
ImportError while importing test module '/home/steffen/med/bcbio/tests/unit/rnaseq/test_ericscript.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/unit/rnaseq/test_ericscript.py:3: in <module>
    from bcbio.rnaseq import ericscript
bcbio/rnaseq/ericscript.py:21: in <module>
    from bcbio.pipeline.fastq import convert_bam_to_fastq
bcbio/pipeline/fastq.py:9: in <module>
    from bcbio.pipeline import alignment
bcbio/pipeline/alignment.py:13: in <module>
    from bcbio.ngsalign import (bbmap, bowtie, bwa, tophat, bowtie2, minimap2,
bcbio/ngsalign/bwa.py:18: in <module>
    from bcbio.heterogeneity import chromhacks
bcbio/heterogeneity/__init__.py:13: in <module>
    from bcbio.heterogeneity import bubbletree, phylowgs, theta
bcbio/heterogeneity/bubbletree.py:23: in <module>
    from bcbio.structural import shared
bcbio/structural/__init__.py:13: in <module>
    from bcbio.structural import (battenberg, cn_mops, cnvkit, delly, gatkcnv, gridss,
bcbio/structural/battenberg.py:14: in <module>
    from bcbio.variation import population, vcfutils
bcbio/variation/population.py:12: in <module>
    from bcbio import install, utils
bcbio/install.py:28: in <module>
    from bcbio.pipeline import genome, version
E   ImportError: cannot import name 'version' from 'bcbio.pipeline' (/home/steffen/med/bcbio/bcbio/pipeline/__init__.py)
______________________________________________ ERROR collecting tests/unit/upload/test_upload.py _______________________________________________
ImportError while importing test module '/home/steffen/med/bcbio/tests/unit/upload/test_upload.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/unit/upload/test_upload.py:5: in <module>
    from bcbio import upload
bcbio/upload/__init__.py:10: in <module>
    from bcbio.upload import shared, filesystem, galaxy, s3, irods
bcbio/upload/galaxy.py:16: in <module>
    from bcbio.pipeline import qcsummary
bcbio/pipeline/qcsummary.py:19: in <module>
    from bcbio.pipeline import config_utils, run_info
bcbio/pipeline/run_info.py:19: in <module>
    from bcbio import install, utils, structural
bcbio/install.py:28: in <module>
    from bcbio.pipeline import genome, version
E   ImportError: cannot import name 'version' from 'bcbio.pipeline' (/home/steffen/med/bcbio/bcbio/pipeline/__init__.py)
=============================================================== warnings summary ===============================================================
```
This now happens whatever test I attempt to run.

**Comment by roryk** [comment]
Hi @smoe,

Sorry for letting this slip through the cracks, just cleaning up my emails and saw I missed this one. That happens sometimes when updating manually with `python setup.py install`. I have no idea how to fix it, other than go into the `site-packages` directory and nuke everything bcbio related.

**Comment by smoe** [comment]
;) Thank you for your reply. I'll investigate.
Best,
Steffen
