### ISSUE TITLE
fastrna-seq can not combine counts

### ISSUE THREAD

**Issue by LMannarino** [bcbio/bcbio-nextgen#3391]
Hi
I'm running a fastrna-seq with 6 samples.

**bcbio version: 1.2.4**

**my configuration:**
```
---
details:
  - analysis: fastrna-seq
    genome_build: hg19
    algorithm: {}
upload:
  dir: ../final
```
bcbio raises this error:

```
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/opt/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 58, in run_main
    fc_dir, run_info_yaml)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 300, in fastrnaseqpipeline
    samples = rnaseq.combine_files(samples)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/rnaseq.py", line 444, in combine_files
    combined = count.combine_count_files(count_files, ext=".counts")
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/rnaseq/count.py", line 22, in combine_count_files
    out_dir = os.path.join(os.path.dirname(files[0]))
IndexError: list index out of range
```

@roryk I think this is related to this: https://github.com/bcbio/bcbio-nextgen/commit/c9a6922956974dd23eeace8022fe991eded96762 

Actually, I don't have any *.counts file in the work folder, so I guess it cannot find it, but maybe I'm wrong.

Thank you for your help!
Laura

**Comment by roryk** [comment]
Thanks, are you running the development version? This will be fixed there, it is fixed post 1.2.4. If you upgrade to the development version with:

```bash
bcbio_nextgen.py upgrade -u development
```

you should pull in the fix which will fix this.
