### ISSUE TITLE
Problem running prep script for config file for multiple samples

### ISSUE THREAD

**Issue by DolapoA** [bcbio/bcbio-nextgen#3400]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.4
- OS name and version (`lsb_release -ds`): CentOS Linux release 7.8.2003 (Core)

**To Reproduce**
Exact bcbio command you have used:
```
bcbio_nextgen.py -w /path/to/config/mpnst_exome_template.yaml  mpnst_analysis ../input/29582_S6_L001_R1_001.fastq.gz ../input/29582_S6_L001_R2_001.fastq.gz ../input/85517_S1_L001_R1_001.fastq.gz ../input/85517_S1_L001_R2_001.fastq.gz
```
Your sample configuration file:
```
fc_date: '171220'
fc_name: mpnst_analysis
upload:
  dir: final
details:
- algorithm:
    aligner: bwa
    trim_ends: [2,0,2,0]
    min_allele_fraction: 0.01
    #correct_umis: /path/config/whitelist.txt
    tools_off:
    - gemini
    #umi_type: fastq_name
    variantcaller: [mutect2, vardict]
    variant_regions: ../input/KAPA_HyperExome_primary_targets.bed
    use_lowfreq_filter: false
  analysis: variant2
  description: MPNST
  files:
  - ../input/
  - ../input/
  genome_build: hg38
  metadata:
    phenotype: tumor
resources:
  fgbio:
    options: [--min-reads, 3]
```

**Observed behavior**
Error message or bcbio output:
```
Incorrect input arguments ['../input/29582_S6_L001_R1_001.fastq.gz', '../input/29582_S6_L001_R2_001.fastq.gz', '../input/85517_S1_L001_R1_001.fastq.gz', '../input/85517_S1_L001_R2_001.fastq.gz']
usage: bcbio_nextgen.py [-h] [-n NUMCORES] [-t {local,ipython}]
                        [-s {lsf,sge,torque,slurm,pbspro}]
                        [--local_controller] [-q QUEUE] [-r RESOURCES]
                        [--timeout TIMEOUT] [--retries RETRIES] [-p TAG]
                        [-w WORKFLOW] [--workdir WORKDIR] [-v]
                        [--force-single] [--separators SEPARATORS]
                        [global_config] [fc_dir] [run_config [run_config ...]]

```

**Expected behavior**
A config file for multiple paired end samples.

**Comment by roryk** [comment]
Hi @DolapoA,

Looks like the call:

```
bcbio_nextgen.py -w /path/to/config/mpnst_exome_template.yaml  mpnst_analysis ../input/29582_S6_L001_R1_001.fastq.gz ../input/29582_S6_L001_R2_001.fastq.gz ../input/85517_S1_L001_R1_001.fastq.gz ../input/85517_S1_L001_R2_001.fastq.gz
```

is messed up.

```
bcbio_nextgen.py -w template /path/to/config/mpnst_exome_template.yaml   mpnst_analysis.csv ../input
```

should do it, and your CSV file should have the first column as the R1 file for each of those, so minimally:

```csv
description,samplename
29582_S6_L001_R1_001.fastq.gz,S6
85517_S1_L001_R2_001.fastq.gz,S1
```

`min_allele_fraction` is a percentage, so you'll want to set that to 1 if you wanted to call down to 1% AF. To call lower you will need duplex UMIs in our experience.

**Comment by DolapoA** [comment]
Thanks, I'll try this.

**Comment by roryk** [comment]
Ok! Let me know if that doesn't get you moving.

**Comment by DolapoA** [comment]
**Config:**
```
fc_date: '171220'
fc_name: mpnst_analysis
upload:
  dir: final
details:
- algorithm:
    aligner: bwa
    trim_ends: [2,0,2,0]
    min_allele_fraction: 1
    #correct_umis: /path/config/whitelist.txt
    tools_off:
    - gemini
    #umi_type: fastq_name
    variantcaller: [mutect2, vardict]
    variant_regions: ../input/KAPA_HyperExome_capture_targets.bed
    use_lowfreq_filter: false
  analysis: variant2
  description: mpnst
  files:
  - ../input/
  - ../input/
  genome_build: hg38
  metadata:
    phenotype: tumor
resources:
  fgbio:
    options: [--min-reads, 3]
```
**Run:**
```
bcbio_nextgen.py -w /path/to/bcbio-pipeline/tests/somatic_variants/MPNST_exome_test/config/mpnst_analysis-template.yaml  mpnst_analysis.csv ../input
Running bcbio version: 1.2.4
global config: /path/to/bcbio-pipeline/tests/somatic_variants/MPNST_exome_test/config/mpnst_analysis.csv
flowcell directory: /path/to/bcbio-pipeline/tests/somatic_variants/MPNST_exome_test/input
```
**Error:**
```
Traceback (most recent call last):
  File "/path/to/bcbio-pipeline/tools/bin/bcbio_nextgen.py", line 239, in <module>
    setup_info = workflow.setup(kwargs["workflow"], kwargs.pop("inputs"))
  File "/path/to/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/workflow/__init__.py", line 10, in setup
    workflow = workflows[name]
KeyError: '/path/to/file/MPNST_exome_test/config/mpnst_analysis-template.yaml'
```

**Comment by roryk** [comment]
Hi @DolapoA,

It looks like your setup is a little messed up-- the config file doesn't need the `files` section and the `metadata` section. You want to add the `metadata` to your CSV file. https://bcbio-nextgen.readthedocs.io/en/latest/contents/single_cell.html has descriptions for how to do it.

`template` in the `bcbio_nextgen.py -w template` command is literally the word template, that just tells bcbio we are templating, not kicking off a run. Hope that helps get you moving. Sorry for being slow about responding, I was on break.

**Comment by DolapoA** [comment]
Thanks @roryk, the config file has been successfully created.
The problem I'm now having, has to do with checking fastq file sizes during the bcbio run.

**Command:**
```
bcbio_nextgen.py ../config/mpnst_analysis.yaml -n 8
```

**Error message:**

```
Traceback (most recent call last):
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/tools/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 133, in variant2pipeline
    samples = run_parallel("process_alignment", samples)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1032, in __call__
    while self.dispatch_one_batch(iterator):
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 765, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 128, in process_alignment
    return sample.process_alignment(*args)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sample.py", line 132, in process_alignment
    data = align_to_sort_bam(fastq1, fastq2, aligner, data)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/pipeline/alignment.py", line 87, in align_to_sort_bam
    names, align_dir, data)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/pipeline/alignment.py", line 164, in _align_from_fastq
    out = align_fn(fastq1, fastq2, align_ref, names, align_dir, data)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/ngsalign/bwa.py", line 198, in align_pipe
    ("bwa-mem" in dd.get_tools_off(data) or not _can_use_mem(fastq_file, data, min_size))):
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/ngsalign/bwa.py", line 163, in _can_use_mem
    for count, size in fastq_size_output(fastq_file, tocheck):
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/ngsalign/bwa.py", line 146, in fastq_size_output
    raise IOError("Failed to check fastq file sizes with: %s" % cmd.format(**locals()))
OSError: Failed to check fastq file sizes with: export PATH=/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/bin:"$PATH" && zcat /SAN/colcc/pillaylab-software/bcbio-pipeline/tests/somatic_variants/MPNST_exome_test/work/align_prep/KAPA_HyperExome_gene_list.txt.gz | head -n 8000000 | seqtk sample -s42 - 5000 | awk '{if(NR%4==2) print length($1)}' | sort | uniq -c
```

**Comments:**
I've seen a similar error posted before [here](https://github.com/bcbio/bcbio-nextgen/issues/1383). However, when I tried to run it in Scratch as opposed to the cluster I still got the same error message.

**Comment by roryk** [comment]
Hi @DolapoA,

It looks like the config is messed up still-- could you post the configuration in `../config/mpnst_analysis.yaml`?

**Comment by DolapoA** [comment]
I've attached the config file:
[mpnst_analysis.yaml.txt](https://github.com/bcbio/bcbio-nextgen/files/5765872/mpnst_analysis.yaml.txt)

**Comment by naumenko-sa** [comment]
Hi!

I think the last part of the config is messed up:
```
- algorithm:
    aligner: bwa
    min_allele_fraction: 1
    tools_off:
    - gemini
    trim_ends:
    - 2
    - 0
    - 2
    - 0
    use_lowfreq_filter: false
    variant_regions: ../input/KAPA_HyperExome_capture_targets.bed
    variantcaller:
    - mutect2
    - vardict
  analysis: variant2
  description: KAPA_HyperExome_gene_list
  files:
  - /SAN/colcc/pillaylab-software/bcbio-pipeline/tests/somatic_variants/MPNST_exome_test/input/KAPA_HyperExome_gene_list.txt
  genome_build: hg38
```

I think you had `KAPA_HyperExome_gene_list.txt` in the input along with the fastq.gz files and the template script picked it up as a sample.
To avoid that, try:
```
bcbio_nextgen.py -w template template.yaml samples.csv MPNST_exome_test/input/*.gz
```
SN

**Comment by DolapoA** [comment]
Thanks @naumenko-sa, your suggestion got the pipeline running, sadly, during the run it hit another snag which I'm currently looking at, here is the beginning of the error message:
```
[2021-01-06T15:52Z] Running:
[2021-01-06T15:52Z]     java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xms681m -Xmx3181m -XX:+UseSerialGC -Djava.io.tmpdir=/SAN/colcc/pillaylab-software/bcbio-pipeline/tests/somatic_variants/MPNST_exome_test/work/bcbiotx/tmpxhks6td3 -jar /SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/share/gatk4-4.1.9.0-0/gatk-package-4.1.9.0-local.jar FilterMutectCalls --reference /SAN/colcc/pillaylab-software/bcbio-pipeline/genomes/Hsapiens/hg38/seq/hg38.fa --variant /SAN/colcc/pillaylab-software/bcbio-pipeline/tests/somatic_variants/MPNST_exome_test/work/mutect2/chr13/85977_S3_L001-chr13_51451005_69701790-raw.vcf.gz --output /SAN/colcc/pillaylab-software/bcbio-pipeline/tests/somatic_variants/MPNST_exome_test/work/bcbiotx/tmpxhks6td3/85977_S3_L001-chr13_51451005_69701790-raw-filt.vcf.gz
[2021-01-06T15:52Z] Filtering MuTect2 calls with allele fraction threshold of 0.01
*** Error in `/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/bin/python': realloc(): invalid next size: 0x0000561ab3d6d710 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7f5d4)[0x2b868d34e5d4]
/lib64/libc.so.6(+0x83bd8)[0x2b868d352bd8]
/lib64/libc.so.6(realloc+0x1d2)[0x2b868d354832]
/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/cyvcf2/../../../libhts.so.2(+0x53f49)[0x2b882284ef49]
```
**Just the error:**
[bcbio_mpnst_analysis_somatic_variants_ERROR_alone.o2681516.txt](https://github.com/bcbio/bcbio-nextgen/files/5781251/bcbio_mpnst_analysis_somatic_variants_ERROR_alone.o2681516.txt)

**Entire log (11MB):**
[bcbio_mpnst_analysis_somatic_variants.o2681516.txt](https://github.com/bcbio/bcbio-nextgen/files/5781263/bcbio_mpnst_analysis_somatic_variants.o2681516.txt)

**Comment by naumenko-sa** [comment]
Hi @DolapoA !

Glad we got it going!

I see some warnings at the top:
```
WARNING: sample not found 29582_S6_L001_R2_001.fastq.gz
WARNING: sample not found 85517_S1_L001_R2_001.fastq.gz
WARNING: sample not found 85535_S5_L001_R2_001.fastq.gz
WARNING: sample not found 85882_S2_L001_R2_001.fastq.gz
WARNING: sample not found 85977_S3_L001_R2_001.fastq.gz
WARNING: sample not found 85979_S7_L001_R2_001.fastq.gz
WARNING: sample not found 86806_S4_L001_R2_001.fastq.gz
WARNING: sample not found 86814_S8_L001_R2_001.fastq.gz
```
Please make sure that the config yaml contains both fastq files for each sample.
The script is trying to pair sample names and fastq files. Usually, having simple names 
like sample and fastq like sample_1.fq.gz sample_2.fq.gz help. At least, removing suffix "_001" might help.

The failing command is filtering mutect calls. You ran a lot of this commands successfully.
Try running it outside of bcbio (but using bcbio's java and gools) and check the input files - maybe there is no variants?
Also, I found it useful not having sample name starting with a number, it could break some tools, i.e.
using S123 is better than 123 as a sample name.

```bash
java \
-Dsamjdk.use_async_io_read_samtools=false \
-Dsamjdk.use_async_io_write_samtools=true \
-Dsamjdk.use_async_io_write_tribble=false \
-Dsamjdk.compression_level=2 \
-Xms681m \
-Xmx3181m \
-XX:+UseSerialGC \
-Djava.io.tmpdir=. \
-jar /SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/share/gatk4-4.1.9.0-0/gatk-package-4.1.9.0-local.jar \
FilterMutectCalls \
--reference /SAN/colcc/pillaylab-software/bcbio-pipeline/genomes/Hsapiens/hg38/seq/hg38.fa \
--variant /SAN/colcc/pillaylab-software/bcbio-pipeline/tests/somatic_variants/MPNST_exome_test/work/mutect2/chr13/85977_S3_L001-chr13_51451005_69701790-raw.vcf.gz \
--output 85977_S3_L001-chr13_51451005_69701790-raw-filt.vcf.gz
```
SN

**Comment by DolapoA** [comment]
Thank you, I'm suspecting that my R2 files are just dodgy.

**Comment by DolapoA** [comment]
Thanks @naumenko-sa and @roryk .
