### ISSUE TITLE
Is there a way to run all QC on fastqs as a standalone step?

### ISSUE THREAD

**Issue by DolapoA** [bcbio/bcbio-nextgen#3417]
**Question:** Is there a way to create a template and run all the available QC tools on FASTQ files as a stand alone step (and for that matter BAMs)? Which can then be collated using multiQC.

**Comment by naumenko-sa** [comment]
I think you may try variant2 pipeline, just running the alignment
```yaml
aligner: bwa
variantcaller: false
```

or even without the alignment if you start with a bam
```
aligner: false
```

**Comment by DolapoA** [comment]
It seems like your suggestion would work, but I came across an error :/

**Version info:** 
    

- bcbio version (bcbio_nextgen.py --version): 1.2.4
- OS name and version (lsb_release -ds): CentOS Linux release 7.8.2003 (Core)

**To Reproduce**
Exact bcbio command you have used:
[vortex_181123_alignQC_2.yaml.txt](https://github.com/bcbio/bcbio-nextgen/files/5873801/vortex_181123_alignQC_2.yaml.txt)
`bcbio_nextgen.py ../config/vortex_181123_alignQC_2.yaml -n 8`

**Your sample configuration file:**

Example:
```
details:
- algorithm:
    align_split_size: false
    aligner: bwa
    coverage_interval: regional
    effects_transcripts: canonical_cancer
    mark_duplicates: true
    min_allele_fraction: 0.05
    platform: Illumina
    quality_format: Standard
    realign: false
    recalibrate: false
    tools_off:
    - gemini
    tools_on:
    - qualimap_full
    - damage_filter
    - gatk4
    umi_type: fastq_name
    variant_regions: /SAN/colcc/sarcoma_bloodcancer_raw/archive/Vortex/10_Vortex_trial/Targeted_sequencing/Fastq/181123/config/Vortex_3167021_Covered.bed
    variantcaller: false
  analysis: variant2
  description: VOR100_2_S39
  files:
  - /SAN/colcc/sarcoma_bloodcancer_raw/archive/Vortex/10_Vortex_trial/Targeted_sequencing/Fastq/181123/input/VOR100_2_S39_R1_001.fastq.gz
  - /SAN/colcc/sarcoma_bloodcancer_raw/archive/Vortex/10_Vortex_trial/Targeted_sequencing/Fastq/181123/input/VOR100_2_S39_R2_001.fastq.gz
  genome_build: hg19
  metadata:
    phenotype: tumor
    samplename: S39
  resources:
    fgbio:
      options:
      - --min-reads
      - 3
      - --edits
      - 1

```

**Observed behavior**
Error message or bcbio output:
Snippet Beginning

```
[2021-01-21T22:39Z] System YAML configuration: /SAN/colcc/pillaylab-software/bcbio-pipeline/galaxy/bcbio_system.yaml.
[2021-01-21T22:39Z] Locale set to en_US.utf8.
[2021-01-21T22:39Z] Timing: organize samples
[2021-01-21T22:39Z] multiprocessing: organize_samples
[2021-01-21T22:39Z] Using input YAML configuration: /SAN/colcc/sarcoma_bloodcancer_raw/archive/Vortex/10_Vortex_trial/Targeted_sequencing/Fastq/181123/config/vortex_181123_alignQC.yaml
[2021-01-21T22:39Z] Checking sample YAML configuration: /SAN/colcc/sarcoma_bloodcancer_raw/archive/Vortex/10_Vortex_trial/Targeted_sequencing/Fastq/181123/config/vortex_181123_alignQC.yaml
[2021-01-21T23:26Z] System YAML configuration: /SAN/colcc/pillaylab-software/bcbio-pipeline/galaxy/bcbio_system.yaml.
[2021-01-21T23:26Z] Locale set to en_US.utf8.
[2021-01-21T23:26Z] Timing: organize samples
[2021-01-21T23:26Z] multiprocessing: organize_samples
[2021-01-21T23:26Z] Using input YAML configuration: /SAN/colcc/sarcoma_bloodcancer_raw/archive/Vortex/10_Vortex_trial/Targeted_sequencing/Fastq/181123/config/vortex_181123_alignQC.yaml
[2021-01-21T23:26Z] Checking sample YAML configuration: /SAN/colcc/sarcoma_bloodcancer_raw/archive/Vortex/10_Vortex_trial/Targeted_sequencing/Fastq/181123/config/vortex_181123_alignQC.yaml
[2021-01-25T08:20Z] System YAML configuration: /SAN/colcc/pillaylab-software/bcbio-pipeline/galaxy/bcbio_system.yaml.
[2021-01-25T08:20Z] Locale set to en_US.utf8.
[2021-01-25T08:20Z] Timing: organize samples
[2021-01-25T08:20Z] multiprocessing: organize_samples
[2021-01-25T08:20Z] Using input YAML configuration: /SAN/colcc/sarcoma_bloodcancer_raw/archive/Vortex/10_Vortex_trial/Targeted_sequencing/Fastq/181123/config/vortex_181123_alignQC.yaml
[2021-01-25T08:20Z] Checking sample YAML configuration: /SAN/colcc/sarcoma_bloodcancer_raw/archive/Vortex/10_Vortex_trial/Targeted_sequencing/Fastq/181123/config/vortex_181123_alignQC.yaml
[2021-01-25T08:20Z] Retreiving program versions from /SAN/colcc/pillaylab-software/bcbio-pipeline/manifest/python-packages.yaml.
[2021-01-25T08:20Z] Retreiving program versions from /SAN/colcc/pillaylab-software/bcbio-pipeline/manifest/r-packages.yaml.
[2021-01-25T08:20Z] Testing minimum versions of installed programs
[2021-01-25T08:20Z] Timing: alignment preparation
[2021-01-25T08:20Z] multiprocessing: prep_align_inputs
[2021-01-25T08:20Z] Skipping trimming of VOR100_2_S39.
[2021-01-25T08:20Z] Skipping trimming of VOR103_2_S40.
[2021-01-25T08:20Z] Skipping trimming of VOR105_2_S41.
[2021-01-25T08:20Z] Skipping trimming of VOR108_2_S42.
[2021-01-25T08:20Z] Skipping trimming of VOR109_2_S43.
[2021-01-25T08:20Z] Skipping trimming of VOR110_2_S44.
[2021-01-25T08:20Z] Skipping trimming of VOR112_2_S45.
[2021-01-25T08:20Z] Skipping trimming of VOR11_2_S2.
[2021-01-25T08:20Z] Skipping trimming of VOR114_2_S46.
[2021-01-25T08:20Z] Skipping trimming of VOR125_2_S47.
[2021-01-25T08:20Z] Skipping trimming of VOR128_2_S48.
[2021-01-25T08:20Z] Skipping trimming of VOR13_2_S3.
[2021-01-25T08:20Z] Skipping trimming of VOR18_2_S4.
[2021-01-25T08:20Z] Skipping trimming of VOR20_2_S5.
[2021-01-25T08:20Z] Skipping trimming of VOR21_2_S6.
[2021-01-25T08:20Z] Skipping trimming of VOR22_2_S7.
[2021-01-25T08:20Z] Skipping trimming of VOR24_2_S8.
[2021-01-25T08:20Z] Skipping trimming of VOR26_2_S9.
[2021-01-25T08:20Z] Skipping trimming of VOR27_2_S10.
[2021-01-25T08:20Z] Skipping trimming of VOR28_2_S11.
[2021-01-25T08:20Z] Skipping trimming of VOR33_2_S12.
[2021-01-25T08:20Z] Skipping trimming of VOR36_2_S13.
[2021-01-25T08:20Z] Skipping trimming of VOR38_2_S14.
[2021-01-25T08:20Z] Skipping trimming of VOR40_2_S15.
[2021-01-25T08:20Z] Skipping trimming of VOR41_2_S16.
[2021-01-25T08:20Z] Skipping trimming of VOR42_2_S17.
[2021-01-25T08:20Z] Skipping trimming of VOR44_2_S18.
[2021-01-25T08:20Z] Skipping trimming of VOR50_2_S19.
[2021-01-25T08:20Z] Skipping trimming of VOR54_2_S20.
[2021-01-25T08:20Z] Skipping trimming of VOR57_2_S21.
[2021-01-25T08:20Z] Skipping trimming of VOR58_2_S22.
[2021-01-25T08:20Z] Skipping trimming of VOR59_2_S23.
[2021-01-25T08:20Z] Skipping trimming of VOR62_2_S24.
[2021-01-25T08:20Z] Skipping trimming of VOR63_2_S25.
[2021-01-25T08:20Z] Skipping trimming of VOR66_2_S26.
[2021-01-25T08:20Z] Skipping trimming of VOR67_2_S27.
[2021-01-25T08:20Z] Skipping trimming of VOR68_2_S28.
[2021-01-25T08:20Z] Skipping trimming of VOR72_2_S29.
[2021-01-25T08:20Z] Skipping trimming of VOR73_2_S30.
[2021-01-25T08:20Z] Skipping trimming of VOR78_2_S31.
[2021-01-25T08:20Z] Skipping trimming of VOR80_2_S32.
[2021-01-25T08:20Z] Skipping trimming of VOR82_2_S33.
[2021-01-25T08:20Z] Skipping trimming of VOR8_2_S1.
[2021-01-25T08:20Z] Skipping trimming of VOR88_2_S34.
[2021-01-25T08:20Z] Skipping trimming of VOR89_2_S35.
[2021-01-25T08:20Z] Skipping trimming of VOR93_2_S36.
[2021-01-25T08:20Z] Skipping trimming of VOR95_2_S37.
[2021-01-25T08:20Z] Skipping trimming of VOR98_2_S38.
[2021-01-25T08:20Z] multiprocessing: disambiguate_split
[2021-01-25T08:20Z] Timing: alignment
[2021-01-25T08:20Z] multiprocessing: process_alignment
[2021-01-25T08:20Z] Aligning lane VOR100_2_S39 with bwa aligner
[2021-01-25T08:33Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && /SAN/colcc/pillaylab-software/bcbio-pipeline/galaxy/../anaconda/bin/fgbio -Xms750m -Xmx15g -XX:+UseSerialGC --tmp-dir /SAN/colcc/sarcoma_bloodcancer_raw/archive/Vortex/10_Vortex_trial/Targeted_sequencing/Fastq/181123/work/bcbiotx/tmp7ay0o373 --async-io=true --compression=0 GroupReadsByUmi --edits=1 --min-map-q=1 -t RX -s adjacency -i /SAN/colcc/sarcoma_bloodcancer_raw/archive/Vortex/10_Vortex_trial/Targeted_sequencing/Fastq/181123/work/align/VOR100_2_S39/VOR100_2_S39-sort.bam -f /SAN/colcc/sarcoma_bloodcancer_raw/archive/Vortex/10_Vortex_trial/Targeted_sequencing/Fastq/181123/work/bcbiotx/tmp7ay0o373/VOR100_2_S39-sort.family_size_histogram.tsv | /SAN/colcc/pillaylab-software/bcbio-pipeline/galaxy/../anaconda/bin/fgbio -Xms750m -Xmx15g -XX:+UseSerialGC --tmp-dir /SAN/colcc/sarcoma_bloodcancer_raw/archive/Vortex/10_Vortex_trial/Targeted_sequencing/Fastq/181123/work/bcbiotx/tmp7ay0o373 --async-io=true --compression=0 CallMolecularConsensusReads --min-input-base-quality=2 --min-reads=3 --max-reads=100000 --output-per-base-tags=false --sort-order=:none: -i /dev/stdin -o /dev/stdout | /SAN/colcc/pillaylab-software/bcbio-pipeline/galaxy/../anaconda/bin/fgbio -Xms750m -Xmx15g -XX:+UseSerialGC --tmp-dir /SAN/colcc/sarcoma_bloodcancer_raw/archive/Vortex/10_Vortex_trial/Targeted_sequencing/Fastq/181123/work/bcbiotx/tmp7ay0o373 --async-io=true --compression=0 FilterConsensusReads --min-reads=3 --min-base-quality=13 --max-base-error-rate=0.1 -r /SAN/colcc/pillaylab-software/bcbio-pipeline/genomes/Hsapiens/hg19/seq/hg19.fa -i /dev/stdin -o /dev/stdout | /SAN/colcc/pillaylab-software/bcbio-pipeline/galaxy/../anaconda/bin/bamtofastq collate=1 T=/SAN/colcc/sarcoma_bloodcancer_raw/archive/Vortex/10_Vortex_trial/Targeted_sequencing/Fastq/181123/work/align/VOR100_2_S39/VOR100_2_S39-sort-cumi-1-bamtofastq-tmp F=/SAN/colcc/sarcoma_bloodcancer_raw/archive/Vortex/10_Vortex_trial/Targeted_sequencing/Fastq/181123/work/bcbiotx/tmp7ay0o373/VOR100_2_S39-sort-cumi-1.fq.gz F2=/SAN/colcc/sarcoma_bloodcancer_raw/archive/Vortex/10_Vortex_trial/Targeted_sequencing/Fastq/181123/work/bcbiotx/tmp7ay0o373/VOR100_2_S39-sort-cumi-2.fq.gz tags=cD,cM,cE gz=1
BgzfInflateHeaderBase::readHeader(): invalid header data (unexpected bytes)
```

Snippet End
```
[V] blocks generated in time 07:58:64355199
[V] number of blocks to be merged is 11 using 744 blocks per input with block size 1048576
ERROR:umis.umis:No annotation present on this file, aborting.
' returned non-zero exit status 1.
```
**What worked**
FastQs were aligned.
Samtools QC complete. 

**Expected behavior**
Produce multiQC with various QC results. And to go no further, as in no variant calling. 

**Log files:**
[bcbio-nextgen.log.txt](https://github.com/bcbio/bcbio-nextgen/files/5873705/bcbio-nextgen.log.txt)
[bcbio-nextgen-commands.log.txt](https://github.com/bcbio/bcbio-nextgen/files/5873706/bcbio-nextgen-commands.log.txt)
[bcbio-nextgen-debug.log.txt](https://github.com/bcbio/bcbio-nextgen/files/5873707/bcbio-nextgen-debug.log.txt)

**Comment by roryk** [comment]
It looks like you haven't run the initial step to put the UMIs in the FASTQ name-- https://bcbio-nextgen.readthedocs.io/en/latest/contents/somatic_variants.html#umis has information about how to do that.

**Comment by DolapoA** [comment]
I apologise, I posted the wrong config file as an example.
I've now corrected it.

**Comment by roryk** [comment]
Thanks, this error:

```
[V] blocks generated in time 07:58:64355199
[V] number of blocks to be merged is 11 using 744 blocks per input with block size 1048576
ERROR:umis.umis:No annotation present on this file, aborting.
' returned non-zero exit status 1.
```

is saying that the UMIs are not actually in the FASTQ name in your file. Is that the case? The documentation I linked to above shows how to run that, if they are not in there already. Depending on your chemistry you might have to tweak some of the options though; if you could describe what your samples are we could help more.

**Comment by DolapoA** [comment]
If I don't wish to use UMIs, which options/parameters in my config file would you say I should remove?

**Comment by roryk** [comment]
Hi @DolapoA,

It should be turned off if you don't have `umi_type` set. Are you sure the log you posted is from the run you did that didn't have that set?

Are you sure you don't have UMIs in your sample? Often times panel sequencing does have UMIs, and they are extremely important for calling.

**Comment by DolapoA** [comment]
Ok thank you @roryk , that's been corrected now.
It ran more smoothly until...
I noticed that my Java option was set to `-Xmx30g`, does this need to be bumped up to correct for the error below:
'''
[2021-01-28T23:37Z] QC: VOR129_2_PGU_S1 peddy
[2021-01-28T23:37Z] QC: VOR129_2_PGU_S1 picard
[2021-01-28T23:37Z] QC: VOR129_2_PGU_S1 qsignature
[2021-01-28T23:37Z] QC: VOR129_2_PGU_S1 qualimap
[2021-01-28T23:37Z] Full qualimap analysis for /SAN/colcc/sarcoma_bloodcancer_raw/archive/Vortex/10_Vortex_trial/Targeted_sequencing/Fastq/181126/work/align/VOR129_2_PGU_S1/VOR129_2_PGU_S1-sort.bam may be slow.
[2021-01-28T23:37Z] Prepare merged BED file : VOR129_2_PGU_S1
[2021-01-28T23:37Z] bgzip cleaned-Vortex_3167021_Covered-merged-merged.bed
[2021-01-28T23:37Z] tabix index cleaned-Vortex_3167021_Covered-merged-merged.bed.gz
[2021-01-28T23:37Z] Qualimap: VOR129_2_PGU_S1
[2021-01-28T23:37Z] Java memory size is set to 1200M
[2021-01-28T23:37Z] Launching application...
[2021-01-28T23:37Z] detected environment java options -Xms32m **-Xmx30g** -Djava.io.tmpdir=/SAN/colcc/sarcoma_bloodcancer_raw/archive/Vortex/10_Vortex_trial/Targeted_sequencing/Fastq/181126/work/bcbiotx/tmp11krk1f_$
[2021-01-28T23:37Z] Error occurred during initialization of VM
[2021-01-28T23:37Z] **Could not reserve enough space for 31457280KB object heap**
[2021-01-28T23:37Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset DISPLAY && export LD_PRELOAD=/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/libfreetype.so && export PATH=/SAN/colcc/pillaylab-software/$
Java memory size is set to 1200M
Launching application...
detected environment java options -Xms32m -Xmx30g -Djava.io.tmpdir=/SAN/colcc/sarcoma_bloodcancer_raw/archive/Vortex/10_Vortex_trial/Targeted_sequencing/Fastq/181126/work/bcbiotx/tmp11krk1f_/VOR129_2_PGU_S1
Error occurred during initialization of VM
Could not reserve enough space for 31457280KB object heap
' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/tools/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 191, in variant2pipeline
    samples = qcsummary.generate_parallel(samples, run_parallel)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/pipeline/qcsummary.py", line 43, in generate_parallel
    qced = run_parallel("pipeline_summary", to_analyze)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1032, in __call__
    while self.dispatch_one_batch(iterator):
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 765, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 243, in pipeline_summary
    return qcsummary.pipeline_summary(*args)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/pipeline/qcsummary.py", line 79, in pipeline_summary
    data["summary"] = _run_qc_tools(work_bam, work_data)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/pipeline/qcsummary.py", line 175, in _run_qc_tools
    out = qc_fn(bam_file, data, cur_qc_dir)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/qc/qualimap.py", line 77, in run
    do.run(cmd.format(**locals()), "Qualimap: %s" % dd.get_sample_name(data), env=bcbio_env)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset DISPLAY && export LD_PRELOAD=/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/libfreetype.so && export PATH=/SAN/colcc/pillaylab-software/$
Java memory size is set to 1200M
Launching application...
detected environment java options -Xms32m -Xmx30g -Djava.io.tmpdir=/SAN/colcc/sarcoma_bloodcancer_raw/archive/Vortex/10_Vortex_trial/Targeted_sequencing/Fastq/181126/work/bcbiotx/tmp11krk1f_/VOR129_2_PGU_S1
Error occurred during initialization of VM
Could not reserve enough space for 31457280KB object heap
' returned non-zero exit status 1.
'''

**Comment by roryk** [comment]
Heya, it looks more like you didn't have 30g available to be reserved on the compute you were on, do the machines have enough RAM? If so is the RAM actually available on the node? It would help to know if you are running on a scheduler and which one to debug some more.

**Comment by DolapoA** [comment]
Thanks @roryk .
