### ISSUE TITLE
Error in multiprocessing: run_rapmap_index

### ISSUE THREAD

**Issue by ryanccarelli** [bcbio/bcbio-nextgen#3428]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.5
- OS name and version (`lsb_release -ds`): Ubuntu 18.04 LTS

**To Reproduce**
Exact bcbio command you have used:
```
bcbio_nextgen.py hp5382_config.yaml
```
Your sample configuration file:
```
details:
- algorithm:
    cellular_barcode_correction: 1
    minimum_barcode_depth: 1000
    sample_barcodes: /home/ryc4001/data/scrnaseq/sample-barcodes-rc.txt
    transcriptome_fasta: /home/ryc4001/Documents/bcbio/genomes/Mmusculus/mm10/rnaseq/ref-transcripts.fa
    transcriptome_gtf: /home/ryc4001/Documents/bcbio/genomes/Mmusculus/mm10/rnaseq/ref-transcripts.gtf
    umi_type: harvard-indrop-v3
  analysis: scRNA-seq
  description: prostate
  files:
  - /home/ryc4001/data/scrnaseq/hp5382/20180327_pool_HP5382_S1_R1_001.fastq.gz
  - /home/ryc4001/data/scrnaseq/hp5382/20180327_pool_HP5382_S1_R2_001.fastq.gz
  - /home/ryc4001/data/scrnaseq/hp5382/20180327_pool_HP5382_S1_R3_001.fastq.gz
  - /home/ryc4001/data/scrnaseq/hp5382/20180327_pool_HP5382_S1_R4_001.fastq.gz
  genome_build: mm10
  metadata: {}
fc_name: prostate-rerun
upload:
  dir: ../final
```

**Observed behavior**
Error message or bcbio output:
```
Running bcbio version: 1.2.5
global config: /home/ryc4001/data/scrnaseq/bcbio_system.yaml
run info config: /home/ryc4001/data/scrnaseq/hp5382_config.yaml
[2021-01-26T23:40Z] System YAML configuration: /home/ryc4001/bcbio/galaxy/bcbio_system.yaml.
[2021-01-26T23:40Z] Locale set to C.UTF-8.
[2021-01-26T23:40Z] Resource requests: picard; memory: 4.00; cores: 16
[2021-01-26T23:40Z] Configuring 1 jobs to run, using 1 cores each with 4.00g of memory reserved for each job
[2021-01-26T23:40Z] Timing: organize samples
[2021-01-26T23:40Z] multiprocessing: organize_samples
[2021-01-26T23:40Z] Using input YAML configuration: /home/ryc4001/data/scrnaseq/hp5382_config.yaml
[2021-01-26T23:40Z] Checking sample YAML configuration: /home/ryc4001/data/scrnaseq/hp5382_config.yaml
[2021-01-26T23:40Z] Retreiving program versions from /home/ryc4001/bcbio/manifest/python-packages.yaml.
[2021-01-26T23:40Z] Retreiving program versions from /home/ryc4001/bcbio/manifest/r-packages.yaml.
[2021-01-26T23:40Z] Testing minimum versions of installed programs
[2021-01-26T23:40Z] multiprocessing: prepare_sample
[2021-01-26T23:40Z] Preparing prostate
[2021-01-26T23:40Z] Resource requests: rapmap, samtools; memory: 4.00, 4.00; cores: 16, 16
[2021-01-26T23:40Z] Configuring 1 jobs to run, using 1 cores each with 4.00g of memory reserved for each job
[2021-01-26T23:40Z] Timing: singlecell-rnaseq
[2021-01-26T23:40Z] multiprocessing: run_umi_transform
[2021-01-26T23:40Z] Inserting UMI and barcode information into the read name of /home/ryc4001/data/scrnaseq/hp5382/20180327_pool_HP5382_S1_R1_001.fastq.gz
[2021-01-26T23:40Z] INFO:umis.umis:Transforming /home/ryc4001/data/scrnaseq/hp5382/20180327_pool_HP5382_S1_R1_001.fastq.gz.
[2021-01-26T23:40Z] INFO:umis.umis:Detected dual cellular indexes.
[2021-01-26T23:40Z] INFO:umis.umis:Detected UMI.
[2021-01-26T23:40Z] INFO:umis.umis:Detected sample.
[2021-01-27T04:52Z] multiprocessing: demultiplex_samples
[2021-01-27T04:52Z] Demultiplexing /home/ryc4001/data/scrnaseq/umis/prostate.umitransformed.fq.gz.
[2021-01-27T05:52Z] multiprocessing: run_rapmap_index
Traceback (most recent call last):
  File "/home/ryc4001/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/home/ryc4001/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/ryc4001/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/home/ryc4001/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/ryc4001/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 316, in singlecellrnaseqpipeline
    samples = rnaseq.singlecell_rnaseq(samples, run_parallel)
  File "/home/ryc4001/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/rnaseq.py", line 36, in singlecell_rnaseq
    samples = run_parallel("run_rapmap_index", [samples])
  File "/home/ryc4001/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/ryc4001/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 82, in run_multicore
    items = [config_utils.add_cores_to_config(x, parallel["cores_per_job"]) for x in items]
  File "/home/ryc4001/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 82, in <listcomp>
    items = [config_utils.add_cores_to_config(x, parallel["cores_per_job"]) for x in items]
  File "/home/ryc4001/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/config_utils.py", line 306, in add_cores_to_config
    return _update_config(args, _update_cores)
  File "/home/ryc4001/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/config_utils.py", line 321, in _update_config
    raise ValueError("Could not find configuration in args: %s" % str(args))
ValueError: Could not find configuration in args: []
```

**Expected behavior**
I expected this to run the scrnaseq pipeline.

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.
[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/5881356/bcbio-nextgen-commands.log)
[bcbio-nextgen-debug.log](https://github.com/bcbio/bcbio-nextgen/files/5881357/bcbio-nextgen-debug.log)
[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/5881358/bcbio-nextgen.log)

**Additional context**
I am using a customized version of mm10 including human transgenes that was created using the bcbio_setup_genome.py script. I tried the obvious things (reinstallation, running on default mm10 instead of version with transgenes) but no luck.
Thanks for your help! Hopefully I am not missing something obvious here...

**Comment by naumenko-sa** [comment]
Hi @ryanccarelli !

Thanks for reporting - sorry about the issues!
Please make sure that your project is following the project structure:
https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#project-structure

i.e. you config hp5382_config.yaml is in `project/config/hp5382_config.yaml` and your are launching bcbio as
```bash
cd /project/work
bcbio_nextgen.py ../config/hp5382_config.yaml -n 10
```
(or likewise in the launch script)

Sergey

**Comment by ryanccarelli** [comment]
Hi Sergey,

After rerunning with the suggested directory structure I get the same error:
```
Running bcbio version: 1.2.5
global config: /home/ryc4001/data/scrnaseq/trg_indrops/work/bcbio_system.yaml
run info config: /home/ryc4001/data/scrnaseq/trg_indrops/config/hp5382_config.yaml
[2021-02-01T14:44Z] System YAML configuration: /home/ryc4001/bcbio/galaxy/bcbio_system.yaml.
[2021-02-01T14:44Z] Locale set to C.UTF-8.
[2021-02-01T14:44Z] Resource requests: picard; memory: 4.00; cores: 16
[2021-02-01T14:44Z] Configuring 1 jobs to run, using 1 cores each with 4.00g of memory reserved for each job
[2021-02-01T14:44Z] Timing: organize samples
[2021-02-01T14:44Z] multiprocessing: organize_samples
[2021-02-01T14:44Z] Using input YAML configuration: /home/ryc4001/data/scrnaseq/trg_indrops/config/hp5382_config.yaml
[2021-02-01T14:44Z] Checking sample YAML configuration: /home/ryc4001/data/scrnaseq/trg_indrops/config/hp5382_config.yaml
[2021-02-01T14:44Z] Retreiving program versions from /home/ryc4001/bcbio/manifest/python-packages.yaml.
[2021-02-01T14:44Z] Retreiving program versions from /home/ryc4001/bcbio/manifest/r-packages.yaml.
[2021-02-01T14:44Z] Testing minimum versions of installed programs
[2021-02-01T14:44Z] multiprocessing: prepare_sample
[2021-02-01T14:44Z] Preparing prostate
[2021-02-01T14:44Z] Resource requests: rapmap, samtools; memory: 4.00, 4.00; cores: 16, 16
[2021-02-01T14:44Z] Configuring 1 jobs to run, using 16 cores each with 64.1g of memory reserved for each job
[2021-02-01T14:44Z] Timing: singlecell-rnaseq
[2021-02-01T14:44Z] multiprocessing: run_umi_transform
[2021-02-01T14:44Z] Inserting UMI and barcode information into the read name of /home/ryc4001/data/scrnaseq/trg_indrops/input/20180327_pool_HP5382_S1_R1_001.fastq.gz
[2021-02-01T14:44Z] INFO:umis.umis:Transforming /home/ryc4001/data/scrnaseq/trg_indrops/input/20180327_pool_HP5382_S1_R1_001.fastq.gz.
[2021-02-01T14:44Z] INFO:umis.umis:Detected dual cellular indexes.
[2021-02-01T14:44Z] INFO:umis.umis:Detected UMI.
[2021-02-01T14:44Z] INFO:umis.umis:Detected sample.
[2021-02-01T18:07Z] multiprocessing: demultiplex_samples
[2021-02-01T18:07Z] Demultiplexing /home/ryc4001/data/scrnaseq/trg_indrops/work/umis/prostate.umitransformed.fq.gz.
[2021-02-01T19:07Z] multiprocessing: run_rapmap_index
Traceback (most recent call last):
  File "/home/ryc4001/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/home/ryc4001/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/ryc4001/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/home/ryc4001/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/ryc4001/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 316, in singlecellrnaseqpipeline
    samples = rnaseq.singlecell_rnaseq(samples, run_parallel)
  File "/home/ryc4001/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/rnaseq.py", line 36, in singlecell_rnaseq
    samples = run_parallel("run_rapmap_index", [samples])
  File "/home/ryc4001/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/ryc4001/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 82, in run_multicore
    items = [config_utils.add_cores_to_config(x, parallel["cores_per_job"]) for x in items]
  File "/home/ryc4001/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 82, in <listcomp>
    items = [config_utils.add_cores_to_config(x, parallel["cores_per_job"]) for x in items]
  File "/home/ryc4001/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/config_utils.py", line 306, in add_cores_to_config
    return _update_config(args, _update_cores)
  File "/home/ryc4001/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/config_utils.py", line 321, in _update_config
    raise ValueError("Could not find configuration in args: %s" % str(args))
ValueError: Could not find configuration in args: []
```

**Comment by roryk** [comment]
Hi Ryan,

Sorry for the problems-- hm. Could you look in the `work/umis` directory and see if the files demultiplexed by sample are there?

**Comment by ryanccarelli** [comment]
Hi Rory,
Good to hear from you, hope you are well! Here is the directory
```
(base) ryc4001@dell-desktop:~/data/scrnaseq/trg_indrops/work/umis$ ls -R -l
.:
total 20197580
drwxr-xr-x 3 ryc4001 ryc4001        4096 Feb  2 13:25 prostate
-rw-r--r-- 1 ryc4001 ryc4001 20682311898 Feb  1 13:07 prostate.umitransformed.fq.gz

./prostate:
total 8
-rw-r--r-- 1 ryc4001 ryc4001   72 Feb  1 13:07 barcodes.csv
drwxr-xr-x 2 ryc4001 ryc4001 4096 Feb  1 13:07 demultiplexed

./prostate/demultiplexed:
total 0
```

**Comment by roryk** [comment]
Great! I think I see the problem, it looks like there hasn't been any samples that were able to be demultiplexed. I will add a check for that in the code so it spits out a more useful error message.

What does ` /home/ryc4001/data/scrnaseq/sample-barcodes-rc.txt` look like? 

If you check the sample barcodes like this:

```bash
gunzip -c /home/ryc4001/data/scrnaseq/hp5382/20180327_pool_HP5382_S1_R3_001.fastq.gz | awk '{if(NR%4 == 2) print $0}' | head -n 400000 | sort | uniq -c | sort -k1,1rn | awk '{print $2","$1}' | head
```

Do the top ones match the ones that are in your `/home/ryc4001/data/scrnaseq/sample-barcodes-rc.txt` file?

Thanks! Sorry for all the back and forth.

**Comment by roryk** [comment]
Thanks for closing Ryan, did that end up being the issue? Just to close the loop.

**Comment by ryanccarelli** [comment]
Yes it did, thanks for your help and sorry that it wasn't a bug in bcbio!

**Comment by roryk** [comment]
Hi Ryan, awesome! Thanks for following up!

**Comment by roryk** [comment]
Thanks Ryan, I added some code to catch this and link to the resolution here.
