### ISSUE TITLE
deepvariant still throwing errors during fresh installation

### ISSUE THREAD

**Issue by djb17** [bcbio/bcbio-nextgen#3438]
Hello,

Even after referring to previous issue (https://github.com/bcbio/bcbio-nextgen/issues/2613#issue-397148845) involving deepvariant installation, I can't seem to resolve the problem. The error occurs after conda finishes downloading the models for deepvariant (signal hanlder TypeError).

Any help would be appreciated.

Thanks.

**Observed behavior**
Error message or bcbio output:
```
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'bioconda::deepvariant-1.0.0-py36hf5a246b_0'.
Rolling back transaction: done

LinkError: post-link script failed for package bioconda::deepvariant-1.0.0-py36hf5a246b_0
location of failed script: /storage/bcbio/anaconda/envs/dv/bin/.deepvariant-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: 
stderr: Copying gs://deepvariant/models/DeepVariant/0.10.0/DeepVariant-inception_v3-0.10.0+data-wgs_standard/model.ckpt.data-00000-of-00001...
WARNING: Found no hashes to validate object downloaded to /storage/bcbio/anaconda/envs/dv/share/deepvariant-1.0.0-0/models/DeepVariant/0.10.0/DeepVariant-inception_v3-0.10.0+data-wgs_standard/model.ckpt.data-00000-of-00001. Integrity cannot be assured witho
ut hashes.
Copying gs://deepvariant/models/DeepVariant/0.10.0/DeepVariant-inception_v3-0.10.0+data-wgs_standard/model.ckpt.index...
WARNING: Found no hashes to validate object downloaded to /storage/bcbio/anaconda/envs/dv/share/deepvariant-1.0.0-0/models/DeepVariant/0.10.0/DeepVariant-inception_v3-0.10.0+data-wgs_standard/model.ckpt.index. Integrity cannot be assured without hashes.
Copying gs://deepvariant/models/DeepVariant/0.10.0/DeepVariant-inception_v3-0.10.0+data-wgs_standard/model.ckpt.meta...
WARNING: Found no hashes to validate object downloaded to /storage/bcbio/anaconda/envs/dv/share/deepvariant-1.0.0-0/models/DeepVariant/0.10.0/DeepVariant-inception_v3-0.10.0+data-wgs_standard/model.ckpt.meta. Integrity cannot be assured without hashes.
| [3 files][357.9 MiB/357.9 MiB]                                                
Operation completed over 3 objects/357.9 MiB. 
Traceback (most recent call last):
  File "/storage/bcbio/anaconda/envs/dv/bin/../share/google-cloud-sdk-328.0.0-0/bin/bootstrapping/gsutil.py", line 133, in <module>
    exceptions.HandleError(e, 'gsutil')
  File "/storage/bcbio/anaconda/envs/dv/share/google-cloud-sdk-328.0.0-0/lib/googlecloudsdk/calliope/exceptions.py", line 551, in HandleError
    core_exceptions.reraise(exc)
  File "/storage/bcbio/anaconda/envs/dv/share/google-cloud-sdk-328.0.0-0/lib/googlecloudsdk/core/exceptions.py", line 146, in reraise
    six.reraise(type(exc_value), exc_value, tb)
  File "/storage/bcbio/anaconda/envs/dv/share/google-cloud-sdk-328.0.0-0/lib/third_party/six/__init__.py", line 693, in reraise
    raise value
  File "/storage/bcbio/anaconda/envs/dv/bin/../share/google-cloud-sdk-328.0.0-0/bin/bootstrapping/gsutil.py", line 131, in <module>
    main()
  File "/storage/bcbio/anaconda/envs/dv/bin/../share/google-cloud-sdk-328.0.0-0/bin/bootstrapping/gsutil.py", line 112, in main
    bootstrapping.ExecutePythonTool('platform/gsutil', 'gsutil', *args)
  File "/storage/bcbio/anaconda/envs/dv/share/google-cloud-sdk-328.0.0-0/bin/bootstrapping/bootstrapping.py", line 115, in ExecutePythonTool
    _FullPath(tool_dir, exec_name), *args, python=py_path))
  File "/storage/bcbio/anaconda/envs/dv/share/google-cloud-sdk-328.0.0-0/bin/bootstrapping/bootstrapping.py", line 205, in _ExecuteTool
    execution_utils.Exec(args + sys.argv[1:], env=_GetToolEnv())
  File "/storage/bcbio/anaconda/envs/dv/share/google-cloud-sdk-328.0.0-0/lib/googlecloudsdk/core/execution_utils.py", line 372, in Exec
    **extra_popen_kwargs)
  File "/storage/bcbio/anaconda/envs/dv/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/storage/bcbio/anaconda/envs/dv/share/google-cloud-sdk-328.0.0-0/lib/googlecloudsdk/core/execution_utils.py", line 270, in _ReplaceSignal
    signal.signal(signo, old_handler)
  File "/storage/bcbio/anaconda/envs/dv/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))

TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object

return code: 1

()
```

**Comment by jxshi** [comment]
@djb17  I have encountered this error before. It's probably an intermittent internet error if you are currently in China mainland. You may need a VPN to finish your fresh install of deepvariant software.

**Comment by djb17** [comment]
@jxshi I'm currently based in the US so I don't think that's the problem

**Comment by naumenko-sa** [comment]
Hi @djb17 !

We have recently had fresh installations of bcbio 1.2.7 both on CentOS7 and AWS Ubuntu machines without issues.
deepvariant-1.0.0 was installed in the dp conda environment.

Sorry - we are currently can't help much with google cloud or with running deep variant in bcbio - there were also numerous issues. It is on our priority list, but only on the 3rd level:
https://github.com/bcbio/bcbio-nextgen/issues/3242

If that is something you are willing to help with and contribute to bcbio, you are more than welcome!

Sergey
