### ISSUE TITLE
library(tidyverse) : there is no package called ‘tidyverse’

### ISSUE THREAD

**Issue by tykim0109** [bcbio/bcbio-nextgen#3445]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.7
- OS name and version (`lsb_release -ds`): Ubuntu 18.04.4 LTS

**To Reproduce**
Exact bcbio command you have used:
```
bcbio_nextgen.py ../config/K0008-K0011_RNA_updated.yaml -n 96
```
Your sample configuration file:
```
details:
- algorithm:
    aligner: star
    fusion_caller:
    - pizzly
    - oncofuse
    - arriba
    hlacaller: optitype
    strandedness: firststrand
    variantcaller:
    - gatk-haplotype
  analysis: RNA-seq
  description: K0006-BF1-RNAseq
  files:
  - /apps2/data/K008-K0011_Target_Discovery/input/RNA/S1N7CLEQE-23022021_S10_R1_001.fastq.gz
  - /apps2/data/K008-K0011_Target_Discovery/input/RNA/S1N7CLEQE-23022021_S10_R2_001.fastq.gz
  genome_build: hg38
  metadata:
    batch: K0006-BF1
    phenotype: tumor
    validate_batch: group0
- algorithm:
    aligner: star
    fusion_caller:
    - pizzly
    - oncofuse
    - arriba
    hlacaller: optitype
    strandedness: firststrand
    variantcaller:
    - gatk-haplotype
  analysis: RNA-seq
  description: K0011-BF1-RNAseq
  files:
  - /apps2/data/K008-K0011_Target_Discovery/input/RNA/S6TRHC9B1-23022021_S16_R1_001.fastq.gz
  - /apps2/data/K008-K0011_Target_Discovery/input/RNA/S6TRHC9B1-23022021_S16_R2_001.fastq.gz
  genome_build: hg38
  metadata:
    batch: K0011-BF1
    phenotype: tumor
    validate_batch: group4
- algorithm:
    aligner: star
    fusion_caller:
    - pizzly
    - oncofuse
    - arriba
    hlacaller: optitype
    strandedness: firststrand
    variantcaller:
    - gatk-haplotype
  analysis: RNA-seq
  description: K0011-AF1-RNAseq
  files:
  - /apps2/data/K008-K0011_Target_Discovery/input/RNA/SK6762KAZ-23022021_S15_R1_001.fastq.gz
  - /apps2/data/K008-K0011_Target_Discovery/input/RNA/SK6762KAZ-23022021_S15_R2_001.fastq.gz
  genome_build: hg38
  metadata:
    batch: K0011-AF1
    phenotype: tumor
    validate_batch: group4
- algorithm:
    aligner: star
    fusion_caller:
    - pizzly
    - oncofuse
    - arriba
    hlacaller: optitype
    strandedness: firststrand
    variantcaller:
    - gatk-haplotype
  analysis: RNA-seq
  description: K0009-AF1-RNAseq
  files:
  - /apps2/data/K008-K0011_Target_Discovery/input/RNA/SM30WC7P9-23022021_S13_R1_001.fastq.gz
  - /apps2/data/K008-K0011_Target_Discovery/input/RNA/SM30WC7P9-23022021_S13_R2_001.fastq.gz
  genome_build: hg38
  metadata:
    batch: K0009-AF1
    phenotype: tumor
    validate_batch: group2
- algorithm:
    aligner: star
    fusion_caller:
    - pizzly
    - oncofuse
    - arriba
    hlacaller: optitype
    strandedness: firststrand
    variantcaller:
    - gatk-haplotype
  analysis: RNA-seq
  description: K0008-AF1-RNAseq
  files:
  - /apps2/data/K008-K0011_Target_Discovery/input/RNA/SM8EGVGWJ-23022021_S12_R1_001.fastq.gz
  - /apps2/data/K008-K0011_Target_Discovery/input/RNA/SM8EGVGWJ-23022021_S12_R2_001.fastq.gz
  genome_build: hg38
  metadata:
    batch: K0008-AF1
    phenotype: tumor
    validate_batch: group1
- algorithm:
    aligner: star
    fusion_caller:
    - pizzly
    - oncofuse
    - arriba
    hlacaller: optitype
    strandedness: firststrand
    variantcaller:
    - gatk-haplotype
  analysis: RNA-seq
  description: K0006-AF1-RNAseq
  files:
  - /apps2/data/K008-K0011_Target_Discovery/input/RNA/SQS2JA66K-23022021_S9_R1_001.fastq.gz
  - /apps2/data/K008-K0011_Target_Discovery/input/RNA/SQS2JA66K-23022021_S9_R2_001.fastq.gz
  genome_build: hg38
  metadata:
    batch: K0006-AF1
    phenotype: tumor
    validate_batch: group0
- algorithm:
    aligner: star
    fusion_caller:
    - pizzly
    - oncofuse
    - arriba
    hlacaller: optitype
    strandedness: firststrand
    variantcaller:
    - gatk-haplotype
  analysis: RNA-seq
  description: K0008-AF1-LMDRNAseq
  files:
  - /apps2/data/K008-K0011_Target_Discovery/input/RNA/SSRGQRVBA-23022021_S11_R1_001.fastq.gz
  - /apps2/data/K008-K0011_Target_Discovery/input/RNA/SSRGQRVBA-23022021_S11_R2_001.fastq.gz
  genome_build: hg38
  metadata:
    batch: K0008-AF1-LMD
    phenotype: tumor
    validate_batch: group1
- algorithm:
    aligner: star
    fusion_caller:
    - pizzly
    - oncofuse
    - arriba
    hlacaller: optitype
    strandedness: firststrand
    variantcaller:
    - gatk-haplotype
  analysis: RNA-seq
  description: K0010-AF1-RNAseq
  files:
  - /apps2/data/K008-K0011_Target_Discovery/input/RNA/SSRIVPS0A-23022021_S14_R1_001.fastq.gz
  - /apps2/data/K008-K0011_Target_Discovery/input/RNA/SSRIVPS0A-23022021_S14_R2_001.fastq.gz
  genome_build: hg38
  metadata:
    batch: K0010-AF1
    phenotype: tumor
    validate_batch: group3
fc_name: K0008-K0011_RNA
upload:
  dir: ../final
```

**Observed behavior**
Error message or bcbio output:
```
Traceback (most recent call last):
  File "/apps1/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/apps1/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command '/apps1/local/share/bcbio/anaconda/envs/r36/bin/Rscript --vanilla -e library(tidyverse);salmon_files = list.files("/apps2/data/K008-K0011_Target_Discovery/K0008-K0011_RNA_updated/work/salmon", pattern="quant.sf", recursive=TRUE, full.names=TRUE);tx2gene = readr::read_csv("/apps2/data/K008-K0011_Target_Discovery/K0008-K0011_RNA_updated/work/inputs/transcriptome/tx2gene.csv", col_names=c("transcript", "gene")); samples = basename(dirname(salmon_files));names(salmon_files) = samples;txi = tximport::tximport(salmon_files, type="salmon", tx2gene=tx2gene, countsFromAbundance="lengthScaledTPM", dropInfReps=TRUE);readr::write_csv(round(txi$counts) %>% as.data.frame() %>% tibble::rownames_to_column("gene"), "/apps2/data/K008-K0011_Target_Discovery/K0008-K0011_RNA_updated/work/bcbiotx/tmpyh6_tqvc/tximport-counts.csv");readr::write_csv(txi$abundance %>% as.data.frame() %>% tibble::rownames_to_column("gene"), "/apps2/data/K008-K0011_Target_Discovery/K0008-K0011_RNA_updated/work/bcbiotx/tmp9mjt2ip1/tximport-tpm.csv");
Error in library(tidyverse) : there is no package called ‘tidyverse’
Execution halted
' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/apps1/local/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/apps1/local/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/apps1/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/apps1/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/apps1/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 264, in rnaseqpipeline
    samples = rnaseq.combine_files(samples)
  File "/apps1/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/rnaseq.py", line 489, in combine_files
    tximport = load_tximport(data)
  File "/apps1/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/rnaseq.py", line 556, in load_tximport
    do.run([rcmd, "--vanilla", "-e", render_string], f"Loading tximport.")
  File "/apps1/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/apps1/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command '/apps1/local/share/bcbio/anaconda/envs/r36/bin/Rscript --vanilla -e library(tidyverse);salmon_files = list.files("/apps2/data/K008-K0011_Target_Discovery/K0008-K0011_RNA_updated/work/salmon", pattern="quant.sf", recursive=TRUE, full.names=TRUE);tx2gene = readr::read_csv("/apps2/data/K008-K0011_Target_Discovery/K0008-K0011_RNA_updated/work/inputs/transcriptome/tx2gene.csv", col_names=c("transcript", "gene")); samples = basename(dirname(salmon_files));names(salmon_files) = samples;txi = tximport::tximport(salmon_files, type="salmon", tx2gene=tx2gene, countsFromAbundance="lengthScaledTPM", dropInfReps=TRUE);readr::write_csv(round(txi$counts) %>% as.data.frame() %>% tibble::rownames_to_column("gene"), "/apps2/data/K008-K0011_Target_Discovery/K0008-K0011_RNA_updated/work/bcbiotx/tmpyh6_tqvc/tximport-counts.csv");readr::write_csv(txi$abundance %>% as.data.frame() %>% tibble::rownames_to_column("gene"), "/apps2/data/K008-K0011_Target_Discovery/K0008-K0011_RNA_updated/work/bcbiotx/tmp9mjt2ip1/tximport-tpm.csv");
Error in library(tidyverse) : there is no package called ‘tidyverse’
Execution halted
' returned non-zero exit status 1.

```

**Expected behavior**

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.
[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/6104625/bcbio-nextgen.log)
[bcbio-nextgen-debug.log](https://github.com/bcbio/bcbio-nextgen/files/6104626/bcbio-nextgen-debug.log)
[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/6104627/bcbio-nextgen-commands.log)

**Additional context**
bulkRNA-seq pipeline failed with error in 'library(tidyverse)'. I tried to install tidyverse with conda forge or install.packages("tidyverse"). It seemed to install tidyverse successfully (See below):
```
trying URL 'https://ftp.osuosl.org/pub/cran/src/contrib/tidyverse_1.3.0.tar.gz'
Content type 'application/x-gzip' length 712837 bytes (696 KB)
==================================================
downloaded 696 KB

 

* installing *source* package ‘tidyverse’ ...
** package ‘tidyverse’ successfully unpacked and MD5 sums checked
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (tidyverse)

 

The downloaded source packages are in
        ‘/tmp/RtmpG0JxxC/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
```
But, I can't load tidyverse package even after successful installation of tidyverse. 
```
library(tidyverse)
Error: package or namespace load failed for ‘tidyverse’:
.onAttach failed in attachNamespace() for 'tidyverse', details:
call: clienv$num_colors[[std]]
error: subscript out of bounds
```

Could you tell me how to fix this issue? How can I install and load tidyverse? Thank you.

**Comment by naumenko-sa** [comment]
Hi @tykim0109 !

Thanks for reporting and sorry about the issues.
We install tidyverse via conda:
https://github.com/chapmanb/cloudbiolinux/blob/master/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml#L274

Is there any chance that you have upgraded from the old version but you have not upgraded tools?
```bcbio_nextgen.py upgrade -u skip --tools``

Or directly in conda (install in r36 environment, not in base)
```
conda install -n r36 -c conda-forge r-tidyverse
```

It is better to upgrade tools since there could be other packages missing.

Sergey

**Comment by tykim0109** [comment]
@naumenko-sa 
After upgrading tools.
Below is the R packages installed in r36 environment. I don't find anything wrong. tidyverse and dplyr look all ok.
I'd appreciate if you tell me what else I need to do. Thank you so much.


```
ubuntu@ip-172-***$ conda activate r36
ubuntu@ip-172-***$ R

R version 3.5.1 (2018-07-02) -- "Feather Spray"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-conda_cos6-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> library(tidyverse)
Error: package or namespace load failed for ‘tidyverse’:
 .onAttach failed in attachNamespace() for 'tidyverse', details:
  call: clienv$num_colors[[std]]
  error: subscript out of bounds
> print(paste("R", getRversion()))
[1] "R 3.5.1"
> print("-------------")
[1] "-------------"
> for (package_name in sort(loadedNamespaces())) {
+     print(paste(package_name, packageVersion(package_name)))
+ }
[1] "assertthat 0.2.1"
[1] "backports 1.1.6"
[1] "base 3.5.1"
[1] "broom 0.5.6"
[1] "cellranger 1.1.0"
[1] "colorspace 1.4.1"
[1] "compiler 3.5.1"
[1] "crayon 1.4.0"
[1] "datasets 3.5.1"
[1] "DBI 1.1.1"
[1] "dbplyr 1.4.3"
[1] "dplyr 1.0.5"
[1] "ellipsis 0.3.1"
[1] "forcats 0.5.1"
[1] "fs 1.4.1"
[1] "generics 0.1.0"
[1] "ggplot2 3.3.3"
[1] "glue 1.4.0"
[1] "graphics 3.5.1"
[1] "grDevices 3.5.1"
[1] "grid 3.5.1"
[1] "gtable 0.3.0"
[1] "haven 2.2.0"
[1] "hms 1.0.0"
[1] "httr 1.4.2"
[1] "jsonlite 1.7.2"
[1] "lattice 0.20.41"
[1] "lifecycle 1.0.0"
[1] "lubridate 1.7.8"
[1] "magrittr 1.5"
[1] "methods 3.5.1"
[1] "modelr 0.1.8"
[1] "munsell 0.5.0"
[1] "nlme 3.1.147"
[1] "pillar 1.4.7"
[1] "pkgconfig 2.0.3"
[1] "purrr 0.3.4"
[1] "R6 2.5.0"
[1] "Rcpp 1.0.4.6"
[1] "readr 1.3.1"
[1] "readxl 1.3.1"
[1] "reprex 1.0.0"
[1] "rlang 0.4.10"
[1] "rstudioapi 0.13"
[1] "rvest 0.3.6"
[1] "scales 1.1.1"
[1] "stats 3.5.1"
[1] "stringi 1.5.3"
[1] "stringr 1.4.0"
[1] "tibble 3.0.1"
[1] "tidyr 1.0.2"
[1] "tidyselect 1.1.0"
[1] "tidyverse 1.3.0"
[1] "tools 3.5.1"
[1] "utils 3.5.1"
[1] "vctrs 0.3.6"
[1] "xml2 1.3.2"
```

**Comment by naumenko-sa** [comment]
There is some installation issue in r36 environment, 
the purpose of having that environment is to have R>3.5.1 for PureCN and bcbio2se,

For example, in the bcbio installation available to me:

```
$ conda activate r36
(r36) $ which R
/n/app/bcbio/dev/anaconda/envs/r36/bin/R
(r36) $ R

R version **4.0.3** (2020-10-10) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-conda-linux-gnu (64-bit)
```

Also:
```
$ conda list -n r36 r-base
r-base                    4.0.3                hfb3ec26_0    conda-forge
r-base64enc               0.1_3           r40hcdcec82_1004    conda-forge
$ conda list -n r36 r-tidyverse
r-tidyverse               1.3.0             r40h6115d3f_2    conda-forge
$ conda list -n r36 python
python                    3.7.8           h6f2ec95_0_cpython    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
```

I think you may either try re-installing bcbio (you could keep and reuse genomes),
or to 1) delete r36 environment with conda; 2) create r36 conda environment with python=3.7.8
and r packages listed here for r36:
https://github.com/chapmanb/cloudbiolinux/blob/master/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml

Sergey

**Comment by tykim0109** [comment]
Thank you  Sergey @naumenko-sa 
I re-installed bcbio (reuse genomes) and now it's working fine. Thank you for your help.
