### ISSUE TITLE
mosdepth issue

### ISSUE THREAD

**Issue by DiyaVaka** [bcbio/bcbio-nextgen#3450]
Hi,

I am doing a T/N analysis and this is the error message i see. mosdepth is in my path but stll the script is not finding it

echo $PATH
/data/bcbio/:/data/tools/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/ec2-user/.local/bin:/home/ec2-user/bin

Running bcbio version: 1.2.7
global config: /data/bcbio_system.yaml
run info config: /data/sample.yaml
[2021-03-23T00:22Z] System YAML configuration: /data/galaxy/bcbio_system.yaml.
[2021-03-23T00:22Z] Locale set to C.utf8.
[2021-03-23T00:22Z] Resource requests: bwa, sambamba, samtools; memory: 4.00, 4.00, 4.00; cores: 16, 16, 16
[2021-03-23T00:22Z] Configuring 1 jobs to run, using 1 cores each with 4.00g of memory reserved for each job
[2021-03-23T00:22Z] Timing: organize samples
[2021-03-23T00:22Z] multiprocessing: organize_samples
[2021-03-23T00:22Z] Using input YAML configuration: /data/sample.yaml
[2021-03-23T00:22Z] Checking sample YAML configuration: /data/sample.yaml
[2021-03-23T00:22Z] Retreiving program versions from /data/manifest/python-packages.yaml.
[2021-03-23T00:22Z] Retreiving program versions from /data/manifest/r-packages.yaml.
[2021-03-23T00:22Z] Testing minimum versions of installed programs
[2021-03-23T00:22Z] Timing: alignment preparation
[2021-03-23T00:22Z] multiprocessing: prep_align_inputs
[2021-03-23T00:22Z] Skipping trimming of Liv-normal.
[2021-03-23T00:22Z] Resource requests: ; memory: 1.00; cores: 1
[2021-03-23T00:22Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2021-03-23T00:22Z] Skipping trimming of Sarc-32.
[2021-03-23T00:22Z] Resource requests: ; memory: 1.00; cores: 1
[2021-03-23T00:22Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
[2021-03-23T00:22Z] multiprocessing: disambiguate_split
[2021-03-23T00:22Z] Timing: alignment
[2021-03-23T00:22Z] multiprocessing: process_alignment
[2021-03-23T00:22Z] multiprocessing: delayed_bam_merge
[2021-03-23T00:22Z] Timing: callable regions
[2021-03-23T00:22Z] multiprocessing: prep_samples
[2021-03-23T00:22Z] multiprocessing: postprocess_alignment
Traceback (most recent call last):
  File "/data/tools/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/data/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 138, in variant2pipeline
    samples = run_parallel("postprocess_alignment", samples)
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/data/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1041, in __call__
    if self.dispatch_one_batch(iterator):
  File "/data/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 859, in dispatch_one_batch
    self._dispatch(tasks)
  File "/data/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 777, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/data/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/data/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/data/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/data/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 59, in wrapper
    return f(*args, **kwargs)
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 157, in postprocess_alignment
    return sample.postprocess_alignment(*args)
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sample.py", line 281, in postprocess_alignment
    covinfo = callable.sample_callable_bed(bam_file_ready, ref_file, data)
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/bam/callable.py", line 45, in sample_callable_bed
    callable_bed, depth_files = coverage.calculate(bam_file, data, sv_bed)
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/variation/coverage.py", line 101, in calculate
    per_base=per_base)
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/variation/coverage.py", line 243, in run_mosdepth
    mosdepth = config_utils.get_program("mosdepth", data)
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/pipeline/config_utils.py", line 191, in get_program
    return _get_program_cmd(name, pconfig, config, default)
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/pipeline/config_utils.py", line 217, in wrap
    raise CmdNotFound(" ".join(map(repr, (fn.__name__ if six.PY3 else fn.func_name, name, pconfig, default))))
bcbio.pipeline.config_utils.CmdNotFound: '_get_program_cmd' 'mosdepth' {} None

**Comment by naumenko-sa** [comment]
Hi @DiyaVaka !

Thanks for the report and sorry about the issues!

Could you please check if mosdepth is installed?

```bash
$ which mosdepth
/n/app/bcbio/tools/bin/mosdepth
$ conda list -n htslib1.10 mosdepth
# packages in environment at /n/app/bcbio/dev/anaconda/envs/htslib1.10:
#
# Name                    Version                   Build  Channel
mosdepth                  0.2.9                hbeb723e_1    bioconda
$ mosdepth --version
mosdepth 0.2.9
```

If mosdepth is absent, please try to update tools

```bash
bcbio_nextgen.py upgrade -u skip --tools
```

Sergey

**Comment by DiyaVaka** [comment]
Thank you.
