### ISSUE TITLE
FreeBayes germline variant calling error

### ISSUE THREAD

**Issue by pengxiao78** [bcbio/bcbio-nextgen#3451]
Hi,

I found the error during FreeBayes germline variant calling. I'm using bcbio 1.2.4 and the yaml template file as follows,

```yaml
details:
   - analysis: variant2 
     genome_build: Sscrofa11.1 
     algorithm: 
       aligner: bwa 
       align_split_size: 5000000 
       mark_duplicates: true
       indelcaller: false
       nomap_split_targets: 100
       platform: illumina
       quality_format: standard
       realign: false 
       recalibrate: true
       remove_lcr: true
       variantcaller: [freebayes, gatk-haplotype, samtools]
       ensemble: 
         numpass: 2
```

Could you help me with solving the error as follows? Thanks!

```
[2021-03-04T20:42Z] ica3: Genotyping with FreeBayes
[2021-03-04T20:42Z] ica2: Genotyping with FreeBayes
[2021-03-04T20:42Z] ica1: Genotyping with FreeBayes
[2021-03-04T23:32Z] ica3: /usr/bin/bash: line 1: 50859 Killed                  /parallel/bcbio/anaconda/bin/freebayes -f /parallel/bcbio/genomes/Sscrofa/Sscrofa11.1/seq/Sscrofa11.1.fa --genotype-qualities --strict-vcf --ploidy 2 --targets /user_pig_DNAseq/02-2021_full_data/trimmed/work/freebayes/2/61-2_0_25019774-regions.bed --min-repeat-entropy 1 --no-partial-observations -b /user_pig_DNAseq/02-2021_full_data/trimmed/work/align/Sample61/Sample61-sort.bam
[2021-03-04T23:32Z] ica3: Uncaught exception occurred
Traceback (most recent call last):
  File "/parallel/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/parallel/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /parallel/bcbio/anaconda/bin/freebayes -f /parallel/bcbio/genomes/Sscrofa/Sscrofa11.1/seq/Sscrofa11.1.fa --genotype-qualities --strict-vcf --ploidy 2 --targets /user_pig_DNAseq/02-2021_full_data/trimmed/work/freebayes/2/61-2_0_25019774-regions.bed --min-repeat-entropy 1 --no-partial-observations -b /user_pig_DNAseq/02-2021_full_data/trimmed/work/align/Sample61/Sample61-sort.bam | bcftools filter -i 'ALT="<*>" || QUAL > 5' | awk -F$'\t' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDXkmryswbvhdx]/, "N", $4) } {print}' | bcftools view  -a - | /parallel/bcbio/anaconda/bin/py -x 'bcbio.variation.freebayes.remove_missingalt(x)' | vcfallelicprimitives -t DECOMPOSED --keep-geno | vcffixup - | vcfstreamsort | vt normalize -n -r /parallel/bcbio/genomes/Sscrofa/Sscrofa11.1/seq/Sscrofa11.1.fa -q - | vcfuniqalleles | vt uniq - 2> /dev/null | bgzip -c > /user_pig_DNAseq/02-2021_full_data/trimmed/work/bcbiotx/tmpc085x7gv/61-2_0_25019774.vcf.gz
/usr/bin/bash: line 1: 50859 Killed                  /parallel/bcbio/anaconda/bin/freebayes -f /parallel/bcbio/genomes/Sscrofa/Sscrofa11.1/seq/Sscrofa11.1.fa --genotype-qualities --strict-vcf --ploidy 2 --targets /user_pig_DNAseq/02-2021_full_data/trimmed/work/freebayes/2/61-2_0_25019774-regions.bed --min-repeat-entropy 1 --no-partial-observations -b /user_pig_DNAseq/02-2021_full_data/trimmed/work/align/Sample61/Sample61-sort.bam
     50860 Done                    | bcftools filter -i 'ALT="<*>" || QUAL > 5'
     50861 Done                    | awk -F'	' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDXkmryswbvhdx]/, "N", $4) } {print}'
     50862 Done                    | bcftools view -a -
     50863 Done                    | /parallel/bcbio/anaconda/bin/py -x 'bcbio.variation.freebayes.remove_missingalt(x)'
     50864 Done                    | vcfallelicprimitives -t DECOMPOSED --keep-geno
     50865 Done                    | vcffixup -
     50866 Done                    | vcfstreamsort
     50867 Done                    | vt normalize -n -r /parallel/bcbio/genomes/Sscrofa/Sscrofa11.1/seq/Sscrofa11.1.fa -q -
     50868 Done                    | vcfuniqalleles
     50869 Done                    | vt uniq - 2> /dev/null
     50870 Done                    | bgzip -c > /user_pig_DNAseq/02-2021_full_data/trimmed/work/bcbiotx/tmpc085x7gv/61-2_0_25019774.vcf.gz
' returned non-zero exit status 137.
[2021-03-04T23:32Z] ica3: Unexpected error
Traceback (most recent call last):
  File "/parallel/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 54, in _setup_logging
    yield config
  File "/parallel/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 445, in variantcall_sample
    return ipython.zip_args(apply(genotype.variantcall_sample, *args))
  File "/parallel/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 82, in apply
    return object(*args, **kwargs)
  File "/parallel/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/genotype.py", line 377, in variantcall_sample
    out_file = caller_fn(align_bams, items, ref_file, assoc_files, region, out_file)
  File "/parallel/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/freebayes.py", line 98, in run_freebayes
    assoc_files, region, out_file)
  File "/parallel/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/freebayes.py", line 143, in _run_freebayes_caller
    do.run(cmd.format(**locals()), "Genotyping with FreeBayes", {})
  File "/parallel/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/parallel/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /parallel/bcbio/anaconda/bin/freebayes -f /parallel/bcbio/genomes/Sscrofa/Sscrofa11.1/seq/Sscrofa11.1.fa --genotype-qualities --strict-vcf --ploidy 2 --targets /user_pig_DNAseq/02-2021_full_data/trimmed/work/freebayes/2/61-2_0_25019774-regions.bed --min-repeat-entropy 1 --no-partial-observations -b /user_pig_DNAseq/02-2021_full_data/trimmed/work/align/Sample61/Sample61-sort.bam | bcftools filter -i 'ALT="<*>" || QUAL > 5' | awk -F$'\t' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDXkmryswbvhdx]/, "N", $4) } {print}' | bcftools view  -a - | /parallel/bcbio/anaconda/bin/py -x 'bcbio.variation.freebayes.remove_missingalt(x)' | vcfallelicprimitives -t DECOMPOSED --keep-geno | vcffixup - | vcfstreamsort | vt normalize -n -r /parallel/bcbio/genomes/Sscrofa/Sscrofa11.1/seq/Sscrofa11.1.fa -q - | vcfuniqalleles | vt uniq - 2> /dev/null | bgzip -c > /user_pig_DNAseq/02-2021_full_data/trimmed/work/bcbiotx/tmpc085x7gv/61-2_0_25019774.vcf.gz
/usr/bin/bash: line 1: 50859 Killed                  /parallel/bcbio/anaconda/bin/freebayes -f /parallel/bcbio/genomes/Sscrofa/Sscrofa11.1/seq/Sscrofa11.1.fa --genotype-qualities --strict-vcf --ploidy 2 --targets /user_pig_DNAseq/02-2021_full_data/trimmed/work/freebayes/2/61-2_0_25019774-regions.bed --min-repeat-entropy 1 --no-partial-observations -b /user_pig_DNAseq/02-2021_full_data/trimmed/work/align/Sample61/Sample61-sort.bam
     50860 Done                    | bcftools filter -i 'ALT="<*>" || QUAL > 5'
     50861 Done                    | awk -F'	' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDXkmryswbvhdx]/, "N", $4) } {print}'
     50862 Done                    | bcftools view -a -
     50863 Done                    | /parallel/bcbio/anaconda/bin/py -x 'bcbio.variation.freebayes.remove_missingalt(x)'
     50864 Done                    | vcfallelicprimitives -t DECOMPOSED --keep-geno
     50865 Done                    | vcffixup -
     50866 Done                    | vcfstreamsort
     50867 Done                    | vt normalize -n -r /parallel/bcbio/genomes/Sscrofa/Sscrofa11.1/seq/Sscrofa11.1.fa -q -
     50868 Done                    | vcfuniqalleles
     50869 Done                    | vt uniq - 2> /dev/null
     50870 Done                    | bgzip -c > /user_pig_DNAseq/02-2021_full_data/trimmed/work/bcbiotx/tmpc085x7gv/61-2_0_25019774.vcf.gz
' returned non-zero exit status 137.
```

**Comment by naumenko-sa** [comment]
Hi @pengxiao78!

Thanks for reporting and sorry about the issues!

The command that fails:

```bash
/parallel/bcbio/anaconda/bin/freebayes \
-f /parallel/bcbio/genomes/Sscrofa/Sscrofa11.1/seq/Sscrofa11.1.fa \
--genotype-qualities \
--strict-vcf \
--ploidy 2 \
--targets /user_pig_DNAseq/02-2021_full_data/trimmed/work/freebayes/2/61-2_0_25019774-regions.bed \
--min-repeat-entropy 1 \
--no-partial-observations \
-b /user_pig_DNAseq/02-2021_full_data/trimmed/work/align/Sample61/Sample61-sort.bam
```

Could you please check the input bam? Sample61-sort.bam?
What happens if you run this command outside of bcbio? Would you get variants, or an empty vcf file?

Sergey

**Comment by pengxiao78** [comment]
Hi @naumenko-sa
I ran the command outside of bcbio. Yes, I could get many variants.

**Comment by naumenko-sa** [comment]
ok, great!
What about the full command then? Could you try to identify where exactly it breaks down the pipe?

```
subprocess.CalledProcessError: Command 'set -o pipefail; /parallel/bcbio/anaconda/bin/freebayes -f /parallel/bcbio/genomes/Sscrofa/Sscrofa11.1/seq/Sscrofa11.1.fa --genotype-qualities --strict-vcf --ploidy 2 --targets /user_pig_DNAseq/02-2021_full_data/trimmed/work/freebayes/2/61-2_0_25019774-regions.bed --min-repeat-entropy 1 --no-partial-observations -b /user_pig_DNAseq/02-2021_full_data/trimmed/work/align/Sample61/Sample61-sort.bam | bcftools filter -i 'ALT="<*>" || QUAL > 5' | awk -F$'\t' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDXkmryswbvhdx]/, "N", $4) } {print}' | bcftools view  -a - | /parallel/bcbio/anaconda/bin/py -x 'bcbio.variation.freebayes.remove_missingalt(x)' | vcfallelicprimitives -t DECOMPOSED --keep-geno | vcffixup - | vcfstreamsort | vt normalize -n -r /parallel/bcbio/genomes/Sscrofa/Sscrofa11.1/seq/Sscrofa11.1.fa -q - | vcfuniqalleles | vt uniq - 2> /dev/null | bgzip -c > /user_pig_DNAseq/02-2021_full_data/trimmed/work/bcbiotx/tmpc085x7gv/61-2_0_25019774.vcf.gz
```

**Comment by pengxiao78** [comment]
@naumenko-sa
Firstly, when I ran the command, it gave me error that one directory is not exist. Then I found that the temp folder tmpc085x7gv was missing in the directory in the command../work/bcbiotx/tmpc085x7gv. So I created this folder under bcbiotx and re-ran the command successfully. The 234kb file 61-2_0_25019774.vcf.gz was successfully generated.

**Comment by pengxiao78** [comment]
@naumenko-sa
Could you respond to my above reply? Why the temp folder was missing? How could bcbio not break when run the pipeline automatically? Thansk!

**Comment by naumenko-sa** [comment]
tmp dirs are being created and deleted on the fly as part of file transaction:
https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/variation/freebayes.py#L115

That is good news - since the command is not breaking, try to increase the amount of RAM you give to bcbio/freebayes.

**Comment by pengxiao78** [comment]
More details on how to increase the RAM to bcbio/freebayes?

**Comment by naumenko-sa** [comment]
freebayes is not a java tool, it does not have resources/java/mem yaml setting,
if you are running a single node job on HPC, i.e. `bcbio_nextgen.py ../config/project.yaml -n 16`,
you may try:
- decreasing the number of threads say to 5 < 16 and leave the memory setting in the job script the same;
see an example for slurm scheduler: https://bcbio-nextgen.readthedocs.io/en/latest/contents/single_cell.html#create-a-batch-script
bcbio runs many freebayes instances in parallel, in that case 16, each is calling variants in a small portion of the alignment
- increasing mem in the job script, while leaving threads the same;
- increasing mem and decreasing threads;

If you are running an ipython bcbio job, the settings for engine jobs are determined by 
`bcbio/galaxy/bcbio_system.yaml` . The default is 4G/core and 16 cores. You may adjust them or override in the project.yaml.

**Comment by pengxiao78** [comment]
Thank you! Yes, when I increased the bcbio_system.yaml  default mem into 128G/core. The pipeline eventually finished and generated results in final folder!
