### ISSUE TITLE
Workflow1 - T/N error: filesystem error: cannot set permissions: Operation not permitted [/]

### ISSUE THREAD

**Issue by chatchawit** [bcbio/bcbio-nextgen#3452]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.7
- OS name and version (`lsb_release -ds`): Ubuntu 20.04.1 LTS

**To Reproduce**
Exact bcbio command you have used:
```
mkdir -p cancer-dream-syn3/config cancer-dream-syn3/input cancer-dream-syn3/work
cd cancer-dream-syn3/config
wget https://raw.githubusercontent.com/bcbio/bcbio-nextgen/master/config/examples/cancer-dream-syn3.yaml
cd ../input
wget https://raw.githubusercontent.com/bcbio/bcbio-nextgen/master/config/examples/cancer-dream-syn3-getdata.sh
bash cancer-dream-syn3-getdata.sh
cd ../work
nohup bcbio_nextgen.py ../config/cancer-dream-syn3.yaml -n 8 2>&1 > log.txt &
```
Your sample configuration file:
```yaml
# Cancer tumor/normal calling evaluation using synthetic dataset 3
# from the ICGC-TCGA DREAM challenge:
# https://www.synapse.org/#!Synapse:syn312572/wiki/62018
---
details:
- algorithm:
    aligner: bwa
    mark_duplicates: true
    remove_lcr: true
    variantcaller: [mutect2, vardict]
    variant_regions: ../input/NGv3.bed
    # svcaller: [cnvkit, lumpy, delly]
    # coverage_interval: amplicon
  analysis: variant2
  description: syn3-normal
  #files: ../input/synthetic.challenge.set3.normal.bam
  files:
    - /san/test/cancer-dream-syn3/input/synthetic_challenge_set3_normal_NGv3_1.fq.gz
    - /san/test/cancer-dream-syn3/input/synthetic_challenge_set3_normal_NGv3_2.fq.gz
  genome_build: hg38
  metadata:
    batch: syn3
    phenotype: normal
- algorithm:
    aligner: bwa
    mark_duplicates: true
    remove_lcr: true
    variantcaller: [mutect2, vardict]
    variant_regions: /san/test/cancer-dream-syn3/input/NGv3.bed
    validate: /san/test/cancer-dream-syn3/input/synthetic_challenge_set3_tumor_20pctmasked_truth.vcf.gz
    validate_regions: /san/test/cancer-dream-syn3/input/synthetic_challenge_set3_tumor_20pctmasked_truth_regions.bed
    # svcaller: [cnvkit, lumpy, delly]
    # coverage_interval: amplicon
  #   svvalidate:
  #     DEL: ../input/synthetic_challenge_set3_tumor_20pctmasked_truth_sv_DEL.bed
  #     DUP: ../input/synthetic_challenge_set3_tumor_20pctmasked_truth_sv_DUP.bed
  #     INS: ../input/synthetic_challenge_set3_tumor_20pctmasked_truth_sv_INS.bed
  #     INV: ../input/synthetic_challenge_set3_tumor_20pctmasked_truth_sv_INV.bed
  analysis: variant2
  description: syn3-tumor
  #files: ../input/synthetic.challenge.set3.tumor.bam
  files:
    - /san/test/cancer-dream-syn3/input/synthetic_challenge_set3_tumor_NGv3_1.fq.gz
    - /san/test/cancer-dream-syn3/input/synthetic_challenge_set3_tumor_NGv3_2.fq.gz
  genome_build: hg38
  metadata:
    batch: syn3
    phenotype: tumor
fc_date: '2014-08-13'
fc_name: dream-syn3
upload:
  dir: /san/test/cancer-dream-syn3/final
```

**Observed behavior**
Error message or bcbio output:
```
[2021-03-24T17:20Z] System YAML configuration: /san/bcbio/galaxy/bcbio_system.yaml.
[2021-03-24T17:20Z] Locale set to C.UTF-8.
[2021-03-24T17:20Z] Resource requests: bwa, sambamba, samtools; memory: 4.00, 4.00, 4.00; cores: 16, 16, 16
[2021-03-24T17:20Z] Configuring 1 jobs to run, using 8 cores each with 32.1g of memory reserved for each job
[2021-03-24T17:20Z] Timing: organize samples
[2021-03-24T17:20Z] multiprocessing: organize_samples
[2021-03-24T17:20Z] Using input YAML configuration: /san/test/cancer-dream-syn3/config/cancer-dream-syn3.yaml
[2021-03-24T17:20Z] Checking sample YAML configuration: /san/test/cancer-dream-syn3/config/cancer-dream-syn3.yaml
[2021-03-24T17:20Z] Retreiving program versions from /san/bcbio/manifest/python-packages.yaml.
[2021-03-24T17:20Z] Retreiving program versions from /san/bcbio/manifest/r-packages.yaml.
[2021-03-24T17:20Z] Testing minimum versions of installed programs
[2021-03-24T17:20Z] Timing: alignment preparation
[2021-03-24T17:20Z] multiprocessing: prep_align_inputs
Running bcbio version: 1.2.7
... ... ...
[2021-03-24T19:09Z] [main] Version: 0.7.17-r1188
[2021-03-24T19:09Z] [main] CMD: /san/bcbio/galaxy/../anaconda/bin/bwa mem -c 250 -M -t 8 -R @RG\tID:syn3-tumor\tPL:illumina\tPU:2_2014-08-13_dream-syn3\tSM:syn3-tumor -v 1 /san/bcbio/genomes/Hsapiens/hg38/bwa/hg38.fa /dev/fd/63 /dev/fd/62
[2021-03-24T19:09Z] [main] Real time: 663.226 sec; CPU: 5256.606 sec
[2021-03-24T19:09Z] [bam_sort_core] merging from 0 files and 8 in-memory blocks...
[2021-03-24T19:10Z] multiprocessing: delayed_bam_merge
[2021-03-24T19:10Z] Ensure integrity of input merge BAM files
[2021-03-24T19:10Z] Ensure integrity of input merge BAM files
[2021-03-24T19:10Z] Ensure integrity of input merge BAM files
[2021-03-24T19:10Z] Merge bam files to syn3-normal-sort.bam
[2021-03-24T19:10Z] filesystem error: cannot set permissions: Operation not permitted [/]
[2021-03-24T19:10Z] filesystem error: cannot set permissions: Operation not permitted [/]
[2021-03-24T19:10Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/san/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/san/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; bamcat level=0 tmpfile=/san/test/cancer-dream-syn3/work/bcbiotx/tmpci_2stx5/bcbiotx/tmp38y65db5/syn3-normal-sort.bam-bammerge `cat /san/test/cancer-dream-syn3/work/bcbiotx/tmpci_2stx5/bcbiotx/tmp38y65db5/syn3-normal-sort.list` | bamsormadup threads=7 tmpfile=/san/test/cancer-dream-syn3/work/bcbiotx/tmpci_2stx5/bcbiotx/tmp38y65db5/syn3-normal-sort.bam-bamsormaduptmp indexfilename=/san/test/cancer-dream-syn3/work/bcbiotx/tmpci_2stx5/bcbiotx/tmp38y65db5/syn3-normal-sort.bam.bai > /san/test/cancer-dream-syn3/work/bcbiotx/tmpci_2stx5/bcbiotx/tmp38y65db5/syn3-normal-sort.bam
filesystem error: cannot set permissions: Operation not permitted [/]
filesystem error: cannot set permissions: Operation not permitted [/]
' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/san/bcbio/tools/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/san/bcbio/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/san/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/san/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/san/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 135, in variant2pipeline
    samples = alignprep.merge_split_alignments(samples, run_parallel)
  File "/san/bcbio/anaconda/lib/python3.6/site-packages/bcbio/ngsalign/alignprep.py", line 236, in merge_split_alignments
    merged = run_parallel("delayed_bam_merge", ready_merge)
  File "/san/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/san/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/san/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1041, in __call__
    if self.dispatch_one_batch(iterator):
  File "/san/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 859, in dispatch_one_batch
    self._dispatch(tasks)
  File "/san/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 777, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/san/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/san/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/san/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/san/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/san/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 59, in wrapper
    return f(*args, **kwargs)
  File "/san/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 223, in delayed_bam_merge
    return sample.delayed_bam_merge(*args)
  File "/san/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sample.py", line 347, in delayed_bam_merge
    out_file=cur_out_file)
  File "/san/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/merge.py", line 72, in merge_bam_files
    None)
  File "/san/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/san/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; bamcat level=0 tmpfile=/san/test/cancer-dream-syn3/work/bcbiotx/tmpci_2stx5/bcbiotx/tmp38y65db5/syn3-normal-sort.bam-bammerge `cat /san/test/cancer-dream-syn3/work/bcbiotx/tmpci_2stx5/bcbiotx/tmp38y65db5/syn3-normal-sort.list` | bamsormadup threads=7 tmpfile=/san/test/cancer-dream-syn3/work/bcbiotx/tmpci_2stx5/bcbiotx/tmp38y65db5/syn3-normal-sort.bam-bamsormaduptmp indexfilename=/san/test/cancer-dream-syn3/work/bcbiotx/tmpci_2stx5/bcbiotx/tmp38y65db5/syn3-normal-sort.bam.bai > /san/test/cancer-dream-syn3/work/bcbiotx/tmpci_2stx5/bcbiotx/tmp38y65db5/syn3-normal-sort.bam
filesystem error: cannot set permissions: Operation not permitted [/]
filesystem error: cannot set permissions: Operation not permitted [/]
' returned non-zero exit status 1.
```

**Expected behavior**
I ran the example of Somatic (cancer) variants - Workflow1 - T/N. It should terminate without errors. OS is freshly installed under Xen virtualization. The folder /san is Storage Area Network (SAN). I have successfully run the example of RNA-seq before testing this workflow. I've changed the limit of number of open files as suggested. The /etc/fstab mounts the file system with option "defaults". I ran the script with user account (not root). The owner / group / permission of the folder /san are correct. I'm the owner with permission to read/write/execute.

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.

[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/6202080/bcbio-nextgen.log)
[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/6202081/bcbio-nextgen-commands.log)
[bcbio-nextgen-debug.log](https://github.com/bcbio/bcbio-nextgen/files/6202082/bcbio-nextgen-debug.log)

**Additional context**

**Comment by naumenko-sa** [comment]
Hi @chatchawit !

Thanks for reporting and sorry about the issue!

bulkRNA-seq pipeline could have skipped the bammerge step which breaks here:
https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/pipeline/merge.py#L39

Could you please try to investigate the command/function that fails?
(you will need to dig out or make syn3-normal-sort.list and maybe adjust some file names)

```bash
bamcat level=0 \
tmpfile=/san/test/cancer-dream-syn3/work/bcbiotx/test/syn3-normal-sort.bam-bammerge \
`cat /san/test/cancer-dream-syn3/work/test/syn3-normal-sort.list` | \
bamsormadup threads=7 tmpfile=/san/test/cancer-dream-syn3/work/bcbiotx/test/syn3-normal-sort.bam-bamsormaduptmp indexfilename=/san/test/cancer-dream-syn3/work/bcbiotx/test/syn3-normal-sort.bam.bai > \
/san/test/cancer-dream-syn3/work/bcbiotx/test/syn3-normal-sort.bam
```

It is likely a system-specific issue, since many projects run bam merge every day without issues,
but let us try to investigate! 

Sergey

**Comment by chatchawit** [comment]
@naumenko-sa Thank you Sergey. I have tried to set the tmp folder (/san/tmp). The same error happened again. After the error, the tmp folder is empty (nothing left). So I cannot find "syn3-normal-sort.list". Why did the file disappear?

**Comment by naumenko-sa** [comment]
Hi @chatchawit !

I've just successfully repeated that test workflow. No errors. Sorry, I can't reproduce this issue.
It reminds me of one case when similar random file system errors 
from bcbio were a good predictor of the approaching file system crash. Bcbio is a good stress test of a filesystem, since it randomly creates and accesses a lot of files and directories.

If you still believe that this is a bcbio issue, could you please try to debug it in pdb?

You would need to fork bcbio code, clone the repo, create a branch, insert `pdb.set_trace()` call into the function that crashing
(https://docs.python.org/3/library/pdb.html),
inject bcbio code into your installation (https://bcbio-nextgen.readthedocs.io/en/latest/contents/development.html#injecting-bcbio-code-into-bcbio-installation) and run. When you are inside the function, you may try to investigate the crash in more detail.

Sergey

**Comment by chatchawit** [comment]
I found the step that produced the error. I ran each command step by step.

/san/bcbio/tools/bin/bwa mem -c 250 -M -t 8 \
  -R '@RG\tID:syn3-tumor\tPL:illumina\tPU:2_2014-08-13_dream-syn3\tSM:syn3-tumor' -v 1 \
  /san/bcbio/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa \
  <(grabix grab /san/test/cancer-dream-syn3/input/synthetic_challenge_set3_tumor_NGv3_1.fq.gz 1 195350104) \
  <(grabix grab /san/test/cancer-dream-syn3/input/synthetic_challenge_set3_tumor_NGv3_2.fq.gz 1 195350104) \
  | /san/bcbio/anaconda/bin/samtools sort -n -@ 8 -m 2G -O bam -T /san/tmp/tumor -o /san/test/bwa-mem/tumor.bam -
  
The command "bwa mem" ran successfully, and produced the bam file.
  
  /san/bcbio/tools/bin/bamsormadup threads=8 tmpfile=/san/tmp/tumor \
  indexfilename=/san/test/bwa-mem/tumor-sorted.bam.bai \
  < /san/test/bwa-mem/tumor.bam \
  > /san/test/bwa-mem/tumor-sorted.bam
  
The command "bamsormadup" produced the error below.
  
filesystem error: cannot set permissions: Operation not permitted [/]
filesystem error: cannot set permissions: Operation not permitted [/]

What should I do?

**Comment by naumenko-sa** [comment]
I'm glad that you've identified the step!
Fortunately for bcbio, it does look like a permission issue in your file system.

It looks like bamsormadup can't write to `/san/tmp`. 

Can you try to investigate /san/tmp mount options/permission, or to change bcbio tmp default to /san/test/tmp
https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#temporary-directory.

Sorry, I don't have other suggestions.
