### ISSUE TITLE
freebayes issue

### ISSUE THREAD

**Issue by DiyaVaka** [bcbio/bcbio-nextgen#3453]
Hi,

WHile running freebayes i see the below error message. I am not using any variant_regions file in the sample.yaml file. 

[2021-03-25T05:10Z] ERROR(freebayes): Target region coordinates (chrY 13654851 91744698) outside of reference sequence bounds (chrY 15902555) terminating.
[2021-03-25T05:10Z] Failed to open -: unknown file type
[2021-03-25T05:10Z] Genotyping paired variants with FreeBayes
[2021-03-25T05:10Z] Genotyping paired variants with FreeBayes
[2021-03-25T05:10Z] Genotyping paired variants with FreeBayes
[2021-03-25T05:10Z] Genotyping paired variants with FreeBayes
[2021-03-25T05:10Z] Genotyping paired variants with FreeBayes
[2021-03-25T05:10Z] Genotyping paired variants with FreeBayes
[2021-03-25T05:10Z] Traceback (most recent call last):
[2021-03-25T05:10Z]   File "<string>", line 1, in <module>
[2021-03-25T05:10Z]   File "/data/anaconda/lib/python3.6/site-packages/bcbio/variation/freebayes.py", line 330, in call_somatic
[2021-03-25T05:10Z]     _write_header(header)
[2021-03-25T05:10Z]   File "/data/anaconda/lib/python3.6/site-packages/bcbio/variation/freebayes.py", line 313, in _write_header
[2021-03-25T05:10Z]     for hline in header[:-1] + new_headers + [header[-1]]:
[2021-03-25T05:10Z] IndexError: list index out of range
[2021-03-25T05:10Z] Failed to open -: unknown file type
[2021-03-25T05:10Z] vcffixup: could not open stdin
[2021-03-25T05:10Z] [bcf_ordered_reader.cpp:49 BCFOrderedReader] Not a VCF/BCF file: -
[2021-03-25T05:10Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /data/anaconda/bin/freebayes -f /data/genomes/Mmusculus/mm9/seq/mm9.fa --genotype-qualities --strict-vcf --ploidy 1 --region chrY:13654851..91744698 --min-repeat-entropy 1 --no-partial-observations --min-alternate-fraction 0.1 --pooled-discrete --pooled-continuous --report-genotype-likelihood-max --allele-balance-priors-off /data/align/Sarc-30/Sarc-30-sort.bam /data/align/Liv-normal/Liv-normal-sort.bam | bcftools filter -i 'ALT="<*>" || QUAL > 5' | /data/anaconda/bin/python -c 'from bcbio.variation import freebayes; freebayes.call_somatic("Sarc-30", "Liv-normal")' | awk -F$'\t' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDXkmryswbvhdx]/, "N", $4) } {print}' | bcftools view -s Sarc-30,Liv-normal -a - | /data/anaconda/bin/py -x 'bcbio.variation.freebayes.remove_missingalt(x)' | vcfallelicprimitives -t DECOMPOSED --keep-geno | vcffixup - | vcfstreamsort | vt normalize -n -r /data/genomes/Mmusculus/mm9/seq/mm9.fa -q - | vcfuniqalleles | vt uniq - 2> /dev/null | bgzip -c > /data/bcbiotx/tmpw40nccki/MM02_Liv_vs_Sarc30-chrY_13654851_91744698.vcf.gz

ERROR(freebayes): Target region coordinates (chrY 13654851 91744698) outside of reference sequence bounds (chrY 15902555) terminating.
Failed to open -: unknown file type
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/variation/freebayes.py", line 330, in call_somatic
    _write_header(header)
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/variation/freebayes.py", line 313, in _write_header
    for hline in header[:-1] + new_headers + [header[-1]]:
IndexError: list index out of range
Failed to open -: unknown file type
vcffixup: could not open stdin
[bcf_ordered_reader.cpp:49 BCFOrderedReader] Not a VCF/BCF file: -
' returned non-zero exit status 1.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/data/anaconda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/data/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/data/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/data/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 59, in wrapper
    return f(*args, **kwargs)
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 319, in variantcall_sample
    return genotype.variantcall_sample(*args)
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/variation/genotype.py", line 377, in variantcall_sample
    out_file = caller_fn(align_bams, items, ref_file, assoc_files, region, out_file)
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/variation/freebayes.py", line 94, in run_freebayes
    ref_file, assoc_files, region, out_file)
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/variation/freebayes.py", line 192, in _run_freebayes_paired
    do.run(cl.format(**locals()), "Genotyping paired variants with FreeBayes", {})
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /data/anaconda/bin/freebayes -f /data/genomes/Mmusculus/mm9/seq/mm9.fa --genotype-qualities --strict-vcf --ploidy 1 --region chrY:13654851..91744698 --min-repeat-entropy 1 --no-partial-observations --min-alternate-fraction 0.1 --pooled-discrete --pooled-continuous --report-genotype-likelihood-max --allele-balance-priors-off /data/align/Sarc-30/Sarc-30-sort.bam /data/align/Liv-normal/Liv-normal-sort.bam | bcftools filter -i 'ALT="<*>" || QUAL > 5' | /data/anaconda/bin/python -c 'from bcbio.variation import freebayes; freebayes.call_somatic("Sarc-30", "Liv-normal")' | awk -F$'\t' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDXkmryswbvhdx]/, "N", $4) } {print}' | bcftools view -s Sarc-30,Liv-normal -a - | /data/anaconda/bin/py -x 'bcbio.variation.freebayes.remove_missingalt(x)' | vcfallelicprimitives -t DECOMPOSED --keep-geno | vcffixup - | vcfstreamsort | vt normalize -n -r /data/genomes/Mmusculus/mm9/seq/mm9.fa -q - | vcfuniqalleles | vt uniq - 2> /dev/null | bgzip -c > /data/bcbiotx/tmpw40nccki/MM02_Liv_vs_Sarc30-chrY_13654851_91744698.vcf.gz
ERROR(freebayes): Target region coordinates (chrY 13654851 91744698) outside of reference sequence bounds (chrY 15902555) terminating.
Failed to open -: unknown file type
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/variation/freebayes.py", line 330, in call_somatic
    _write_header(header)
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/variation/freebayes.py", line 313, in _write_header
    for hline in header[:-1] + new_headers + [header[-1]]:
IndexError: list index out of range
Failed to open -: unknown file type
vcffixup: could not open stdin
[bcf_ordered_reader.cpp:49 BCFOrderedReader] Not a VCF/BCF file: -
' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/tools/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/data/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 154, in variant2pipeline
    samples = genotype.parallel_variantcall_region(samples, run_parallel)
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/variation/genotype.py", line 208, in parallel_variantcall_region
    "vrn_file", ["region", "sam_ref", "config"]))
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/distributed/split.py", line 35, in grouped_parallel_split_combine
    final_output = parallel_fn(parallel_name, split_args)
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/data/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/data/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/data/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/data/anaconda/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
subprocess.CalledProcessError: Command 'set -o pipefail; /data/anaconda/bin/freebayes -f /data/genomes/Mmusculus/mm9/seq/mm9.fa --genotype-qualities --strict-vcf --ploidy 1 --region chrY:13654851..91744698 --min-repeat-entropy 1 --no-partial-observations --min-alternate-fraction 0.1 --pooled-discrete --pooled-continuous --report-genotype-likelihood-max --allele-balance-priors-off /data/align/Sarc-30/Sarc-30-sort.bam /data/align/Liv-normal/Liv-normal-sort.bam | bcftools filter -i 'ALT="<*>" || QUAL > 5' | /data/anaconda/bin/python -c 'from bcbio.variation import freebayes; freebayes.call_somatic("Sarc-30", "Liv-normal")' | awk -F$'\t' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDXkmryswbvhdx]/, "N", $4) } {print}' | bcftools view -s Sarc-30,Liv-normal -a - | /data/anaconda/bin/py -x 'bcbio.variation.freebayes.remove_missingalt(x)' | vcfallelicprimitives -t DECOMPOSED --keep-geno | vcffixup - | vcfstreamsort | vt normalize -n -r /data/genomes/Mmusculus/mm9/seq/mm9.fa -q - | vcfuniqalleles | vt uniq - 2> /dev/null | bgzip -c > /data/bcbiotx/tmpw40nccki/MM02_Liv_vs_Sarc30-chrY_13654851_91744698.vcf.gz

**Comment by DiyaVaka** [comment]
update: used mm10.fa to overcome this
