### ISSUE TITLE
could not import: bam_hdr_destroy

### ISSUE THREAD

**Issue by adammaikai** [bcbio/bcbio-nextgen#3484]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.8
- OS name and version (`lsb_release -ds`): Ubuntu 16.04.7 LTS

**To Reproduce**
Exact bcbio command you have used:
```
cd $workspace && bcbio_nextgen.py \
	-w template $template_yaml \
	$metadata \
	$workspace \
	--workdir $workspace
```
Your sample configuration file:
```
# Germline Variant calling
---
details:
- algorithm:
    aligner: bwa
    mark_duplicates: true
    #recalibrate: gatk
    exclude_regions: [altcontigs, highdepth, lcr]
    variantcaller: gatk-haplotype
    tools_on: [gatk4,gvcf]
    svcaller: [cnvkit, delly, lumpy]
    vcfanno: [gemini]
  analysis: variant2
  genome_build: hg38
upload:
  dir: final
```

**Observed behavior**
Error message or bcbio output:
```
Traceback (most recent call last):
  File "/shared/workspace/software/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/shared/workspace/software/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/shared/workspace/software/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/shared/workspace/software/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/shared/workspace/software/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 179, in variant2pipeline
    samples = structural.run(samples, run_parallel, "standard")
  File "/shared/workspace/software/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/__init__.py", line 228, in run
    for xs in to_process.values()))
  File "/shared/workspace/software/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/shared/workspace/software/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/shared/workspace/software/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1042, in __call__
    self.retrieve()
  File "/shared/workspace/software/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 921, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/shared/workspace/software/bcbio/anaconda/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
subprocess.CalledProcessError: Command 'set -o pipefail; duphold --threads 4 --vcf /scratch/germline/RF_0001_S1/bcbiotx/tmpdh35u4a6/RF_0001_S1-call-effects.vcf.gz --bam /scratch/germline/RF_0001_S1/align/RF_0001_S1/RF_0001_S1-sort.bam --fasta /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa -o /scratch/germline/RF_0001_S1/bcbiotx/tmpdh35u4a6/RF_0001_S1-call-effects-duphold.vcf.gz
could not import: bam_hdr_destroy
' returned non-zero exit status 1.
```

**Expected behavior**

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.

**Additional context**
I also tried to run 
```duphold --version```
and get the same exact error:
```could not import: bam_hdr_destroy```
[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/6437247/bcbio-nextgen.log)

[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/6437231/bcbio-nextgen-commands.log)
[bcbio-nextgen-debug.log](https://github.com/bcbio/bcbio-nextgen/files/6437232/bcbio-nextgen-debug.log)

**Comment by naumenko-sa** [comment]
Hi @adammaikai !

Thanks for reporting!

Duphold is a tool which annotated structural variants called by split-read methods with coverage depth:
https://github.com/brentp/duphold

It looks like wasn't properly installed properly in your system.

```bash
$ duphold
  version: 0.2.1
  Usage: duphold [options]
$ conda list duphold
# packages in environment at /n/app/bcbio/dev/anaconda:
#
# Name                    Version                   Build  Channel
duphold                   0.2.1                h516909a_1    bioconda
```

Could you please try to re-install it and report back?
```bash
# make sure you are using bcbio conda
which conda
conda remove duphold
conda install -c bioconda duphold
```

Sergey

**Comment by adammaikai** [comment]
I figured this was the issue so I have had ```conda remove duphold``` running in the background and is now on day 2 of the spinning wheel trying resolve inconsistencies. Hope this resolves soon! Thanks for the help.

**Comment by naumenko-sa** [comment]
try also ```mamba remove duphold```
Not sure why, but sometimes mamba for removal and conda for the installation works better.

**Comment by naumenko-sa** [comment]
It looks like your system is somehow trapped in a non-solvable state. Probably, it is easier to reinstall with --nodata, it takes 2h with conda (default now in the installer).

**Comment by adammaikai** [comment]
thanks for the tips! all working now
