### ISSUE TITLE
unable to run bcbio-nextgen

### ISSUE THREAD

**Issue by iichelhadi** [bcbio/bcbio-nextgen#3490]
Hi all, 
a bit of a beginner here
I have installed bcbio-nextgen using a `conda` environment on a HPC.I am trying to do variant calling for a patient tumor/normal sample but get the following error:

`run info config: /home/svu/phaei/bcbio-nextgen/patient_zero.yaml
Traceback (most recent call last):
  File "/home/svu/phaei/.conda/miniconda/4.9/envs/bcbio/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/home/svu/phaei/.conda/miniconda/4.9/envs/bcbio/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/svu/phaei/.conda/miniconda/4.9/envs/bcbio/lib/python3.8/site-packages/bcbio/pipeline/main.py", line 40, in run_main
    config, config_file = config_utils.load_system_config(config_file, workdir)
  File "/home/svu/phaei/.conda/miniconda/4.9/envs/bcbio/lib/python3.8/site-packages/bcbio/pipeline/config_utils.py", line 68, in load_system_config
    raise ValueError("Could not find input system configuration file %s, "
ValueError: Could not find input system configuration file bcbio_system.yaml, including inside standard directory /home/svu/phaei/.conda/miniconda/4.9/envs/galaxy`

Help would be greatly appreciated.
thank you

**Comment by naumenko-sa** [comment]
Hi @iichelhadi !

So you have installed bcbio-nextgen python package?

It is more than that: https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html

As a result you should get an isolated conda with several enviroments, tools, and data installation.

Sergey

**Comment by iichelhadi** [comment]
> Hi @iichelhadi !
> 
> So you have installed bcbio-nextgen python package?
> 
> It is more than that: https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html
> 
> As a result you should get an isolated conda with several enviroments, tools, and data installation.
> 
> Sergey

Hi Sergey,
I believe the issue is the missing reference data, etc. I tried running this install command after installing bcbio
`bcbio_nextgen.py upgrade -u skip --genomes hg38 --aligners bwa`
But it wouldn't work likely due to lack of admin priveleges but I am not sure.
I installed bcbio-nextgen using the following command in a conda env
`conda install -c bioconda bcbio-nextgen`

I still cannot get it to work.

regards

EL

**Comment by naumenko-sa** [comment]
Hi @iichelhadi ! 

Unfortunately, this is not the way bcbio works. It is not enough to install one package via conda.
You need to run the installer script, etc, as described in the installation guide:
https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html

bcbio is a heavy package ~50G + data with its own conda etc

Sergey

**Comment by iichelhadi** [comment]
> Hi @iichelhadi !
> 
> Unfortunately, this is not the way bcbio works. It is not enough to install one package via conda.
> You need to run the installer script, etc, as described in the installation guide:
> https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html
> 
> bcbio is a heavy package ~50G + data with its own conda etc
> 
> Sergey

Thanks for the reply. I contacted IT to help me install it. Hope that will resolve this issue
