### ISSUE TITLE
Bulk RNA-Seq alignment (Hisat2) problems

### ISSUE THREAD

**Issue by PatrickJReed** [bcbio/bcbio-nextgen#3496]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.8
- OS name and version (`lsb_release -ds`):  Ubuntu 20.04.2 LTS

**To Reproduce**
Exact bcbio command you have used:
```
/home/ubuntu/bcbio/anaconda/bin/bcbio_nextgen.py -w template Mouse_Age_RNA-template.yaml Mouse_Age_RNA.csv *.gz --only-metadata
 nohup /home/ubuntu/bcbio/anaconda/bin/bcbio_nextgen.py ../config/Mouse_Age_RNA.yaml -n 64 &
```
Your sample configuration file:
```
samplename,description,celltype,age
101208,Hepatocyte_7wk_RNA_A2,Hepatocyte,7wk
101209,Hepatocyte_88wk_RNA_B3,Hepatocyte,88wk
101210,Hepatocyte_7wk_RNA_A3,Hepatocyte,7wk
101211,Hepatocyte_7wk_RNA_A4,Hepatocyte,7wk
101212,Hepatocyte_88wk_RNA_B1,Hepatocyte,88wk
101213,Hepatocyte_88wk_RNA_B4,Hepatocyte,88wk
101214,Hepatocyte_7wk_RNA_A1,Hepatocyte,7wk
101215,Hepatocyte_Aged_RNA_C4A8,Hepatocyte,88wk
101216,Hepatocyte_Aged_RNA_C1A5,Hepatocyte,88wk
101217,Cortex_7wk_RNA_C3A3,Cortex,7wk
101218,Cortex_7wk_RNA_C4A4,Cortex,7wk
101219,Hepatocyte_Aged_RNA_C2A6,Hepatocyte,88wk
101220,Cortex_7wk_RNA_C1A1,Cortex,7wk
101221,Hepatocyte_Aged_RNA_C3A7,Hepatocyte,88wk
101222,Cortex_7wk_RNA_C2A2,Cortex,7wk
101223,Cortex_88wk_RNA_B2,Cortex,88wk
101224,Cortex_88wk_RNA_B3,Cortex,88wk
101225,Cortex_88wk_RNA_B1,Cortex,88wk
101226,Cortex_88wk_RNA_B4,Cortex,88wk
101227,Cortex_7wk_RNA_A1,Cortex,7wk
101228,Cortex_7wk_RNA_A4,Cortex,7wk
101229,Cortex_7wk_RNA_A2,Cortex,7wk
101230,Cortex_7wk_RNA_A3,Cortex,7wk

# Template for human RNA-seq using Illumina prepared samples
---
details:
  - analysis: RNA-seq
    genome_build: mm10
    algorithm:
      quality_format: standard
      aligner: hisat2
      strandedness: firststrand
upload:
  dir: ../final
```

**Observed behavior**
Error message or bcbio output:
```
[2021-05-26T15:27Z] Aligning /home/ubuntu/Mouse_Age_RNA/101216_1.fastq.gz and /home/ubuntu/Mouse_Age_RNA/101216_2.fastq.gz with hisat2.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 59, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 128, in process_alignment
    return sample.process_alignment(*args)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sample.py", line 140, in process_alignment
    data = align_to_sort_bam(fastq1, fastq2, aligner, data)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/alignment.py", line 87, in align_to_sort_bam
    names, align_dir, data)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/alignment.py", line 164, in _align_from_fastq
    out = align_fn(fastq1, fastq2, align_ref, names, align_dir, data)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/ngsalign/hisat2.py", line 49, in align
    do.run(cmd.format(**locals()), message)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /home/ubuntu/bcbio/galaxy/../anaconda/bin/hisat2 --new-summary -x /home/ubuntu/bcbio/genomes/Mmusculus/mm10/hisat2/mm10 -p 16 --phred33 --rna-strandness RF --rg-id Hepatocyte_7wk_RNA_A3 --rg PL:illumina --rg PU:Hepatocyte_7wk_RNA_A3 --rg SM:Hepatocyte_7wk_RNA_A3  -1 /home/ubuntu/Mouse_Age_RNA/101210_1.fastq.gz -2 /home/ubuntu/Mouse_Age_RNA/101210_2.fastq.gz --known-splicesite-infile /home/ubuntu/bcbio/genomes/Mmusculus/mm10/rnaseq/ref-transcripts-splicesites.txt --novel-splicesite-outfile /home/ubuntu/Mouse_Age_RNA/Mouse_Age_RNA/work/align/Hepatocyte_7wk_RNA_A3/Hepatocyte_7wk_RNA_A3-novelsplicesites.bed  | /home/ubuntu/bcbio/galaxy/../anaconda/bin/bamsormadup inputformat=sam threads=12 tmpfile=/home/ubuntu/Mouse_Age_RNA/Mouse_Age_RNA/work/bcbiotx/tmp1k20ijfx/Hepatocyte_7wk_RNA_A3-sort-sorttmp-markdup SO=coordinate indexfilename=/home/ubuntu/Mouse_Age_RNA/Mouse_Age_RNA/work/bcbiotx/tmp1k20ijfx/Hepatocyte_7wk_RNA_A3-sort.bam.bai > /home/ubuntu/Mouse_Age_RNA/Mouse_Age_RNA/work/bcbiotx/tmp1k20ijfx/Hepatocyte_7wk_RNA_A3-sort.bam
27	1.90223
28	1.90223
29	1.90223
30	1.90223
31	1.90223
32	1.90223
33	1.90223
34	1.90223
35	1.90223
36	1.90223
37	1.90223
38	1.90223
39	1.90223
40	1.90223
41	1.90223
42	1.90223
43	1.90223
44	1.90223
45	1.90223
46	1.90223
47	1.90223
48	1.90223
49	1.90223
50	1.90223
51	1.90223
52	1.90223
53	1.90223
54	1.90223
55	1.90223
56	1.90223
57	1.90223
58	1.90223
59	1.90223
60	1.90223
61	1.90223
62	1.90223
63	1.90223
64	1.90223
65	1.90223
66	1.90223
67	1.90223
68	1.90223
69	1.90223
70	1.90223
71	1.90223
72	1.90223
73	1.90223
74	1.90223
75	1.90223
76	1.90223
77	1.90223
78	1.90223
79	1.90223
80	1.90223
81	1.90223
82	1.90223
83	1.90223
84	1.90223
85	1.90223
86	1.90223
87	1.90223
88	1.90223
89	1.90223
90	1.90223
91	1.90223
92	1.90223
93	1.90223
94	1.90223
95	1.90223
96	1.90223
97	1.90223
98	1.90223
99	1.90223
100	1.90223
[V] blocks generated in time 01:57:83935999
[V] number of blocks to be merged is 20 using 409 blocks per input with block size 1048576
[V] 1793149 01:90757399
[V] 2685735 02:61484899
[V] 3602726 04:11409800
[V] 4488946 04:46865999
[V] 5370329 04:88492899
[V] 7190328 05:77421000
[V] 8082355 06:45434600
[V] 8973193 06:79850599
[V] 9864694 07:88054200
[V] 10772236 09:57479799
[V] 11683062 10:49722799
[V] 12605211 11:71030799
[V] 14394965 13:71437799
[V] 15292804 14:90830399
[V] 16187451 16:10666799
[V] 17082689 17:41090700
[V] 17980346 18:24061599
[V] 19126533 19:37264800
[V] 20159650 20:65728800
[V] 20159650
[D]	md5	63dd69acf50be8dfb3efc8f06ed7c464
[V] checksum ok
[V] blocks merged in time 28:57649400
[V] run time 02:26:44453799 (146.445 s)	MemUsage(size=9894.82,rss=1153.87,peak=12209.9)
' returned non-zero exit status 134.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/home/ubuntu/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 249, in rnaseqpipeline
    samples = run_parallel("process_alignment", samples)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ubuntu/bcbio/anaconda/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
subprocess.CalledProcessError: Command 'set -o pipefail; /home/ubuntu/bcbio/galaxy/../anaconda/bin/hisat2 --new-summary -x /home/ubuntu/bcbio/genomes/Mmusculus/mm10/hisat2/mm10 -p 16 --phred33 --rna-strandness RF --rg-id Hepatocyte_7wk_RNA_A3 --rg PL:illumina --rg PU:Hepatocyte_7wk_RNA_A3 --rg SM:Hepatocyte_7wk_RNA_A3  -1 /home/ubuntu/Mouse_Age_RNA/101210_1.fastq.gz -2 /home/ubuntu/Mouse_Age_RNA/101210_2.fastq.gz --known-splicesite-infile /home/ubuntu/bcbio/genomes/Mmusculus/mm10/rnaseq/ref-transcripts-splicesites.txt --novel-splicesite-outfile /home/ubuntu/Mouse_Age_RNA/Mouse_Age_RNA/work/align/Hepatocyte_7wk_RNA_A3/Hepatocyte_7wk_RNA_A3-novelsplicesites.bed  | /home/ubuntu/bcbio/galaxy/../anaconda/bin/bamsormadup inputformat=sam threads=12 tmpfile=/home/ubuntu/Mouse_Age_RNA/Mouse_Age_RNA/work/bcbiotx/tmp1k20ijfx/Hepatocyte_7wk_RNA_A3-sort-sorttmp-markdup SO=coordinate indexfilename=/home/ubuntu/Mouse_Age_RNA/Mouse_Age_RNA/work/bcbiotx/tmp1k20ijfx/Hepatocyte_7wk_RNA_A3-sort.bam.bai > /home/ubuntu/Mouse_Age_RNA/Mouse_Age_RNA/work/bcbiotx/tmp1k20ijfx/Hepatocyte_7wk_RNA_A3-sort.bam
27	1.90223
28	1.90223
29	1.90223
30	1.90223
31	1.90223
32	1.90223
33	1.90223
34	1.90223
35	1.90223
36	1.90223
37	1.90223
38	1.90223
39	1.90223
40	1.90223
41	1.90223
42	1.90223
43	1.90223
44	1.90223
45	1.90223
46	1.90223
47	1.90223
48	1.90223
49	1.90223
50	1.90223
51	1.90223
52	1.90223
53	1.90223
54	1.90223
55	1.90223
56	1.90223
57	1.90223
58	1.90223
59	1.90223
60	1.90223
61	1.90223
62	1.90223
63	1.90223
64	1.90223
65	1.90223
66	1.90223
67	1.90223
68	1.90223
69	1.90223
70	1.90223
71	1.90223
72	1.90223
73	1.90223
74	1.90223
75	1.90223
76	1.90223
77	1.90223
78	1.90223
79	1.90223
80	1.90223
81	1.90223
82	1.90223
83	1.90223
84	1.90223
85	1.90223
86	1.90223
87	1.90223
88	1.90223
89	1.90223
90	1.90223
91	1.90223
92	1.90223
93	1.90223
94	1.90223
95	1.90223
96	1.90223
97	1.90223
98	1.90223
99	1.90223
100	1.90223
[V] blocks generated in time 01:57:83935999
[V] number of blocks to be merged is 20 using 409 blocks per input with block size 1048576
[V] 1793149 01:90757399
[V] 2685735 02:61484899
[V] 3602726 04:11409800
[V] 4488946 04:46865999
[V] 5370329 04:88492899
[V] 7190328 05:77421000
[V] 8082355 06:45434600
[V] 8973193 06:79850599
[V] 9864694 07:88054200
[V] 10772236 09:57479799
[V] 11683062 10:49722799
[V] 12605211 11:71030799
[V] 14394965 13:71437799
[V] 15292804 14:90830399
[V] 16187451 16:10666799
[V] 17082689 17:41090700
[V] 17980346 18:24061599
[V] 19126533 19:37264800
[V] 20159650 20:65728800
[V] 20159650
[D]	md5	63dd69acf50be8dfb3efc8f06ed7c464
[V] checksum ok
[V] blocks merged in time 28:57649400
[V] run time 02:26:44453799 (146.445 s)	MemUsage(size=9894.82,rss=1153.87,peak=12209.9)
' returned non-zero exit status 134.
```

**Expected behavior**
complete bcbio run w/o error
[bcbio-nextgen-3.log](https://github.com/bcbio/bcbio-nextgen/files/6548003/bcbio-nextgen-3.log)
[bcbio-nextgen-debug-2.log](https://github.com/bcbio/bcbio-nextgen/files/6548004/bcbio-nextgen-debug-2.log)
[bcbio-nextgen-commands-3.log](https://github.com/bcbio/bcbio-nextgen/files/6548005/bcbio-nextgen-commands-3.log)

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.

**Additional context**
bcbio was installed on a fresh aws ec2 instance

**Comment by naumenko-sa** [comment]
Hi @PatrickJReed !

Thanks for reporting and sorry about the issues!

You are running with 64 cores, how much RAM do you have for that AMI?
Has the alignment for any of the samples finished?
Could you monitor the memory usage with `free -h`? or the system profiling tool?
It might be the case that it is trying to run 64/16 = 4 samples at the same time given the available number of cores,
and exhausts the RAM. If that is the case you may try running with `-n 16`

If you tried just to run one failed command out of bcbio, what would happen?
```bash
/home/ubuntu/bcbio/galaxy/../anaconda/bin/hisat2 \
--new-summary \
-x /home/ubuntu/bcbio/genomes/Mmusculus/mm10/hisat2/mm10 \
-p 16 \
--phred33 --rna-strandness RF \
--rg-id Hepatocyte_7wk_RNA_A3 --rg PL:illumina --rg PU:Hepatocyte_7wk_RNA_A3 --rg SM:Hepatocyte_7wk_RNA_A3  \
-1 /home/ubuntu/Mouse_Age_RNA/101210_1.fastq.gz \
-2 /home/ubuntu/Mouse_Age_RNA/101210_2.fastq.gz \
--known-splicesite-infile /home/ubuntu/bcbio/genomes/Mmusculus/mm10/rnaseq/ref-transcripts-splicesites.txt \
--novel-splicesite-outfile /home/ubuntu/Mouse_Age_RNA/Mouse_Age_RNA/work/align/Hepatocyte_7wk_RNA_A3/Hepatocyte_7wk_RNA_A3-novelsplicesites.bed  | \
/home/ubuntu/bcbio/galaxy/../anaconda/bin/bamsormadup inputformat=sam threads=12 \
tmpfile=./Hepatocyte_7wk_RNA_A3-sort-sorttmp-markdup SO=coordinate \
indexfilename=./Hepatocyte_7wk_RNA_A3-sort.bam.bai > \
./Hepatocyte_7wk_RNA_A3-sort.bam
```

Sergey
