### ISSUE TITLE
Error installing bcbio v1.2.8

### ISSUE THREAD

**Issue by gis-nlsim** [bcbio/bcbio-nextgen#3501]
I'm attempting to install bcbio v1.2.8, but am encountering a CalledProcessError. Am unable to figure out what's wrong as there's not much information about it.

Command that I ran:
python3 bcbio_nextgen_install.py /apps/bcbio/v1.2.8 --tooldir=/apps/bcbio/v1.2.8 --nodata

Error after requirements-condo.txt was saved:

Saving to: `requirements-conda.txt'

requirements-conda.txt                                   100%[==================================================================================================================================>]      20  --.-KB/s    in 0s

2021-06-10 11:30:30 (180 KB/s) - `requirements-conda.txt' saved [20/20]

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: - Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 302, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 50, in main
    bcbio = install_conda_pkgs(anaconda, args)
  File "bcbio_nextgen_install.py", line 114, in install_conda_pkgs
    subprocess.check_call([mamba_bin, "install", "--yes", "--only-deps", "bcbio-nextgen"], env=env)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/apps/bcbio/v1.2.8/anaconda/bin/conda', 'install', '--yes', '--only-deps', 'bcbio-nextgen']' died with <Signals.SIGKILL: 9>.

**Comment by kokyriakidis** [comment]
Hi @naumenko-sa 

I cannot perform a fresh install of bcbio 1.2.8. Here are the conflicts it finds:

```
python3 bcbio_nextgen_install.py /media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio --tooldir=/media/kokyriakidis/RED/BCBIO/TOOLS --genomes hg38 --aligners bwa --aligners star --mamba
Checking required dependencies
Installing isolated base python installation
Installing mamba
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.7/site-packages/conda/cli/install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.7/site-packages/conda/core/solve.py", line 281, in solve_final_state
        ssc = self._run_sat(ssc)
      File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.7/site-packages/conda/core/solve.py", line 808, in _run_sat
        should_retry_solve=ssc.should_retry_solve
      File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.7/site-packages/conda/resolve.py", line 1316, in solve
        raise UnsatisfiableError({})
    conda.exceptions.UnsatisfiableError: 
    Did not find conflicting dependencies. If you would like to know which
    packages conflict ensure that you have enabled unsatisfiable hints.
    
    conda config --set unsatisfiable_hints True
                
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        return getattr(module, func_name)(args, parser)
      File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.7/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.7/site-packages/conda/cli/install.py", line 299, in install
        should_retry_solve=(repodata_fn != repodata_fns[-1]),
      File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.7/site-packages/conda/core/solve.py", line 281, in solve_final_state
        ssc = self._run_sat(ssc)
      File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.7/site-packages/conda/core/solve.py", line 808, in _run_sat
        should_retry_solve=ssc.should_retry_solve
      File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.7/site-packages/conda/resolve.py", line 1318, in solve
        self.find_conflicts(specs, specs_to_add, history_specs)
      File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.7/site-packages/conda/resolve.py", line 347, in find_conflicts
        bad_deps = self.build_conflict_map(specs, specs_to_add, history_specs)
      File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.7/site-packages/conda/resolve.py", line 507, in build_conflict_map
        root, search_node, dep_graph, num_occurances)
      File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.7/site-packages/conda/resolve.py", line 369, in breadth_first_search_for_dep_graph
        last_spec = MatchSpec.union((path[-1], target_paths[-1][-1]))[0]
      File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.7/site-packages/conda/models/match_spec.py", line 481, in union
        return cls.merge(match_specs, union=True)
      File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.7/site-packages/conda/models/match_spec.py", line 475, in merge
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.7/site-packages/conda/models/match_spec.py", line 475, in <lambda>
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.7/site-packages/conda/models/match_spec.py", line 502, in _merge
        final = this_component.union(that_component)
      File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.7/site-packages/conda/models/match_spec.py", line 764, in union
        return '|'.join(options)
    TypeError: sequence item 0: expected str instance, Channel found

`$ /media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/bin/conda install --yes mamba`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda
            DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
           MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
                     PATH=/home/kokyriakidis/.local/bin:/media/kokyriakidis/RED/BCBIO/RESOURCES/
                          bcbio/anaconda/bin:/home/kokyriakidis/gatk-4.1.8.0/:/media/kokyriakidi
                          s/RED/BCBIO/RESOURCES/bcbio/anaconda/bin:/media/kokyriakidis/RED/BCBIO
                          /TOOLS/bin:/home/kokyriakidis/PLINK2/:/home/kokyriakidis/bcftools/:/ho
                          me/kokyriakidis/htslib/:/home/kokyriakidis/.local/bin:/usr/local/sbin:
                          /usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/gam
                          es:/snap/bin:/usr/local/go/bin:/usr/local/go/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=2

     active environment : None
       user config file : /home/kokyriakidis/.condarc
 populated config files : /media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/.condarc
                          /home/kokyriakidis/.condarc
          conda version : 4.8.2
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __cuda=11.2
                          __glibc=2.31
       base environment : /media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda  (writable)
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/pkgs
                          /home/kokyriakidis/.conda/pkgs
       envs directories : /media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/envs
                          /home/kokyriakidis/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Linux/5.8.0-55-generic ubuntu/20.04.2 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

Upload successful.
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 302, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 46, in main
    anaconda = install_mamba(anaconda, args)
  File "bcbio_nextgen_install.py", line 95, in install_mamba
    subprocess.check_call([anaconda["conda"], "install", "--yes", conda_bin])
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/bin/conda', 'install', '--yes', 'mamba']' returned non-zero exit status 1.
```

**Comment by naumenko-sa** [comment]
@gis-nlsim 
conda solve could require a lot of RAM (20G+). Please make sure if you enough RAM in the installation session.

@kokyriakidis 
Are you sure you are not mixing two conda instances?
```
package cache : /media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/pkgs
                          /home/kokyriakidis/.conda/pkgs
envs directories : /media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/envs
                          /home/kokyriakidis/.conda/envs
```
