### ISSUE TITLE
PureCN tumor only error

### ISSUE THREAD

**Issue by kokyriakidis** [bcbio/bcbio-nextgen#3507]
Hi @naumenko-sa!
 
I get the following error when I run PureCN as stated in the user story:

```
INFO [2021-07-06 14:18:28] ------------------------------------------------------------
INFO [2021-07-06 14:18:28] PureCN 1.22.1
INFO [2021-07-06 14:18:28] ------------------------------------------------------------
INFO [2021-07-06 14:18:28] Arguments: -tumor.coverage.file /media/kokyriakidis/PRODUCTION/TMBFDA/NORMALS/ton/work/structural/A/purecn/A_coverage_loess.txt.gz -log.ratio  -seg.file  -vcf.file /media/kokyriakidis/PRODUCTION/TMBFDA/NORMALS/ton/work/mutect2/A-batch-effects-annotated.vcf.gz -genome hg19 -sex ? -args.setPriorVcf 6 -args.setMappingBiasVcf /media/kokyriakidis/PRODUCTION/TMBFDA/NORMALS/pon/final/2021-07-04_pon/mapping_bias_hg19.rds -args.filterIntervals 100 -args.segmentation 0.005,NULL, -sampleid A -min.ploidy 1.4 -max.ploidy 6 -max.non.clonal 0.2 -max.homozygous.loss 0.05,1e+07 -log.ratio.calibration 0.1 -model.homozygous FALSE -error 0.001 -interval.file /media/kokyriakidis/PRODUCTION/TMBFDA/NORMALS/ton/work/bedprep/cleaned-panel.padded100bp.merged.txt -max.segments 300 -plot.cnv TRUE -vcf.field.prefix PureCN. -DB.info.flag DB -POPAF.info.field POP_AF -model beta -post.optimize TRUE -log.file /media/kokyriakidis/PRODUCTION/TMBFDA/NORMALS/ton/work/structural/A/purecn/A.log -normal.coverage.file <data> -normalDB <data> -args.filterVcf <data> -fun.segmentation <data> -test.num.copy <data> -test.purity <data> -speedup.heuristics <data> -BPPARAM <data>
INFO [2021-07-06 14:18:28] Using BiocParallel for parallel optimization.
INFO [2021-07-06 14:18:28] Loading coverage files...
INFO [2021-07-06 14:18:34] Mean target coverages: 271X (tumor) 259X (normal).
INFO [2021-07-06 14:18:34] Mean coverages: chrX: 163.01, chrY: 303.08, chr1-22: 233.20.
INFO [2021-07-06 14:18:34] Mean coverages: chrX: 184.35, chrY: 141.75, chr1-22: 233.16.
INFO [2021-07-06 14:18:48] Removing 904 intervals with missing log.ratio.
INFO [2021-07-06 14:18:48] Removing 6 low/high GC targets.
INFO [2021-07-06 14:18:48] Removing 15753 intervals excluded in normalDB.
INFO [2021-07-06 14:18:49] normalDB provided. Setting minimum coverage for segmentation to 0.0015X.
INFO [2021-07-06 14:18:49] Removing 13591 low coverage (< 0.0015X) intervals.
INFO [2021-07-06 14:18:49] Removing 213 low count (< 100 total reads) intervals.
INFO [2021-07-06 14:18:49] Using 376283 intervals (354253 on-target, 22030 off-target).
INFO [2021-07-06 14:18:49] Ratio of mean on-target vs. off-target read counts: 0.08
INFO [2021-07-06 14:18:49] Mean off-target bin size: 89225
INFO [2021-07-06 14:18:50] AT/GC dropout: 1.06 (tumor), 1.03 (normal), 1.04 (coverage log-ratio). 
INFO [2021-07-06 14:18:50] Loading VCF...
INFO [2021-07-06 14:18:58] Found 162541 variants in VCF file.
INFO [2021-07-06 14:18:59] Removing 10330 triallelic sites.
INFO [2021-07-06 14:18:59] Maximum of POPAP INFO is > 1, assuming -log10 scaled values
WARN [2021-07-06 14:18:59] vcf.file has no DB info field for membership in germline databases. Found and used valid population allele frequency > 0.001000 instead.
INFO [2021-07-06 14:18:59] 109900 (72.2%) variants annotated as likely germline (DB INFO flag).
WARN [2021-07-06 14:19:03] Found 1 variants with missing allelic fraction starting with chr17:40490484_TGAGGGAATACTCCTGGACCTGAGGGAATACTCCTTGACCTGAGGGAATACTCCTTGACCTGAGGGAATACTCCTG/T. Removing them.
INFO [2021-07-06 14:19:03] A is tumor in VCF file.
INFO [2021-07-06 14:19:04] 998 homozygous and 854 heterozygous variants on chrX.
INFO [2021-07-06 14:19:04] Sex from VCF: F (Fisher's p-value: < 0.0001, odds-ratio: 0.66).
WARN [2021-07-06 14:19:04] Sex mismatch of coverage and VCF. Could be because of noisy data, contamination, loss of chrY or a mis-alignment of coverage and VCF.
INFO [2021-07-06 14:19:04] Detected MuTect2 VCF.
INFO [2021-07-06 14:19:06] Removing 56842 Mutect2 calls due to blacklisted failure reasons.
INFO [2021-07-06 14:19:10] Initial testing for significant sample cross-contamination: maybe
INFO [2021-07-06 14:19:11] Removing 70619 variants with AF < 0.030 or AF >= 0.970 or less than 5 supporting reads or depth < 15.
INFO [2021-07-06 14:19:12] Removing 1002 blacklisted variants.
WARN [2021-07-06 14:19:12] Variant ids contain NAs at filter step BQ.
INFO [2021-07-06 14:19:12] Removing 0 low quality variants with BQ < 25.
INFO [2021-07-06 14:19:12] Total size of targeted genomic region: 103.60Mb (119.15Mb with 50bp padding).
INFO [2021-07-06 14:19:12] 5.7% of targets contain variants.
INFO [2021-07-06 14:19:12] Removing 2956 variants outside intervals.
INFO [2021-07-06 14:19:12] Setting somatic prior probabilities for dbSNP hits to 0.000500 or to 0.500000 otherwise.
INFO [2021-07-06 14:19:13] Loading mapping bias file mapping_bias_hg19.rds...
INFO [2021-07-06 14:19:13] Found 18564 variants in mapping bias file.
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'nrow': no method for coercing this S4 class to a vector
Calls: runAbsoluteCN ... as.character -> .local -> as.vector -> .handleSimpleError -> h
In addition: Warning message:
In .bcfHeaderAsSimpleList(header) :
  duplicate keys in header will be forced to unique rownames
Execution halted
' returned non-zero exit status 1.
[2021-07-06T11:19Z] PureCN failed
Traceback (most recent call last):
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 179, in variant2pipeline
    samples = structural.run(samples, run_parallel, "standard")
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/__init__.py", line 228, in run
    for xs in to_process.values()))
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1048, in __call__
    if self.dispatch_one_batch(iterator):
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 866, in dispatch_one_batch
    self._dispatch(tasks)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 784, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 59, in wrapper
    return f(*args, **kwargs)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 359, in detect_sv
    return structural.detect_sv(*args)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/__init__.py", line 254, in detect_sv
    for svdata in caller_fn(items):
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/purecn.py", line 36, in run
    purecn_out = _run_purecn_dx(purecn_out, paired)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/purecn.py", line 117, in _run_purecn_dx
    out_base, out, all_files = _get_purecn_dx_files(paired, out)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/purecn.py", line 139, in _get_purecn_dx_files
    out_base = utils.splitext_plus(out["rds"])[0]
KeyError: 'rds'
```

EDIT: Updating to version 1.23.5 solved the issue!

**Comment by kokyriakidis** [comment]
Bcbio halts later in mutation_burden

```
[2021-07-06T13:18Z] INFO [2021-07-06 16:18:14] Optimized purity: 0.60
[2021-07-06T13:18Z] INFO [2021-07-06 16:18:14] Initial guess of contamination rate: 0.021
[2021-07-06T13:18Z] INFO [2021-07-06 16:18:14] Optimizing contamination rate of optimum 1/3...
[2021-07-06T13:19Z] INFO [2021-07-06 16:19:54] Optimized contamination rate: 0.027
[2021-07-06T13:19Z] INFO [2021-07-06 16:19:54] Optimized contamination rate: 0.001
[2021-07-06T13:19Z] INFO [2021-07-06 16:19:54] Optimized contamination rate: 0.002
[2021-07-06T13:19Z] INFO [2021-07-06 16:19:54] Done.
[2021-07-06T13:19Z] INFO [2021-07-06 16:19:54] ------------------------------------------------------------
[2021-07-06T13:20Z] Warning message:
[2021-07-06T13:20Z] In .bcfHeaderAsSimpleList(header) :
[2021-07-06T13:20Z]   duplicate keys in header will be forced to unique rownames
[2021-07-06T13:20Z] INFO [2021-07-06 16:20:57] Generating output files...
[2021-07-06T13:21Z] INFO [2021-07-06 16:21:10] Tumor/normal noise ratio: 30.513
[2021-07-06T13:21Z] WARN [2021-07-06 16:21:10] Extensive noise in tumor compared to normals.
[2021-07-06T13:21Z] INFO [2021-07-06 16:21:10] Using BiocParallel for parallel optimization.
[2021-07-06T13:26Z] Saved PureCN output to /media/kokyriakidis/PRODUCTION/TMBFDA/NORMALS/ton/work/structural/A/purecn
Traceback (most recent call last):
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 179, in variant2pipeline
    samples = structural.run(samples, run_parallel, "standard")
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/__init__.py", line 228, in run
    for xs in to_process.values()))
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1048, in __call__
    if self.dispatch_one_batch(iterator):
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 866, in dispatch_one_batch
    self._dispatch(tasks)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 784, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 59, in wrapper
    return f(*args, **kwargs)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 359, in detect_sv
    return structural.detect_sv(*args)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/__init__.py", line 254, in detect_sv
    for svdata in caller_fn(items):
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/purecn.py", line 36, in run
    purecn_out = _run_purecn_dx(purecn_out, paired)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/purecn.py", line 122, in _run_purecn_dx
    if not utils.file_uptodate(out["mutation_burden"], out["rds"]):
KeyError: 'mutation_burden'
```

**Comment by naumenko-sa** [comment]
Thanks for reporting @kokyriakidis !
Please update to the latest code and give it a try!
SN

**Comment by naumenko-sa** [comment]
This should be resolved in bcbio1.2.9. Please re-open if you still see issues there.
