### ISSUE TITLE
Running T/N for multi-tumour sample experiments

### ISSUE THREAD

**Issue by DolapoA** [bcbio/bcbio-nextgen#3524]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.4
- OS name and version (`lsb_release -ds`): CentOS Linux release 7.8.2003 (Core)

**To Reproduce**
Exact bcbio command you have used:
```
bcbio_nextgen.py ../config/MPNST_exome_93.yaml -n 8
```
Your sample configuration file:
```
description,samplename,batch,phenotype
096-S000855-T_S5_R1_001.fastq.gz,2190960-S00085517,ROY004,tumor
096-S000855-T_S5_R2_001.fastq.gz,2190960-S00085517,ROY004,tumor
096-S000878-T_S6_R1_001.fastq.gz,2190961-S00087833,ROY004,tumor
096-S000878-T_S6_R2_001.fastq.gz,2190961-S00087833,ROY004,tumor
096-S000878-T_S7_R1_001.fastq.gz,2190962-S00087839,ROY004,tumor
096-S000878-T_S7_R2_001.fastq.gz,2190962-S00087839,ROY004,tumor
096-S000878-T_S8_R1_001.fastq.gz,2190963-S00087845,ROY004,tumor
096-S000878-T_S8_R2_001.fastq.gz,2190963-S00087845,ROY004,tumor
096-S000878-T_S9_R1_001.fastq.gz,2190964-S00087850,ROY004,tumor
096-S000878-T_S9_R2_001.fastq.gz,2190964-S00087850,ROY004,tumor
096-S000858-T_S0_R1_001.fastq.gz,2190965-S00085882,ROY005,tumor
096-S000858-T_S0_R2_001.fastq.gz,2190965-S00085882,ROY005,tumor
096-S000878-T_S1_R1_001.fastq.gz,2190966-S00087880,ROY005,tumor
096-S000878-T_S1_R2_001.fastq.gz,2190966-S00087880,ROY005,tumor
096-S000878-T_S2_R1_001.fastq.gz,2190967-S00087887,ROY005,tumor
096-S000878-T_S2_R2_001.fastq.gz,2190967-S00087887,ROY005,tumor
096-S000878-T_S3_R1_001.fastq.gz,2190968-S00087892,ROY005,tumor
096-S000878-T_S3_R2_001.fastq.gz,2190968-S00087892,ROY005,tumor
096-S000878-T_S4_R1_001.fastq.gz,2190969-S00087897,ROY005,tumor
096-S000878-T_S4_R2_001.fastq.gz,2190969-S00087897,ROY005,tumor
```

**Observed behavior**
Error message or bcbio output:
```
Traceback (most recent call last):
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/tools/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 128, in variant2pipeline
    [x[0]["description"] for x in samples]]])
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 765, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 459, in organize_samples
    return run_info.organize(*args)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/pipeline/run_info.py", line 62, in organize
    is_cwl=is_cwl, integrations=integrations)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/pipeline/run_info.py", line 1014, in _run_info_from_yaml
    _check_sample_config(run_details, run_info_yaml, config)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/pipeline/run_info.py", line 785, in _check_sample_config
    _check_for_problem_somatic_batches(items, config)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/pipeline/run_info.py", line 494, in _check_for_problem_somatic_batches
    vcfutils.check_paired_problems(items)
  File "/SAN/colcc/pillaylab-software/bcbio-pipeline/anaconda/lib/python3.6/site-packages/bcbio/variation/vcfutils.py", line 106, in check_paired_problems
    [dd.get_sample_name(data) for data in items]))
ValueError: Unsupported configuration: found multiple tumor samples in batch ROY004: ['96-S000855-T_S5', '096-S000878-T_S6', '096-S000878-T_S7', '96-S000878-T_S8', '96-S000878-T_S39', '01-S0008553-B_S5']

```

Any help on how or whether I am able to use the Tumour/Normal pipeline on an experiment consisting of multiple tumour samples per patient, each with a single adjacent or associated normal sample will be greatly appreciated. 
Thank you.

**Comment by naumenko-sa** [comment]
Hi @DolapoA !

Every T/N should go to its own batch. A normal sample could participate in many batches, i.e. serving as a normal for many tumor samples:
https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#automated-sample-configuration

SN

**Comment by DolapoA** [comment]
My apologies, this is not quite clear to me. Using my example sample configuration, could you show me how your solution works in practise?

**Comment by naumenko-sa** [comment]
Also, I would recommend to update 1.2.4 to the latest dev if possible.
