### ISSUE TITLE
mosdepth index error for germline WES

### ISSUE THREAD

**Issue by biosurgeon** [bcbio/bcbio-nextgen#3531]
Hi, 

Thanks for developing and sharing this nice tool.  It is really helpful to me for my project. 
I have germline WES data and I'm running bcbio and encountered below situation. 
It seemed some kind of indexing problem, but I do not figure it out.  (samtools version 1.9)
Could you help me?

**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.9a
- OS name and version (`lsb_release -ds`): Docker (Ubuntu) in Mac

**To Reproduce**
Exact bcbio command you have used:
```
details:
- description: MPC_001
  files:
  - /scratch_16T/MPC_germline/raw_data/W091-03-01_1.fastq.gz
  - /scratch_16T/MPC_germline/raw_data/W091-03-01_2.fastq.gz
  metadata:
    batch: [MPC001]
    phenotype: normal
  analysis: variant2
  genome_build: hg38
  algorithm:
    platform: illumina
    quality_format: standard
    trim_reads: true
    adapters: truseq
    aligner:  bwa
    mark_duplicates: true
    recalibrate: gatk
    realign: false
    variantcaller: gatk-haplotype
    effects: vep
    tools_off: [peddy]
    coverage: /scratch_16T/annotation_DB/SureSelect_v6.bed
    variant_regions: /scratch_16T/annotation_DB/SureSelect_v6.bed
    min_allele_fraction: 0
    ensemble:
      numpass: 2
fc_date: '2021-09-18'
fc_name: MPC_001
upload:
  dir: ../MPC_001
```
Your sample configuration file:
```

```

**Observed behavior**
Error message or bcbio output:
```
2021-09-19T12:56Z] [V] flushing read ends lists...done.
[2021-09-19T12:59Z] [V] merging read ends lists/computing duplicates...done, time 03:22:10125400
[2021-09-19T12:59Z] [V] num dups 23039705
[2021-09-19T12:59Z] # bamsormadup
[2021-09-19T12:59Z] ##METRICS
[2021-09-19T12:59Z] LIBRARY	UNPAIRED_READS_EXAMINED	READ_PAIRS_EXAMINED	UNMAPPED_READS	UNPAIRED_READ_DUPLICATES	READ_PAIR_DUPLICATES	READ_PAIR_OPTICAL_DUPLICATES	PERCENT_DUPLICATION	ESTIMATED_LIBRARY_SIZE
[2021-09-19T12:59Z] Unknown Library	172671	99037661	226219	106653	11466526	1042164	0.116217   	427329677
[2021-09-19T12:59Z] ## HISTOGRAM
[2021-09-19T12:59Z] BIN	VALUE
[2021-09-19T12:59Z] 1	1.00945
...
[2021-09-19T12:59Z] 100	4.8798
[2021-09-19T12:59Z] [V] blocks generated in time 11:40:74700800
[2021-09-19T12:59Z] [V] number of blocks to be merged is 218 using 37 blocks per input with block size 1048576
[2021-09-19T13:00Z] [V] 1648513 01:12:33096600
[2021-09-19T13:00Z] [V] 2440512 01:12:75686500
...
[2021-09-19T13:15Z] [V] 199306268
[2021-09-19T13:16Z] [D]	md5	b708c4779d525789ddadaf9977efcef5
[2021-09-19T13:16Z] [V] checksum ok
[2021-09-19T13:16Z] [V] blocks merged in time 16:30:80321300
[2021-09-19T13:16Z] [V] run time 28:11:58966200 (1691.59 s)	MemUsage(size=11070.9,rss=10121.7,peak=13929.2)
[2021-09-19T13:16Z] Check for valid merged BAM
[2021-09-19T13:16Z] Check for valid merged BAM after transfer
[2021-09-19T13:16Z] Timing: callable regions
[2021-09-19T13:16Z] multiprocessing: prep_samples
[2021-09-19T13:16Z] multiprocessing: postprocess_alignment
[2021-09-19T13:16Z] Calculating coverage: MPC_001 variant_regions
[2021-09-19T13:16Z] fatal.nim(49)            sysFatal
[2021-09-19T13:16Z] Error: unhandled exception: index 249106160 not in 0 .. 248956422 [IndexError]
[2021-09-19T13:16Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; export MOSDEPTH_Q0=NO_COVERAGE && export MOSDEPTH_Q1=LOW_COVERAGE && export MOSDEPTH_Q2=CALLABLE && /bcbio/tools/bin/mosdepth -t 12 -F 1804 -Q 1 --no-per-base --by /scratch_16T/MPC_germline/config/bedprep/cleaned-SureSelect_v6-merged.bed --quantize 0:1:4: /scratch_16T/MPC_germline/config/bcbiotx/tmp63v92ijx/MPC_001-variant_regions /scratch_16T/MPC_germline/config/align/MPC_001/MPC_001-sort.bam
fatal.nim(49)            sysFatal
Error: unhandled exception: index 249106160 not in 0 .. 248956422 [IndexError]
' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 138, in variant2pipeline
    samples = run_parallel("postprocess_alignment", samples)
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1041, in __call__
    if self.dispatch_one_batch(iterator):
  File "/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 859, in dispatch_one_batch
    self._dispatch(tasks)
  File "/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 777, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 59, in wrapper
    return f(*args, **kwargs)
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 157, in postprocess_alignment
    return sample.postprocess_alignment(*args)
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sample.py", line 281, in postprocess_alignment
    covinfo = callable.sample_callable_bed(bam_file_ready, ref_file, data)
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/bam/callable.py", line 45, in sample_callable_bed
    callable_bed, depth_files = coverage.calculate(bam_file, data, sv_bed)
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/coverage.py", line 101, in calculate
    per_base=per_base)
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/coverage.py", line 247, in run_mosdepth
    do.run(cmd.format(**locals()), message.format(**locals()))
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; export MOSDEPTH_Q0=NO_COVERAGE && export MOSDEPTH_Q1=LOW_COVERAGE && export MOSDEPTH_Q2=CALLABLE && /bcbio/tools/bin/mosdepth -t 12 -F 1804 -Q 1 --no-per-base --by /scratch_16T/MPC_germline/config/bedprep/cleaned-SureSelect_v6-merged.bed --quantize 0:1:4: /scratch_16T/MPC_germline/config/bcbiotx/tmp63v92ijx/MPC_001-variant_regions /scratch_16T/MPC_germline/config/align/MPC_001/MPC_001-sort.bam
fatal.nim(49)            sysFatal
Error: unhandled exception: index 249106160 not in 0 .. 248956422 [IndexError]
' returned non-zero exit status 1.
```

**Expected behavior**

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.

[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/7192189/bcbio-nextgen-commands.log)
[bcbio-nextgen-debug.log](https://github.com/bcbio/bcbio-nextgen/files/7192190/bcbio-nextgen-debug.log)
[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/7192191/bcbio-nextgen.log)
**Additional context**

**Comment by naumenko-sa** [comment]
Hi @biosurgeon !

Glad that bcbio is useful for you!

I think 248,956,422 is the chrom1 length, see `genomes/Hsapiens/hg38/seq/hg38.dict`
During the MOSDEPTH step bcbio is trying to calculate coverage over the bed file you supplied.
I suspect this file has an interval outside of the chr1 boundaries, i.e. at 249,106,160.

Could you please check it in `/scratch_16T/annotation_DB/SureSelect_v6.bed`? 

You can also compare it to the one we have in bcbio:
`genomes/Hsapiens/hg38/coverage/capture_regions/Exome-Agilent_V6.bed`

Another potential issue - you are using just one variant caller (gatk-haplotype) and `ensemble/numpass: 2` which requires at least 2 variant callers.

SN

**Comment by biosurgeon** [comment]
Hi Sergey, 

Yes. You are right.  It's the bed file problem, and It works well with new bed file. 
I really appreciate your prompt response and solution. :)

best, 

Young
