### ISSUE TITLE
errors with atacseq

### ISSUE THREAD

**Issue by DiyaVaka** [bcbio/bcbio-nextgen#3545]
Hi, 

I am trying to run atacseq, Below are the errors. I tried to increase ulimit. No use. Can you please help

Traceback (most recent call last):
  File "/home/projects/dvaka/bcbio/tools/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/home/projects/dvaka/bcbio/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/projects/dvaka/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/home/projects/dvaka/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/projects/dvaka/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 388, in chipseqpipeline
    samples = run_parallel("clean_chipseq_alignment", samples)
  File "/home/projects/dvaka/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/projects/dvaka/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/home/projects/dvaka/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1043, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/projects/dvaka/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 861, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/projects/dvaka/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 779, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/projects/dvaka/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/home/projects/dvaka/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/home/projects/dvaka/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/projects/dvaka/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/projects/dvaka/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 59, in wrapper
    return f(*args, **kwargs)
  File "/home/projects/dvaka/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 415, in clean_chipseq_alignment
    return chipseq.clean_chipseq_alignment(*args)
  File "/home/projects/dvaka/bcbio/anaconda/lib/python3.6/site-packages/bcbio/chipseq/__init__.py", line 29, in clean_chipseq_alignment
    clean_bam = remove_mitochondrial_reads(clean_bam, data)
  File "/home/projects/dvaka/bcbio/anaconda/lib/python3.6/site-packages/bcbio/chipseq/__init__.py", line 70, in remove_mitochondrial_reads
    do.run(cmd, message)
  File "/home/projects/dvaka/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/projects/dvaka/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 85, in _do_run
    env=env,
  File "/home/projects/dvaka/bcbio/anaconda/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/home/projects/dvaka/bcbio/anaconda/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: '/usr/bin/bash'

**Comment by naumenko-sa** [comment]
Hi @DiyaVaka !

Could you please attach the yaml config file of your project?

Sergey

**Comment by naumenko-sa** [comment]
HI @DiyaVaka !

I think I've seen that bug. What is your MT genome in galGal4?

https://github.com/bcbio/bcbio-nextgen/blob/cd1720c0e150f436b7e8fb136ca3001c21a110fb/bcbio/heterogeneity/chromhacks.py#L29

Sergey
