### ISSUE TITLE
ggd-run.sh ftp file not found errors

### ISSUE THREAD

**Issue by gis-nlsim** [bcbio/bcbio-nextgen#3547]
Greetings, 
I'm trying to install bcbio v1.2.8 on an AWS cluster, but upon running upgrade to install the aligners and genomes, I'm getting this error: 2021-10-28 00:44:02 ERROR 404: Not Found

```
ubuntu@ip-10-255-0-252:/apps/install.bcbio$ python $BCBIO_HOME/anaconda/bin/bcbio_nextgen.py upgrade -u skip --genomes GRCh37 --genomes hg38 --aligners bwa --aligners star
Upgrading bcbio
Upgrading bcbio-nextgen data files
List of genomes to get (from the config file at '{'genomes': [{'dbkey': 'GRCh37', 'name': 'Human (GRCh37)', 'indexes': ['seq', 'twobit'], 'annotations': ['GA4GH_problem_regions', 'capture_regions', 'MIG', 'prioritize', 'dbsnp', 'hapmap',\
 '1000g_omni_snps', 'ACMG56_genes', '1000g_snps', 'mills_indels', 'clinvar', 'cosmic', 'ancestral', 'qsignature', 'genesplicer', 'effects_transcripts', 'varpon', 'vcfanno', 'viral', 'transcripts', 'RADAR', 'fusion-blacklist', 'mirbase'],\
 'validation': ['giab-NA12878', 'giab-NA24385', 'giab-NA24631', 'dream-syn3', 'dream-syn4', 'giab-NA12878-NA24385-somatic', 'giab-NA24143', 'giab-NA24149', 'giab-NA24694', 'giab-NA24695']}, {'dbkey': 'hg38', 'name': 'Human (hg38) full', \
'indexes': ['seq', 'twobit', 'bwa', 'hisat2'], 'annotations': ['ccds', 'capture_regions', 'coverage', 'prioritize', 'dbsnp', 'hapmap_snps', '1000g_omni_snps', 'ACMG56_genes', '1000g_snps', 'mills_indels', '1000g_indels', 'clinvar', 'qsig\
nature', 'genesplicer', 'effects_transcripts', 'varpon', 'vcfanno', 'viral', 'purecn_mappability', 'simple_repeat', 'af_only_gnomad', 'transcripts', 'RADAR', 'rmsk', 'salmon-decoys', 'fusion-blacklist', 'mirbase'], 'validation': ['giab-N\
A12878', 'giab-NA24385', 'giab-NA24631', 'platinum-genome-NA12878', 'giab-NA12878-remap', 'giab-NA12878-crossmap', 'dream-syn4-crossmap', 'dream-syn3-crossmap', 'giab-NA12878-NA24385-somatic', 'giab-NA24143', 'giab-NA24149', 'giab-NA2469\
4', 'giab-NA24695']}], 'genome_indexes': ['bwa', 'star', 'rtg'], 'install_liftover': False, 'install_uniref': False}'): Human (GRCh37), Human (hg38) full
Running GGD recipe: GRCh37 srnaseq 20180710
2021-10-28 00:43:39 URL: ftp://mirbase.org/pub/mirbase/20/genomes/hsa.gff3 [519390] -> "hsahg19.gff3" [1]
2021-10-28 00:43:56 URL: ftp://mirbase.org/pub/mirbase/21/hairpin.fa.gz [1207144] -> "hairpin.fa.gz" [1]
2021-10-28 00:43:57 URL: ftp://mirbase.org/pub/mirbase/21/mature.fa.gz [590888] -> "mature.fa.gz" [1]
2021-10-28 00:43:59 URL: ftp://mirbase.org/pub/mirbase/21/miRNA.str.gz [2640341] -> "miRNA.str.gz" [1]
2021-10-28 00:44:00 URL: ftp://mirbase.org/pub/mirbase/21/genomes/hsa.gff3 [522631] -> "mirbase.gff3" [1]
https://github.com/TJU-CMC-Org/MINTmap/raw/master/LookupTable.tRFs.MINTmap_v1.txt:
2021-10-28 00:44:02 ERROR 404: Not Found.
Traceback (most recent call last):
  File "/apps/bcbio128/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/apps/bcbio128/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 107, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/apps/bcbio128/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 359, in upgrade_bcbio_data
    args.cores, ["ggd", "s3", "raw"])
  File "/apps/install.bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 354, in install_data_local
    _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
  File "/apps/install.bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 480, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/apps/install.bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 875, in _install_with_ggd
    ggd.install_recipe(os.getcwd(), env.system_install, recipe_file, gid)
  File "/apps/install.bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"], system_install)
  File "/apps/install.bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/apps/bcbio128/anaconda/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/apps/bcbio128/anaconda/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bash', '/apps/bcbio128/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh']' returned non-zero exit status 8.
```

**Comment by naumenko-sa** [comment]
Thanks for catching this @gis-nlsim !

It is hard to catch since we almost never re-install the data.

The error is due to restructuing of https://github.com/TJU-CMC-Org/MINTmap

I've updated the recipe: https://github.com/chapmanb/cloudbiolinux/pull/390

Please try again and let me know it if works for you!

Sergey
