### ISSUE TITLE
Picard path not detected since cloudbiolinux env update

### ISSUE THREAD

**Issue by matthdsm** [bcbio/bcbio-nextgen#3551]
Hi,

We recently reinstalled our bcbio instance (with the new env config from cloudbiolinux).
Since then we're getting the following error
```
ValueError: Could not find directory in config for picard
```

Reading past issues, it seems like `picard` in the `java` env isn`t detected.

Matthias

**Comment by naumenko-sa** [comment]
Hi @matthdsm !

Thanks for testing!

Please make sure you upgraded `bcbio_nextgen.py upgrade -u development` after install and received
https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/variation/vcfutils.py#L539

picard now is in the java env, so we are picking up java8 from it not java11 from the base.

If you are hitting a similar error, please provide more details to reproduce!

Sergey

**Comment by matthdsm** [comment]
fixed by updating the codebase!

Thanks!

**Comment by jxshi** [comment]
Hi,

I encountered the same error recently after update to the latest development version.
```
Traceback (most recent call last):
  File "/home/dell/local/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/home/dell/local/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/dell/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/home/dell/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/dell/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 138, in variant2pipeline
    samples = run_parallel("postprocess_alignment", samples)
  File "/home/dell/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/dell/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/home/dell/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1041, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/dell/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 859, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/dell/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 777, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/dell/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/home/dell/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/home/dell/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/dell/local/share/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/dell/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 59, in wrapper
    return f(*args, **kwargs)
  File "/home/dell/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 157, in postprocess_alignment
    return sample.postprocess_alignment(*args)
  File "/home/dell/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/sample.py", line 269, in postprocess_alignment
    artifacts = gatk.collect_artifact_metrics(data)
  File "/home/dell/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/gatk.py", line 222, in collect_artifact_metrics
    broad_runner = broad.runner_from_config(dd.get_config(data))
  File "/home/dell/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/broad/__init__.py", line 518, in runner_from_config
    return BroadRunner(_get_picard_ref(config), pdir, config)
  File "/home/dell/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/broad/__init__.py", line 508, in _get_picard_ref
    picard = config_utils.get_program("picard", config, "dir")
  File "/home/dell/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/config_utils.py", line 193, in get_program
    return _get_program_dir(name, pconfig)
  File "/home/dell/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/config_utils.py", line 245, in _get_program_dir
    raise ValueError("Could not find directory in config for %s" % name)
ValueError: Could not find directory in config for picard
```

I have updated the the stable version but the error message did not disappear. Do you guys have any ideas to solve the problem?

Thank you in advance!
Best,
Jianxiang

**Comment by naumenko-sa** [comment]
Hi @jxshi !

I see `python3.6` in your log, so you are upgrading the old installation. 
Due to reogranization of conda environments, 
to get the new version you need to reinstall bcbio code from scratch and link the genomes:
https://bcbio-nextgen.readthedocs.io/en/latest/contents/development.html#creating-a-separate-bcbio-installation

(install and then upgrade it to the latest dev)

Sergey

**Comment by jxshi** [comment]
Hi @naumenko-sa ,

Thank you for your timely reply! Your solution works!

Best,
Jianxiang
