### ISSUE TITLE
can't make use of Picard tools via gatk3

### ISSUE THREAD

**Issue by mvheetve** [bcbio/bcbio-nextgen#3553]
Hi,

this issue concerns the same recently renewed installation mentioned in #3551 (@matthdsm). The following problem arose: 

```
[2021-11-05T04:27Z] multiprocessing: postprocess_alignment
[2021-11-05T04:27Z] GATK: CollectSequencingArtifactMetrics
[2021-11-05T04:27Z] ##### ERROR ------------------------------------------------------------------------------------------
[2021-11-05T04:27Z] ##### ERROR A USER ERROR has occurred (version 3.8-1-0-gf15c1c3ef):
[2021-11-05T04:27Z] ##### ERROR
[2021-11-05T04:27Z] ##### ERROR This means that one or more arguments or inputs in your command are incorrect.
[2021-11-05T04:27Z] ##### ERROR The error message below tells you what is the problem.
[2021-11-05T04:27Z] ##### ERROR
[2021-11-05T04:27Z] ##### ERROR If the problem is an invalid argument, please check the online documentation guide
[2021-11-05T04:27Z] ##### ERROR (or rerun your command with --help) to view allowable command-line arguments for this tool.
[2021-11-05T04:27Z] ##### ERROR
[2021-11-05T04:27Z] ##### ERROR Visit our website and forum for extensive documentation and answers to
[2021-11-05T04:27Z] ##### ERROR commonly asked questions https://software.broadinstitute.org/gatk
[2021-11-05T04:27Z] ##### ERROR
[2021-11-05T04:27Z] ##### ERROR Please do NOT post this error to the GATK forum unless you have really tried to fix it yourself.
[2021-11-05T04:27Z] ##### ERROR
[2021-11-05T04:27Z] ##### ERROR MESSAGE: Invalid command line: Malformed walker argument: Could not find walker with name: CollectSequencingArtifactMetrics
[2021-11-05T04:27Z] ##### ERROR ------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/tools/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 138, in variant2pipeline
    samples = run_parallel("postprocess_alignment", samples)
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 1048, in __call__
    if self.dispatch_one_batch(iterator):
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 866, in dispatch_one_batch
    self._dispatch(tasks)
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 784, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/bcbio/utils.py", line 59, in wrapper
    return f(*args, **kwargs)
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/bcbio/distributed/multitasks.py", line 157, in postprocess_alignment
    return sample.postprocess_alignment(*args)
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/sample.py", line 269, in postprocess_alignment
    artifacts = gatk.collect_artifact_metrics(data)
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/bcbio/variation/gatk.py", line 241, in collect_artifact_metrics
    broad_runner.run_gatk(params, log_error=False, parallel_gc=True)
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/bcbio/broad/__init__.py", line 365, in run_gatk
    log_error=log_error)
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && export PATH=/kyukon/data/gent/shared/000/gvo00082/bcbio/tools/bin:"$PATH" && /kyukon/data/gent/shared/000/gvo00082/bcbio/tools/bin/gatk3 -Xms681m -Xmx3636m -Djava.io.tmpdir=/scratch/gent/vo/000/gvo00082/vsc43079/bcbio/tmp9l_f51zm -T CollectSequencingArtifactMetrics --VALIDATION_STRINGENCY SILENT -R /kyukon/data/gent/shared/000/gvo00082/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa -I /vscmnt/gent_kyukon_data/_kyukon_data_gent/vo/000/gvo00082/research/LabDeBaere/WES/2006KNO-0039/samples_2006KNO-0039-merged/work/align/D1914769/D1914769-sort.bam -O /scratch/gent/vo/000/gvo00082/vsc43079/bcbio/tmpg1tzqqxe/D1914769/D1914769 -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment
```

would it be possible to make use of Picard for subroutines such as CollectSequencingArtifactMetrics in stead of GATK? 

Regards
Mvheetve

**Comment by naumenko-sa** [comment]
Hi @mvheetve !

Thanks for reporting and sorry about the issues!
Could you please provide your yaml config file? Are you using `tools_off: gatk4`?

In gatk4, picard is merged into gatk.

Sergey

**Comment by matthdsm** [comment]
Hi Sergey,

Yes, we're using gatk3 for variant calling. It seems bcbio just goes with the chosen gatk version (which is good) regardless of the availability of the called tool (less good). IMO, picard tools should run with the picard runner instead of the gatk runner. 
This will also fix some version conflicts, since the version of picard bundled with gatk is not the same as the one installed from conda (and used during qc).

Matthias

**Comment by mvheetve** [comment]
Hi Sergey,

thanks for the reply. Attached is the template we use to build the config file.

Mattias (not to be mistaken with Matthias ;))
[samples_2006KNO-0039-merged-template.yaml.txt](https://github.com/bcbio/bcbio-nextgen/files/7503092/samples_2006KNO-0039-merged-template.yaml.txt)

**Comment by naumenko-sa** [comment]
Please update to the latest dev and give it a try: https://github.com/bcbio/bcbio-nextgen/pull/3556
Works for both gatk4 and gatk3 in my tests.

Thanks for bringing to my attention that we now have two picards:
- picard 2.26.5 from bioconda
- picard bundled into GATK4:
```
The Genome Analysis Toolkit (GATK) v4.2.3.0
HTSJDK Version: 2.24.1
Picard Version: 2.25.4
```
Interestingly, the separate picard is a bit newer, since they first release it in picard and then as a part of gatk release.

So, we historically arrived to having 2 gatk's and 2 picards: just picard and gatk3.x, then gatk4x, then gatk4x+picard.

I understand the motivation of running picard utils through the picard runner for the gatk3 based use case (you'd want gatk(3) and picard, rather than gatk(3) and some utilities from gatk(4)).

However, after some thought, I think that for the bcbio codebase 
it would still be better to run picard tools through gatk4 and drop the separate picard entirely (and separate picard runner). 
That would simplify our gatk setup (default= gatk4+picard, for some exceptional cases run gatk3), allow to have just one version of picard, and refactor
- https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/broad/__init__.py, 
- https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/broad/metrics.py, 
- https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/broad/picardrun.py, 
- https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/variation/gatk.py#L213 ).

If anybody else has thoughts re two picards, please chime in!

SN

**Comment by matthdsm** [comment]
Hi Sergey,

Thanks for the fixes.
Personally, I'd run all picard tools through picard and leave the bundled and not use the bundled gatk. As you stated, the bundled version is older than the latest one. 
The bundled picard may contain bugs which are fixed in later picard versions (which have a much shorter generation time). This has happened before and may well happen again.
I'd go for a  picard + gatk3 + gatk4 setup and migrate all running of picard tools to the picard runner.

I do realise this gives us some overhead in the code and install base, but that way the user is guaranteed the latest version of the output, regardless of whichever version happened to be bundled with gatk.

Matthias

**Comment by mvheetve** [comment]
Hi Sergey,

while I think Matthias raises a valid point, I can also appreciate your side of things. For now the issue seems to be fixed for which we are very grateful! 

Mattias
