### ISSUE TITLE
ValueError: numpy.ufunc size changed, may indicate binary incompatibility.

### ISSUE THREAD

**Issue by mvheetve** [bcbio/bcbio-nextgen#3559]
Hi again,

regarding the analysis we were running in #3553. The Picard issue was fixed, for which many thanks, but we just encountered this issue downstream: 

```
Traceback (most recent call last):
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/tools/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 187, in variant2pipeline
    samples = population.prep_db_parallel(samples, run_parallel)
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/bcbio/variation/population.py", line 406, in prep_db_parallel
    output = parallel_fn("prep_gemini_db", to_process)
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 1048, in __call__
    if self.dispatch_one_batch(iterator):
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 866, in dispatch_one_batch
    self._dispatch(tasks)
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 784, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/bcbio/utils.py", line 59, in wrapper
    return f(*args, **kwargs)
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/bcbio/distributed/multitasks.py", line 387, in prep_gemini_db
    return population.prep_gemini_db(*args)
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/bcbio/variation/population.py", line 51, in prep_gemini_db
    gemini_db = create_gemini_db(ann_vcf, data, gemini_db, ped_file)
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/bcbio/variation/population.py", line 143, in create_gemini_db
    do.run(cmd, "GEMINI: create database with vcf2db")
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/lib/python3.7/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command '/vscmnt/gent_kyukon_data/_kyukon_data_gent/shared/000/gvo00082/bcbio/anaconda/envs/python2/bin/vcf2db.py /vscmnt/gent_kyukon_data/_kyukon_data_gent/vo/000/gvo00082/research/LabDeBaere/WES/2006KNO-0039/samples_2006KNO-0039-merged/work/gemini/D1914769-joint-gatk-haplotype-joint-nomultiallelic-annotated-dbnsfp.vcf.gz /vscmnt/gent_kyukon_data/_kyukon_data_gent/vo/000/gvo00082/research/LabDeBaere/WES/2006KNO-0039/samples_2006KNO-0039-merged/work/gemini/D1914769-joint-gatk-haplotype-joint-nomultiallelic.ped /scratch/gent/vo/000/gvo00082/vsc43079/bcbio/tmpxalvnlv5/D1914769-joint-gatk-haplotype-joint.db
Traceback (most recent call last):
  File "/vscmnt/gent_kyukon_data/_kyukon_data_gent/shared/000/gvo00082/bcbio/anaconda/envs/python2/bin/vcf2db.py", line 30, in <module>
    import cyvcf2
  File "/kyukon/data/gent/shared/000/gvo00082/bcbio/anaconda/envs/python2/lib/python2.7/site-packages/cyvcf2/__init__.py", line 1, in <module>
    from .cyvcf2 import (VCF, Variant, Writer, r_ as r_unphased, par_relatedness,
  File "__init__.pxd", line 918, in init cyvcf2.cyvcf2
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
' returned non-zero exit status 1.
```
We've tried updating to:
```
vcf2db                    2020.02.24           hdfd78af_1    bioconda
cyvcf2                    0.30.11          py27h3ce6e29_0    bioconda
numpy                     1.12.1          py27_blas_openblash1522bff_1001    conda-forge
```
But no luck... 
Considering these threads: 
https://github.com/scikit-learn-contrib/hdbscan/issues/272
https://stackoverflow.com/questions/60323366/valueerror-numpy-ufunc-size-changed-may-indicate-binary-incompatibility-expec

Would it be possible to extract vcf2db and cyvcf2 from the Py2 environment and switch to Py3? This way we hope a more recent numpy version will alleviate the problem. 

Regards
Mattias, also on behalf of Matthias (@matthdsm)

**Comment by naumenko-sa** [comment]
Hi Mattias @mvheetve !

Thanks for the detailed report!

We have tried upgrading vcf2db to python3 and ran into issues. 

Could you please try (you might need to remove vcf2db/cyvcf2/numpy in the python2 env):
```
mamba install -n python2 vcf2db=2020.02.24=0 cyvcf2=0.10 numpy=1.16
``` 
and try running the project again?
(it seems to be a working combination in one of the installations)

Sergey

**Comment by matthdsm** [comment]
Hi Sergey,

Sorry, but this fix won't work for us. When we try to install this we get the following diff
```
  Package                Version  Build                            Channel                    Size
────────────────────────────────────────────────────────────────────────────────────────────────────
  Change:
────────────────────────────────────────────────────────────────────────────────────────────────────

  - platypus-variant     0.8.1.2  py27ha70a282_1                   installed                      
  + platypus-variant     0.8.1.2  py27hb763d49_0                   bioconda/linux-64          4 MB
  - vcf2db            2020.02.24  hdfd78af_1                       installed                      
  + vcf2db            2020.02.24  0                                bioconda/noarch           14 KB

  Upgrade:
────────────────────────────────────────────────────────────────────────────────────────────────────

  - numpy                 1.12.1  py27_blas_openblash1522bff_1001  installed                      
  + numpy                 1.16.5  py27h95a1406_0                   conda-forge/linux-64       4 MB
  - pandas                0.19.2  np112py27_1                      installed                      
  + pandas                0.24.2  py27hb3f55d8_0                   conda-forge/linux-64      11 MB

  Downgrade:
────────────────────────────────────────────────────────────────────────────────────────────────────

  - bcftools              1.10.2  h4f4756c_3                       installed                      
  + bcftools                 1.9  h68d8f2e_9                       bioconda/linux-64        682 KB
  - cyvcf2               0.30.11  py27h3ce6e29_0                   installed                      
  + cyvcf2               0.10.10  py27hbbd59f4_0                   bioconda/linux-64        697 KB
  - gsl                      2.6  he838d99_2                       installed                      
  + gsl                      2.5  h294904e_1                       conda-forge/linux-64     Cached
  - htslib                1.10.2  h78d89cc_0                       installed                      
  + htslib                   1.9  h244ad75_9                       bioconda/linux-64        Cached
  - lumpy-sv               0.3.1  py27hfbaaabd_0                   installed                      
  + lumpy-sv               0.3.0  ha52163a_3                       bioconda/linux-64          4 MB
  - mosdepth               0.2.9  hbeb723e_1                       installed                      
  + mosdepth               0.2.6  hfb13731_0                       bioconda/linux-64        207 KB
  - phylowgs            20181105  py27h40b51d9_5                   installed                      
  + phylowgs            20150714  py27_1                           bioconda/linux-64        930 KB
  - sambamba               0.8.0  h984e79f_0                       installed                      
  + sambamba               0.7.1  h148d290_2                       bioconda/linux-64          3 MB
  - samtools                1.10  h2e538c0_3                       installed                      
  + samtools                 1.7  1                                bioconda/linux-64        Cached
  - svtools                0.5.1  py_0                             installed                      
  + svtools                0.4.0  py27h24bf2e0_2                   bioconda/linux-64         81 KB
  - svtyper                0.7.1  py_0                             installed                      
  + svtyper                0.7.0  py27h24bf2e0_1                   bioconda/linux-64         66 KB
```

We're seeing downgrades for cyvcf2 and mosdepth (no idea why mosdepth is in there?) which would reintroduce some bugs which have since been fixed in the most recent versions.

Could you specify which issues you ran into when trying to install vcf2db under py3? Perhaps thats something that can be fixed at the source.

Thanks
MattHias

**Comment by naumenko-sa** [comment]
Hi @matthdsm and @mvheetve !

Thanks for testing!
I was lucky to reproduce and fix this issue with:

```
mamba install -n python2 numpy=1.16
```

the diff is quite small:
```
Package    Version  Build              Channel                    Size
──────────────────────────────────────────────────────────────────────────
 Upgrade:
──────────────────────────────────────────────────────────────────────────

 - numpy     1.11.3  py27he5ce36f_1207  installed                      
 + numpy     1.16.5  py27h95a1406_0     conda-forge/linux-64     Cached
 - pandas    0.19.2  np111py27_1        installed                      
 + pandas    0.24.2  py27hb3f55d8_0     conda-forge/linux-64      11 MB

 Downgrade:
──────────────────────────────────────────────────────────────────────────

 - svtools    0.5.1  py_0               installed                      
 + svtools    0.4.0  py27h24bf2e0_2     bioconda/linux-64        Cached
 - svtyper    0.7.1  py_0               installed                      
 + svtyper    0.7.0  py27h24bf2e0_1     bioconda/linux-64        Cached
```

Could you please confirm whether this pin works for you?

Sergey

ps. I will try to dig out what was the particular the vcf2db python3 issue, but no commitments on the fast switch, unfortunately.
We have a long term project, from which bcbio had originated initially, so 10 years already, with thousands of samples, 0.5T gemini databases (one db), dozens of databases, sophisticated annotations, active data mining. It is using vcf2db/gemini and we had troubles generating the databases with python3 vcf2db.

**Comment by matthdsm** [comment]
Upgrading the numpy version seems to have fixed the issue (for now)!
Thanks for the help. If you have any idea what causes the vcf2db py3 issues, please let me know.

Matthias

**Comment by mvheetve** [comment]
Hi Sergey,

analysis was completed with succes after the numpy upgrade. Thanks for the help!

Mattias
