### ISSUE TITLE
PureCN: if signatures aren't generated (too few somatic calls) they shouldn't be considered for upload

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#3560]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.8
- OS name and version (`lsb_release -ds`): Debian 10 (buster)

**To Reproduce**

If by any chance `deconstructSigs` fails to generate a proper signature (because there aren't enough somatic calls) when called from PureCN, the pipeline still considers the file to be done and adds it to the metadata. This ultimately causes a failure before the upload step, because `_add_meta` finds a file that does not exist.

Example:

```
Traceback (most recent call last):
  File "/opt/bcbio/1.2.8/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 54, in _setup_logging
    yield config
  File "/opt/bcbio/1.2.8/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 378, in multiqc_summary
    return ipython.zip_args(apply(multiqc.summary, *args))
  File "/opt/bcbio/1.2.8/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 82, in apply
    return object(*args, **kwargs)
  File "/opt/bcbio/1.2.8/anaconda/lib/python3.6/site-packages/bcbio/qc/multiqc.py", line 88, in summary
    data_json_final = _save_uploaded_data_json(samples, data_json, os.path.join(out_dir, "multiqc_data"))
  File "/opt/bcbio/1.2.8/anaconda/lib/python3.6/site-packages/bcbio/qc/multiqc.py", line 146, in _save_uploaded_data_json
    upload_path_mapping.update(get_all_upload_paths_from_sample(sample))
  File "/opt/bcbio/1.2.8/anaconda/lib/python3.6/site-packages/bcbio/upload/__init__.py", line 49, in get_all_upload_paths_from_sample
    for finfo in _get_files(sample):
  File "/opt/bcbio/1.2.8/anaconda/lib/python3.6/site-packages/bcbio/upload/__init__.py", line 64, in _get_files
    return _get_files_variantcall(sample)
  File "/opt/bcbio/1.2.8/anaconda/lib/python3.6/site-packages/bcbio/upload/__init__.py", line 192, in _get_files_variantcall
    return _add_meta(out, sample)
  File "/opt/bcbio/1.2.8/anaconda/lib/python3.6/site-packages/bcbio/upload/__init__.py", line 161, in _add_meta
    raise ValueError("Unexpected path for upload: %s" % x)
ValueError: Unexpected path for upload: {'path': '/home/incalci/lbeltrame/Ovaio/OV.4/OV4/work/structural/21556-A/purecn/21556-A_signatures.pdf', 'sample': '21556-A', 'type': 'pdf', 'ext': 'purecn-signatures', 'variantcaller': 'purecn'}
```

**Comment by lima1** [comment]
@lbeltrame , I think I changed the behavior in 1.22.0 that the file is always generated. It will just contain NAs for all signatures in case there are not enough mutations.

**Comment by naumenko-sa** [comment]
thanks @lima1 !

@lbeltrame thanks for reporting! 
Could you please confirm that it fails /not fails with the latest purecn as well? If so, I'd handle at the bcbio level.

SN

**Comment by lbeltrame** [comment]
The difference between the case where signatures are generated and when they aren't is here:

https://github.com/lima1/PureCN/blob/4f0616fb4e2875c5f64fd2b456b6b05fe5e4d8d7/inst/extdata/Dx.R#L187

One case generates a PDF file, which is tracked by bcbio, one does not (but bcbio searches for it anyway).

**Comment by lima1** [comment]
Oh, yes, the PDF is not generated, only the CSV file.

**Comment by naumenko-sa** [comment]
@lbeltrame here is the fix https://github.com/bcbio/bcbio-nextgen/pull/3563,
could you please test?

**Comment by lbeltrame** [comment]
Would that work with samples that have files, and samples that do not?

**Comment by naumenko-sa** [comment]
yes, in my test it works

**Comment by naumenko-sa** [comment]
there was another fix in this module - please check out + purecn2.0.1 fix.

**Comment by lbeltrame** [comment]
I'll see about getting bcbio updated in the HPC system I use.
