### ISSUE TITLE
FileNotFoundError during bulk RNA-seq. Bcbio is looking for Rscript in a non-existing r36 environment

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#3561]
Hello,

Using a one-week old fresh install of bcbio, I am running into the following error during a bulk RNA-seq run:

```
[2021-11-22T13:47Z] Converting Sailfish to Sleuth format.
[2021-11-22T13:47Z] Mon Nov 22 15:47:13 2021
[2021-11-22T13:47Z] [1] "Successfully converted sailfish / salmon results in /home/user/bcbio-runs/rna-seq/rna-seq-analysis/work/bcbiotx/tmpa8m318ao/RT3 to kallisto HDF5 format"
[2021-11-22T13:47Z] [1] TRUE
[2021-11-22T13:47Z] multiprocessing: detect_fusions
[2021-11-22T13:47Z] Resource requests: dexseq, express; memory: 10.00, 8.00; cores: 1, 1
[2021-11-22T13:47Z] Configuring 1 jobs to run, using 1 cores each with 10.00g of memory reserved for each job
[2021-11-22T13:47Z] Timing: estimate expression (single threaded)
[2021-11-22T13:47Z] Combining count files into /home/user/bcbio-runs/rna-seq/rna-seq-analysis/work/htseq-count/combined.counts.
[2021-11-22T13:47Z] tx2gene file /home/user/bcbio-runs/rna-seq/rna-seq-analysis/work/inputs/transcriptome/sacCer3-tx2gene.csv created from /home/user/bcbio/genomes/Scerevisiae/sacCer3/rnaseq/ref-transcripts.gtf.
[2021-11-22T13:47Z] Combining tx2gene CSV files.
[2021-11-22T13:47Z] Loading tximport.
[2021-11-22T13:47Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/user/bcbio/anaconda/lib/python3.7/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/user/bcbio/anaconda/lib/python3.7/site-packages/bcbio/provenance/do.py", line 85, in _do_run
    env=env,
  File "/home/user/bcbio/anaconda/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/user/bcbio/anaconda/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/bcbio/anaconda/envs/r36/bin/Rscript': '/home/user/bcbio/anaconda/envs/r36/bin/Rscript'
Traceback (most recent call last):
  File "/home/user/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/home/user/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/user/bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/home/user/bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/user/bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 264, in rnaseqpipeline
    samples = rnaseq.combine_files(samples)
  File "/home/user/bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/rnaseq.py", line 489, in combine_files
    tximport = load_tximport(data)
  File "/home/user/bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/rnaseq.py", line 556, in load_tximport
    do.run([rcmd, "--vanilla", "-e", render_string], f"Loading tximport.")
  File "/home/user/bcbio/anaconda/lib/python3.7/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/user/bcbio/anaconda/lib/python3.7/site-packages/bcbio/provenance/do.py", line 85, in _do_run
    env=env,
  File "/home/user/bcbio/anaconda/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/user/bcbio/anaconda/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/bcbio/anaconda/envs/r36/bin/Rscript': '/home/user/bcbio/anaconda/envs/r36/bin/Rscript'
```

There doesn't seem to be any `r36` env on my system at all. There is, instead, an `r35` env:

```
$ ls -l /home/user/bcbio/anaconda/envs/
total 52
drwxrwxr-x 13 user user 4096 nov 14 19:43 bwakit
drwxrwxr-x 16 user user 4096 nov 14 19:53 dv
drwxrwxr-x 20 user user 4096 nov 14 19:55 htslib1.10
drwxrwxr-x 17 user user 4096 nov 14 19:56 htslib1.11
drwxrwxr-x 14 user user 4096 nov 14 19:56 htslib1.12
drwxrwxr-x 15 user user 4096 nov 14 19:57 htslib1.12_py3.9
drwxrwxr-x 14 user user 4096 nov 14 19:57 htslib1.9
drwxrwxr-x 23 user user 4096 nov 14 20:00 java
drwxrwxr-x 23 user user 4096 nov 14 20:03 python2
drwxrwxr-x 24 user user 4096 nov 14 20:04 python3.6
drwxrwxr-x 16 user user 4096 nov 14 20:06 r35
drwxrwxr-x 17 user user 4096 nov 14 20:09 rbcbiornaseq
drwxrwxr-x 17 user user 4096 nov 14 20:10 samtools0
```

Rscript is present in the `r35` env:

```
$ ls /home/user/bcbio/anaconda/envs/r35/bin/Rscript 
/home/user/bcbio/anaconda/envs/r35/bin/Rscript
```

Why is bcbio looking for Rscript in a non-existing `r36` env?

**Comment by amizeranschi** [comment]
Update:

As suggested in https://github.com/bcbio/bcbio-nextgen/issues/3557, I tried reinstalling Bcbio again from scratch, but this didn't make any difference and I get the same error as above.

**Comment by amizeranschi** [comment]
Update 2:

Thanks to [this comment](https://github.com/bcbio/bcbio-nextgen/issues/3538#issuecomment-954422397), I've just realized that I never upgraded bcbio to the latest code from the development branch. After running

```
bcbio_nextgen.py upgrade -u development
```

the issue reported here went away. Will there be a new stable release anytime soon?

**Comment by naumenko-sa** [comment]
Thanks for the update @amizeranschi !
Sorry - the transition is never easy.
Yes, in the latest dev Rscript is pulled from the base `https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/pipeline/rnaseq.py#L535`
We are planning to release 1.2.9 before the NY.
Sergey
