### ISSUE TITLE
Files related to hg19 mirbase changed names - installation or upgrade crashes

### ISSUE THREAD

**Issue by pfpjs** [bcbio/bcbio-nextgen#3564]
Hi,

A recent update of cloudbiolinux updated the URLs of mirbase srnaseq files for hg19 and hg38. One of these files, here:

https://github.com/chapmanb/cloudbiolinux/blob/cbba4e96c2f45ccc5d57c96d310b7dbeb18db580/ggd-recipes/hg19/mirbase.yaml#L45

has changed name from `mirna_mature.txt.gz` to `mirna_context.txt.gz`. Both the old and the new files still exist under the new URL at https://www.mirbase.org/ftp/21/database_files/. I'm not sure of the significance and impact of this change. However, when updating a current bcbio-nextgen install, the GGD recipe still references the old name, here:

https://github.com/chapmanb/cloudbiolinux/blob/cbba4e96c2f45ccc5d57c96d310b7dbeb18db580/ggd-recipes/hg19/mirbase.yaml#L59

which causes the update process to crash:

```
2021-11-25 10:45:11 URL:https://www.mirbase.org/ftp/21/database_files/mirna_context.txt.gz [212869/212869] -> "mirna_context.txt.gz" [1]
Traceback (most recent call last):
  File "/path/to/bcbio/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/path/to/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 107, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/path/to/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 359, in upgrade_bcbio_data
    args.cores, ["ggd", "s3", "raw"])
  File "/path/to/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 354, in install_data_local
    _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
  File "/path/to/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 480, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/path/to/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 875, in _install_with_ggd
    ggd.install_recipe(os.getcwd(), env.system_install, recipe_file, gid)
  File "/path/to/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 31, in install_recipe
    _move_files(tmpdir, base_dir, recipe["recipe"]["full"]["recipe_outfiles"])
  File "/path/to/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 74, in _move_files
    (out_file, tmp_dir))
AssertionError: Did not find expected output file srnaseq/mirna_mature.txt.gz in /path/to/bcbio/genomes/Hsapiens/hg19/txtmp
```

Would you be able to fix this small issue? I didn't propose a PR as I don't do mirna analysis, so someone experienced with these files and analyses should review and update this recipe.

Thank you in advance, and thank you for all the work on bcbio-nextgen.

Best,
-- Paulo

**Comment by naumenko-sa** [comment]
Thanks for catching this, @pfpjs 

I think this is because we require `mirna_mature.txt.gz` in the output of the recipe:
https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/hg19/mirbase.yaml#L59

I've updated it to mature https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/hg19/mirbase.yaml#L45
at least it should run smoothly now.

**Comment by pfpjs** [comment]
Thank you @naumenko-sa, I confirm the issue is solved and I was able to upgrade successfully.

Best,
-- Paulo

**Comment by rollf** [comment]
Hi @naumenko-sa,

sorry, I can't comment on these files since I don't have experience with mirbase neither.
