### ISSUE TITLE
Failed to upgrade with --genome GRCh37

### ISSUE THREAD

**Issue by zetamui** [bcbio/bcbio-nextgen#3574]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.9a
- OS name and version (`lsb_release -ds`): Ubuntu 16.04.7 LTS

**To Reproduce**
Exact bcbio command you have used:
```
sudo /home/iblc3/Tools/bcbio/tools/bin/bcbio_nextgen.py upgrade -u development --genomes GRCh37
```

Your yaml configuration file:
```

```

**Log files (could be found in work/log)**
Please attach (10MB max):  `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.

Error message:
```
File ‘GRCh37-rnaseq-2015-12-01.tar.xz’ not modified on server. Omitting download.

xz: GRCh37-rnaseq-2015-12-01.tar.xz: Compressed data is corrupt
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
Traceback (most recent call last):
  File "/home/iblc3/Tools/bcbio/tools/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/home/iblc3/Tools/bcbio/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 107, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/home/iblc3/Tools/bcbio/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 359, in upgrade_bcbio_data
    args.cores, ["ggd", "s3", "raw"])
  File "/home/iblc3/MD/02_MDv3_pipeline/sample/work/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 354, in install_data_local
    _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
  File "/home/iblc3/MD/02_MDv3_pipeline/sample/work/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 480, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/home/iblc3/MD/02_MDv3_pipeline/sample/work/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 875, in _install_with_ggd
    ggd.install_recipe(os.getcwd(), env.system_install, recipe_file, gid)
  File "/home/iblc3/MD/02_MDv3_pipeline/sample/work/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"], system_install)
  File "/home/iblc3/MD/02_MDv3_pipeline/sample/work/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/home/iblc3/Tools/bcbio/anaconda/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/iblc3/Tools/bcbio/anaconda/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bash', '/home/iblc3/Tools/bcbio/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh']' returned non-zero exit status 2.
```

**Comment by naumenko-sa** [comment]
Hi @zetamui !

Thanks for reporting and sorry about the issue!
It is this recipe that failing: https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/GRCh37/transcripts.yaml

Could you please check these two commands in your environment?

```bash
wget https://s3.amazonaws.com/biodata/annotation/GRCh37-rnaseq-2015-12-01.tar.xz
xz -dc *-rnaseq-*.tar.xz | tar --no-same-owner -xpf -
```
It works in the two environments I have access to.

The xz is from bcbio (please make sure you are not using another xz).

```bash
$ which xz
[bcbio]/anaconda/bin/xz
```

You may also check the file size:
 2021-12-07 15:39:25 (6.74 MB/s) - ‘GRCh37-rnaseq-2015-12-01.tar.xz’ saved [**2245386164**/2245386164]

Sergey

**Comment by zetamui** [comment]
> Hi @zetamui !
> 
> Thanks for reporting and sorry about the issue! It is this recipe that failing: https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/GRCh37/transcripts.yaml
> 
> Could you please check these two commands in your environment?
> 
> ```shell
> wget https://s3.amazonaws.com/biodata/annotation/GRCh37-rnaseq-2015-12-01.tar.xz
> xz -dc *-rnaseq-*.tar.xz | tar --no-same-owner -xpf -
> ```
> 
> It works in the two environments I have access to.
> 
> The xz is from bcbio (please make sure you are not using another xz).
> 
> ```shell
> $ which xz
> [bcbio]/anaconda/bin/xz
> ```
> 
> You may also check the file size: 2021-12-07 15:39:25 (6.74 MB/s) - ‘GRCh37-rnaseq-2015-12-01.tar.xz’ saved [**2245386164**/2245386164]
> 
> Sergey

I have checked these two commands, both works and the output to `which xz` is:

```
iblc3@Johnny-6:~/MD/02_MDv3_pipeline/sample/work$ which xz
/home/iblc3/Tools/bcbio/tools/bin/xz
```

Filesize is `2021-12-08 09:28:43 (2.72 MB/s) - ‘GRCh37-rnaseq-2015-12-01.tar.xz’ saved [2245386164/2245386164]`

**Comment by naumenko-sa** [comment]
thanks for checking! It looks like everything works as expected.

It might be a random connection error when downloading from s3, I also got it once.
I made wget a little tougher with `--random-wait --retry-connrefused`

Please try again! If it is still not working, you may just extract all these files to
`[bcbio]/genomes/Hsapiens/GRCh37/rnaseq` and make sure you have references in your
`[bcbio]/genomes/Hsapiens/GRCh37/seq/GRCh37-resources.yaml` :

```yaml
rnaseq:
  transcripts: ../rnaseq/ref-transcripts.gtf
  transcripts_mask: ../rnaseq/ref-transcripts-mask.gtf
  transcriptome_index:
    tophat: ../rnaseq/tophat/GRCh37_transcriptome.ver
  dexseq: ../rnaseq/ref-transcripts.dexseq.gff3
  refflat: ../rnaseq/ref-transcripts.refFlat
  rRNA_fa: ../rnaseq/rRNA.fa
```

**Comment by zetamui** [comment]
> ```yaml
> rnaseq:
>   transcripts: ../rnaseq/ref-transcripts.gtf
>   transcripts_mask: ../rnaseq/ref-transcripts-mask.gtf
>   transcriptome_index:
>     tophat: ../rnaseq/tophat/GRCh37_transcriptome.ver
>   dexseq: ../rnaseq/ref-transcripts.dexseq.gff3
>   refflat: ../rnaseq/ref-transcripts.refFlat
>   rRNA_fa: ../rnaseq/rRNA.fa
> ```

I have tried but still the same error. Then, I tried your suggestions downloading and extracting the GRCh37 rnaseq file and put in the folder as you have suggested. However, since the GRCh37 didn't go through the installation, it is still not usable and I got this error:

``
ValueError: Did not find genome build GRCh37 in bcbio installation: /home/iblc3/Tools/bcbio/galaxy/tool-data/sam_fa_indices.loc
```

**Comment by naumenko-sa** [comment]
Have you tried to repeat the genome install after unpacking the rnaseq files?

**Comment by zetamui** [comment]
> 


> 






> 


> 




> Have you tried to repeat the genome install after unpacking the rnaseq files? What about hg38 genome? Could you please try to install it?

I have tried, upgrade --genomes GRCh37 continues to have error:

```
File ‘GRCh37-rnaseq-2015-12-01.tar.xz’ not modified on server. Omitting download.

xz: GRCh37-rnaseq-2015-12-01.tar.xz: Compressed data is corrupt
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
Traceback (most recent call last):
  File "/home/iblc3/Tools/bcbio/tools/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/home/iblc3/Tools/bcbio/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 107, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/home/iblc3/Tools/bcbio/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 359, in upgrade_bcbio_data
    args.cores, ["ggd", "s3", "raw"])
  File "/home/iblc3/MD/02_MDv3_pipeline/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 354, in install_data_local
    _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
  File "/home/iblc3/MD/02_MDv3_pipeline/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 480, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/home/iblc3/MD/02_MDv3_pipeline/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 875, in _install_with_ggd
    ggd.install_recipe(os.getcwd(), env.system_install, recipe_file, gid)
  File "/home/iblc3/MD/02_MDv3_pipeline/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"], system_install)
  File "/home/iblc3/MD/02_MDv3_pipeline/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/home/iblc3/Tools/bcbio/anaconda/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/iblc3/Tools/bcbio/anaconda/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bash', '/home/iblc3/Tools/bcbio/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh']' returned non-zero exit status 2.
```

But upgrade --genomes hg38 successfully installed.

**Comment by naumenko-sa** [comment]
thanks for checking!

This is unfortunate that GRCh37 is not working: the recipes are very similar:
https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/GRCh37/transcripts.yaml
https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/hg38/transcripts.yaml

And GRCh37 works on the other system. 
I could only think that the incomplete file was downloaded on your system and cached, so you may try to reach out to network admins asking to drop it from the cache or give you an instruction on how to bypass the proxy.

On the bcbio side I can suggest installing your genome as a custom one:
https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#adding-custom-genomes
