### ISSUE TITLE
not writable error

### ISSUE THREAD

**Issue by dauss75** [bcbio/bcbio-nextgen#3576]
Hello,

I have installed a latest bcbio and have been getting an error. 
I don't see any permission issue of the temporary folder, but fgbio keeps failing. Without passing '-f' below, fgbio seems to be working fine. 

```bash
~/bcbio/tools/bin/fgbio \
-Xms750m -Xmx25480m -XX:+UseSerialGC \
--tmp-dir ~/work/bcbiotx/tmpck91_acm \
--async-io=true \
--compression=0 \
GroupReadsByUmi \
--edits=1 --min-map-q=1 -t RX -s adjacency \
-i ~/work/align/Sample1_S1_R1_001-sort.bam \
-f ~/work/bcbiotx/tmpck91_acm/Sample1_S1_R1_001-sort.family_size_histogram.tsv
```

[2021/12/08 15:19:35 | FgBioMain | Info] GroupReadsByUmi failed. Elapsed time: 0.02 minutes.
**Exception in thread "main" java.lang.AssertionError: assertion failed: Cannot write file because parent directory is not writable:** ~/work/bcbiotx/tmpck91_acm/Sample1_S1_R1_001-sort.family_size_histogram.tsv
        at scala.Predef$.assert(Predef.scala:282)
        at com.fulcrumgenomics.commons.io.IoUtil.assertCanWriteFile(Io.scala:153)
        at com.fulcrumgenomics.commons.io.IoUtil.assertCanWriteFile$(Io.scala:139)
        at com.fulcrumgenomics.util.Io.assertCanWriteFile(Io.scala:38)
        at com.fulcrumgenomics.umi.GroupReadsByUmi.$anonfun$execute$1(GroupReadsByUmi.scala:457)
        at com.fulcrumgenomics.umi.GroupReadsByUmi.$anonfun$execute$1$adapted(GroupReadsByUmi.scala:457)
        at scala.Option.foreach(Option.scala:437)
        at com.fulcrumgenomics.umi.GroupReadsByUmi.execute(GroupReadsByUmi.scala:457)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:110)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:86)
        at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:50)
        at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)

**Comment by naumenko-sa** [comment]
Hi @dauss75 !

The complete command is longer than that:
https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/ngsalign/postalign.py#L242,
so if fgbio can't write the diagram it should not be writing other tmp files as well.

I don't have much ideas here beyond:

```bash
readlink -f ~/work
ls -ld `readlink -f ~/work`
umask
```

Sergey

**Comment by dauss75** [comment]
Thanks Sergey,
You are right and I grabbed only a command causing the problem.  It turned out that it's not a fgbio related issue, but something has to do with ipython.  I looked at carefully a bcbio log file and found:

2021-12-08 15:07:11.760 [IPClusterStart] Looking for ipcluster_config in /scratch/NGS_Run_Data/Pipeline_Output_Data/QIAseq323/2020/12_DEC/QIAseq-123020-umi/work
/isilon/Illumina/prody/bcbio/anaconda/lib/python3.7/site-packages/IPython/paths.py:60: UserWarning: IPython dir '/scratch/NGS_Run_Data/Pipeline_Output_Data/QIAseq323/2020/12_DEC/QIAseq-123020-umi/work/log/ipython' **is not a writable location, using a temp directory.
  " using a temp directory.".format(ipdir))**

This is a first time seeing such warnings and I am looking into it, but if you have any insight, I'd be much appreciated.

Segun

**Comment by dauss75** [comment]
I tried without ipython and the problem is still there so my guess was wrong.

> [2021-12-09T18:00Z] [2021/12/09 13:00:05 | FgBioMain | Info] GroupReadsByUmi failed. Elapsed time: 0.02 minutes.
[2021-12-09T18:00Z] Exception in thread "main" java.lang.AssertionError: assertion failed: Cannot write file because parent directory is not writable: /scratch/NGS_Run_Data/Pipeline_Output_Data/QIAseq323/2020/12_DEC/QIAseq-123020-umi/work/bcbiotx/tmp7iw80408/MOL20-744629_S1_R1_001-sort.family_size_histogram.tsv
[2021-12-09T18:00Z]     at scala.Predef$.assert(Predef.scala:282)
[2021-12-09T18:00Z]     at com.fulcrumgenomics.commons.io.IoUtil.assertCanWriteFile(Io.scala:153)
[2021-12-09T18:00Z]     at com.fulcrumgenomics.commons.io.IoUtil.assertCanWriteFile$(Io.scala:139)
[2021-12-09T18:00Z]     at com.fulcrumgenomics.util.Io.assertCanWriteFile(Io.scala:38)
[2021-12-09T18:00Z]     at com.fulcrumgenomics.umi.GroupReadsByUmi.$anonfun$execute$1(GroupReadsByUmi.scala:457)
[2021-12-09T18:00Z]     at com.fulcrumgenomics.umi.GroupReadsByUmi.$anonfun$execute$1$adapted(GroupReadsByUmi.scala:457)
[2021-12-09T18:00Z]     at scala.Option.foreach(Option.scala:437)
[2021-12-09T18:00Z]     at com.fulcrumgenomics.umi.GroupReadsByUmi.execute(GroupReadsByUmi.scala:457)
[2021-12-09T18:00Z]     at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:110)
[2021-12-09T18:00Z]     at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:86)
[2021-12-09T18:00Z]     at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:50)
[2021-12-09T18:00Z]     at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)

**Comment by naumenko-sa** [comment]
Hi @dauss75 !

Re ipython not writable: it is a known one - sometimes you need to delete `work/log/ipython` if you are rerunning a failed run.

Re the scratch non-writable - I think it is a good puzzle for storage/cluster sysadmins. Isilon could be tricky. It looks like your bcbio instance is on one partition (isilon) and the run is on another (scratch). It is fine, just make sure your UIDs are synchonized across different partitions (and potentially different storage systems/filesystems). Also  you may check your umask.

Sorry - not many ideas here. You may also try running simple benchmarks which would created files and dirs on both storages to create a simple reproducible example for sysadmins.

Sergey
