### ISSUE TITLE
Problem installing sacCer3 genome data (snpEff) with bcbio 1.2.9

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#3594]
Hello,

I've installed Bcbio 1.2.9 from scratch and I am now trying to install the sacCer3 genome data, but it's not finding the snpEff data:

```
2021-12-17 00:22:07 (1,12 MB/s) - ‘sacCer3-rnaseq-2018-11-20_94.tar.xz’ saved [5456832/5456832]

Updating sacCer3 genome resources configuration
Installing snpEff database R64-1-1.86 in /home/user/bcbio-nextgen/genomes/Scerevisiae/sacCer3/snpeff
--2021-12-17 00:22:09--  https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_R64-1-1.86.zip
Resolving snpeff.blob.core.windows.net (snpeff.blob.core.windows.net)... 52.239.234.228
Connecting to snpeff.blob.core.windows.net (snpeff.blob.core.windows.net)|52.239.234.228|:443... connected.
HTTP request sent, awaiting response... 404 The specified blob does not exist.
2021-12-17 00:22:10 ERROR 404: The specified blob does not exist..

Traceback (most recent call last):
  File "/home/user/bcbio-nextgen/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/home/user/bcbio-nextgen/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 109, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/home/user/bcbio-nextgen/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 363, in upgrade_bcbio_data
    _upgrade_snpeff_data(galaxy_home, args, remotes)
  File "/home/user/bcbio-nextgen/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 440, in _upgrade_snpeff_data
    subprocess.check_call(["wget", "--no-check-certificate", "-c", "-O", dl_file, dl_url])
  File "/home/user/bcbio-nextgen/anaconda/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wget', '--no-check-certificate', '-c', '-O', 'snpEff_v5_0_R64-1-1.86.zip', 'https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_R64-1-1.86.zip']' returned non-zero exit status 8.
```

**Comment by naumenko-sa** [comment]
Thanks for reporting - you are the first one working in sacCer3 in bcbio1.2.9.

I've updated the snpeff.db version, please try again (you need to upgrade to the development first):
https://github.com/bcbio/bcbio-nextgen/blob/master/config/genomes/sacCer3-resources.yaml#L5

```bash
bcbio_nextgen.py upgrade -u development
bcbio_nextgen.py upgrade -u skip --genomes sacCer3
```

S

**Comment by amizeranschi** [comment]
Thanks a lot, Sergey. It worked alright now. It could be worth checking out the other installable genomes as well, in case there are any other situations such as this one.
