### ISSUE TITLE
ggd-run.sh returned non-zero exit status 255

### ISSUE THREAD

**Issue by gis-nlsim** [bcbio/bcbio-nextgen#3599]
I'm trying to install bcbio (27th Dec 2021), but am encountering this issue when installing the genome. Seek your help in this matter please. Thank you.

My command:
bcbio_nextgen.py upgrade -u skip --genomes GRCh37 --aligners bwa --aligners star

Writing to .uacRYK
Merging 221 temporary files
[E::bgzf_flush] File write failed (wrong size)
[merge_blocks] Error: cannot write to dbsnp-154.vcf.gz
Cleaning
Traceback (most recent call last):
  File "/bcbio/v129/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/bcbio/v129/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 109, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/bcbio/v129/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 361, in upgrade_bcbio_data
    args.cores, ["ggd", "s3", "raw"])
  File "/home/centos/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 354, in install_data_local
    _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
  File "/home/centos/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 480, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/home/centos/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 875, in _install_with_ggd
    ggd.install_recipe(os.getcwd(), env.system_install, recipe_file, gid)
  File "/home/centos/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"], system_install)
  File "/home/centos/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/bcbio/v129/anaconda/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/bcbio/v129/anaconda/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bash', '/bcbio/v129/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh']' returned non-zero exit status 255.

**Comment by gis-nlsim** [comment]
Apologies, I think it's because the disk ran out of space.

**Comment by gis-nlsim** [comment]
Hi, 
Turns out it's not due to disk space; hence re-opening the issue.
I ran the installation of genomes on a 11TB disk, and the error still shows up

Merging 221 temporary files
[E::bgzf_flush] File write failed (wrong size)
[merge_blocks] Error: cannot write to dbsnp-154.vcf.gz
Cleaning
Traceback (most recent call last):
  File "/bcbio/v129/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/bcbio/v129/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 109, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/bcbio/v129/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 361, in upgrade_bcbio_data
    args.cores, ["ggd", "s3", "raw"])
  File "/projects/install.bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 354, in install_data_local
    _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
  File "/projects/install.bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 480, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/projects/install.bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 875, in _install_with_ggd
    ggd.install_recipe(os.getcwd(), env.system_install, recipe_file, gid)
  File "/projects/install.bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"], system_install)
  File "/projects/install.bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/bcbio/v129/anaconda/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/bcbio/v129/anaconda/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bash', '/bcbio/v129/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh']' returned non-zero exit status 255.

**Comment by naumenko-sa** [comment]
Hi @gis-nlsim!
How much RAM do you have in the installation session?
SN

**Comment by gis-nlsim** [comment]
This is an R5A.4xLarge AWS instance with 128GB (not a cluster)

**Comment by naumenko-sa** [comment]
Unfortunately, I can't reproduce this issue, I've successfully installed GRCh37 reference with

```bash
bash-4.2$ which python3
/n/app/bcbio/1.2.9/anaconda/bin/python3
bash-4.2$ bcbio_nextgen.py upgrade -u skip --genomes GRCh37 --aligners bwa
Upgrading bcbio
Upgrading bcbio-nextgen data files
--2022-01-08 23:50:17--  https://github.com/chapmanb/cloudbiolinux/archive/master.tar.gz
Resolving github.com (github.com)... 140.82.114.4
```

dbsnp message:
```
Resolving ftp.ncbi.nih.gov (ftp.ncbi.nih.gov)... 165.112.9.229, 165.112.9.228, 2607:f220:41e:250::13, ...
Connecting to ftp.ncbi.nih.gov (ftp.ncbi.nih.gov)|165.112.9.229|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2925007 (2.8M) [application/x-gzip]
Saving to: ‘dbsnp-154-orig.vcf.gz.tbi’

dbsnp-154-orig.vcf.gz.tbi                                   100%[=========================================================================================================================================>]   2.79M  --.-KB/s    in 0.1s    

2022-01-09 02:15:15 (26.0 MB/s) - ‘dbsnp-154-orig.vcf.gz.tbi’ saved [2925007/2925007]

Writing to .vL8Hgy
Merging 221 temporary files
Cleaning
Done
Running GGD recipe: GRCh37 hapmap 3.3
```

and it continued till the finish:

```
  inflating: data/GRCh37.75/sequence.HSCHR6_MHC_SSTO.bin  
  inflating: data/GRCh37.75/sequence.X.bin  
  inflating: data/GRCh37.75/sequence.Y.bin  
  inflating: data/GRCh37.75/sequence.bin  
  inflating: data/GRCh37.75/snpEffectPredictor.bin  
 extracting: data/GRCh37.75/cytoBand.txt.gz  
bcbio-nextgen data upgrade complete.
Upgrade completed successfully.
```

The install took 5h (including STAR), session with 20G RAM, dbsnp processing step took 100GB of intermediate files, total install size 79G.

In your place, I would try to look at AWS freeze/timouts/runnig as nohup.
