### ISSUE TITLE
bin/bash:samtools command not found- hg19 somatic variant calling

### ISSUE THREAD

**Issue by Priyankanator** [bcbio/bcbio-nextgen#3602]
Hi,
I have been trying to run bcbio variant calling. while running the pipeline it gives error - 
Job <bcbio_nextgen.py project_1.yaml> was submitted from host <node153.hpc.local> by user <prawat> in cluster <pennhpc>.
Job was executed on host(s) <32*r94001>, in queue <denovo>, as user <prawat> in cluster <pennhpc>.
</home/prawat> was used as the home directory.
</project/rdrapkinlab/WGS_bcbio/config/FT_cell/config/project_1/config> was used as the working directory.
Started at Results reported on
Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
bcbio_nextgen.py project_1.yaml
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   509.33 sec.
    Max Memory :                                 141 MB
    Average Memory :                             108.71 MB
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Swap :                                   -
    Max Processes :                              6
    Max Threads :                                8
    Run time :                                   406 sec.
    Turnaround time :                            406 sec.

The output (if any) follows:

[2022-01-13T17:19Z] System YAML configuration: /project/rdrapkinlab/WGS_bcbio/galaxy/bcbio_system.yaml.
[2022-01-13T17:19Z] Locale set to en_US.utf8.
[2022-01-13T17:19Z] Resource requests: sambamba, samtools; memory: 4.00, 4.00; cores: 16, 16
[2022-01-13T17:19Z] Configuring 1 jobs to run, using 1 cores each with 4.00g of memory reserved for each job
[2022-01-13T17:19Z] Timing: organize samples
[2022-01-13T17:19Z] multiprocessing: organize_samples
[2022-01-13T17:19Z] Using input YAML configuration: /project/rdrapkinlab/WGS_bcbio/config/FT_cell/config/project_1/config/project_1.yaml
[2022-01-13T17:19Z] Checking sample YAML configuration: /project/rdrapkinlab/WGS_bcbio/config/FT_cell/config/project_1/config/project_1.yaml
[2022-01-13T17:19Z] Retreiving program versions from /project/rdrapkinlab/WGS_bcbio/manifest/python-packages.yaml.
[2022-01-13T17:19Z] Retreiving program versions from /project/rdrapkinlab/WGS_bcbio/manifest/r-packages.yaml.
[2022-01-13T17:19Z] Testing minimum versions of installed programs
[2022-01-13T17:19Z] Timing: alignment preparation
[2022-01-13T17:19Z] multiprocessing: prep_align_inputs
[2022-01-13T17:19Z] multiprocessing: disambiguate_split
[2022-01-13T17:19Z] Timing: alignment
[2022-01-13T17:19Z] multiprocessing: process_alignment
[W::hts_idx_load3] The index file is older than the data file: /project/rdrapkinlab/WGS_bcbio/config/FT_cell_lines_WGS/FT189.bam.bai
[2022-01-13T17:19Z] Index BAM file: FT189.bam
[2022-01-13T17:25Z] bamprep, remove extra contigs: T-ag_1
[2022-01-13T17:25Z] /bin/bash: samtools: command not found
[2022-01-13T17:25Z] /bin/bash: samtools: command not found
[2022-01-13T17:25Z] /bin/bash: samtools: command not found
[2022-01-13T17:25Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; samtools view -@ 1 -h /project/rdrapkinlab/WGS_bcbio/config/FT_cell/config/project_1/config/bcbiotx/tmpwu1b8ae2/FT189.bam chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22 chrX chrY | /project/rdrapkinlab/WGS_bcbio/anaconda/bin/python -c 'from bcbio.pipeline import cleanbam; cleanbam.fix_header("/project/rdrapkinlab/WGS_bcbio/genomes/Hsapiens/hg19/seq/hg19.fa")' | samtools view -@ 1 -u - | samtools addreplacerg -@ 1 -r '@RG\tID:T-ag_1\tPL:illumina\tPU:T-ag_1\tSM:T-ag_1' -m overwrite_all -O bam -o /project/rdrapkinlab/WGS_bcbio/config/FT_cell/config/project_1/config/bcbiotx/tmpwu1b8ae2/T-ag_1-noextras.bam -
/bin/bash: samtools: command not found
/bin/bash: samtools: command not found
/bin/bash: samtools: command not found
' returned non-zero exit status 127.
Running bcbio version: 1.2.9
global config: /project/rdrapkinlab/WGS_bcbio/config/FT_cell/config/project_1/config/bcbio_system.yaml
run info config: /project/rdrapkinlab/WGS_bcbio/config/FT_cell/config/project_1/config/project_1.yaml
Traceback (most recent call last):
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 133, in variant2pipeline
    samples = run_parallel("process_alignment", samples)
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 1048, in __call__
    if self.dispatch_one_batch(iterator):
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 866, in dispatch_one_batch
    self._dispatch(tasks)
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 784, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/bcbio/utils.py", line 59, in wrapper
    return f(*args, **kwargs)
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/bcbio/distributed/multitasks.py", line 128, in process_alignment
    return sample.process_alignment(*args)
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/sample.py", line 168, in process_alignment
    out_bam = cleanbam.remove_extracontigs(fastq1, data)
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/cleanbam.py", line 72, in remove_extracontigs
    do.run(cmd.format(**locals()), "bamprep, remove extra contigs: %s" % dd.get_sample_name(data))
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; samtools view -@ 1 -h /project/rdrapkinlab/WGS_bcbio/config/FT_cell/config/project_1/config/bcbiotx/tmpwu1b8ae2/FT189.bam chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22 chrX chrY | /project/rdrapkinlab/WGS_bcbio/anaconda/bin/python -c 'from bcbio.pipeline import cleanbam; cleanbam.fix_header("/project/rdrapkinlab/WGS_bcbio/genomes/Hsapiens/hg19/seq/hg19.fa")' | samtools view -@ 1 -u - | samtools addreplacerg -@ 1 -r '@RG\tID:T-ag_1\tPL:illumina\tPU:T-ag_1\tSM:T-ag_1' -m overwrite_all -O bam -o /project/rdrapkinlab/WGS_bcbio/config/FT_cell/config/project_1/config/bcbiotx/tmpwu1b8ae2/T-ag_1-noextras.bam -
/bin/bash: samtools: command not found
/bin/bash: samtools: command not found
/bin/bash: samtools: command not found
' returned non-zero exit status 127.
Please suggest how do I fix this..
Thanks

**Comment by naumenko-sa** [comment]
Hi @Priyankanator !

samtools is not found. Please make sure you have added both `bcbio/anaconda/bin` and `bcbio/tools/bin` to your PATH.
https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html

```bash
$ which samtools
/n/app/bcbio/1.2.9/anaconda/bin/samtools
```

A side note: it could be useful to organize bcbio projects according to the proposed structure:
https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html

SN

**Comment by Priyankanator** [comment]
Hi SN,
Thanks for replying. I figured that when I run this in my home directory, it runs smoothly but when running on cluster, it gives this error. 
Also, while running the pipeline for variant calling further, now I am getting this error -
Traceback (most recent call last):
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/bcbio/provenance/do.py", line 89, in _do_run
    line = s.stdout.readline().decode("utf-8", errors="replace")
KeyboardInterrupt

File "/project/rdrapkinlab/WGS_bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 154, in variant2pipeline
    samples = genotype.parallel_variantcall_region(samples, run_parallel)
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/bcbio/variation/genotype.py", line 208, in parallel_variantcall_region
    "vrn_file", ["region", "sam_ref", "config"]))
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/bcbio/distributed/split.py", line 35, in grouped_parallel_split_combine
    final_output = parallel_fn(parallel_name, split_args)
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 1061, in __call__
    self.retrieve()
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 940, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/multiprocessing/pool.py", line 651, in get
    self.wait(timeout)
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/multiprocessing/pool.py", line 648, in wait
    self._event.wait(timeout)
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

when I try to rerun, it will run again for 30min and then give same errors. 

Thanks
Priyanka

**Comment by naumenko-sa** [comment]
Hi @Priyankanator !

It looks like a keyboard interrupt (Ctrl+C) in terminal.
Are you running it in an interactive session or are you submitting a batch job?

SN
