### ISSUE TITLE
Python error when installing data

### ISSUE THREAD

**Issue by TingtingSsl2** [bcbio/bcbio-nextgen#3605]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.0.4
- OS name and version (`lsb_release -ds`):  BWH ERISONE server

**To Reproduce**
Exact bcbio command you have used:
```
bcbio_nextgen.py upgrade -u skip --genomes hg38 --aligners bwa
```

Your yaml configuration file:
```

```

**Log files (could be found in work/log)**
Please attach (10MB max):  `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.
Upgrading bcbio
Traceback (most recent call last):
  File "/apps/lib-osver/bcbio/1.0.4/anaconda/bin/bcbio_nextgen.py", line 215, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/apps/lib-osver/bcbio/1.0.4/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 69, in upgrade_bcbio
    _set_matplotlib_default_backend()
  File "/apps/lib-osver/bcbio/1.0.4/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 144, in _set_matplotlib_default_backend
    out_file.write(line)
  File "/apps/lib-osver/bcbio/1.0.4/anaconda/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/apps/lib-osver/bcbio/1.0.4/anaconda/lib/python2.7/site-packages/bcbio/distributed/transaction.py", line 75, in file_transaction
    _move_tmp_files(safe, orig)
  File "/apps/lib-osver/bcbio/1.0.4/anaconda/lib/python2.7/site-packages/bcbio/distributed/transaction.py", line 92, in _move_tmp_files
    _move_file_with_sizecheck(safe, orig)
  File "/apps/lib-osver/bcbio/1.0.4/anaconda/lib/python2.7/site-packages/bcbio/distributed/transaction.py", line 114, in _move_file_with_sizecheck
    open(tmp_file, 'wb').close()
IOError: [Errno 13] Permission denied: u'/apps/lib-osver/bcbio/1.0.4/anaconda/lib/python2.7/site-packages/matplotlib/mpl-data/matplotlibrc.bcbiotmp'

**Comment by naumenko-sa** [comment]
Hi @TingtingSsl2 

bcbio 1.0.4/python2.7 is not supported anymore. Please install the current version - 1.2.9/python3.7.
https://bcbio-nextgen.readthedocs.io/en/latest/contents/intro.html

Sergey
