### ISSUE TITLE
ModuleNotFoundError: No module named 'conda._vendor.auxlib' | bcbio version 1.2.9

### ISSUE THREAD

**Issue by golubnikova** [bcbio/bcbio-nextgen#3614]
Hi!

Thank you for your updated fast installation.
Unfortunately, I have a problem with `conda` when run the  `bcbio_nextgen_install.py`.

**Version info**
- bcbio version: 1.2.9
- OS name and version: ubuntu:18.04

**To Reproduce**
Exact bcbio command you have used:
```
ENV BCBIO_VERSION='1.2.9'
RUN cd "$SOFT" \
    && wget -q "https://github.com/bcbio/bcbio-nextgen/archive/refs/tags/v${BCBIO_VERSION}.tar.gz" -O "$SOFT/bcbio-nextgen-${BCBIO_VERSION}.tar.gz" \
    && tar -xzf "$SOFT/bcbio-nextgen-${BCBIO_VERSION}.tar.gz" \
    && mv "$SOFT/bcbio-nextgen-${BCBIO_VERSION}" "$SOFT/bcbio-nextgen-${BCBIO_VERSION}-src" \
    && cd "$SOFT/bcbio-nextgen-${BCBIO_VERSION}-src/scripts"
    && python3 bcbio_nextgen_install.py "$SOFT/bcbio-nextgen-${BCBIO_VERSION}" --tooldir="$SOFT" --nodata --mamba
```

**Log files**
[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/8023264/bcbio-nextgen-commands.log)

```
Traceback (most recent call last):
  File "/soft/bcbio-nextgen-1.2.9/anaconda/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/soft/bcbio-nextgen-1.2.9/anaconda/lib/python3.7/site-packages/mamba/mamba.py", line 53, in <module>
    from mamba.utils import get_index, to_package_record_from_subjson, _supplement_index_with_system
  File "/soft/bcbio-nextgen-1.2.9/anaconda/lib/python3.7/site-packages/mamba/utils.py", line 7, in <module>
    from .FastSubdirData import FastSubdirData
  File "/soft/bcbio-nextgen-1.2.9/anaconda/lib/python3.7/site-packages/mamba/FastSubdirData.py", line 23, in <module>
    from conda._vendor.auxlib.ish import dals
ModuleNotFoundError: No module named 'conda._vendor.auxlib'
Checking required dependencies
Installing isolated base python installation
Installing mamba
Installing conda-build
Installing bcbio-nextgen
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 304, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 50, in main
    bcbio = install_conda_pkgs(anaconda, args)
  File "bcbio_nextgen_install.py", line 114, in install_conda_pkgs
    subprocess.check_call([mamba_bin, "install", "--yes", "--only-deps", "bcbio-nextgen"], env=env)
  File "/usr/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/soft/bcbio-nextgen-1.2.9/anaconda/bin/mamba', 'install', '--yes', '--only-deps', 'bcbio-nextgen']' returned non-zero exit status 1.
```

**Comment by naumenko-sa** [comment]
Hi @golubnikova !

Thanks for reporting and sorry about the issue!

It seems that
https://github.com/bcbio/bcbio-nextgen/blob/master/scripts/bcbio_nextgen_install.py#L48, 
i.e. `mamba install conda-build`
started triggering the upgrade of python and downgrade of mamba:

```
- python                3.7.10  h12debd9_4            installed                      
+ python                3.7.12  hf930737_100_cpython  conda-forge/linux-64      57 MB
 - tk                    8.6.10  hbc83047_0            installed                      
 + tk                    8.6.11  h27826a3_1            conda-forge/linux-64       3 MB

  Downgrade:
─────────────────────────────────────────────────────────────────────────────────────────

  - mamba                 0.15.3  py37h7f483ca_0        installed                      
  + mamba                  0.1.2  py37h99015e2_0        conda-forge/linux-64     104 KB
```
hence the downstream issues.

It did not happen before in many installations since 1.2.9 release, hopefully, it will get resolved in mamba.

As a quick fix, I have pinned mamba version here:
https://github.com/bcbio/bcbio-nextgen/blob/master/scripts/bcbio_nextgen_install.py#L48

It seems to be working for me, could you please run it yourself?

Please note that you would need to download the dev version of the installation script:
```bash
wget https://raw.github.com/bcbio/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py
```
rather than extracting it from the 1.2.9 release tarball.

Sergey

**Comment by golubnikova** [comment]
@naumenko-sa, it works, thank you!
