### ISSUE TITLE
postprocessing of vcf file error - 

### ISSUE THREAD

**Issue by Priyankanator** [bcbio/bcbio-nextgen#3615]
Hi
I am running the variant calling pipeline with vardict and mutect2..After calling variants and during the annotation process  I get this error - 
[2022-02-09T12:12Z] Calculating variation effects for T-ag_1, vardict
[2022-02-09T12:28Z] Annotate VCF file: T-ag_1, vardict
[2022-02-09T12:30Z] Filtering for T-ag_1, vardict
[2022-02-09T12:30Z] Prioritization for T-ag_1, vardict
[2022-02-09T12:30Z] Uncaught exception occurred

Traceback (most recent call last):
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/project/rdrapkinlab/WGS_bcbio/anaconda/lib/python3.7/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /project/rdrapkinlab/WGS_bcbio/anaconda/bin/vcfanno -p 1 -lua /project/rdrapkinlab/WGS_bcbio/config/FT_cell/work/vardict/T-ag_1-effects-annotated-annotated-gemini-combine.lua  /project/rdrapkinlab/WGS_bcbio/config/FT_cell/work/vardict/T-ag_1-effects-annotated-annotated-gemini-combine.conf /project/rdrapkinlab/WGS_bcbio/config/FT_cell/work/vardict/T-ag_1-effects-annotated.vcf.gz |  bgzip -c > /project/rdrapkinlab/WGS_bcbio/config/FT_cell/work/bcbiotx/tmp4bx5xqyr/T-ag_1-effects-annotated-annotated-gemini.vcf.gz
=============================================
vcfanno version 0.3.3 [built with go1.16.5]
see: https://github.com/brentp/vcfanno
=============================================
vcfanno.go:116: found 69 sources from 7 files
vcfanno.go:157: falling back to non-bgzip
panic: runtime error: slice bounds out of range [28:27]
goroutine 5 [running]:
github.com/brentp/bix.NewCSI(0x86ff20, 0xc0001f6b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/brentp/go/go/pkg/mod/github.com/brentp/bix@v0.0.0-20190718140914-00aa7a7f205d/csi.go:122 +0x3a5
github.com/brentp/bix.New(0xc000026240, 0x52, 0xc005587f78, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/brentp/go/go/pkg/mod/github.com/brentp/bix@v0.0.0-20190718140914-00aa7a7f205d/bix.go:124 +0x12bf
github.com/brentp/vcfanno/api.(*Annotator).Setup.func1(0xc0001b5810, 0x7, 0x7, 0xc0027c10f0, 0x1, 0xc000026240, 0x52)
	/home/brentp/src/vcfanno/api/api.go:792 +0x231
created by github.com/brentp/vcfanno/api.(*Annotator).Setup
	/home/brentp/src/vcfanno/api/api.go:783 +0x170
' returned non-zero exit status 2.
What could be the reason ? I am running this on HPC cluster..

Thanks

**Comment by naumenko-sa** [comment]
Hi @Priyankanator !

What is your project yaml file? What kind of annotations were applied?

Sergey

**Comment by Priyankanator** [comment]
Hi Sergey,
Here is the project yaml file -
details:
- algorithm:
    aligner: false
    bam_clean: remove_extracontigs
    variantcaller: [vardict,mutect2]
  analysis: variant2
  description: T-ag_1
  files:
  - /project/rdrapkinlab/WGS_bcbio/config/FT_cell/input/FT189.bam
  genome_build: hg19
  metadata:
    phenotype: tumor
- algorithm:
    aligner: false
    bam_clean: remove_extracontigs
    variantcaller: [vardict,mutect2]
  analysis: variant2
  description: T-ag_2
  files:
  - /project/rdrapkinlab/WGS_bcbio/config/FT_cell/input/FT190.bam
  genome_build: hg19
  metadata:
    phenotype: tumor
- algorithm:
    aligner: false
    bam_clean: remove_extracontigs
    variantcaller: [vardict,mutect2]
  analysis: variant2
  description: T-ag_3
  files:
  - /project/rdrapkinlab/WGS_bcbio/config/FT_cell/input/FT194.bam
  genome_build: hg19
  metadata:
    phenotype: tumor
- algorithm:
    aligner: false
    bam_clean: remove_extracontigs
    variantcaller: [vardict,mutect2]
  analysis: variant2
  description: non-Tag_1
  files:
  - /project/rdrapkinlab/WGS_bcbio/config/FT_cell/input/FT237.bam
  genome_build: hg19
  metadata:
    phenotype: tumor
- algorithm:
    aligner: false
    bam_clean: remove_extracontigs
    variantcaller: [vardict,mutect2]
  analysis: variant2
  description: non-Tag_2
  files:
  - /project/rdrapkinlab/WGS_bcbio/config/FT_cell/input/FT240.bam
  genome_build: hg19
  metadata:
    phenotype: tumor
- algorithm:
    aligner: false
    bam_clean: remove_extracontigs
    variantcaller: [vardict,mutect2]
  analysis: variant2
  description: non-Tag_3
  files:
  - /project/rdrapkinlab/WGS_bcbio/config/FT_cell/input/FT246.bam
  genome_build: hg19
  metadata:
    phenotype: tumor
- algorithm:
    aligner: false
    bam_clean: remove_extracontigs
    variantcaller: [vardict,mutect2]
  analysis: variant2
  description: non-Tag_4
  files:
  - /project/rdrapkinlab/WGS_bcbio/config/FT_cell/input/FT282.bam
  genome_build: hg19
  metadata:
    phenotype: tumor
- algorithm:
    aligner: false
    bam_clean: remove_extracontigs
    variantcaller: [vardict,mutect2]
  analysis: variant2
  description: T-ag_4
  files:
  - /project/rdrapkinlab/WGS_bcbio/config/FT_cell/input/FT33TAG.bam
  genome_build: hg19
  metadata:
    phenotype: tumor
fc_name: project_1
upload:
  dir: /project/rdrapkinlab/WGS_bcbio/config/FT_cell/final

I used the variant2 pipeline and I think it is getting stuck while annotating with vcfanno..

Thanks
Priyanka

**Comment by naumenko-sa** [comment]
Hi @Priyankanator !

Thanks for providing more details!

We need to dig into this command:

```bash
/project/rdrapkinlab/WGS_bcbio/anaconda/bin/vcfanno \
-p 1 \
-lua /project/rdrapkinlab/WGS_bcbio/config/FT_cell/work/vardict/T-ag_1-effects-annotated-annotated-gemini-combine.lua  \
/project/rdrapkinlab/WGS_bcbio/config/FT_cell/work/vardict/T-ag_1-effects-annotated-annotated-gemini-combine.conf \
/project/rdrapkinlab/WGS_bcbio/config/FT_cell/work/vardict/T-ag_1-effects-annotated.vcf.gz |  bgzip -c > \
T-ag_1-effects-annotated-annotated-gemini.vcf.gz
```

Could you please try running it outside of bcbio, and provide your combine.lua and combine.conf?

Sergey

**Comment by Priyankanator** [comment]
Hi Sergey,
I ran the command and get the same results-
(base) [prawat@consign rdrapkinlab]$ /project/rdrapkinlab/WGS_bcbio/anaconda/bin/vcfanno \
> -p 1 \
> -lua /project/rdrapkinlab/WGS_bcbio/config/FT_cell/work/vardict/T-ag_1-effects-annotated-annotated-gemini-combine.lua  \
> /project/rdrapkinlab/WGS_bcbio/config/FT_cell/work/vardict/T-ag_1-effects-annotated-annotated-gemini-combine.conf \
> /project/rdrapkinlab/WGS_bcbio/config/FT_cell/work/vardict/T-ag_1-effects-annotated.vcf.gz |  bgzip -c > \
> T-ag_1-effects-annotated-annotated-gemini.vcf.gz

=============================================
vcfanno version 0.3.3 [built with go1.16.5]

see: https://github.com/brentp/vcfanno
=============================================
vcfanno.go:116: found 69 sources from 7 files
vcfanno.go:157: falling back to non-bgzip
panic: runtime error: slice bounds out of range [28:27]

goroutine 8 [running]:
github.com/brentp/bix.NewCSI(0x86ff20, 0xc0000ecb00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/brentp/go/go/pkg/mod/github.com/brentp/bix@v0.0.0-20190718140914-00aa7a7f205d/csi.go:122 +0x3a5
github.com/brentp/bix.New(0xc0000222a0, 0x52, 0xc003345f78, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/brentp/go/go/pkg/mod/github.com/brentp/bix@v0.0.0-20190718140914-00aa7a7f205d/bix.go:124 +0x12bf
github.com/brentp/vcfanno/api.(*Annotator).Setup.func1(0xc0057ec8c0, 0x7, 0x7, 0xc003114ac0, 0x1, 0xc0000222a0, 0x52)
	/home/brentp/src/vcfanno/api/api.go:792 +0x231
created by github.com/brentp/vcfanno/api.(*Annotator).Setup
/home/brentp/src/vcfanno/api/api.go:783 +0x170
[T-ag_1-effects-annotated-annotated-gemini-combine_conf.txt](https://github.com/bcbio/bcbio-nextgen/files/8111611/T-ag_1-effects-annotated-annotated-gemini-combine_conf.txt)
[T-ag_1-effects-annotated-annotated-gemini-combine_lua.txt](https://github.com/bcbio/bcbio-nextgen/files/8111613/T-ag_1-effects-annotated-annotated-gemini-combine_lua.txt)

I have attached the lua and conf file as in txt format.

Thanks 
Priyanka

**Comment by naumenko-sa** [comment]
Hi @Priyankanator !

My run finishes ok with a similar config and hg19 reference.
Not sure, why do you have gemini annotations is in your vcfanno? gemini is not specified in the yaml.
Are you providing the complete yaml?

If you want to use gemini annotations, you need to install gemini files:
 `bcbio_nextgen.py upgrade -u skip --genomes hg19 --datatarget gemini`
By default gemini annotations are off, to turn on: `tools_on: gemini`.

Sergey

**Comment by Priyankanator** [comment]
Hi Sergey,
I have provided complete yaml file. I was also not sure that why I have gemini annotations. I did also tried with tools on option and installed gemini files but still it is giving me the same error. 
Do you think it is vcfanno specific error as described in this page- 
https://github.com/brentp/vcfanno/issues/64

Thanks
Priyanka

**Comment by naumenko-sa** [comment]
No, I think it is not related. Could you please try to install gemini as outlined above?
