### ISSUE TITLE
IndexError: list index out of range while updating bcbio

### ISSUE THREAD

**Issue by prasundutta87** [bcbio/bcbio-nextgen#3627]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.9
- OS name and version (`lsb_release -ds`): Scientific Linux release 7.5 (Nitrogen)

**To Reproduce**
Exact bcbio command you have used:
```
bcbio_nextgen.py upgrade --tools --tooldir /gpfs/igmmfs01/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_tools/bin
```

Your yaml configuration file:
```

```

**Log files (could be found in work/log)**
Please attach (10MB max):  `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.

[pdutta@node2f24(eddie) bcbio_nextgen]$ bcbio_nextgen.py upgrade --tools --tooldir /gpfs/igmmfs01/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_tools/bin
Upgrading bcbio
Upgrading third party tools to latest versions
Reading packages from /gpfs/igmmfs01/eddie/aitman-lab/Prasun/bcbio_nextgen/tmpbcbio-install/cloudbiolinux/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml
Creating conda environment: python3.6

## Package Plan ##

  environment location: /gpfs/igmmfs01/eddie/aitman-lab/Prasun/conda/envs/python3.6

  added / updated specs:
    - nomkl
    - python=3.6

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_gnu
  ca-certificates    conda-forge/linux-64::ca-certificates-2021.10.8-ha878542_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.36.1-hea4e1c9_2
  libffi             conda-forge/linux-64::libffi-3.4.2-h7f98852_5
  libgcc-ng          conda-forge/linux-64::libgcc-ng-11.2.0-h1d223b6_13
  libgomp            conda-forge/linux-64::libgomp-11.2.0-h1d223b6_13
  libnsl             conda-forge/linux-64::libnsl-2.0.0-h7f98852_0
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-11.2.0-he4da1e4_13
  libzlib            conda-forge/linux-64::libzlib-1.2.11-h36c2ea0_1013
  ncurses            conda-forge/linux-64::ncurses-6.3-h9c3ff4c_0
  nomkl              conda-forge/noarch::nomkl-1.0-h5ca1d4c_0
  openssl            conda-forge/linux-64::openssl-1.1.1l-h7f98852_0
  python             conda-forge/linux-64::python-3.6.15-hb7a2778_0_cpython
  readline           conda-forge/linux-64::readline-8.1-h46c0cb4_0
  sqlite             conda-forge/linux-64::sqlite-3.37.0-h9cd32fc_0
  tk                 conda-forge/linux-64::tk-8.6.12-h27826a3_0
  xz                 conda-forge/linux-64::xz-5.2.5-h516909a_1
  zlib               conda-forge/linux-64::zlib-1.2.11-h36c2ea0_1013

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Traceback (most recent call last):
  File "/gpfs/igmmfs01/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_tools/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/exports/igmm/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_data/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 93, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/exports/igmm/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_data/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 510, in upgrade_thirdparty_tools
    cbl_conda.install_in(conda_bin, args.tooldir, package_yaml)
  File "/gpfs/igmmfs01/eddie/aitman-lab/Prasun/bcbio_nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 97, in install_in
    conda_envs = _create_environments(conda_bin, packages)
  File "/gpfs/igmmfs01/eddie/aitman-lab/Prasun/bcbio_nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 287, in _create_environments
    out[addenv] = [x for x in conda_envs if x.endswith("/%s" % addenv)][0]
IndexError: list index out of range
[pdutta@node2f24(eddie) bcbio_nextgen]$ bcbio_nextgen.py upgrade --tools
Upgrading bcbio
Upgrading third party tools to latest versions
Reading packages from /gpfs/igmmfs01/eddie/aitman-lab/Prasun/bcbio_nextgen/tmpbcbio-install/cloudbiolinux/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml
Creating conda environment: python3.6

## Package Plan ##

  environment location: /gpfs/igmmfs01/eddie/aitman-lab/Prasun/conda/envs/python3.6

  added / updated specs:
    - nomkl
    - python=3.6

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_gnu
  ca-certificates    conda-forge/linux-64::ca-certificates-2021.10.8-ha878542_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.36.1-hea4e1c9_2
  libffi             conda-forge/linux-64::libffi-3.4.2-h7f98852_5
  libgcc-ng          conda-forge/linux-64::libgcc-ng-11.2.0-h1d223b6_13
  libgomp            conda-forge/linux-64::libgomp-11.2.0-h1d223b6_13
  libnsl             conda-forge/linux-64::libnsl-2.0.0-h7f98852_0
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-11.2.0-he4da1e4_13
  libzlib            conda-forge/linux-64::libzlib-1.2.11-h36c2ea0_1013
  ncurses            conda-forge/linux-64::ncurses-6.3-h9c3ff4c_0
  nomkl              conda-forge/noarch::nomkl-1.0-h5ca1d4c_0
  openssl            conda-forge/linux-64::openssl-1.1.1l-h7f98852_0
  python             conda-forge/linux-64::python-3.6.15-hb7a2778_0_cpython
  readline           conda-forge/linux-64::readline-8.1-h46c0cb4_0
  sqlite             conda-forge/linux-64::sqlite-3.37.0-h9cd32fc_0
  tk                 conda-forge/linux-64::tk-8.6.12-h27826a3_0
  xz                 conda-forge/linux-64::xz-5.2.5-h516909a_1
  zlib               conda-forge/linux-64::zlib-1.2.11-h36c2ea0_1013

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Traceback (most recent call last):
  File "/gpfs/igmmfs01/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_tools/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/exports/igmm/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_data/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 93, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/exports/igmm/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_data/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 510, in upgrade_thirdparty_tools
    cbl_conda.install_in(conda_bin, args.tooldir, package_yaml)
  File "/gpfs/igmmfs01/eddie/aitman-lab/Prasun/bcbio_nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 97, in install_in
    conda_envs = _create_environments(conda_bin, packages)
  File "/gpfs/igmmfs01/eddie/aitman-lab/Prasun/bcbio_nextgen/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 287, in _create_environments
    out[addenv] = [x for x in conda_envs if x.endswith("/%s" % addenv)][0]
IndexError: list index out of range

**Comment by prasundutta87** [comment]
Closing this issue as I am performing a fresh install of the latest bcbio version (v1.2.9)
