### ISSUE TITLE
smoove issue while running structural variation pipeline

### ISSUE THREAD

**Issue by prasundutta87** [bcbio/bcbio-nextgen#3628]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.9
- OS name and version (`lsb_release -ds`): Scientific Linux release 7.5 (Nitrogen)

**To Reproduce**
Exact bcbio command you have used:
```
bcbio_nextgen.py ../config/NA12878-sv.yaml -n 16
```

Your yaml configuration file:
```
# Evaluate structural variant calling on NA12878 whole genome data,
# using validated deletions and insertions from the Genome in a Bottle svclassify project
# https://groups.google.com/d/msg/genome-in-a-bottle/v3EDUgZT0Xo/eGYsQlJk2JMJ
#
# See the bcbio-nextgen documentation for full instructions to
# run this analysis:
# https://bcbio-nextgen.readthedocs.org/en/latest/contents/testing.html#example-pipelines
---
details:
- algorithm:
    aligner: bwa
    align_split_size: 5000000
    exclude_regions: [lcr]
    recalibrate: false
    realign: false
    variantcaller: false
    tools_off: [collectsequencingartifacts]
    svcaller: [lumpy, manta, cnvkit, metasv, wham]
    svvalidate:
      DEL: ../input/giab-svclassify-deletions-2015-05-22.bed
      INS: ../input/giab-svclassify-insertions-2015-05-22.bed
  analysis: variant2
  description: NA12878
  files:
  - ../input/NA12878_50000_1.fastq
  - ../input/NA12878_50000_2.fastq
  genome_build: hg38
  metadata:
    batch: ceu
    sex: female
upload:
  dir: ../final

```

**Log files (could be found in work/log)**
Please attach (10MB max):  `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.
[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/8244693/bcbio-nextgen-commands.log)
[bcbio-nextgen-debug.log](https://github.com/bcbio/bcbio-nextgen/files/8244694/bcbio-nextgen-debug.log)

The issue I a getting is:

```
Traceback (most recent call last):
  File "/gpfs/igmmfs01/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_tools/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/gpfs/igmmfs01/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/exports/igmm/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_data/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/exports/igmm/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_data/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/exports/igmm/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_data/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 179, in variant2pipeline
    samples = structural.run(samples, run_parallel, "standard")
  File "/exports/igmm/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_data/anaconda/lib/python3.6/site-packages/bcbio/structural/__init__.py", line 228, in run
    for xs in to_process.values()))
  File "/exports/igmm/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_data/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/exports/igmm/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_data/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/exports/igmm/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_data/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1003, in __call__
    if self.dispatch_one_batch(iterator):
  File "/exports/igmm/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_data/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 834, in dispatch_one_batch
    self._dispatch(tasks)
  File "/exports/igmm/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_data/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 753, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/exports/igmm/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_data/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 201, in apply_async
    result = ImmediateResult(func)
  File "/exports/igmm/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_data/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 582, in __init__
    self.results = batch()
  File "/exports/igmm/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_data/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/exports/igmm/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_data/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/exports/igmm/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_data/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 59, in wrapper
    return f(*args, **kwargs)
  File "/exports/igmm/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_data/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 359, in detect_sv
    return structural.detect_sv(*args)
  File "/exports/igmm/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_data/anaconda/lib/python3.6/site-packages/bcbio/structural/__init__.py", line 254, in detect_sv
    for svdata in caller_fn(items):
  File "/exports/igmm/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_data/anaconda/lib/python3.6/site-packages/bcbio/structural/lumpy.py", line 175, in run
    lumpy_vcf, exclude_file = _run_smoove(full_bams, sr_bams, disc_bams, work_dir, items)
  File "/exports/igmm/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_data/anaconda/lib/python3.6/site-packages/bcbio/structural/lumpy.py", line 57, in _run_smoove
    smoove = config_utils.get_program("smoove", data)
  File "/exports/igmm/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_data/anaconda/lib/python3.6/site-packages/bcbio/pipeline/config_utils.py", line 191, in get_program
    return _get_program_cmd(name, pconfig, config, default)
  File "/exports/igmm/eddie/aitman-lab/Prasun/bcbio_nextgen/bcbio_data/anaconda/lib/python3.6/site-packages/bcbio/pipeline/config_utils.py", line 221, in wrap
    raise CmdNotFound(" ".join(map(repr, (fn.__name__ if six.PY3 else fn.func_name, name, pconfig, default))))
bcbio.pipeline.config_utils.CmdNotFound: '_get_program_cmd' 'smoove' {} None

```

Just to add, my bcbio tool directory is already present in .bashrc and when executing `which smoove`, I am getting the correct smoove path as well. I am trying to update the tools in case there is any tool version issue, but I am getting other errors which I have asked as another issue on this GitHub account.

**Comment by prasundutta87** [comment]
Closing this issue as I am performing a fresh install of the latest bcbio version (v1.2.9)
