### ISSUE TITLE
STAR index error upon installation

### ISSUE THREAD

**Issue by fardellas** [bcbio/bcbio-nextgen#3630]
I installed recently bcbio and successfully run RNAseq experiments with hisat2 as aligner. I tried to install STAR index using hg38 but I am getting the error below, yet I do not get the same message when I try to install STAR using hg19.

Any ideas?

--------------------------------
bcbio_nextgen.py upgrade -u skip --genomes hg38 --aligners star --cores 10

Upgrading bcbio
Upgrading bcbio-nextgen data files

List of genomes to get (from the config file at '{'genomes': [{'dbkey': 'hg38', 'name': 'Human (hg38) full', 'indexes': ['seq', 'twobit', 'bwa', 'hisat2'], 'annotations': ['transcripts', 'RADAR', 'rmsk', 'salmon-decoys', 'fusion-blacklist']}], 'genome_indexes': ['star', 'hisat2', 'minimap2', 'bowtie2', 'rtg'], 'install_liftover': False, 'install_uniref': False}'): Human (hg38) full
Moving on to next genome prep method after trying ggd
GGD recipe not available for hg38 star
Downloading genome from s3: hg38 star
Moving on to next genome prep method after trying s3
No pre-computed indices for hg38 star
Preparing genome hg38 with index star
hg38 detected, building a simple reference with no alts, decoys or HLA from /mnt/storage/user_data/fardellasach/MacinNASH/bcbio/stable/genomes/Hsapiens/hg38/seq/hg38.fa to /mnt/storage/user_data/fardellasach/MacinNASH/bcbio/stable/genomes/Hsapiens/hg38/seq/hg38-simple.fa.
Moving on to next genome prep method after trying raw
math domain error
Traceback (most recent call last):
  File "/mnt/storage/user_data/fardellasach/MacinNASH/bcbio/stable/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/mnt/storage/user_data/fardellasach/MacinNASH/bcbio/stable/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 109, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/mnt/storage/user_data/fardellasach/MacinNASH/bcbio/stable/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 361, in upgrade_bcbio_data
    args.cores, ["ggd", "s3", "raw"])
  File "/mnt/storage/user_data/fardellasach/MacinNASH/project1/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 354, in install_data_local
    _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
  File "/mnt/storage/user_data/fardellasach/MacinNASH/project1/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 495, in _prep_genomes
    .format(idx, gid, last_exc))
OSError: Could not prepare index star for hg38 by any method
Traceback (most recent call last):
  File "/mnt/storage/user_data/fardellasach/MacinNASH/project1/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 480, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/mnt/storage/user_data/fardellasach/MacinNASH/project1/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 519, in _prep_raw_index
    get_index_fn(idx)(env, ref_file)
  File "/mnt/storage/user_data/fardellasach/MacinNASH/project1/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 445, in decorator
    return func(*args, **kwargs)
  File "/mnt/storage/user_data/fardellasach/MacinNASH/project1/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 748, in _index_star
    Nbases = int(round(min(14, log(GenomeLength, 2) / 2 - 2), 0))
ValueError: math domain error
-------

**Comment by naumenko-sa** [comment]
Hi @fardellas !

I've installed hg38 STAR index recently. Could you please try more RAM or less cores, or both?

Sergey

**Comment by fardellas** [comment]
I couldn't solve it last year and continue to work with hg19. I tried recently to re-run hg38 with less cores as you suggested and I have the same issue, unfortunately.


`bcbio_nextgen.py upgrade -u skip --genomes hg38  --cores 4`

Upgrading bcbio
Upgrading bcbio-nextgen data files
List of genomes to get (from the config file at '{'genomes': [{'dbkey': 'hg38', 'name': 'Human (hg38) full', 'indexes': ['seq', 'twobit', 'bwa', 'hisat2'], 'annotations': ['transcripts', 'RADAR', 'rmsk', 'salmon-decoys', 'fusion-blacklist']}], 'genome_indexes': ['hisat2', 'minimap2', 'bowtie2', 'rtg', 'bwa', 'star'], 'install_liftover': False, 'install_uniref': False}'): Human (hg38) full
Moving on to next genome prep method after trying ggd
GGD recipe not available for hg38 star
Downloading genome from s3: hg38 star
Moving on to next genome prep method after trying s3
No pre-computed indices for hg38 star
Preparing genome hg38 with index star
hg38 detected, building a simple reference with no alts, decoys or HLA from /mnt/storage/user_data/fardellasach/MacinNASH/bcbio/stable/genomes/Hsapiens/hg38/seq/hg38.fa to /mnt/storage/user_data/fardellasach/MacinNASH/bcbio/stable/genomes/Hsapiens/hg38/seq/hg38-simple.fa.
Moving on to next genome prep method after trying raw
math domain error
Traceback (most recent call last):
  File "/mnt/storage/user_data/fardellasach/MacinNASH/bcbio/stable/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/mnt/storage/user_data/fardellasach/MacinNASH/bcbio/stable/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 109, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/mnt/storage/user_data/fardellasach/MacinNASH/bcbio/stable/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 361, in upgrade_bcbio_data
    args.cores, ["ggd", "s3", "raw"])
  File "/home/fardellasach/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 354, in install_data_local
    _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
  File "/home/fardellasach/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 495, in _prep_genomes
    .format(idx, gid, last_exc))
OSError: Could not prepare index star for hg38 by any method
Traceback (most recent call last):
  File "/home/fardellasach/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 480, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/home/fardellasach/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 519, in _prep_raw_index
    get_index_fn(idx)(env, ref_file)
  File "/home/fardellasach/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 445, in decorator
    return func(*args, **kwargs)
  File "/home/fardellasach/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 748, in _index_star
    Nbases = int(round(min(14, log(GenomeLength, 2) / 2 - 2), 0))
