### ISSUE TITLE
GATK AnnotatedInervalCodec Exception (GATK4)

### ISSUE THREAD

**Issue by gis-nlsim** [bcbio/bcbio-nextgen#3631]
Greetings,
I am running bcbio v1.2.9a, and I'm encountering this issue for all my samples. 
Seek your help in resolving this please. Thank you.

My yaml file is as attached.

[2022-03-16T08:24Z] org.broadinstitute.hellbender.exceptions.GATKException: Unable to automatically instantiate codec org.broadinstitute.hellbender.utils.codecs.AnnotatedIntervalCodec
[2022-03-16T08:24Z]     at org.broadinstitute.hellbender.engine.FeatureManager.getCandidateCodecsForFile(FeatureManager.java:529)
[2022-03-16T08:24Z]     at org.broadinstitute.hellbender.engine.FeatureManager.getCodecForFile(FeatureManager.java:476)
[2022-03-16T08:24Z]     at org.broadinstitute.hellbender.engine.FeatureDataSource.getCodecForFeatureInput(FeatureDataSource.java:397)
[2022-03-16T08:24Z]     at org.broadinstitute.hellbender.engine.FeatureDataSource.getFeatureReader(FeatureDataSource.java:373)
[2022-03-16T08:24Z]     at org.broadinstitute.hellbender.engine.FeatureDataSource.<init>(FeatureDataSource.java:319)
[2022-03-16T08:24Z]     at org.broadinstitute.hellbender.engine.FeatureDataSource.<init>(FeatureDataSource.java:291)
[2022-03-16T08:24Z]     at org.broadinstitute.hellbender.engine.VariantWalker.initializeDrivingVariants(VariantWalker.java:58)
[2022-03-16T08:24Z]     at org.broadinstitute.hellbender.engine.VariantWalkerBase.initializeFeatures(VariantWalkerBase.java:67)
[2022-03-16T08:24Z]     at org.broadinstitute.hellbender.engine.GATKTool.onStartup(GATKTool.java:726)
[2022-03-16T08:24Z]     at org.broadinstitute.hellbender.engine.VariantWalker.onStartup(VariantWalker.java:45)
[2022-03-16T08:24Z]     at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:138)
[2022-03-16T08:24Z]     at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
[2022-03-16T08:24Z]     at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
[2022-03-16T08:24Z]     at org.bro
[config.yaml.txt](https://github.com/bcbio/bcbio-nextgen/files/8260728/config.yaml.txt)
adinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
[2022-03-16T08:24Z]     at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
[2022-03-16T08:24Z]     at org.broadinstitute.hellbender.Main.main(Main.java:289)
[2022-03-16T08:24Z] 16:24:14.062 WARN  NativeLibraryLoader - Unable to load libgkl_compression.so from native/libgkl_compression.so (Disk quota exceeded)
[2022-03-16T08:24Z] Using GATK jar /scratch/users/astar/gis/simngl/apps/bcbio/anaconda/envs/java/share/gatk4-4.2.2.0-1/gatk-package-4.2.2.0-local.jar
[2022-03-16T08:24Z] Running:
[2022-03-16T08:24Z]     java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xms681m -Xmx3181m -XX:+UseSerialGC -Djava.io.tmpdir=/scratch/users/astar/gis/simngl/bcbioruns/TCGA-ESCA/runs/TCGA-L5-A4ON/bcbio_work/bcbiotx/tmpcscn29vc -jar /scratch/users/astar/gis/simngl/apps/bcbio/anaconda/envs/java/share/gatk4-4.2.2.0-1/gatk-package-4.2.2.0-local.jar FilterMutectCalls --reference /home/users/astar/gis/simngl/scratch/apps/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa --variant /scratch/users/astar/gis/simngl/bcbioruns/TCGA-ESCA/runs/TCGA-L5-A4ON/bcbio_work/mutect2/chr11/TCGA-L5-A4ON-chr11_112615613_128704003-raw.vcf.gz --output /scratch/users/astar/gis/simngl/bcbioruns/TCGA-ESCA/runs/TCGA-L5-A4ON/bcbio_work/bcbiotx/tmpcscn29vc/TCGA-L5-A4ON-chr11_112615613_128704003-raw-filt.vcf.gz
[2022-03-16T08:24Z] Uncaught exception occurred

**Comment by naumenko-sa** [comment]
Hi @gis-nlsim !

"Disk quota exceeded" - is it possible that the run is out of disk space?

SN

**Comment by gis-nlsim** [comment]
Hi Dr Naumenko,

Thanks for pointing that out, but I cleared up the disk space and reran with only a few samples; I’m still getting the same error, even without the disk quota issue, so I think this is a separate problem? Attached is the error log file. Thank you.


Sim Ngak Leng

**Comment by naumenko-sa** [comment]
@gis-nlsim I don't see the attachment - is it missing?
