### ISSUE TITLE
Error in bcbio installation

### ISSUE THREAD

**Issue by keenhl** [bcbio/bcbio-nextgen#3636]
I'm trying to do a new install of bcbio.  I am using the directions as on the following web page.

https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#install-bcbio-package-and-tools
python3 bcbio_nextgen_install.py /home/user/bcbio --tooldir=/home/user/bcbio/tools --nodata

I get the following error.  I guess this is a python related issue, but I really don't know where to start debugging.   Thanks for your help. 

Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 304, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 55, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/Users/keenhl/miniconda3/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/Users/keenhl/miniconda3/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Users/keenhl/miniconda3/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/keenhl/miniconda3/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Shared/Bioinformatics/data/keenhl/bcbio_1.2.9/anaconda/bin/bcbio_nextgen.py'

**Comment by keenhl** [comment]
I have a couple of updates.

I thought the conda python might be a problem, so I deactivated Conda, and edited PATH to remove reference to Conda.  However, I still get the same error referencing miniconda.

miniconda3/lib/python3.8/subprocess.py


FileNotFoundError: [Errno 2] No such file or directory: '/Shared/Bioinformatics/data/keenhl/bcbio_1.2.9/anaconda/bin/bcbio_nextgen.py'

This error is correct.  The file is not present.   What I don't understand is why it's not there.

**Comment by keenhl** [comment]
Here's some more information that might be helpful in debugging.  Thanks.

Installation

python3 bcbio_nextgen_install.py \
/Shared/Bioinformatics/data/keenhl/bcbio_1.2.9 \
--core 8 \
--isolate \
--tooldir=/Shared/Bioinformatics/data/keenhl/bcbio_1.2.9/tools \
--nodata

Some information about Python and conda

echo $PATH

/opt/sge/bin:/opt/sge/bin/lx-amd64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/Users/keenhl/.local/bin:/Users/keenhl/bin

echo $PYTHONPATH

(empty)

which python

/usr/bin/python

which -a conda

/usr/bin/which: no conda in (/opt/sge/bin:/opt/sge/bin/lx-amd64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/Users/keenhl/.local/bin:/Users/keenhl/bin)

conda info -e

# conda environments:
#
                         /Shared/Bioinformatics/data/bcbio_hk/stable/anaconda
                         /Shared/Bioinformatics/data/bcbio_hk/stable/anaconda/envs/dv
                         /Shared/Bioinformatics/data/bcbio_hk/stable/anaconda/envs/python2
                         /Shared/Bioinformatics/data/bcbio_hk/stable/anaconda/envs/python3
                         /Shared/Bioinformatics/data/bcbio_hk/stable/anaconda/envs/samtools0
                         /Shared/Bioinformatics/data/keenhl/bcbio/stable/anaconda
                         /Shared/Bioinformatics/data/keenhl/bcbio/stable/anaconda/envs/dv
                         /Shared/Bioinformatics/data/keenhl/bcbio/stable/anaconda/envs/python3
                         /Shared/Bioinformatics/data/keenhl/bcbio/stable/anaconda/envs/samtools0
                         /Shared/Bioinformatics/data/keenhl/bcbio_1.2.9/anaconda
                         /Shared/Bioinformatics/data/miniconda3/envs/mageckenv
base                  *  /Users/keenhl/miniconda3
mageckenv                /Users/keenhl/miniconda3/envs/mageckenv
mysam                    /Users/keenhl/miniconda3/envs/mysam
openjdk_11               /Users/keenhl/miniconda3/envs/openjdk_11
py27                     /Users/keenhl/miniconda3/envs/py27
py27b                    /Users/keenhl/miniconda3/envs/py27b
py36                     /Users/keenhl/miniconda3/envs/py36
r-reticulate             /Users/keenhl/miniconda3/envs/r-reticulate

which -a gsutil

/usr/bin/which: no gsutil in (/opt/sge/bin:/opt/sge/bin/lx-amd64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/Users/keenhl/.local/bin:/Users/keenhl/bin)

ls ~/.gsutil

metrics.log  tracker-files

**Comment by WimSpee** [comment]
I have the same error for a fresh bcbio installation.
```
File "bcbio_nextgen_install.py", line 304, in <module>
main(parser.parse_args(), sys.argv[1:])
File "bcbio_nextgen_install.py", line 55, in main
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/{my_user}/bcbio/bcbio/anaconda/bin/bcbio_nextgen.py':
```

Were you able to get the installation to work?

**Comment by keenhl** [comment]
Thanks. No, I still haven't gotten it to work.

**Comment by WimSpee** [comment]
ping @naumenko-sa  Could you please help?

**Comment by naumenko-sa** [comment]
Hi @keenhl  and @WimSpee !

Sorry for the delay.

I've just started the installation successfully. 

I think the issue is in multiple pythons/condas.

when you are looking for python, look for python3: `which python3`

I also have multiple bcbios/conda env. 

For the new installation I create `.bcbio_devel_profile`:

```
BCBIO_HOME=/n/data1/cores/bcbio/naumenko/bcbio_install_test1
PATH=${BCBIO_HOME}/anaconda/bin:${BCBIO_HOME}/tools/bin
PATH=${PATH}:/usr/local/bin:/usr/bin:/opt/puppetlabs/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/opt/dell/srvadmin/bin
export PATH
export CONDA_EXE=
export CONDA_PYTHON_EXE=
export CONDA_PREFIX=
export PYTHONPATH=
export PYTHONNOUSERSITE=True
```
Inject the env: `. .bcbio_devel_profile`
Load python:
```
ml gcc/6.2.0
ml python/3.6.0
```

Install bcbio:
```bash
python3 \
bcbio_nextgen_install.py \
/n/data1/cores/bcbio/naumenko/bcbio_install_test1 --tooldir=/n/data1/cores/bcbio/naumenko/bcbio_install_test1/tools \
--nodata```

First of all, bcbio downloads miniconda with python3.7.10 and goes from there. If your installation uses 3.8, it is the wrong python.

SN

**Comment by WimSpee** [comment]
Thank you for the information. Will try later or ask a colleague to install new bcbio with the above information.
