### ISSUE TITLE
Samtools problem in python2 env

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#3647]
Hi @naumenko-sa 

The Samtools error `error while loading shared libraries: libcrypto.so.1.0.0` also happens in the `python2` env from bcbio. It came up when I tried running a variant calling job using `svcaller: lumpy`:

```
[smoove] 2022/04/29 18:50:34 starting with version 0.2.8
[smoove] 2022/04/29 18:50:34 calculating bam stats for 1 bams
[smoove] 2022/04/29 18:50:41 done calculating bam stats
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
panic: exit status 127
goroutine 22855 [running]:
github.com/brentp/smoove/lumpy.check(...)
        /home/brentp/src/smoove/lumpy/lumpy.go:54
github.com/brentp/smoove/lumpy.remove_sketchy(0xc0003642a0, 0x6d, 0x3e8, 0x7ffc7e99c6b7, 0x66, 0x0, 0x0, 0xc00035a000, 0x867, 0x867, ...)
        /home/brentp/src/smoove/lumpy/depthfilter.go:232 +0x1825
github.com/brentp/smoove/lumpy.remove_sketchy_all.func1(0xc00012ae40, 0x3e8, 0x7ffc7e99c6b7, 0x66, 0x0, 0x0, 0xc00035a000, 0x867, 0x867, 0x1, ...)
        /home/brentp/src/smoove/lumpy/depthfilter.go:399 +0x231
created by github.com/brentp/smoove/lumpy.remove_sketchy_all
        /home/brentp/src/smoove/lumpy/depthfilter.go:397 +0x194
panic: exit status 127
goroutine 22977 [running]:
github.com/brentp/smoove/lumpy.check(...)
        /home/brentp/src/smoove/lumpy/lumpy.go:54
github.com/brentp/smoove/lumpy.remove_sketchy(0xc000364310, 0x6c, 0x3e8, 0x7ffc7e99c6b7, 0x66, 0x0, 0x0, 0xc00035a000, 0x867, 0x867, ...)
        /home/brentp/src/smoove/lumpy/depthfilter.go:232 +0x1825
github.com/brentp/smoove/lumpy.remove_sketchy_all.func1(0xc00012ae40, 0x3e8, 0x7ffc7e99c6b7, 0x66, 0x0, 0x0, 0xc00035a000, 0x867, 0x867, 0x1, ...)
        /home/brentp/src/smoove/lumpy/depthfilter.go:399 +0x231
created by github.com/brentp/smoove/lumpy.remove_sketchy_all
        /home/brentp/src/smoove/lumpy/depthfilter.go:397 +0x194
' returned non-zero exit status 2.
```

The reason I mentioned the `phyton2` env is because smoove seems to be installed there:

```
[a.mizeranschi@fep8 ~]$ which smoove
~/bcbio_nextgen/tools/bin/smoove
[a.mizeranschi@fep8 ~]$ ls -lh ~/bcbio_nextgen/tools/bin/smoove
lrwxrwxrwx. 1 a.mizeranschi profi 38 Jan 20 19:44 /export/home/ncit/external/a.mizeranschi/bcbio_nextgen/tools/bin/smoove -> ../../anaconda/envs/python2/bin/smoove
```

And, sure enough, the `samtools` vinary from that conda env is throwing the libcrypto the error:

```
[a.mizeranschi@fep8 ~]$ /export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/envs/python2/bin/samtools
/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/envs/python2/bin/samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

```
[a.mizeranschi@fep8 ~]$ bcbio_conda list -n python2 | grep samtools
samtools                  1.7                           1    bioconda
```

Does that Samtools version need to be so old? Would it be safe to upgrade it?

**Comment by amizeranschi** [comment]
Update: manually upgrading samtools and bcftools to v1.10 in that environment fixed Lumpy. Not sure if this will break any other functionalities, but I will mention here if it does.
