### ISSUE TITLE
Cellranger mkref

### ISSUE THREAD

**Issue by YuriPPAN** [bcbio/bcbio-nextgen#3648]
**Version info**
- Cellranger version (`cellranger4.0.0 --version`):

**Question**
Hi,
I use cellranger mkref to build the customized mm10 genome reference. But it always showes error like this:
```
May 03 20:17:47 ..... Started STAR run
['/home/panyiru/software/cellranger-4.0.0/bin/rna/mkref', '--genome=mm10', '--nthreads=20', '--fasta=Mus_musculus.GRCm39.dna.toplevel.fa', '--genes=Mus_musculus.GRCm39.106.filtered.gtf', '--ref-version=4.0.0']
Creating new reference folder at /home/panyiru/sc/mouse/mm10
...done

Writing genome FASTA file into reference folder...
...done

Computing hash of genome FASTA file...
...done

Indexing genome FASTA file...
...done

Writing genes GTF file into reference folder...
...done

Computing hash of genes GTF file...
...done

Writing genes index file into reference folder (may take over 10 minutes for a 3Gb genome)...
...done

Writing genome metadata JSON file into reference folder...
...done

Generating STAR genome index (may take over 8 core hours for a 3Gb genome)...
Traceback (most recent call last):
  File "/home/panyiru/software/cellranger-4.0.0/bin/rna/mkref", line 108, in <module>
    main()
  File "/home/panyiru/software/cellranger-4.0.0/bin/rna/mkref", line 105, in main
    referenceBuilder.build_reference()
  File "/home/panyiru/software/cellranger-4.0.0/lib/python/cellranger/reference.py", line 410, in build_reference
    new_genome_fasta, new_gene_gtf, num_threads=self.num_threads, mem_gb=self.mem_gb
  File "/home/panyiru/software/cellranger-4.0.0/lib/python/cellranger/reference.py", line 787, in index_reference_with_mem_gb
    limit_ram=limit_ram,
  File "/home/panyiru/software/cellranger-4.0.0/lib/python/cellranger/reference.py", line 827, in index_reference
    tk_subproc.check_call(args)
  File "/home/panyiru/software/cellranger-4.0.0/lib/python/tenkit/log_subprocess.py", line 43, in check_call
    return subprocess.check_call(*args, **kwargs)
  File "/home/panyiru/software/cellranger-4.0.0/external/anaconda/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['STAR', '--runMode', 'genomeGenerate', '--genomeDir', '/home/panyiru/sc/mouse/mm10/star', '--runThreadN', '20', '--genomeFastaFiles', '/home/panyiru/sc/mouse/mm10/fasta/genome.fa', '--sjdbGTFfile', '/home/panyiru/sc/mouse/mm10/genes/genes.gtf', '--limitGenomeGenerateRAM', '17179869184', '--genomeSAsparseD', '3', '--genomeSAindexNbases', '14', '--genomeChrBinNbits', '18']' returned non-zero exit status -4
```

I tried to find the same question from other people, I found there is a same question: https://www.biostars.org/p/394710/. But I tried to use --memgb=64, it didn't work.
Can anybody tell me what is wrong with this?
Thanks, Yuri

**Log files (could be found in work/log)**
[Log.txt](https://github.com/bcbio/bcbio-nextgen/files/8610538/Log.txt)

**Comment by naumenko-sa** [comment]
Hi @YuriPPAN !
Maybe https://github.com/10XGenomics/cellranger/issues is a better address for this question?
Sergey

**Comment by YuriPPAN** [comment]
Hi @naumenko-sa , I am a novice in github, thank you for your suggestion！
