### ISSUE TITLE
Installation issue conda error

### ISSUE THREAD

**Issue by hanaecarrie** [bcbio/bcbio-nextgen#3649]
Dear authors,
I am facing issue while attempting to install bcbio v129 on a HPC cluster with Linux RED HAT OS.
I have conda installed but I removed conda from my path to avoid conflict with bcbio installation.

How can I fix this issue?
Thank you in advance for your attention,
Kind regards,
Hanae

Here are the logs I get:

TypeError('not all arguments converted during string formatting')
TypeError('not all arguments converted during string formatting')
TypeError('not all arguments converted during string formatting')
TypeError('not all arguments converted during string formatting')
TypeError('not all arguments converted during string formatting')

Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 304, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 46, in main
    anaconda = install_mamba(anaconda, args)
  File "bcbio_nextgen_install.py", line 95, in install_mamba
    subprocess.check_call([anaconda["conda"], "install", "--yes", conda_bin])
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/path-to-my-folder/apps/bcbio/v129/anaconda/bin/conda', 'install', '--yes', 'conda']' returned non-zero exit status 1.

**Comment by naumenko-sa** [comment]
Hi @hanaecarrie !

It looks like your installation is not isolated - it uses system python (you can see /usr/lib64/python3.6) which should be something like /path/apps/bcbio/v129/anaconda/bin/python).

The solution might be to add /path-to-my-folder/apps/bcbio/v129/anaconda/bin/ to your PATH to have it before your system python.

S.
