### ISSUE TITLE
Error running bamsormadup (version 2.0.183): libmaus2.so.2: undefined symbol: _ZTIN6snappy4SinkE

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#3650]
We're seeing the following error when running the `bamsormadup` command during atac-seq pipeline when mapping reads with BWA:

```
libmaus2.so.2: undefined symbol: _ZTIN6snappy4SinkE
```

Some extra info:

```
test@server-bioinfo:~/Lab08-11$ which bamsormadup
/home/test/bcbio_nextgen_maria/anaconda/bin/bamsormadup
```

```
test@server-bioinfo:~/Lab08-11$ /home/test/bcbio_nextgen_maria/anaconda/bin/conda list | grep biobambam
biobambam                 2.0.183              h9f5acd7_1    bioconda
```

The error also appears when manually running the `bamsormadup` command:

```
test@server-bioinfo:~/Lab08-11$ bamsormadup
bamsormadup: symbol lookup error: /home/test/bcbio_nextgen_maria/anaconda/bin/../lib/libmaus2.so.2: undefined symbol: _ZTIN6snappy4SinkE
```

The full stack trace is below.

```
[2022-05-11T21:38Z] Timing: alignment
[2022-05-11T21:38Z] multiprocessing: prepare_sample
[2022-05-11T21:38Z] Preparing Rep1-500-I
[2022-05-11T21:38Z] Preparing Rep2-500-I
[2022-05-11T21:38Z] Preparing Rep3-500-I
[2022-05-11T21:38Z] multiprocessing: trim_sample
[2022-05-11T21:38Z] Skipping trimming of Rep1-500-I.
[2022-05-11T21:38Z] Skipping trimming of Rep2-500-I.
[2022-05-11T21:38Z] Skipping trimming of Rep3-500-I.
[2022-05-11T21:38Z] multiprocessing: disambiguate_split
[2022-05-11T21:38Z] multiprocessing: process_alignment
[2022-05-11T21:38Z] bwa mem alignment from fastq: Rep1-500-I
[2022-05-11T21:38Z] /home/maria/bcbio_nextgen/galaxy/../anaconda/bin/bamsormadup: symbol lookup error: /home/maria/bcbio_nextgen/anaconda/bin/../lib/libmaus2.so.2: undefined symbol: _ZTIN6snappy4SinkE
[2022-05-11T21:38Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/maria/bcbio_nextgen/anaconda/lib/python3.7/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/maria/bcbio_nextgen/anaconda/lib/python3.7/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && /home/maria/bcbio_nextgen/galaxy/../anaconda/bin/bwa mem -p  -c 250 -M -t 3  -R '@RG\tID:Rep1-500-I\tPL:illumina\tPU:Rep1-500-I\tSM:Rep1-500-I' -v 1 /home/maria/bcbio_nextgen/genomes/Scerevisiae/sacCer3/bwa/sacCer3.fa /home/maria/bcbio_runs/workflow_atac_seq/input/500-I-Rep1.fastq.gz   | /home/maria/bcbio_nextgen/galaxy/../anaconda/bin/bamsormadup inputformat=sam threads=3 tmpfile=/home/maria/bcbio_runs/workflow_atac_seq/input/atac_seq/work/bcbiotx/tmpxtpxse6b/Rep1-500-I-sort-sorttmp-markdup SO=coordinate indexfilename=/home/maria/bcbio_runs/workflow_atac_seq/input/atac_seq/work/bcbiotx/tmpxtpxse6b/Rep1-500-I-sort.bam.bai > /home/maria/bcbio_runs/workflow_atac_seq/input/atac_seq/work/bcbiotx/tmpxtpxse6b/Rep1-500-I-sort.bam
/home/maria/bcbio_nextgen/galaxy/../anaconda/bin/bamsormadup: symbol lookup error: /home/maria/bcbio_nextgen/anaconda/bin/../lib/libmaus2.so.2: undefined symbol: _ZTIN6snappy4SinkE
' returned non-zero exit status 127.
```

Any help with this would be much appreciated.

**Comment by amizeranschi** [comment]
Seems to be related (but not identical) to the issue reported here: https://github.com/bcbio/bcbio-nextgen/issues/3475

**Comment by amizeranschi** [comment]
Solved this for the time being by downgrading biobambam to v. 2.0.87, as seen here: https://github.com/bcbio/bcbio-nextgen/issues/3475

The issue persisted with v. 2.0.182, 2.0.177 etc.

**Comment by kokyriakidis** [comment]
I get the same error while running the RNASeq pipeline

**Comment by kokyriakidis** [comment]
@naumenko-sa 

I did not manage to remove biobambam and install the older version. The resolution takes forever. Can you please pin biobambam to v2.0.87?

**Comment by naumenko-sa** [comment]
thanks,  `mamba install biobambam=2.0.87` worked for me
Pinned in cloudbiolinux https://github.com/chapmanb/cloudbiolinux/blob/master/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml#L42
