### ISSUE TITLE
ggd-run.sh error when installing sacCer3 genome data: "can't open file '/bin/python': [Errno 2] No such file or directory"

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#3652]
Hello,

I'm getting the error from the title, when installing the `sacCer3` genome data in a freshly created Bcbio install. 

I'm guessing the sacCer3 ggd recipe needs fixing (https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/sacCer3/seq.yaml). It was last modified in 2019, in order to fix a previous issue (https://github.com/bcbio/bcbio-nextgen/issues/2758). 

Not sure why this error started happening now. Installing the genome data worked fine in bcbio v1.2.8. 

Here's what I'm running now:

```
## install bcbio-nextgen
## online documentation: https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html
cd ${HOME}
wget https://raw.githubusercontent.com/bcbio/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py
python3 bcbio_nextgen_install.py ${HOME}/bcbio-nextgen-TEST --tooldir=${HOME}/bcbio-nextgen-TEST/tools --nodata --mamba
## add the locations to the bcbio-nextgen dependency executables to the system's $PATH variable
export PATH=${HOME}/bcbio-nextgen-TEST/anaconda/bin:${HOME}/bcbio-nextgen-TEST/tools/bin:$PATH

## download genome data for sacCer3
bcbio_nextgen.py upgrade -u skip --genomes sacCer3 --aligners bwa --aligners bowtie2 --aligners hisat2 --aligners star
```

And this is the stack trace:

```
Saccharomyces_cerevisiae.R64-1-1.dna.toplevel.fa.gz                    100%[==========================================================================================================================================================================>]   3.61M  4.54MB/s    in 0.8s    

2022-05-18 10:03:14 (4.54 MB/s) - written to stdout [3786555]

/home/test/bcbio-nextgen-TEST/anaconda/envs/python2/bin/python: can't open file '/bin/python': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/test/bcbio-nextgen-TEST/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/home/test/bcbio-nextgen-TEST/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 109, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/home/test/bcbio-nextgen-TEST/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 361, in upgrade_bcbio_data
    args.cores, ["ggd", "s3", "raw"])
  File "/home/test/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 354, in install_data_local
    _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
  File "/home/test/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 480, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/home/test/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 875, in _install_with_ggd
    ggd.install_recipe(os.getcwd(), env.system_install, recipe_file, gid)
  File "/home/test/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"], system_install)
  File "/home/test/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/home/test/bcbio-nextgen-TEST/anaconda/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/test/bcbio-nextgen-TEST/anaconda/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bash', '/home/test/bcbio-nextgen-TEST/genomes/Scerevisiae/sacCer3/txtmp/ggd-run.sh']' returned non-zero exit status 2.
```

Below is the content of the `ggd-run.sh` script:

```
test@server-bioinfo:~$ cat /home/test/bcbio-nextgen-TEST/genomes/Scerevisiae/sacCer3/txtmp/ggd-run.sh
#!/bin/bash
set -eu -o pipefail
export PATH=/home/test/bcbio-nextgen-TEST/tools/bin:$PATH
RELEASE=94
BUILD=sacCer3
url=ftp://ftp.ensembl.org/pub/release-$RELEASE/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna.toplevel.fa.gz
mkdir -p seq
wget -O - --no-check-certificate https://gist.githubusercontent.com/chapmanb/a973558c2ec67a57eb4592c709ec0d09/raw/81d398fd7f3c901f89753d4f9f39c5a87d05a7fa/sacCer3.chrom.sizes | cut -f 1 > sacCer3.chrom.sizes
wget -c --no-check-certificate https://raw.githubusercontent.com/kwongj/sort-contigs/master/sort-contigs.py
wget --no-check-certificate -O - $url | gunzip -c | python -c 'import sys; [sys.stdout.write(">chr%s\n" % (l[1:].split()[0].replace("Mito", "M")) if l.startswith(">") else l) for l in sys.stdin]' > seq/$BUILD.fa.orig
`bcbio_conda env list | grep python2 | awk '{print $2"/bin/python"}'` sort-contigs.py seq/$BUILD.fa.orig --out seq/$BUILD.fa --fmt fasta --order sacCer3.chrom.sizes
samtools faidx seq/$BUILD.fa
picard -Xms1g -Xmx3g CreateSequenceDictionary REFERENCE=seq/$BUILD.fa OUTPUT=seq/$BUILD.dict SPECIES=$BUILD
```

Sure enough, there is no `/bin/python` on my system, there is only `/bin/python3`:

```
test@server-bioinfo:~$ ls -lh /bin/python
ls: cannot access '/bin/python': No such file or directory

test@server-bioinfo:~$ ls -lh /bin/python3
lrwxrwxrwx 1 root root 9 Mar 13  2020 /bin/python3 -> python3.8
```

**Comment by naumenko-sa** [comment]
@amizeranschi  please try again - I've made a fix

**Comment by naumenko-sa** [comment]
what is your 
```
which python2
echo $PATH
```
python2 should be there if you have installed bcbio and added bcbio/anaconda/bin:bcbio/tools/bin to PATH

**Comment by amizeranschi** [comment]
@naumenko-sa  In that case, it looks like the problem is there is no `python2` in our $PATH, although we do have the 2 bcbio bin directories:

```
test@server-bioinfo:~$ echo $PATH
/home/test/bcbio_nextgen_maria/anaconda/bin:/home/test/bcbio_nextgen_maria/tools/bin:/home/test/bcbio_nextgen_maria/extra3/bin:/home/test/bcbio_nextgen_maria/extra_conda2/bin:/sbin:/bin:/usr/bin:/usr/local/bin:/snap/bin
```

```
test@server-bioinfo:~$ ls -lh /home/test/bcbio_nextgen_maria/anaconda/bin/python2*
ls: cannot access '/home/test/bcbio_nextgen_maria/anaconda/bin/python2*': No such file or directory
```

```
test@server-bioinfo:~$ ls -lh /home/test/bcbio_nextgen_maria/tools/bin/python2*
ls: cannot access '/home/test/bcbio_nextgen_maria/tools/bin/python2*': No such file or directory
```

**Comment by marianastase0912** [comment]
Hi! I was able to install the genome by creating a symlink like this:
```   ln -s /bcbio/install/path/anaconda/envs/python2/bin/python  /bcbio/install/path/tools/bin/python2 ```

**Comment by naumenko-sa** [comment]
It is great that it has been solved, so we were able to install sacCer3 in the end?

cloudbiolinux when installing is making symlinks for envs into tools/bin:
`https://github.com/chapmanb/cloudbiolinux/blob/master/cloudbio/package/conda.py#L124`

If your installation did not finish successfully, other files could remain unlinked and some workflows may not be working.

**Comment by amizeranschi** [comment]
@naumenko-sa 

Thanks a lot for looking into this. 

> If your installation did not finish successfully, other files could remain unlinked and some workflows may not be working.

This is a very good point. What else should we be looking for in there? I can send you a list of the contents of our `bcbio/tools/bin`, in case this helps. 

As far as we could see from the logs, the installation DID finish successfully, we didn't get any errors, but the `python2` binary just didn't get linked into `bcbio/bools/bin` automatically, thus, we had to create it ourselves to solve the issue mentioned above.

Have you also tested this yourself, in a fresh install, and did you end up having `python2` symlinked in `bcbio/tools/bin`?

**Comment by naumenko-sa** [comment]
@amizeranschi 
You are right- python2 was not linked since it is not a package.
I added linking here - please give it a try
https://github.com/chapmanb/cloudbiolinux/blob/master/cloudbio/package/conda.py#L138

**Comment by amizeranschi** [comment]
I just noticed now that I forgot to reply here. This issue is fixed.
