### ISSUE TITLE
snpEff v4.3GRCh38.99.zip unavailable 

### ISSUE THREAD

**Issue by IBEXCluster** [bcbio/bcbio-nextgen#3658]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`):
```
$ bcbio_nextgen.py --version
1.2.9
```
- OS name and version (`lsb_release -ds`):
```
$ lsb_release -ds
"CentOS Linux release 7.9.2009 (Core)"
```

**To Reproduce**
Exact bcbio command you have used:
```
$ bcbio_nextgen.py upgrade -u skip --genomes hg38
Upgrading bcbio
Upgrading bcbio-nextgen data files
--2022-06-15 11:30:40--  https://github.com/chapmanb/cloudbiolinux/archive/master.tar.gz
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/refs/heads/master [following]
--2022-06-15 11:30:40--  https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/refs/heads/master
Resolving codeload.github.com (codeload.github.com)... 140.82.121.9
Connecting to codeload.github.com (codeload.github.com)|140.82.121.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘STDOUT’

     0K ........ ........ ........ ........ ........ ........ 3.50M
  3072K ........ ........ ........ .......                    2.76M=1.6s

2022-06-15 11:30:42 (3.17 MB/s) - written to stdout [5194304]

List of genomes to get (from the config file at '{'genomes': [{'dbkey': 'hg38', 'name': 'Human (hg38) full', 'indexes': ['seq', 'twobit', 'bwa', 'hisat2'], 'annotations': ['ccds', 'capture_regions', 'coverage', 'prioritize', 'dbsnp', 'hapmap_snps', '1000g_omni_snps', 'ACMG56_genes', '1000g_snps', 'mills_indels', '1000g_indels', 'clinvar', 'qsignature', 'genesplicer', 'effects_transcripts', 'varpon', 'vcfanno', 'viral', 'purecn_mappability', 'simple_repeat', 'af_only_gnomad', 'transcripts', 'RADAR', 'rmsk', 'salmon-decoys', 'fusion-blacklist', 'mirbase'], 'validation': ['giab-NA12878', 'giab-NA24385', 'giab-NA24631', 'platinum-genome-NA12878', 'giab-NA12878-remap', 'giab-NA12878-crossmap', 'dream-syn4-crossmap', 'dream-syn3-crossmap', 'giab-NA12878-NA24385-somatic', 'giab-NA24143', 'giab-NA24149', 'giab-NA24694', 'giab-NA24695']}], 'genome_indexes': ['bwa', 'rtg', 'star'], 'install_liftover': False, 'install_uniref': False}'): Human (hg38) full
Installing snpEff database GRCh38.99 in /ibex/sw/csi/bcbio-nextgen/1.2.5/el7.9_python2/bcbio/genomes/Hsapiens/hg38/snpeff
--2022-06-15 11:30:47--  https://snpeff.blob.core.windows.net/databases/v4_3/snpEff_v4_3_GRCh38.99.zip
Resolving snpeff.blob.core.windows.net (snpeff.blob.core.windows.net)... 52.239.234.228
Connecting to snpeff.blob.core.windows.net (snpeff.blob.core.windows.net)|52.239.234.228|:443... connected.
HTTP request sent, awaiting response... 404 The specified blob does not exist.
2022-06-15 11:30:48 ERROR 404: The specified blob does not exist..

Traceback (most recent call last):
  File "/ibex/sw/csi/bcbio-nextgen/1.2.5/el7.9_python2/bcbio/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/ibex/sw/csi/bcbio-nextgen/1.2.5/el7.9_python2/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 109, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/ibex/sw/csi/bcbio-nextgen/1.2.5/el7.9_python2/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 363, in upgrade_bcbio_data
    _upgrade_snpeff_data(galaxy_home, args, remotes)
  File "/ibex/sw/csi/bcbio-nextgen/1.2.5/el7.9_python2/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 440, in _upgrade_snpeff_data
    subprocess.check_call(["wget", "--no-check-certificate", "-c", "-O", dl_file, dl_url])
  File "/ibex/sw/csi/bcbio-nextgen/1.2.5/el7.9_python2/bcbio/anaconda/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wget', '--no-check-certificate', '-c', '-O', 'snpEff_v4_3_GRCh38.99.zip', 'https://snpeff.blob.core.windows.net/databases/v4_3/snpEff_v4_3_GRCh38.99.zip']' returned non-zero exit status 8.
```

Your yaml configuration file:
```

```

**Log files (could be found in work/log)**
Please attach (10MB max):  `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.

**Error description:** 
We are trying to update the SnpEff database and it's failed. Further, our bcbio workflow was failing with ''Could not find directory in config for snpeff'' error. Any advise to resolve this issues. 

Thanks and Regards,
Naga

**Comment by naumenko-sa** [comment]
@IBEXCluster : it seems that you are running bcbio1.2.5 which on snpEff4.3

@pengxiao78 : for this upgrade you need a fresh install of bcbio1.2.9.

**Comment by naumenko-sa** [comment]
BTW, I have just installed a fresh bcbio1.2.9 - no issues

**Comment by IBEXCluster** [comment]
Dear @naumenko-sa Thanks for your advise. Looks, I'm able to do the fresh install of bcbio 1.2.9. 
PS: The upgrade command from 1.2.5 to 1.2.9 gives us the issue.

**Comment by naumenko-sa** [comment]
@IBEXCluster : glad to hear you managed to install 1.2.9!
1.2.5 > 1.2.9 upgrade is not possible, fresh install needed.
let us know if you still see any issues!
