### ISSUE TITLE
Installing 1.2.9 error

### ISSUE THREAD

**Issue by pengxiao78** [bcbio/bcbio-nextgen#3661]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): installing 1.2.9
- OS name and version (`lsb_release -ds`): Linux 3.10.0-1160.66.1.el7.x86_64

**To Reproduce**
Exact bcbio command you have used:
```
When I install a fresh bcbio 1.2.9, using the following command,
python3 bcbio_nextgen_install.py [bcbio_path] --tooldir=[bcbio_tools_path] --nodata

I found the following error,

Checking required dependencies
Installing isolated base python installation
Installing conda
Installing conda-build
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 304, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 48, in main
    subprocess.check_call([anaconda[conda_bin], "install", "--yes", "conda-build", "mamba=0.15.3"])
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/.../bcbio/anaconda/bin/conda', 'install', '--yes', 'conda-build', 'mamba=0.15.3']' returned non-zero exit status 1.



```

Your yaml configuration file:
```
NA
```

**Log files (could be found in work/log)**
```
NA
```

**Comment by naumenko-sa** [comment]
Hi @pengxiao78 !

At this stage bcbio should use it own python, not the systems one.
Please try adding to the PATH (before running installation):

export PATH=[bcbio_path/anaconda/bin]:[bcbio_tools_path/bin]:$PATH

**Comment by pengxiao78** [comment]
I changed the PATH but still the same error...

Checking required dependencies
Installing isolated base python installation
Installing conda
Installing conda-build
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 304, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 48, in main
    subprocess.check_call([anaconda[conda_bin], "install", "--yes", "conda-build", "mamba=0.15.3"])
  File "/../bcbio/anaconda/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/.../bcbio/anaconda/bin/conda', 'install', '--yes', 'conda-build', 'mamba=0.15.3']' returned non-zero exit status 1.

**Comment by naumenko-sa** [comment]
https://github.com/bcbio/bcbio-nextgen/blob/master/scripts/bcbio_nextgen_install.py#L135

Could you please post your PATH and PYTHONPATH?

**Comment by pengxiao78** [comment]
For security purpose, I cannot put the actual full path but used /../ before the bcbio folder. I did not specifically set up PYTHONPATH.

export BCBIO_PATH=/.../bcbio
export PATH=/etc/alternatives/jre_1.7.0_openjdk/bin:$BCBIO_PATH/anaconda/bin:$BCBIO_PATH/bin:$BCBIO_PATH/tools/bin:$PATH

In previous error, I can see that the python3 path has been changed to the bcbio,

File "/../bcbio/anaconda/lib/python3.7/subprocess.py", line 363, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/.../bcbio/anaconda/bin/conda', 'install', '--yes', 'conda-build', 'mamba=0.15.3']' returned non-zero exit status 1.

**Comment by pengxiao78** [comment]
I tried both but the error persists...

**Comment by gabeng** [comment]
I have the same issue with a fresh install on a clean `ubuntu 18.04` image when using `conda` and omitting data (`--nodata`)
* Then I tried installing with the `--mamba` option. The installation proceeds further but fails at a later stage when trying to solve dependencies. 
* I also tried an initial installation without tools (omitting the `--tooldir` argument). This works, but when subsequently installing any tool configuration via `bcbio_nextgen.py upgrade --isolate --tooldir=/usr/local --tools --toolconf test.yaml`, the following error occurs:

```
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 93, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 510, in upgrade_thirdparty_tools
    cbl_conda.install_in(conda_bin, args.tooldir, package_yaml)
  File "/tmp/bcbio-nextgen-install/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 143, in install_in
    source_file = os.path.realpath(os.path.join(conda_envs.get(env_name), "bin", package))
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```


Has anyone been successful recently installing `bcbio 1.2.9`?

**Comment by naumenko-sa** [comment]
Hi @gabeng !

Yes, I've installed the 1.2.9. 

I think if you are installing with `--tooldir=/usr/local` that means that binaries will be installed in /usr/local/bin.
Do you have anything else in /usr/local/bin? bcbio installs nearly a 1000 symlinks to that dir, and having it in the PATH is crucial for bcbio runs. If you have some other binaries there, that could be the source of the issues. Isolating bcbio might be a good idea, since it has a lot of tools in it.

@pengxiao78 was your installation successful?

Sergey

**Comment by gabeng** [comment]
Hi @naumenko-sa,

I am actually installing into a plain `ubuntu 18.04` (also tested `20.04`) `docker` image. I know that you are no longer actively supporting a `docker` build (https://github.com/bcbio/bcbio_docker), but containerization is the only way for us to manage different tool environments.
I do not think that docker per se is the issue here. Changing the `tooldir` does not help.

**Comment by gabeng** [comment]
I just retried the `bcbio` installation in a clean `ubuntu 20.04` image and it succeeded. No idea why now and not 21 days ago.
I also understood why the upgrade command using a `tools.yaml` failed: some `conda` packages are hard coded in `cloudbiolinux` scripts, like this one: https://github.com/chapmanb/cloudbiolinux/blob/92543c4a7acc6550265d90f91cceb4481a448248/cloudbio/package/conda.py#L139
