### ISSUE TITLE
New installation error with current (21 Oct 2022) installer

### ISSUE THREAD

**Issue by fouriejoubert** [bcbio/bcbio-nextgen#3678]
Hi Folks

I am on RedHat 7.3 (can't update this server due to Lustre file system factors).

It is time to install a newer bcbio, but when running the currently available installation script, despite many attempts, I always end up getting the following. Any advice would be appreciated!

...
...
...
`typing_extensions  conda-forge/noarch::typing_extensions-4.1.1-pyha770c72_0 None
  unzip              conda-forge/linux-64::unzip-6.0-h7f98852_3 None
  urllib3            conda-forge/noarch::urllib3-1.26.11-pyhd8ed1ab_0 None
  werkzeug           conda-forge/noarch::werkzeug-0.16.1-py_0 None
  wrapt              conda-forge/linux-64::wrapt-1.13.1-py36h8f6f2f9_0 None
  yarl               conda-forge/linux-64::yarl-1.6.3-py36h8f6f2f9_2 None
  zipp               conda-forge/noarch::zipp-3.6.0-pyhd8ed1ab_0 None
  zlib               conda-forge/linux-64::zlib-1.2.13-h166bdaf_4 None
  zstd               conda-forge/linux-64::zstd-1.5.2-h6239696_4 None

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html

By downloading and using the cuDNN conda packages, you accept the terms and conditions of the NVIDIA cuDNN EULA -
  https://docs.nvidia.com/deeplearning/cudnn/sla/index.html

done
ERROR conda.core.link:_execute(735): An error occurred while installing package 'bioconda::deepvariant-1.4.0-py36hf3e76ba_0'.
Rolling back transaction: ...working... done

LinkError: post-link script failed for package bioconda::deepvariant-1.4.0-py36hf3e76ba_0
location of failed script: /apps/bcbio2022/anaconda/envs/dv/bin/.deepvariant-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout:
stderr: Your credentials are invalid. Please run
$ gcloud auth login

return code: 1

()

Traceback (most recent call last):
  File "/apps/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 73, in _install_env_pkgs
    "{py_version} {pkgs_str}".format(**locals()), shell=True)
  File "/apps/bcbio2022/anaconda/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/apps/bcbio2022/anaconda/bin/mamba install -q -y -n dv -c conda-forge -c bioconda python=3.6 'deepvariant'' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/bcbio2022/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/apps/bcbio2022/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 93, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/apps/bcbio2022/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 510, in upgrade_thirdparty_tools
    cbl_conda.install_in(conda_bin, args.tooldir, package_yaml)
  File "/apps/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 128, in install_in
    conda_pkg_list = _install_env_pkgs(env_name, env_packages, conda_bin, conda_envs, channels)
  File "/apps/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 78, in _install_env_pkgs
    "{py_version} {pkgs_str}".format(**locals()), shell=True)
  File "/apps/bcbio2022/anaconda/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'export BOTO_CONFIG=/ignoreglobal && /apps/bcbio2022/anaconda/bin/conda install -q -y -n dv -c conda-forge -c bioconda python=3.6 'deepvariant'' returned non-zero exit status 1.
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 306, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 55, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/apps/bcbio2022/anaconda/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/apps/bcbio2022/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/apps/bcbio2022/tools']' returned non-zero exit status 1.`

**Comment by fouriejoubert** [comment]
Many thanks!
