### ISSUE TITLE
bcbio 1.2.9 installation error in the HPC cluster

### ISSUE THREAD

**Issue by kimal999** [bcbio/bcbio-nextgen#3679]
Hi,

I'm having trouble with a new installation of bcbio 1.2.9. I have tried the instructions in https://github.com/bcbio/bcbio-nextgen/issues/3624 as well. Unfortunately, they didn't work and I didn't find any google account. Details are given below.

**Version info**
- bcbio version (`bcbio_nextgen.py --version`):1.2.9
- OS name and version (`lsb_release -ds`):Red Hat Enterprise Linux Server release 7.9

**To Reproduce**
Exact bcbio command you have used:
```
python3 bcbio_nextgen_install.py /rsrch3/scratch/user123/Tools/bcbio --tooldir=/rsrch3/scratch/user123/Tools/bcbio/tools --nodata --mamba
```

Error:
```
Traceback (most recent call last):
  File "/rsrch3/scratch/user123/Tools/bcbio/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/rsrch3/scratch/user123/Tools/bcbio/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 93, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/rsrch3/scratch/user123/Tools/bcbio/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 510, in upgrade_thirdparty_tools
    cbl_conda.install_in(conda_bin, args.tooldir, package_yaml)
  File "/rsrch3/scratch/user123/Tools/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 97, in install_in
    conda_envs = _create_environments(conda_bin, packages)
  File "/rsrch3/scratch/user123/Tools/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 297, in _create_environments
    out[addenv] = [x for x in conda_envs if x.endswith("/%s" % addenv)][0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/rsrch3/scratch/user123/Tools/bcbio_nextgen_install.py", line 307, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "/rsrch3/scratch/user123/Tools/bcbio_nextgen_install.py", line 56, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/risapps/rhel7/python/3.9.7/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/rsrch3/scratch/user123/Tools/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/rsrch3/scratch/user123/Tools/bcbio/tools']' returned non-zero exit status 1.
```

**Comment by naumenko-sa** [comment]
Hi @kimal999 !
Could you please demonstrate your PATH variable?
It looks like  `/risapps/rhel7/python/3.9.7/lib/python3.9/subprocess.py` was called, while
bcbio's python in `/rsrch3/scratch/user123/Tools/bcbio should be used.`

If so, setting 
bcbio_base=/rsrch3/scratch/user123/Tools/bcbio
export PATH=${bcbio_base}/anaconda/bin:${bcbio_base}/tools/bin:$PATH
could be helpful.

SN

**Comment by kimal999** [comment]
Hi @naumenko-sa,

Thank you very much for your reply. Even with bcbio's python, I get same error. 

```
Traceback (most recent call last):
  File "/rsrch3/scratch/user123/Tools/bcbio/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/rsrch3/scratch/user123/Tools/bcbio/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 93, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/rsrch3/scratch/user123/Tools/bcbio/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 510, in upgrade_thirdparty_tools
    cbl_conda.install_in(conda_bin, args.tooldir, package_yaml)
  File "/rsrch3/scratch/user123/Tools/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 97, in install_in
    conda_envs = _create_environments(conda_bin, packages)
  File "/rsrch3/scratch/user123/Tools/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 297, in _create_environments
    out[addenv] = [x for x in conda_envs if x.endswith("/%s" % addenv)][0]
IndexError: list index out of range
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 307, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 56, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/rsrch3/scratch/user123/Tools/bcbio/anaconda/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/rsrch3/scratch/user123/Tools/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/rsrch3/scratch/user123/Tools/bcbio/tools']' returned non-zero exit status 1.
```
Do you have any other suggestions? I have run bcbio 1.2.8 with no issues.

**Comment by kimal999** [comment]
I was able to install after commenting out the envs_dirs section from the .condarc file as suggested by #2969. 

Had problems with gemini and  bioconductor-all packages. So they were installed separately before restarting the installation.
