### ISSUE TITLE
installing from scratch using ether conda or mamba fails on perl version?

### ISSUE THREAD

**Issue by LeoWelter** [bcbio/bcbio-nextgen#3687]
problem, installing from scratch on our HPC fails  while trying to install a perl packages:
```
Encountered problems while solving:
  - package perl-encode-locale-1.05-pl526_6 requires perl >=5.26.2,<5.26.3.0a0, but none of the providers can be installed
```  
I have perl 5.26.3 as default on the system or 5.30.2 or 5.34.1 loadable as module.
thanks for any advice in advance

**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.9
- OS name and version (`lsb_release -ds`):Red Hat Enterprise Linux 8.4

**To Reproduce**
Exact bcbio command you have used:
```
/usr/local/bin/python3
 ../bcbio_nextgen_install.py \
	-u stable \
	--datatarget variation \
	--datatarget rnaseq \
	--cores 32 \
	--tooldir ${TOOLDIR} \
	--isolate \
	--distribution "centos" \
	--mamba \
	--genomes ${GENOMES} \
	${DATADIR}
```

Your yaml configuration file:
```

```

**Log files (could be found in work/log)**
Please attach (10MB max):  `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.

```
Checking required dependencies
Installing isolated base python installation
Installing mamba
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Retrieving notices: ...working... done
Installing conda-build

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.24.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['conda-build', 'mamba=0.24.0']

r/noarch                                                      No change
r/linux-64                                                    No change
pkgs/r/linux-64                                               No change
pkgs/r/noarch                                                 No change
ursky/linux-64                                                No change
ursky/noarch                                                  No change
pkgs/main/noarch                                   817.9kB @ 901.1kB/s  0.3s
bioconda/linux-64                                    4.5MB @   4.1MB/s  1.2s
pkgs/main/linux-64                                   5.0MB @   3.9MB/s  1.3s
conda-forge/noarch                                  10.3MB @   4.4MB/s  2.5s
bioconda/noarch                                      4.1MB @   1.6MB/s  1.7s
conda-forge/linux-64                                27.8MB @   4.0MB/s  7.3s

Pinned packages:
  - python 3.7.*


Transaction

  Prefix: /projects/0/lwc2020006/software/bcbio/1.2.9/data/anaconda

  All requested packages already installed

Installing bcbio-nextgen
--2022-11-21 14:05:48--  https://raw.githubusercontent.com/bcbio/bcbio-nextgen/master/requirements-conda.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20 [text/plain]
Saving to: ‘requirements-conda.txt’

requirements-conda.txt       100%[============================================>]      20  --.-KB/s    in 0s

2022-11-21 14:05:48 (2.23 MB/s) - ‘requirements-conda.txt’ saved [20/20]


                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.24.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['bcbio-nextgen']

r/linux-64                                                  Using cache
r/noarch                                                    Using cache
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
bioconda/linux-64                                           Using cache
bioconda/noarch                                             Using cache
pkgs/main/linux-64                                          Using cache
pkgs/main/noarch                                            Using cache
pkgs/r/linux-64                                             Using cache
pkgs/r/noarch                                               Using cache
ursky/noarch                                                  No change
ursky/linux-64                                                No change

Pinned packages:
  - python 3.7.*


Transaction

  Prefix: /projects/0/lwc2020006/software/bcbio/1.2.9/data/anaconda

  All requested packages already installed

Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Retrieving notices: ...working... done
Installing data and third party dependencies
Upgrading bcbio
--2022-11-21 14:06:42--  https://raw.githubusercontent.com/bcbio/bcbio-nextgen/master/requirements-conda.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20 [text/plain]
Saving to: ‘bcbio-update-requirements.txt’

bcbio-update-requirements.tx 100%[============================================>]      20  --.-KB/s    in 0s

2022-11-21 14:06:43 (424 KB/s) - ‘bcbio-update-requirements.txt’ saved [20/20]

Upgrade of bcbio-nextgen code complete.
Upgrading third party tools to latest versions
--2022-11-21 14:06:50--  https://github.com/chapmanb/cloudbiolinux/archive/master.tar.gz
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/refs/heads/master [following]
--2022-11-21 14:06:51--  https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/refs/heads/master
Resolving codeload.github.com (codeload.github.com)... 140.82.121.9
Connecting to codeload.github.com (codeload.github.com)|140.82.121.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘STDOUT’

     0K ........ ........ ........ ........ ........ ........ 6.55M
  3072K ........ ........ ........ .......                    32.6M=0.5s

2022-11-21 14:06:51 (9.56 MB/s) - written to stdout [5195149]

Reading packages from /gpfs/work2/0/lwc2020006/software/bcbio/1.2.9/tmpbcbio-install/cloudbiolinux/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml
Checking for problematic or migrated packages in default environment
Initalling initial set of packages for default environment with mamba
# Installing into conda environment default: age-metasv, atropos, bamtools, bamutil, bbmap, bcftools=1.13, bedops, bio-vcf, biobambam=2.0.87, bowtie, break-point-inspector, bwa, cage, cnvkit, coincbc, cramtools, deeptools, express, fastp, fastqc, geneimpacts, genesplicer, gffcompare, goleft, grabix, gsort, gsutil, gvcfgenotyper, h5py=3.3, hdf5=1.10, hisat2, hmmlearn, htseq, impute2, kallisto=0.46, kraken, ldc, macs2, maxentscan, mbuffer, minimap2, mintmap, mirdeep2, mirtop, moreutils, multiqc, multiqc-bcbio, ngs-disambiguate, novoalign, oncofuse, pandoc, parallel, pbgzip, peddy, pizzly, pythonpy, qsignature, rapmap, rtg-tools, sailfish, salmon, samblaster, samtools=1.13, scalpel, seq2c<2016, seqbuster, seqcluster, seqtk, sickle-trim, simple_sv_annotation, singlecell-barcodes, snap-aligner=1.0dev.97, snpeff=5.0, solvebio, spades, star=2.6.1d, stringtie, subread, survivor, tdrmapper, tophat-recondition, trim-galore, ucsc-bedgraphtobigwig, ucsc-bedtobigbed, ucsc-bigbedinfo, ucsc-bigbedsummary, ucsc-bigbedtobed, ucsc-bigwiginfo, ucsc-bigwigsummary, ucsc-bigwigtobedgraph, ucsc-bigwigtowig, ucsc-fatotwobit, ucsc-gtftogenepred, ucsc-liftover, ucsc-wigtobigwig, umis, vardict-java, vardict<=2015, variantbam, varscan, vcfanno, viennarna, vqsr_cnn, wham, ipyparallel=6.3.0, ipython-cluster-helper=0.6.4=py_0, ipython=7.29.0, ipython_genutils=0.2.0=py37_0, traitlets=4.3.3, anaconda-client, awscli, bzip2, ncurses, nodejs, p7zip, readline, s3gof3r, xz, perl-app-cpanminus, perl-archive-extract, perl-archive-zip, perl-bio-db-sam, perl-cgi, perl-dbi, perl-encode-locale, perl-file-fetch, perl-file-sharedir, perl-file-sharedir-install, perl-ipc-system-simple, perl-lwp-protocol-https, perl-lwp-simple, perl-sanger-cgp-battenberg, perl-statistics-descriptive, perl-time-hires, perl-vcftools-vcf, bioconductor-annotate, bioconductor-apeglm, bioconductor-biocgenerics, bioconductor-biocinstaller, bioconductor-biocstyle, bioconductor-biostrings, bioconductor-biovizbase, bioconductor-bsgenome.hsapiens.ucsc.hg19, bioconductor-bsgenome.hsapiens.ucsc.hg38, bioconductor-bubbletree, bioconductor-cn.mops, bioconductor-copynumber, bioconductor-degreport, bioconductor-deseq2, bioconductor-dexseq, bioconductor-dnacopy, bioconductor-genomeinfodb, bioconductor-genomeinfodbdata, bioconductor-genomeinfodbdata, bioconductor-genomicranges, bioconductor-iranges, bioconductor-limma, bioconductor-org.hs.eg.db, bioconductor-purecn>=2.0.1, bioconductor-rhdf5, bioconductor-rtracklayer, bioconductor-rtracklayer, bioconductor-summarizedexperiment, bioconductor-titancna, bioconductor-txdb.hsapiens.ucsc.hg19.knowngene, bioconductor-txdb.hsapiens.ucsc.hg38.knowngene, bioconductor-tximport, bioconductor-vsn, r-base=4.1.1=hb67fd72_0, r-chbutils, r-deconstructsigs, r-devtools, r-dplyr, r-dt, r-ggdendro, r-ggplot2, r-ggrepel, r-gplots, r-gsalib, r-janitor, r-knitr, r-optparse, r-pheatmap, r-plyr, r-pscbs, r-reshape, r-rmarkdown, r-rsqlite, r-sleuth, r-snow, r-stringi, r-tidyverse, r-viridis, r-wasabi, r=4.1=r41hd8ed1ab_1004, xorg-libxt
Encountered problems while solving:
  - package perl-encode-locale-1.05-pl526_6 requires perl >=5.26.2,<5.26.3.0a0, but none of the providers can be installed

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... cdfailed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... ^[[A^[[A^[[A






Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
```
```

Your yaml configuration file:
```

```

**Log files (could be found in work/log)**
Please attach (10MB max):  `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.

**Comment by dnbuckley** [comment]
I have also encountered this problem.

**Comment by amizeranschi** [comment]
Same issue for me: https://github.com/bcbio/bcbio-nextgen/issues/3686

@naumenko-sa any clue what's going on?

It would be great to bring back support for creating Docker images, given all these recurrent Conda issues for new installs.

**Comment by naumenko-sa** [comment]
Hi @amizeranschi !
Sorry for the delay: I am refactoring the whole installation script to address the install issues.
SN

**Comment by gabeng** [comment]
I was very fond of the strategy from `bcbio_docker`: using a focused, compact `tool.yaml` config file that installs only a small subset of the full swiss-army knife collection. This avoids the typical dependency hell of `conda`, given that many tools in the standard installation seem to be unused or outdated.
https://github.com/bcbio/bcbio_docker/blob/19369dde53fe40e624b1086d19570b3024929567/Dockerfile.tools#L13

Will you be going in that direction, @naumenko-sa?

**Comment by naumenko-sa** [comment]
Hi @LeoWelter, @dnbuckley, @amizeranschi !

It looks like the perl related issue was due to 
https://github.com/chapmanb/cloudbiolinux/blob/master/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml#L181

My install command:
.bcbio_devel_profie:

```
BCBIO_HOME=/path-tobcbio_install_test2
PATH=${BCBIO_HOME}/anaconda/bin:${BCBIO_HOME}/tools/bin
PATH=${PATH}:/home/user.aspera/connect/bin:/usr/local/bin:/usr/bin:/opt/puppetlabs/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/opt/dell/srvadmin/bin
export PATH
export CONDA_EXE=
export CONDA_PYTHON_EXE=
export CONDA_PREFIX=
export PYTHONPATH=
# don't add ~/.local to PYTHONPATH
export PYTHONNOUSERSITE=True
```

```bash
. .bcbio
$ which python3
/usr/bin/python3
$ python3 bcbio_nextgen_install.py /path-to/bcbio_install_test2 --tooldir=/path-to/bcbio_install_test2/tools --mamba --nodata
```
(please note --nodata installation, install data separately)

Please give it a try!

It passes the perl issue for me and installs all environments down to python3.6:
```
# Installing into conda environment python3.6: bowtie2, crossmap, cufflinks, htslib=1.7, optitype, pandas=0.25.3, pyloh, pysam=0.15.4, razers3, samtools=1.7, vt=2015.11.10=he941832_3
Encountered problems while solving:
  - package libsqlite-3.40.0-h753d276_0 requires libzlib >=1.2.13,<1.3.0a0, but none of the providers can be installed
```

I am working to untangle this one, but you are also invited to make a contribution!

I'd also call the community to be more active in solving such bugs: the perl one wasn't too complicated.
The way to debug them:
- create a python3.7.10 conda env (python3.7.10 is a default python in base) (or just use one from the interrupted installation)
- try to install packages which are reported in a conflict
- in this case, you'd find that one conda/perl package is deprecated and pushes perl version down, while other packages require newer perl, hence the conflict. the deprecated perl package is replaced with a new one, so we need to update our conda specification
- test and describe the solution, make a PR.
 
In this case, I also removed battenberg, since we are also using the frozen version of it from some time ago, and it pushes perl down. The battenberg (for subclones and CNV in cancer data) is a little subproject - one would need to have proper data to test the new battenberg, incorporate it into bcbio, update installation script.

SN

**Comment by mhclev27** [comment]
I also get a conflict during installation. This is not resolved with mamba and occurs on a no-data installation. Any recommendations to install on an HPC to avoid this conflict?

```

Retrieving notices: ...working... done
Encountered problems while solving:
  - package libsqlite-3.47.0-hadc24fc_1 requires libzlib >=1.3.1,<2.0a0, but none of the providers can be installed

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed
Upgrading bcbio
Upgrade of bcbio-nextgen code complete.
Upgrading third party tools to latest versions
Reading packages from /project2/nchevrier/software5/bcbio/tmpbcbio-install/cloudbiolinux/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml
Checking for problematic or migrated packages in default environment
# Installing into conda environment default: age-metasv, atropos, bamtools, bamutil, bbmap, bcftools=1.13, bedops, bio-vcf, biobambam=2.0.87, bowtie, break-point-inspector, bwa, cage, cnvkit, coincbc, cramtools, deeptools, express, fastp, fastqc=0.11.9, geneimpacts, genesplicer, gffcompare, goleft, grabix, gsort, gsutil, gvcfgenotyper, h5py=3.3, hdf5=1.10, hisat2, hmmlearn, htseq, impute2, kallisto=0.46, kraken, ldc, macs2, maxentscan, mbuffer, minimap2, mintmap, mirdeep2, mirtop, moreutils, multiqc, multiqc-bcbio, ngs-disambiguate, novoalign, oncofuse, pandoc, parallel, pbgzip, peddy, pizzly, pythonpy, qsignature, rapmap, rtg-tools, sailfish, salmon, samblaster, samtools=1.13, scalpel, seq2c<2016, seqbuster, seqcluster, seqtk, sickle-trim, simple_sv_annotation, singlecell-barcodes, snap-aligner=1.0dev.97, snpeff=5.0, solvebio, spades, star=2.6.1d, stringtie, subread, survivor, tdrmapper, tophat-recondition, trim-galore, ucsc-bedgraphtobigwig, ucsc-bedtobigbed, ucsc-bigbedinfo, ucsc-bigbedsummary, ucsc-bigbedtobed, ucsc-bigwiginfo, ucsc-bigwigsummary, ucsc-bigwigtobedgraph, ucsc-bigwigtowig, ucsc-fatotwobit, ucsc-gtftogenepred, ucsc-liftover, ucsc-wigtobigwig, umis, vardict-java, vardict<=2015, variantbam, varscan, vcfanno, viennarna, vqsr_cnn, wham, ipyparallel=6.3.0, ipython-cluster-helper=0.6.4=py_0, ipython=7.29.0, ipython_genutils=0.2.0=py37_0, traitlets=4.3.3, anaconda-client, awscli, bzip2, ncurses, nodejs, p7zip, readline, s3gof3r, xz, perl-app-cpanminus, perl-archive-extract, perl-archive-zip, perl-bio-samtools, perl-cgi, perl-dbi, perl-encode-locale, perl-file-fetch, perl-file-sharedir, perl-file-sharedir-install, perl-ipc-system-simple, perl-lwp-protocol-https, perl-lwp-simple, perl-statistics-descriptive, perl-time-hires, perl-vcftools-vcf, bioconductor-annotate, bioconductor-apeglm, bioconductor-biocgenerics, bioconductor-biocinstaller, bioconductor-biocstyle, bioconductor-biostrings, bioconductor-biovizbase, bioconductor-bsgenome.hsapiens.ucsc.hg19, bioconductor-bsgenome.hsapiens.ucsc.hg38, bioconductor-bubbletree, bioconductor-cn.mops, bioconductor-copynumber, bioconductor-degreport, bioconductor-deseq2, bioconductor-dexseq, bioconductor-dnacopy, bioconductor-genomeinfodb, bioconductor-genomeinfodbdata, bioconductor-genomeinfodbdata, bioconductor-genomicranges, bioconductor-iranges, bioconductor-limma, bioconductor-org.hs.eg.db, bioconductor-purecn>=2.0.1, bioconductor-rhdf5, bioconductor-rtracklayer, bioconductor-rtracklayer, bioconductor-summarizedexperiment, bioconductor-titancna, bioconductor-txdb.hsapiens.ucsc.hg19.knowngene, bioconductor-txdb.hsapiens.ucsc.hg38.knowngene, bioconductor-tximport, bioconductor-vsn, r-base=4.1.1=hb67fd72_0, r-chbutils, r-deconstructsigs, r-devtools, r-dplyr, r-dt, r-ggdendro, r-ggplot2, r-ggrepel, r-gplots, r-gsalib, r-janitor, r-knitr, r-optparse, r-pheatmap, r-plyr, r-pscbs, r-reshape, r-rmarkdown, r-rsqlite, r-sleuth, r-snow, r-stringi, r-tidyverse, r-viridis, r-wasabi, r=4.1=r41hd8ed1ab_1004, xorg-libxt
# Installing into conda environment bwakit: bwakit
# Installing into conda environment dv: deepvariant
# Installing into conda environment htslib1.10: ataqv, cancerit-allelecount, delly, ensembl-vep=104, freebayes, hts-nim-tools, htslib=1.10, mosdepth, perl-bio-db-hts>=3.01, pindel, vcflib, verifybamid2
# Installing into conda environment htslib1.11: htslib=1.11, scramble
# Installing into conda environment htslib1.12: htslib=1.12, octopus>=0.7.4
# Installing into conda environment htslib1.12_py3.9: chipseq-greylist, htslib=1.12, lofreq, sambamba
# Installing into conda environment htslib1.9: duphold, extract-sv-reads, htslib=1.9
# Installing into conda environment java: bcbio-prioritize, bcbio-variation-recall, bcbio-variation, fgbio, gatk4=4.2.5.0, gatk, picard=2.27.5, qualimap
# Installing into conda environment python2: bismark, cpat, cutadapt=1.16, cyvcf2=0.10.0, dkfz-bias-filter, gemini, gvcf-regions, hap.py, htslib=1.10, lumpy-sv, manta, metasv, mirge, numpy=1.16, phylowgs, platypus-variant, pysam=0.15.3, samtools=1.10, sentieon, smcounter2, smoove, strelka, svtools, svtyper, theta2, tophat, vawk, vcf2db
# Installing into conda environment python3.6: bowtie2, crossmap, cufflinks, htslib=1.7, optitype, pandas=0.25.3, pyloh, pysam=0.15.4, razers3, samtools=1.7, vt=2015.11.10=he941832_3
Checking required dependencies
Installing isolated base python installation
Installing mamba
Installing conda-build
Installing bcbio-nextgen
Installing data and third party dependencies

```


with error:
```

Traceback (most recent call last):
  File "./software/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 73, in _install_env_pkgs
    "{py_version} {pkgs_str}".format(**locals()), shell=True)
  File "./software/bcbio/anaconda/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command './software/bcbio/anaconda/bin/mamba install -q -y -n python3.6 -c conda-forge -c bioconda python=3.6 'bowtie2' 'crossmap' 'cufflinks' 'htslib=1.7' 'optitype' 'pandas=0.25.3' 'pyloh' 'pysam=0.15.4' 'razers3' 'samtools=1.7' 'vt=2015.11.10=he941832_3'' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./software/bcbio/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "./software/bcbio/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 93, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "./software/bcbio/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 510, in upgrade_thirdparty_tools
    cbl_conda.install_in(conda_bin, args.tooldir, package_yaml)
  File "./software/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 128, in install_in
    conda_pkg_list = _install_env_pkgs(env_name, env_packages, conda_bin, conda_envs, channels)
  File "./software/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 78, in _install_env_pkgs
    "{py_version} {pkgs_str}".format(**locals()), shell=True)
  File "./software/bcbio/anaconda/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command './software/bcbio/anaconda/bin/conda install -q -y -n python3.6 -c conda-forge -c bioconda python=3.6 'bowtie2' 'crossmap' 'cufflinks' 'htslib=1.7' 'optitype' 'pandas=0.25.3' 'pyloh' 'pysam=0.15.4' 'razers3' 'samtools=1.7' 'vt=2015.11.10=he941832_3'' returned non-zero exit status 1.
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 306, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 55, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "./software/bcbio/anaconda/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./software/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=tools', '--upgrade=stable', '--cores=1']' returned non-zero exit status 1."

```
