### ISSUE TITLE
ValueError: Could not find directory in config for snpeff

### ISSUE THREAD

**Issue by azzatha** [bcbio/bcbio-nextgen#3693]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.5 
- OS name and version (`lsb_release -ds`): "CentOS Linux release 7.9.2009 (Core)"

**To Reproduce**
Exact bcbio command you have used:
```
bcbio_nextgen.py ${yaml} -n 500 -t ipython -s slurm -q batch -r "t=4-00:00:00"  --timeout 4000 --retries 500 

```

Your yaml configuration file:
```
resources:
  bwa:
     cores: 8
     memory: 3.5G
  samtools:
     cores: 4
     memory: 3.5G
  gatk:
     jvm_opts: ['-Xms6g' , '-Xmx6g']
     memory: 16G

details:
- algorithm:
    adapters:
    - polya
    aligner: bwa
    jointcaller: gatk-haplotype-joint
    mark_duplicates: true
    realign: false
    save_diskspace: true
    trim_reads: read_through
    variantcaller: gatk-haplotype
    vcfanno: gemini
  analysis: variant2
  description: 10G
  files:
  - 10G_R1.fastq.gz
  - 10G_R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: ksu
    sex: male
- algorithm:
    adapters:
    - polya
    aligner: bwa
    jointcaller: gatk-haplotype-joint
    mark_duplicates: true
    realign: false
    save_diskspace: true
    trim_reads: read_through
    variantcaller: gatk-haplotype
    vcfanno: gemini
  analysis: variant2
  description: 10F
  files:
  - 10F_R1.fastq.gz
  - 10F_R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: ksu
    sex: male 
fc_name: '28'
upload:
  dir: ../final
```

**Log files (could be found in work/log)**
Please attach (10MB max):  `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.
It works perfectly, but at the final annotation I get the following error:
```
2023-01-03 08:01:35.623 [IPClusterStart] Loaded config file: /encrypted/e3008/Azza/ksu_bcbio_fam/families/28/work/log/ipython/ipcluster_config.py
2023-01-03 08:01:35.623 [IPClusterStart] Looking for ipcluster_config in /encrypted/e3008/Azza/ksu_bcbio_fam/families/28/work
[2023-01-03T05:02Z] cn605-27-r: Timing: variant post-processing
[2023-01-03T05:02Z] cn605-27-r: ipython: postprocess_variants
[2023-01-03T05:02Z] cn514-09-l: Finalizing variant calls: 10G, gatk-haplotype
[2023-01-03T05:02Z] cn514-09-l: Calculating variation effects for 10G, gatk-haplotype
[2023-01-03T05:02Z] cn514-09-l: Unexpected error
Traceback (most recent call last):
  File "/ibex/sw/csi/bcbio-nextgen/1.2.5/el7.9_python2/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 54, in _setup_logging
    yield config
  File "/ibex/sw/csi/bcbio-nextgen/1.2.5/el7.9_python2/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 360, in postprocess_variants
    return ipython.zip_args(apply(variation.postprocess_variants, *args))
  File "/ibex/sw/csi/bcbio-nextgen/1.2.5/el7.9_python2/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 82, in apply
    return object(*args, **kwargs)
  File "/ibex/sw/csi/bcbio-nextgen/1.2.5/el7.9_python2/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/variation.py", line 97, in postprocess_variants
    ann_vrn_file, vrn_stats = effects.add_to_vcf(data[vrn_key], data)
  File "/ibex/sw/csi/bcbio-nextgen/1.2.5/el7.9_python2/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/effects.py", line 32, in add_to_vcf
    ann_vrn_file, stats_files = snpeff_effects(in_file, data)
  File "/ibex/sw/csi/bcbio-nextgen/1.2.5/el7.9_python2/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/effects.py", line 298, in snpeff_effects
    return _run_snpeff(vcf_in, "vcf", data)
  File "/ibex/sw/csi/bcbio-nextgen/1.2.5/el7.9_python2/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/effects.py", line 399, in _run_snpeff
    snpeff_db, datadir = get_db(data)
  File "/ibex/sw/csi/bcbio-nextgen/1.2.5/el7.9_python2/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/effects.py", line 353, in get_db
    snpeff_base_dir, snpeff_db = _installed_snpeff_genome(snpeff_db, data["config"])
  File "/ibex/sw/csi/bcbio-nextgen/1.2.5/el7.9_python2/bcbio/anaconda/lib/python3.6/site-packages/bcbio/variation/effects.py", line 439, in _installed_snpeff_genome
    snpeff_config_file = os.path.join(config_utils.get_program("snpeff", config, "dir"),
  File "/ibex/sw/csi/bcbio-nextgen/1.2.5/el7.9_python2/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/config_utils.py", line 193, in get_program
    return _get_program_dir(name, pconfig)
  File "/ibex/sw/csi/bcbio-nextgen/1.2.5/el7.9_python2/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/config_utils.py", line 249, in _get_program_dir
    raise ValueError("Could not find directory in config for %s" % name)
ValueError: Could not find directory in config for snpeff

```

Although the snpeff database is there in the bcbio directory
```
ls ./bcbio/genomes/Hsapiens/hg38/
bwa  config  coverage  editing  rnaseq  rtg  seq  snpeff  srnaseq  star  txtmp  validation  variation  vep  versions.csv  viral

```

Thank you!

**Comment by naumenko-sa** [comment]
Hi @azzatha !

Please try to check ./bcbio/genomes/Hsapiens/hg38/seq/hg38-resources.yaml for snpEff alias, a folder with the same name as alias has to be present in genomes/hg38/snpeff.

Also, bcbio1.2.5 is quite an old version, please upgrade to 1.2.9.

SN
