### ISSUE TITLE
Java error after fresh install of v1.2.9 

### ISSUE THREAD

**Issue by lindakohn** [bcbio/bcbio-nextgen#3702]
Hi!

Thank you for maintaining this great workflow!

I've run into java problems after a fresh install of v1.2.9, see traceback below

```
 Traceback (most recent call last):
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && export PATH=/home/bcbio/bcbio/anaconda/bin:"$PATH" && picard -Xms750m -Xmx3500m -XX:+UseSerialGC CollectSequencingArtifactMetrics -REFERENCE_SEQUENCE /home/bcbio/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa -INPUT /home/bcbio/data/test_230301/calling/work/align/15-5935D/15-5935D-sort.bam -OUTPUT /home/bcbio/data/test_230301/calling/work/bcbiotx/tmpweba5bat/15-5935D/15-5935D --VALIDATION_STRINGENCY SILENT
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: picard/cmdline/PicardCommandLine has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/bcbio/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/home/bcbio/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 138, in variant2pipeline
    samples = run_parallel("postprocess_alignment", samples)
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 1048, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 866, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 784, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/utils.py", line 59, in wrapper
    return f(*args, **kwargs)
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/distributed/multitasks.py", line 157, in postprocess_alignment
    return sample.postprocess_alignment(*args)
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/sample.py", line 269, in postprocess_alignment
    artifacts = gatk.collect_artifact_metrics(data)
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/variation/gatk.py", line 241, in collect_artifact_metrics
    picard.run("CollectSequencingArtifactMetrics", params)
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/broad/__init__.py", line 571, in run
    do.run(utils.clear_java_home() + " && " + " ".join(cmd), "Picard: %s" % subcmd)
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && export PATH=/home/bcbio/bcbio/anaconda/bin:"$PATH" && picard -Xms750m -Xmx3500m -XX:+UseSerialGC CollectSequencingArtifactMetrics -REFERENCE_SEQUENCE /home/bcbio/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa -INPUT /home/bcbio/data/test_230301/calling/work/align/15-5935D/15-5935D-sort.bam -OUTPUT /home/bcbio/data/test_230301/calling/work/bcbiotx/tmpweba5bat/15-5935D/15-5935D --VALIDATION_STRINGENCY SILENT
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: picard/cmdline/PicardCommandLine has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
' returned non-zero exit status 1.
```
Checking the java versions yields:

````
$/home/bcbio/bcbio/anaconda/bin/java --version
openjdk 11.0.9.1-internal 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 11.0.9.1-internal+0-adhoc..src, mixed mode)
````

````
$/usr/bin/java --version
openjdk 17.0.6 2023-01-17
OpenJDK Runtime Environment (build 17.0.6+10-Ubuntu-0ubuntu120.04.1)
OpenJDK 64-Bit Server VM (build 17.0.6+10-Ubuntu-0ubuntu120.04.1, mixed mode, sharing)
````

So I tried setting an environment variable to get bcbio to use java version 17 since it's asking for  Java Runtime (class file version 61.0):

````
$export BCBIO_JAVA_HOME=/usr 
````

Bcbio then continues to run but further along another java error is thrown:

````
Traceback (most recent call last):
  File "/home/bcbio/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/home/bcbio/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 173, in variant2pipeline
    samples = ensemble.combine_calls_parallel(samples, run_parallel)
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/variation/ensemble.py", line 118, in combine_calls_parallel
    processed = run_parallel("combine_calls", ((b, xs, xs[0]) for b, xs in batch_groups.items()))
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 1048, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 866, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 784, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/utils.py", line 59, in wrapper
    return f(*args, **kwargs)
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/distributed/multitasks.py", line 379, in combine_calls
    return ensemble.combine_calls(*args)
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/variation/ensemble.py", line 84, in combine_calls
    callinfo = _run_ensemble_intersection(batch_id, vrn_files, caller_names, base_dir, edata)
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/variation/ensemble.py", line 260, in _run_ensemble_intersection
    do.run(cmd, "Ensemble intersection calling: %s" % (batch_id))
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/bcbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; export JAVA_HOME=/usr && export PATH=/usr/bin:"$PATH" && /home/bcbio/bcbio/anaconda/envs/java/bin/bcbio-variation-recall ensemble --cores=16 --numpass 1 --names freebayes,vardict --nofiltered /home/bcbio/data/test_230301/calling/work/bcbiotx/tmp_rjexhhk/B15-5935D-ensemble.vcf.gz /home/bcbio/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa /home/bcbio/data/test_230301/calling/work/ensemble/B15-5935D/freebayes/B15-5935D-effects-annotated-filter-annotated-somatic-priority-noeff-nomultiallelic.vcf.gz /home/bcbio/data/test_230301/calling/work/ensemble/B15-5935D/vardict/B15-5935D-effects-annotated-annotated-somatic-priority-noeff-nomultiallelic.vcf.gz
                   bcbio.variation.recall.main.main                         
                                                ...                         
                  bcbio.variation.recall.main/-main            main.clj:  30
                  bcbio.variation.recall.main/-main            main.clj:  33
               bcbio.variation.recall.main/-main/fn            main.clj:  34
                                 clojure.core/apply            core.clj: 665
                                                ...                         
           bcbio.variation.ensemble.intersect/-main       intersect.clj: 117
           bcbio.variation.ensemble.intersect/-main       intersect.clj: 141
   bcbio.variation.ensemble.intersect/ensemble-vcfs       intersect.clj:  87
bcbio.variation.ensemble.intersect/ensemble-vcfs/fn       intersect.clj:  89
                                                ...                         
bcbio.variation.variantcontext/write-vcf-w-template  variantcontext.clj: 165
bcbio.variation.variantcontext/write-vcf-w-template  variantcontext.clj: 186
                                                ...                         
java.lang.IllegalArgumentException: No matching method writeHeader found taking 1 args for class htsjdk.variant.variantcontext.writer.VCFWriter
' returned non-zero exit status 1.
````

Unsetting the environment variable at this point solves the issue

````
$unset BCBIO_JAVA_HOME
````

and bcbio finishes successfully.

Please suggest on how to solve this

Kind regards
Linda

**Comment by naumenko-sa** [comment]
Hi Linda @lindakohn !

Thanks for raising the issue!
I think the issue stems from the major upgrade in gatk and picard which both switched to java17:
- https://github.com/broadinstitute/gatk/releases
- https://github.com/broadinstitute/picard/releases/tag/3.0.0

While other packages in java env in bcbio are not compatible with newer java:
https://github.com/chapmanb/cloudbiolinux/blob/master/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml#L292

I am testing a solution. I will likely be a separate java17 environment for gatk/picard and java8 for other packages.

SN

**Comment by naumenko-sa** [comment]
Hi Linda @lindakohn !

I've made a fix and ran a test installation - picard and gatk work!
For now we are just pinning pre-java17 gatk4 and picard version, since there is no gatk4.4.0/java17 in conda yet.
https://github.com/chapmanb/cloudbiolinux/blob/master/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml#L277

Once it is published, we will switch to java17 and unpin picard and gatk4, placing gatk and other legacy tools in java8 env.

SN

**Comment by lindakohn** [comment]
Thank you!

I ran 
`bcbio_nextgen.py upgrade -u development --tools`
and saw that gatk ang picard were downgraded to 4.2.5.0 and 2.27.5, respectively. However, I now encountered another error:

````
Traceback (most recent call last):
  File "/home/bcbio/bcb/tools/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/home/bcbio/bcb/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/bcbio/bcb/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/home/bcbio/bcb/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/bcbio/bcb/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 194, in variant2pipeline
    samples = qcsummary.generate_parallel(samples, run_parallel)
  File "/home/bcbio/bcb/anaconda/lib/python3.7/site-packages/bcbio/pipeline/qcsummary.py", line 43, in generate_parallel
    qced = run_parallel("pipeline_summary", to_analyze)
  File "/home/bcbio/bcb/anaconda/lib/python3.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/bcbio/bcb/anaconda/lib/python3.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/home/bcbio/bcb/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 1051, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/bcbio/bcb/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 866, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/bcbio/bcb/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 784, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/bcbio/bcb/anaconda/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/home/bcbio/bcb/anaconda/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/home/bcbio/bcb/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/bcbio/bcb/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/bcbio/bcb/anaconda/lib/python3.7/site-packages/bcbio/utils.py", line 59, in wrapper
    return f(*args, **kwargs)
  File "/home/bcbio/bcb/anaconda/lib/python3.7/site-packages/bcbio/distributed/multitasks.py", line 243, in pipeline_summary
    return qcsummary.pipeline_summary(*args)
  File "/home/bcbio/bcb/anaconda/lib/python3.7/site-packages/bcbio/pipeline/qcsummary.py", line 79, in pipeline_summary
    data["summary"] = _run_qc_tools(work_bam, work_data)
  File "/home/bcbio/bcb/anaconda/lib/python3.7/site-packages/bcbio/pipeline/qcsummary.py", line 177, in _run_qc_tools
    out = qc_fn(bam_file, data, cur_qc_dir)
  File "/home/bcbio/bcb/anaconda/lib/python3.7/site-packages/bcbio/qc/fastqc.py", line 52, in run
    do.run(cl, "FastQC: %s" % dd.get_sample_name(data))
  File "/home/bcbio/bcb/anaconda/lib/python3.7/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/bcbio/bcb/anaconda/lib/python3.7/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; export LD_PRELOAD=/home/bcbio/bcb/anaconda/lib/libfreetype.so &&  export PATH=/home/bcbio/bcb/anaconda/bin:"$PATH" &&  /home/bcbio/bcb/anaconda/bin/fastqc -d /home/bcbio/data/test_230301/calling/work/qc/15-5935D/bcbiotx/tmpkkh6gva8 -t 16 --extract -o /home/bcbio/data/test_230301/calling/work/qc/15-5935D/bcbiotx/tmpkkh6gva8 -f bam /home/bcbio/data/test_230301/calling/work/align/15-5935D/15-5935D-sort.bam
Option d is ambiguous (delete, dir, dup_length)
Failed to process /home/bcbio/data/test_230301/calling/work/qc/15-5935D/bcbiotx/tmpkkh6gva8
java.io.FileNotFoundException: /home/bcbio/data/test_230301/calling/work/qc/15-5935D/bcbiotx/tmpkkh6gva8 (Is a directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at uk.ac.babraham.FastQC.Sequence.BAMFile.<init>(BAMFile.java:62)
	at uk.ac.babraham.FastQC.Sequence.SequenceFactory.getSequenceFile(SequenceFactory.java:81)
	at uk.ac.babraham.FastQC.Sequence.SequenceFactory.getSequenceFile(SequenceFactory.java:62)
	at uk.ac.babraham.FastQC.Analysis.OfflineRunner.processFile(OfflineRunner.java:163)
	at uk.ac.babraham.FastQC.Analysis.OfflineRunner.<init>(OfflineRunner.java:125)
	at uk.ac.babraham.FastQC.FastQCApplication.main(FastQCApplication.java:316)
Started analysis of 15-5935D-sort.bam
Approx 5% complete for 15-5935D-sort.bam
Approx 10% complete for 15-5935D-sort.bam
Approx 15% complete for 15-5935D-sort.bam
Approx 20% complete for 15-5935D-sort.bam
Approx 25% complete for 15-5935D-sort.bam
Approx 30% complete for 15-5935D-sort.bam
Approx 35% complete for 15-5935D-sort.bam
Approx 40% complete for 15-5935D-sort.bam
Approx 45% complete for 15-5935D-sort.bam
Approx 50% complete for 15-5935D-sort.bam
Approx 55% complete for 15-5935D-sort.bam
Approx 60% complete for 15-5935D-sort.bam
Approx 65% complete for 15-5935D-sort.bam
Approx 70% complete for 15-5935D-sort.bam
Approx 75% complete for 15-5935D-sort.bam
Approx 80% complete for 15-5935D-sort.bam
Approx 85% complete for 15-5935D-sort.bam
Approx 90% complete for 15-5935D-sort.bam
Approx 95% complete for 15-5935D-sort.bam
Approx 100% complete for 15-5935D-sort.bam
Analysis complete for 15-5935D-sort.bam
' returned non-zero exit status 1.
````

Something seems to have changed for fastqc?

**Comment by naumenko-sa** [comment]
Yes, it looks like we received a major update of fastqc and we should adapt to it:
https://github.com/s-andrews/FastQC/releases/tag/v0.12.0

Pinned to the previous version in the meanwhile - no error,
please upgrade tools and it should downgrade for you as well.

**Comment by lindakohn** [comment]
Perfect, thank you, works now!
