### ISSUE TITLE
Installing bcbio in macos in VM fails

### ISSUE THREAD

**Issue by GACGAMA** [bcbio/bcbio-nextgen#3712]
Trying to install bcbio inside the VM (for macos)
Vagrant version - latest that works on Ventura OS - 2.3.7
VirtualBox - same thing - 7.0.8-1

**Version info**
- bcbio version (`bcbio_nextgen.py --version`):
- OS name and version (`lsb_release -ds`): Ventura 13.4 - Ubuntu 18.04.6 LTS

**To Reproduce**
Exact bcbio command you have used:
```

git clone https://github.com/bcbio/bcbio-nextgen.git
cd bcbio-nextgen
vagrant up
Install bcbio-nextgen
```

**Log files (could be found in work/log)**
```
vagrant@bcbio:~$ python3 /vagrant/scripts/bcbio_nextgen_install.py ~/local/share/bcbio --tooldir=~/local --nodata
Checking required dependencies
Installing isolated base python installation
Installing conda
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 22.9.0
  latest version: 23.5.0

Please update conda by running

    $ conda update -n base -c conda-forge conda



# All requested packages already installed.

Retrieving notices: ...working... done
Installing conda-build
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 22.9.0
  latest version: 23.5.0

Please update conda by running

    $ conda update -n base -c conda-forge conda



# All requested packages already installed.

Retrieving notices: ...working... done
Installing bcbio-nextgen
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: - Traceback (most recent call last):
  File "/vagrant/scripts/bcbio_nextgen_install.py", line 306, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "/vagrant/scripts/bcbio_nextgen_install.py", line 50, in main
    bcbio = install_conda_pkgs(anaconda, args)
  File "/vagrant/scripts/bcbio_nextgen_install.py", line 114, in install_conda_pkgs
    subprocess.check_call([mamba_bin, "install", "--yes", "--only-deps", "bcbio-nextgen"], env=env)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/vagrant/local/share/bcbio/anaconda/bin/conda', 'install', '--yes', '--only-deps', 'bcbio-nextgen']' died with <Signals.SIGKILL: 9>.

```

**Comment by naumenko-sa** [comment]
sorry, not supported, linux only.
removed vagrant instruction from the install
https://github.com/bcbio/bcbio-nextgen/commit/6a159b6593caa6d8403fd2fb0107998edb9f54bf
