### ISSUE TITLE
Failed in generating genome files

### ISSUE THREAD

**Issue by gis-nlsim** [bcbio/bcbio-nextgen#3714]
I tried generating the genomes using the following command:
bcbio_nextgen.py upgrade -u skip --genomes GRCh37 --genomes hg38 --aligners bwa --aligners sta

But encountered a failure. It seems that this file does not exist:
https://ftp.ncbi.nih.gov/snp/archive/b154/VCF/GCF_000001405.25.gz

Running GGD recipe: GRCh37 dbsnp 154-20210112
--2023-07-24 09:48:18--  https://ftp.ncbi.nih.gov/snp/archive/b154/VCF/GCF_000001405.25.gz
Resolving ftp.ncbi.nih.gov (ftp.ncbi.nih.gov)... 130.14.250.13, 165.112.9.229, 130.14.250.7, ...
Connecting to ftp.ncbi.nih.gov (ftp.ncbi.nih.gov)|130.14.250.13|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-07-24 09:48:19 ERROR 404: Not Found.

Traceback (most recent call last):
  File "/apps/bcbio/v129/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/apps/bcbio/v129/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 109, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/apps/bcbio/v129/anaconda/lib/python3.7/site-packages/bcbio/install.py", line 361, in upgrade_bcbio_data
    args.cores, ["ggd", "s3", "raw"])
  File "/install/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 354, in install_data_local
    _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
  File "/install/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 480, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/install/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 875, in _install_with_ggd
    ggd.install_recipe(os.getcwd(), env.system_install, recipe_file, gid)
  File "/install/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"], system_install)
  File "/install/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/apps/bcbio/v129/anaconda/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/apps/bcbio/v129/anaconda/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bash', '/apps/bcbio/v129/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh']' returned non-zero exit status 8.

**Comment by gis-nlsim** [comment]
It seems that the gzip file is no longer gzipped in ncbi:
https://ftp.ncbi.nih.gov/snp/archive/b154/VCF/GCF_000001405.25
