### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by PCanavelli** [bcbio/bcbio-nextgen#3744]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.9
- OS name and version (`lsb_release -ds`):
  - Ubuntu 18.04
  - Ubuntu 20.04 (WSL2)
  - Ubuntu 22.04 (WSL2)

**To Reproduce**
Exact bcbio command you have used:
```
export PATH=/bcbio_installation/anaconda/bin:/bcbio_installation/tools/bin:$PATH
wget https://raw.github.com/bcbio/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py
python3 bcbio_nextgen_install.py [bcbio_path] --tooldir=[bcbio_path]/tools --nodata --mamba
```

Your yaml configuration file:
```
N/A
```

**Log files (could be found in work/log)**

```
Checking required dependencies
Installing isolated base python installation
--2024-07-14 16:34:15--  https://repo.anaconda.com/miniconda/Miniconda3-py37_4.10.3-Linux-x86_64.sh
Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.191.158, 104.16.32.241, 2606:4700::6810:20f1, ...
Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.191.158|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 89026327 (85M) [application/x-sh]
Saving to: ‘Miniconda3-py37_4.10.3-Linux-x86_64.sh’

     0K ........ ........ ........ ........ 37%  107M 0s
 32768K ........ ........ ........ ........ 75%  110M 0s
 65536K ........ ........ ....             100%  112M=0.8s

2024-07-14 16:34:16 (109 MB/s) - ‘Miniconda3-py37_4.10.3-Linux-x86_64.sh’ saved [89026327/89026327]

PREFIX=/usr/local/share/bcbio/anaconda
Unpacking payload ...
Collecting package metadata (current_repodata.json): done                                                                                                           
Solving environment: done

## Package Plan ##

  environment location: /usr/local/share/bcbio/anaconda

  added / updated specs:
    - _libgcc_mutex==0.1=main
    - _openmp_mutex==4.5=1_gnu
    - brotlipy==0.7.0=py37h27cfd23_1003
    - ca-certificates==2021.7.5=h06a4308_1
    - certifi==2021.5.30=py37h06a4308_0
    - cffi==1.14.6=py37h400218f_0
    - chardet==4.0.0=py37h06a4308_1003
    - conda-package-handling==1.7.3=py37h27cfd23_1
    - conda==4.10.3=py37h06a4308_0
    - cryptography==3.4.7=py37hd23ed53_0
    - idna==2.10=pyhd3eb1b0_0
    - ld_impl_linux-64==2.35.1=h7274673_9
    - libffi==3.3=he6710b0_2
    - libgcc-ng==9.3.0=h5101ec6_17
    - libgomp==9.3.0=h5101ec6_17
    - libstdcxx-ng==9.3.0=hd4cf53a_17
    - ncurses==6.2=he6710b0_1
    - openssl==1.1.1k=h27cfd23_0
    - pip==21.1.3=py37h06a4308_0
    - pycosat==0.6.3=py37h27cfd23_0
    - pycparser==2.20=py_2
    - pyopenssl==20.0.1=pyhd3eb1b0_1
    - pysocks==1.7.1=py37_1
    - python==3.7.10=h12debd9_4
    - readline==8.1=h27cfd23_0
    - requests==2.25.1=pyhd3eb1b0_0
    - ruamel_yaml==0.15.100=py37h27cfd23_0
    - setuptools==52.0.0=py37h06a4308_0
    - six==1.16.0=pyhd3eb1b0_0
    - sqlite==3.36.0=hc218d9a_0
    - tk==8.6.10=hbc83047_0
    - tqdm==4.61.2=pyhd3eb1b0_1
    - urllib3==1.26.6=pyhd3eb1b0_1
    - wheel==0.36.2=pyhd3eb1b0_0
    - xz==5.2.5=h7b6447c_0
    - yaml==0.2.5=h7b6447c_0
    - zlib==1.2.11=h7b6447c_3


The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-4.5-1_gnu
  brotlipy           pkgs/main/linux-64::brotlipy-0.7.0-py37h27cfd23_1003
  ca-certificates    pkgs/main/linux-64::ca-certificates-2021.7.5-h06a4308_1
  certifi            pkgs/main/linux-64::certifi-2021.5.30-py37h06a4308_0
  cffi               pkgs/main/linux-64::cffi-1.14.6-py37h400218f_0
  chardet            pkgs/main/linux-64::chardet-4.0.0-py37h06a4308_1003
  conda              pkgs/main/linux-64::conda-4.10.3-py37h06a4308_0
  conda-package-han~ pkgs/main/linux-64::conda-package-handling-1.7.3-py37h27cfd23_1
  cryptography       pkgs/main/linux-64::cryptography-3.4.7-py37hd23ed53_0
  idna               pkgs/main/noarch::idna-2.10-pyhd3eb1b0_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.35.1-h7274673_9
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_2
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.3.0-h5101ec6_17
  libgomp            pkgs/main/linux-64::libgomp-9.3.0-h5101ec6_17
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.3.0-hd4cf53a_17
  ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1k-h27cfd23_0
  pip                pkgs/main/linux-64::pip-21.1.3-py37h06a4308_0
  pycosat            pkgs/main/linux-64::pycosat-0.6.3-py37h27cfd23_0
  pycparser          pkgs/main/noarch::pycparser-2.20-py_2
  pyopenssl          pkgs/main/noarch::pyopenssl-20.0.1-pyhd3eb1b0_1
  pysocks            pkgs/main/linux-64::pysocks-1.7.1-py37_1
  python             pkgs/main/linux-64::python-3.7.10-h12debd9_4
  readline           pkgs/main/linux-64::readline-8.1-h27cfd23_0
  requests           pkgs/main/noarch::requests-2.25.1-pyhd3eb1b0_0
  ruamel_yaml        pkgs/main/linux-64::ruamel_yaml-0.15.100-py37h27cfd23_0
  setuptools         pkgs/main/linux-64::setuptools-52.0.0-py37h06a4308_0
  six                pkgs/main/noarch::six-1.16.0-pyhd3eb1b0_0
  sqlite             pkgs/main/linux-64::sqlite-3.36.0-hc218d9a_0
  tk                 pkgs/main/linux-64::tk-8.6.10-hbc83047_0
  tqdm               pkgs/main/noarch::tqdm-4.61.2-pyhd3eb1b0_1
  urllib3            pkgs/main/noarch::urllib3-1.26.6-pyhd3eb1b0_1
  wheel              pkgs/main/noarch::wheel-0.36.2-pyhd3eb1b0_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  yaml               pkgs/main/linux-64::yaml-0.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3


Preparing transaction: done
Executing transaction: done
installation finished.
Installing conda
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.3
  latest version: 24.5.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /usr/local/share/bcbio/anaconda

  added / updated specs:
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2024.7.4   |       hbcca054_0         151 KB  conda-forge
    certifi-2024.7.4           |     pyhd8ed1ab_0         156 KB  conda-forge
    conda-4.14.0               |   py37h89c1867_0        1010 KB  conda-forge
    openssl-1.1.1w             |       h7f8727e_0         3.7 MB
    python_abi-3.7             |          2_cp37m           4 KB  conda-forge
    toolz-0.12.1               |     pyhd8ed1ab_0          51 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         5.1 MB

The following NEW packages will be INSTALLED:

  python_abi         conda-forge/linux-64::python_abi-3.7-2_cp37m
  toolz              conda-forge/noarch::toolz-0.12.1-pyhd8ed1ab_0

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2021.7.5-h~ --> conda-forge::ca-certificates-2024.7.4-hbcca054_0
  certifi            pkgs/main/linux-64::certifi-2021.5.30~ --> conda-forge/noarch::certifi-2024.7.4-pyhd8ed1ab_0
  conda              pkgs/main::conda-4.10.3-py37h06a4308_0 --> conda-forge::conda-4.14.0-py37h89c1867_0
  openssl                                 1.1.1k-h27cfd23_0 --> 1.1.1w-h7f8727e_0



Downloading and Extracting Packages
python_abi-3.7       | 4 KB      | ######################################################################################################################### | 100% 
certifi-2024.7.4     | 156 KB    | ######################################################################################################################### | 100% 
ca-certificates-2024 | 151 KB    | ######################################################################################################################### | 100% 
conda-4.14.0         | 1010 KB   | ######################################################################################################################### | 100% 
openssl-1.1.1w       | 3.7 MB    | ######################################################################################################################### | 100% 
toolz-0.12.1         | 51 KB     | ######################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing conda-build
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /usr/local/share/bcbio/anaconda

  added / updated specs:
    - conda-build
    - mamba=0.24.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _libgcc_mutex-0.1          |      conda_forge           3 KB  conda-forge
    _openmp_mutex-4.5          |       2_kmp_llvm           6 KB  conda-forge
    beautifulsoup4-4.12.3      |     pyha770c72_0         115 KB  conda-forge
    bzip2-1.0.8                |       h4bc722e_6         248 KB  conda-forge
    c-ares-1.32.1              |       h4bc722e_0         176 KB  conda-forge
    conda-22.9.0               |   py37h89c1867_1         960 KB  conda-forge
    conda-build-3.22.0         |   py37h89c1867_2         559 KB  conda-forge
    filelock-3.15.4            |     pyhd8ed1ab_0          17 KB  conda-forge
    glob2-0.7                  |             py_0          11 KB  conda-forge
    icu-70.1                   |       h27087fc_0        13.5 MB  conda-forge
    jinja2-3.1.4               |     pyhd8ed1ab_0         109 KB  conda-forge
    keyutils-1.6.1             |       h166bdaf_0         115 KB  conda-forge
    krb5-1.20.1                |       hf9c8cef_0         1.3 MB  conda-forge
    libarchive-3.5.2           |       hb890918_3         1.6 MB  conda-forge
    libcurl-7.87.0             |       h6312ad2_0         339 KB  conda-forge
    libedit-3.1.20191231       |       he28a2e2_2         121 KB  conda-forge
    libev-4.33                 |       hd590300_2         110 KB  conda-forge
    libgcc-ng-14.1.0           |       h77fa898_0         822 KB  conda-forge
    libiconv-1.17              |       hd590300_2         689 KB  conda-forge
    liblief-0.12.2             |       h27087fc_0         2.1 MB  conda-forge
    libmamba-0.24.0            |       hd8a31e3_1         1.4 MB  conda-forge
    libmambapy-0.24.0          |   py37h1ee4b26_1         276 KB  conda-forge
    libnghttp2-1.51.0          |       hdcd2b5c_0         608 KB  conda-forge
    libsolv-0.7.29             |       ha6fb4c9_0         460 KB  conda-forge
    libssh2-1.10.0             |       haa6b8db_3         234 KB  conda-forge
    libstdcxx-ng-14.1.0        |       hc0a3c3a_0         3.7 MB  conda-forge
    libxml2-2.9.14             |       h22db469_4         771 KB  conda-forge
    libzlib-1.2.13             |       h4ab18f5_6          60 KB  conda-forge
    llvm-openmp-18.1.7         |       ha31de31_0        55.9 MB  conda-forge
    lz4-c-1.9.4                |       hcb278e6_0         140 KB  conda-forge
    lzo-2.10                   |    hd590300_1001         167 KB  conda-forge
    mamba-0.24.0               |   py37h6dacc13_1          45 KB  conda-forge
    markupsafe-2.1.1           |   py37h540881e_1          22 KB  conda-forge
    openssl-1.1.1w             |       hd590300_0         1.9 MB  conda-forge
    patch-2.7.6                |    h7f98852_1002         121 KB  conda-forge
    patchelf-0.17.2            |       h58526e2_0          92 KB  conda-forge
    pkginfo-1.10.0             |     pyhd8ed1ab_0          27 KB  conda-forge
    psutil-5.9.3               |   py37h540881e_0         348 KB  conda-forge
    py-lief-0.12.2             |   py37hd23a5d3_0         1.6 MB  conda-forge
    pybind11-abi-4             |       hd8ed1ab_3          10 KB  conda-forge
    python-libarchive-c-4.0    |   py37h89c1867_1          62 KB  conda-forge
    pytz-2024.1                |     pyhd8ed1ab_0         184 KB  conda-forge
    pyyaml-6.0                 |   py37h540881e_4         178 KB  conda-forge
    reproc-14.2.4.post0        |       hd590300_1          33 KB  conda-forge
    reproc-cpp-14.2.4.post0    |       h59595ed_1          25 KB  conda-forge
    ripgrep-14.1.0             |       he8a937b_0         1.6 MB  conda-forge
    soupsieve-2.3.2.post1      |     pyhd8ed1ab_0          34 KB  conda-forge
    toml-0.10.2                |     pyhd8ed1ab_0          18 KB  conda-forge
    yaml-cpp-0.7.0             |       h59595ed_3         203 KB  conda-forge
    zlib-1.2.13                |       h4ab18f5_6          91 KB  conda-forge
    zstd-1.5.6                 |       ha6fb4c9_0         542 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        93.6 MB

The following NEW packages will be INSTALLED:

  beautifulsoup4     conda-forge/noarch::beautifulsoup4-4.12.3-pyha770c72_0
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h4bc722e_6
  c-ares             conda-forge/linux-64::c-ares-1.32.1-h4bc722e_0
  conda-build        conda-forge/linux-64::conda-build-3.22.0-py37h89c1867_2
  filelock           conda-forge/noarch::filelock-3.15.4-pyhd8ed1ab_0
  glob2              conda-forge/noarch::glob2-0.7-py_0
  icu                conda-forge/linux-64::icu-70.1-h27087fc_0
  jinja2             conda-forge/noarch::jinja2-3.1.4-pyhd8ed1ab_0
  keyutils           conda-forge/linux-64::keyutils-1.6.1-h166bdaf_0
  krb5               conda-forge/linux-64::krb5-1.20.1-hf9c8cef_0
  libarchive         conda-forge/linux-64::libarchive-3.5.2-hb890918_3
  libcurl            conda-forge/linux-64::libcurl-7.87.0-h6312ad2_0
  libedit            conda-forge/linux-64::libedit-3.1.20191231-he28a2e2_2
  libev              conda-forge/linux-64::libev-4.33-hd590300_2
  libiconv           conda-forge/linux-64::libiconv-1.17-hd590300_2
  liblief            conda-forge/linux-64::liblief-0.12.2-h27087fc_0
  libmamba           conda-forge/linux-64::libmamba-0.24.0-hd8a31e3_1
  libmambapy         conda-forge/linux-64::libmambapy-0.24.0-py37h1ee4b26_1
  libnghttp2         conda-forge/linux-64::libnghttp2-1.51.0-hdcd2b5c_0
  libsolv            conda-forge/linux-64::libsolv-0.7.29-ha6fb4c9_0
  libssh2            conda-forge/linux-64::libssh2-1.10.0-haa6b8db_3
  libxml2            conda-forge/linux-64::libxml2-2.9.14-h22db469_4
  libzlib            conda-forge/linux-64::libzlib-1.2.13-h4ab18f5_6
  llvm-openmp        conda-forge/linux-64::llvm-openmp-18.1.7-ha31de31_0
  lz4-c              conda-forge/linux-64::lz4-c-1.9.4-hcb278e6_0
  lzo                conda-forge/linux-64::lzo-2.10-hd590300_1001
  mamba              conda-forge/linux-64::mamba-0.24.0-py37h6dacc13_1
  markupsafe         conda-forge/linux-64::markupsafe-2.1.1-py37h540881e_1
  patch              conda-forge/linux-64::patch-2.7.6-h7f98852_1002
  patchelf           conda-forge/linux-64::patchelf-0.17.2-h58526e2_0
  pkginfo            conda-forge/noarch::pkginfo-1.10.0-pyhd8ed1ab_0
  psutil             conda-forge/linux-64::psutil-5.9.3-py37h540881e_0
  py-lief            conda-forge/linux-64::py-lief-0.12.2-py37hd23a5d3_0
  pybind11-abi       conda-forge/noarch::pybind11-abi-4-hd8ed1ab_3
  python-libarchive~ conda-forge/linux-64::python-libarchive-c-4.0-py37h89c1867_1
  pytz               conda-forge/noarch::pytz-2024.1-pyhd8ed1ab_0
  pyyaml             conda-forge/linux-64::pyyaml-6.0-py37h540881e_4
  reproc             conda-forge/linux-64::reproc-14.2.4.post0-hd590300_1
  reproc-cpp         conda-forge/linux-64::reproc-cpp-14.2.4.post0-h59595ed_1
  ripgrep            conda-forge/linux-64::ripgrep-14.1.0-he8a937b_0
  soupsieve          conda-forge/noarch::soupsieve-2.3.2.post1-pyhd8ed1ab_0
  toml               conda-forge/noarch::toml-0.10.2-pyhd8ed1ab_0
  yaml-cpp           conda-forge/linux-64::yaml-cpp-0.7.0-h59595ed_3
  zstd               conda-forge/linux-64::zstd-1.5.6-ha6fb4c9_0

The following packages will be REMOVED:

  libgomp-9.3.0-h5101ec6_17

The following packages will be UPDATED:

  conda                               4.14.0-py37h89c1867_0 --> 22.9.0-py37h89c1867_1
  libgcc-ng          pkgs/main::libgcc-ng-9.3.0-h5101ec6_17 --> conda-forge::libgcc-ng-14.1.0-h77fa898_0
  libstdcxx-ng       pkgs/main::libstdcxx-ng-9.3.0-hd4cf53~ --> conda-forge::libstdcxx-ng-14.1.0-hc0a3c3a_0
  zlib                    pkgs/main::zlib-1.2.11-h7b6447c_3 --> conda-forge::zlib-1.2.13-h4ab18f5_6

The following packages will be SUPERSEDED by a higher-priority channel:

  _libgcc_mutex           pkgs/main::_libgcc_mutex-0.1-main --> conda-forge::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex          pkgs/main::_openmp_mutex-4.5-1_gnu --> conda-forge::_openmp_mutex-4.5-2_kmp_llvm
  openssl              pkgs/main::openssl-1.1.1w-h7f8727e_0 --> conda-forge::openssl-1.1.1w-hd590300_0



Downloading and Extracting Packages
jinja2-3.1.4         | 109 KB    | ######################################################################################################################### | 100% 
libsolv-0.7.29       | 460 KB    | ######################################################################################################################### | 100% 
toml-0.10.2          | 18 KB     | ######################################################################################################################### | 100% 
libev-4.33           | 110 KB    | ######################################################################################################################### | 100% 
soupsieve-2.3.2.post | 34 KB     | ######################################################################################################################### | 100% 
lzo-2.10             | 167 KB    | ######################################################################################################################### | 100% 
zstd-1.5.6           | 542 KB    | ######################################################################################################################### | 100% 
icu-70.1             | 13.5 MB   | ######################################################################################################################### | 100% 
pytz-2024.1          | 184 KB    | ######################################################################################################################### | 100% 
reproc-14.2.4.post0  | 33 KB     | ######################################################################################################################### | 100% 
openssl-1.1.1w       | 1.9 MB    | ######################################################################################################################### | 100% 
patchelf-0.17.2      | 92 KB     | ######################################################################################################################### | 100% 
yaml-cpp-0.7.0       | 203 KB    | ######################################################################################################################### | 100% 
reproc-cpp-14.2.4.po | 25 KB     | ######################################################################################################################### | 100% 
zlib-1.2.13          | 91 KB     | ######################################################################################################################### | 100% 
ripgrep-14.1.0       | 1.6 MB    | ######################################################################################################################### | 100% 
libzlib-1.2.13       | 60 KB     | ######################################################################################################################### | 100% 
lz4-c-1.9.4          | 140 KB    | ######################################################################################################################### | 100% 
libnghttp2-1.51.0    | 608 KB    | ######################################################################################################################### | 100% 
_libgcc_mutex-0.1    | 3 KB      | ######################################################################################################################### | 100% 
libedit-3.1.20191231 | 121 KB    | ######################################################################################################################### | 100% 
mamba-0.24.0         | 45 KB     | ######################################################################################################################### | 100% 
bzip2-1.0.8          | 248 KB    | ######################################################################################################################### | 100% 
filelock-3.15.4      | 17 KB     | ######################################################################################################################### | 100% 
libgcc-ng-14.1.0     | 822 KB    | ######################################################################################################################### | 100% 
python-libarchive-c- | 62 KB     | ######################################################################################################################### | 100% 
conda-22.9.0         | 960 KB    | ######################################################################################################################### | 100% 
krb5-1.20.1          | 1.3 MB    | ######################################################################################################################### | 100% 
libiconv-1.17        | 689 KB    | ######################################################################################################################### | 100% 
libarchive-3.5.2     | 1.6 MB    | ######################################################################################################################### | 100% 
beautifulsoup4-4.12. | 115 KB    | ######################################################################################################################### | 100% 
markupsafe-2.1.1     | 22 KB     | ######################################################################################################################### | 100% 
psutil-5.9.3         | 348 KB    | ######################################################################################################################### | 100% 
liblief-0.12.2       | 2.1 MB    | ######################################################################################################################### | 100% 
llvm-openmp-18.1.7   | 55.9 MB   | ######################################################################################################################### | 100% 
c-ares-1.32.1        | 176 KB    | ######################################################################################################################### | 100% 
libxml2-2.9.14       | 771 KB    | ######################################################################################################################### | 100% 
libcurl-7.87.0       | 339 KB    | ######################################################################################################################### | 100% 
py-lief-0.12.2       | 1.6 MB    | ######################################################################################################################### | 100% 
conda-build-3.22.0   | 559 KB    | ######################################################################################################################### | 100% 
libmamba-0.24.0      | 1.4 MB    | ######################################################################################################################### | 100% 
libmambapy-0.24.0    | 276 KB    | ######################################################################################################################### | 100% 
patch-2.7.6          | 121 KB    | ######################################################################################################################### | 100% 
_openmp_mutex-4.5    | 6 KB      | ######################################################################################################################### | 100% 
pyyaml-6.0           | 178 KB    | ######################################################################################################################### | 100% 
glob2-0.7            | 11 KB     | ######################################################################################################################### | 100% 
libstdcxx-ng-14.1.0  | 3.7 MB    | ######################################################################################################################### | 100% 
pkginfo-1.10.0       | 27 KB     | ######################################################################################################################### | 100% 
libssh2-1.10.0       | 234 KB    | ######################################################################################################################### | 100% 
keyutils-1.6.1       | 115 KB    | ######################################################################################################################### | 100% 
pybind11-abi-4       | 10 KB     | ######################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Retrieving notices: ...working... done
Installing bcbio-nextgen
--2024-07-14 16:38:48--  https://raw.githubusercontent.com/bcbio/bcbio-nextgen/master/requirements-conda.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20 [text/plain]
Saving to: ‘requirements-conda.txt’

requirements-conda.txt                   100%[==================================================================================>]      20  --.-KB/s    in 0s      

2024-07-14 16:38:48 (1.17 MB/s) - ‘requirements-conda.txt’ saved [20/20]

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 306, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 50, in main
    bcbio = install_conda_pkgs(anaconda, args)
  File "bcbio_nextgen_install.py", line 114, in install_conda_pkgs
    subprocess.check_call([mamba_bin, "install", "--yes", "--only-deps", "bcbio-nextgen"], env=env)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/conda', 'install', '--yes', '--only-deps', 'bcbio-nextgen']' died with <Signals.SIGKILL: 9>.
```

### Description of the issue

I am trying to install `bcbio` as per the [user manual](https://bcbio-nextgen.readthedocs.io/en/latest/contents/intro.html) in a WSL2 Ubuntu environment. The installation invariably fails and throws the error message copied above.

I have tried switching to Ubuntu 22.04 to 20.04, but got the same outcome.

Also, this [issue](https://github.com/bcbio/bcbio-nextgen/issues/3712) seems to suggest that installing in-VM isn't supported. To check whether this is the source of my problem, I also tried to install on a proper, non-WSL Ubuntu 18.04 freshly installed - same error.

Is there any known fix for this, or, alternatively, a trusted Docker image I could use?

**Comment by PCanavelli** [comment]
Any update on this?

It looks like you've recently started having the same bug happen in your [CI](https://github.com/bcbio/bcbio-nextgen/actions/runs/9958118168/job/27511732914).

**Comment by lpantano** [comment]
Hi,

I think is related but I don't have an option right now. probably we need to change some versions. Let me see what I find out.

**Comment by PCanavelli** [comment]
Hi @lpantano 

Thank you for your answer. I'll keep trying and let you know if I stumble onto a fix.

Please let me know if there is anything I can do to help.
