### ISSUE TITLE
Sambamba:version `GLIBC_2.7' not found

### ISSUE THREAD

**Issue by nhansen** [bcbio/bcbio-nextgen#715]
I've just installed bcbio-nextgen, and am eager to start processing our data, but when I attempt to run the NA12878 exome example (with NA12878-exome-methodcmp.yaml), it dies with the error below.  We are running Centos5 with glibc2.5, and I see sambamba requires 2.7, so that all makes sense.  But I'm not sure why I need to be running sambamba anyway--is there a way to substitute in samtools instead so I'm not required to find a way to pull in glibc 2.7?

Best,
--Nancy

Here's the error (sorry so long):
[2014-12-30 15:04] samblaster: Inputting from stdin[2014-12-30 15:04] samblaster: Outputting to stdout[2014-12-30 15:04] samblaster: Opening /dev/fd/62 for write.[2014-12-30 15:04] samblaster: Opening /dev/fd/63 for write.[2014-12-30 15:04] /cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/bin/sambamba: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by /cluster/ifs/projects/seqSim/bcbio-nextg
en/bcbio/bin/sambamba)
[2014-12-30 15:04] /cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/bin/sambamba: /lib64/libc.so.6: version`GLIBC_2.7' not found (required by /cluster/ifs/projects/seqSim/bcbio-nextg
en/bcbio/bin/sambamba)
[2014-12-30 15:04] /cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/bin/sambamba: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by /cluster/ifs/projects/seqSim/bcbio-nextg
en/bcbio/bin/sambamba)[2014-12-30 15:06] [M::mem_pestat] skip orientation FF as there are not enough pairs
[2014-12-30 15:06] [M::mem_pestat] analyzing insert size distribution for orientation FR...
[2014-12-30 15:06] [M::mem_pestat](25, 50, 75) percentile: (158, 187, 226)[2014-12-30 15:06] [M::mem_pestat] low and high boundaries for computing mean and std.dev: (22, 362)
[2014-12-30 15:06] [M::mem_pestat] mean and std.dev: (194.21, 51.21)[2014-12-30 15:06] [M::mem_pestat] low and high boundaries for proper pairs: (1, 430)
[2014-12-30 15:06] [M::mem_pestat] analyzing insert size distribution for orientation RF...
[2014-12-30 15:06] [M::mem_pestat](25, 50, 75) percentile: (354, 862, 994)
[2014-12-30 15:06] [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 2274)
[2014-12-30 15:06] [M::mem_pestat] mean and std.dev: (619.60, 371.84)
[2014-12-30 15:06] [M::mem_pestat] low and high boundaries for proper pairs: (1, 2914)
[2014-12-30 15:06] [M::mem_pestat] skip orientation RR as there are not enough pairs
[2014-12-30 15:06] [M::mem_pestat] skip orientation RF
[2014-12-30 15:06] samblaster: Loaded 84 header sequence entries.
[2014-12-30 15:06] samtools: writing to standard output failed: Broken pipe
[2014-12-30 15:06] samtools: error closing standard output: -1
[2014-12-30 15:06] samblaster: Unable to write to output file.
[2014-12-30 15:06] 
[2014-12-30 15:06] [fputs] Broken pipe
[2014-12-30 15:06] samtools: error closing standard output: -1
[2014-12-30 15:06] samtools: error closing standard output: -1
[2014-12-30 15:06] Uncaught exception occurred
Traceback (most recent call last):
  File "/cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/bin/bwa mem -M -t 8  -R '@RG\tID:1\tPL:illumina\tPU:NA12878-1\tSM:NA12878-1' -v 1 /clust
er/ifs/projects/seqSim/bcbio-nextgen/bcbio/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa <(/cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/bin/grabix grab /cluster/ifs/projects/seqSim/bcbio_testanalysis/NA12878-exome-eval/work/align_prep/NA12878-NGv3-LAB1360-A_1.fastq.gz 1 20000000) <(/cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/bin/grabix grab /cluster/ifs/projects/seqSim/bcbio_testanalysis/NA12878-exome-eval/work/align_prep/NA12878-NGv3-LAB1360-A_2.fastq.gz 1 20000000) | /cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/bin/samblaster --splitterFile >(/cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/bin/samtools view -S -u /dev/stdin | /cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/bin/sambamba sort -t 8 -m 682M --tmpdir /cluster/ifs/projects/seqSim/bcbio_testanalysis/NA12878-exome-eval/work/tx/tmpLsNTMF/spl -o /cluster/ifs/projects/seqSim/bcbio_testanalysis/NA12878-exome-eval/work/align/NA12878-1/split/tx/tmpSjLtc5/NA12878-1-sort-1_20000000-sr.bam /dev/stdin) --discordantFile >(/cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/bin/samtools view -S -u /dev/stdin | /cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/bin/sambamba sort -t 8 -m 682M --tmpdir /cluster/ifs/projects/seqSim/bcbio_testanalysis/NA12878-exome-eval/work/tx/tmpLsNTMF/disc -o /cluster/ifs/projects/seqSim/bcbio_testanalysis/NA12878-exome-eval/work/align/NA12878-1/split/tx/tmpwh_D1c/NA12878-1-sort-1_20000000-disc.bam /dev/stdin) | /cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/bin/samtools view -S -u /dev/stdin | /cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/bin/sambamba sort -t 8 -m 682M --tmpdir /cluster/ifs/projects/seqSim/bcbio_testanalysis/NA12878-exome-eval/work/tx/tmpLsNTMF/full -o /cluster/ifs/projects/seqSim/bcbio_testanalysis/NA12878-exome-eval/work/align/NA12878-1/split/tx/tmp6syyYu/NA12878-1-sort-1_20000000.bam /dev/stdin

**Comment by lomereiter** [comment]
Brad,
Thanks for noticing this. 0.5.1 builds (and later) should work on CentOS 5, and I've even added a line `readelf -V $executable | grep 'Name:' | grep GLIBC` to my build script in order to spot any unwanted dependencies immediately.

**Comment by chapmanb** [comment]
Artem;
Thanks much for the quick fix. I updated our builds to use 0.5.1 so we should have the latest and greatest plus CentOS5 compatibility. Thanks again.
